### ISSUE TITLE
Our bad find mode is terribly broken

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1000]
```
:bind / find
/
[anything] " errors about ke.key
```

Presumably broken by #962.

**Comment by dpaetzel** [comment]
I can confirm this. After setting `bind / find`, pressing any key (even if it is a modifier such as Ctrl) results in the following error message:

`# An error occurred in the content controller: TypeError: e.key is undefined ¯\_(ツ)_/¯`

**Comment by lorenzleutgeb** [comment]
I would like to report horrible user experience (for me) when attempting to find text on websites. Maybe consider that going forward for find mode.

Firstly, the README is imprecise and should be clarified to avoid confusing people like me in the future. There are (at least) two "built-in Firefox search"es:
 * "Find" (by default bound to `Ctrl+F`) and 
 * "Quick Find" (by default bound to `/`

I proposed a change at #1033.

Secondly, I want to be able to navigate matches, and so far I am only able to do that with "Find", while "Quick Find" just jumps to the next match and exits.

So my experience with Tridactyl was to press `/` and be sad about seeing "Quick Find". Then, however, my initial reaction was to press `Ctrl-F` to get the better "Find". But that just scrolls the page. Not only is the decent "Find" not invoked by Tridactyl (temporarily, until a better find mode is implemented) but also I cannot access "Find" with a default config.

**Comment by glacambre** [comment]
@lorenzleutgeb With "Quick Find", you can jump from match to match using `<C-g>` and `<C-G>`. This is a default firefox keyboard shortcut.

We agree that Tridactyl isn't very good at finding things for now. We have several pull requests that attempt to fix this (mainly https://github.com/tridactyl/tridactyl/pull/623, which itself depends on https://github.com/tridactyl/tridactyl/pull/932 and https://github.com/tridactyl/tridactyl/pull/973, which is blocked until I can use my powerful computer again to write a Firefox patch to fix some of Firefox's limitations with the optional permissions API).

**Comment by lorenzleutgeb** [comment]
> @lorenzleutgeb With "Quick Find", you can jump from match to match using `<C-g>` and `<C-G>`. This is a default firefox keyboard shortcut.

Thanks, I did not know about these shortcuts.

> We agree that Tridactyl isn't very good at finding things for now. We have several pull requests that attempt to fix this (mainly #623, which itself depends on #932 and #973, which is blocked until I can use my powerful computer again to write a Firefox patch to fix some of Firefox's limitations with the optional permissions API).

Yeah, that's clear and also perfectly fine. I was just trying to make the experience a little more pleasent in the meantime. Thank you for working towards integrating find with Tridactyl!

**Comment by bovine3dom** [comment]
We should remove the ex command until it is fixed because it's just confusing people.

**Comment by ljohnston** [comment]
This is a showstopper for me. I'm just not willing to do the mental gymnastics required to do find differently in my browser than when in vim. I've been using cvim in Chrome while waiting for this feature in tridactyl. I just gave vim-vixen a whirl and it supports find in Firefox as I would expect. It has too many other shortcomings for serious consideration though.

**Comment by bovine3dom** [comment]
@ljohnston if you have the time and the inclination, hop on Matrix and we can work out what exactly is blocking this and where, if anywhere, you might be able to help. I'm personally not too bothered about it, which is partially why it has lasted so long without it getting some.

Plenty of people do happily use Vim Vixen, so it can't be that bad... there's also Qutebrowser that you might want to try.

**Comment by bovine3dom** [comment]
Fixed in #623 - see `:help find` in latest betas (you'll need to allow the new find permission) for instructions on how to bind it again.
