### ISSUE TITLE
autocmd for fullscreen events

### ISSUE THREAD

**Issue by notJerl** [tridactyl/tridactyl#1003]
It'd be nice to be able to set an autocmd for fullscreen events.  My use case would be to auto-hide the mode indicator (and status line, when that gets finished) when the browser goes into fullscreen mode, and restore them on exit, but I can imagine a bunch of different use cases people might have (binding/unbinding certain keys, switching to ignore mode, etc).

**Comment by bovine3dom** [comment]
https://developer.mozilla.org/en-US/docs/Web/Events/fullscreenchange

Probably as simple as shoving an event listener on this and executing matching autocommands; just look at how the other ones are done for a hint - grep for DocStart / TriStart / TabLeft etc.

Happy to help anyone who wants to give this a go.

**Comment by WhiteAbeLincoln** [comment]
Well, I spent way too long trying to debug until I realized the api was still prefixed, but I think #1110 should cover this :)
