### ISSUE TITLE
Installing on a new computer resets config.

### ISSUE THREAD

**Issue by kevincox** [tridactyl/tridactyl#1004]
*   Brief description of the problem: When installing tridactyl on a new computer synced with my Firefox account (including auto-install via sync) settings are reset.

*  Steps to reproduce:
    1. `:bind b back`
    1. Turn on new computer and let tridactyl sync.
    1. Press b on either computer.
    1. Note that it does the default action `tabprev`

*   Tridactyl version (`:version`): 1.14.0-1.14.0

*   Firefox version (Top right menu > Help > About Firefox): Developer edition 63.0b4 (64-bit)

*   URL of the website the bug happens on: N/A

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com): https://gist.github.com/kevincox/ff316446f0ef89e892bcd60a944009ba

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist): None

**Comment by glacambre** [comment]
Hi, thank you for taking the time to report this issue. It's quite a surprising one since `b` is bound to `fillcmdline buffer` by default and not `tabprev`. Are you sure you didn't have a previous installation of Tridactyl on this firefox profile or a tridactylrc?
Have you ever bound `b` to `tabprev` yourself at some point?

**Comment by bovine3dom** [comment]
Firefox beta and stable currently have different storage backends, so it could be an artefact of that: is one of your machines running stable?

That said, I don't think we are particularly careful with how we store stuff in the sync storage. It's plausible that every time the storage is modified, the whole thing gets overwritten and not just the new keys.

**Comment by kevincox** [comment]
No, they are all running developer edition. (It happened when I first synced both other computers).

That is something to keep in mind as I was considering switching to stable.

> It's plausible that every time the storage is modified, the whole thing gets overwritten and not just the new keys.

This looks like the case because I also lost things like search engines and other things and custom mappings that aren't "overwritten".

**Comment by kevincox** [comment]
Of course all mappings appear to be stored in one object. So maybe the entire thing is "synced".

**Comment by bovine3dom** [comment]
I don't know if we can actually fix this but it's probably worth looking into. Thanks for reporting.

**Comment by kevincox** [comment]
If it can't be fixed we should add warnings for users. Having all of your settings get wiped when you add a new device is pretty rough.

**Comment by notJerl** [comment]
I had this issue a few days ago and troubleshot it with Mozilla's sync devs.  It seems to be a quirk about how app syncing works.  They told me to submit a ticket if I experience it again.

**Comment by bovine3dom** [comment]
I'm closing this issue as I believe it is an upstream bug - please file an issue with Bugzilla if you experience it again and add it to #760.
