### ISSUE TITLE
buffer # behaves weirdly in ignore mode

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1011]
Steps to reproduce:

1. have at least three tabs (I guess)
2. put one in ignore mode
3. tab away from it with ctrl-tab
4. press ctrl-6 twice
5. you end up in a different tab to where you started

Have been a bit lazy and not tested these reproduction steps, trying to get some work done...

**Comment by bovine3dom** [comment]
It doesn't just seem to be ignore mode. Does anyone else have this bug?

**Comment by glacambre** [comment]
I tried to reproduce it with both a slow and fast computer and couldn't do it. `composite buffer # ; sleep 10 ; buffer #` didn't work either :/

**Comment by bovine3dom** [comment]
It could have been due to my being on Firefox beta, I suppose. I've downgraded and I'll see if it still happens.

**Comment by glacambre** [comment]
What did you bind `<C-6>` to? It's not bound bound by default in ignore mode.

**Comment by notJerl** [comment]
I haven't bound `<C-6>` to anything.  It appears that it actually is bound by default in ignore mode.  The only ignore mode map I've set at all is `<Insert> = mode normal` to match my muscle memory for Vimperator, yet `set imaps.<C-6>` returns `# imaps.<C-6> = buffer #`.  When it activates in ignore mode, it jumps to a completely unexpected tab.  From what I've experienced, it seems to be the first unpinned tab.

**Comment by glacambre** [comment]
> it appears that <C-6> is a hotkey built in to Firefox to jump to tab 6

Oh, that explains a lot, this hotkey is bound to `<A-6>` when using the keyboard layout I use.

**Comment by bovine3dom** [comment]
And so begins the normal-ignore mode unification...

I think adding this to ignore mode is sound because it _looks_ like it works when you press it (and I also thought I'd added the bind by default).


I suspect it failing to work outside of ignore mode sometimes is just on pages where Tridactyl hadn't loaded properly or somesuch breakage.
