### ISSUE TITLE
Seeming we don't have stop loadings?

### ISSUE THREAD

**Issue by FrankEular** [tridactyl/tridactyl#1018]
I learned that we have reloads (reload, reloadall, reloadhard) but not stop loadings? I can only input Esc (the default keybinding in Firefox) to stop a loading. I searched :help, nothing like :stop is there.

**Comment by bovine3dom** [comment]
Thanks for the report. I've bound it to `x` which I believe was the bind in Pentadactyl.

It will only work after Tridactyl has loaded in the page.

**Comment by bovine3dom** [comment]
If you want, you can add an alias here: https://github.com/tridactyl/tridactyl/blob/master/src/config.ts#L344
`stop: "js window.stop()"`

and then change nmaps.x to `x: stop`.
