### ISSUE TITLE
Keybindings lost in Reader View

### ISSUE THREAD

**Issue by sc68cal** [tridactyl/tridactyl#102]
While reading https://www.redhat.com/archives/libvir-list/2017-November/msg00525.html , I switched over to the Reader View but lost my ability to use `j` and `k` to scroll. :(

**Comment by bovine3dom** [comment]
I don't think we can inject anything onto about:reader pages, so this will have to wait until the keyboard API is in Firefox.

**Comment by bovine3dom** [comment]
Closing in favour of https://github.com/cmcaine/keyboard-api.

**Comment by kwstannard** [comment]
Is there an explanation for how keyboard-api solves this issue anywhere? Google is not helping. Thank you.

**Comment by bovine3dom** [comment]
It doesn't solve it yet - it's more like closing it in favour of another issue.

The idea is to persuade Mozilla to let us listen to key events browser wide and then do stuff with them, such as scrolling down or closing tabs.

If you'd like to help out there's a metabug on Bugzilla of things that need to happen: https://bugzilla.mozilla.org/showdependencytree.cgi?id=1215061&hide_resolved=0

Another option is forking xkeysnail to have mode support. Currently you can use it to bind e.g. Ctrl f to page down but I wouldn't recommend doing it for single keys as you wouldn't be able to type them any more.

**Comment by kwstannard** [comment]
Would it be hard to implement a reader mode owned by tridactyl?

**Comment by bovine3dom** [comment]
It depends what you want. Bundling one with Tridactyl could be easy if premade ones exist.

If you're happy using a third party service, it's already possible, e.g. `bind gr js window.location.href = "https://outline.com/" + window.location.href`.

**Comment by kwstannard** [comment]
Cool. That isn't a bad stopgap. I was looking into it and it seems like there are some JS implementations like this one: https://github.com/luin/readability

**Comment by bovine3dom** [comment]
That'd be pretty easy to bundle. Just need to make a new background page (e.g. look at how `tutor` is done), give that a query string with an encoded URL and then have the background page replace (most of) its HTML with the output of that library.

**Comment by kwstannard** [comment]
@bovine3dom So, I had a little time but I am having difficulty with DOM manipulation. I tried using mozilla/readability lib, but that wasn't doing anything. So I tried debugging by just replacing reader function with the following:

```
export async function reader() {
    document.body.innerText = "hello world";
}
```

This also doesn't do anything, even though it works if I run that inner line in the cmd prompt as 

`:js document.body.innerText = "hello world"`

What am I doing wrong?

**Comment by bovine3dom** [comment]
https://github.com/tridactyl/tridactyl/blob/5412e6ebc74ca40c24137df9d234eae23eb3eb21/src/excmds.ts#L1836

You need to change this to `//#content`.

WebExtensions have two types of script: content scripts, which run inside tabs and have access to a few browser APIs and access to the web page, and a background script which has access to more browser APIs but has no direct access to pages. For `src/excmds.ts` we have a python preprocessor script that registers an ex cmd for each exported function and puts it in the background or content scripts, which is what the magic comment controls.

I'd suggest opening a WIP PR as soon as you are comfortable as it's usually always easier to spot issues directly from the changes themselves.

**Comment by kwstannard** [comment]
Nice! Thank you so much. Let me open a PR. It still doesn't work correctly, but it is doing *something* now.

**Comment by hughwilliams94** [comment]
Did a PR ever come about from this?

**Comment by bovine3dom** [comment]
To include readability - nope : )

I was playing with https://github.com/tridactyl/godmode a few days ago which in theory should let sufficiently intrepid users use Tridactyl in the normal Firefox reader mode, but it didn't immediately work and I lost interest. If you're feeling adventurous you could take a look, but the readability solution would probably help more people.

**Comment by kwstannard** [comment]
https://github.com/kwstannard/tridactyl/pull/2/files

My 3rd kid was born and then I moved cities, so I think I will never get around to finishing it if anyone wants to pick it up.

**Comment by bovine3dom** [comment]
Huh, I have no recollection of that PR. Thanks for the correction!

**Comment by bovine3dom** [comment]
5 and a half years for a bug fix, how's that for a speedy turnaround :)

A new `:reader` command which works with Tridactyl binds will be available whenever the next beta is released.

**Comment by hughwilliams94** [comment]
Thanks, will make sure to try it out!

6 Apr 2023 17:36:56 Oliver Blanthorn ***@***.***>:

**Comment by kwstannard** [comment]
Yessss
