### ISSUE TITLE
Unresponsive tabs

### ISSUE THREAD

**Issue by nvkrishna77** [tridactyl/tridactyl#1021]
<!--

# Reporting a bug / getting help

The following steps lead to the bug:

== Bug 1 ==
1- First Set the option to open empty tab on new tab.

2- Create New window

3- It opens a tab but not a tridactyl tab. Hence cannot use tridactyl commands. Cannot even open an url (I have guiset navbar set to none).

== Bug 2 ==
4- Use Command+t to open a new tab. This one is a tridactyl tab. But I still cannot use tridactyl commands. 
(Quick fix for step-4: Pressing tab-key immediately once after opening the tridactyl tab does the trick though. But if I press Tab-key multiple times the tridactyl tab also becomes unresponsive ).

== Bug 3 ==
On some websites none of the keys work. If tab-key or esc-key is pressed.

 

*   Tridactyl version (`:version`):1.14.0-1.14.0

*   Firefox version (Top right menu > Help > About Firefox):62

```
$ cat ~/.tridactylrc

sanitise tridactyllocal tridactylsync

set csp clobber
quickmark j http://www.j2meforums.com/forum/index.php?board=2.0

bind h back
bind l forward
" bind x tabclose
map e fillcmdline open

set hintchars 4327895610
set hintnames numeric
set hintfiltermode vimperator-reflow
autocontain docs.google.com google
set newtab about:blank

```

**Comment by antonva** [comment]
Could you update this with a description of the problem you're dealing with? It could possibly be related to #804 but who knows?

**Comment by nvkrishna77** [comment]
# Reporting a bug / getting help

The following steps lead to the bug:

== Bug 1 ==
1- First Set the option to open empty tab on new tab.

2- Create New window

3- It opens a tab but not a tridactyl tab. Hence cannot use tridactyl commands. Cannot even open an url (I have guiset navbar set to none).

== Bug 2 ==
4- Use Command+t to open a new tab. This one is a tridactyl tab. But I still cannot use tridactyl commands. 
(Quick fix for step-4: Pressing tab-key immediately once after opening the tridactyl tab does the trick though. But if I press Tab-key multiple times the tridactyl tab also becomes unresponsive ).

== Bug 3 ==
On some websites none of the keys work. If tab-key or esc-key is pressed.

 

*   Tridactyl version (`:version`):1.14.0-1.14.0

*   Firefox version (Top right menu > Help > About Firefox):62

```
$ cat ~/.tridactylrc

sanitise tridactyllocal tridactylsync

set csp clobber
quickmark j http://www.j2meforums.com/forum/index.php?board=2.0

bind h back
bind l forward
" bind x tabclose
map e fillcmdline open

set hintchars 4327895610
set hintnames numeric
set hintfiltermode vimperator-reflow
autocontain docs.google.com google
set newtab about:blank

```

PS: I had given all the description. But that remained within comments, probably. Hope this will show up.

**Comment by antonva** [comment]
1) Using the ff shortcuts to open a new window will do that, using `:winopen` can alleviate this as it loads the tridactyl newtab in the new window (or your url of choice). it's currently bound to `w`

2) Again an unfortunate state of affairs but that's the default firefox behaviour and I'm not aware of any config setting that can be applied to remedy this. Your workaround is the one I'm currently using myself if I need to open a new tab via ^t.

3) This is further documented in #804 and currently the only method of fixing it is hitting escape and in some cases you'd need to reload the tab.

**Comment by bovine3dom** [comment]
Have we actually tried document.focus() on newtab load? It seems optimistic but could work...

**Comment by glacambre** [comment]
>Have we actually tried document.focus() on newtab load?

I think I did and it didn't work.

**Comment by nvkrishna77** [comment]
>     1. Using the ff shortcuts to open a new window will do that, using `:winopen` can alleviate this as it loads the tridactyl newtab in the new window (or your url of choice). it's currently bound to `w`

Even with winopen the issue remains the same. The first tab is the FF tab. The latter ones are tridactyl tabs.

> 
>     2. Again an unfortunate state of affairs but that's the default firefox behaviour and I'm not aware of any config setting that can be applied to remedy this. Your workaround is the one I'm currently using myself if I need to open a new tab via ^t.

I have seen another workaround: Pressing F6, a couple of times seems to fix this issue.

> 
>     3. This is further documented in #804 and currently the only method of fixing it is hitting escape and in some cases you'd need to reload the tab.

Again pressing F6 seems to be helping in some cases.

Thanks. 

Krishna.

**Comment by bovine3dom** [comment]
Unfortunately, @glacambre's fix doesn't work on Windows. It does work on Linux, however.

**Comment by glacambre** [comment]
Are you running the same firefox versions on windows and linux?

**Comment by bovine3dom** [comment]
Yes, FF62.02. Same Tridactyl version - 1.14.0-74-gc451faf - too.

**Comment by bovine3dom** [comment]
`<C-,>` - that's Ctrl-comma - is probably the closest we're going to get to a fix for this for a long time. It gets your focus back to Tridactyl from pretty much anywhere in the browser.
