### ISSUE TITLE
Readme etc could do with some TLC

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1024]
I know we already have an issue for this but I can't find it. :(

**Comment by glacambre** [comment]
https://github.com/tridactyl/tridactyl/issues/162 ?

**Comment by glacambre** [comment]
What's missing from the readme/tutorial/help pages?

**Comment by bovine3dom** [comment]
I think text.*, ex.*, hint.* are all still quite hard to discover - that's not really TLC though.

I'll close this issue as there doesn't seem to be anything horrendously out of date on the readme / AMO.
