### ISSUE TITLE
saving settings to config file error

### ISSUE THREAD

**Issue by irmpow** [tridactyl/tridactyl#1029]
Good day, i have some problem to save settings like

:set hitchars fdsagqwertzxcvb

I suppose that can be bind with write to rules for my firefox. 

I've searched by default hinchars string in my home-dir. The only files i found are sqlite with default hinchars string. rw rights are present for me. firefox are started as me. But problem is that i can't save hintchars string and manually configured (in GUI settings in FF) list of searchengines between FF restart.

**Comment by bovine3dom** [comment]
Hi, thanks for opening this issue. It sounds like a problem with Firefox rather than Tridactyl.

You could try making a new profile and seeing if that fixes it. `firefox -p` IIRC.

**Comment by irmpow** [comment]
Tthat's helped in scope of creating new profile, thanks.
