### ISSUE TITLE
error on gmail: element.attributes is undefined

### ISSUE THREAD

**Issue by holtzermann17** [tridactyl/tridactyl#1031]
On Gmail, when I search for mail and then mouse-over the returned hits, I get an error at the bottom of the screen:

`:# An error occurred in the content controller: TypeError: element.attributes is undefined ¯\_(ツ)_/¯` 

This is true even after adding mail.google.com to the blacklist via `:blacklistadd` per #57.  

I do not get the error when Tridactyl is disabled globally via the Add Ons menu.

*   Tridactyl version (`:version`):
1.14.0

*   Firefox version (Top right menu > Help > About Firefox):

62.0.2

*   URL of the website the bug happens on:

mail.google.com

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

https://gist.github.com/holtzermann17/9b65f36375dc5ae550a93cff164c9b0e

**Comment by gurpreetatwal** [comment]
This also happens on `drive.google.com` when searching for files

**Comment by holtzermann17** [comment]
Thanks, I can confirm that installing the beta fixed this for me, after disabling stable per #1156.
