### ISSUE TITLE
editorcmd="auto" get information from Firefox but does not send it back!

### ISSUE THREAD

**Issue by joaquinlpereyra** [tridactyl/tridactyl#1035]
*   Brief description of the problem:
Pretty much a fresh install of Tridactyl after coming back from Chrome.
editorcmd is on "auto" and correctly opens up Gnome Terminal with vim, as per my `$EDITOR` env-variable.
The vim buffer will have the information which I have already written on the input box. I can write on the vim buffer, but nor saving nor saving+exiting the vim buffer will write the appended text to input box on Firefox.
Works fine if I set `editorcmd=gedit" but if I were a gedit user I would not be using the project :smile:

*   Steps to reproduce:

    1. Go to input box  
    2. Press <Ctrl-I>
    3. Write `example` 
    4. Save, quit
    5. See `example` is not on the input box.

*   Tridactyl version (`:version`): 1.14.0

*   Firefox version (Top right menu > Help > About Firefox): 62

*   URL of the website the bug happens on: Every input box I could find, even Google and Github Search

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com): https://gist.github.com/joaquinlpereyra/77f73a210e360b06ad92d57fd2f0634f

*   Operating system:  Ubuntu 18.04
*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:
```/usr/local/bin:/usr/local/sbin:/home/joaquin/.cargo/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/joaquin/.bin:/home/joaquin/.go/bin:/usr/local/go/bin:/home/joaquin/.npm/gobal/bin:~/.gem/ruby/2.4.0/bin/:/home/joaquin/.rvm/bin:~/.cabal/bin/:/home/joaquin/.grails/grails-2.4.5//bin:/home/joaquin/.scripts/bin/:/home/joaquin/.npm-global/bin/:/home/joaquin/.gem/ruby/2.4.0/bin/:/home/joaquin/.cabal/bin/:/home/joaquin/.rvm/bin```
*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal: ```{"cmd": "run", "content": "/usr/local/bin:/usr/local/sbin:/home/joaquin/.cargo/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/joaquin/.bin:/home/joaquin/.go/bin:/usr/local/go/bin:/home/joaquin/.npm/gobal/bin:~/.gem/ruby/2.4.0/bin/:/home/joaquin/.rvm/bin:~/.cabal/bin/:/home/joaquin/.grails/grails-2.4.5//bin:/home/joaquin/.scripts/bin/:/home/joaquin/.npm-global/bin/:/home/joaquin/.gem/ruby/2.4.0/bin/:/home/joaquin/.cabal/bin/:/home/joaquin/.rvm/bin\n", "code": 0}```

**Comment by joaquinlpereyra** [comment]
Not a solution, but more of a workaround: gvim works fine. Just install `vim-gtk3` (at least if you're on Ubuntu) and then `set editorcmd gvim`. It will work wonders.

**Comment by glacambre** [comment]
When the text shows up in the terminal but isn't copied back in Firefox, the problem is often that the call to the editor is non-blocking. This was the problem here, `auto` selected `gnome-terminal`, which by default is non-blocking. Since @joaquinlpereyra is using Ubuntu, one solution is to give the distro-specific `--disable-factory` flag to gnome-terminal.
Thus, using the following command should fix this issue: `set editorcmd gnome-terminal --disable-factory -- vim`.

The whole debugging process can be found on matrix:
https://view.matrix.org/room/!xmubtggllUtLrQiGyn:matrix.org/?anchor=$15382339723102807GsKhh:matrix.org&offset=-30

**Comment by bovine3dom** [comment]
We should probably remove gnome-terminal from the list `auto` chooses from.

**Comment by heshamsafi** [comment]
same exact issue with terminator

I have 
```
set editorcmd terminator -e 'vim %f'
```
which loads the input from firefox but doesn't save it back
```
set editorcmd gvim
```
works like a charm though.
