### ISSUE TITLE
Don't override default search

### ISSUE THREAD

**Issue by trialism** [tridactyl/tridactyl#1048]
Hi,

 Please, don't override the default search function because the one introduced by tridactyl is just terrible. Thanks!

**Comment by glacambre** [comment]
What do you mean by "default search function"? Do you mean search engines or using the command line instead of the url bar?

If you want to change your search engine you can just use `set searchengine $name_of_search_engine`. The name of the search engine is the key used in the `searchurls` setting you see when running `:viewconfig`.
For example, in `:viewconfig`, you'll see that the `searchurls` object has a `duckduckgo` key which points to a duckduckgo url. So if you want to use duckduckgo as default search engine, use `set searchengine duckduckgo`.
If you want to add new search engines to Tridactyl, you can do so with the following: `:set searchurls.mysearchengine https://search.com/?q=%s`.

Using Firefox's default search engines is planned, see https://github.com/tridactyl/tridactyl/issues/792

**Comment by trialism** [comment]
No: **the search tool** - the one you use to search for *text* on a webpage. The one you'd invoke with `<C-f>`.

**Comment by glacambre** [comment]
Oh, right, sorry. `<C-f>` is bound to page-next in vim/pentadactyl/vimperator so that's why it is overriden. `/` is how you search text in vim/pentadactyl/vimperator and thus also in Tridactyl. If you want to be able to use `<C-f>` again you can run `unbind <C-f>`, which should free it again.

**Comment by bovine3dom** [comment]
Dozens of us prefer the / search. Ctrl G  / Ctrl Shift G cycle results.

Closed as solution was given by glacambre.

**Comment by trialism** [comment]
I'm not talking about the binding: I'm talking about *the way the search works in tridactyl* - it's broken. When pressing `/` use firefox's search tool instead.

**Comment by antonva** [comment]
`/` is a default firefox binding for their own 'Quick Find' feature. There's nothing we did involved in that process. It's the same functionality on the same key, with or without tridactyl installed.

We plan on introducing our own find mode at one point but it's blocked by a number of rewrites that need to happen first.

If you detailed how you feel the current firefox feature is broken maybe we could help you. It seems to be working for most of us.

**Comment by glacambre** [comment]
>it's broken

Are you sure you didn't bind `/` to use Tridactyl's broken find mode? You can make sure by using `bind /` in order to see if anything's bound to it and `unbind /` in order to remove the binding.

**Comment by trialism** [comment]
@antonva I think the 'Quick Find' feature shouldn't be the default for `/` since it's more like `search()` in vim.
@glacambre I didn't change any binding.

**Comment by glacambre** [comment]
>I think the 'Quick Find' feature shouldn't be the default for /

Unfortunately we have no control over that, this is a Firefox binding and we can't change these.

>I didn't change any binding.

Then `/` really shouldn't be broken, or if it is, you should report that to mozilla on bugzilla.mozilla.org.

**Comment by trialism** [comment]
@trialism That's unfortunate. Btw, by "broken" I meant that it can only search for the first match which's not practical.

**Comment by glacambre** [comment]
I'm not sure I understand what you mean by "only search for the first match", do you mean you can't jump from match to match? Because that's absolutely possible by using `<C-g>` and `<C-G>`.

**Comment by trialism** [comment]
Why those? Why not `n` and `N`?

**Comment by antonva** [comment]
Because those are the keybinds presented by FF. We have no control over it. Once we have our own (working) find mode, it will replace Quick Find as the functionality bound to `/` and it will accept `n` and `N`. Until then we are working with what FF gives us.

**Comment by funnydman** [comment]
@ghost three years passed. The future hasn't arrived yet(

**Comment by bovine3dom** [comment]
@funnydman have you seen `:help find`? We have a find mode that pretty much works and you can use n/N with it (if you bind it).

It isn't bound by default because we don't have `incsearch` in that mode yet. The Firefox one does and I personally value that more than the n/N keybinds : )

**Comment by funnydman** [comment]
@bovine3dom yes, in the end, I started to use find mode. Thanks!
