### ISSUE TITLE
horizontal scrolling past the edge of a page snaps vertically

### ISSUE THREAD

**Issue by majuscule** [tridactyl/tridactyl#1056]
Horizontal scrolling snaps the page back to the top vertically after reaching an edge. Expected behaviour is to do nothing once reaching the edge of a page.
    
*   Steps to reproduce:

    1. scroll partially down any page that is wider than your browser window
    2. press `h` or `l` until you reach the edge of the page, then press again (or just hold the key)

*   Tridactyl version (`:version`): 1.14.0-1.14.0

**Comment by glacambre** [comment]
Hi, thank you for reporting this issue. This bug has been fixed yesterday, so upgrading to the betas should make it disappear :)

**Comment by glacambre** [comment]
Warning: we just found out that the betas are pretty broken when it comes to the command line settings completions. I've opened a PR to fix it but if you haven't upgraded to the betas yet I'd recommend waiting for the PR to be merged.

**Comment by glacambre** [comment]
Problem fixed, feel free to update :)
