### ISSUE TITLE
`tri` seems to be missing on `jsb`

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1063]
`jsb console.log(tri) // <unavailable> appears in the Browser Console`.

I noticed because I was trying to suggest that #57 could be solved easily with

```
jsb Object.keys(tri.config.get("nmaps")).map(x=>tri.excmds.unbindurl("site.com", x))
```

but tri.excmds is empty.

**Comment by glacambre** [comment]
Works fine for me on ff62-Linux-Tridactyl1.14.0-139-g86ddc36.

**Comment by bovine3dom** [comment]
Oh, nice, it looks like it's specific to Windows (or my Window install). I can't reproduce on Linux.

**Comment by bovine3dom** [comment]
@Rummskartoffel does this bug still exist?

**Comment by Rummskartoffel** [comment]
I tried `:jsb console.log(tri)` and it looked normal in the background debugger. All the members appear to be present.
Tridactyl 1.20.4pre5114-757d6578, Firefox 84.0.2
