### ISSUE TITLE
nativegate doesn't catch all errors

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1071]
If you install the native messenger and just delete the python script (i.e, leaving the manifest alone), nativegate leaks the following error:

`File at path "/home/olie/.local/share/tridactyl/native_main.py" does not exist, or is not executable`

Removing the manifest gives you:

`No such native application tridactyl`

... so, generally, this seems remarkably un-robust.

---

These errors discovered while trying to gate off exclaim.

**Comment by glacambre** [comment]
Nativegate now returns pretty readable error messages.
