### ISSUE TITLE
allow for stateless interaction with tridactyl

### ISSUE THREAD

**Issue by zach-nervana** [tridactyl/tridactyl#1079]
i use talonvoice to control my computer by voice, which allows me to bind custom phrases to keyboard presses. Tridactyl makes it possible for me to control a lot more of firefox by voice than i would otherwise. One thing that would be nice as if there was a keyboard shortcut which forced tridactyl into normal mode. this way i can have a voice command trigger something like: `<normal mode>:tabopen -c personal<enter>`. As it stands now, i need to always check what mode i am in before triggering the keypresses above. I know it is a different use case then Tridactyl was likely designed for, but this seems like a minor request which would benefit of this use case well. I imagine other users who are automating various processes would also benefit from this feature.

**Comment by antonva** [comment]
This is most certainly an intriguing use case.

 I'm wondering if it's not possible to use our current tools to get what you want out of the extension though. Instead of creating a bind directly to the command you could use `composite` and `mode` in your binds to create something like `:composite mode normal;  tabopen -c personal`.

This would ensure that you're always in the intended mode for the phrase you're using.  If I'm missing the point here please let me know.

**Comment by zach-nervana** [comment]
that would be great if there was already a way to do this.

i may be misunderstanding, but in the solution you provide, the first keypress is still `:` which will only activate if the mode is already normal. The problem is if i am in ignore mode so i can interact with the website key bindings directly, i have to make sure to switch back to normal mode before entering the first `:`.

**Comment by zach-nervana** [comment]
alternatively, i can try to just always immediately switch back to normal mode after interacting with a website directly in ignore mode.

**Comment by antonva** [comment]
Ah I see what you mean. 

You could define your own set of binds in `ignoremaps` and any other modes and use that bind.  `:set ignoremaps.<C-]> fillcmdline_notrail` would bind `Ctrl-]` to opening the commandline in ignore mode for instance.

@bovine3dom @glacambre any thoughts on this?

**Comment by zach-nervana** [comment]
nice, that sounds like it would work well, thanks

**Comment by bovine3dom** [comment]
`bind --mode=ignore <Esc> composite unfocus | mode ignore`?

I can't think of any other mode where escape doesn't take you to ignore mode.

**Comment by zach-nervana** [comment]
that is nice and intuitive, thanks.

**Comment by bovine3dom** [comment]
Great! Closing this issue, then. Feel free to bump it if you need anything else. Thanks.
