### ISSUE TITLE
tabnext, tabprev, tabnext_gt, etc should only cycle to non-hidden tabs

### ISSUE THREAD

**Issue by notJerl** [tridactyl/tridactyl#1084]
Currently, these commands will cycle through any tabs at all in what apparently is the order of their ID, even if they've been hidden.  This can be pretty jarring if you're using an extension that takes advantage of tab hiding, since suddenly the tab isn't hidden any more.  With Simple Tab Groups, it even jumps you to a completely different tab group, hiding all the other tabs you have open (including, often, the one you were actually trying to access).

**Comment by antonva** [comment]
Is Simple Tab Groups the extension you're currently using? I'll need to take a look at a few of these to get a feel for the use case here.

This should probably live behind a config option  but should be a pretty straightforward fix.

**Comment by notJerl** [comment]
Yes, Simple Tab Groups.

**Comment by antonva** [comment]
I've come up with a rudimentary fix for this, I need to figure out how to fix an edge case in `tab{next,prev,etc}` and `:buffer` would only show currently visible tabs as well.
 
This would have no effect on a user not using hidden tabs but I assume is something people would want if they're hiding their tabs anyhow. `:bufferall` will still show hidden tabs.

This is blocked until we can get updated types into web-ext-types via  [https://github.com/kelseasy/web-ext-types/pull/73](https://github.com/kelseasy/web-ext-types/pull/73)

**Comment by bovine3dom** [comment]
You can inline the types [here](https://github.com/tridactyl/tridactyl/blob/master/src/tridactyl.d.ts) if you want, azk.

**Comment by antonva** [comment]
I might just do that @bovine3dom 

At least it can stay there until the stuff is in web-ext-types.

**Comment by notJerl** [comment]
Thank you.  `:buffer` showing tabs from all groups is how Vimperator handled it, but I can see why someone might want to just see non-hidden tabs as well, especially if it won't be possible to actually sort it by group, so having the option to bind whichever is more useful to whoever's using it is nice.

**Comment by davidsierradz** [comment]
Hi, is there a way to use the previous functionality? (I know, I know, sorry... [relevant xkcd](https://xkcd.com/1172/)), I am using TreeStyleTabs shortcuts to cycle through non-hidden buffers/tabs and tridactyl shortcuts to cycle through all buffers/tabs.

Also when I open `:tab ` command, I am still viewing all buffers/tabs (hidden and no hidden), is this a bug?

thanks!

**Comment by bovine3dom** [comment]
First part:

`command tabprev jsb ` and then something like the first red bit. You'll need to replace browser with tri.browser https://github.com/tridactyl/tridactyl/pull/1150

Second part :woman_shrugging:
