### ISSUE TITLE
Can I automatically select the first search result? ("feeling lucky" kind of functionality)

### ISSUE THREAD

**Issue by liviu-** [tridactyl/tridactyl#1087]
Often, when I search something I'm pretty sure I'll just want the first Google result, but the hints are not the same between searches.

Is there a way to search and automatically choose the first result from the engine?

**Comment by bovine3dom** [comment]
`set searchurls.lucky https://www.google.com/search?btnI=I'm+Feeling+Lucky&q=%s`
`open lucky test` etc

Does that solve your problem?

**Comment by liviu-** [comment]
Yes, thank you!

**Comment by bovine3dom** [comment]
It's probably reasonable to add this to searchurls. In fact I thought I had done as googlelucky. Reopening to remind me to investigate.
