### ISSUE TITLE
Will anyone get upset if I unbind I in ignore mode?

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1096]
Currently, it leaves ignore mode.

I suspect that most people will want to be able to type capital I's in ignore mode.

I _think_ the only reason it is there is because we didn't support fancy keys like Insert at the beginning, and I unbound it once that was fixed, and people got a bit sad, so I rebound it again.

I think I'd like to unbind it again.

Should we also unbind it in the other modes?

Feedback wanted.

**Comment by antonva** [comment]
Should be fine to unbind it.

**Comment by cmcaine** [comment]
So long as we note it visibly on the new tab page for a little while I'm
cool with it.

Tell people how to bind it themselves.
