### ISSUE TITLE
Directories on MaCOS?

### ISSUE THREAD

**Issue by nedludd** [tridactyl/tridactyl#1097]
Trying to run a custom colorscheme on MacOS.  

Tridactyl looks for it in "~/themes"

Shouldn't this be in "~/.config/tridactyl/themes"?

**Comment by glacambre** [comment]
It looks for it in the directory where your tridactylrc is (https://github.com/tridactyl/tridactyl/blob/42384cf0a72a07368886fe9401b496f1823d8d72/src/excmds.ts#L756) and will only default to ~ if you don't have a tridactylrc in your XDG_CONFIG_DIR or ~/.config/tridactyl dir (https://github.com/tridactyl/tridactyl/blob/42384cf0a72a07368886fe9401b496f1823d8d72/native/native_main.py#L85).

**Comment by nedludd** [comment]
Perfect!  Thanks!

**Comment by bovine3dom** [comment]
I think we should probably default to .config/tridactyl/themes.

~/themes is a bit too generic. Maybe ~/.tridactylthemes/? I haven't thought about this a great deal.

**Comment by nedludd** [comment]
This doesn't seem to work.  I moved my `.tridactylrc` file into `~/.config/tridactyl`, and moved my custom theme into `~/.config/tridactyl/themes/`, but I get this when I try and load it:

```
# background_controller:  Error: getrcpath error: Path not found 
```

**Comment by glacambre** [comment]
Did you rename ".tridactylrc" to "tridactylrc"?

**Comment by nedludd** [comment]
D'oh, that was it.  Thanks.
