### ISSUE TITLE
Unresponsiveness/crashing when scrolling at the end of any website when using smoothscroll

### ISSUE THREAD

**Issue by devsnd** [tridactyl/tridactyl#1101]
*   Brief description of the problem:

When I open any website and use j/k to scroll at the end of the page, the add-on or even the whole browser becomes unresponsive and takes 100% CPU.

*   Steps to reproduce:

    0. enable smoothscroll `:set smoothscroll true`
    1. Open any website
    2. Scroll to the top
    3. Press and HOLD `k` to scroll up further (1s is enough to show the effect on my laptop, the longer you press the more it is visible)
    4. Try to perform any other action afterwards, the add-on and/or browser will not respond anymore

*   Tridactyl version (`:version`):
Tridactyl 1.14.0-206-gb0f6306

*   Firefox version (Top right menu > Help > About Firefox):
62.0.3 (64-bit)

*   URL of the website the bug happens on:
Any, e.g. https://nullprogram.com/blog/2018/09/20/

**Comment by glacambre** [comment]
Hi, thank you for opening this issue. I think this bug might be a duplicate of https://github.com/tridactyl/tridactyl/issues/777 . Does this only happen when `smoothscroll` is set to `true`?

**Comment by devsnd** [comment]
oops, it seems it is a duplicate if #777, and it only happens with smoothscroll, yes.
