### ISSUE TITLE
Native error messages are still useless sometimes

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1102]
1. Delete native messenger (easiest way is to delete ~/.mozilla/native-messaging-hosts/tridactyl*)
2. `restart` in Tridactyl
3. `# background_controller:  Error: Attempt to postMessage on disconnected port `

This is probably a duplicate issue, but I keep forgetting to look into this so more can't hurt much.

**Comment by glacambre** [comment]
This has been accidentally fixed in #1153.
