### ISSUE TITLE
Broken links in :help guiset

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#1104]
Broken lby #1039. Just a matter of updating them.

We should probably make sure we don't have any other broken links. Maybe there's a way to do that automatically?

**Comment by adouzzy** [comment]
+1
`Firefox can’t find the file at moz-extension://2faa8ea6-62cc-40ce-964d-fe1e61b0db8e/static/docs/modules/_excmds_.html#`

**Comment by glacambre** [comment]
adouzzy: The link you gave is correct and should result in displaying the main help page. How did you trigger this error?
