### ISSUE TITLE
Shift+F doesn't open links in new tab in Waterfox

### ISSUE THREAD

**Issue by radio-van** [tridactyl/tridactyl#1118]
*   Brief description of the problem:
Shift+F opens links in the same tab instead of new tab.

*   Steps to reproduce:

    <shift_down> F <shift_up> <letter>

*   :Tridactyl version: 1.14.1-1.14.1

*   Firefox version: Waterfox 56.2.3 (64-bit)

*   URL of the website the bug happens on: seems like any, I've tried DuckDuckGo, Github, Wikipedia, etc...

*   Config: default config hasn't been changed

`t` and  `:tabnew` are able to create new tabs. VimFx plugin doesn't have such problem. Also I looked up the source code and see that hint mode opens links via `DOM.simulateClick`, when I'm clicking on links with a left mouse button, they are opened in the same tab too. Maybe it's just a Waterfox issue?

**Comment by bovine3dom** [comment]
It could be https://github.com/tridactyl/tridactyl/issues/760#issuecomment-433679201. Could you try `:hint -b` and see if it works?

If you have no luck with that, could you provide some logs? https://github.com/tridactyl/tridactyl/blob/master/doc/troubleshooting.md#user-content-getting-logging-information

Thanks.

**Comment by radio-van** [comment]
@bovine3dom in my Waterfox config `privacy.resistFingerprinting` is `false`, anyway the bug presents both if the option is `true` or `false`.
I set `hinting:DEBUG` and figured out that there is a conflict with **Browsec** extension:
```
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  ExtensionUtils.jsm:547:50
Error: WebExtension context not found! ExtensionParent.jsm:778:13
[30, 09:37:16], browser.runtime.onMessage, {"type":"date","url":"https://github.com/tridactyl/tridactyl"}, {"id":"browsec@browsec.com","frameId":0,"url":"https://github.com/tridactyl/tridactyl","extensionId":"browsec@browsec.com","contextId":"1382-1","tab":{"id":17,"index":4,"windowId":3,"highlighted":true,"active":true,"pinned":false,"status":"loading","incognito":false,"width":958,"height":999,"lastAccessed":-----,"audible":false,"mutedInfo":{"muted":false},"url":"https://github.com/tridactyl/tridactyl","title":"github.com/tridactyl/tridactyl"}}
```
However, disabling extension didn't solve the problem, opening links from **DuckDuckGo** still doesn't create new tabs. The only connected error I see is
```
TypeError: browserBg.tabs is undefined  content.js:14760:5
```
I've enabled DEBUG for all components, here is the log:
```
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  ExtensionUtils.jsm:547:50
Error: WebExtension context not found! ExtensionParent.jsm:778:13
ReferenceError: PerformanceObserver is not defined  content.js:15102:11
Error: WebExtension context not found! ExtensionParent.jsm:778:13
ReferenceError: PerformanceObserver is not defined
```

**Comment by bovine3dom** [comment]
> ReferenceError: PerformanceObserver is not defined  content.js:15102:11

Ah, this could be a symptom of us only supporting Firefox stable due to time and sanity constraints.

Could you try the oldest version of Tridactyl from https://tridactyl.cmcaine.co.uk/betas/ and see if the issue persists? I suspect it broke when we added the performance monitoring.

**Comment by radio-van** [comment]
@bovine3dom I've tried 'tridactyl-1.10.0pre956-an+fx.xpi' (the oldest one), but no luck. The only error in log is
```
Error: WebExtension context not found! ExtensionParent.jsm:778:13
```

**Comment by bovine3dom** [comment]
Closing for same reasons as those detailed in #1282.

**Comment by chocolateboy** [comment]
FYI: the workaround mentioned [here](https://github.com/tridactyl/tridactyl/issues/854#issuecomment-407700856) works for me.
