### ISSUE TITLE
blacklistadd

### ISSUE THREAD

**Issue by GianniGi** [tridactyl/tridactyl#1119]
*   Brief description of the problem:
I'm trying to disable tridactyl on some websistes, like gmail.com (mail.google.com), but it continues to work anyway.

*   Steps to reproduce:

:blacklistadd domain
:set blacklistadd domain

*   Tridactyl version (`:version`):
1.14.1-1.14.1

*   Firefox version (Top right menu > Help > About Firefox):
63

*   URL of the website the bug happens on:
gmail.com
mail.google.com

**Comment by bovine3dom** [comment]
It works fine for me.

`:set blacklistadd domain` is incorrect syntax.

Please could you provide us with your configuration when you are on mail.google.com? Copy `:viewconfig` and put it on hastebin etc.

**Comment by GianniGi** [comment]
sometimes it gives the error:
# An error occurred in the content controller: TypeError: element.attributes is undefined ¯\_(ツ)_/¯ 

even if the site is blacklisted ¯\_(ツ)_/¯

**Comment by stevenbell** [comment]
I also get the error in Gmail.  It happens when I type something in the search bar then then try to select something from the drop-down (without hitting enter).  The drop-down disappears, and Tridactl shows the error message GianniGi posted.

**Comment by antonva** [comment]
This was fixed in #1136 which is at least in the betas, not sure if it's in any release. Which version are you on @stevenbell

**Comment by GianniGi** [comment]
how do I remove a site from blacklistadd?

**Comment by bovine3dom** [comment]
`set normal url` won't do anything.

If you go on `help blacklistadd`, I believe it tells you which commands it executes. You'll just need to remove those autocmds. I think the only way is `unset autocmds`, but I'm away from my PC so I can't really check.

**Comment by glacambre** [comment]
You can also use `jsb tri.config.unset("autocmds", "DocStart", "www.url.com")` in order to remove autocmds for a specific url I believe.

**Comment by GianniGi** [comment]
one of your suggestion worked (not sure about which), thanks

**Comment by Flimm** [comment]
To do disable Tridactyl on a website, press <kbd>:</kbd> and type `blacklistadd example.com` using the domain that you won't to blacklist.
