### ISSUE TITLE
winopen should support containers

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1126]
I get sad every time I do `winopen -c emacs` and it doesn't work : (

**Comment by bovine3dom** [comment]
What's wrong with tabopen | tabdetach?

**Comment by antonva** [comment]
It'd open a new tab but before switching to it, it'd pop out your current tab to a new window?

**Comment by bovine3dom** [comment]
`composite tabopen -c Personal news.bbc.co.uk | sleep 100 | tabdetach` seems to work fine.

**Comment by caputchinefrobles** [comment]
That's how I address this today. Never had an issue.. just a bit slow, but not enough to bother...

**Comment by antonva** [comment]
@bovine3dom So what do you want to do here? an exalias? Something better?

**Comment by bovine3dom** [comment]
> Something better?

Yeah. I'd just hack a -c detector into `winopen` and then call composite().
