### ISSUE TITLE
Add undo completions

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#1127]
I want to be able to do `:undo tabid` in order to restore a specific tab which might not be the last one I closed. Matching on tab titles/urls might be unnecessary/hard to implement depending on what happens with #1125 .

**Comment by antonva** [comment]
I'm all for it, but I wouldn't want to add a completion to `u` or `U`, I feel like that should be a one-op.

**Comment by glacambre** [comment]
Absolutely, it should probably be left unbound by default

**Comment by MilanV** [comment]
I think this will be a really useful feature. Plus a Tab-completion for :undo arguments showing a list of closed tabs (plus window). Same as what FF shows you when you click on the "Back" button and get a list of closed tabs. Or as Pentadactyl did.
