### ISSUE TITLE
User defined bind overlaped by new default bind

### ISSUE THREAD

**Issue by caputchinefrobles** [tridactyl/tridactyl#1130]
*   Brief description of the problem:

User defined binding on "x" key being overwritten by the new default bind for alias "stop". 
Already reported on riot/matrix and fixed with `unbind x` command. 

*   Tridactyl version (`:version`): 1.14.1
*   Firefox version (Top right menu > Help > About Firefox): 63.0.1

**Comment by bovine3dom** [comment]
For clarity - the binds you had that were overwritten were `x` followed by some other keys, such as `xo`, IIRC.

I suggested that Tridactyl should prioritise any user binds over default binds.

I am not sure how often this issue will crop up as it is unlikely that we will add new single character binds very often.

**Comment by bovine3dom** [comment]
Closing this as we're not going to add new single-character binds very often; I don't think it's worth the effort.
