### ISSUE TITLE
README not complete: How to buy you coffee and beer?

### ISSUE THREAD

**Issue by mraenker** [tridactyl/tridactyl#1137]
Hey there, lovely devs,
two hours ago I stumbled upon this extension and I am simply blown away. This is the single most useful, value-adding and supporting program I've came across for _years_. I'm completely stoked.

I read thru the README but couldn't find any possibilty to send you some money for your outstanding work. Is there a possibility? I really would like to.

This is incredible work.

Thank you!

**Comment by bovine3dom** [comment]
Thanks, I'm really glad you like it. It wasn't our idea  - Conkeror, Vimperator, Pentadactyl, Vimium all did it first.

The trouble with donations is that we have about 3-5 core contributors who do more or less equal amounts of work and it wouldn't be clear how to distribute it. Number of commits in the last month with some floor might work I guess but I'd have an unfair advantage as I get commits every time I merge other people's work.

I guess we could set up on Open Collective and see how it goes.

Slightly related: I do need to stick #676 on the readme and maybe somewhere in the extension. The t-shirts are actually pretty cool.

**Comment by mraenker** [comment]
yeah the floor idea might work. and/or you could multiply the merge-commits by a factor smaller than 1 (one that seems acceptable for all of you), since it is true, that this is an advantage, but it is also true that it does not take _no time_.

i'd happy to send you some money.
