### ISSUE TITLE
`Esc` no longer closes the command window with 1.14.1 on Android

### ISSUE THREAD

**Issue by robsmith11** [tridactyl/tridactyl#1138]
As I mentioned in #1092 while testing betas, there has been a regression where it is no longer possible to close the command window by pressing `Esc`.

For example, with a default configuration of `1.14.1` on Firefox Nightly for Android 8.1, I can open the command window by pressing `o`, but if I attempt to close it by pressing `Esc`, it remains open with just a colon and the blinking cursor visible.

**Comment by glacambre** [comment]
Hi, thanks for reporting this issue (again :p). We have a PR open that will change the way input is handled in the command line (https://github.com/tridactyl/tridactyl/pull/1123), it might fix your problem (or not).

**Comment by bovine3dom** [comment]
Closing this issue as hopefully `strict_min_version` will help us prevent these things.
