### ISSUE TITLE
gmail.com error: "An error occurred in the content controller:...."

### ISSUE THREAD

**Issue by GianniGi** [tridactyl/tridactyl#1139]
*   Brief description of the problem:
When I visit some google sites, for example gmail, I get this error, even if tridactyl is disabled on that site via blacklistadd:

`# An error occurred in the content controller: TypeError: element.attributes is undefined ¯\_(ツ)_/¯ `

*   Tridactyl version (`:version`):
1.14.1-1.14.1

*   Firefox version (Top right menu > Help > About Firefox):
63.0

*   URL of the website the bug happens on:
gmail.com

**Comment by antonva** [comment]
This is reported in #1031 and is fixed in #1136

**Comment by bovine3dom** [comment]
#1136 merged so closing this. Give it a few minutes and then hopefully it will be fixed in the latest betas.
