### ISSUE TITLE
Problems with mode

### ISSUE THREAD

**Issue by cmcaine** [tridactyl/tridactyl#114]
- mode is global so entering hint mode on one tab, changing tab with ctrl-tab breaks stuff
- if you enter hint mode quickly enough, the mode changes back to normal on page load and the hints cannot be deleted
- probably more

Fix by making state tab-local.

Workaround is probably to just test if mode == hint, because that's the most common problem.

**Comment by bovine3dom** [comment]
Mode has been tab-local for a while now
