### ISSUE TITLE
Tridactyl breaks gitlab

### ISSUE THREAD

**Issue by linges** [tridactyl/tridactyl#1145]
Reproduce:
1. Open https://gitlab.com/gitlab-org/release/tasks/merge_requests/53
2. Reload
3. Notice how some elements in the main body are gone
The dev tools reports: "NS_ERROR_FILE_CORRUPTED: "
`localStorage.clear()` fixes the problem for one reload, then its broken again

*   Tridactyl version: 1.14.1pre2078

*   Firefox version: 63.0

*   URL of the website the bug happens on: https://gitlab.com/gitlab-org/release/tasks/merge_requests/53

**Comment by antonva** [comment]
I cannot reproduce this on `1.14.1-42-g7f034a1` (1.14.1pre2078). Can you try reproducing this on a new profile?

Alternatively, which elements are missing? I tried viewing that page both signed in and not and saw no change.

**Comment by linges** [comment]
Bug does not happen on a new profile. Disabling all addons and restarting fixes the bug, activating tridactly triggers the bug again but so does turning on uBlock. My bad! This seems to be a bug unique to my instance and addons in general.
