### ISSUE TITLE
Help's broken again

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1149]
I did `git clean -fxd` on the build bot but it didn't fix it.

: (

**Comment by cmcaine** [comment]
I can have a quick look in a few hours if you like. Otherwise busy till
wednesday afternoon.

**Comment by bovine3dom** [comment]
That would be helpful, thanks.

**Comment by glacambre** [comment]
Current, broken urls: `static/docs/modules/_excmds_.html#`
New, correct urls: `static/docs/modules/_src_excmds_.html`

Could the build bot be running a different TypeDoc version than the one we're using to dev Tridactyl?

**Comment by antonva** [comment]
Isn't it a matter of it running TypeDoc from the tridactyl root directory instead of inside `tridactyl/src/` ?

**Comment by cmcaine** [comment]
Nah. I logged in and just ran `npm run build` and got the right results.

Typedoc will only generate the _src_ bit if there's any code outside of
_src_ it needs to make docs for. On the buildbot I've only got _src_ and
_compiler_

**Comment by bovine3dom** [comment]
So how is it different? My local builds had the URLs working.

**Comment by cmcaine** [comment]
I get the same results on laptop and buildbot. Maybe a race where
.metadata.generated.ts wasn't created in time?

Looks like build.sh tries to avoid that, though.

**Comment by glacambre** [comment]
Might be that TypeDoc doesn't try to generate documentation if files haven't changed since its last build? This would explain why this problem happened before and mysteriously disappeared.

In any case, one possibly simple solution could be to make sure that TypeDoc only generates documentation for the `src/` directory.

**Comment by bovine3dom** [comment]
> This would explain why this problem happened before and mysteriously disappeared.

I don't think it was too mysterious - I just ran `git clean -fxd` and it fixed it that time. It didn't fix it this time hence the puzzlement. : (
