### ISSUE TITLE
Investigate about:sync extension

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#1161]
[This extension](https://addons.mozilla.org/en-US/firefox/addon/about-sync/?src=search) is able to interact with Firefox sync. Not sure what it can do or how it does it but we might be able to steal their code in order to provide sync features in Tridactyl with no extra permissions.

Related issue: https://github.com/tridactyl/tridactyl/issues/908

**Comment by bovine3dom** [comment]
Link to repo to save me a click in the future: https://github.com/mhammond/aboutsync

**Comment by bovine3dom** [comment]
Ah, glacambre, it's simple: it's includes a WebExtension experiment, so he can just do whatever he wants.

We could adopt a similar approach where we have a Tridactyl: Hacker edition that only supports nightly (but I don't want to run nightly).

**Comment by glacambre** [comment]
Thanks for looking into it :). I still have ideas for ff sync support in tridactyl (either by compiling https://github.com/mozilla/application-services to WASM or by using it as a library in the native messenger/a separate binary). I'll probably work on them once we're done with Tridactyl V2 :p.
