### ISSUE TITLE
Erratic freezes of Firefox after upgrading from FF 62.0 to 63.0 (and 63.0.3)

### ISSUE THREAD

**Issue by lmoellendorf** [tridactyl/tridactyl#1184]
*   Brief description of the problem:

After upgrading  from FF 62.0 to 63.0 (and later to 63.0.3) Firefox freezes erratically.

By freezing I mean, that the Firefox window is not responding any more and CPU usage goes up to 100%. Firefox can only be closed by killing (SIGTERM).

These  actions had no effect on the freezes:

- using a new profile
- turning off all addons but tridactyl

The freezes did not occur while tridactyl had been turned off. 

*   Steps to reproduce:

Use Firefox with tridactyl turned on until it freezes.

*   Tridactyl version (`:version`):

1.14.1-79-gcda87cd

*   Firefox version (Top right menu > Help > About Firefox):

 63.0.3 (64-bit)

*   URL of the website the bug happens on:

any

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

https://gist.github.com/lmoellendorf/b45fbef1740b320fcf292b1aee124594

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

I have none

*   Operating system:

GNU/Linux 4.14.78-gentoo x86_64

*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:

```/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib64/subversion/bin```

*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:

```{"cmd": "run", "content": "/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib64/subversion/bin:/home/lars.moellendorf/bin:/home/lars.moellendorf/.gem/ruby/2.3.0/bin/\n", "code": 0}```

**Comment by bovine3dom** [comment]
Thanks for filing this issue. It's going to be a challenge to reproduce, I think.

How frequent is the freezing? What kind of hardware are you experiencing this on?

Can you give us an example of the kind of page it freezes on? Are they complex pages such as Facebook, YouTube et al., or something simple like Hacker News?

**Comment by antonva** [comment]
@lmoellendorf  You mentioned something on irc about it happening when using search, was that just coincidence or is that something you still observe?

**Comment by glacambre** [comment]
How many tabs do you usually have open?

**Comment by lmoellendorf** [comment]
> How many tabs do you usually have open?

Up to 40.

**Comment by glacambre** [comment]
Maybe Tridactyl eats too much RAM and Firefox periodically tries to GC some of it.

**Comment by lmoellendorf** [comment]
> Could you try to spend a day with <10 tabs open and see if the bug still happens?

I'll try.

FYI:
It froze again while I have been closing ~30 tabs. It froze in the moment I clicked the star icon in the address bar to bookmark http://www.catb.org/esr/structure-packing/, a website without JS. FF froze just before the bookmarking drop down menu should have been appearing.

(TODO: learn how to use bookmarks with tridactyl ;) )

**Comment by bovine3dom** [comment]
Feel free to re-open this if it re-appears and you reckon it's our fault : )
