### ISSUE TITLE
Add a setting for Tridactyl to not allow hotkey overriding for pages by default

### ISSUE THREAD

**Issue by WorldCodeCentral** [tridactyl/tridactyl#1185]
Currently websites can override both Firefox's and Tridactyl's keyboard shortcuts like ctrl+F. By hitting ctrl+i and going to the tab permissions you can forbid pages to override Firefox's shortcuts.

It would be very useful to change the default behaviour for shortcuts to Firefox's or Tridactyl's shortcuts, instead of the ones of the page you're on. Which can be surprising and not desired.

Thanks!

**Comment by bovine3dom** [comment]
Should be an easy extension to `leavegithubalone` if anyone's interested.

**Comment by glacambre** [comment]
We should also define leavegithubalone in config.ts while we're at it, otherwise users won't be able to find it in `:set` completions.

**Comment by bovine3dom** [comment]
I'm imagining `blacklistkeys` as an array of key-sequences, each of which we run the noleavegithubalone code for, and then recommend people use `seturl` with it.

This is distinct from binding it to a Tridactyl no-op as it allows Firefox binds to run.
