### ISSUE TITLE
Tridactyl not working on moz-extension pages

### ISSUE THREAD

**Issue by makkanx** [tridactyl/tridactyl#1189]
*   Brief description of the problem:
Tridactyl not working on moz-extension pages. I have found that Tridactyl will not work on some pages but nothing about moz-extension pages.

*   Steps to reproduce:
1. Install tree style tabs
2. Create a group tab by opening new tab and pasting this: moz-extension://94c7ca6a-d1c2-4c14-9e1f-10468220a907/resources/group-tab.html?title=News&temporary=false
3. Open new tab as child of News tab.
4. Do gt when you are on the moz-extension page.

*   Tridactyl version (`:version`):
1.14.1-88-g2a520a3

*   Firefox version (Top right menu > Help > About Firefox):
63.0.3

*   URL of the website the bug happens on:
moz-extension://94c7ca6a-d1c2-4c14-9e1f-10468220a907/resources/group-tab.html?title=News&temporary=false

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
https://gist.github.com/makkanx/f58dbc4d6181c2074537759359f39763

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):
```
set hintchars "arstdhneiowfpluy"
bind ; fillcmdline
bind j scrollline 10
bind k scrollline -10
bind o fillcmdline tabopen
bind O fillcmdline open
bind c current_url open
bind C current_url tabopen
bind tn tabmove -1
bind te tabmove +1
bind P tabprev
bind N tabnext
bind h back
bind H forward
bind tl jumpprev
bind tL jumpnext
bind y clipboard yankshort
bind p clipboard tabopen
bind E clipboard open
bind gp followpage prev
bind gn followpage next
```

**Comment by bovine3dom** [comment]
We're not allowed to play with other extenions pages at all. : (

It might be worth trawling through bugzilla or #760 and filing or voting an existing issue up. Sorry.

**Comment by MilanV** [comment]
[Second Search extension](https://addons.mozilla.org/en-US/firefox/addon/second-search/) hotkey (Ctrl-Shift-L by default) works even on the about:extension page, including a page of _another_ extension (i.e. Tridactyl). Can we inspire there?

**Comment by bovine3dom** [comment]
Sort of - the keybinds have to a) be chosen/set-up by the user (as of nightly) through a special page; b) it only supports Octopus-style binds (like Ctrl-Shift-L) rather than key-sequence (like b, d, or gT).

What we need is https://github.com/cmcaine/keyboard-api, but development on that has stalled. If you're interested in having a crack at it, I'd be happy to help.
