### ISSUE TITLE
Update unbindurl/mode documentation

### ISSUE THREAD

**Issue by Noexpert** [tridactyl/tridactyl#1193]
Hi,

this is possibly related to [this](https://github.com/tridactyl/tridactyl/issues/57) issue in which case feel free to close.

As advised [here](https://github.com/tridactyl/tridactyl/issues/57#issuecomment-427478606) I'm using Gmail in ignore mode.

However, it tridactyl is not disabled when I'm composing or replying to an email and the text input is focussed.

Here's an extract of my config:
```  "configversion": "1.2",  
  "subconfigs": {
    "mail.google.com/mail": {
      "ignoremaps": {
        "p": "",
        "J": "tabprev",
        "K": "tabnext",
        "S": "fillcmdline tabopen search",
        "b": "fillcmdline buffer",
        "t": "fillcmdline tabopen"
      }
    },
    "mail.google.com": {}
```
When I press J or K for instance whilst typing an email, it switches tab instead of disabling tridactyl since I'm focussed in a text entry box.

I've tried a using Gmail in normal mode (in another Firefox profile) and just binding J and K and in this case it works correctly, but of course the downside is that there are more keys to unbind.
```  "configversion": "1.2",
  "subconfigs": {
    "mail.google.com/mail": {
      "nmaps": {
        "J": "tabprev",
        "K": "tabnext"
      }
    }
```
Thanks

**Comment by Noexpert** [comment]
Hi @glacambre,

I'm currently on 1.14.6 which if I'm not mistaken, includes the fix above.

Unfortunately, the issue persists: whenever I'm in a text or search field in gmail (and in ignore mode), Triddactyl keeps registering the keystrokes instead of ignoring them.

I don't want to increase your workload by opening another issue.
Perhaps you could tell me if I'm doing something wrong?

Thanks

**Comment by bovine3dom** [comment]
Oh. Tridactyl doesn't switch to ignore mode when you're in a text area on purpose because the main point of it is to let me use Vim bindings that already exist in the text area.

You are probably better off unbinding everything in normal mode for the site in question.

**Comment by glacambre** [comment]
Could you try opening Tridactyl's newtab page, opening the Firefox console, running `tri.config.unsetURL("mail.google.com/mail")` and then running your `:seturl` calls again, but this time using either `mail.google.com` or `mail.google.com\/mail` as url? The URL is actually a JS regex and I believe the slash might be breaking it.

**Comment by Noexpert** [comment]
Thanks. In the end the solution was to clear all `subconfigs` and `autocmd` and simply use gmail in normal mode with the right `unbindurl` for the keys I need to use.

I initially used the "guide" here[https://github.com/tridactyl/tridactyl/issues/57#issuecomment-427478606](url) but it might be worth adding a bit more detail in the readme.

**Comment by glacambre** [comment]
You're right, `unbindurl` and `mode` are a bit undocumented at the moment. I've edited the comment your problem came from and I'll reopen this until the documentation is a bit more fleshed out.
