### ISSUE TITLE
Using seturl subtly breaks things

### ISSUE THREAD

**Issue by antonva** [tridactyl/tridactyl#1203]
Issuing `seturl example.com modeindicator true` will change the current theme to the default one. Clearing `subconfigs` reverts the change. I'd guess that this might be breaking other things as well.

**Comment by glacambre** [comment]
I ran `:tabopen example.org`, `:set theme dark`, `:seturl example.org modeindicator false` and `:reload` and couldn't reproduce this issue. Are there specific steps to reproduce it?

I've noticed the theme not being applied from time to time but it seemed unrelated to subconfigs to me.

**Comment by antonva** [comment]
This was indeed fixed by that commit. Nvm.
