### ISSUE TITLE
It would be useful if the file created to edit the contents of an input box in external editor was named something that signified its origin

### ISSUE THREAD

**Issue by michaelmrose** [tridactyl/tridactyl#1204]
If I trigger an external editor with C-i on this comment box I get a temporary file at /tmp/tmp_github.com_2l6plbnh for at least some editors example emacs its useful to put the text editor in a particular mode when it opens this file. For example one may not desire spellchecking on buffers containing code but desire spellchecking on buffers containing text intended purely for human beings.

The desired mode by be selected by matching the filename to one or more regex to decide what sort of file it is.  its entirely possible now to match tmp_\.* now and make this work but this could in theory result in unrelated files matching if they started with the same string. Simply adding .dactyl to the temp file definitively belongs to tridactyl and let the user choose the desired mode without inadvertently matching other items. Alternatively ending in .txt would make things work out of the box correctly for most parties.

Either is reasonable.

**Comment by cmcaine** [comment]
I don't think this would break many autocommands (only if they have a
restrictive regex).

An autocmd that changes the file type might be overridden if it acts on a
very early signal, I don't remember. BufRead should be fine. BufEnter
*might* not be?

I don't think it's worth worrying about, tho. If someone is setting their
own aucmds they can probably work out what's happening.
