### ISSUE TITLE
text.insert_text fails in email input fields

### ISSUE THREAD

**Issue by arcnmx** [tridactyl/tridactyl#1209]
`bind --mode=insert <C-]> composite js "testing" | text.insert_text`

Seems to work in most (all other?) fields except for `<input type="email" />`. Can be tested [here](https://mastodon.social/auth/sign_in). Nothing happens when pressing the binding if the field is an email field.

**Comment by glacambre** [comment]
This is a problem we [already encountered](https://github.com/tridactyl/tridactyl/issues/471). The problem stems from not being able to read cursor position in email elements, which is unfortunately what the [spec](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange) says should happen. We can't do anything about it :(

**Comment by arcnmx** [comment]
Hm, that's unfortunate... The ability to write to email fields is pretty important for being able to paste in or fill parts of forms...

1. At the least, if the field value is empty, the state of selection is known. `insert_text` could at least replace/append rather than doing absolutely nothing? Neither is necessarily correct, but at least it can work in some cases rather than being completely nonfunctional.
2. Temporarily change `element.type = "text"`, read/modify the field properties, immediately set back to `"email"`. It's a bit of a hack but seems to work fine from a quick test.

**Comment by bovine3dom** [comment]
I meant to test this on weird elements like CodeMirror / ACE - did you, @glacambre? Does it break them?

**Comment by glacambre** [comment]
Editor functions work ok (not great) on contenteditable elements. They mostly do not work with CodeMirror/Ace with a few exceptions (insert_text works in CodeMirror but not in Ace for example) but they nonetheless do not break the editor.

**Comment by arcnmx** [comment]
Thanks for the quick fix!
