### ISSUE TITLE
Easily configure the hint CSS?

### ISSUE THREAD

**Issue by x-ji** [tridactyl/tridactyl#1212]
The hint chars seem really large in my case and on Reddit all of the three-character hints overlap, making it difficult to select anything. Is there an easier way to configure the style for hinting? (e.g. Allow the user to edit the hint CSS in the browser and offer an option to reset to default)

**Comment by bovine3dom** [comment]
Have you seen e.g, https://github.com/glacambre/.dotfiles/blob/2077603882c7bfe695dd7bc61b539650419598ac/default/.config/tridactyl/tridactylrc#L86-L87 ?

**Comment by x-ji** [comment]
Thanks. This is much better. I wasn't able to find information about it and wasn't sure whether the hint CSS is a part of the colorscheme configuration.
