### ISSUE TITLE
Content Security Policy error — current beta Tridactyl not capturing input

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [tridactyl/tridactyl#1226]
No input causes a response; the mode-indicator claims `normal`, but it doesn't seem it. Relatedly, my `tridactylrc` is having no effect, either — theme is default, instead of `halloween`.

Reinstalling has no effect. `)=`

I'm getting this error in the console:

> Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

Tridactyl `1.14.3-18-g1577a8e`
FireFox `63.0.3`

**Comment by ELLIOTTCABLE** [comment]
Added to OP.

Also worth noting, I'd just tried to add `seturl localhost:4200 noiframe true`, after an error reported that that's supposed to replace `set noiframeon ["localhost:4200"]` — but I also hadn't used this machine in a while, and I'm pretty sure Tridactyl's interface was white *before* I noticed that message and modified my `tridactylrc`, so I'm unsure that's related.

Currently reproducing with *no* `tridactylrc`, though.

**Comment by bovine3dom** [comment]
Could you add `viewconfig` to the end of your tridactylrc, restart the browser, and show the URL to us?

**Comment by ELLIOTTCABLE** [comment]
Having done so, with [this tridactylrc](https://gist.github.com/ELLIOTTCABLE/4b2e9e6278cbe9b5d3e20ceae010ab9b), I get a default/white Tridactyl new-tab page, and the `:` still has no effect.

Not sure what you mean by ‘show the URL to us!’ (Sorry it took me so long to reply.)

(Note that I'm losing access to this machine for a few days — it's going in for service for unrelated hardware reasons — so if you reply, I might not get back to this for a few *more* days! Sigh. 🤣)

**Comment by bovine3dom** [comment]
You could try sanitise tridactylsync at the top? Viewconfig ought to give you a URL that's actually just JSON you can share with us.

You can access some Tridactyl commands via the browser console and about:debugging... I think we have instructions around here somewhere. Then you just want to do tri.excmds.fillcmdline() and that should give you a command line or loads of errors.

**Comment by ELLIOTTCABLE** [comment]
So I had an intuition — I'm too lazy to check the code, but is the section I added most recently *actually correct*?

```vim
autocmd DocStart /localhost:4200/ mode ignore
seturl localhost:4200 modeindicator false
seturl localhost:4200 noiframe true
```

Like — no quotes around the URL for literal URLs in the latter two, slashes around the URL in the first? I'm wondering if one of those basically ended up applying globally (presumably `noiframe`), and disabling the command-line even on the welcome-page and tutorial …

If that's not obviously wrong, I suppose investigating this until the broken machine comes back from Apple.

**Comment by glacambre** [comment]
>is the section I added most recently actually correct?

It looks correct, and loading your whole Tridactylrc isn't enough to reproduce your issue on my computer. Could you try using a fresh firefox profile when you get your computer back?

**Comment by ELLIOTTCABLE** [comment]
This is really odd — now it's started occuring on my *other machine.*

Okay, hopping in the debugger, it's precisely the error you'd expect given the only change that caused the bug: `TypeError: "cmdline_iframe is undefined"`

Trying to to reset Tridactyl's config entirely with `sanitise`, see if I can reproduce — meanwhile, there's this, too:

<img width="921" alt="image" src="https://user-images.githubusercontent.com/200/49906608-396f0180-fe38-11e8-8025-af9630384759.png">

**Comment by glacambre** [comment]
These errors will go away once https://github.com/tridactyl/tridactyl/pull/1192 is merged. Restarting the browser should be enough to make them disappear for now, but of course it's going to reload your tridactylrc and the bugs with it :/

**Comment by ELLIOTTCABLE** [comment]
Since I can't reproduce *after* a `sanitise tridactylsync`, I'm gonna close this for now. How weird.

Thanks for looking into it, @glacambre!
