### ISSUE TITLE
# An error occurred in the content controller: TypeError: modeState is undefined 

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#1233]
*   Brief description of the problem: # An error occurred in the content controller: TypeError: modeState is undefined 

*   Steps to reproduce:

    1.  Visit https://github.com/tridactyl/tridactyl/pulls while being logged out
    2. Go in hint mode
    3. Attempt focusing the topmost search input field

*   Tridactyl version (`:version`): 1.14.4-801-ge7046af

*   Firefox version (Top right menu > Help > About Firefox): 63.0.3

I believe this might have been introduced in #1224 as I couldn't reproduce this error with a non-updated Tridactyl.

**Comment by bovine3dom** [comment]
Can't reproduce on Linux, FF63.0.1, Tridactyl 1.14.4-2-ge7046af.

(PS: git pull --tags :) )

**Comment by glacambre** [comment]
Weird. I'm using the default config, are you?

**Comment by xTpx** [comment]
Reproduce the bug on Linux, Firefox 65 b3.

**Comment by davidsierradz** [comment]
Same on:

Linux Manjaro Firefox Developer Edition 64.0b14 on Tridactyl 1.14.4-8-gbe2618c

**Comment by bovine3dom** [comment]
Ah, yes. Reproducible with `set hintfiltermode simple`.

**Comment by bovine3dom** [comment]
Fixed, stable version released in 1.14.5.

(By the way, you should all use `set hintfiltermode vimperator-reflow`, and `set hintnames numeric` as it is the superior hinting mode : ) )
