### ISSUE TITLE
`yy` sometimes gives an error of # background_controller:  Error: undefined 

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1239]
Tridactyl 1.14.5-1-gbc01010

The URL still seems to be copied to the clipboard. This error only happens intermittently - I don't have steps to reproduce - but once it happens on a tab and page it keeps happening on `yy` on that page even after refresh / navigation away from and back to that page.

I get the following errors in the background console with most `logging` on debug:

```
normal normal <unavailable> <unavailable>
content.js:5892:17
background_controller:  <unavailable> background.js:32560:25
log/<
moz-extension://36bea099-aa64-4e49-8d26-cc585d6dba9e/background.js:32560:25
acceptExCmd
moz-extension://36bea099-aa64-4e49-8d26-cc585d6dba9e/background.js:28072:13
set clipboard: https://www.bmj.com/content/363/bmj.k5094 commandline_frame.js:2935:13
<unavailable> commandline_frame.js:2678:9
```

**Comment by glacambre** [comment]
I think this is actually #1237 in disguise.

**Comment by bovine3dom** [comment]
I haven't seen this in a while. Has anyone else?

**Comment by glacambre** [comment]
It has disappeared for me too, along with the extra `:tabopen` tabs.

**Comment by bovine3dom** [comment]
My favourite kind of fix! Time heals all bugs!

**Comment by skrattaren** [comment]
Still happens for me on _1.17.1pre3763-e61fd83_.  Much less often than on 1.16.0, though (and `tabopen` doesn't open extra tabs).

**Comment by bovine3dom** [comment]
I just saw it again :(

**Comment by bovine3dom** [comment]
Potentially related to https://github.com/tridactyl/tridactyl/issues/1135

**Comment by bovine3dom** [comment]
After #2580 we now get the more helpful error of "Failed to copy!" which is thrown here https://github.com/tridactyl/tridactyl/blob/3ae5e2d3ac8557a9051a9a42d9c2be785ec523a8/src/commandline_frame.ts#L345 - next time I see it I'll see if the stack trace leads to anything useful.

**Comment by bovine3dom** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand#Return_value

> Note: Only returns true if part of a user interaction. Don't try using the return value to verify browser support before calling a command.

This suggests that it can return false even when it works, so I'm just going to remove the `if`.
