### ISSUE TITLE
Enable actually overriding ex commands

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#1241]
In https://github.com/tridactyl/tridactyl/issues/344#issuecomment-400543964 I suggest using `tri.excmds.exCmd = myExCmd` in order to replace Tridactyl's default exCmd with myExCmd. This never actually worked or changes to webpack/our architecture broke it.
We can still use
```
alias tabopen jsb -p let tabopenargs = str.slice(str.indexOf("/" + "/") + 1); console.log(performance.now(), `tabopen ${tabopenargs}`); tri.excmds.tabopen(...tabopenargs) //
```
In order to work around this issue but this is far from being user-friendly, and it won't override direct calls to tri.excmds. We should have a proper excmd-overriding mechanism.

**Comment by bovine3dom** [comment]
Do you mean overriding such that internal Tridactyl commands use the new command?

For interactive uses (or anything that hits the parser) e.g. `alias tabopen winopen` works fine.

**Comment by glacambre** [comment]
>Do you mean overriding such that internal Tridactyl commands use the new command?

I think that's what I was talking about yeah. I don't remember why I wanted that and this should come for free if we ever manage to implement the more dynamic command declaration API we talked about ~6 months ago so we can probably close this issue.
