### ISSUE TITLE
Clicktime login screen triggers infinite redirect

### ISSUE THREAD

**Issue by fancypantalons** [tridactyl/tridactyl#1250]
Navigating to the ClickTime login page results in an infinite redirect.  The URL for that page is:

https://login.clicktime.com/

This is with Tridactyl 1.14.6.

Firefox Windows 64-bit 65.0b4

This is with out-of-the-box configuration, though I can provide that if it's useful.

**Comment by bovine3dom** [comment]
`seturl [URL] noiframe true` will probably fix this, but it will disable the command line on the page.

Closing as instance of #355.

**Comment by fancypantalons** [comment]
Ah, I suppose I could've found that issue if I'd just spent a little time looking for it...

Thank you for your patience!  That worked perfectly!

**Comment by glacambre** [comment]
@fancypantalons If you encounter other issues there's also a [troubleshooting guide](https://github.com/tridactyl/tridactyl/blob/master/doc/troubleshooting.md) that lists a few settings you can fiddle with in the hope of stopping Tridactyl from breaking everything :)
