### ISSUE TITLE
Tabopen can open in wrong window if you're fast enough.

### ISSUE THREAD

**Issue by antonva** [tridactyl/tridactyl#1251]
I use multiple workspaces and if I enter `:tabopen example.com` and switch to a workspace with no Firefox window open it will open the tab in an unrelated window. 

This could very well be documented but I don't recall it /can't find it in searches.

Reproduction:
* I have three workspaces **_a_**, **_b_**, **_c_**. 
* **_a_** and **_c_** both have firefox windows open, **_b_** does not.
* On workspace **_a_** I execute `:tabopen example.com`.
* As soon as I hit enter I navigate to **_b_**.
* Navigate to **_c_** and find the tab opened there.
* Version 1.14.5-1-gbc01010

**Comment by notJerl** [comment]
Maybe related to #727?

**Comment by glacambre** [comment]
@notJerl I don't think so. This does sound similar to #1019 though.

**Comment by antonva** [comment]
I cannot reproduce this at all on 1.14.9-13-g87adde1. Closing.

**Comment by bovine3dom** [comment]
Hmm, I sometimes hear people complaining that Tridactyl doesn't work well with multiple windows, so I'm not sure that this is fixed.
