### ISSUE TITLE
tabopen lag

### ISSUE THREAD

**Issue by ironhouzi** [tridactyl/tridactyl#1272]
Not sure exactly when, but a few months ago I started noticing that my normal workflow of tabopen and writing `redd<tab` would do a web search instead of taking me to `www.reddit.com`.
I can observe that when doing a tabopen, quickly type a few letters followed by tab, deselects immediately, requiring me to hit tab twice.

This was never a problem for me on vimperator or pentadactyl and until now never on tridactyl either.

**Comment by bovine3dom** [comment]
Duplicate of #1208. It is really annoying, I agree...
