### ISSUE TITLE
Function to execute a command

### ISSUE THREAD

**Issue by user753** [tridactyl/tridactyl#1275]
Similar to `fillcmdline` but instead of filling it would execute the command
For example I want to add bookmarks in specific folder
```bind ,a composite js "bmark " + window.location.href + " readlater/" | execcmd```

**Comment by bovine3dom** [comment]
Yeah, sure, seems like a sensible idea.

In the meantime, you can use this horrendous hack:

`bind ,a composite js "bmark " + window.location.href + " readlater/" | composite`
