### ISSUE TITLE
hard to distinguish Q and O in hints

### ISSUE THREAD

**Issue by eeshugerman** [tridactyl/tridactyl#1280]
Maybe it's just me but I have a hard time distinguishing Q from O in hints. 
![screenshot from 2019-01-14 14-22-11](https://user-images.githubusercontent.com/25518211/51142177-65e7b600-1808-11e9-81e7-bbf093c8c67b.png)
Can we add options for the font or something? Thanks! :)

**Comment by bovine3dom** [comment]
We just use your system default. You can change it in about:preferences.

Otherwise you can do `:set hintchars [every character but q and o in some sane order of preference]`.

**Comment by bovine3dom** [comment]
We should probably add a pixel of padding to the hints looking at the Q one a little closer...

**Comment by eeshugerman** [comment]
Yeah some padding might help. Thanks for the tips, I'll try them out.
