### ISSUE TITLE
tabprev doesn't work in Waterfox

### ISSUE THREAD

**Issue by chocolateboy** [tridactyl/tridactyl#1282]
<table>
<tr><td><b>Tridactyl</b></td><td>1.14.6</td></tr>
<tr><td><b>Waterfox</b></td><td> 56.2.6</td></tr>
<tr><td><b>OS</b></td><td>Linux (Arch)</td></tr>
</table>

The `tabprev` command no longer works in Waterfox. It results in the following error:

> Type error for parameter queryInfo (Unexpected property "hidden") for tabs.query. 

This is because the `hidden` parameter of `tabs.query` is not supported by Waterfox:

https://github.com/tridactyl/tridactyl/blob/e62eae4d152a681330a0b6e472c93057505d032e/src/excmds.ts#L1792-L1796

Waterfox is based on Firefox 56, and the `hidden` parameter was introduced in Firefox [59-ish](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/hide#Browser_compatibility). According to [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1423725#c85) (**edit**: and [this table](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/hide#Browser_compatibility)), it's missing on Firefox for Android as well.

Rolling back to 1.14.1, the release before the [fix for invisible tabs](https://github.com/tridactyl/tridactyl/issues/1150) was introduced, fixes the problem.

**Comment by bovine3dom** [comment]
Yeah, I'm not very surprised. We've had similar issues before.

We probably need some kind of runtime polyfill that replaces `browser` with one that degrades gracefully wrt forwards compatibility.

That seems like a) a great case for a collaborative effort between extension makers and b) a lot of work. One ought to be able to automate at least some of it via crawling MDN.

The other option is to be stricter with the minimum versions of Firefox we require for each release, but that would mean that people would get stuck on old versions, and I don't see us having the man power to backport bug fixes etc.

**Comment by bovine3dom** [comment]
> The other option is to be stricter with the minimum versions of Firefox we require for each release, but that would mean that people would get stuck on old versions, and I don't see us having the man power to backport bug fixes etc.

We've gone with this approach. Closing this as while I can't fix this exact bug, we shouldn't see any more like it: I now increment `min_version` in the manifest to whatever version I tested on. Related: #1564.
