### ISSUE TITLE
Block or ask for confirmation when attempting to set a variable that contains key-value pairs without specifying a key

### ISSUE THREAD

**Issue by notJerl** [tridactyl/tridactyl#1288]
It would be very helpful to get a confirmation prompt when attempting to use `set` on variables that contain key-value pairs without specifying a key to change the value for.  Alternatively, blocking the user from using `set` on these variables altogether if they haven't specified a key to change the value for would also be a functional solution, since it seems like attempting to do so on purpose wouldn't give the desired result anyway given that the quotation marks around the keys and values would all be escaped (see the below abomination for an example of how this messes the whole variable up).  I think a confirmation prompt combined with fixing the issue with escaping all the quotation marks would be the ideal solution, but I can only assume that the quotation marks are getting escaped for a reason.

It seems like completely destroying my entire searchurls variable happens almost as often as me attempting to add a new entry.  It's easy (for me, at least) to accidentally type `set searchurls key value` instead of `set searchurls.key value`, especially if I'm in a hurry and adding several at once, since other applications I use have the former syntax.  This is pretty distressing, since I use *dozens* of searchurls daily (I'm not exaggerating - I'm getting pretty close to 50 of them).  When this happens, it can take a *very* long time to fix them all.  Using a tridactylrc as insurance isn't really a good solution since I sync my settings across 4 computers with Firefox Sync - if I add a searchurl while using one that doesn't have the tridactylrc, there's a good chance I'll forget to add it to the tridactylrc when I'm next at my main computer.

The most recent time this happened to me, I managed to copy the previous, non-destroyed version from another machine.  Attempting to restore it by using `set searchurls <everything I copied>` unfortunately just made matters worse, since it escapes all of the quotation marks with backslashes, which makes all of them useless (the actual result is an abomination that looks like this: `# searchurls = {"0":"{","1":"\"","2":"g","3":"o","4":"o","5":"g","6" ... etc`).  Even just fixing this without providing a confirmation prompt, though, still wouldn't be an ideal solution, since you could still destroy the variable and not even realize it until after the chance synced to all of your other installs.

**Comment by glacambre** [comment]
I'm aware this doesn't fix your issue but if you have access to your searchurls in their JSON representation, I think you can run something like `jsb tri.config.set("searchurls", $THE_JSON_OBJECT)` in order to recover your settings.

**Comment by bovine3dom** [comment]
I think the crux of the issue is that `set searchurls key value` should always fail as it is the wrong type.

I guess the current type checking we have is failing because it doesn't work on nested objects? Is that right, @glacambre?

**Comment by glacambre** [comment]
@bovine3dom Yup, this was the problem. #1289 fixes that. It also makes `:set searchurls {"hello": "world"}` work properly. Sorry for messing up your config, @notJerl .
