### ISSUE TITLE
Links provided by Qwant.com are not followed

### ISSUE THREAD

**Issue by pmaziere** [tridactyl/tridactyl#1294]
Hello,

When using the qwant.com search engine, hitting <f> brings the links hints as expected but hitting the hints related to the search results does not open any page. On the same page, following hints associated with other links than search results works as expected. 

Firefox 64.0.2
tridactyl 1.14.6 default configuration

Thanks for having a look at this

**Comment by bovine3dom** [comment]
Hmm, it works fine for me on version `1.14.6-63-g214df84`. Could you check on the latest beta, and explain exactly what search terms you used, which link you clicked on, and with which hint mode?

Thanks.

**Comment by pmaziere** [comment]
You made me doubt, so I created a new profile with tridactyl 1.14.6 webextension only: surprise, it works as expected.
I must have modified something in the profile used above, hence the observed behavior with qwant.com
Sorry for the noise
