### ISSUE TITLE
`undo` completions intially displays "undo"

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1295]
Steps to reproduce:

- Type `:undo `  manually (i.e, with a space after `undo`).
- Observe that only `undo` is listed.
- Type a space and delete it, and the correct completions are listed.

Also, the completion title should have a capital `S` on `sessions`.

**Comment by glacambre** [comment]
This issue is present for all completion sources unfortunately. I think I introduced it with the input-lag solving code.
