### ISSUE TITLE
Hinting with selectors includes all JS hints no matter what element

### ISSUE THREAD

**Issue by Rahlir** [tridactyl/tridactyl#1299]
###   Brief description of the problem:
When using the command :hint -c [selectors], the hints that are shown also include all the javascript hints. This makes this command much less useful and goes against the idea of using specific selectors for hints.

###   Steps to reproduce:
Open google for instance. Type :hint -c [class="madeupclasslala"] and you will see hints for javascript elements (events) that are not of that made up class

### My notes
I traced back why is this happening: in `pipe()` located at [hinting.ts](https://github.com/tridactyl/tridactyl/blob/master/src/content/hinting.ts) the elements to be hinted are chosen by calling `hintables()` with the argument `withjs = true`. This means that the hintables returned will include all the javascript elements as well as those chosen by the selectors. This makes the use of -c option much less useful. I would love to have binded hint option for sites such as google that would return hints of only clickable links excluding all the useless javascript. But, having the -c option use `hintables()` where withjs is set to true makes this impossible. I would suggest allowing changing the `withjs` argument from the tridactyl commandline or maybe even setting the `withjs = false` when -c option is used -> I doubt that if someone decided to use -c option to narrow down hints, that user will also want to see all the random javascript elements on that page.

I haven't contributed to tridactyl so far. But seeing where this comes from I could also open the pull request myself if I have the time. Do let me know if this behavior is intended. I really do not see the reason for having `withjs` set to true when calling :hint -c.

**Comment by glacambre** [comment]
I think enabling JS hints with a flag (`-j` maybe?) is a good idea (in fact that's what I planned on doing at first) but @bovine3dom thought that it'd be better for them to be enabled by default and I just didn't bother to add a flag to disable them. So having `-j` to either enable or disable js hints sounds good to me :).

**Comment by Rahlir** [comment]
Is now possible using `-J` flag: See #1301
