### ISSUE TITLE
Half a page scroll

### ISSUE THREAD

**Issue by mvrozanti** [tridactyl/tridactyl#1304]
Hi there
I really like this repo and has helped me a lot but there's just one feature missing that bugs me:
there's currently no way to scroll half a page. Is there a reason why this is not implemented?

Thanks!

**Comment by bovine3dom** [comment]
It is implemented, and bound by default to `<C-u>` and `<C-d>`. What were you expecting it to be bound to?

**Comment by mvrozanti** [comment]
Sorry, nevermind! Keep up the good work
