### ISSUE TITLE
Warn when using `bind $letters$letter` where $letters is a sequence of already-bound keys

### ISSUE THREAD

**Issue by aureooms** [tridactyl/tridactyl#1309]
Is the following supposed to work and/or am I a complete idiot?

    " type xh to route page through sci-hub's proxy
    bind xh js window.location.replace('https://sci-hub.tw/' + window.location.href)

**Comment by glacambre** [comment]
Hi, thanks for opening this issue. You probably need to `:unbind x`. I must admit that `xh` not working was quite surprising to me too. We should probably warn when people create bindings with prefixes that are already bound to something.

**Comment by aureooms** [comment]
Yes that works!
