### ISSUE TITLE
After update to 1.14.7, composite tabopen <url> | tabopen <url> uses the search engine to search for the URL, adds  [object Object] after

### ISSUE THREAD

**Issue by nnadd** [tridactyl/tridactyl#1313]
Good day. After updating today Tridactyl no longer wants to play nice with the way I used to open multiple URLs with a keybind: 

It looked like this:

`bind E5 composite tabopen https://stuff.com | tabopen http://things/news.html | tabopen http://etc.com` and so on for around 10 tabs, this worked just fine before the update, the tabs would open without problem.
But now only the first tab opens while all the others open up in the search engine and have [object Object] after the URL, example: https://soylentnews.org/%20[object%20Object], but without the %20 URL encoding. 

For now I have just downgraded because I see no way to fix this in tridactylrc.

Firefox 64.0 <-- also affects 65

**Comment by bovine3dom** [comment]
Confirmed.

I don't know how we broke this without anyone noticing in the beta :(

I'll look into it tomorrow.

**Comment by glacambre** [comment]
`tabopen` returns a promise resolved when the new tab is opened. When you use a pipe, you're piping the result of this promise to the new command. What you need to use is `bind E5 composite tabopen https://stuff.com ; tabopen http://things/news.html ; tabopen http://etc.com`.

**Comment by bovine3dom** [comment]
Ah, I see, there was a breaking change because we made more functions return things.

I'll add some stuff to the new-tab page explaining it.
