### ISSUE TITLE
Can not update to 1.14.8

### ISSUE THREAD

**Issue by bodograumann** [tridactyl/tridactyl#1317]
I just updated firefox to version 65.0 and thus encountered the issue with the missing tab bar.
So I tried to update tridactyl from 1.14.6 to the latest version, but it does not work.

*   Steps to reproduce:

    1.  Select “Check for updates” in about:addons
    2.  Wait for the Tridactyl update to finish download
    3.  Allow the newly requested permissions

*   Tridactyl version (`:version`): 1.14.6-1.14.6

*   Firefox version (Top right menu > Help > About Firefox): 65.0 (64-bit)

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com): Reset through .tridactylrc

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
sanitise tridactyllocal tridactylsync

colourscheme shydactyl

guiset_quiet tabs autohide
guiset_quiet navbar autohide
guiset_quiet hoverlink top-right
guiset_quiet titlebar hide

set searchengine duckduckgo
set searchurls.duckduckgo https://duckduckgo.com/?q=
set searchurls.google https://www.google.com/search?q=
set searchurls.wikien https://en.wikipedia.org/wiki/Special:Search/
set searchurls.wikide https://de.wikipedia.org/wiki/Spezial:Suche/
set searchurls.osm https://www.openstreetmap.org/search?query=
set searchurls.leo https://dict.leo.org/englisch-deutsch/
set searchurls.duden https://www.duden.de/suchen/dudenonline/
set searchurls.unicode http://www.fileformat.info/info/unicode/char/search.htm?preview=entity&q=
set searchurls.github https://github.com/search?utf8=✓&q=
set searchurls.mdn https://developer.mozilla.org/en-US/search?q=
set searchurls.gentoo https://bugs.gentoo.org/buglist.cgi?quicksearch=
set searchurls.youtube https://www.youtube.com/results?search_query=
set searchurls.imdb https://www.imdb.com/find?ref_=nv_sr_fn&s=all&q=

set hintchars nharitsdevygclofuqxbpmwk,z

bind ;t hint -W tabopen
bind ;o hint -W open

" vim: set filetype=vim:
```

*   Operating system: gentoo linux
*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:
    > /usr/lib/llvm/6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/games/bin:/home/bodo/.local/bin:/home/bodo/.sbin:/home/bodo/.gem/ruby/2.0.0/bin:/home/bodo/.config/composer/vendor/bin
*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:
    > &lt;FF&gt;^@^@^@{"cmd": "run", "content": "/usr/lib/llvm/6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/games/bin:/home/bodo/.local/bin:/home/bodo/.sbin:/home/bodo/.gem/ruby/2.0.0/bin:/home/bodo/.config/composer/vendor/bin\n", "code": 0}

**Comment by bovine3dom** [comment]
Have you tried following the steps in https://github.com/tridactyl/tridactyl/issues/1229#issuecomment-458583919 ?

**Comment by bodograumann** [comment]
Oh, yes, seems that was related.

I managed to circumvent the issue of #1229 by changing the userchrome as in suggested in #1316 and removing `guiset_quiet titlebar hide` from my `.tridactylrc

And now suddenly tridactyl is updated as well...
