### ISSUE TITLE
Warn about `profiledir=auto` on guiset on windows

### ISSUE THREAD

**Issue by mabier** [tridactyl/tridactyl#1320]
I am using firefox 65.0 with tridactyl 1.14.8 installed. I  followed tridactyl's instruction of installing native messenger in windows 7's cmd.exe and the running result showed native messenger had been installed successfully, but when I checked it in firefox by inputting "native", the result reported it was not installed.  My question is how to install native messenger in Windows SP1 ?
![image](https://user-images.githubusercontent.com/7421605/52163233-4ca49c00-271a-11e9-8cba-9a3578aead5b.png)
![image](https://user-images.githubusercontent.com/7421605/52163237-53331380-271a-11e9-9c93-9953c97f8bba.png)

**Comment by glacambre** [comment]
>Then I tried "guiset gui none" and "guiset tabs always" and "guiset hoverlink right", unfortunately no single command worked !

What were the error messages? Also, did you set your `profiledir` setting? I think Tridactyl can't guess it on windows.

**Comment by mabier** [comment]
> 
> 
> > Then I tried "guiset gui none" and "guiset tabs always" and "guiset hoverlink right", unfortunately no single command worked !
> 
> What were the error messages? Also, did you set your `profiledir` setting? I think Tridactyl can't guess it on windows.

You are right ! After set profiledir to firefox's profile folder explicitly , guiset gui none and guiset tabs always etc. work flawlessly !

**Comment by glacambre** [comment]
With https://github.com/tridactyl/tridactyl/pull/1382 merged, Tridactyl should be able to guess profiledir on windows.
