### ISSUE TITLE
Tab / Buffer list based on current tab

### ISSUE THREAD

**Issue by chrisvella** [tridactyl/tridactyl#1323]
Could you please add an option to show the tab / buffer list based on the current tab? I have a lot of tabs so I am most interested in the tabs around my current one. Apologies if this is supported already.

**Comment by glacambre** [comment]
Yep, https://github.com/tridactyl/tridactyl/issues/1158 I believe.

**Comment by chrisvella** [comment]
> 
> 
> Hi, thanks for opening this issue. I believe #1158 is about the same thing, so I'll close this issue. Please let us know if I misunderstood what you meant :).

Yes it is. Thank you.
