### ISSUE TITLE
Command history search disappeared

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1329]
Pressing `<Up>` in the command line used to go to the previous thing you had in history that started with what you currently had typed in the command line.

I initially assumed I had a broken configuration and so ignored it, but I can't find any code in Tridactyl that does it.

I'm guessing this disappeared when we made ex-mode into a mode?

**Comment by glacambre** [comment]
`<ArrowUp>` is [bound](https://github.com/tridactyl/tridactyl/blob/799f2d32334c04eacb778139a7920d347dabb7fc/src/lib/config.ts#L79) to [prev_history](https://github.com/tridactyl/tridactyl/blob/799f2d32334c04eacb778139a7920d347dabb7fc/src/commandline_frame.ts#L314). It works fine for me, although I do remember seeing a bug where the command line history wouldn't be stored but it was about a year ago I think.

**Comment by bovine3dom** [comment]
Yeah. It used to do a reverse history search based on what had been typed.

I see it I think - `history(n)`. Probably just need to export that and change the default bind.

**Comment by bovine3dom** [comment]
Sorry, I misread that code. History is being called, so it should be doing a search.

Can you confirm that it does? E.g,

`:bind<ArrowUp>` should cycle through all the bind commands you have run.

**Comment by bovine3dom** [comment]
Hmm. If I load a page, do `w<ArrowUp>`, I get `winopen` history. But if I close the command line and then open it again with something else typed in, I still only get `winopen` history.

I guess we're not updating the fragment properly?

**Comment by glacambre** [comment]
Yep, it looks like we're not resetting HISTORY_SEARCH_STRING. The logic required to do this seems tricky.

I doubt this is the reason why you weren't getting any history results though.

**Comment by bovine3dom** [comment]
I was getting some results, but they weren't filtered.
