### ISSUE TITLE
Add additional symbols to buffer/tab list?

### ISSUE THREAD

**Issue by davidsierradz** [tridactyl/tridactyl#1338]
Hi!

Would be nice if we can get some useful tab status information, seeing [tabs.query() - Mozilla | MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/query), add symbols for:

- audible
- discarded / hidden
- muted
- pinned

It would be nice if we can also get unread status, but from [1421785 - Add unread to tabs.Tab](https://bugzilla.mozilla.org/show_bug.cgi?id=1421785) this API wont be implemented, through Tree Style Tab [adds/maintains](https://github.com/piroor/treestyletab/blob/e4c0d77bdb0c614f9fbc8541d349bfddf9947bd2/webextensions/common/tabs-update.js#L76) a list of unread tabs with [sessions.setTabValue() - Mozilla | MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sessions/setTabValue), I know there is some pending TST integration going on [Add TST integration by rootkit-ty · Pull Request #1260 · tridactyl/tridactyl](https://github.com/tridactyl/tridactyl/pull/1260).

I can try to poke around the tridactyl codebase, what do you think?

**Comment by glacambre** [comment]
Sounds like a good idea to me (we already show whether tabs are pinned or not though - it's the `@` symbol. Perhaps we should replace it with an icon/emoji?). It'd be pretty cool if it was configurable with a format string or something else that enables selecting items/choosing their order.

If you want to implement this yourself, we recently updated the [contributing guide](https://github.com/tridactyl/tridactyl/blob/master/contributing.md). The file you're going to be most interested in is [`src/completions/Tab.ts`](https://github.com/tridactyl/tridactyl/blob/master/src/completions/Tab.ts) (and maybe [`TabAll.ts`](https://github.com/tridactyl/tridactyl/blob/master/src/completions/TabAll.ts). I don't know why I didn't but TabAll.ts's content in Tab.ts). The width of the various completion columns are set with CSS in [`src/static/css/commandline.css`](https://github.com/tridactyl/tridactyl/blob/master/src/static/css/commandline.css). If you want to add a setting, you can do it in [`src/lib/config.ts`](https://github.com/tridactyl/tridactyl/blob/master/src/lib/config.ts).

**Comment by fluem** [comment]
Volunteering. How about 
- replacing ```@``` for pinned tabs with unicode character (U+1F4CC) &#128204; (Pushpin, 0xD83D 0xDCCC in UTF-16)
- adding (U+1F50A) &#128266; for audible tabs (Speaker with three sound waves, 0xD83D 0xDD0A in UTF-16)
- adding (U+1F507) &#128263; for muted tabs (Speaker with cancellation stroke, 0xD83D 0xDD07 in UTF-16)
- adding (U+29B8) &#10680; for discarded tabs (Circled Reverse Solidus, 0x29B8 in UTF-16),

Alternatively, we could use ```p``` for pinned, ```a``` for audible, ```m``` for muted, ```d``` for discarded to keep it easy.
Opinions?

**Comment by bovine3dom** [comment]
We discussed this a little in #2811. There my concern was that people should be able to filter tabs by typing the characters. I think in that case an alphabetical character is too easy as people will be trying to filter by tab names but instead will filter by tab status, or vice versa.

Perhaps uppercase letters would solve that problem? It sort of makes sense as "%" is already "uppercase" on most keyboards.

**Comment by fluem** [comment]
Sorry, I was not aware of #2811 - I see some of the trade-offs. 
Yes, I think uppercase letters (e.g. P,A,M,D) might be the best way to solve this problem. They don't appear frequently in tab names, so filtering by tab status will work well and filtering by tab name will only be marginally disrupted. The down-side is that user might have to enter more than one character to find the tab with 007's boss' biography when they have multiple muted tabs open, but these would be edge cases. When filtering by tab names I'd imagine most users will enter more than one single character already. I will think some more about this.

For the ones of us who like things pretty, we could introduce a setting ```tabstatusstyle``` set to ```plain``` by default. If set to ```pretty```, display fancy unicode symbols, but keep filtering with the same uppercase letters as in ```plain``` mode.

**Comment by bovine3dom** [comment]
> For the ones of us who like things pretty, we could introduce a setting tabstatusstyle set to plain by default. If set to pretty, display fancy unicode symbols, but keep filtering with the same uppercase letters as in plain mode.

I like this idea. Please use the new completions setting object - i.e. https://github.com/tridactyl/tridactyl/blob/eca1e1614b8d0e51dcb7369a3b4026fed72ad209/src/lib/config.ts#L992 - as I'm hoping to eventually make completions more configurable.

I'm 90% sure tab filtering is case insensitive, so the person looking for M should be typing m anyway.

**Comment by bovine3dom** [comment]
Added in #2917. `:set completions.Tab.statusstylepretty true` for emoji symbols
