### ISSUE TITLE
`:findnext` hangs if placeholder text matches

### ISSUE THREAD

**Issue by zsugabubus** [tridactyl/tridactyl#1340]
*   Brief description of the problem:
`:findnext` hangs if there is a match inside of the placeholder text of an `input[type=password]` element.

* Steps to reproduce:
    1.  Navigate to [github.com](https://github.com/) without being logged in.
    2.  `:find assword`
    3.  `:findnext 1`

**Comment by glacambre** [comment]
Thank you for reporting this and for the clear repro steps :)
