### ISSUE TITLE
`:findnext` doesn't bring matches into view

### ISSUE THREAD

**Issue by zsugabubus** [tridactyl/tridactyl#1342]
*   Brief description of the problem:
    `:findnext` does not bring matches into view if there is a match inside of a placeholder text, because it always scrolls back to this position.

*   Steps to reproduce:
    1.  Navigato to  [github.com](https://github.com) without being logged in OR [github.com/tridactyl/tridactyl](https://github.com/tridactyl/tridactyl).
    2. `:find name` OR `:find rc`
    3. `:findnext 1`
    4. Go to step iii.

**Comment by bovine3dom** [comment]
Fixed in #1613.
