### ISSUE TITLE
using terminator as my terminal emulator results in the same issue as gnome-terminal

### ISSUE THREAD

**Issue by heshamsafi** [tridactyl/tridactyl#1346]
this is certainly the same issue as https://github.com/tridactyl/tridactyl/issues/1035

but [1035](https://github.com/tridactyl/tridactyl/issues/1035) was resolved as a gnome-terminal issue, and I just want to point out that more terminal emulators have the same issue

to reproduce the issue please follow https://github.com/tridactyl/tridactyl/issues/1035#issuecomment-462164731

**Comment by heshamsafi** [comment]
also found that similar to https://github.com/tridactyl/tridactyl/issues/1035#issuecomment-425656155 

the work around for terminator is the -u option 


```
set editorcmd terminator -u -e 'vim %f'
```
works like a charm

one solution is to 

add the -u option to this line :
https://github.com/tridactyl/tridactyl/blob/master/src/background/native_background.ts#L125

and update this comment because it is not great advice https://github.com/tridactyl/tridactyl/blob/master/src/excmds.ts#L258

but that won't protect people like me who are using set editorcmd to explicitly provide an editor

one solution for that aswell, is to add another option called terminalemulator or whatnot that people can set, and tridactyl can add the -u to terminator and --disable-factory for gnome-terminal. instead of embedding the terminal emulator in the editorcmd option.

have a think about it I am already unblocked with the -u workaround and I am just sharing ideas.

**Comment by glacambre** [comment]
Does `-u` exist for all distros or is it an ubuntu-specific flag? The [die.net](https://linux.die.net/man/1/terminator) manpage doesn't mention it but the [ubuntu](http://manpages.ubuntu.com/manpages/bionic/man1/terminator.1.html) one does. It doesn't seem to be mentionned in [terminator's manpage source-code](https://bazaar.launchpad.net/~gnome-terminator/terminator/gtk3/view/head:/doc/terminator.1).

**Comment by heshamsafi** [comment]
holy moly, I go to bed and wake up and you have [taken care of everything](https://github.com/tridactyl/tridactyl/commit/e0545aca653a33eb079fa0ffd26a136a0a6e6dcb).
looks like you added another wildcard %c for the editor, while %f is for filename only now, kudos !

thank you for doing this. and feel free to resolve.

**Comment by glacambre** [comment]
>looks like you added another wildcard %c for the editor,

This wildcard isn't actually available to users, it's only expanded when trying to guess what editor should be used. `%c` isn't needed when using editorcmd because the user has full control of the command that should be executed :)

>thank you for doing this. and feel free to resolve.

You're welcome, thank you for opening this issue :)

**Comment by eliasdaler** [comment]
Just a heads up for xfce-terminal users. This is what I got working, thanks to this issue

```set editorcmd xfce4-terminal --disable-server -e 'vim %f'```

P.S. One thing bugs me a bit, though. When I'm finished writing and exit editor, cursor is still positioned in the beginning of the text box. Can it be made positioned in the end instead?
