### ISSUE TITLE
Add migration between stable and beta to FAQ / troubleshooting

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1353]
Testimonial follows

====

I did a couple small corrections to your suggested steps:
I replaced steps from 1 to 4 with the following
1. Run in Tri command line the `viewconfig`
2. This should open a new tab with the JSON file with all your configs inside the Firefox convenient builtin JSON viewer. In the viewer press the `Save` or `Copy` button and store the JSON config content somewhere

I've also replaced the step 9 with the following:
  
9. Run the following command in the console and paste the JSON string text that you saved earlier in the pop box field that will be displayed:

        let myConfig = JSON.parse(prompt('Paste the JSON string in the field below')); Object.keys(myConfig).forEach(key => tri.config.set(key, myConfig[key])); alert('Tridactyl settings saved!')

I suggest your instructions to be documented somewhere also, I think this could be useful to many people, thank you for your time!

_Originally posted by @GlassGruber in https://github.com/tridactyl/tridactyl/issues/792#issuecomment-462635191_

**Comment by GlassGruber** [comment]
Hey there, I just reassembled the whole procedure steps for completeness

1. Run in Tridactyl command line the `viewconfig` command
2. This should open a new tab with the JSON file with all your configs inside the Firefox convenient builtin JSON viewer. In the viewer press the `Save` or `Copy` button and store the JSON config content somewhere
3. Uninstall Tridactyl stable
4. Install Tridactyl beta
5. Open the newtab page
6. Open the console with `<C-I>`
7. Run the following command in the console and paste the JSON string text that you saved earlier in the popup box field that will be displayed:

        let myConfig = JSON.parse(prompt('Paste the JSON string in the field below')); Object.keys(myConfig).forEach(key => tri.config.set(key, myConfig[key])); alert('Tridactyl settings saved!')

**Comment by alerque** [comment]
How does this procedure of copying the JSON data dump compare to using `:mkt` to export an RC file with all current settings and keeping that in `~/.config/tridactyl/tridactylrc`?

**Comment by bovine3dom** [comment]
The migration steps here will bake all of your settings, not just ones you set, so if we ever changed any defaults (e.g. because there's a bug) you would not get those updates. The RC method only includes settings you have set so wouldn't have that issue. (There's no fundamental reason we couldn't change the migration steps to stop this baking though).

The RC method needs the native messenger and, in practice, running the RC files isn't 100% reliable when getting the settings back into Tridactyl, especially if they are large.

**Comment by braham-snyder** [comment]
For posterity, I think the migration steps listed in the wiki are probably what you want to use now, IIUC. For one, they add `--user` so that it only includes settings you have set yourself: https://github.com/tridactyl/tridactyl/wiki/Migration-from-stable-to-beta
