### ISSUE TITLE
Provide a cmd to open a popup window

### ISSUE THREAD

**Issue by robertgzr** [tridactyl/tridactyl#1357]
similar to https://addons.mozilla.org/en-US/firefox/addon/popup/

I can currently do that like this: 
```js
js window.open(window.location.href, window.document.title, "menubar=0,location=0,resizable=1,scrollbars=1,status=1")
```

but I have to disable ff preventing sites from opening popups :/

integrating it into the `winopen` cmd as an option or having something like `popopen` would be nice

**Comment by glacambre** [comment]
The extension you mention uses [browser.windows.create and browser.windows.update](https://github.com/aqt/webext-popup/blob/833848be5ac87a9b768f0b1bd1a029fce235e8cb/content/background/background.js#L228) to create popups so this can already be done in Tridactyl. It'd indeed be nicer to have an excmd to do all of that automatically though.
