### ISSUE TITLE
Updatecheck doesn't actually work at FF launch

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1360]
I think we probably need to move it from background to content, perhaps with a timeout, to ensure that there's actually a Tridactyl command line waiting to be shown.

**Comment by bovine3dom** [comment]
Added P2 label as this should block adding any more permissions.

**Comment by saulrh** [comment]
For the specific case of permissions, have we considered using the permissions API to request appropriate permissions at runtime? The limitation to event handlers for user events is annoying, but it shouldn't be *too* hard to add a layer of permission annotations to the excmds and then request them in the shims. Would that be a valuable capability to add to tridactyl?

**Comment by cmcaine** [comment]
Last time we looked at that api we couldn't request any useful permissions
from it. Maybe it has changed?

**Comment by bovine3dom** [comment]
See #973 - `onInstalled` wasn't a valid event, so we had to leave Tridactyl half-broken just so some people could choose to have it be broken. I don't know if we considered it in the context of new permissions.

**Comment by saulrh** [comment]
Ah, yeah, contextualIdentities and nativeMessaging are both on the list of non-optional permissions, and I bet those were the two that mattered at the time.

management looks like it's on the list of permissions that can be optional and requested at runtime.

Let me experiment with this. I'll try putting a permissions check in the content controller, on `acceptKey` or `acceptExCmd`. It should trigger essentially instantly for every user that'd ever need to do anything with tridactyl, and it should be quite difficult to avoid it.

**Comment by saulrh** [comment]
Oooooor apparently management is also not on that list. Blast.

Well, same technique should work for the update nag. Let's try that instead.
