### ISSUE TITLE
Not working with web components (e.g. input triggers Tridactyl binds in shadow dom)

### ISSUE THREAD

**Issue by Jez3652** [tridactyl/tridactyl#1365]
Does not work on input boxes in web components
I can post a jsFiddle if that would help but basically do this
Create a template object in a shadow dom containing an input box (type=text in my test case)

Because the parent element is not editable then I think the element is seen by tridactyl as not allowing input so directs all keyboard input to itself. Evidence for this is that you can quite happily delete text content and even add spaces. But all alpha chars fail. Fires tridactyl instead.

if I set contentEditable=true on the web component it's happy but of course this is undesirable in the context of the component itself :)

Could it be that possibly a bit of recursion is needed on each test component if the element contains a dash (i.e. a custom component?) Could be fun! :)

**Comment by bovine3dom** [comment]
Example page - https://mini-form-demo.firebaseapp.com/ (courtesy of arix on Matrix).

Keys trigger Tridactyl functions in those input boxes and `gi` doesn't work either. cmcaine suspects source of bug is somewhere in this function https://github.com/tridactyl/tridactyl/blob/b30ef3097e1cecec629758936edeca4786d649a3/src/lib/dom.ts#L23

arix claims that the site works fine in Vimium and Vim-Vixen.
