### ISSUE TITLE
load next page in a thread

### ISSUE THREAD

**Issue by GianniGi** [tridactyl/tridactyl#1366]
Feature request:
Add a key combo to **load the next page**.

When **navigating through forums**, it is would be very helpful to have a keycombo that loads directly the next page. 

For example in this forum:
https://www.skyscrapercity.com/showthread.php?t=832456&page=157
the addon should look for the > key, or fro the "next page" link

There used to be an addon like tridactyl (maybe vimperator), that used to do exactly this.

**Comment by bovine3dom** [comment]
A fellow Mancunian, or are you just admiring our world class architecture?


`:followpage {next,prev}` already exist and work fine on that page. Bound to `[[` and `]]`  by default.

What were you expecting it to be bound to?
