### ISSUE TITLE
Bind : to ; to open command prompt?

### ISSUE THREAD

**Issue by haudren** [tridactyl/tridactyl#1367]
On my machine, in my `vimrc` I remapped `:` to `;` for quicker access to commands (no need to hold shift). Given that my `vimrc` contains:
```
nnoremap ; :
nnoremap : ;
```

I tried to input
```
bind ; : 
bind : ;
```
In my `tridactylrc`. However, that does not seem to function, as pressing `;`, instead of opening the command prompt gives me:
> :# background_controller:  Not an excmd: : 

Is there a way to remap `:` properly?

**Comment by glacambre** [comment]
In tridactyl, every keypress is bound to an ex command. If you want to know what `:` is bound to, you need to run `bind :`. This will tell you that `:` is bound to `fillcmdline_notrail`. You can then bind `;` to `fillcmdline_notrail` with `bind ; fillcmdline_notrail`.
If you'd rather have `;` be translated to `:` for all default bindings, you can use `:keymap`, like this: `keymap : ;`. I believe `:keymap` only works in normal mode for now though.

**Comment by haudren** [comment]
Thanks for the comment, I've been experimenting a bit and 
`bind ; fillcmdline_notrail` is great to open the command line. However, I can't seem to find a good way to achieve:
- `;` opens the command line
- `:y` (for example) opens the extended hint mode for pasting

**Comment by bovine3dom** [comment]
Yes, you can't do that. It was a conscious choice we made to simplify writing the parser.

If we did, we'd have to make it so that any binds that shadow other binds only execute if no other (valid) key has been pressed after some timeout. That feels janky to me.

I'd suggest binding e.g, `;;` to `fillcmdline_notrail` instead.

**Comment by bovine3dom** [comment]
As glacambre pointed out on IRC, you should run
`keymap ; :`
`keymap : ;`

The order is important - you won't be able to open the command line if you run the second command first.

**Comment by haudren** [comment]
Thanks a lot, that's exactly what I needed !
