### ISSUE TITLE
hint -qy should copy all links to clipboard

### ISSUE THREAD

**Issue by qk** [tridactyl/tridactyl#1374]
Right now selecting multiple links with `hint -qy` results with only the last link in the clipboard. It would be more intuitive to have all selected links in a newline-separated list in the clipboard instead.

So if a user types the hints for link_1,...,link_n they end up with

    link_1
    link_2
    ...
    link_n

The clipboard could be reset when `hint -qy` is re-invoked by the user.

**Comment by glacambre** [comment]
`composite hint -qpipe a href | yank` almost does what you want.

**Comment by qk** [comment]
Thank you for the solution, but this should have been the default behavior. I don't see where it would be detrimental for hint -qy to behave that way.

**Comment by glacambre** [comment]
It's just a workaround until the behavior you described is implemented :)
