### ISSUE TITLE
expand cmd line with selections to allow editing

### ISSUE THREAD

**Issue by majuscule** [tridactyl/tridactyl#1377]
Feature request: Expand command line with full urls when tabbing through completion suggestions. This will allow for editing previously visited urls before entering. Tabbing back out of the suggestions should reset the command line to only what was explicitly typed.

**Comment by glacambre** [comment]
Hi, thanks for opening this issue. I believe this is a duplicate of https://github.com/tridactyl/tridactyl/issues/420 so I'm going to close this issue.

Until the feature you want is implemented, know that you can insert the selected completion option with `ex.insert_completion` or `ex.insert_space_or_completion`. `ex.insert_space_or_completion` is bound to `<Space>` by default.

**Comment by majuscule** [comment]
You are correct, thank you.
