### ISSUE TITLE
Page keeps reloading

### ISSUE THREAD

**Issue by paradx** [tridactyl/tridactyl#1380]
*   Brief description of the problem: 
With Tridactyl enabled the mentioned website reloads continously and will never show any content. 
The website seems to be running typo 3 CMS 
I did not contact them yet but can do that if it's more of a configuration issue on their side. 
Did not have the problem anywhere else.

*   Steps to reproduce:
    1.  visit https://www.zarm.uni-bremen.de/ with tridactyl enabled  
    2.  page will keep reloading 

*   Tridactyl version (`:version`): 1.14.8

*   Firefox version (Top right menu > Help > About Firefox): 65.0.1 (64-Bit)

*   URL of the website the bug happens on:  https://www.zarm.uni-bremen.de/

**Comment by bovine3dom** [comment]
Closing in favour of #639.
