### ISSUE TITLE
Airflow dashboard missing hints

### ISSUE THREAD

**Issue by eeshugerman** [tridactyl/tridactyl#1390]
Airflow is a popular data pipeline orchestration framework, and a central feature is it's web dashboard. In Tridactyl 1.14.8, hints no longer appear for a main section of the dashboard.

1.14.7:
![screenshot from 2019-02-26 14-50-40](https://user-images.githubusercontent.com/25518211/53448965-f69fdd00-39d5-11e9-9d27-69a2f6f04708.png)

1.14.8:
![screenshot from 2019-02-26 14-49-35](https://user-images.githubusercontent.com/25518211/53448968-f7d10a00-39d5-11e9-9e95-431c38b70e5d.png)

HTML for the page in the screenshot: https://pastebin.com/uUW8fxsr
Full source (ie with javascript): https://pastebin.com/fZSt2asB

URL of website: N/A, self-hosted

Firefox version: 65.0.1

`:viewconfig`: https://pastebin.com/uM5yLRyq

trydactylrc: https://pastebin.com/vPVARhYL

Let me know if there's any more information I can provide.

**Comment by glacambre** [comment]
Ah, it seems https://github.com/tridactyl/tridactyl/pull/1381 changed the behavior of `:hint`. By default, `:hint` used to grab normal hints and js hints. With #1381, now it doesn't and you have to add `-J` for it to do.

Could you try `:hint -J` and see if the elements you need are hinted?

**Comment by glacambre** [comment]
Should be fixed by #1391. Let me know if it isn't.

**Comment by eeshugerman** [comment]
`:hint -J` works. Thanks!

**Comment by glacambre** [comment]
`:hint -J` will stop working and `:hint` alone will start working again once Tridactyl updates to the latest version :)

**Comment by eeshugerman** [comment]
Yep I'm using the "beta" builds and `:hint: is working today :+1:
