### ISSUE TITLE
":tutor" link is a 404

### ISSUE THREAD

**Issue by phmarek** [tridactyl/tridactyl#1392]
When doing `:help` and clicking on the `:tutor` link in the first paragraph, the address moz-extension://284755cd-b231-4ced-b522-b11d03db95e7/static/clippy/tutor.html gets opened - but is a 404.

Tridactyl 1.14.8, FF 65.0.1, on Debian AMD64 testing/unstable.

**Comment by glacambre** [comment]
Are you running the stable versions or the betas? (You can run `:tutor` in order to get to the tutorial btw.)

**Comment by phmarek** [comment]
I downloaded from addons.mozilla.org.

Thanks, `:tutor` works.
