### ISSUE TITLE
Move build bot / web server to VPS

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1398]
Several people report that they cannot access the beta builds internationally. We should move it to the VPS I have for a bunch of other things, potentially just as a forward that lets people access the current build bot.

**Comment by bovine3dom** [comment]
@cmcaine you like fiddling with this sort of thing, any bright ideas?

**Comment by cmcaine** [comment]
I wonder why we've been a blocked and if we can appeal.

We seem to be blocked from university of Leeds and uni of Manchester computers too.

**Comment by cmcaine** [comment]
But yeah, I can set up forwarding. We'll just wireguard and iptables. Forward me the VPS details.

**Comment by bovine3dom** [comment]
Issue was being caused by a recalcitrant VPN running on the box. Fixed.
