### ISSUE TITLE
Syntax for disabling All, or `j/k` for certain URLs?

### ISSUE THREAD

**Issue by llinfeng** [tridactyl/tridactyl#1407]
May I ask something quick here? What should I _say_ in the `~/.tridactylrc ` so that:
1. All keys are ignored on the domain: `mail.google.com`;
2. That certain keys, `j`, `k`, etc., are escaped for, say, `calendar.google.com`?

Thank you in advance.

**Comment by glacambre** [comment]
I think
```
autocmd DocStart mail.google.com mode ignore
unbindurl mail.google.com j
unbindurl mail.google.com k
```
Should do what you want. I'm not sure the autocmd will work if you open mail.google.com in a background tab though.

**Comment by llinfeng** [comment]
All works well! I don't even quite know how to load a URL through the background tab :) `T` now brings up the same `:tabopen url_current_page`.

Thank you for your quick reply!
