### ISSUE TITLE
Feature request: Ignoring a single keypress

### ISSUE THREAD

**Issue by JaniM** [tridactyl/tridactyl#1410]
Being able to toggle ignore mode is useful, but often enough ignoring a single keypress is what you want. For example, using `f` to go fullscreen in youtube, using `s` to focus the search in docs.rs, etc.

I propose a new command, `ignoreone`, which'd do exactly that: pass through a single keypress and then return to whatever mode was active before the command.

**Comment by glacambre** [comment]
I believe this has already been mentionned in https://github.com/tridactyl/tridactyl/issues/57 :).

**Comment by JaniM** [comment]
Maybe? I can't find a relevant comment.

**Comment by glacambre** [comment]
I thought the last two, mentionning pentadactyl's `<C-v>` keybinding, evoked the same feature as you just did here. Did I misunderstand something?

**Comment by bovine3dom** [comment]
@JaniM https://github.com/tridactyl/tridactyl/issues/57#issuecomment-433505945 it's ctrl-v

**Comment by JaniM** [comment]
Closing as a duplicate of #57 then :)

**Comment by bovine3dom** [comment]
#57 is open only for "ignore a single keypress", so the issues are sort of duplicates.
