### ISSUE TITLE
I couldn't open single quoted editorcmd.

### ISSUE THREAD

**Issue by octaltree** [tridactyl/tridactyl#1413]
*   Brief description of the problem:
error with a way of help about editorcmd ```set editorcmd 'terminator -u -e "vim %f"'```
*   Steps to reproduce:
With ```set editorcmd 'urxvt -e nvim %f'```, I couldn't open editor.
With ```set editorcmd urxvt -e nvim %f```, I could open the editor.
*   Tridactyl version (`:version`):
1.14.9-1.14.9
*   Firefox version (Top right menu > Help > About Firefox):l
66.0 (64-bit) Mozilla Firefox for Manjaro Linux
$ firefox --version
Mozilla Firefox 66.0.1
*   URL of the website the bug happens on:
https://www.google.com/search?client=firefox-b-d&q=hoge

**Comment by glacambre** [comment]
This is normal, you shouldn't use quotes if not needed when using `:set` since they'll be added literally to your setting. Just try `:set editorcmd terminator -u -e "vim '%f'"` or `:set editorcmd terminal -e nvim '%f'`.
