### ISSUE TITLE
No favicons with shydactyl

### ISSUE THREAD

**Issue by eeshugerman** [tridactyl/tridactyl#1419]
Not sure if this is known, and it's not a big deal, but figured I'd make note: The `shydactyl` theme does not show emoticons for the `tab` command.
shydactyl:
![image](https://user-images.githubusercontent.com/25518211/55094211-90ad8080-507b-11e9-991d-da23d00dcdfb.png)
default:
![image](https://user-images.githubusercontent.com/25518211/55094255-a9b63180-507b-11e9-9d9e-deed63b02164.png)
*   Tridactyl version (`:version`): 1.14.9-2-g1f12c31

*   Firefox version (Top right menu > Help > About Firefox): 65.0.1

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com): https://gist.github.com/eeshugerman/cdbfeefdbf895905ae20e180c71bc2a5

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
" bovine3dom's dogfood

" Provided only as an example.
" Do not install/run without reading through as you may be surprised by some
" of the settings.
 
" May require the latest beta builds.

" Move this to $XDG_CONFIG_DIR/tridactyl/tridactylrc (that's
" ~/.config/tridactyl/tridactylrc to mere mortals) or ~/.tridactylrc and
" install the native messenger (:installnative in Tridactyl). Run :source to
" get it in the browser, or just restart.

" NB: If you want "vim-like" behaviour where removing a line from 
" here makes the setting disappear, uncomment the line below.

sanitise tridactyllocal tridactylsync

"
" Binds
"

bind <C-k> tabnext
bind <C-j> tabprev
bind D tabclosealltoright

" Comment toggler for Reddit and Hacker News
" bind ;c hint -c [class*="expand"],[class="togg"]

" GitHub pull request checkout command to clipboard (only works if you're a collaborator or above)
" bind yp composite js document.getElementById("clone-help-step-1").textContent.replace("git checkout -b", "git checkout -B").replace("git pull ", "git fetch ") + "git reset --hard " + document.getElementById("clone-help-step-1").textContent.split(" ")[3] | yank

"
" Misc settings
"

set editorcmd 'gnome-terminal -e "%f"'

" Sane hinting mode
" set hintfiltermode vimperator-reflow

" Make Tridactyl work on more sites at the expense of some security
set csp clobber
fixamo_quiet

"
" URL redirects
" 

" New reddit is bad
autocmd DocStart www.reddit.com js tri.excmds.urlmodify("-t", "www", "old")
" Mosquito nets won't make themselves
autocmd DocStart www.amazon.co.uk js tri.excmds.urlmodify("-t", "www", "smile")

guiset hoverlink top-right

" This will have to do until someone writes us a nice syntax file :)
" vim: set filetype=vim:

colors shydactyl

set hintchars wertyuioasdfjkl;zxcnm
" set hintchars 1234567890
```

**Comment by glacambre** [comment]
This seems to be a [conscious choice](https://github.com/tridactyl/tridactyl/blob/0aaabe1b962aece8056d46debb3236ec5b501887/src/static/themes/shydactyl/shydactyl.css#L75-L76) from Shydactyl's creator so we probably shouldn't change it.

If you want favicons with shydactyl, I'd recommend creating your own theme based on it. There's a bit of information about doing that in `:help colourscheme`. I recognize that the documentation isn't perfect so feel free to ask questions should you need to.
