### ISSUE TITLE
Feature request: copy outer html and copy as markdown in hint mode

### ISSUE THREAD

**Issue by antislava** [tridactyl/tridactyl#1423]
Would like to add a possibility of copying the outerHTML or ultimately copying as markdown (using something like [turndown](https://github.com/domchristie/turndown) for example?) similar to copying element text `;p`.
Related: #1041

Isn't it relatively straightforward to implement (by adding the corresponding function(s) in [hinting.ts](https://github.com/tridactyl/tridactyl/blob/master/src/content/hinting.ts))?

**Comment by glacambre** [comment]
You could indeed implement it by making modifications to hinting.ts and excmds.ts. But if you're lazy, you can also do `:composite hint -pipe * outerHTML | yank`. Copying as markdown can probably be painfully made to work by piping to `js -p` before `yank` and performing the conversion yourself.

**Comment by antislava** [comment]
Thank you, `:composite hint -pipe * outerHTML | yank` works great already (with any command line tool conversion piping it to a file, which also provides better control over the conversion)! Will fix the shortcut in hinting.js if I end up using this feature a lot.
