### ISSUE TITLE
p / P searches if copying a URL from Excel, instead of opening clipboard contents

### ISSUE THREAD

**Issue by Noexpert** [tridactyl/tridactyl#1440]
Hi,

if this is not an issue, please feel free to close.

When opening the clipboard contents with `p` or `P` is Tridactyl supposed to recognise the pattern of the clipboard contents and then open the URL or search for the item, as appropriate?

For example, whether I copy `test` or `www.test.com`, Tridactyl always searches of the item, instead of searching for `test` and **opening** `www.test.com`.

Is this expected behaviour?

Thanks

**Comment by cmcaine** [comment]
This is unexpected.

If I copy "www.test.com"  and paste with p or P, I don't search for the
text, I open the page as you expect.

My version is: 1.14.6-56-ge62eae4

What's yours?

**Comment by cmcaine** [comment]
Tested with 1.14.9-13-g87adde1 too.

**Comment by Noexpert** [comment]
Indeed, you are correct.
Bizarrely, it now seems to work so closing this.

Thanks

**Comment by Noexpert** [comment]
OK I managed to replicate this.

It's very much an edge case, but if you type `www.test.com` into Excel, it will convert it to a hyperlink.
Then copy the cell (not the contents of the cell, but the cell itself) and try p or P in Tridactyl which will then search for `www.test.com`.

Probably a P4, but I'll reopen anyway.

**Comment by cmcaine** [comment]
Can you try pasting into some other applications and seeing what the pasted
text is?

**Comment by Noexpert** [comment]
I tried Word and it seems fine.
That and Excel are the only two applications I can think of that I would use in this context.

**Comment by Noexpert** [comment]
This is now resolved
