### ISSUE TITLE
Can not focus text area

### ISSUE THREAD

**Issue by vlmarek** [tridactyl/tridactyl#1443]
First of all, thank you for working on tridactly. It is a life saver to me.

*   Brief description of the problem:
Tridactyl does not allow to focus text area, but clicking on it works fine. For example:
https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/30/configure
There are two input boxes and a text area at the bottom. I can't find a way to edit the text area via external editor by using keyboard only. I can't find a way to focus the element. 

*   Steps to reproduce:

1. open https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/30/configure
2. click on the "search" textbox at the top
3. press escape and type :focusinput -n
4. next textbox is in focus
5. press escape again and type :focusinput -n
6. the "search" textbox is in focus again, not the main area below
7. if I click on the main area down, I can both type a text and run external editor <ctrl-i>

*   Tridactyl version (`:version`):
1.14.9-1.14.9

*   Firefox version (Top right menu > Help > About Firefox):
66.0 (64-bit)

*   URL of the website the bug happens on:
https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/30/configure

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
https://gist.github.com/vlmarek/1dd17984f0a4f03798a51aa607dc4e6c

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):
```
bindurl mrcarson.us.oracle.com.*[0-9]+/?$ <C-e> urlmodify -g -1 configure
bindurl mrcarson.us.oracle.com.*[0-9]+/(console|changes)/?$ <C-e> urlmodify -g -2 configure
```

I have taken a look at the code, and it could be that the field does not match INPUTTAGS_selectors so it is not considered.

I have tried to use focus the element via hint
```
hint -J;c [class*="CodeMirror-scroll"]
```
The element is highlighted (I believe) but it does not receive the focus.

I have tried to use javascript directly via
```
js document.getElementsByClassName("CodeMirror-scroll")[0].focus();
```
or
```
js document.getElementsByClassName("CodeMirror-scroll")[0].click();
```
But I didn't get into input mode and using "gi" just afeter does not select the text area.

I have tried accessing the the LAST_USED_INPUT variable via
```
js alert(LAST_USED_INPUT)
```
but that didn't work too. The idea is that I would assign an element via
```
js LAST_USED_INPUT=getElements....
```

Thank you
__ 
  Vlad

**Comment by antonva** [comment]
There are unresolved issues on how to interface with content rich editors such as CodeMirror.
The workaround would be to try and focus the textarea with something like 
`:js document.getElementsByClassName("CodeMirror")[0].firstChild.firstChild.focus()`
which at least on this site focuses the text area decently.

**Comment by vlmarek** [comment]
That indeed works, the element gets focus! But I just noticed that editing does not work.
```
composite js document.getElementsByClassName("CodeMirror")[0].firstChild.firstChild.focus() | editor
```
But I guess it's CodeMirror being annoyance here. It seems that I'm missing the first line in the temporary file opened by external editor.

Thank you for looking into this, I take it as a lost case :/

**Comment by antonva** [comment]
Yeah, I neglected to mention that. Sorry. That won't be fixed until we figure out a  decent way to interface with CodeMirror.

**Comment by vlmarek** [comment]
Hey, no problem, it was not hard to find out :) Thanks for looking into this!
