### ISSUE TITLE
Subsequent calls to :colors require page refresh

### ISSUE THREAD

**Issue by noctuid** [tridactyl/tridactyl#1444]
# Making a feature request

I'm trying to get the hints to look like they do in vimium (specifically the old pentadactyl vimium theme). I have no experience with CSS, and there are a lot of differences from pentadactyl themes, so it's been a trial and error process of changing one thing at a time. Right now there doesn't seem to be anyway to reload a theme after first using `:colors`. Every time I make a change to the file, I have to restart firefox to get those changes. Could a command or argument for `:colors` be added to actually reload the file from disk every time?

Also, is it possible to use something like `@import` to import css from another theme instead of having to copy the entire theme? If not, would this be something you would consider (I can make a separate feature request)?

**Comment by glacambre** [comment]
>Right now there doesn't seem to be anyway to reload a theme after first using :colors

Using `:colors` again will reload the theme but you'll have to reload the page. Not sure why this happens.

>Every time I make a change to the file, I have to restart firefox to get those changes.

You could also try to use Firefox's style editor (`Shift+F7` apparently). It will let you create a new stylesheet and re-render your modifications on the fly. You can then save the content of the stylesheet to a file and load it with `:colors`.

>Also, is it possible to use something like @import to import css from another theme instead of having to copy the entire theme? If not, would this be something you would consider (I can make a separate feature request)?

I thought it would be but apparently isn't. So what this would require is load the CSS file from disk, parse it and perform the imports manually (by loading additional files from disk with the native messenger or from extension storage with `fetch()`).

**Comment by noctuid** [comment]
Awesome! Thanks for the information/help. I got things looking a little nicer:
![tridactyl_vimium](https://user-images.githubusercontent.com/4250696/55751911-c7d54780-5a14-11e9-9de3-304a2cb1724f.png)

> I thought it would be but apparently isn't....

I'll make a separate issue about this.

**Comment by bovine3dom** [comment]
Feel free to make a PR adding your theme once you're happy with it :)

**Comment by noctuid** [comment]
It doesn't seem that it is possible to alter the firefox UI with themes (e.g. tab styling), correct?

**Comment by glacambre** [comment]
Correct. However it's possible to do that by modifying your `usechrome.css`. We could perhaps add a mechanism to do that right from a theme file.

**Comment by bovine3dom** [comment]
`:colours` hasn't required a page refresh for a while
