### ISSUE TITLE
[Feature Request]: hint option to emulate right click on links

### ISSUE THREAD

**Issue by pmaziere** [tridactyl/tridactyl#1454]
Is it possible to add an option to :hint so that it can open the context menu as it is done by a mouse right click ?
Use case: some extensions add a context menu entry to enable a specific action that is unreachable without a mouse

thanks

**Comment by bovine3dom** [comment]
I believe this isn't possible with web-extensions. Related: #28.

**Comment by bovine3dom** [comment]
I might have been wrong on this - https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event exists so we could fire fake mouse events that mimic a right click should websites allow it.

However, in practice, I have not been able to get this to work.

VVimpulation have code that claims to do a similar thing but I haven't been able to get that to work in their extension either. https://github.com/amedama41/vvimpulation/commit/3c1f0c05f5d7a0c5a01c2ee8e70a70c621476f4a

**Comment by pmaziere** [comment]
As suggested and pointed at by @bovine3dom  on IRC , one can adapt the following binding  : 
https://github.com/tridactyl/tridactyl/blob/da9bea7edf63dd3ec24bd44c120cb72d6530ee18/src/lib/config.ts#L1174

If xdotool is available on your system, in order to simulate a right click, one can bind a key combination with the following command:

`bind ;c hint -F e => { const pos = tri.dom.getAbsoluteCentre(e); tri.excmds.exclaim_quiet("xdotool mousemove --sync " + window.devicePixelRatio * pos.x + " " + window.devicePixelRatio * pos.y + "; xdotool click 3")}`

Here, if I understand correctly, hitting `;c` opens the context menu related to a clickable element.
I can successfully enjoy this new available feature now ! 

Thanks again to all tridactyl developers to make this great extension possible.

**Comment by PhillipChaffee** [comment]
Any more thoughts on this since 2021? I love this extension and have been wanting to get into the code base for a few weeks now. Thinking about taking a crack at this first, so any new context/thoughts/etc would be helpful.

**Comment by bovine3dom** [comment]
If you have :native and xdotool installed, all you need to do is add pmaziere's bind to src/lib/config.ts :)

For me it would be a ten second job, but I'm happy to leave it for you if you would like to get to grips with the codebase a little.
