### ISSUE TITLE
"open" opens a empty tab.

### ISSUE THREAD

**Issue by nvkrishna77** [tridactyl/tridactyl#1482]
*   Brief description of the problem: 
When I open an url (using :open xyz, where xyz can be an URL or search text), sometimes it leads to opening of an empty tab (with no tridactyl) and no relation to the expected webpage.

*   Steps to reproduce:

    1. Type :open test page  
    2.  Sometimes you will see the expected page, sometimes it will be an empty page.

*   Tridactyl version (`:version`): 1.14.9-1.14.9

*   Firefox version (Top right menu > Help > About Firefox): 66.0.2 (64-bit)

*   URL of the website the bug happens on: Any website. 

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
set newtab about:blank
```

*   Operating system: Mac OSX 10.14.4

**Comment by glacambre** [comment]
Hi, thanks for opening this issue. I'm fairly certain this is the same bug as https://github.com/tridactyl/tridactyl/issues/1237 , somehow excmds for the command line are executed twice, once with an argument, once without one and the time without an argument wins. I've spent countless hours trying to debug this and couldn't get farther than the conclusion I came to in https://github.com/tridactyl/tridactyl/issues/760#issuecomment-447642870 .
So we're very aware of this issue but don't know if or when it'll be fixed :(.

**Comment by nvkrishna77** [comment]
I do not understand the underlying details, and hence not able to correlate the bugs. But I will trust you.

I noticed something more: everytime such a blank tab is opened - if I close the "blank" tab, FF takes me to one of the previous tabs. And I see the following error message at the bottom of that tab:

# background_controller:  Error: Message manager disconnected 

Does it help in any way?

**Comment by nvkrishna77** [comment]
Hi.
I do not understand the underlying details to correlate the two bugs. But I will trust your judgement.

I found something else, that may be of some help. Everytime I close such a "blank" tab, FF takes me to a previously visited tab and at the bottom of the tab, I see the following error message:

# background_controller:  Error: Message manager disconnected 

Does this error message help in any way?

**Comment by glacambre** [comment]
>I do not understand the underlying details, and hence not able to correlate the bugs.

What happens is that `open` is ran twice, once without any arguments and once with the arguments you provided. Unfortunately, `open` without arguments is ran first and this loads the blank tab, which then prevents the "real" call to `open` to be executed. This causes the javascript promise created when the real `open` was about to be performed to be broken and thus results in the error message you're seeing.

Tridactyl recently went through a lot of internal changes. They haven't been published yet because the build bot is down, but I have the faint hope that once it is brought back up this bug will have magically disappeared.

**Comment by nvkrishna77** [comment]
Okay. This makes better sense. 

> Tridactyl recently went through a lot of internal changes. They haven't been published yet because the build bot is down, but I have the faint hope that once it is brought back up this bug will have magically disappeared.
> 

Keeping my fingers crossed. :-)



Krishna.

**Comment by bovine3dom** [comment]
I've never seen this bug. Has it magically disappeared? : )
