### ISSUE TITLE
Sanitize composite pipes to exclaim

### ISSUE THREAD

**Issue by jamesepatrick** [tridactyl/tridactyl#1485]
Hey all,

This is most likely a minor issue with a niche effected subset of users, but I've recently found out that composite piping to exclaim can allow for locally executing code via shell [command substitution](https://www.gnu.org/software/bash/manual/html_node/Command-Substitution.html).  I cannot currently find any work around to prevent this.

If you run

```
:composite hint -pipe code textContent | exclaim echo
```

on `I am an example $(touch ~/bad_bad_not_good)` it will append this to the echo command above. The `$(touch ~/bad_bad_not_good)` section will be executed via command substitution and you will end up a file at `~/bad_bad_not_good`. 

This will also works with zero font-sized text. For instance 

```html
<div>Example <span style="font-size:0pt;">$(rm -rf ~/)</span> Text</div>
```
with
```
:composite hint -pipe * textContent | exclaim echo
```

----

Version: 1.14.9-1.14.9

`printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` result : 2

Paths 
```2{"cmd": "run", "content": "/Users/james/.rbenv/shims:/Users/james/.scripts:/Users/james/.cargo/bin::/Applications/Postgres.app/Contents/Versi
ons/9.5/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin:
/usr/local/MacGPG2/bin:/opt/X11/bin:/Users/james/.rbenv/shims:/Users/james/.scripts:/Users/james/.cargo/bin:/Applications/Postgres.app/Content
s/Versions/9.5/bin:~/.scripts:/usr/local/opt/go/libexec/bin:~/.scripts:/usr/local/opt/go/libexec/bin:/Users/james/.fzf/bin\n", "code": 0}%```

**Comment by glacambre** [comment]
Yeah, we have a few hacks [here](https://github.com/tridactyl/tridactyl/blob/9b02a1ac223434c9198060e28ee9386b4e62d0c9/src/lib/native.ts#L377) and [there](https://github.com/tridactyl/tridactyl/blob/9b02a1ac223434c9198060e28ee9386b4e62d0c9/src/excmds.ts#L542) to prevent command injection but it'd be much better to provide a standard way to do that, use it everywhere and make it available to users.
Please note that for now you can do the escaping yourself by using js/jsb and following the guidelines for [rsscmd](https://github.com/tridactyl/tridactyl/blob/9b02a1ac223434c9198060e28ee9386b4e62d0c9/src/lib/config.ts#L700-L722).

**Comment by bovine3dom** [comment]
I'd add that this is somewhat by design.

We should just add a `sanitise` excmd that takes its input and outputs a sanitised output, mostly for use in pipes. Obviously we can't call it sanitise.

**Comment by bovine3dom** [comment]
Simply put `shellescape` between unsafe input in the latest betas - e.g. `composite js steal_your_bitcoins() | shellescape | exclaim echo`.

Uses https://github.com/dy/node-shell-quote which is a (somewhat) maintained fork of node-shell-quote. If people are concerned, we could adopt it ourselves.
