### ISSUE TITLE
cannot locate the config JSON

### ISSUE THREAD

**Issue by protrolium** [tridactyl/tridactyl#1486]
I want to edit the file that is displayed when I invoke :viewconfig but cannot find it on my system. I have a config file at ~/.tridactylrc and there is a binding that I accidentally made that I am trying to delete that is not present in .tridactlyrc 

The file in the current Firefox 

`profile/browser-extension-data/tridactyl.vim@cmcaine.co.uk/storage.js.migrated`

does not contain what I am looking for either. I have native installed. I'm a little confused, any clarification much appreciated!

macOS 10.13.6
FF 66.0.3

**Comment by glacambre** [comment]
I don't think you need to edit your config to remove bindings, `:unbind` and `:reset` should be enough. I think your config won't stored in a json file unless you `:set storageloc local`.

**Comment by bovine3dom** [comment]
The Firefox local storage is moving to SQLite either very soon, or it has already anyway.

**Comment by protrolium** [comment]
Okay I used unbind to try to remove the entry but it seems to have added an additional entry at the end of config. Obviously this binding was some blundering mistake I made:

`<SA-ArrowUp><SA-ArrowUp><SA-ArrowDown><SA-ArrowDown><SA-ArrowLeft><SA-ArrowRight><SA-ArrowLeft><SA-ArrowRight>ba | "open https://www.youtube.com/"
-- | --`

now after I used :unbind, at the end of the :viewconfig nmaps JSON it added this entry:
`<SA-ArrowUp><SA-ArrowUp><SA-ArrowDown><SA-ArrowDown><SA-ArrowLeft><SA-ArrowRight><SA-ArrowLeft><SA-ArrowRight>ba | ""
-- | --`

What I'd like to do is remove both of these from config. How do I do that?

**Comment by bovine3dom** [comment]
That bind is in Tridactyl by default - it's the Konami code, sort of. The latter entry is because we bind unbound key sequences to a no-op so that they overwrite default binds.

**Comment by bovine3dom** [comment]
Closing as storage is now in SQLite - see https://github.com/tridactyl/tridactyl/issues/79.
