### ISSUE TITLE
Scrolling not working on specific website

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#1492]
Tridactyl v1.14.9-13-g87adde1, website: https://www.notion.so/tinySelf-performance-gains-2019-4-ef0d6334f7fb4256a3f21cb90bd5db37
You need to click somewhere on the header in order to be able to scroll

**Comment by antonva** [comment]
It's more than just scrolling, no keybinds work at all unless you twiddle with it.

**Comment by bovine3dom** [comment]
`seturl [dodgy website here] preventautofocusjackhammer true` in Betas once I fix the negated boolean.
