### ISSUE TITLE
With ResistFingerprint enabled, Tridactyl can thwart other extensions keybinds

### ISSUE THREAD

**Issue by GIPeon** [tridactyl/tridactyl#1500]
Hello there!  
I've reported to [Ghacks user.js](https://github.com/ghacksuserjs/ghacks-user.js/issues/391#issuecomment-486137363) some issues with RFP and uBlock Origin shortcuts (and maybe this can affect other extensions too).  

The discussion followed [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/703) and the conclusion was indeed RFP can put some troubles with extension shortcuts, like you already reported in [760](https://github.com/tridactyl/tridactyl/issues/760#issuecomment-433679201), but in this specific scenario I confirmed that with RFP enabled and Trid *disabled*, the shortcut for uBlock is working properly. Leaving Trid enabled will instead prevent the correct working of the shortcut. This only with RFP enabled ofc.

* Steps to reproduce:
1. Enable RFP
2. Try to set a shortcut in the uBO utility settings -> won't work (see gif attached [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/703))
3. Disable RFP
4. Try to set a shortcut in the uBO utility settings -> (should) work
5. Re-enable RFP
6. Try shortcut on any web page -> won't work
7. Disable Tridactyl
8. Try shortcut on any web page -> (should) work. *Remember that RFP is enabled*.

* Tridactyl version: `1.14.9-1.14.9`

* Firefox version: `66.0.3 (64-bit)`

* Configs: no custom config, fresh installed

Thank you for your time!

**Comment by bovine3dom** [comment]
This really sounds like a Mozilla issue. All one can do is make a minimum working example (two tiny extensions that conflict in this manner) and submit an issue to bugzilla as we've done for some others in #760.

**Comment by cmcaine** [comment]
Does ubo shortcut + tridactyl - rfp work?

We do eat keypresses that we think are for us, but I imagine ubo uses the commands API to receive events, and we don't interfere with that.

If they don't use the commands API and rfp mangles the keyevent enough that tridactyl thinks it's for us instead that could be something we can fix, but sounds like a Firefox problem.

**Comment by GIPeon** [comment]
> Does ubo shortcut + tridactyl - rfp work?

Yes!  This was my main issue trying to debug this RFP issue in the beginning, Tridactyl never actually interfered with any other extension I use without RFP, so I didn't really suspected it could cripple something.
  
Also reading more carefully your docs I eventually found about the _ignore_ mode. I can confirm that with RFP _enabled_ and entering ignore, the uBO shortcut works.

Thank you for your time!

**Comment by bovine3dom** [comment]
Closing as I really don't think we can do anything about this :)
