### ISSUE TITLE
remove some letters from "f" hints

### ISSUE THREAD

**Issue by GianniGi** [tridactyl/tridactyl#1537]
When following a link after pressing "f", sometimes you need to press some awkwards key combinations, which are very slow to type. Some other plugins allow to define which letters do you want to use. Personally I'm ok with all the letters, but I find the combinations that need to be pressed with only one index particularly slow, for example: yj, bf etc.

**Comment by antonva** [comment]
Does `hintchars` not cover this use case?

**Comment by bovine3dom** [comment]
You should be able to mitigate it with some cunning hintchars - we use them preferentially in the order that they are set, so

`set hintchars fjdksla` should give you more alternating keys than `set hintchars jklfdsa`.

**Comment by GianniGi** [comment]
Thank you, this addon is fantastic.

**Comment by GianniGi** [comment]
The fact that the hints aren't optimized and aren't shown clearly in a readable way, is what makes you stop using them forever. When for example, in some forums, there are so much overlapping hints that it makes everything unreadable, well, you just stop using them. I'll search past bug reports and see if something else can be reported.

**Comment by glacambre** [comment]
You can control what elements should get hints with `hint -c` (see `:help hint`). You can the use `bindurl url f hint -c selector` to have `f` only highlight the hints you need on a specific website. There's an [example here](https://github.com/tridactyl/tridactyl/blob/8d315357f3a86ffb6075643fae1cef072808f128/.tridactylrc#L39).

**Comment by bovine3dom** [comment]
What version are you using? Current is 1.14.10. We removed lots of useless hints a few months ago. It's possible you're on an old version.

**Comment by GianniGi** [comment]
I confirm that I'm using the last version.
If you go here, you see that the "pages" links on the top left are so cluttered that they're unreadable, one coutld be satisfied in having only two links highligted: the last page of the thread, and the next page link.
https://geekhack.org/index.php?PHPSESSID=1he3fac0lu1if8jo47jrvl91908sierd&topic=99002.0

**Comment by glacambre** [comment]
`bindurl geekhacks.org f hint -c span ~ a.navPages, .nextlinks > a` does what you want I think.

**Comment by GianniGi** [comment]
not exactly :-/ it broke the site :-D 
now it underlines only a couple of links at all, in the whole page :-/

**Comment by glacambre** [comment]
Oh, ok, I misunderstood what you meant. `bindurl geekhack.org f hint -c a:not(.navPages), span + a.navPages` should work.

**Comment by bovine3dom** [comment]
The page looks OK to me; I don't really think we can improve it much without jiggling hints around (which we have other issues open for, I believe). Closing this issue - thanks for reporting :)
