### ISSUE TITLE
How to delete tridactylrc config

### ISSUE THREAD

**Issue by RidaAyed** [tridactyl/tridactyl#1542]
Tridactyl version: 1.14.10-220-g12f1c68
Firefox version: Mozilla Firefox 66.0.3
Operating system: linux

*   Brief description of the problem:
After deleting tridactylrc the config remains on it. I checked all possible locations e.g. `~` `~/.config/~` `$XDG_HOME`

*   Steps to reproduce:

1. Setup nativenstall and download the example [tridactylrc](https://github.com/tridactyl/tridactyl/blob/master/.tridactylrc) to `~/.tridactylrc` 
2. Delete `~/.tridactylrc` 
2. Restart (firefox, window manager, even the machine)
3. Firefox `:viewconfig`  still displays the deleted file settings and acts on it

*   URL of the website the bug happens on:

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
Insert tridactylrc contents between the backticks
```

*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:
`\0\0{"cmd": "run", "content": "/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl\n", "code": 0}
`

**Comment by bovine3dom** [comment]
`:sanitise tridactylsync` should wipe _all_ your settings.

The RC file and the in-browser settings all go to the same place, so there's no way on distinguishing them.
