### ISSUE TITLE
Tridactyl breaks acm.org

### ISSUE THREAD

**Issue by cowile** [tridactyl/tridactyl#1543]
Tridactyl version: 1.14.10-186-gae6deb0
Firefox version: Mozilla Firefox 66.0.4
Operating system: linux

NOTE: Problem resolved by seturl acm.org noiframe true

*   Brief description of the problem: Visiting Association of Computing Machinery official website results in the loaded page flashing followed by a blank window. 

*   Steps to reproduce:

    1. With tridactyl enabled, visit acm.org

*   URL of the website the bug happens on: https://www.acm.org

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com): https://gist.github.com/cowile/778d735398f7174fc444a235721bc46a

**Comment by bovine3dom** [comment]
Can anyone reproduce this? It works fine for me without noiframeon.

**Comment by antonva** [comment]
Works here, except the content is like a whole page down below the page you land on.

**Comment by cowile** [comment]
On repeat inspection, my issue is the same as what @antonva describes. All content is available after scrolling down.

So I guess the website is less "broken" and more "disfigured". This is still a bug, but less severe than I thought.

**Comment by bovine3dom** [comment]
Either we fixed it or they did
