### ISSUE TITLE
Error: You found a bug! 

### ISSUE THREAD

**Issue by thrisp** [tridactyl/tridactyl#1548]
Tridactyl version: 1.14.10-186-gae6deb0
Firefox version: Mozilla Firefox 66.0.5
Operating system: linux

I get this error two days in a row, and I don't know what is causing it in any way, I will look back at a tab and its there. Yesterday the tab crashed and I had restart firefox, but I just found it and so far nothing noticeable is happening:

`# controller in excmd:  Error: You found a bug! Tridactyl should have been able to match the profile you're using with the profiles found in "/home/name/.mozilla/firefox/profiles.ini" but it couldn't. Please report this issue on https://github.com/tridactyl/tridactyl/issues .`

seems related to #1529 so I'll close it

**Comment by SRGOM** [comment]
I get this on `guiset tab always`

**Comment by glacambre** [comment]
@SRGOM What Tridactyl version are you using?
