### ISSUE TITLE
:native command works, but all of its funcitons do not

### ISSUE THREAD

**Issue by JeremyStepp** [tridactyl/tridactyl#1558]
Tridactyl version: 1.14.10-186-gae6deb0
Firefox version: Mozilla Firefox 66.0.5
Operating system: linux

I have done nativeinstall and the :native command works, but whenever I try to use commands that native enables I get errors. The error I get for the :fixamo command is ` # controller in excmd: Error: You found a bug! Tridactyl should have been able to match the profile you're using with the profiles found in "/home/jeremy/.mozilla/firefox/profiles.ini" but it couldn't. Please report this issue on https://github.com/tridactyl/tridactyl/issues .` I have tried restarting my browser. Please tell me if I need to provide more info.

*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:

    *  `/home/jeremy/torch/install/bin:/home/jeremy/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin` 
*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:

    * `�{"cmd": "run", "content": "/home/jeremy/anaconda3/bin:/home/jeremy/anaconda3/condabin:/home/jeremy/torch/install/bin:/home/jeremy/.pyenv/plugins/pyenv-virtualenv/shims:/home/jeremy/.pyenv/shims:/home/jeremy/.pyenv/bin:/home/jeremy/torch/install/bin:/home/jeremy/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin\n", "code": 0}`

**Comment by glacambre** [comment]
You're using an old Tridactyl version, the current one is `1.14.10-263-g046df89`. Could you update and let us know if you can still reproduce this issue?

**Comment by JeremyStepp** [comment]
Using the latest version seems to have fixed the issue.
