### ISSUE TITLE
Is it possible to hide status bar from right bottom corner?

### ISSUE THREAD

**Issue by wh75er** [tridactyl/tridactyl#1559]
When I'm watching youtube or something like that(in fullscreen mode) I want to hide a status bar with text from right bottom corner. Is it possible to do it?

**Comment by glacambre** [comment]
Do `:set modeindicator false` or `:seturl youtube.com modeindicator false` do what you want?

**Comment by wh75er** [comment]
@glacambre thats what I need. Thank you!
