### ISSUE TITLE
guiset doesn't work

### ISSUE THREAD

**Issue by wh75er** [tridactyl/tridactyl#1563]
I'm using Mozilla Firefox 66.0.5
tridactyl ver. 1.14.10-186-gae6deb0
OS: linux
When I use guiset to remove gui:
` :guiset gui none`
I'm getting:
`userChrome.css written. Please restart Firefox to see the changes.`
and then
`# controller while accepting: Error: Unknwown namespace: userChrome. `
I have the same error with different args (e.g. _tabs autohide_ or _tabs none_)

It doesn't edit my  ~/.mozilla/firefox/<profile_name>/chrome/userChrome.css file anyway.

**Comment by wh75er** [comment]
Alright, the problem has been solved, I've installed trida native messenger, but then I get other error:

`guiset gui none`

`# controller in excmd: Error: You found a bug! Tridactyl should have been able to match the profile you're using with the profiles found in "/home/wh75er/.mozilla/firefox/profiles.ini" but it couldn't. Please report this issue on https://github.com/tridactyl/tridactyl/issues . `

My profiles.ini file:
```
[General]
StartWithLastProfile=1

[Profile0]
Name=default
IsRelative=1
Path=9krqk7qr.default-1542046840114
Default=1
```

**Comment by glacambre** [comment]
Hi, thanks for reporting this issue. You're using an old tridactyl version, could you try upgrading and see if you can still reproduce this?

**Comment by wh75er** [comment]
Yep, thank you! After update to 1.14.10-270-g938b71d, everything works fine.
