### ISSUE TITLE
`nativeopen` errors on Win FF67

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1566]
Tridactyl version: 1.14.10-270-g938b71d
Firefox version: Mozilla Firefox 67.0
Operating system: win

Any `nativeopen` gives me this pop-up:

![](https://i.imgur.com/qNG1Gw8.png)

**Comment by glacambre** [comment]
I can't reproduce this on FF67+1.14.10-280.
If you can still reproduce this after updating Tridactyl, could you upload the content of your `profiles.ini`?

**Comment by bovine3dom** [comment]
Still reproducible. Profiles.ini:

```
[Install308046B0AF4A39CB]
Default=Profiles/gwm76nmk.default
Locked=1

[Profile1]
Name=testing
IsRelative=1
Path=Profiles/kelk7aie.testing

[Profile0]
Name=default
IsRelative=1
Path=Profiles/gwm76nmk.default
Default=1

[General]
StartWithLastProfile=1
Version=2
```
