### ISSUE TITLE
nonewtab build history completions broken

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1569]
Tridactyl version: 1.14.10-93-g1076577
Firefox version: Mozilla Firefox 67.0
Operating system: win

Steps to reproduce:

1. Use https://tridactyl.cmcaine.co.uk/betas/nonewtab/tridactyl_no_new_tab_beta-latest.xpi
2. `t` shows empty completions
3. `<Tab>` gives `# Error processing next_completion() TypeError: this.options is undefined`

**Comment by cmcaine** [comment]
This needs to be changed:

src/completions/History.ts
104:        const newtaburl = browser.extension.getURL(newtab)

**Comment by cmcaine** [comment]
Probably fixed in 65de30fe6cdd7db5ffbac1e834bf01dc4e0bf8ef
