### ISSUE TITLE
Tridactyl broken by Firefox 67

### ISSUE THREAD

**Issue by benplumley** [tridactyl/tridactyl#1583]
*   Brief description of the problem:

None of Tridactyl's features work at all after updating to Firefox 67. Firefox's behaviour is identical with Tridactyl disabled as enabled.

---
@bovine3dom edit: Hijacked for workaround

If you're on Tridactyl beta just click [this link](https://tridactyl.cmcaine.co.uk/betas/tridactyl-latest.xpi) to reinstall Tridactyl, which should fix the issue. If you're on Tridactyl stable, just reinstall by clicking the big button on the Mozilla Add-ons site: 

https://addons.mozilla.org/en-GB/firefox/addon/tridactyl-vim/

---

*   Steps to reproduce:

Install Tridactyl on Firefox 67. Try using any Tridactyl shortcut or open a new tab. Tridactyl does nothing. Pressing `:` does not open a prompt.

*   Tridactyl version (`:version`):

I can't run this 🙃 1.15.0 (latest) according to the Add-on manager.

*   Firefox version (Top right menu > Help > About Firefox):

Quantum 67.0 64-bit

*   URL of the website the bug happens on:

All/any.

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com): Can't run this

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
Doesn't exist
```

*   Operating system: Windows 10 1809
*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:

I can't run this in Tridactyl so I'm just running it on the command line. Also, no idea whether this has anything to do with the native executable, but I know I have it installed.
```
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\bjp\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\OpenVPN\bin;
```

What I've already tried: Updating Firefox, updating Tridactyl, re-enabling Tridactyl, restarting Firefox

**Comment by jamesepatrick** [comment]
Same here. Extension still exist, but is non-functional. OS is Linux (Arch).

**Comment by eailfly** [comment]
Same here, OS is Mac

**Comment by glacambre** [comment]
Hi, thanks for opening this issue. Somebody on IRC mentionned that they also had this issue and fixed it by removing and re-installing Tridactyl. Could you try that?

**Comment by benplumley** [comment]
I was hesitant to remove it because I thought I'd lose my config, which I couldn't export due to not being able to open the command line. I've removed and re-added it and it's now working again, and my config wasn't lost.

Note that you need to restart Firefox **between** removing and reinstalling Tridactyl or this workaround won't work.

**Comment by glacambre** [comment]
Great, thanks for reporting back :)

Just out of curiosity, did opening a new tab open Tridactyl's newtab page?

**Comment by benplumley** [comment]
Before reinstalling, no, it opened a blank page (my Firefox setting with no extensions). Now that I've reinstalled, it's opening the Tridactyl new tab page again.

**Comment by eailfly** [comment]
No, it just show the firefox's default homepage

**Comment by snippins** [comment]
I didn't remove anything, just install again and it works (Ubuntu 18.04, beta version).

**Comment by bovine3dom** [comment]
Yeah, I had to reinstall Tridactyl on two machines after updating to FF67. The options button and Tridactyl logo disappeared on about:addons.

**Comment by alwayswimmin** [comment]
> Note that you need to restart Firefox *between* removing and reinstalling Tridactyl or this workaround won't work.

Not sure if it's just because I'm on Mac, but I didn't need to restart Firefox.

**Comment by cmcaine** [comment]
If you experience this issue, please check the browser console (not the web console) and copy any messages you get into this issue before you try the workaround.

**Comment by cmcaine** [comment]
Browser console errors for me:

```
Error while loading 'jar:file:///home/colin/.mozilla/firefox/9697a1j0.nofuckups/extensions/staged/tridactyl.vim.betas@cmcaine.co.uk.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND) Extension.jsm:467
1558860365178	addons.xpi	WARN	Exception running bootstrap method startup on tridactyl.vim.betas@cmcaine.co.uk: Error: Error while loading 'jar:file:///home/colin/.mozilla/firefox/9697a1j0.nofuckups/extensions/staged/tridactyl.vim.betas@cmcaine.co.uk.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND)(resource://gre/modules/Extension.jsm:467:18) JS Stack trace: readJSON/</<@Extension.jsm:467:18
onStopRequest@NetUtil.jsm:123:17
```

```
OpenGL compositor Initialized Succesfully.
Version: 3.0 Mesa 19.0.5
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) Sandybridge Mobile 
FBO Texture Target: TEXTURE_2D

1558860366191	addons.xpi-utils	DEBUG	Starting async load of XPI database /home/colin/.mozilla/firefox/9697a1j0.nofuckups/extensions.json
1558860366422	addons.xpi	DEBUG	Existing add-on @mendeleyimporter in app-profile
1558860366423	addons.xpi	DEBUG	Existing add-on {7a7a4a92-a2a0-41d1-9fd7-1e92480d612d} in app-profile
1558860366423	addons.xpi	DEBUG	Existing add-on marcoagpinto@mail.telepac.pt in app-profile
1558860366423	addons.xpi	DEBUG	Existing add-on langpack-en-GB@firefox.mozilla.org in app-profile
1558860366423	addons.xpi	DEBUG	Existing add-on zotero@chnm.gmu.edu in app-profile
1558860366423	addons.xpi	DEBUG	Existing add-on https-everywhere@eff.org in app-profile
1558860366423	addons.xpi	DEBUG	Existing add-on jid1-xUfzOsOFlzSOXg@jetpack in app-profile
1558860366424	addons.xpi	DEBUG	Existing add-on formhistory@yahoo.com in app-profile
1558860366424	addons.xpi	DEBUG	Existing add-on tridactyl.vim@cmcaine.co.uk in app-profile
1558860366424	addons.xpi	DEBUG	Existing add-on uBlock0@raymondhill.net in app-profile
1558860366424	addons.xpi	DEBUG	Existing add-on tridactyl.vim.betas.nonewtab@cmcaine.co.uk in app-profile
1558860366425	addons.xpi	DEBUG	Existing add-on tridactyl.vim.betas@cmcaine.co.uk in app-profile
1558860366426	addons.xpi	DEBUG	Existing add-on formautofill@mozilla.org in app-system-defaults
1558860366426	addons.xpi	DEBUG	Existing add-on fxmonitor@mozilla.org in app-system-defaults
1558860366426	addons.xpi	DEBUG	Existing add-on screenshots@mozilla.org in app-system-defaults
1558860366426	addons.xpi	DEBUG	Existing add-on webcompat-reporter@mozilla.org in app-system-defaults
1558860366427	addons.xpi	DEBUG	Existing add-on webcompat@mozilla.org in app-system-defaults
1558860366427	addons.xpi	DEBUG	scanForChanges changed: false, state: {}
1558860366524	addons.xpi-utils	DEBUG	Finished async read of XPI database, parsing...
Error: url.match(...) is null msg.js:228:27
unreachable code after return statement content-firefox-bundle.js:7844:4
Error: listener not re-registered
ExtensionCommon.jsm:2173:24
1558860367013	addons.manager	DEBUG	Registering upgrade listener for formautofill@mozilla.org
unreachable code after return statement content-firefox-bundle.js:7844:4
Unkown category for SetEventRecordingEnabled.
Error: Missing host permission for the tab
undefined
unreachable code after return statement
content-firefox-bundle.js:7844:4
1558860368013	addons.xpi-utils	DEBUG	Successfully read XPI database
listener not re-registered
ExtensionCommon.jsm:2173
Error: WebExtension context not found! ExtensionParent.jsm:1041:13
OpenGL compositor Initialized Succesfully.
Version: 3.0 Mesa 19.0.5
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) Sandybridge Mobile 
FBO Texture Target: TEXTURE_2D
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20initial%2C%20length%2C%20actor%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
```

Only the beta build is broken like this. No new tab build and the stable build load okay. Stable build doesn't override new tab page for some reason (but ff does give me the "an extension has changed your new tab page" dialogue).

**Comment by thmsaurel** [comment]
Hi,

I've this issue, on a windows and a linux installation. I think it's came from the internal tag of firefox version.

When I go into the addon page of tridactyl, I can't reinstall it because I "don't use the newer version of firefox". It say my version is the 60.0. (on both computer, the version given by "help > about firefox" is 67.0)

**Comment by bovine3dom** [comment]
I think I just replied to you on Reddit - pick an old version from https://addons.mozilla.org/en-GB/firefox/addon/tridactyl-vim/versions/ which supports your "version" of Firefox.

I suggest you report your wrong version bug here: https://github.com/mozilla/addons/issues. Thanks :)

**Comment by thmsaurel** [comment]
Thx for your answer on [reddit](https://www.reddit.com/r/firefox/comments/btiwnz/firefox_67_after_upgrade_some_plugin_stop_to_work/?utm_source=share&utm_medium=web2x).

Like another answer say, I configure firefox to resist fingerprinting. So, my tag version version was the version of Firefox ESR (60.0).
I've remove disable the option (about:config > privacy.resistfingerprinting), reinstall tridactyl and reactivate the option.

Works well.

**Comment by glacambre** [comment]
@thmsaurel In case you encounter issues with binding chorded keys, know that Tridactyl [doesn't work well with privacy.resistfingerprinting](https://github.com/tridactyl/tridactyl/issues/760#issuecomment-433679201).

**Comment by xbmute** [comment]
Firefox 67.0 on Linux, I removed/reinstalled several times, both stable and beta. It still does not load.

I am using **Always use private browsing mode** under _Preferences -> Privacy & Security._

One is unable to set the option **Allow In Private Window**.  Clicking on Tridactyl _Preferences_ didn't bring up the about:addons windows but instead the following: moz-extension://static/docs/classes/_src_lib_config_.default_config.html

**Comment by cmcaine** [comment]
@xbmute Instead of clicking preferences, just try clicking on the surrounding box. i.e. click on the word "Tridactyl" or something.

**Comment by xbmute** [comment]
That did it. Loaded and working again. Thank you, @cmcaine

**Comment by seren** [comment]
FYI, I ran into the same issue (Mac OS). I see this in the browser console:
```
Error while loading 'jar:file:///Users/seren/Library/Application%20Support/Firefox/Profiles/p0tsl9pk.default/extensions/staged/tridactyl.vim@cmcaine.co.uk.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND) Extension.jsm:467
    readJSON resource://gre/modules/Extension.jsm:467
    onStopRequest resource://gre/modules/NetUtil.jsm:123
```
and
```
1559069208187	addons.xpi	WARN	Exception running bootstrap method startup on tridactyl.vim@cmcaine.co.uk: Error: Error while loading 'jar:file:///Users/seren/Library/Application%20Support/Firefox/Profiles/p0mlt3qj.default/extensions/staged/tridactyl.vim@cmcaine.co.uk.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND)(resource://gre/modules/Extension.jsm:467:18) JS Stack trace: readJSON/</<@Extension.jsm:467:18
onStopRequest@NetUtil.jsm:123:17
```

**Comment by Sberlos** [comment]
Tridactyl beta, Arch Linux:
`Error while loading 'jar:file:///home/sberlos/.mozilla/firefox/df89axlh.default-1441473731222-1539876961295/extensions/staged/tridactyl.vim.betas@cmcaine.co.uk.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND) Extension.jsm:467
1559381354208	addons.xpi	WARN	Exception running bootstrap method startup on tridactyl.vim.betas@cmcaine.co.uk: Error: Error while loading 'jar:file:///home/sberlos/.mozilla/firefox/df89axlh.default-1441473731222-1539876961295/extensions/staged/tridactyl.vim.betas@cmcaine.co.uk.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND)(resource://gre/modules/Extension.jsm:467:18) JS Stack trace: readJSON/</<@Extension.jsm:467:18
onStopRequest@NetUtil.jsm:123:17
Unkown category for SetEventRecordingEnabled.
cookies is undefined cookies.js:105
Unchecked lastError value: Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set. vapi-background.js:695
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. fingerprinting.js:316
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. socialwidgets.js:457
Key event not available on some keyboard layouts: key=“r” modifiers=“accel,alt” id=“key_toggleReaderMode” browser.xul
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xul
`

Clicking on the link in the first post for reinstalling the extension solved the issue immediately without needing to restart.

**Comment by sunjon** [comment]
I'm getting similar issues:

*Browser:* Firefox 71.0
*OS:* macOS Catalina
*Tridactyl Version:*  1.17.1pre3418

On manual source of `.tridactylrc`
```
[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 75"  data: no] 12 ExtensionCommon.jsm:75:12
    runSafeSyncWithoutClone resource://gre/modules/ExtensionCommon.jsm:75
    cssPromise resource://gre/modules/ExtensionContent.jsm:525
    InterpretGeneratorResume self-hosted:1150
    AsyncFunctionNext self-hosted:689
```

and when the settings unload (opening a new tab, changing current tab content, etc):

```
Promise resolved while context is inactive
content.js:26488
    getAsync moz-extension://5a2bbc66-c921-2745-9d2e-b7b75010398d/content.js:26488
```

**Comment by bovine3dom** [comment]
Have reduced the priority of this as presumably very few people will be upgrading to FF67 now that we have left it so long.

**Comment by jamesepatrick** [comment]
@bovine3dom: I don't know what tridactyl policy for closing tickets but there hasn't the most recent directly related comments was a year ago to the date, and I don't think there will be a noticeable number of people upgrading to FF67.
