### ISSUE TITLE
Can't scroll on reddit

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#1587]
Tridactyl version: 1.15.0-2-gf1b0ba3
Firefox version: Mozilla Firefox 69.0a1
Operating system: linux

Steps to reproduce:
- `tabopen https://www.reddit.com/r/vim`
- Click on a post
- Try to scroll with `j`/`k`

What happens here is that scrolling actually works but the scrolled element is the `<html>` element itself, which can be infinitely scrolled. So `recursiveScroll` manages to scroll it and thinks it's done.

No idea how to fix this. We would need a way to visually identify whether the page has changed or not after a `recusriveScroll()` call.
Related issue: https://github.com/tridactyl/tridactyl/issues/35

**Comment by ar1a** [comment]
+1, would love to see this addressed!

**Comment by cmcaine** [comment]
I was never able to find the code, but firefox must have an algorithm for deciding how to scroll the page on arrow down, etc.

It would be real useful if someone could find that code.

Here are some potential starting points:

Mozilla IRC irc.mozilla.org

https://searchfox.org/mozilla-central/search?q=scroll&path=
https://searchfox.org/mozilla-central/source/gfx/layers/apz/src/KeyboardScrollAction.cpp#12
https://searchfox.org/mozilla-central/source/layout/generic/nsIScrollableFrame.h#53

**Comment by glacambre** [comment]
I'm not sure we can 100% copy what Firefox does as sometimes we do better (https://github.com/tridactyl/tridactyl/issues/826).

**Comment by cmcaine** [comment]
I didn't know about that. There are definitely a bunch of cases where firefox does better than us, however. I think it would still be worth investigating what they do.

**Comment by glacambre** [comment]
@cmcaine Do you know of any websites where firefox does better than us without user interaction?

**Comment by bovine3dom** [comment]
This seems to work fine for me after #1805.

**Comment by rddunphy** [comment]
Just to check, the fix for this is to focus the scrollable element with `;;`, right? Is there anyway to automatically do this when the page loads?

**Comment by bovine3dom** [comment]
Yes, `;;` is the fix. I'd recommend using `old.reddit.com` though as it plays much more nicely with Tridactyl (and computers in general). I have a redirect set up: https://github.com/tridactyl/tridactyl/blob/49c887222b72f7848957ba173a80037c49f29f57/.tridactylrc#L149

Usually the way to focus an element when a page loads would be to use a `DocLoad` autocmd. New reddit, however, doesn't use page loads so you'd need to use our `UriChange` event instead. In itself that uses a little bit of CPU though so it's not recommended.

`:autocmd [event] [URL regex] js [element].focus()` is what you need to do in general. But reddit uses nonsense IDs for the comment divs so working out which element you need to focus programmatically is not going to be fun.

**Comment by rddunphy** [comment]
Thanks, in that case I'll give old Reddit a try.

**Comment by rddunphy** [comment]
Old Reddit wasn't really doing it for me, so I had a go getting new Reddit to work - thought I'd share the results here in case it helps someone else.

When you open a comment from the timeline, the comment page has a wrapper div with ID `overlayScrollContainer`. If you navigate directly to a comments page (e.g. from Google), apparently there's no div with that ID - but this is fine since the focus seems to be correct here in any case.
```
autocmd UriChange ^http(s?)://www.reddit.com js document.getElementById("overlayScrollContainer")?.focus();
```

Even with the focus fixed, Reddit only registers `scrollline`, not `scrollpage` - so I've also added these bindings:
```
bindurl ^http(s?)://www.reddit.com <C-d> scrollline 45
bindurl ^http(s?)://www.reddit.com <C-u> scrollline -45
```
