### ISSUE TITLE
Add pattern match for generated files to gitignore

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1594]
Pattern is probably `\..*\.generated\.ts`.

This is mostly for @saulrh's benefit :)

**Comment by saulrh** [comment]
We already have `generated`, which does the right thing. The issue is that the compiler doesn't pay any attention to `.gitignore`, so it tries to compile generated files from old branches which refer to files that no longer exist. :P

**Comment by saulrh** [comment]
(at least, it _should_ be doing the right thing now that you reminded me to put everything in a `generated` directory. Did I miss something? >_>)

**Comment by bovine3dom** [comment]
On my version of Tridactyl we have generated files all over the place :man_shrugging:

**Comment by saulrh** [comment]
Ah. Oops, sorry.
