### ISSUE TITLE
Tridactyl breaks tiddlywiki on FF67

### ISSUE THREAD

**Issue by nthorne** [tridactyl/tridactyl#1599]
Tridactyl version: 1.15.0-24-g3607057
Firefox version: Mozilla Firefox 67.0
Operating system: linux

Attempting to edit a page, and pressing any key other than enter gives the following error:

    # An error occurred in the content controller: TypeError: keyEvent.key is undefined 

Below fixed the issue.

    :seturl file:///<URL> noiframe true

**Comment by bovine3dom** [comment]
Sounds like another thing that #639 would fix. Closing in favour of that issue.
