### ISSUE TITLE
Pressing <F1> doesn't open help

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1606]
Tridactyl version: 1.15.0pre2784-b098e76
Firefox version: Mozilla Firefox 67.0
Operating system: linux

Instead, it adds a literal "F1" to the command line, waiting for you when you open it with `:`.

**Comment by notJerl** [comment]
This happens for all F keys, and dumps the plaintext name of the F key after the command for any command that opens the commandline (e.g. `<F11><t>` ends up filling the commandline with `:tabopen F11`).

**Comment by bovine3dom** [comment]
Consensus in chez pique is that it's probably @saulrh's fault - introduced with counts in the parser.
