### ISSUE TITLE
Trying to scroll with repeat makes Tridactyl hang

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1607]
Tridactyl version: 1.15.0pre2784-b098e76
Firefox version: Mozilla Firefox 67.0
Operating system: linux

I was just following `tutor`. Not a great initial experience...

Steps to reproduce:

`j.` - Tridactyl/Firefox will hang and eventually give you the error `# controller in excmd: InternalError: too much recursion`.

@saulrh, any ideas? :)

**Comment by aasril** [comment]
Hi, I want to report that I'm still having the same issue with repeat. Tried with scrolling and zooming. Firefox will freeze for few seconds and then tridactyl will throw said error message.

Tridactyl version: 1.15.0pre2785
Firefox: 67.0 (Linux Mint)

**Comment by glacambre** [comment]
@aasril , could you try updating to Tridactyl v1.15.0pre2798 and telling us if you can still reproduce this bug after that?

**Comment by aasril** [comment]
@glacambre , yup the new one works, thank you! 

I want to note that installing the new version over the older (despite the installation was completed with no error) but it didn't change the version I could see in the add-on page. I had to remove the tridactyl first before reinstalling.
