### ISSUE TITLE
Find state doesn't update lastSearchQuery when changing tabs

### ISSUE THREAD

**Issue by antonva** [tridactyl/tridactyl#1641]
Tridactyl version: 1.15.0pre2842-bba12b6
Firefox version: Mozilla Firefox 69.0a1
Operating system: linux

Steps to reproduce: 
- Open tab and navigate to a site
- Search for a thing that exists on the site
- Open a new tab on a different (or same) site.
- Search for a thing not on the site. The find error show's the old lastSearchQuery from the other tab.

**Comment by antonva** [comment]
This is correct behaviour now that I've thought about it. closing.

**Comment by bovine3dom** [comment]
I don't understand - why should you get the search query from the other tab?

**Comment by antonva** [comment]
I cannot replicate the behaviour described in the initial bug report so I must have misdiagnosed it.

The reason why you should get the query from another tab is lets say that we have some fancy search term in one tab **a**, we want to carry that over to another tab **b**. The current implementation allows you to use `findnext` without having done a search on tab **b** with the fancy search term stored in `lastSearchQuery`. This is analogous to VIM search behaviour where search terms can carry over between buffers.

I should have detailed this in my closing message.
