### ISSUE TITLE
scripts/common.sh:tslintUgly broken

### ISSUE THREAD

**Issue by cmcaine** [tridactyl/tridactyl#1647]
Reproduce with this:

```sh
bash -c 'source scripts/common.sh ; PATH=node_modules/.bin:$PATH tslintUgly src/content/hinting.ts'
```
I get this output:

```
Warning: The 'arguments-order' rule requires type information.
Warning: The 'consecutive-overloads' rule requires type information.
Warning: The 'no-accessor-field-mismatch' rule requires type information.
Warning: The 'no-alphabetical-sort' rule requires type information.
Warning: The 'no-collection-size-mischeck' rule requires type information.
Warning: The 'no-dead-store' rule requires type information.
Warning: The 'no-element-overwrite' rule requires type information.
Warning: The 'no-empty-array' rule requires type information.
Warning: The 'no-gratuitous-expressions' rule requires type information.
Warning: The 'no-ignored-initial-value' rule requires type information.
Warning: The 'no-ignored-return' rule requires type information.
Warning: The 'no-in-misuse' rule requires type information.
Warning: The 'no-invalid-await' rule requires type information.
Warning: The 'no-misleading-array-reverse' rule requires type information.
Warning: The 'no-redundant-boolean' rule requires type information.
Warning: The 'no-return-type-any' rule requires type information.
Warning: The 'no-self-assignment' rule requires type information.
Warning: The 'no-try-promise' rule requires type information.
Warning: The 'no-undefined-argument' rule requires type information.
Warning: The 'no-unused-array' rule requires type information.
Warning: The 'no-use-of-empty-return-value' rule requires type information.
Warning: The 'no-useless-cast' rule requires type information.
Warning: The 'no-useless-intersection' rule requires type information.
Warning: The 'no-variable-usage-before-declaration' rule requires type information.
Warning: The 'parameters-max-number' rule requires type information.
Warning: The 'prefer-immediate-return' rule requires type information.
Warning: The 'use-type-alias' rule requires type information.
Warning: The 'no-unused-declaration' rule requires type information.
```

This is because tslint needs to know about the other files for type information. Setting the --project option isn't sufficient because the linter complains that the file is not in the project.

I've fixed it in fix-tslint branch so that it now does what I think @glacambre intended it to do, but it doesn't seem to fix code issues that I'd expect it to (tested inconsistent indentation, extra spaces between brackets and operators). I think we should probably use prettier as well as or instead of tslint.

@glacambre Thoughts?

**Comment by cmcaine** [comment]
https://github.com/tridactyl/tridactyl/tree/fix-tslint

**Comment by cmcaine** [comment]
Also relevant: https://github.com/palantir/tslint/issues/4534

The tslint people also think prettier is better for formatting issues.

**Comment by glacambre** [comment]
Running `bash -c 'source scripts/common.sh ; PATH=node_modules/.bin:$PATH tslintUgly src/content/hinting.ts'` doesn't break for me. Not sure what could be happening there.

I didn't test it but your PR seems fine.

>The tslint people also think prettier is better for formatting issues.

The reason I wanted to stop using prettier is that it constantly breaks completions by adding newlines to tagged templates (this changes the generated dom tree).

**Comment by antonva** [comment]
Well, we're going to end up writing the completions with mithril. Consider moving back to prettier when we get the completions redone?

**Comment by cmcaine** [comment]
This is confusing. Maybe my globally installed copy of tslint was getting in the way?

**Comment by bovine3dom** [comment]
Did we file an issue about prettier breaking templates? Sounds like a bug.

**Comment by glacambre** [comment]
There already was an issue about it so I just commented in it: https://github.com/prettier/prettier/issues/5588

**Comment by glacambre** [comment]
The prettier bug can now be disabled, so Tridactyl could probably switch back to prettier for formatting now (perhaps this could be done in https://github.com/tridactyl/tridactyl/pull/2477 since it seems to touch the precommit hook?).

**Comment by bovine3dom** [comment]
Closing as we switched back to prettier some time ago.
