### ISSUE TITLE
`:nativeinstall` is broken on Windows

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1651]
Tridactyl version: 1.15.0pre2902-ff73610
Firefox version: Mozilla Firefox 67.0
Operating system: win

Need to do something along the lines of

```
$TempScript = Invoke-WebRequest 'https://raw.githubusercontent.com/cmcaine/tridactyl/master/native/win_install.ps1'; $ScriptBlock = [Scriptblock]::Create($TempScript.Content); Invoke-Command -ScriptBlock $ScriptBlock -ArgumentList ($args + @('Tag') + @('master')) 
```

which gives the error
```
Invoke-Command : Cannot convert the "Tag" value of type "System.String" to type "System.Management.Automation.SwitchParameter".
At line:1 char:177
+ ... t.Content); Invoke-Command -ScriptBlock $ScriptBlock -ArgumentList ($ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-Command], PSInvalidCastException
    + FullyQualifiedErrorId : ConvertToFinalInvalidCastException,Microsoft.PowerShell.Commands.InvokeCommandCommand
```

so we just need to work out how to pass `-Tag master` as an argument.

**Comment by bovine3dom** [comment]
I'd really appreciate some help with this - it's blocking our release of Tridactyl 1.16.0 which has lots of nice features. I don't have the time to grok powershell myself. It should be as simple as figuring out how to construct a named argument object.

**Comment by bovine3dom** [comment]
Need to make sure this also works with the pre-compiled exectuables. I think it should "just work".

**Comment by Dranaxel** [comment]
Hello, can you eplicit me the problem ? command seems to work for me in 1.19.1

**Comment by bovine3dom** [comment]
@Dranaxel yes: the bug isn't on master, it is on https://github.com/tridactyl/tridactyl/pull/1639 which was reverted in e0c0723.

We'd still like to be able to re-apply that PR as it would allow us to make breaking changes to the native messenger, such as supporting unicode better: #896.

**Comment by Rummskartoffel** [comment]
@bovine3dom I've started looking into this and I think I'll have something working soon. It'll only work when pasted into PowerShell, but that shouldn't be a problem, since the install script requires that anyway.
