### ISSUE TITLE
Address bar loses focus when opening a new tab

### ISSUE THREAD

**Issue by modk** [tridactyl/tridactyl#1652]
When I open a new tab via Ctrl-t the Tridactyl help page is shown.
I would expect to be able to type an URL right away but after half a second or so the focus gets lost and I have to press Ctrl-l again to focus the address bar (this will automatically select what I typed before so not ideal either).

Is it possible to get rid of that focus stealing?

To give some context - I used Ctrl-t instead of 't' because the latter has been pretty slow for me. I was used to the snappiness of vimperator and therefore I went with the usual address bar which appears faster. Performance has improved lately but I still think the focus thing is annoying enough to warrant an issue. If you disagree please close :)

**Comment by bovine3dom** [comment]
Are you using an old version of Firefox? Mozilla broke this functionality a while ago.

`set newtabfocus false`, anyway. Generally all our settings are shown on `:help` if you click the link at the top of that page, or click preferences/options on Tridactyl on `about:addons`.
