### ISSUE TITLE
Tridactyl is broken on ubuntu's version of firefox 68

### ISSUE THREAD

**Issue by dylanfprice** [tridactyl/tridactyl#1670]
Workaround:

1. Visit about:preferences
2. Go to Search
3. Remove the Amazon search engine under "One-Click Search Engines"

---

Original bug report:

Tridactyl version: 1.15.0pre2926-417b982
Firefox version: Mozilla Firefox 68.0
Operating system: linux

## Brief description of the problem:

The following *do not* work:
- `:open test` 
- `:open example.com`

The following *do* work:
- `:open github test`

The error message in the command line for the commands that fail is `controller in excmd: Error: An unexpected error occurred`.

`:tabopen` has the same problems, but because it opens a new tab I don't see the error message.

## Steps to reproduce:

I opened Firefox with a clean profile and no `.tridactylrc`. I installed the beta version of tridactyl. I turned logging to debug for all components. Then, on an empty tab, I typed `:open test` and observed the error message referenced above.

## More information

[Contents of :viewconfig](https://gist.github.com/dylanfprice/bef7739d4b0c0217477d66a8c4bc0c3a)

Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist): I removed ~/.tridactylrc before starting Firefox with a clean profile

Browser console logs (these start from a page refresh on the Tridactly new tab page and end with me typing `:open test`)
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). newtab.html
Error: WebExtension context not found! 5 ExtensionParent.jsm:1084:13
SyntaxError: An invalid or illegal string was specified content.js:32164
    listenForCounters moz-extension://2dafc182-a4e5-47d0-b65a-375d4944432e/content.js:32164
    ts moz-extension://2dafc182-a4e5-47d0-b65a-375d4944432e/content.js:23915
    __webpack_require__ moz-extension://2dafc182-a4e5-47d0-b65a-375d4944432e/content.js:20
    <anonymous> moz-extension://2dafc182-a4e5-47d0-b65a-375d4944432e/content.js:84
    <anonymous> moz-extension://2dafc182-a4e5-47d0-b65a-375d4944432e/content.js:87
SyntaxError: An invalid or illegal string was specified commandline_frame.js:15447
    listenForCounters moz-extension://2dafc182-a4e5-47d0-b65a-375d4944432e/commandline_frame.js:15447
    ts moz-extension://2dafc182-a4e5-47d0-b65a-375d4944432e/commandline_frame.js:7818
    __webpack_require__ moz-extension://2dafc182-a4e5-47d0-b65a-375d4944432e/commandline_frame.js:20
    <anonymous> moz-extension://2dafc182-a4e5-47d0-b65a-375d4944432e/commandline_frame.js:84
    <anonymous> moz-extension://2dafc182-a4e5-47d0-b65a-375d4944432e/commandline_frame.js:87
Use of nsIFile in content process is deprecated. 2 NetUtil.jsm:245:12
normal normal <unavailable> 
{…}
​
exstr: "fillcmdline open"
​
isMatch: true
​
numericPrefix: undefined
​
value: "fillcmdline open"
​
<prototype>: Object { … }
content.js:24220:24
NetworkError when attempting to fetch resource. ExtensionCommon.jsm:654:10
    normalizeError resource://gre/modules/ExtensionCommon.jsm:654
    call resource://gre/modules/ExtensionParent.jsm:1006
controller in excmd:  <unavailable> content.js:30004:33
    log moz-extension://2dafc182-a4e5-47d0-b65a-375d4944432e/content.js:30004
    acceptExCmd moz-extension://2dafc182-a4e5-47d0-b65a-375d4944432e/content.js:27476
```

Web console logs (these start from a page refresh and end with me typing `:open test`)
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). newtab.html
SyntaxError: An invalid or illegal string was specified content.js:32164
    listenForCounters perf.ts:167
    ts content.ts:354
    Webpack 3
SyntaxError: An invalid or illegal string was specified commandline_frame.js:15447
    listenForCounters perf.ts:167
    ts commandline_frame.ts:378
    Webpack 3
normal normal 
Array [ keydown ]
 
Object { value: "fillcmdline open", exstr: "fillcmdline open", isMatch: true, numericPrefix: undefined }
controller_content.ts:146:23
controller in excmd:  Error: "An unexpected error occurred" logging.ts:42:32
    log logging.ts:42
    acceptExCmd controller.ts:24
```

I feel that the SyntaxError must be a red herring or it would have been fixed already.

To celebrate filing my first issue I finally gave Tridactyl a review and donated. Thanks for your work on this extension!

**Comment by dylanfprice** [comment]
Anything I can try to help make progress on this?

**Comment by bovine3dom** [comment]
Sorry, I've been quite busy in the last month so this slipped through the cracks. Bumping it was probably the best thing you could do :)

**Comment by bovine3dom** [comment]
What do you mean by "an empty tab"? Do you see our new tab page?

**Comment by dylanfprice** [comment]
Thanks for taking a look!

Yes I see the Tridactyl new tab page. The `:open` commands referenced above were started from that new tab page. If I run `:tabopen test` I get to the Tridactyl new tab page as if I had just typed `:tabopen` with no arguments.

**Comment by bovine3dom** [comment]
Stupid question: do you see the same behaviour with logging turned off?

**Comment by glacambre** [comment]
Are you still using firefox 68? Where did you download it from? Are you still trying to use 1.15.0pre2926-417b982 or did you update?

**Comment by dylanfprice** [comment]
> Stupid question: do you see the same behaviour with logging turned off?

I set all logging components to `never` and saw the same behavior (w/o the `controller in excmd: Error: An unexpected error occurred` error message of course).

> Are you still using firefox 68? Where did you download it from?

Yes I have `68.0b14 (64-bit)`, "Mozilla Firefox for Ubuntu" installed through apt (Ubuntu 18.04). The apt package is `68.0~b14+build1-0ubuntu0.18.04.1`. Good call though I will try installing it through a different channel and see if I can still repro.

**Comment by dylanfprice** [comment]
I downloaded from mozilla.org and when I run that binary (68.0) I don't see the issue. Thanks @glacambre!

I also noticed I had a custom apt repository configured for firefox: `http://ppa.launchpad.net/mozillateam/firefox-next/ubuntu`. I removed the `sources.list.d` file, `apt remove --purge firefox`, `apt install firefox`. My firefox version now says `68.0 (64-bit)` and the apt package is `68.0+build3-0ubuntu0.18.04.1`, still seeing the issue. 

So something in the Ubuntu packaging/customizations for Firefox? If we can narrow it down to something reproducible for them I can file with the [Ubuntu Mozilla Team](https://wiki.ubuntu.com/MozillaTeam). Guessing that might be hard to do.

I am happy switching to the Mozilla build. I don't know how many Tridactyl users are on Ubuntu but willing to keep pursuing this if it would be useful for others. Maybe it's worth adding a note to the troubleshooting section that if you are running a non-Mozilla build of Firefox you should try installing the official build and see if you still have the issue.

**Comment by trevorld** [comment]
>  I don't know how many Tridactyl users are on Ubuntu but willing to keep pursuing this if it would be useful for others.

I'm another Tridactyl user on Ubuntu also being impacted by this bug.  Please keep pursuing this.

**Comment by setharnold** [comment]
I'm getting the same error message today, though I'm not sure if the cause is today's Firefox 68 from Ubuntu, or me finally accepting a new version of Tridactyl that included new permission requests.

Using `o`, then `[Tab]`, then selecting an entry from the history, still works fine.

Thanks

**Comment by aidengindin** [comment]
> I'm another Tridactyl user on Ubuntu also being impacted by this bug. Please keep pursuing this.

Same here. I've been experiencing this issue for the past few days. Switching to the official Mozilla build solved it for me as well.

**Comment by bovine3dom** [comment]
Has anyone filed a bug? https://bugs.launchpad.net/ubuntu/+source/firefox

I suspect it isn't our fault.

**Comment by setharnold** [comment]
So, many of the times I try to use open, it works; sometimes it doesn't, with this error message.

For many months now I'd been having trouble with opening and tab-opening things: both searches and url loads. (It's been driving me insane.) If you'd then hit 'o' and up arrow, you'd get the `:open` prompt with a bunch of spaces.

This is wild speculation but I wonder if this is the same underlying problem that I've had for months and only now there's a solid error message to go with the issue.

Thanks

**Comment by glacambre** [comment]
I think these are two different issues. The one you're describing is https://github.com/tridactyl/tridactyl/issues/1237 I think.

**Comment by glacambre** [comment]
Hi, I think I fixed this issue in #1740. Could you tell us if the bug really disappeared after updating Tridactyl to the latest betas?

**Comment by aidengindin** [comment]
Nope, bug is still there for me.

**Comment by suyashbire1** [comment]
Hi from a fellow `Firefox 68` + `Tridactyl 1.16.2` user on Ubuntu. This problem is specific to incomplete URLs. For example, I can reproduce this error for `:o amazon.com` but `:o https://amazon.com` works as expected.

**Comment by escherdragon** [comment]
I've just found the most bizarre work-around for this issue (firefox 68.0.1 x64 on Ubuntu 18.04 LTS): set `LC_ALL` to some invalid value before running: `LC_ALL=xx /usr/bin/firefox`.

Alternatively, considering that /usr/bin/firefox is in Ubuntu a symlink to /usr/lib/firefox/firefox.sh, it's enough to add a like `LC_ALL=xx` at the very beginning of the script to make it work again.

Just don't ask me why this works.

**Comment by galenhuntington** [comment]
Confirmed that @escherdragon's workaround fixes the problem for me.  Perhaps this is a clue as to what's going on?

**Comment by aidengindin** [comment]
Confirmed, although adding `LC_ALL=xx` to `/usr/lib/firefox/firefox.sh` doesn't work for me.

**Comment by LanJian** [comment]
Confirmed. You can change the line that launches Firefox in `/usr/lib/firefox/firefox.sh` to: `exec env LC_ALL=xx $MOZ_LIBDIR/$MOZ_APP_NAME "$@"` to make it work

**Comment by robin-snt** [comment]
> Confirmed, although adding `LC_ALL=xx` to `/usr/lib/firefox/firefox.sh` doesn't work for me.

You need to export the envvar..
`export LC_ALL=xx`

**Comment by robin-snt** [comment]
The work around changes the tridactyl font, does anyone know how to make the font monospace?

I'm talking about the font that is used in the menu that shows up when you hit `t` or `o` ..

**Comment by bovine3dom** [comment]
It should just use the default monospace font set under `about:preferences`.

**Comment by anoopelias** [comment]
> So something in the Ubuntu packaging/customizations for Firefox? If we can narrow it down to something reproducible for them I can file with the [Ubuntu Mozilla Team](https://wiki.ubuntu.com/MozillaTeam). Guessing that might be hard to do.

Looks like `browser.search.get()` is throwing this error. It is not specific to Tridactyl, was able to reproduce in a simple extension. See this [gist](https://gist.github.com/anoopelias/34a8fd5ac8d032bacb84e3e500c318f0). This is happening only with Firefox distribution for Ubuntu, not in Mozilla's original distribution.

**Comment by galenhuntington** [comment]
The `LC_ALL=xx` workaround is no longer working for me.  Has this changed for anyone else?

**Comment by bovine3dom** [comment]
There's clearly quite a few users effected by this. Could someone report it to Ubuntu via [Launchpad](https://bugs.launchpad.net/ubuntu/+source/firefox?field.searchtext=browser.search.get&search=Search&field.status%3Alist=NEW&field.status%3Alist=INCOMPLETE_WITH_RESPONSE&field.status%3Alist=INCOMPLETE_WITHOUT_RESPONSE&field.status%3Alist=CONFIRMED&field.status%3Alist=TRIAGED&field.status%3Alist=INPROGRESS&field.status%3Alist=FIXCOMMITTED&field.assignee=&field.bug_reporter=&field.omit_dupes=on&field.has_patch=&field.has_no_package=)? @anoopelias, your gist should help them.

**Comment by anoopelias** [comment]
Reported it to Ubuntu.

See: https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1840597

**Comment by orangenschalen** [comment]
@galenhuntington: The LC_ALL=xx workaround still works. But an update of the firefox package has reverted you edit to /usr/lib/firefox/firefox.sh (most probably).

**Comment by galenhuntington** [comment]
`LC_ALL=xx` still does not work for me (and I use it directly in the command line), although it did at first.  I was doing some tinkering with config variables trying to fix an unrelated problem, so possibly I broke something (?).

However, from reading the bug report, it seems the root cause is a bad icon for the Amazon search engine.  By going into Preferences > Search and removing the Amazon engine (for which the icon is visibly absent), this bug went away for me.  No `LC_ALL` required.

**Comment by bovine3dom** [comment]
Thanks. I've added that workaround to the original post.

**Comment by dfkamm** [comment]
Just updated to Firefox 69 on Ubuntu 18.04, and this seems to have been fixed.
