### ISSUE TITLE
Bind different commands to same key, according to domain

### ISSUE THREAD

**Issue by oxysoft** [tridactyl/tridactyl#1671]
Hi, my idea with this is that I could make a more friendly hint mode for various websites (using CSS selector hinting) such as 

- Google: Only hint the links, that way 1 is the first link, 2  is the second link, 3 is the third, etc.
- Reddit: Only hint certain elements to reduce clutter, hint differently for comments, etc. Reddit has a massive amount of clutter when simply using `f`.

The problem is that I think I would have to bind different keys for each of these and it could get annoying. Instead it would be cool if I could just have a single "friendly hint" bind, to keep things simple.

(Or perhaps this idea of friendly hinting could be expanded and offered out of the box for various websites. Users could contribute to Tridactyl by contributing useful CSS selectors.)

**Comment by glacambre** [comment]
Binding different commands to the same key according to domains is already possible with `:bindurl`.
For example, you could have the following bindings:
```vim
bindurl example.com a js alert("hello")
bindurl example.org a js alert("world")
```
Then pressing `a` would do different things depending on whether you're on example.com or example.org.
