### ISSUE TITLE
getrcpath error: Path not found (attempting to change colors)

### ISSUE THREAD

**Issue by oxysoft** [tridactyl/tridactyl#1675]
Tridactyl version: 1.15.0-1.15.0
Firefox version: Mozilla Firefox 69.0a1
Operating system: win

I think I understand what the error is trying to communicate, but it's not exactly obvious what I should do to fix it... I have native installed and placed the themes folder in `~/.tridactyl`, not sure what else I am supposed to do.

**Comment by McSinyx** [comment]
Might be related to #1097: does the file `~/.tridactyl/tridactylrc` exist?

**Comment by oxysoft** [comment]
It does exist

**Comment by avalonv** [comment]
Also having this issue. I placed my tridactylrc in `~/.config/tridactyl/` and the theme in a folder called `themes`.

**Comment by glacambre** [comment]
@avalonv Are you also using windows?

**Comment by avalonv** [comment]
No, I'm on linux:

Tridactyl version: 1.16.2pre2999-95db0a8
Firefox version: Mozilla Firefox 68.0.1
Operating system: Void linux

**Comment by glacambre** [comment]
@avalonv Could you run the following commands and let us know what the output is?
```
:exclaim ls $XDG_CONFIG_HOME/tridactyl/*
:get theme
:get customthemes
```

@oxysoft Sorry for not helping you but I don't have a windows computer and I don't know how the native messenger works on windows.

**Comment by avalonv** [comment]
`exclaim ls $XDG_CONFIG_HOME/tridactyl/*`:
no output:

`get theme`:
# theme = quake

`get customthemes`:
# customthemes = {}

**Comment by glacambre** [comment]
>no output

This is weird. You should have gotten something like `/home/user/.config/tridactyl/tridactylrc/home/user/.config//tridactyl/themes:atheme.css`. Could you check what your `$XDG_CONFIG_HOME` is set to and ensure that it contains a directory named `tridactyl` and that this directory contains your tridactylrc and your `themes` directory?

**Comment by avalonv** [comment]
I figured out what was the problem: I somehow managed to misspell tridactyl when creating the directory and when creating the rc file. Thanks for your help!

**Comment by oxysoft** [comment]
Well damn, it's most definitely spelled correctly on my end :/

**Comment by glacambre** [comment]
@oxysoft Try running the content of the [findUserConfigFile](https://github.com/tridactyl/tridactyl/blob/132e385a7667224f625adeb91fee06bcecddd919/native/native_main.py#L85-L110) function in a python repl and see if it returns a result.

**Comment by oxysoft** [comment]
Okay so I printed each of the paths that `findUserConfigFile` seaches for...

```
C:\Users\oxysoft/.config\tridactyl\tridactylrc
C:\Users\oxysoft\.tridactylrc
C:\Users\oxysoft\_config\tridactyl\tridactylrc
C:\Users\oxysoft\_tridactylrc
```

I quickly realized mine is located in `C:\Users\oxysoft\.tridactyl\tridactylrc`, with a `.` in front of the tridactyl config folder!!

**Comment by glacambre** [comment]
Does moving your config+theme directory to one of the paths the native messenger uses fix your problems?

**Comment by oxysoft** [comment]
Eventually yes, after some fiddling around. It seems that the native messenger is in fact installed in `~/.tridactyl`, so I had inadvertently broke it by renaming the folder to remove the period. After that I started over from a clean slate and `tridactylrc` was found in `C:\Users\oxysoft/.config\tridactyl\tridactylrc`. However, when attempting to set the color scheme, it appeared to be searching in a peculiar location: `C:\Users\oxysoft/themes`. Well, at least it works by placing the themes folder there!

**Comment by glacambre** [comment]
`C:\Users\oxysoft/.config\tridactyl\tridactylrc` doesn't seem like a valid path so it's probably failing to find your tridactylrc there and defaulting to your $HOME. I think moving your tridactylrc and theme folder to `C:\Users\oxysoft\_config\tridactyl` would probably work.

Closing this because you say it's fixed, feel free to reopen/ask other questions :)
