### ISSUE TITLE
two new tabs are opening

### ISSUE THREAD

**Issue by bonegabor** [tridactyl/tridactyl#1678]
Tridactyl version: 1.15.0-1.15.0
Firefox version: Mozilla Firefox 67.0.2
Operating system: linux - Debian 9

*   Brief description of the problem:
if I am using the mouse to open a new tab, by clicking on the + button two tabs are opening, one with active tridactyl, and one without

*   Steps to reproduce:

 1. open a new tab by clicking on the + button

**Comment by bovine3dom** [comment]
Could you show us your configuration? Just copy and paste the URL from `:viewconfig`.

I suspect the problem might be your `newtab` setting.

**Comment by bonegabor** [comment]
data:application/json,{"configversion":"1.7","subconfigs":{},"priority":0,"exmaps":{"<Enter>":"ex.accept_line","<C-j>":"ex.accept_line","<C-m>":"ex.accept_line","<Escape>":"ex.hide_and_clear","<ArrowUp>":"ex.prev_history","<ArrowDown>":"ex.next_history","<C-a>":"text.beginning_of_line","<C-e>":"text.end_of_line","<C-u>":"text.backward_kill_line","<C-k>":"text.kill_line","<C-c>":"text.kill_whole_line","<C-f>":"ex.complete","<Tab>":"ex.next_completion","<S-Tab>":"ex.prev_completion","<Space>":"ex.insert_space_or_completion"},"ignoremaps":{"<S-Insert>":"modenormal","<CA-Escape>":"modenormal","<CA-`>":"modenormal","<S-Escape>":"modenormal","<C-^>":"tab%23","<C-6>":"tab%23"},"inputmaps":{"<Escape>":"compositeunfocus|modenormal","<C-[>":"compositeunfocus|modenormal","<C-i>":"editor","<Tab>":"focusinput-n","<S-Tab>":"focusinput-N","<CA-Escape>":"modenormal","<CA-`>":"modenormal","<C-^>":"tab%23","<C-6>":"tab%23"},"imaps":{"<Escape>":"compositeunfocus|modenormal","<C-[>":"compositeunfocus|modenormal","<C-i>":"editor","<CA-Escape>":"modenormal","<CA-`>":"modenormal","<C-6>":"tab%23","<C-^>":"tab%23","<S-Escape>":"modeignore"},"nmaps":{"gno":"tabopenhttp://blogok.penzcsinalok.ro/combridge/index.php/2018/09/17/savantgarde-32/","goo":"openhttp://blogok.penzcsinalok.ro/combridge/index.php/2018/09/17/savantgarde-32/","gwo":"winopenhttp://blogok.penzcsinalok.ro/combridge/index.php/2018/09/17/savantgarde-32/","<A-p>":"pin","<A-m>":"mutetoggle","<F1>":"help","o":"fillcmdlineopen","O":"current_urlopen","w":"fillcmdlinewinopen","W":"current_urlwinopen","t":"fillcmdlinetabopen","]]":"followpagenext","[[":"followpageprev","[c":"urlincrement-1","]c":"urlincrement1","<C-x>":"urlincrement-1","<C-a>":"urlincrement1","T":"current_urltabopen","yy":"clipboardyank","ys":"clipboardyankshort","yc":"clipboardyankcanon","ym":"clipboardyankmd","yt":"clipboardyanktitle","gh":"home","gH":"hometrue","p":"clipboardopen","P":"clipboardtabopen","j":"scrollline10","<C-e>":"scrollline10","k":"scrollline-10","<C-y>":"scrollline-10","h":"scrollpx-50","l":"scrollpx50","G":"scrollto100","gg":"scrollto0","<C-u>":"scrollpage-0.5","<C-d>":"scrollpage0.5","<C-f>":"scrollpage1","<C-b>":"scrollpage-1","$":"scrollto100x","^":"scrollto0x","<C-6>":"tab%23","<C-^>":"tab%23","H":"back","L":"forward","<C-o>":"jumpprev","<C-i>":"jumpnext","d":"tabclose","D":"compositetabprev;tabclose%23","gx0":"tabclosealltoleft","gx$":"tabclosealltoright","<<":"tabmove-1",">>":"tabmove+1","u":"undo","U":"undowindow","r":"reload","R":"reloadhard","x":"stop","gi":"focusinput-l","g;":"changelistjump-1","J":"tabprev","K":"tabnext","gt":"tabnext_gt","gT":"tabprev","g^":"tabfirst","g0":"tabfirst","g$":"tablast","gr":"reader","gu":"urlparent","gU":"urlroot","gf":"viewsource",":":"fillcmdline_notrail","s":"fillcmdlineopensearch","S":"fillcmdlinetabopensearch","M":"gobble1quickmark","B":"fillcmdlinetaball","b":"fillcmdlinetab","ZZ":"qall","f":"hint","F":"hint-b","gF":"hint-br",";i":"hint-i",";b":"hint-b",";o":"hint",";I":"hint-I",";k":"hint-k",";y":"hint-y",";p":"hint-p",";P":"hint-P",";r":"hint-r",";s":"hint-s",";S":"hint-S",";a":"hint-a",";A":"hint-A",";;":"hint-;",";%23":"hint-%23",";v":"hint-Wexclaim_quietmpv",";w":"hint-w",";t":"hint-Wtabopen",";O":"hint-Wfillcmdline_notrailopen",";W":"hint-Wfillcmdline_notrailwinopen",";T":"hint-Wfillcmdline_notrailtabopen",";z":"hint-z",";m":"compositehint-pipeimgsrc|js-ptri.excmds.open('images.google.com/searchbyimage?image_url='+JS_ARG)",";M":"compositehint-pipeimgsrc|jsb-ptri.excmds.tabopen('images.google.com/searchbyimage?image_url='+JS_ARG)",";gi":"hint-qi",";gI":"hint-qI",";gk":"hint-qk",";gy":"hint-qy",";gp":"hint-qp",";gP":"hint-qP",";gr":"hint-qr",";gs":"hint-qs",";gS":"hint-qS",";ga":"hint-qa",";gA":"hint-qA",";g;":"hint-q;",";g%23":"hint-q%23",";gv":"hint-qWexclaim_quietmpv",";gw":"hint-qw",";gb":"hint-qb","<S-Insert>":"modeignore","<CA-Escape>":"modeignore","<CA-`>":"modeignore","<S-Escape>":"modeignore","<Escape>":"compositemodenormal;hidecmdline","<C-[>":"compositemodenormal;hidecmdline","a":"current_urlbmark","A":"bmark","zi":"zoom0.1true","zo":"zoom-0.1true","zm":"zoom0.5true","zr":"zoom-0.5true","zM":"zoom0.5true","zR":"zoom-0.5true","zz":"zoom1","zI":"zoom3","zO":"zoom0.3",".":"repeat","<SA-ArrowUp><SA-ArrowUp><SA-ArrowDown><SA-ArrowDown><SA-ArrowLeft><SA-ArrowRight><SA-ArrowLeft><SA-ArrowRight>ba":"openhttps://www.youtube.com/watch?v=M3iOROuTuMA"},"leavegithubalone":"false","autocmds":{"DocStart":{},"DocLoad":{"^https://github.com/tridactyl/tridactyl/issues/new$":"issue"},"DocEnd":{},"TriStart":{".*":"source_quiet"},"TabEnter":{},"TabLeft":{},"FullscreenChange":{},"FullscreenEnter":{},"FullscreenLeft":{}},"keytranslatemap":{},"keytranslatemodes":{"nmaps":"true","imaps":"false","inputmaps":"false","ignoremaps":"false"},"autocontain":{},"exaliases":{"alias":"command","au":"autocmd","aucon":"autocontain","audel":"autocmddelete","audelete":"autocmddelete","b":"tab","clsh":"clearsearchhighlight","nohlsearch":"clearsearchhighlight","o":"open","w":"winopen","t":"tabopen","tabnew":"tabopen","tn":"tabnext_gt","bn":"tabnext_gt","tnext":"tabnext_gt","bnext":"tabnext_gt","tp":"tabprev","tN":"tabprev","bp":"tabprev","bN":"tabprev","tprev":"tabprev","bprev":"tabprev","tabfirst":"tab1","tablast":"tab0","bfirst":"tabfirst","blast":"tablast","tfirst":"tabfirst","tlast":"tablast","buffer":"tab","bufferall":"taball","bd":"tabclose","bdelete":"tabclose","quit":"tabclose","q":"tabclose","qa":"qall","sanitize":"sanitise","tutorial":"tutor","h":"help","unmute":"muteunmute","authors":"credits","openwith":"hint-W","!":"exclaim","!s":"exclaim_quiet","containerremove":"containerdelete","colours":"colourscheme","colorscheme":"colourscheme","colors":"colourscheme","man":"help","!js":"fillcmdline_tmp3000!jsisdeprecated.Pleaseusejsinstead","!jsb":"fillcmdline_tmp3000!jsbisdeprecated.Pleaseusejsbinstead","current_url":"compositeget_current_url|fillcmdline_notrail","stop":"jswindow.stop()","zo":"zoom","installnative":"nativeinstall","nativeupdate":"updatenative"},"followpagepatterns":{"next":"^(next|newer)\\b|%C2%BB%7C>>|more","prev":"^(prev(ious)?|older)\\b|%C2%AB%7C<<"},"searchengine":"","searchurls":{"google":"https://www.google.com/search?q=","googlelucky":"https://www.google.com/search?btnI=I'm+Feeling+Lucky&q=","scholar":"https://scholar.google.com/scholar?q=","googleuk":"https://www.google.co.uk/search?q=","bing":"https://www.bing.com/search?q=","duckduckgo":"https://duckduckgo.com/?q=","yahoo":"https://search.yahoo.com/search?p=","twitter":"https://twitter.com/search?q=","wikipedia":"https://en.wikipedia.org/wiki/Special:Search/","youtube":"https://www.youtube.com/results?search_query=","amazon":"https://www.amazon.com/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=","amazonuk":"https://www.amazon.co.uk/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=","startpage":"https://startpage.com/do/search?language=english&cat=web&query=","github":"https://github.com/search?utf8=%E2%9C%93&q=","searx":"https://searx.me/?category_general=on&q=","cnrtl":"http://www.cnrtl.fr/lexicographie/","osm":"https://www.openstreetmap.org/search?query=","mdn":"https://developer.mozilla.org/en-US/search?q=","gentoo_wiki":"https://wiki.gentoo.org/index.php?title=Special%3ASearch&profile=default&fulltext=Search&search=","qwant":"https://www.qwant.com/?q="},"newtab":"about:home","viewsource":"tridactyl","storageloc":"sync","homepages":[],"hintchars":"hjklasdfgyuiopqwertnmzxcvb","hintfiltermode":"simple","hintnames":"short","hintuppercase":"true","hintdelay":300,"allowautofocus":"true","newtabfocus":"page","smoothscroll":"false","scrollduration":100,"tabopenpos":"next","relatedopenpos":"related","ttsvoice":"default","ttsvolume":1,"ttsrate":1,"ttspitch":1,"gimode":"nextinput","cursorpos":"end","theme":"default","modeindicator":"true","jumpdelay":3000,"logging":{"cmdline":"warning","containers":"warning","controller":"warning","excmd":"error","hinting":"warning","messaging":"warning","native":"warning","performance":"warning","state":"warning","styling":"warning"},"noiframe":"false","editorcmd":"auto","rsscmd":"yank%u","browser":"firefox","yankto":"clipboard","putfrom":"clipboard","externalclipboardcmd":"auto","nativeinstallcmd":"curl-fsSlhttps://raw.githubusercontent.com/tridactyl/tridactyl/master/native/install.sh|bash","win_nativeinstallcmd":"powershell-NoProfile-InputFormatNone-Command\"Invoke-Expression((New-ObjectSystem.Net.WebClient).DownloadString('https://raw.githubusercontent.com/cmcaine/tridactyl/master/native/win_install.ps1'))\"","update":{"lastchecktime":1560657081422,"nag":true,"nagwait":7,"lastnaggedversion":"1.14.0","checkintervalsecs":86400},"profiledir":"auto","tabopencontaineraware":"false","containerindicator":"true","auconcreatecontainer":"true","historyresults":50,"findresults":-1,"findcontextlen":100,"findcase":"smart","incsearch":"false","minincsearchlen":3,"csp":"untouched","wordpattern":"[^\\s]+","perfcounters":"false","perfsamples":"10000","modeindicatorshowkeys":"false"}

**Comment by bovine3dom** [comment]
Yeah, as I thought:

`set newtab about:home` will give you two tabs, as it hints on `help newtab`.

Just `unset newtab` to fix it. We supply builds without our newtab which might do what you want - https://tridactyl.cmcaine.co.uk/betas/nonewtab/.

**Comment by bonegabor** [comment]
thanks!! problem solved!
