### ISSUE TITLE
Bind C-j and C-k to ArrowDwon and ArrowUp respectively in search bars to traverse candidates.

### ISSUE THREAD

**Issue by arturakb** [tridactyl/tridactyl#1695]
Is there a way to traverse search suggestions using C-j and C-k? I've tried `bind --map=input <C-j> <ArrowDown>`. Didn't seem to work.

**Comment by bovine3dom** [comment]
No, `bind` maps key sequences to ex-commands (so that will be the equivalent of running `:<ArrowDown>`, i.e. nonsense, although there's also no `--map` argument).

You could try writing some `js` to fire a KeyboardEvent https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/KeyboardEvent, and you could then do `bind --mode=insert js [fire a keyevent here]`. However, I can't guarantee that the website will accept it as it will appear as a synthetic keyboard event, and the website (or browser) might choose to ignore it.

**Comment by arturakb** [comment]
Ah, yeah sorry, of course it's `--mode`. I found this add-on only 2 days ago. It's an awesome add-on!

**Comment by bovine3dom** [comment]
I'm not sure if you misunderstood me - `bind --mode=input <C-j> <ArrowDown>` wouldn't work either as it is trying to map ctrl-j to the ex-command `<ArrowDown>`, which doesn't exist. We don't have key-to-key maps for webpages themselves so you'll need to make it yourself with `js` (or write an ex-command for Tridactyl to do it - it shouldn't be too difficult to intercept and rewrite the key events, I don't think).

**Comment by arturakb** [comment]
No, I understood you very well! I have re-bound some keys the other day using `--mode` but as I was tweaking my `Evil` config for Emacs the word `map` just got stuck. I know it can't be done without as you suggested using some JavaScript. I am not a software developer, I won't be able to do it. I just love Vim/Evil and have been using Vimium for a while. But this is much much better. If you ever add the visual selections it would make this one of the best add-ons for Firefox! At least for people who like Vim.

**Comment by bovine3dom** [comment]
I wasn't thinking straight when I answered this. You can do it easily (on Linux) with our `:native` and `xdotool` installed on your system.

```
bind --mode=insert <C-j> !s xdotool key Down
bind --mode=insert <C-k> !s xdotool key Up
```

Some forms (GitHub's search, for example) don't work with this, but binding it to a prefix instead such as 

```
bind --mode=insert <C-b>j !s xdotool key Down
```

does work. Potentially a Tridactyl bug.

**Comment by arturakb** [comment]
Thanks.  It works fine, although it feels a tad less smoother than just pressing the arrow keys.

**Comment by bovine3dom** [comment]
Thankfully a lot of that is out fault - the native messenger is a lot slower than it needs to be - so it might get fixed someday :)
