### ISSUE TITLE
Accidentally blacklistadded all websites with blacklistadd .

### ISSUE THREAD

**Issue by Vincent-Carrier** [tridactyl/tridactyl#1697]
Tridactyl version: 1.16.1pre2946-cc77de0
Firefox version: Mozilla Firefox 68.0
Operating system: mac

Thought the dot meant the current webpage, but apparently I was quite wrong. Now I can't use Tridactyl at all because I don't know how to edit the blacklist without ex mode :/

**Comment by bovine3dom** [comment]
That's quite funny. The dot will be treated as a regex, i.e. any character will match it.

You should be able to run commands from the address bar, so running `tri autocmddelete DocStart .` should fix it.

The nuclear option is to go to `about:addons`, click Preferences or Options on Tridactyl, scroll to the bottom of the page and click reset.

**Comment by Vincent-Carrier** [comment]
Yeah lol I must admit I freaked out quite a bit at first. Ended up going with the nuclear option. That reset button was really well-hidden though. Thanks for the quick reply!
