### ISSUE TITLE
There is no description for 2 permissions on AMO

### ISSUE THREAD

**Issue by petRUShka** [tridactyl/tridactyl#1707]
There is [a beautiful description on AMO](https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim) of some permissions that requires Tridactyl for work.

But 2 permissions are missed out in that description:

1. [Read the text of all open tabs](https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions?as=u&utm_source=inproduct#w_read-the-text-of-all-open-tabs)
2. [Monitor extension usage and manage themes](https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions?as=u&utm_source=inproduct#w_monitor-extension-usage-and-manage-themes)

And also "Access browsing history" is listed twice which is quite confusing:

![2019-06-26-173028_415x378_scrot](https://user-images.githubusercontent.com/146893/60189179-3322fe80-9839-11e9-848e-1f11551abc41.png)

P.S. I try to install latest version from AMO which is 1.16.1 (updated Jun 15, 2019)

**Comment by bovine3dom** [comment]
Woops, this is my fault. It's documented on https://github.com/tridactyl/tridactyl/blob/master/doc/amo.md but I forgot to update the AMO.

I'll try to get round to this tomorrow.

**Comment by bovine3dom** [comment]
Woops, this took me a little longer to get round to than I would have hoped :)
