### ISSUE TITLE
guiset gui none brokes Firefox (no tabs, high CPU usage, inability to revert)

### ISSUE THREAD

**Issue by petRUShka** [tridactyl/tridactyl#1708]
*   Brief description of the problem:

After setting `guiset gui none` there is no way to switch tabs, open help page or revert this settings. Also Firefox heavily loads CPU.

I also looking for way to revert things without deleting Firefox profile.

*   Steps to reproduce:

    1. Execute `:guiset gui none`
    2. Restart Firefox
    3. Look at standard Firefox start page and through address bar open any URL to activate Trydactil
    4. Try to open any other page on this tab (it works)
    5. Try to open new tab with `ctrl+t` or `:tabopen google.com`. It will not work (you stay on previous page) but causes heavily usage of CPU.
    6. Try to set `:guiset gui full` it will not response with any message.
    7. Try to close Firefox it will show you warning message about 2 closing tabs (so we can see that tab is actually opened but something gone wrong)
    8. Open Firefox again and see absence of gui (so 7. doesn't work)

*   Tridactyl version (`:version`):

1.16.1pre2946-cc77de0

*   Firefox version (Top right menu > Help > About Firefox):

67.0

*   URL of the website the bug happens on:

Any

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com): 

https://gist.github.com/petRUShka/f93dd42ab69fd394944cbca5efe98ad7

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

No such file or directory

*   Operating system: 
Arch linux
*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:

```
/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/emulator:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl 
```

*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:

```
{"cmd": "run", "content": "/home/user/.rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/emulator:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/user/bin:/home/user/.fzf/bin\n", "code": 0}
```

**Comment by glacambre** [comment]
Hi, you can revert any change made with `:guiset` by removing the content of your `$firefoxprofile/chrome/userChrome.css` file.
