### ISSUE TITLE
Overrriding Firefox default shortcuts

### ISSUE THREAD

**Issue by surfcao** [tridactyl/tridactyl#1721]
Is there a way to override the some of the firefox default keybindings, such as <C-w> and <C-n>?
I tried to bind <C-w> to text.kill_backward_word and <C-n> to tabnext. Both cases didn't work, still do the close tab and new window as in Firefox default settings. 

Tridactyl version: 1.16.1pre2946-cc77de0
Firefox version: Mozilla Firefox 67.0.4
Operating system: linux

*   Brief description of the problem:

*   Steps to reproduce:

    1.  2.  3.  4.  5.

*   URL of the website the bug happens on:

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
Insert tridactylrc contents between the backticks
```

*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:
*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:

**Comment by glacambre** [comment]
It's possible, see https://github.com/tridactyl/tridactyl/issues/1428 . I'm planning on making this easier to do because I'm tired of recompiling firefox.

**Comment by surfcao** [comment]
> It's possible, see #1428 . I'm planning on making this easier to do because I'm tired of recompiling firefox.

Thanks! Swap Alt and Ctrl sounds like a brilliant work around (https://github.com/tridactyl/tridactyl/issues/1428#issuecomment-479684439).
