### ISSUE TITLE
 keybind to copy a link url to the clipboard (similar to Vimium's "yf")

### ISSUE THREAD

**Issue by victor-lund** [tridactyl/tridactyl#1727]
Trying out Tridactyl, and couldn't find a way to yank an url. Is this possible?

I'm not talking about `yy` which yanks the current url, but rather Vimium's `yf` behavior that lets me copy any url on the page.

Many thanks!

**Comment by bovine3dom** [comment]
`;y` does what you want, I think. If you do `bind ;y` it will tell you what it is bound to, then you can do `bind yt [the command]`.

**Comment by victor-lund** [comment]
Sorry guys, realised `;y` does exactly what I wants.

Closing.

**Comment by AB1908** [comment]
Dammit, I keep coming back here every few months since I'm so used to the vimium binding.
