### ISSUE TITLE
Can't see find indicators in file names in github diffs

### ISSUE THREAD

**Issue by raffomania** [tridactyl/tridactyl#1732]
Tridactyl version: 1.15.0-1.15.0
Firefox version: Mozilla Firefox 69.0
Operating system: linux

*   Steps to reproduce:
1. Open a PR on github.com
2. search for a string found in a filename
3. tridactyl jumps to the filename but doesn't highlight the string it found

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com): https://gist.github.com/raffomania/a49a80ba9cb7b1f147c29b1825e23d41

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
bind x tabclose
bind d scrollpage 0.5
bind u scrollpage -0.5
bind J tabprev
bind K tabnext
bind ] followpage next
bind [ followpage prev
fixamo_quiet
```

**Comment by bovine3dom** [comment]
I'll look at this issue later but for now, please update Tridactyl as 1.15.0 has a serious security issue: https://github.com/tridactyl/tridactyl/security/advisories/GHSA-7qr7-93pf-hr8f

**Comment by glacambre** [comment]
I can't reproduce this issue by running the following commands:
```
tabopen https://github.com/tridactyl/tridactyl/pull/1646/files
find interop
findnext
findnext
findnext
```

Does what I'm doing differ from what you're doing?

**Comment by raffomania** [comment]
Seems to be fixed in the latest beta. for some reason I didn't get updates :man_shrugging:
