### ISSUE TITLE
Content is selectable on new tab page with newtab=about:blank

### ISSUE THREAD

**Issue by pacien** [tridactyl/tridactyl#1743]
Tridactyl version: 1.16.1pre2991-59aabd9
Firefox version: Mozilla Firefox 68.0.1
Operating system: linux

 ---

#### Brief description of the problem:

After setting `newtab about:blank`, the new tab page appears empty but still has some invisible selectable and clickable elements on it, which can be revealed by pressing `f` for example.

![tridactyl-newpage](https://user-images.githubusercontent.com/1449319/61496216-d8a23b80-a9bb-11e9-9d26-c14998ba7a1f.gif)

#### Steps to reproduce:

1. `:set newtab about:blank`
2. open a new tab
3. move the cursor around or use `f` and notice that text and links can still be selected

---

*   URL of the website the bug happens on: the newtab page
*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com): /
*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist): /

**Comment by WloHu** [comment]
It also happens to me. To reproduce this tab should be opened by clicking `+` (for new tab) in Firefox not by using `:tabopen`. Also notice the Tridactyl icon this opened tab has.

**Comment by bovine3dom** [comment]
https://github.com/tridactyl/tridactyl/blob/32ac11fe9d4321905fe1b412d5780f8952f55363/src/content.ts#L181 we probably just need to swap opacity for display: none.

**Comment by Rummskartoffel** [comment]
According to 2ced3ae54d2bf18e63573c0810a9816a8ff3b986, that wouldn't work. (Also this code in content.ts *displays* the page – it's hidden by default as a hack to pretend to be about:blank.) Just navigating to about:blank wouldn't work, either, because Tridactyl can't run on that page. But what if we just include a blank, static page and navigate there when `'newtab'` is set to about:blank? That should work, I think.

**Comment by bovine3dom** [comment]
Can't we shove everything in a `div` and put display none on that? Leaving the body displayed

**Comment by Rummskartoffel** [comment]
Maybe? But using an actually blank page feels cleaner to me somehow – if I can get it to work, that is...

**Comment by bovine3dom** [comment]
:smiling_imp:

Feel free to do it the hard way if you like - I'll still merge it. But 12a0724 works fine

**Comment by Rummskartoffel** [comment]
I don't think I will – that would just reintroduce #384, which I just now found out about.

**Comment by bovine3dom** [comment]
That issue lead to one of my favourite Tridactyl reviews:

> - the plugin sets your home page without asking you ― haven’t seen this behaviour in a long time, and certainly not in opensource world;
> - doesn’t work on some sites (many of those, actually);
> - no easy access to settings;
> - no whitelist.
>
> for a plugin that is expected to _enhance_ my user experience that’s a _fail_ in my book.

People felt really strongly about it
