### ISSUE TITLE
Default tridactylrc

### ISSUE THREAD

**Issue by schyzophrene-asynchrone** [tridactyl/tridactyl#1745]
Is there any way I could find a default tridactylrc, with a list of default mapping, so that I can change things directly from there ?

The thing is I mainly need to adapt default mapping to my keyboard layout, and I’d like to avoid conflict (two commands mapped to the same key).

**Comment by bovine3dom** [comment]
Is looking at https://github.com/tridactyl/tridactyl/blob/master/src/lib/config.ts good enough? `nmaps` is probably what you're looking for.

**Comment by bovine3dom** [comment]
You might also find `:help keymap` does what you want in a more ergonomic way.

**Comment by schyzophrene-asynchrone** [comment]
`:mktridactylrc ~/.tridactylrc` does what I’m looking for.
