### ISSUE TITLE
No default search, I just get sent to the tridactyl default new page

### ISSUE THREAD

**Issue by 1xch** [tridactyl/tridactyl#1750]
Tridactyl Version: 1.16.2pre2999-95db0a8
Firefox Version: 68.0
OS: Ubuntu

*   Brief description of the problem:

no default engine search with open tab( : -> t -> search terms --> enter )

this happened after the latest update, there appears to be a default search engine but new tabs leads to the tridacyl default new page, not a search 

( : -> t -> search engione + search terms --> enter ) opens in the search engine

has something changed and if so what

@glacambre With a fresh untouched profile with only tridactyl installed i get "# controller while accepting: Could not find type information for excmd records"

**Comment by glacambre** [comment]
Hi, does this issue also happen when using a clean firefox profile?

**Comment by arpaulnet** [comment]
I have the same problem and can elaborate some:
- **`:t SEARCH_TERMS or URL`** takes me to the default tridactyl page as if I just entered **`:t`**
- **`:t SEARCH_ENGINE SEARCH_TERMS`** works correctly (ex: `:t google test`)
- **`:s SEARCH_TERMS`** results in _`# controller in excmd: Error: An unexpected error occurred`_
- **`:o SEARCH_ENGINE SEARCH_TERMS`** works correctly (ex: `:o google test`)
- **`:o SEARCH_TERMS or URL`** results in a _`# controller in excmd: Error: An unexpected error occurred`_ (ex: `:o cat pics` or `:o www.google.com`)
- **`:o SEARCH_ENGINE SEARCH_TERMS`** works correctly (ex `:o google test`)

Things I have tried with no success:
1. Reinstalling the Tridactyl extension
2. Blowing away my Firefox profile
3. Uninstalling all other extensions

Also, I'm using the default Tridactyl config.  I have no custom keybindings, etc.  This may be related to #1670 .

Tridactyl Version: 11.16.2pre2999-95db0a8
Firefox Version: 68.0
OS: Ubuntu

**Comment by ingsme** [comment]
Same results as @arpaulnet though both :t and :o works with url so longs as the url is complete with http(s)://

Tridactyl: 11.16.2
Firefox: 68.0.1 (from ubuntu repo)
Ubuntu 18.04

**Comment by bovine3dom** [comment]
Does this issue persist? #1670 was fixed some time ago.

**Comment by bovine3dom** [comment]
Closing as I suspect it has been fixed :)
