### ISSUE TITLE
CTRL-C in command line doesn't copy

### ISSUE THREAD

**Issue by oxysoft** [tridactyl/tridactyl#1752]
CTRL-X properly cuts the text to clipboard but CTRL-C does nothing

**Comment by bovine3dom** [comment]
Have you tried `unbind --mode=ex <C-c>`? Another possibility is that is shadowed by another bind; could we see your config?

**Comment by oxysoft** [comment]
Thanks a lot! `unbind --mode=ex <C-c>` worked perfectly. No idea why this shortcut got bound but oh well!
