### ISSUE TITLE
Hitting "t" and entering url opens new tab page

### ISSUE THREAD

**Issue by steffen-heublein** [tridactyl/tridactyl#1753]
Tridactyl version: 1.16.2pre2999-95db0a8
Firefox version: Mozilla Firefox 68.0.1
Operating system: linux

*   Brief description of the problem:
When hitting 't' to  and entering any url or search term the Tridactyl new tab page opens instead of the url or the google search results.

*   Steps to reproduce:

    1. When on any website hit 't' for :newtab
    2. enter a url, e.g. www.google.com

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

https://gist.github.com/steffen-heublein/668b0b4e5ee012d7d54d12c51ad1fb4a#file-gistfile1-txt

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

does not exist

* additional information

This bug does not exist on my computer at home with a similar setup (running Tridactyl in Firefox on Linux Mint).

**Comment by vague666** [comment]
Same here, worked fine with ff 67.0.4+build1-0ubuntu0.18.10.1
updated to 68.0+build3-0ubuntu0.18.10.1 when 't' stopped working
I get around it with :newtab<enter> , switch to new tab, :o google.com
but it's a bother to have to do the dance

**Comment by glacambre** [comment]
@vague666 Ubuntu's firefox being buggy is a known issue (see https://github.com/tridactyl/tridactyl/issues/1670#issuecomment-510953439 ). Users in #1670 say that using a build from Mozilla makes this issue disappear so you can probably do that until we find what's wrong (this might take a while since none of the Tridactyl devs use Ubuntu).

**Comment by vague666** [comment]
Well, changing to mozilla build helped on 1.16.1 but today when tridactyl automatically updated to 1.16.2 I get the same behaviour as reported by OP :)
ubuntu 18.10
ff 68.0.1 mozilla build
tridactyl 1.16.2

**Comment by glacambre** [comment]
Does removing tridactyl, restarting (mozilla's build of) firefox and re-installing tridactyl change anything?

**Comment by vague666** [comment]
removal helped but I had to delete userChrome.css to get ui elements back so I could approve installation of the addon

**Comment by glacambre** [comment]
Ah, then you might be experiencing https://github.com/tridactyl/tridactyl/issues/1728.

**Comment by vague666** [comment]
With the ubuntu build I was hitting parts of that, probably because I ran :guiset navbar none
Well, anyway, I'm ok for the moment :) Thanks!

**Comment by steffen-heublein** [comment]
I'm using the standard FF from Mozilla now and Tridactyl works without problems :-)
Thanks!
