### ISSUE TITLE
Implement support for config sync via Firefox sync service

### ISSUE THREAD

**Issue by vadz** [tridactyl/tridactyl#1758]
This issue might depend on/be duplicate of #1161 but is somewhat more precise: it would be great if Tridactyl supported (at least) manual sync of its config via Firefox sync service, as is done in [uBlock Origin](https://github.com/gorhill/uBlock/wiki/Cloud-storage), for example.

E.g. ideal would be to have `:exportconfig` and `:importconfig` commands that save/restore config to/from the cloud storage.

**Comment by glacambre** [comment]
I think we already support doing this with `:set storageloc sync`. I don't know what makes firefox decide to sync settings after they've changed though.

**Comment by bovine3dom** [comment]
As glacambre says, automatic syncing should already happen without any input from the user (`set storageloc sync` is the default).

**Comment by vadz** [comment]
Sorry, I didn't know about this, thanks for your answer!

However it doesn't seem to work for me out of the box: I've never changed `storageloc` value (as I didn't know about its existence), but I've just checked `:viewconfig` output and it's indeed set to `sync`. Nevertheless none of my options is synced. Can I do something to manually force syncing them or debug this somehow?

Does sync require having exactly the same versions of the extension on both machines? I have 1.16.1pre2946-cc77de0 here and 1.16.2pre2999-95db0a8 on the other one if it matters.

**Comment by glacambre** [comment]
Do you have `Add-ons` checked under the "Sync Settings" options in "about:preferences"?

**Comment by vadz** [comment]
> Do you have `Add-ons` checked under the "Sync Settings" options in "about:preferences"?

Yes, absolutely. And I can sync the settings for uBlock Origin, so I know that it works.

**Comment by farnoy** [comment]
I'm also experiencing problems with this, when I installed tridactyl on a second device, it synced and overwrote all my settings for the first device. I read somewhere that it's a problem so I knew to open the first device offline and dump my config before syncing.

I even messed with devtools on the background page of tridactyl, that was the only way I could come up with to import a json config.

**Comment by bovine3dom** [comment]
> when I installed tridactyl on a second device

I'm struggling to wrap my head around this - if you had sync enabled, surely Tridactyl would have been installed automatically?

Is it possible to disable add-on synchronisation but still have the add-on storage synchronised? That strikes me as a little counter-intuitive, and sounds like a Firefox bug.

**Comment by farnoy** [comment]
Yes, it was installed automatically, I just took a shortcut in my head. I don't know if it's relevant, but my first device is firefox stable, and my second is using firefox nightly.

**Comment by bovine3dom** [comment]
`:firefoxsyncpull` (to import from cloud storage) and `:firefoxsyncpush` (to export to cloud storage) added in 1.20.0 :)

**Comment by Flimm** [comment]
> 
> 
> As glacambre says, automatic syncing should already happen without any input from the user (`set storageloc sync` is the default).

`set storageloc` doesn't seem to be available any more. But the `:firefoxsyncpull` and `:firefoxsyncpush` commands do seem to be available.

**Comment by tmladek** [comment]
The commands don't seem to do anything and don't provide any feedback, how do I troubleshoot if that doesn't work either?

**Comment by pabloariasal** [comment]
`:firefoxsyncpush` and `:firefoxsyncpull` did work for me, (I had to manually click on "sync on" the firefox UI). At least the manual approach is working, automatic syncing did for me. It would be great if the commands would provide some feedback, as @tmladek mentions.
