### ISSUE TITLE
Numbers in text fields are still processed as counts

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1769]
Steps to reproduce:
1. Type a number into a text field
2. Click away from it (don't press Escape)
3. Press `b` or similar normal bind and see your number appended to the command line

**Comment by glacambre** [comment]
Can't reproduce on a clean profile with 1.16.2pre3027-92e1b00+Firefox 68.

**Comment by bovine3dom** [comment]
Reproducible for me on 1.16.2pre3033-e6d5416 in a fresh profile in FF68.0.1:

1. Visit http://txti.es/
2. Click in the text box with left mouse
3. Type 12345
4. Click outside of the text box but on the web page with left mouse
5. Press b
6. `:tab 12345 ` appears in the command line

**Comment by glacambre** [comment]
Still can't reproduce, even on pre3033 and FF68.0.1. The only difference I can think of are build (I'm using debian's firefox) and keyboard layout (I'm using an azerty layout).

**Comment by bovine3dom** [comment]
Do counts work at all with AZERTY?

**Comment by joaomsa** [comment]
I can reproduce and am on QUERTY

**Comment by glacambre** [comment]
No, looks like they don't work at all. I guess french people don't count ¯\_(ツ)_/¯.
