### ISSUE TITLE
bmarks autocomplete is not useful with -t option

### ISSUE THREAD

**Issue by farnoy** [tridactyl/tridactyl#1772]
Tridactyl version: 1.16.2pre2999-95db0a8
Firefox version: Mozilla Firefox 68.0.1
Operating system: linux

*   Brief description of the problem:
The documentation states this about `bmarks`:
> any argument accepted by open, or tabopen if opt is "-t"

And it works, but autocomplete suggestions for bookmarks are focused on `container_name`, and not the later input.

*   Steps to reproduce:

    1.  `:bmarks -t -c container_name X`
    2. See suggestions filtered by `container_name`, not `X` as desired

*   URL of the website the bug happens on:
Not relevant

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
Not relevant

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):
Not relevant

*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:
*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:

**Comment by farnoy** [comment]
Interestingly, bookmark autocompletion works perfectly with `:tabopen`, but obviously it shows more than just bookmarks.

**Comment by bovine3dom** [comment]
We probably just need to copy the logic that ignores container names from the tabopen completion option to the bookmark completions. I'd be happy to assist anyone who wanted to make a PR.

**Comment by farnoy** [comment]
I'd like to contribute for sure, can you give me a few pointers as to where this logic is missing, and where it's present? I'll try to extract & reuse rather than copy if possible :smile:

**Comment by bovine3dom** [comment]
Copy from https://github.com/tridactyl/tridactyl/blob/32ac11fe9d4321905fe1b412d5780f8952f55363/src/completions/History.ts#L63 to https://github.com/tridactyl/tridactyl/blob/32ac11fe9d4321905fe1b412d5780f8952f55363/src/completions/Bmark.ts#L57
