### ISSUE TITLE
Optional number parameter not passed to urlincrement

### ISSUE THREAD

**Issue by PMarci** [tridactyl/tridactyl#1791]
Tridactyl version: 1.16.2pre3033-e6d5416
Firefox version: Mozilla Firefox 68.0.1
Operating system: linux

*   Brief description of the problem:
When I press `[c` or `]c` to increment or decrement urls the feature works as expected. It even seems to be more permissive than was the default in vimperator, which is actually welcome in my case. However the _amount n_ prefixing of the keystroke seems to be broken/not implemented. I file this as a bug report because the same works for `tabnext`, `tabnext_gt`, and `tabprev`, so I'd expect `urlincrement` to work the same way. No matter what number I enter before pressing `[c` or `]c` the amount is always one. The same is true for `<C-x>`, `<C-a>`.

*   Steps to reproduce:

    1. visit any URL containing an integer
    1. enter an integer > 1 and then follow it up with `[c` or `]c` or `<C-x>` or `<C-a>`
    1. the URL is only incremented/decremented by one
 

*   URL of the website the bug happens on:
All URLs.

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
https://gist.github.com/PMarci/cccb377e05b1c43484106ac86b7829cb
*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
sanitise tridactyllocal tridactylsync
" Ctrl-F should use the browser's native 'find' functionality.
unbind <C-f>

set hintfiltermode vimperator-reflow
set hintchars 5432167890
set hintnames uniform
colors dark
guiset_quiet hoverlink top-left
set modeindicatorshowkeys true

" But also support Tridactyl search too.
bind / fillcmdline find
bind ? fillcmdline find -?
bind n findnext 1
bind N findnext -1
set incsearch true

" Ctrl C for copying in the command line
unbind --mode=ex <C-c>

" x as prev tab, unbind default
bind --mode=normal x tab #
unbind --mode=normal <C-6>
unbind --mode=normal <C-^>

" Hint only titles and menu options on yt
bindurl youtube.com/feed f hint -Jc .yt-simple-endpoint:not(.ytd-thumbnail)
bindurl youtube.com/feed F hint -Jc .yt-simple-endpoint:not(.ytd-thumbnail)
bindurl youtube.com/channel f hint -Jc .yt-simple-endpoint:not(.ytd-thumbnail)
bindurl youtube.com/channel F hint -Jc .yt-simple-endpoint:not(.ytd-thumbnail)

unbindurl youtube.com/watch --mode=normal f
unbindurl youtube.com/watch --mode=normal F
unbindurl escapistmagazine.com/v2/20 --mode=normal f
unbindurl escapistmagazine.com/v2/20 --mode=normal F

quickmark y youtube.com/feed/subscriptions
quickmark s github.com/synoa
quickmark z escapistmagazine.com/v2/series/zero-punctuation/
quickmark t github.com/tridactyl/tridactyl

set searchengine duckduckgo
```

Thanks in advance.

**Comment by bovine3dom** [comment]
Counts are simply appended to the ex-command, which here is `urlincrement 1`,  but `urlincrement` takes only one argument. Easy fix for this is to allow it to take a second argument and then multiply the two together.

https://github.com/tridactyl/tridactyl/blob/32ac11fe9d4321905fe1b412d5780f8952f55363/src/excmds.ts#L1529

Do count =1, multiplier =1, then count = count * multiplier.

**Comment by bovine3dom** [comment]
Fixed a while ago
