### ISSUE TITLE
native messenger could not work properly on windows

### ISSUE THREAD

**Issue by alanche** [tridactyl/tridactyl#1796]
Tridactyl version: 1.16.2pre3052-27402ea
Firefox version: Mozilla Firefox 68.0.1
Operating system: win

*   Brief description of the problem:
   the  'source' command could not load the ~/.tridactylrc report error as:
    # controller in excmd: Error: Failed to send message to native messenger. If it is correctly installed (run `:native`), please report this bug on https://github.com/tridactyl/tridactyl/issues .

*   Steps to reproduce:
  1. :native   get # Native messenger is correctly installed, version 0.1.10 
  2. source

*   URL of the website the bug happens on:

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
`data:application/json,{"configversion":"1.7","subconfigs":{"www.google.com":{"followpagepatterns":{"next":"Next","prev":"Previous"}}},"priority":0,"exmaps":{"<Enter>":"ex.accept_line","<C-j>":"ex.accept_line","<C-m>":"ex.accept_line","<Escape>":"ex.hide_and_clear","<ArrowUp>":"ex.prev_history","<ArrowDown>":"ex.next_history","<C-a>":"text.beginning_of_line","<C-e>":"text.end_of_line","<C-u>":"text.backward_kill_line","<C-k>":"text.kill_line","<C-c>":"text.kill_whole_line","<C-f>":"ex.complete","<Tab>":"ex.next_completion","<S-Tab>":"ex.prev_completion","<Space>":"ex.insert_space_or_completion"},"ignoremaps":{"<S-Insert>":"mode normal","<CA-Escape>":"mode normal","<CA-`>":"mode normal","<S-Escape>":"mode normal","<C-^>":"tab %23","<C-6>":"tab %23"},"imaps":{"<Escape>":"composite unfocus | mode normal","<C-[>":"composite unfocus | mode normal","<C-i>":"editor","<CA-Escape>":"mode normal","<CA-`>":"mode normal","<C-6>":"tab %23","<C-^>":"tab %23","<S-Escape>":"mode ignore"},"inputmaps":{"<Escape>":"composite unfocus | mode normal","<C-[>":"composite unfocus | mode normal","<C-i>":"editor","<CA-Escape>":"mode normal","<CA-`>":"mode normal","<C-6>":"tab %23","<C-^>":"tab %23","<S-Escape>":"mode ignore","<Tab>":"focusinput -n","<S-Tab>":"focusinput -N"},"nmaps":{"gna":"tabopen http://www.amazon.com","goa":"open http://www.amazon.com","gwa":"winopen http://www.amazon.com","gnb":"tabopen http://www.baidu.com","gob":"open http://www.baidu.com","gwb":"winopen http://www.baidu.com","gnD":"tabopen http://www.douban.com","goD":"open http://www.douban.com","gwD":"winopen http://www.douban.com","gnd":"tabopen http://www.iciba.com","god":"open http://www.iciba.com","gwd":"winopen http://www.iciba.com","gnf":"tabopen http://news.ifeng.com","gof":"open http://news.ifeng.com","gwf":"winopen http://news.ifeng.com","gng":"tabopen https://www.google.com/ncr","gog":"open https://www.google.com/ncr","gwg":"winopen https://www.google.com/ncr","gnh":"tabopen http://www.bjguahao.gov.cn/comm/content.php?hpid=256&keid=1012","goh":"open http://www.bjguahao.gov.cn/comm/content.php?hpid=256&keid=1012","gwh":"winopen http://www.bjguahao.gov.cn/comm/content.php?hpid=256&keid=1012","gnj":"tabopen http://www.jd.com","goj":"open http://www.jd.com","gwj":"winopen http://www.jd.com","gnl":"tabopen http://www.laoyaoba.com","gol":"open http://www.laoyaoba.com","gwl":"winopen http://www.laoyaoba.com","gnM":"tabopen https://www.gmail.com","goM":"open https://www.gmail.com","gwM":"winopen https://www.gmail.com","gnm":"tabopen http://music.163.com","gom":"open http://music.163.com","gwm":"winopen http://music.163.com","gnn":"tabopen http://news.163.com","gon":"open http://news.163.com","gwn":"winopen http://news.163.com","gnq":"tabopen http://www.qiyi.com","goq":"open http://www.qiyi.com","gwq":"winopen http://www.qiyi.com","gns":"tabopen http://www.newsmth.net/nForum/%23!mainpage","gos":"open http://www.newsmth.net/nForum/%23!mainpage","gws":"winopen http://www.newsmth.net/nForum/%23!mainpage","gnt":"tabopen http://www.taobao.com","got":"open http://www.taobao.com","gwt":"winopen http://www.taobao.com","gnw":"tabopen http://www.weather.com.cn","gow":"open http://www.weather.com.cn","gww":"winopen http://www.weather.com.cn","gny":"tabopen http://www.youku.com","goy":"open http://www.youku.com","gwy":"winopen http://www.youku.com","gnv":"tabopen http://v.qq.com","gov":"open http://v.qq.com","gwv":"winopen http://v.qq.com","j":"scrollline 3",";c":"hint -c [class*=\"expand\"],[class=\"togg\"]","gd":"tabdetach","gD":"composite tabduplicate | tabdetach","yy":"clipboard yankshort","w":"tabprev","e":"tabnext","<A-p>":"pin","<A-m>":"mute toggle","<F1>":"help","o":"fillcmdline open","O":"current_url open","W":"current_url winopen","t":"fillcmdline tabopen","]]":"followpage next","[[":"followpage prev","[c":"urlincrement -1","]c":"urlincrement 1","<C-x>":"urlincrement -1","<C-a>":"urlincrement 1","T":"current_url tabopen","ys":"clipboard yankshort","yc":"clipboard yankcanon","ym":"clipboard yankmd","yt":"clipboard yanktitle","gh":"home","gH":"home true","p":"clipboard open","P":"clipboard tabopen","<C-e>":"scrollline 10","k":"scrollline -10","<C-y>":"scrollline -10","h":"scrollpx -50","l":"scrollpx 50","G":"scrollto 100","gg":"scrollto 0","<C-u>":"scrollpage -0.5","<C-d>":"scrollpage 0.5","<C-f>":"scrollpage 1","<C-b>":"scrollpage -1","$":"scrollto 100 x","^":"scrollto 0 x","<C-6>":"tab %23","<C-^>":"tab %23","H":"back","L":"forward","<C-o>":"jumpprev","<C-i>":"jumpnext","d":"tabclose","D":"composite tabprev; tabclose %23","gx0":"tabclosealltoleft","gx$":"tabclosealltoright","<<":"tabmove -1",">>":"tabmove +1","u":"undo","U":"undo window","r":"reload","R":"reloadhard","x":"stop","gi":"focusinput -l","g?":"rot13","g;":"changelistjump -1","J":"tabprev","K":"tabnext","gt":"tabnext_gt","gT":"tabprev","g^":"tabfirst","g0":"tabfirst","g$":"tablast","gr":"reader","gu":"urlparent","gU":"urlroot","gf":"viewsource",":":"fillcmdline_notrail","s":"fillcmdline open search","S":"fillcmdline tabopen search","M":"gobble 1 quickmark","B":"fillcmdline taball","b":"fillcmdline tab","ZZ":"qall","f":"hint","F":"hint -b","gF":"hint -br",";i":"hint -i",";b":"hint -b",";o":"hint",";I":"hint -I",";k":"hint -k",";y":"hint -y",";p":"hint -p",";P":"hint -P",";r":"hint -r",";s":"hint -s",";S":"hint -S",";a":"hint -a",";A":"hint -A",";;":"hint -;",";%23":"hint -%23",";v":"hint -W mpvsafe",";w":"hint -w",";t":"hint -W tabopen",";O":"hint -W fillcmdline_notrail open ",";W":"hint -W fillcmdline_notrail winopen ",";T":"hint -W fillcmdline_notrail tabopen ",";z":"hint -z",";m":"composite hint -pipe img src | js -p tri.excmds.open('images.google.com/searchbyimage?image_url=' + JS_ARG)",";M":"composite hint -pipe img src | jsb -p tri.excmds.tabopen('images.google.com/searchbyimage?image_url=' + JS_ARG)",";gi":"hint -qi",";gI":"hint -qI",";gk":"hint -qk",";gy":"hint -qy",";gp":"hint -qp",";gP":"hint -qP",";gr":"hint -qr",";gs":"hint -qs",";gS":"hint -qS",";ga":"hint -qa",";gA":"hint -qA",";g;":"hint -q;",";g%23":"hint -q%23",";gv":"hint -qW mpvsafe",";gw":"hint -qw",";gb":"hint -qb","<S-Insert>":"mode ignore","<CA-Escape>":"mode ignore","<CA-`>":"mode ignore","<S-Escape>":"mode ignore","<Escape>":"composite mode normal ; hidecmdline","<C-[>":"composite mode normal ; hidecmdline","a":"current_url bmark","A":"bmark","zi":"zoom 0.1 true","zo":"zoom -0.1 true","zm":"zoom 0.5 true","zr":"zoom -0.5 true","zM":"zoom 0.5 true","zR":"zoom -0.5 true","zz":"zoom 1","zI":"zoom 3","zO":"zoom 0.3",".":"repeat","<SA-ArrowUp><SA-ArrowUp><SA-ArrowDown><SA-ArrowDown><SA-ArrowLeft><SA-ArrowRight><SA-ArrowLeft><SA-ArrowRight>ba":"open https://www.youtube.com/watch?v=M3iOROuTuMA","m":"jsb (function() {window.tri.excmds.tabopen('http://www.sina.com.cn')})()","gs":"fillinput null [Tridactyl](https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/)","hintmaps":{"<Backspace>":"hint.popKey","<Escape>":"hint.reset","<Tab>":"hint.focusPreviousHint","<S-Tab>":"hint.focusNextHint","<ArrowUp>":"hint.focusTopHint","<ArrowDown>":"hint.focusBottomHint","<ArrowLeft>":"hint.focusLeftHint","<ArrowRight>":"hint.focusRightHint","<Enter>":"hint.selectFocusedHint","<Space>":"hint.selectFocusedHint"},"leavegithubalone":"false","blacklistkeys":["/"],"autocmds":{"DocStart":{"^http(s?)://www.reddit.com":"js tri.excmds.urlmodify(\"-t\", \"www\", \"old\")","^http(s?)://www.amazon.co.uk":"js tri.excmds.urlmodify(\"-t\", \"www\", \"smile\")"},"DocLoad":{"^https://github.com/tridactyl/tridactyl/issues/new$":"issue"},"DocEnd":{},"TriStart":{".*":"source_quiet"},"TabEnter":{},"TabLeft":{},"FullscreenChange":{},"FullscreenEnter":{},"FullscreenLeft":{}},"keytranslatemap":{},"keytranslatemodes":{"nmaps":"true","imaps":"false","inputmaps":"false","ignoremaps":"false","exmaps":"false","hintmaps":"false"},"autocontain":{},"exaliases":{"man":"js -p ( function(args) { var manual = { 'perl':['The Perl manual','http://localhost/man/perldoc-html/index.html'], 'bash':['The Advanced Bash Programming Guide','https://linux.die.net/abs-guide/'], 'git' :['The Official Git Document','https://git-scm.com/doc'], 'python':['The Python 3.7.2 Document','http://localhost/man/python-3.7.2-docs-html/index.html'], 'uvmo':['The official UVM document','http://localhost/man/uvm/index.html'], 'uvmd':['The doxygen generated UVM document','http://localhost/'], 'cpp':['The Online CPP Reference Manual','https://en.cppreference.com'], 'modules':['The GNU Modules','https://modules.readthedocs.io/en/latest/'], 'ruby-doc':['The Ruby online docs','http://localhost/ruby/index.html'], 'ruby-book':['The Programming Ruby - OLD VERSION, read PDF instead','http://ruby-doc.com/docs/ProgrammingRuby/'], 'ruby-intro':['Introduction to Programming with Ruby','https://launchschool.com/books/ruby'], 'make':['The GNU Make manual','http://localhost/man/make/make.html'], 'p4': ['The Perforce Manual','https://www.perforce.com/perforce/doc.current/manuals/cmdref/index.html'], 'tcl':['The Tcl Manual','http://www.tcl.tk/man/tcl8.4/TclCmd/contents.htm'], 'mysql':['The MySQL Manual','http://localhost/man/mysql/index.html'], 'm4':['The GNU M4 manual','http://localhost/man/m4/m4.html'], 'synopsys':['SolvNet','https://solvnet.synopsys.com'], 'yaml-for-ruby':['The yaml Cookbook','http://yaml.org/YAML_for_ruby.html'], 'yaml-intro':['The Chinese version','http://www.ruanyifeng.com/blog/2016/07/yaml.html'] }; try { var url = manual[args][1]; console.log(url); tri.excmds.tabopen(url); } catch (ex) { var msg = ''; for (var cmd in manual) { msg += cmd + \"\\t\"; } tri.excmds.fillcmdline_nofocus(msg); console.log(msg) } })(JS_ARG)","alias":"command","au":"autocmd","aucon":"autocontain","audel":"autocmddelete","audelete":"autocmddelete","b":"tab","clsh":"clearsearchhighlight","nohlsearch":"clearsearchhighlight","noh":"clearsearchhighlight","o":"open","w":"winopen","t":"tabopen","tabnew":"tabopen","tabm":"tabmove","tabo":"tabonly","tn":"tabnext_gt","bn":"tabnext_gt","tnext":"tabnext_gt","bnext":"tabnext_gt","tp":"tabprev","tN":"tabprev","bp":"tabprev","bN":"tabprev","tprev":"tabprev","bprev":"tabprev","tabfirst":"tab 1","tablast":"tab 0","bfirst":"tabfirst","blast":"tablast","tfirst":"tabfirst","tlast":"tablast","buffer":"tab","bufferall":"taball","bd":"tabclose","bdelete":"tabclose","quit":"tabclose","q":"tabclose","qa":"qall","sanitize":"sanitise","tutorial":"tutor","h":"help","unmute":"mute unmute","authors":"credits","openwith":"hint -W","!":"exclaim","!s":"exclaim_quiet","containerremove":"containerdelete","colours":"colourscheme","colorscheme":"colourscheme","colors":"colourscheme","!js":"fillcmdline_tmp 3000 !js is deprecated. Please use js instead","!jsb":"fillcmdline_tmp 3000 !jsb is deprecated. Please use jsb instead","get_current_url":"js document.location.href","current_url":"composite get_current_url | fillcmdline_notrail ","stop":"js window.stop()","zo":"zoom","installnative":"nativeinstall","nativeupdate":"updatenative","mkt":"mktridactylrc","mkt!":"mktridactylrc -f","mktridactylrc!":"mktridactylrc -f","mpvsafe":"js -p tri.excmds.shellescape(JS_ARG).then(url => tri.excmds.exclaim_quiet('mpv ' + url))","mm":"jsb window.tri.excmds.nativeopen('file:///E:/tools/manual/perldoc-html/index.html')","wiki":"tabopen http://localhost/wiki"},"followpagepatterns":{"next":"^(next|newer)\\b|%C2%BB%7C>>|more","prev":"^(prev(ious)?|older)\\b|%C2%AB%7C<<"},"searchengine":"","searchurls":{"google":"https://www.google.com/search?q=","googlelucky":"https://www.google.com/search?btnI=I'm+Feeling+Lucky&q=","scholar":"https://scholar.google.com/scholar?q=","googleuk":"https://www.google.co.uk/search?q=","bing":"https://www.bing.com/search?q=","duckduckgo":"https://duckduckgo.com/?q=","yahoo":"https://search.yahoo.com/search?p=","twitter":"https://twitter.com/search?q=","wikipedia":"https://en.wikipedia.org/wiki/Special:Search/","youtube":"https://www.youtube.com/results?search_query=","amazon":"https://www.amazon.com/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=","amazonuk":"https://www.amazon.co.uk/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=","startpage":"https://startpage.com/do/search?language=english&cat=web&query=","github":"https://github.com/search?utf8=%E2%9C%93&q=","searx":"https://searx.me/?category_general=on&q=","cnrtl":"http://www.cnrtl.fr/lexicographie/","osm":"https://www.openstreetmap.org/search?query=","mdn":"https://developer.mozilla.org/en-US/search?q=","gentoo_wiki":"https://wiki.gentoo.org/index.php?title=Special%3ASearch&profile=default&fulltext=Search&search=","qwant":"https://www.qwant.com/?q="},"newtab":"","viewsource":"tridactyl","storageloc":"sync","homepages":[],"hintchars":"hjklasdfgyuiopqwertnmzxcvb","hintfiltermode":"simple","hintnames":"short","hintuppercase":"true","hintdelay":300,"allowautofocus":"true","preventautofocusjackhammer":"false","newtabfocus":"page","smoothscroll":"false","scrollduration":100,"tabopenpos":"next","relatedopenpos":"related","ttsvoice":"default","ttsvolume":1,"ttsrate":1,"ttspitch":1,"gimode":"nextinput","cursorpos":"end","theme":"default","customthemes":{},"modeindicator":"true","jumpdelay":3000,"logging":{"cmdline":"warning","containers":"warning","controller":"warning","excmd":"error","hinting":"warning","messaging":"warning","native":"warning","performance":"warning","state":"warning","styling":"warning"},"noiframe":"false","noiframeon":[],"editorcmd":"auto","rsscmd":"yank %u","browser":"firefox","yankto":"clipboard","putfrom":"clipboard","externalclipboardcmd":"auto","nativeinstallcmd":"curl -fsSl https://raw.githubusercontent.com/tridactyl/tridactyl/master/native/install.sh -o /tmp/trinativeinstall.sh && bash /tmp/trinativeinstall.sh %TAG","win_nativeinstallcmd":"powershell -NoProfile -InputFormat None -Command \"Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/cmcaine/tridactyl/master/native/win_install.ps1'))\"","update":{"lastchecktime":1565258060344,"nag":true,"nagwait":7,"lastnaggedversion":"1.14.0","checkintervalsecs":86400},"profiledir":"auto","tabopencontaineraware":"false","containerindicator":"true","auconcreatecontainer":"true","historyresults":50,"bmarkweight":100,"findresults":-1,"findcontextlen":100,"findcase":"smart","incsearch":"false","minincsearchlen":3,"csp":"untouched","wordpattern":"[^\\s]+","perfcounters":"false","perfsamples":"10000","modeindicatorshowkeys":"false","urlparenttrailingslash":"true"}`
*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
"Quick Marks
quickmark a http://www.amazon.com
quickmark b http://www.baidu.com
quickmark D http://www.douban.com
quickmark d http://www.iciba.com
quickmark f http://news.ifeng.com
quickmark g https://www.google.com/ncr
quickmark h http://www.bjguahao.gov.cn/comm/content.php?hpid=256&keid=1012
quickmark j http://www.jd.com
quickmark l http://www.laoyaoba.com
quickmark N https://www.news.cn
quickmark m http://music.163.com
quickmark n http://news.163.com
quickmark q http://www.qiyi.com
quickmark s http://www.newsmth.net/nForum/#!mainpage
quickmark t http://www.taobao.com
quickmark w http://www.weather.com.cn
quickmark y http://www.youku.com
quickmark v http://v.qq.com

```
:

*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:
C:\ProgramData\Oracle\Java\javapath;C:\Perl64\site\bin;C:\Perl64\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\WinSCP\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\bin;C:\Ruby24-x64\bin;C:\mysql\bin;C:\Users\alanche\AppData\Local\Microsoft\WindowsApps; :
*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:

**Comment by glacambre** [comment]
Does running `:source $ABSOLUTE_PATH_TO_YOUR_TRIDACTYLRC` work?

**Comment by alanche** [comment]
Dear Sir,
 Thanks for your kindly reply.
 it does not works.
 
the command line prompt return: # controller in excmd: Error: undefined





------------------ 原始邮件 ------------------
发件人: "Ghjuvan Lacambre"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 下午4:04
收件人: "tridactyl/tridactyl"<tridactyl@noreply.github.com>;
抄送: "胜仔Alan"<alan-che@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [tridactyl/tridactyl] native messenger could not work properly onwindows (#1796)




Does running :source $ABSOLUTE_PATH_TO_YOUR_TRIDACTYLRC work?

**Comment by bovine3dom** [comment]
Sorry for the delay in replying to this, I've been a little busy. @alanche, do other commands using the native messenger work? E.g. `:! dir`, `:! explorer .`?

**Comment by alanche** [comment]
Dear Sir,
 sorry for later reply.
 It still not works.
 it report the same error message:'# controller in excmd: Error: Failed to send message to native messenger. If it is correctly installed (run `:native`), please report this bug on https://github.com/tridactyl/tridactyl/issues .'





------------------ 原始邮件 ------------------
发件人: "Oliver Blanthorn"<notifications@github.com>; 
发送时间: 2019年9月21日(星期六) 凌晨2:15
收件人: "tridactyl/tridactyl"<tridactyl@noreply.github.com>; 
抄送: "胜仔Alan"<alan-che@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [tridactyl/tridactyl] native messenger could not work properly onwindows (#1796)




Sorry for the delay in replying to this, I've been a little busy. @alanche, do other commands using the native messenger work? E.g. :! dir, :! explorer .?

**Comment by bovine3dom** [comment]
But `! echo %PATH%` works as stated in your original post? How about `! echo %CD%`?

**Comment by alanche** [comment]
it prints:

C:\Users\alanche\.tridactyl 





I listed the directory content as:


dir C:\Users\alanche\.tridactyl

2019/08/03  18:18    <DIR>          .
2019/08/03  18:18    <DIR>          ..
2019/08/03  18:47                34 native_main.bat
2019/08/03  18:47         5,087,048 native_main.exe
2019/08/03  18:47               285 tridactyl.json
2019/07/22  09:21             1,240 win_firefox_restart.ps1







------------------ 原始邮件 ------------------
发件人: "Oliver Blanthorn"<notifications@github.com>; 
发送时间: 2019年10月8日(星期二) 下午2:20
收件人: "tridactyl/tridactyl"<tridactyl@noreply.github.com>; 
抄送: "胜仔Alan"<alan-che@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [tridactyl/tridactyl] native messenger could not work properly onwindows (#1796)




But ! echo %PATH% works as stated in your original post? How about ! echo %CD%?

**Comment by alanche** [comment]
additional comments:
`: ! dir ` report error as the original post.
`: ! explorer . ` can open an explorer window.

> 
> 
> Sorry for the delay in replying to this, I've been a little busy. @alanche, do other commands using the native messenger work? E.g. `:! dir`, `:! explorer .`?

additional comments:
`: ! dir ` report error as the original post.
`: ! explorer . ` can open an explorer window.

**Comment by bovine3dom** [comment]
Ah, you're using the compiled executable. Could you try installing Python 3 on your PATH and reinstalling the native messenger?

**Comment by alanche** [comment]
Thanks for your kindly help, it works now with python3 installed and folllowing fixes.
my tridactylrc has JS command span multiple lines, e.g.:

command man jsb -p ( function(args) {
  var manual = {
    'perl':['The Perl manual','http://localhost/man/perldoc-html/index.html'],
    'bash':['The Advanced Bash Programming Guide','https://linux.die.net/abs-guide/']
} 
  try {
    var url = manual[args][1];
    tri.excmds.tabopen(url);
  } catch (ex) {}
})(JS_ARG)

to mimic the man command.

recently, I found it is not supported by tridactylrc yet, I've combined those lines into a single line to let tridactylrc happy.

BTW,
  I found the command `:nativeopen` pass a 'firefox -p default --new-tab' to native_main.py which cause a new firefox window is created rather than just open an tab page in current window. I suppose it should be fixed, and 'firefox' path must be added into `$PATH' to let it work properly.

**Comment by alanche** [comment]
It seems I have multiple profiles, tridactylrc do not determine the correct one to use.

profiles.ini contents:
[Install308046B0AF4A39CB]
Default=Profiles/jq3riy2r.default-release-1563755697495
Locked=1

[Profile1]
Name=default-release
IsRelative=1
Path=Profiles/jq3riy2r.default-release-1563755697495

[Profile0]
Name=default
IsRelative=1
Path=Profiles/wqxqm9of.default
Default=1

[General]
StartWithLastProfile=1
Version=2

The actively used one is:

 C:\Users\alanche\AppData\Roaming\Mozilla\Firefox\Profiles\jq3riy2r.default-release-1563755697495


should not be selected as: 'firefox -p deault', right?

**Comment by bovine3dom** [comment]
`:set profiledir C:\Users\alanche\AppData\Roaming\Mozilla\Firefox\Profiles\jq3riy2r.default-release-1563755697495` should do the trick :)

We will support newlines in the RC file in the next Tridactyl release - https://github.com/tridactyl/tridactyl/pull/2003 - but the betas are currently broken on some people's machines so it might be a while before we release that :)
