### ISSUE TITLE
Enhancements to `;k`

### ISSUE THREAD

**Issue by cmcaine** [tridactyl/tridactyl#1799]
We should save the element selections that users make with `;k` and allow users to copy these to the clipboard for pasting into e.g. ublock's custom rules page.

It would be nice to integrate with ublock more seamlessly, but gorhill said no and this is an OK compromise.

We should also make the deletions that ;k makes reversible. `u` would be a natural bind, but obviously we use that for something else. Opinions welcome on what *undo last action* should be as a bind.

**Comment by bovine3dom** [comment]
Added a while ago - `;K` element-hide hint mode and `:elementunhide` (not bound by default because no opinions were given) to restore. `;k` still kills the element because it's handy for killing things that are eating CPU.
