### ISSUE TITLE
control the container that is scrolled on a web page

### ISSUE THREAD

**Issue by BurntSushi** [tridactyl/tridactyl#1805]
Tridactyl version: 1.15.0
Firefox version: Mozilla Firefox 68.0.1
Operating system: linux

This is a feature request for supporting scrolling on pages with multiple scrollable containers. A good example page is here: https://docs.rs/regex/1.2.1/regex/struct.Regex.html On that page, there is a scrollable side bar along with a scrollable "main" section of the page. As far as I know, I don't _think_ there is anyway to instruct Tridactyl to "focus" on the sidebar and scroll it using `j`/`k`. Tridactyl will scroll the sidebar if the main section of the page is scrolled all the way down, but as soon as you scroll up, it applies to the main section of the page instead of the sidebar.

I'm not sure exactly what the UX for this should be, but for example, one plausible route that would work for me I think is to make it possible to toggle focus between scrollable areas. This could be as simple as having a `prev`/`next` command to cycle focus, or something like `gi`, or even something like `f` that puts a marker on each scrollable container in the web page.

**Comment by glacambre** [comment]
Related to https://github.com/tridactyl/tridactyl/issues/1587, https://github.com/tridactyl/tridactyl/issues/1521, https://github.com/tridactyl/tridactyl/issues/1318, https://github.com/tridactyl/tridactyl/issues/35 and maybe https://github.com/tridactyl/tridactyl/issues/1210.

**Comment by bovine3dom** [comment]
As the reply says [here](https://www.reddit.com/r/rust/comments/cq4dip/comment/ewunj7e), `;;` can sort of do this. I guess we just need to figure out a CSS selector or make our own magic one in order to hint scrollable areas.

**Comment by bovine3dom** [comment]
@BurntSushi that version of Tridactyl has a serious [vulnerability](https://github.com/tridactyl/tridactyl/security/advisories/GHSA-7qr7-93pf-hr8f) in it. I suggest you update to 1.6.x ASAP. I'm sorry it didn't happen automatically for you.

**Comment by BurntSushi** [comment]
@bovine3dom Interesting. I didn't know about `;;`. When I tried it, I can indeed focus on something in the sidebar, but when I use `j`/`k` at that point, it still scrolls the main page. (For the link I posted in my first comment.)

If I could make `;;` work, then I think that would be good enough for me honestly.

Also, thanks for the heads up about the outdated version! Yeah, Firefox isn't telling me that there is an update available. I'll force the issue.

**Comment by Philipp0205** [comment]
Is there an update/workaround for this? I really want to change the focus to different scrollable elements on a website. Atm it feels like every second website I visit has a scrollable sidebar.

**Comment by bovine3dom** [comment]
Not that I'm aware of. If you have any examples of sites where our current behaviour is annoying, that is often helpful. (Or, if we can tempt you, perhaps you'd like to look into fixing it yourself? We're always happy to help people get started.)

**Comment by Philipp0205** [comment]
On example are the Google documentations: 
![image](https://user-images.githubusercontent.com/36603238/71881099-f4e49100-3131-11ea-87d3-cfa9a3110f61.png)
They have mutliple scrollabe elements. Another example would be reddit. 

The tridactyl like extention [SurfingKeys](https://github.com/brookhong/Surfingkeys) has a good implementation for this. With `;fs` it shows a hint for every scrollable element on the page and  changes the focus to it.
 
I don't if my understanding in this topics is deep enough to develop something but I can defently have a lookt at it. 

My previous post shouldn't sound like a complain, I really value all the work done on this project.

**Comment by bovine3dom** [comment]
I think I've worked out why this doesn't bother me as much as it does the rest of you: `;;` does allow you to scroll other elements, but you have to use the arrow keys, not Tridactyl's binds.

At the moment we have some decent logic for working out what element it you want to scroll. You might notice that on the Rust page the arrow keys don't work at all until you click somewhere whereas j/k do.

I think we essentially need to change this
https://github.com/tridactyl/tridactyl/blob/85cdd530209cfbadde27b2ca5a1ecc630322dfef/src/content/scrolling.ts#L174 to be the `activeElement`, but then we need to change our tree walker ... somehow.

**Comment by BurntSushi** [comment]
@bovine3dom Ah interesting! Yes, I use `j`/`k` to scroll. I do see that using the arrow keys after focusing via `;;` does work though. It would be great if `j`/`k` could be made to scroll in that case too!

**Comment by Philipp0205** [comment]
Makes sense! Never realised that I can use the ´;;´ and the arrow keys to scroll.
Thanks!

**Comment by bovine3dom** [comment]
To fix this and #2410, I think this is my ideal solution:

- we scroll the widest element on the page first (i.e. j/k scroll wide elements, h/l scroll tall elements)
- once that element is scrolled we switch to the next widest element
- if focus changes we scroll that element instead.

I might try to have a crack at this soon.
