### ISSUE TITLE
SHIFT-DELETE to close highlighted tab in tab suggestions

### ISSUE THREAD

**Issue by oxysoft** [tridactyl/tridactyl#1815]
This could be an efficient way to quickly clean/close several tabs you don't need anymore without reverting to the cursor or having to tediously switch around.

Example usage:

1. Hit `b` to open tab list.
2. Type to search or use `TAB` to highlight tabs in the list.
3. Hit SHIFT-DEL to close the currently highlighted tab.

**Comment by glacambre** [comment]
You can already kind of do that since `:tabclose` accepts multiple arguments. The problem is that tabclose doesn't know how to suggest more than one tab.

**Comment by epichub** [comment]
This would be a very nice feature - I use it all the time in emacs with helm-buffers I can C-space the items in the buffer list to select buffers then M-D to delete/close the selected buffers.. and tabs cleaning in firefox is a more needed feature than buffer cleaning in emacs :)

**Comment by bovine3dom** [comment]
Quite straightforward to add - you want to take inspiration from https://github.com/tridactyl/tridactyl/blob/fe39c3e43adfe9cef9bc225c9db16aba3586af7c/src/lib/commandline_cmds.ts#L108 and https://github.com/tridactyl/tridactyl/blob/fe39c3e43adfe9cef9bc225c9db16aba3586af7c/src/lib/commandline_cmds.ts#L40 to create an `execute_ex_on_completion` command that accepts an ex command and executes it with the value of the completion.

Then bind it in src/lib/config.ts near ex.accept_line :)

**Comment by bovine3dom** [comment]
Added in #2617
