### ISSUE TITLE
taball <search> term including a space introduced unexpected results

### ISSUE THREAD

**Issue by shallowbit** [tridactyl/tridactyl#1835]
### Affects 
	:tab
	:taball
	:buffer
    :bufferall

When using the :**_taball_** excmd if you type a space before the result popup is populated your results are buffer that contain spaces as a user would expect. 

The unexpected behavior is introduced if you try the same query after the results set has been populated. At that point any space will inject a **_windownumber.tabindex_** of the first matching result. 

**Example**

`
:taball some text
`

_results in the below term being inserted into the excmd line_ 

`
:taball 1.4`

This may be _intended behavior_ but it makes searching for titles with spaces difficult and unnatural. It is especially noticeable in a result set that is slower to load like **_:taball_**. It is also undocumented how the function handles wildcards in the query. 

**Sugested Fix**
I suggest waiting for the first tab character to inject this data. That would be more consistent with the rest of the design in tridactyl currently and avoid any further issues. If the tab index needs to be taken into account for the query, wait for the enter key like some other excmds.

Although this behavior has been present for some time, I'll include a version for posterity.

**VERSION: 1.16.3pre3056-077a135**

**Comment by glacambre** [comment]
Does running `unbind --mode=ex <Space>` and `bind --mode=ex <Tab> ex.next_completion` do what you want?

**Comment by bovine3dom** [comment]
Should make `TabAll` completions support `:set completions.TabAll.autoselect false`, then I think we can close this issue

**Comment by shallowbit** [comment]
Seems like reasonable solution.

**Comment by bovine3dom** [comment]
Woops, I didn't mean to close this issue. There's no chance I'll remember to do it otherwise : )
