### ISSUE TITLE
Use the i18n api for CSS

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#1837]
There are a few places in Tridactyl's CSS files where I used base64 icons because I couldn't find a way to load images from the extension's storage. I think these base64 icons can be replaced with urls to Tridactyl's resources if said URLs use the [i18n API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization#Predefined_messages) in order to specify absolute paths containing Tridactyl's UUID.

**Comment by rektrex** [comment]
I would like to take on this one. Where should the images directory be stored - root of the project or `src/static`?

**Comment by glacambre** [comment]
I think they should go in `static`. Thanks for doing this :)

**Comment by rektrex** [comment]
Thank you.
