### ISSUE TITLE
Pasting a url with leading spaces opens the welcome page

### ISSUE THREAD

**Issue by mistotebe** [tridactyl/tridactyl#1857]
Tridactyl version: 1.16.3pre3056-077a135
Firefox version: Mozilla Firefox 68.0.2
Operating system: linux

*   Brief description of the problem:

If you include whitespace at the front of a URI you're pasting, the wrong thing happens...

*   Steps to reproduce:

1. Copy a link but forget you included leading whitespace.
1. use `p`/`P` to open it in Tridactyl.
1. see yourself being navigated to the Welcome to Tridactyl page instead.

*   URL of the website the bug happens on:

Try "` https://github.com`".

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

Looks vanilla: https://paste.ubuntu.com/p/r3CfvMy5rc/

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

They don't.

**Comment by glacambre** [comment]
Probably just need to `.trim()` [here](https://github.com/tridactyl/tridactyl/blob/019a364d667c1f232c8ec3e318ba5ef175e9af6e/src/excmds.ts#L2912) or [here](https://github.com/tridactyl/tridactyl/blob/019a364d667c1f232c8ec3e318ba5ef175e9af6e/src/excmds.ts#L1158).
