### ISSUE TITLE
Cannot install the addon on Firefox 69 OSX

### ISSUE THREAD

**Issue by victor-lund** [tridactyl/tridactyl#1874]
*   Brief description of the problem:
Cannot install the addon on Firefox 69.0.1 (OSX)

*   Steps to reproduce:

    1.  Install Firefox on OSX
    2. Go to https://addons.mozilla.org/en-GB/firefox/addon/tridactyl-vim
    3. Addon is not listed.

*   Firefox version (Top right menu > Help > About Firefox):
69.0.1 (OSX)

Is there any way to install tridactyl as an inofficial addon to FF on OSX?

**Comment by glacambre** [comment]
Tridactyl being delisted has been mentioned in https://github.com/tridactyl/tridactyl/issues/1800#issuecomment-525131558 , you can find information about how to install it from somewhere than addons.mozilla.org in this thread.
I'll close this issue but feel free to reopen it if you have more questions :).
