### ISSUE TITLE
Work out why `hint -;` can't focus images

### ISSUE THREAD

**Issue by notJerl** [tridactyl/tridactyl#1875]
Tridactyl version: 1.16.2pre2999-95db0a8
Firefox version: Mozilla Firefox 69.0.1
Operating system: win

*   Brief description of the problem:
Can't use `hint -;` to focus images, for example to follow up with `<Menu>` or `<S-F10>` to access the context menu for the image.
*   Steps to reproduce:
Use `;;` or `hint -;` on a page with an image on it.  If the image has an anchor, it will focus the actual anchor and **not** the image, giving you access to hyperlink context menu options such as opening links, but not image context menu options such as saving the image or ones added by add-ons.

This may be upstream, since it doesn't appear to be possible to focus images with tab or caret mode either.

**Comment by mozbugbox** [comment]
See [Focusable Elements - Browser Compatibility Table](https://allyjs.io/data-tables/focusable.html)

Maybe you need a hint option to popup context menu on interesting elements.

**Comment by bovine3dom** [comment]
We don't think there is a way of getting the context menu to appear with WebExtensions.

**Comment by Rummskartoffel** [comment]
`<img>`s can be focused if they have the `tabindex` property, and once focused, <kbd>Menu</kbd> works as it should. We could maybe set that on any `<img>` you try to focus with `:hint -;`.
