### ISSUE TITLE
Delayed multi-tabopen

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#1904]
Tridactyl version: 1.17.0pre3194-caad30e
Firefox version: Mozilla Firefox 69.0.2
Operating system: linux

Sometimes I want to open a lot of tabs but I don't have enough RAM. I'd like an ex command that takes an array of urls as parameter and opens url `n+1` in the background when the tab with url `n` is focused for the first time.

**Comment by notJerl** [comment]
That sounds like a good idea.  This might already be what you're thinking, but a way to build such an array using hints that can then be piped into that command would be amazing too.  I can imagine something similar to `;gF` being very helpful.  I can also see building an array using hints being helpful if you want to paste a bunch of URL's; you could use it with composite to dump it into the clipboard using something like `hint -l | yank` (little l for list just as an idea).
