### ISSUE TITLE
autocmd regex documentation is misleading

### ISSUE THREAD

**Issue by simonwjackson** [tridactyl/tridactyl#1910]
Tridactyl version: 1.17.0pre3200-2f28555
Firefox version: Mozilla Firefox 69.0.1
Operating system: Linux (Manjaro)

*   Steps to reproduce:

This works:
```autocmd DocStart /lifehacker.com.*/ js alert('Hello')```

This does not:
```autocmd DocStart /lifehacker.com.*$/ js alert('Hello')```

**Comment by bovine3dom** [comment]
The `/` are literal forward slashes. You want `lifehacker.com.*$` instead.

I think this is probably a documentation problem more than anything else.
