### ISSUE TITLE
Jump list is broken

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1911]
1. Visit a page
2. Wait 3 seconds
3. Scroll down
4. Press `<C-o>`

Expected behaviour: page is scrolled back to top.

Actual behaviour: navigate one page back in history.

**Comment by glacambre** [comment]
Looks like pageX/pageY have been removed: https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/pageX

I had no idea they were non-standard. We can replace them with [window.scrollX/Y](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY).

**Comment by farnoy** [comment]
Should be fixed now as #1816 was merged.

@glacambre I'm not sure that it was removed, because typings say that scroll handler received an event of type `Event`, not `UIEvent`. But maybe you're right and it was really removed recently
