### ISSUE TITLE
Feature request: Thunderbird extension

### ISSUE THREAD

**Issue by bijang** [tridactyl/tridactyl#1920]
First many thanks to everyone for their thundering work on this, so very grateful! 
This is not an issue of a bug, but more an awkwardly placed feature request, for a muttator resurrection, which I know has been raised in the past; though I would not want ot divert anyone's attention from tridactyl... now thunderbird has migrated its extension infrastructure; its future is looking brigthter, but incomplete without a decent keyboard based extension

**Comment by bovine3dom** [comment]
Duplicate of #597.

As we said there, we wouldn't want to do this ourselves but would be happy to help anyone who did.
