### ISSUE TITLE
Modifier order in default config is wrong

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#1921]
Tridactyl version: 1.17.0pre3194-caad30e
Firefox version: Mozilla Firefox 69.0.2
Operating system: linux

Default config has `<CA-*>` and it should be `<AC-*>`. Ideally this should be checked by the build system.

**Comment by glacambre** [comment]
Closed in favour of #1922

**Comment by bovine3dom** [comment]
Reopening this for a more permanent solution
