### ISSUE TITLE
Using an external config throws `conf is undefined`

### ISSUE THREAD

**Issue by nesmyslny** [tridactyl/tridactyl#1924]
Tridactyl version: 1.17.0pre3233-5c5116d
Firefox version: Mozilla Firefox 71.0
Operating system: linux

**Brief description of the problem:**
Using an external config (tridactylrc) results in an error `conf is undefined`. I didn't have the issue last week, so maybe it started with 1.17.0pre3233-5c5116d.

**Steps to reproduce:**

Minimal tridactylrc:
```
sanitise tridactyllocal tridactylsync
bind j scrollline 5
```

1. Comment out both lines
2. Start FF
3. -> Tridactyl works like expected
4. Activate both lines
5. `:source`
6. Try to execute a Tridactyl command (e.g. `r`)
7. -> `conf is undefined` (also on page load with `F5`)

Error message (couldn't get more log with `set logging.controller DEBUG`):
```
controller in excmd:  Error: "conf is undefined" logging.ts:42:32
    log logging.ts:42
    acceptExCmd controller.ts:24
```

**URL of the website the bug happens on:**

E.g. startpage of Tridactyl.

I hope the description is kind of clear, but just let me know if not or if I can provide more information :)

**Comment by bovine3dom** [comment]
Potentially a duplicate of #1918. We just merge a fix for that. Could you update Tridactyl beta and see if the problem persists?

**Comment by nesmyslny** [comment]
Yes, #1919 fixed it. Thanks for pointing to it.

Can't believe I haven't found the other issue. Sorry for the duplicate :(
