### ISSUE TITLE
Version 1.17.0pre3273-3005d24 swallows "A" on fastmail.com

### ISSUE THREAD

**Issue by bronsen** [tridactyl/tridactyl#1956]
Tridactyl version: 1.17.0pre3273-3005d24
Firefox version: Mozilla Firefox 70.0
Operating system: linux

*   Brief description of the problem:
When composing a message on fastmail.com I cannot type "A" (capital a) while in ignore mode. I can paste that letter, but shift-a does not produce a capital a. I can type all other upper case letters and all the lower case ones.

Downgrading to some 1.16 version lets me type A. I cannot say exactly which version of 1.17 started with this behavior...

*   Steps to reproduce:

   1. open fastmail.com & login  
   1. enter ignore mode
   1. press 'c' to start composing a message
   1. press tab until cursor is in the textarea for the email body
   1. press S-a; no input appears

*   URL of the website the bug happens on: https://www.fastmail.com/

*   Config: https://gist.github.com/bronsen/905a35f70bab5e11c91af4c95f84c81b

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc: neither file exists

**Comment by bovine3dom** [comment]
Thanks for providing your config. I think the issue is that you missed off a left angle bracket in one of your ignore maps:

`"AC-Escape>":"mode normal"` 

So this is now bound to literally A C - E s ... etc.

`reset --mode=ignore AC-Escape>` should do the trick.

If it's only on Fastmail you'll probably need to look at unbindurl instead.

**Comment by bronsen** [comment]
What else can I do if the reset command seems not to have worked: I typed `:reset --mode=ignore AC-Escape>` and even restarted the browser, but I still cannot input uppercase a. (and yes it's not only on fastmail but here on github as well)

I don't mind editing files by hand.

**Comment by bovine3dom** [comment]
Nuclear option is `sanitise tridactylsync tridactyllocal` which wipes all Tridactyl settings and history.

**Comment by bronsen** [comment]
How can I tell this command has actually done something? After `:sanitise` I still see the unwanted ignoremaps when I `:viewconfig`...

**Comment by bovine3dom** [comment]
@bronsen aha: the bug was in our default configuration and nothing to do with you. That's why it didn't get fixed when you reset the settings to default.

Thanks for bringing it to our attention. It should be fixed in the next beta (available in approx 5 minutes).
