### ISSUE TITLE
Cannot unbind <C-i> in Gmail

### ISSUE THREAD

**Issue by Noexpert** [tridactyl/tridactyl#1960]
Hi,

I'm trying to unbind `<C-i>` in Gmail so I can <kbd>Ctrl</kbd>+<kbd>i</kbd> and convert text to italic.

I've unbound the key:
`unbindurl mail.google.com --mode=normal <C-i>`

But every time I try the key combination I get the message:
``# # Native messenger not found. Please run `:installnative` and follow the instructions.``

Can someone replicate or do I have a syntax error?

Thanks

**Comment by glacambre** [comment]
`<C-i>` is also bound to something in input and insert mode, does running `unbindurl mail.google.com --mode=input <C-i>` and `unbindurl mail.google.com --mode=insert <C-i>` work?

**Comment by Noexpert** [comment]
Indeed it does.
Thank you.
