### ISSUE TITLE
Quickmark: mutiple urls and  [object Object]

### ISSUE THREAD

**Issue by cula-sp** [tridactyl/tridactyl#1967]
Tridactyl version: 1.17.0pre3297-8a4075e
Firefox version: Mozilla Firefox 68.2.0
Operating system: linux

I have a question about "quickmark". I'm setting a quickmark with multiple urls, say, 
quickmark s https://www.bing.com/ https://i.duckduckgo.com/ https://www.ldoceonline.com/
The setting is also written on my own ~/.tridactylrc

But I find that except for the first url, the other two are opened with "[object Object]", like
https://i.duckduckgo.com/ [object Object] 
or 
https://www.ldoceonline.com/ [object Object]

The problem may come from JavaScript. I try many times to solve it, but I still cannot figure it out. Is there any solution to solve it? Thanks for the help.

**Comment by bovine3dom** [comment]
This was a bug. We can't fix it for current binds, so you'd need to make those quickmarks again once the beta is released in a few minutes. Thanks for pointing it out!
