### ISSUE TITLE
Urlbar/address bar is selected when opening help page

### ISSUE THREAD

**Issue by noctuid** [tridactyl/tridactyl#1974]
Tridactyl version: 1.17.0pre3297-8a4075e
Firefox version: Mozilla Firefox 70.0
Operating system: linux

I'm not sure whether or not this is expected. I couldn't find another open issue, but maybe I was searching for the wrong thing.

When I do `:h topic` on a non-help page, the urlbar is selected when the help page is opened, and I either have to click or press tab a few times to focus the page. This happens without any config (after `sanitize tridactylsync`).

**Comment by bovine3dom** [comment]
Probably the same cause as #1652 - i.e. a Firefox bug/feature that we can't do much about.

**Comment by noctuid** [comment]
Do you mean `newtabfocus` is broken for both settings?

**Comment by bovine3dom** [comment]
No, newtabfocus only ever worked on the new tab page. I don't think we've tried it on other pages. I think all extension pages when opened in new tabs lose focus.

Someone recently opened an issue on bugzilla asking for a setting to set the focus to always be on the page for newly-opened tabs, but I can't find it.

**Comment by soifou** [comment]
@bovine3dom I think you mean this one https://bugzilla.mozilla.org/show_bug.cgi?id=1589987

**Comment by bovine3dom** [comment]
Fixed in #2490
