### ISSUE TITLE
autocmd is not working from tridactylrc

### ISSUE THREAD

**Issue by dhharris** [tridactyl/tridactyl#1982]
Tridactyl version: 1.17.1pre3316-2cd0a0f
Firefox version: Mozilla Firefox 70.0.1
Operating system: mac

*   Briefly describe your issue:

`autocmd`s are not working when tridactylrc is sourced. I am not certain that this is limited to autocmd, but that is how I noticed the issue.

*   Steps to reproduce:
    1. Prerequisite: native messenger installed
    2. Set up a tridactylrc with an autocmd, i.e. `autocmd DocStart google.com mode ignore`
    3. Notice that the mode is *not* ignore on google.com

*   URL of the website the bug happens on:

Everywhere

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

https://pastebin.com/zv9JJfwD

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

https://github.com/dhharris/dotfiles/blob/master/firefox/tridactylrc

*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:
```
/usr/bin:/bin:/usr/sbin:/sbin 
```

*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:

```
b{"cmd": "run", "content": "/Users/dhh/scripts:/Users/dhh/.cargo/bin:/Users/dhh/Library/Python/3.7/bin:/usr/local/sbin:/usr/local/bin:/usr/local/opt/llvm/bin:/opt/facebook/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/opt/facebook/bin/biggrep:/opt/facebook/nuclide/latest/nuclide/pkg/fb-on-demand-cli/bin:/opt/facebook/ops/scripts/chef:/opt/homebrew/bin:/usr/local/munki:/opt/facebook/hg/bin:/opt/android_sdk/tools:/opt/android_sdk/platform-tools:/opt/android_sdk/tools:/opt/android_sdk/platform-tools\n", "code": 0}
```

**Comment by bovine3dom** [comment]
I think this is another race condition.

If I add the autocmd to the start of my RC file it doesn't work. If I add it to the bottom of my RC file it does work.

If I make a special RC file with only the autocmd in it and source that specially it does work.

#1983 fixes the issue for me but it feels like a bad-to-terrible idea, especially if people use RCs to store all their config as it could potentially be seconds before all of their config is done.

**Comment by bovine3dom** [comment]
That PR closed this a little eagerly. Let us know if the latest beta fixes it :)

**Comment by dhharris** [comment]
Running version 2cd0a0fb6ac1d0ef623b600be37faad0934f41f3 now. Still not working with my RC file :(

**Comment by dhharris** [comment]
Working now as of 1.17.1pre3333-30fb7cb (30fb7cb)
