### ISSUE TITLE
Counts not working for scrollline?

### ISSUE THREAD

**Issue by forgetmenotz** [tridactyl/tridactyl#1984]
Hi all,

When I apply a count to a scroll action (e.g "5k" to scroll down) it did not scroll "n" times the default scroll value as stated in the help page, instead remaining at its normal scroll speed.

My scroll binds are :bind i scrollline -10, and :bind k scrollline 10. (I use ijkl for movements universally.) I tried 1/-1 too.

My config is here. https://gist.github.com/forgetmenotz/e9e0d3011188969128402e4aadfe2ab9#file-tridactyl-config-06-11-19

Thanks!

**Comment by bovine3dom** [comment]
Should be fixed in the latest betas, available approx 5-10 minutes after this post :)
