### ISSUE TITLE
Better tabopen

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#1993]
As said on Matrix, `tabopen -b` doesn't focus the urlbar while `tabopen` does. `tabopen` should use `tabopen -b` and then only then focus the newly opened tab.

**Comment by bovine3dom** [comment]
Should maybe have an option to disable this behaviour if it looks too janky

**Comment by notJerl** [comment]
If this Bugzilla ticket gets completed, we won't need to go through those hoops: https://bugzilla.mozilla.org/show_bug.cgi?id=1589987
