### ISSUE TITLE
Pipe shell command output to tridactyl command

### ISSUE THREAD

**Issue by noctuid** [tridactyl/tridactyl#2002]
Is there some way to use the stdout of a command as an argument? As one example, I'd like to do something along the lines of `composite ! awk '/default/ {print $3}' <(ip route) | tabopen`. Maybe this is possible with `js`? Is it possible at all?

**Comment by glacambre** [comment]
`jsb tri.native.run("echo http://example.org/").then(result => tri.excmds.tabopen(result.content))` seems to work.

**Comment by bovine3dom** [comment]
I think you just need to use `!s` instead: `composite !s awk '/default/ {print $3}' <(ip route) | tabopen`

**Comment by noctuid** [comment]
I was trying to figure out how to workaround `|` not working with composite, but `<()` doesn't work with `composite !s ...`. `!s` does work for a simple command, but I had to use `tri.native.run` to get a pipeline to work (e.g. `jsb tri.native.run("echo 'example.org dont-open-me.com' | awk '{print $1}'").then(result => tri.excmds.tabopen(result.content))`). Thanks!

**Comment by bovine3dom** [comment]
`<()` doesn't work with composite or pipelines don't? The former would be quite surprising to me.

`composite` steals all pipes and semicolons because I wrote it without thinking. One solution is to write and alias e.g. `alias foo !s echo bar | grep -v pub` and then `composite foo | tabopen`.

**Comment by noctuid** [comment]
> <() doesn't work with composite or pipelines don't?

Neither works. `<()` doesn't seem to work with `!` or `tri.native.run`. Not sure why, but `!s bash -c "command with <()"` does work though (`/bin/sh` is bash on my system for reference).

**Comment by glacambre** [comment]
Not surprising. Python probably has its own bad shell implementation it uses for [popen](https://github.com/tridactyl/tridactyl/blob/30fb7cbe0a44b9bb953523c28b5caad905a0aba7/native/native_main.py#L426) and it probably doesn't support things like pipes and redirections. We should probably just stick whatever command the user tries to run into a file and ask a shell to execute it instead of using popen.
