### ISSUE TITLE
# controller while accepting: Could not find type information for excmd rsssave

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#2009]
Tridactyl version: 1.17.1pre3326-e5c676a
Firefox version: Mozilla Firefox 70.0.1
Operating system: linux

I get the following error message when trying to execute `:rssexec` on any website with a feed:
```
# controller while accepting: Could not find type information for excmd rsssave
```
I think this could be related to #2001 as the error disappeared after manually running `:source`.

**Comment by bovine3dom** [comment]
For future reference: `rsssave` is a custom alias that glacambre uses:

https://github.com/glacambre/.dotfiles/blob/6ceba2afda5041a34a108c67bb4bd0899cce583b/default/.config/tridactyl/tridactylrc#L8

**Comment by glacambre** [comment]
Hah, completely forgot that rsssave was an alias of mine, sorry. This error is most certainly #2001 then (can't expand the alias => treat as excmd => no types for non-existing excmd).
