### ISSUE TITLE
Interact with pinboard?

### ISSUE THREAD

**Issue by alerque** [tridactyl/tridactyl#2019]
Has anybody worked out a way to interact with (esp. save to) [pinboard.in](https://pinboard.in/) from Tridactyl without having a toolbar active? There are a number of extensions for doing so, but they all rely on being able to access their own little interface popups. Since I can't get to that (see #2018) I'm wondering if anybody has come up with another way.

**Comment by glacambre** [comment]
Since there are dozens of extensions for interacting with pinboard the API must be really simple to use. I think it should be possible to implement a set of commands that use `:js` in order to do that.

**Comment by alerque** [comment]
Note there seem to be a [number of Bookmarklets](https://pinboard.in/howto/#saving) documented upstream. I haven't figured out how to make those into bindings yet, but that seems promising.

**Comment by bovine3dom** [comment]
It should be as simple as `bind [key sequence] open [bookmarklet]`.
