### ISSUE TITLE
Way to show the command line at top?

### ISSUE THREAD

**Issue by mightbered** [tridactyl/tridactyl#2024]
Its really cumbersome when a page is loading or when my mouse is on top of a link as it shows the link details on the bottom of the page where the cmdline is. I'm new to tridactyl, and is there a way to show the cmdline at top?

**Comment by alerque** [comment]
The location of the command line is actually specified in the theme. See `:help theme` and the [theme names in the repository](https://github.com/tridactyl/tridactyl/tree/master/src/static/themes) for available themes you can try. I use *shydactyl* which actually has the command line in the middle of the screen. You may want to try the *quake* theme which has it at the top: `:set theme quake`.

**Comment by mightbered** [comment]
Nice! thank you

**Comment by bovine3dom** [comment]
`:colours quakelight` does much the same @zeorin : )

**Comment by zeorin** [comment]
One thing that annoyed me about `quakelight` (and `quake`) was that the actual input line is at the bottom, still. The height of the completions is variable, as you narrow down the options while typing, meaning that the input line jumps up, too, as you type.

This was a most jarring experience. My theme puts the command line above the completions (like `shydactyl`), which alleviates this problem.

**Comment by bovine3dom** [comment]
Fair enough - glad you found a good solution : )
