### ISSUE TITLE
Tridactyl can't read local conf file

### ISSUE THREAD

**Issue by N214** [tridactyl/tridactyl#2028]
Tridactyl version: 1.17.1pre3304-7dcf183
Firefox version: Mozilla Firefox 70.0.1

Since I reinstalled my OS, tridactyl can't read my local config file anymore and :mkt does not work either? I don't understand what's the problem

**Comment by bovine3dom** [comment]
Thanks for filing this issue. I have a few questions / things to try:

Do you get any error messages? Do you see any in the web console (Ctrl-Shift-J) or the browser console (Ctrl-Shift-J)?

Where is your source file?

Does it work when you run `:source` manually?

If you add something obvious to the start of your RC file (e.g. `tabopen news.bbc.co.uk`) does that run?

**Comment by N214** [comment]
Thanks for your reply,

Yes I do get error messages in the web console. Mainly a bunch of 

> "WebExtension context not found!"
and some 

> No such native application tridactyl "startupPromise resource://gre/modules/NativeMessaging.jsm:112"

The RC file is in $HOME/.tridactylrc, it does not work when I source manually.

**Comment by bovine3dom** [comment]
Have you got the native messenger installed? What is the output of `:! pwd` and `:native`?

**Comment by N214** [comment]
Thanks a lot, it worked with `:installnative ` !
