### ISSUE TITLE
Remove XUL namespace from userChrome.css for guiset

### ISSUE THREAD

**Issue by zeorin** [tridactyl/tridactyl#2037]
Firefox 72 (current Developer Edition) doesn't work correctly with the generated `userChrome.css` from `guiset` because the browser UI is no longer made using XUL, but Web Components. Removing `@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");` from the top of the file fixes the issue.

https://github.com/tridactyl/tridactyl/blob/266988344ec8fcd524311e61914d82ff44fcc703/src/excmds.ts#L379 seems to add that line.

**Comment by bovine3dom** [comment]
Does your suggestion still work in FF71?

**Comment by zeorin** [comment]
I have tested it with FF70, where it still worked.
