### ISSUE TITLE
paste url to external file. 

### ISSUE THREAD

**Issue by fullstopslash** [tridactyl/tridactyl#2047]
Maybe you all can help me out. I've been having the hardest time trying to find the exact commands to accomplish this.
Basically I'd like to bind a key to delete the current tab and append the url to a file. I've come up with something like this, but it isn't /quite/ there. 
`composite get_current_url | fillcmdline echo >> $HOME/file.txt`
This obviously puts the arguments in all the wrong order. Is there any way to fill the commandline and add text from the beginning? Or a way to execute part of it first like $() in a shell script?

**Comment by glacambre** [comment]
`js tri.native.run('tee -a /tmp/test', document.location.href + "\n").then(_ => tri.excmds.tabclose())` will probably do what you want :)

**Comment by bovine3dom** [comment]
You might want to wrap the `href` in `shellescape` first to make sure you don't accidentally run random commands in your shell:

`composite get_current_url | shellescape | js -p tri.native.run('tee -a /tmp/test', JS_ARG + "\n").then(_ => tri.excmds.tabclose())`

**Comment by glacambre** [comment]
I don't think `shellescape`'ing the url is necessary since the second argument of tri.native.run is piped to `tee` instead of being evaluated by a shell.
