### ISSUE TITLE
bind `Y` to select highlighted text

### ISSUE THREAD

**Issue by mozbugbox** [tridactyl/tridactyl#2050]
Tridactyl version: 1.17.1pre3367-30eadf31
Firefox version: Mozilla Firefox 68.2.0
Operating system: linux

The shortcut is handy on reducing mouse clicks when trying to copy text phrases from a webpage. 

`bind Y composite js document.getSelection().toString() | yank`

**Comment by bovine3dom** [comment]
The bind is a cool idea. I'm not sure I like the key you're binding it to (I think most people have Y in vim bound to "yank-to-end-of-line").

I think I'd rather have a `select` mode that is entered when text is selected via https://developer.mozilla.org/en-US/docs/Web/API/Document/selectionchange_event and then bind `y` to your suggestion in that mode.

**Comment by bovine3dom** [comment]
In the latest betas (available in about 5 minutes from this comment being posted), select text with the mouse or caret mode (F7) and then press `y` to copy.

The selection can be extended and reduced with some of the usual motions (hjklebw).
