### ISSUE TITLE
Unable to set new tab `about:home` 

### ISSUE THREAD

**Issue by Dentrax** [tridactyl/tridactyl#2051]
Tridactyl version: _1.17.1pre3304-7dcf183_
Firefox version: _Mozilla Firefox 71.0_
Operating system: _Arch_

**Suggestion:** Please **DO NOT** _override new tab URL_ on fresh install. This can be annoying.

*   Brief description of the problem:

I just installed this extension on my fresh-installed Firefox. And just tried to open new tab but i couldn't get default `about:home` start page even i set the `newtab about:home`. Ref: #948, #1090, #2035; All closed but solutions didn't work for me.

*   Steps to reproduce:

1. :set newtab about:home
2. Restart
3. Open new tab

*   URL of the website the bug happens on: **New tab (White-blank)**

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com): https://gist.github.com/Dentrax/2f5f3018b74df02efc5882af1d2334d0

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist): **Both of not exist**

*   Result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal: **Not exist**

**Comment by glacambre** [comment]
You probably want to use the [build that doesn't have a newtab page](https://github.com/tridactyl/tridactyl#beta) instead of the one you're currently using.

**Comment by Dentrax** [comment]
@glacambre Hey, i've installed it on officially Firefox extension store, and i don't want to deal with beta or compile things. Are there any _simple_ way to fix this?

**Comment by glacambre** [comment]
>Are there any simple way to fix this?

I don't think so.

**Comment by bovine3dom** [comment]
I regard the "beta" builds as the stable builds. The versions on the AMO are just old. They're unlikely to have fewer bugs. You just need to open https://tridactyl.cmcaine.co.uk/betas/nonewtab/tridactyl_no_new_tab_beta-latest.xpi in Firefox and it will install. Make sure you disable the old Tridactyl via about:addons.

Migrating your configuration is slightly more involved.

**Comment by Dentrax** [comment]
Thanks, beta build fixed my problem.

**Comment by Jestar342** [comment]
> I regard the "beta" builds as the stable builds. The versions on the AMO are just old. They're unlikely to have fewer bugs. You just need to open https://tridactyl.cmcaine.co.uk/betas/nonewtab/tridactyl_no_new_tab_beta-latest.xpi in Firefox and it will install. Make sure you disable the old Tridactyl via about:addons.
> 
> Migrating your configuration is slightly more involved.

Why are they even called "beta" then? Why aren't _they_ in the extension store? Why must tridactyl do things differently to how just about every other extension out there does it?

**Comment by bovine3dom** [comment]
Beta releases are completely automated. They were previously on the store but Mozilla removed that functionality. They're called Beta because that's what Mozilla called them. https://blog.mozilla.org/addons/2018/02/28/discontinuing-support-for-beta-versions/

Stable releases take about 20 minutes of really boring faffing around. I didn't want to double that by having to do two releases every time to keep the nonewtab build in sync.

I don't have a theory on why other extensions are developed differently. I write Tridactyl for myself and I'm always slightly perplexed when I see anyone else using it. I don't know why anyone else writes extensions.

**Comment by Jestar342** [comment]
My apologies, my previous reply was inappropriately toned. 

> Stable releases take about 20 minutes of really boring faffing around.

Is that faff imposed by AMO or by the build?

**Comment by bovine3dom** [comment]
It's imposed by the AMO - they require that source code is manually uploaded. So I have to run the build manually, wait for it to finish, download the source code from our buildbot, log in to the developer site, find the button to upload the source code (which is quite poorly signposted) and finally upload the source code to a really slow server.

I imagine it would be possible to modify `web-ext` and the AMO backend to allow it to upload a zip of the source code which would remove most of the friction.
