### ISSUE TITLE
buildbot down?

### ISSUE THREAD

**Issue by chrispickard** [tridactyl/tridactyl#2064]
is the buildbot down? the latest I'm seeing is `1.17.1pre3355-6facf5d` from november 30th.

**Comment by bovine3dom** [comment]
Good spot. We need to accept some new Mozilla TOS before it can sign anything. I think it's on cmcaine's account so we'll have to wait for him to take a breather from his festivities :)

**Comment by cmcaine** [comment]
Fixed
