### ISSUE TITLE
Duplicate tab

### ISSUE THREAD

**Issue by mb720** [tridactyl/tridactyl#2074]
Hi and thanks a lot for Tridactyl!

I was wondering if there's a keybinding for duplicating a tab?

Currently I have to use the mouse to right-click on a tab and select "Duplicate Tab".

---

Tridactyl version: 1.17.1pre3304-7dcf183
Firefox version: Mozilla Firefox 71.0
Operating system: linux

**Comment by glacambre** [comment]
Theres `:tabduplicate`, which you can bind to anything you want. Read `:help duplicate` to know more about it :)

**Comment by mb720** [comment]
Thanks for pointing that out!
I used `:bind yd tabduplicate` to get what I wanted.
