### ISSUE TITLE
Filter links from top to bottom

### ISSUE THREAD

**Issue by jcalonso** [tridactyl/tridactyl#2077]
Tridactyl version: 1.17.1pre3304-7dcf183
Firefox version: Mozilla Firefox 71.0
Operating system: linux

Hello, I have this 2 settings:
```
"hintfiltermode": "vimperator-reflow"
"hintnames": "numeric"
```
When filtering links (f) and pressing tab, the selection start from bottom to top of the page, is there a way to reverse this? start from top to bottom.

Maybe I am missing some config.

**Comment by bovine3dom** [comment]
I think this is a bug. I can't imagine we'd do that on purpose.

**Comment by jcalonso** [comment]
@bovine3dom somehow this is happening again, I checked the lines you fixed, and those are still correct. not sure is it is happening somewhere else now. any ideas?

**Comment by glacambre** [comment]
@jcalonso What Tridactyl version are you using? What does `:bind --mode=hint <Tab>` print?

**Comment by jcalonso** [comment]
Hey @glacambre, that command doesn't print anything, version is:
`1.17.1pre3304-7dcf183`
Just noticed that my version is older that the change made by @bovine3dom (not sure how it was working before then)
This is reason why is not working I guess.

**Comment by bovine3dom** [comment]
That version looks like it might be the stable version. Does about:addons say Tridactyl: Beta or just Tridactyl?

**Comment by jcalonso** [comment]
Just Tridactyl:
![screenshot_2020-02-19_23-30-57_032214983](https://user-images.githubusercontent.com/664474/74886539-570af580-5370-11ea-99e2-7a75530d70d9.png)

**Comment by bovine3dom** [comment]
Ah, that's an easy answer then: we haven't released the fix in a stable version yet. It's only in the Beta editions. I won't do a stable release for at least a week as I just merged some slightly risky stuff that completely changes how configuration is synchronised between tabs.

**Comment by jcalonso** [comment]
Got it, thanks, now I am on beta and works great. Sorry for the confusion.
Keep up the amazing work :+1:
