### ISSUE TITLE
guiset no longer works in Firefox 72

### ISSUE THREAD

**Issue by leaty** [tridactyl/tridactyl#2078]
Tridactyl version: 1.17.1pre3441-7a22e96
Firefox version: Mozilla Firefox 72.0
Operating system: 5.4.8-arch1-1

*   Brief description of the problem:

`guiset` does not work fully in Firefox 72, cannot get rid of address bar (navbar) anymore.

*   Steps to reproduce:
1. Upgraded Firefox to 72
2. Noticed whole gui visible.
3. All but the navbar hidden after running `guiset gui none`.
4. Navbar still visible after `guiset navbar none` as well.
5. Retried after reinstalling native, no luck.

If it's not just me, then I realize Firefox obviously changed something, but goddamn am I missing this amazing feature. I just really hope that Firefox didn't make it unfixable.

**Comment by alerque** [comment]
I'm on FF72 and still able to use `guiset`. I found this setup in my rc file works to disable the navbar and tabbar completely:

```
guiset_quiet gui none
guiset_quiet tabstoolbar show
guiset_quiet tabs autohide
guiset_quiet navbar autohide
guiset_quiet hoverlink left
guiset_quiet statuspanel left
```

Note trying to set *tabs* and *navbar* to `none` on their own does not work as expected, but enabling them plus setting *gui* to `none` seems to work.

**Comment by leaty** [comment]
Thanks for that, sadly it didn't work for me - in fact it made everything show after I restarted Firefox 2-3 times (did it because it didn't change anything at first), very odd. I moved `guiset_quiet gui none` to be last because I thought it made sense, nothing changed. I tried to fiddle manually as well but it still hasn't gone away once in any of my attempts, doesn't even go into autohide mode.

Want to swap PC? I'm desperate :smiley:

**Comment by alerque** [comment]
I just updated another machine to FF72. I had some trouble getting these settings working, it took a couple times running them before they worked like I expected. I ended updating my rc file with a slightly different ordering, but I'm not sure if the rc file actually sets these right, I think some combination of running them manually did the trick in the end. You're welcome to review [my tridactylrc](https://github.com/alerque/que-firefox/blob/master/.config/tridactyl/tridactylrc) file.

**Comment by leaty** [comment]
Honestly, I think you're just a wizard. I can't for the life of me get it to work properly no matter how many times/regardless of order I try. But I'll try on another rig later just to be safe.

**Comment by bovine3dom** [comment]
@leaty, did you see `Upcoming userChrome breakage Firefox 72 requires that @namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"); is not in your userChrome.css. You will need to remove that line manually from chrome/userChrome.css if you have either created that file manually or used guiset. You can find your profile folder on about:support.` on the new tab page?

**Comment by leaty** [comment]
Thanks! @bovine3dom 

I have a custom new tab page so I did not see that, but it works perfectly now.

**Comment by protrolium** [comment]
thank you @leaty @bovine3dom for showing the @namespace exception. I was having the same issue with the navbar displaying even after `guiset gui none`
