### ISSUE TITLE
Other extensions keybindings don't work along with tridactyl

### ISSUE THREAD

**Issue by dit7ya** [tridactyl/tridactyl#2096]
Tridactyl version: 1.17.1pre3304-7dcf183
Firefox version: Mozilla Firefox 72.0.1
Operating system: linux

*   Brief description of the problem:

I am trying to use tridactyl along with [Memex](https://worldbrain.io/memex) which comes with its own shortcut keys. Those shortcuts are not working in any webpage, not even the ones that do not conflict with tridactyl (for example c).

*   Steps to reproduce:

    1.  Install [Memex](https://addons.mozilla.org/en-US/firefox/addon/worldbrain/).

	2. Try any of the shortcut keys with Tridactly enabled on a webpage.

**Comment by bovine3dom** [comment]
I've had a brief play with this. The binds work fine for me, with the exception of `c`, e.g.:

1. Install Memex and Tridactyl
2. Visit https://www.bbc.co.uk/news/uk-51109538
3. `:unbind r`, press `r`
4. "Memex" menu opens.

For `c`, I just have to press it twice the first time on a page. Other binds such as `n` to highlight text work fine (it even works nicely with `visual` mode :) ).

**Comment by dit7ya** [comment]
I clean installed Memex and the problem disappeared, I guess it was not tridactyl's fault at all.

Also, there is a visual mode for tridactyl?!! :open_mouth:

**Comment by bovine3dom** [comment]
Visual mode is only in the betas for now :)
