### ISSUE TITLE
Timeout like vim timeout

### ISSUE THREAD

**Issue by eatthoselemons** [tridactyl/tridactyl#2101]
Tridactyl version: 1.17.1pre3304-7dcf183
Firefox version: Mozilla Firefox 72.0.1
Operating system: linux

# Making a feature request

I would like to be able to have a timeout like there is in vim so I can bind jk to <Esc> this works natively in vim with `inoremap jk <Esc>` however it relies on a timeout feature and some other method as well that I don't know about so it doesn't capture ju if you type those in quick succession. Unsure how close Tridactyl is to vim and how it implements vimscript but would love this feature as it would make tridactyl usable for me as well as allow great improvements to window movement reducing the number of modifiers needed.

**Comment by bovine3dom** [comment]
This would make our parser much more complicated.

I think it might also be fundamentally impossible in Firefox. To implement it we would have to cancel the key events as we currently do, but then fire them again if the timeout was passed without any valid commands being executed. Key events that we generate are marked as fake so most (?) web pages ignore them.

If you're really keen on it, I'd merge a PR that a) worked reasonably well and b) was switched off by default.

**Comment by eatthoselemons** [comment]
That is good to know that this sort of feature would be fundamentally impossible in Firefox.

Based on what would be needed I will attempt to use other avenues to solve the issue but might be drawn back to making a PR.

Thanks for getting back to me!

**Comment by bovine3dom** [comment]
It's probably possible to get it working for most cases (e.g. in input boxes by inserting the j or k characters directly rather than trying to re-fire key events). It'd be very messy though.

I'm personally in the "capslock is escape when tapped and control when held" gang. I use `xcape` on Linux and a random autohotkey script on Windows.

**Comment by eatthoselemons** [comment]
How do you set capslock to esc? on tap and ctrl on hold? I assume that you are using a regular off the shelf keyboard to QMK isn't how you are doing it?

It would be possible to do it that way but that is such a specific implementation that it concerns me it would be too specific and limit other options. However changing the keyboard would make more sense and I could even use QMK to map to esc so should fix the keyboard issue first since that is the easier and better issue to tackle for this issue.

**Comment by bovine3dom** [comment]
It's just software: https://gist.github.com/tanyuan/55bca522bf50363ae4573d4bdcf06e2e
