### ISSUE TITLE
How to delete specific URL in tridactyl history

### ISSUE THREAD

**Issue by yulrizka** [tridactyl/tridactyl#2115]
Tridactyl version: 1.17.1pre3304-7dcf183
Firefox version: Mozilla Firefox 73.0
Operating system: mac

*   Brief description of the problem:
I wanted to delete history for a specific url eg: all history from http://host.com

**Comment by bovine3dom** [comment]
We don't store the URL a command was executed on. Could you explain more fully what you mean by "history"?

If you mean the completions that appear on `tabopen`, that's just Firefox history, which you can clear in the usual fashion (e.g. press Alt to find the secret menu with focus in the URL bar, click History, click "Clear recent history").

**Comment by yulrizka** [comment]
Yes, the URL of site that I visited. Hmm I deleted the url in the url (by shift + delete). It's gone from firefox like it doesn't do completion anymore but that URL is still appearing on the open.

Apparently that doesn't clean it from the history. After i clean the url from the history it does removed it. Thanks. I'll close the ticket
