### ISSUE TITLE
Native messenger on Arch Linux

### ISSUE THREAD

**Issue by mb720** [tridactyl/tridactyl#2123]
Hi and thanks a lot for Tridactyl!

I'm having trouble getting the native messenger to run on Arch Linux.

I installed it with `pacman -S firefox-tridactyl` and restarted Firefox twice.

Executing `:native` in Firefox afterwards tells me that the native messenger could not be found.

The contents of `~/.mozilla/native-messaging-hosts/tridactyl.json` are:

    {
        "name": "tridactyl",
        "description": "Tridactyl native command handler",
        "path": "REPLACE_ME_WITH_SED",
        "type": "stdio",
        "allowed_extensions": [ "tridactyl.vim@cmcaine.co.uk","tridactyl.vim.betas@cmcaine.co.uk", "tridactyl.vim.betas.nonewtab@cmcaine.co.uk" ]
    }

`pacman -Ql firefox-tridactyl` says that the file `/usr/lib/firefox/browser/extensions/tridactyl.vim\@cmcaine.co.uk.xpi` belongs to the package, but it's empty.

Thanks for looking into this!

---

Tridactyl version: 1.17.1pre3304-7dcf183
Firefox version: Mozilla Firefox 72.0.2
Operating system: linux

**Comment by bovine3dom** [comment]
`firefox-tridactyl` is the extension, not the native messenger. You want `firefox-tridactyl-native`, which is on the AUR: https://aur.archlinux.org/packages/firefox-tridactyl-native/ :)

**Comment by mb720** [comment]
Good gracious! Sorry for the mix up! :-)

I installed the native messenger with `sudo aura -A firefox-tridactyl-native`.

After changing a line in `~/.mozilla/native-messaging-hosts/tridactyl.json` to

    "path": "/usr/lib/tridactyl/native_main.py",

calling `:native` in Firefox works:

>Native messenger is correctly installed, version 0.1.11

Thanks for your help!
