### ISSUE TITLE
Make Tridactyl font size configurable

### ISSUE THREAD

**Issue by protrolium** [tridactyl/tridactyl#2127]
I am not sure how to target the text-size in my ~/.tridactylrc. I would like to increase the text-size of the command line and buffer list readout.

Tridactyl version: 1.17.1pre3304-7dcf183
Firefox version: Mozilla Firefox 72.0.1
Operating system: mac

**Comment by bovine3dom** [comment]
There isn't an easy way to set only the font size. There is a theme in Tridactyl with a larger font size - `:colors shydactyl`.

If you wish to "keep" the default theme, you will need to make your own theme. See e.g. https://github.com/tridactyl/tridactyl/blob/master/src/static/themes/dark/dark.css and `:help colours` for limited instructions on how to make one. Ask on Riot if you get stuck :)

**Comment by bovine3dom** [comment]
We get asked this enough that we should add a variable that people can change in userContent.css

https://developer.mozilla.org/en-US/docs/Web/CSS/font-size - we should change all the other fonts to use percentages relative to the default Tridactyl size

**Comment by upbqdn** [comment]
Related to #3198.

**Comment by bovine3dom** [comment]
this should only be a five minute job as described (a variable that can be changed via userContent.css or maybe Stylus), so I should really do it

**Comment by bovine3dom** [comment]
I don't want to do this before I do the next release just in case I mess it up on some screen sizes / pixel ratios

But I think it is as simple as changing all the `font-size` variables here https://github.com/tridactyl/tridactyl/blob/b5507f3b803a84b1969922c9f1cb9349fe3a6288/src/static/themes/default/default.css#L5
 to be `calc(var(--tridactyl-font-size) * x)` where `x` is some fraction to be determined that leaves all the fonts roughly the same size as they are currently. 4/3 pt = 1 px
