### ISSUE TITLE
:source reads only parts of tridactylrc

### ISSUE THREAD

**Issue by mb720** [tridactyl/tridactyl#2135]
Hi!

At `~/.config/tridactyl/tridacytlrc` I have a file with this content:

    " General Settings
    js tri.config.set("update", {"lastchecktime": 1580650690239})
    set configversion 1.8
    js tri.config.set("searchurls", {"we": "https://en.wikipedia.org/w/index.php?search="})
    js tri.config.set("searchurls", {"wd": "https://de.wikipedia.org/w/index.php?search="})
    js tri.config.set("searchurls", {"d": "https://www.dict.cc/?s="})
    js tri.config.set("searchurls", {"y": "https://www.youtube.com/results?search_query="})
    js tri.config.set("searchurls", {"ga": "https://google.at/search?q="})
    js tri.config.set("searchurls", {"ho": "https://hoogle.haskell.org/?hoogle="})

    " Binds
    bind yd tabduplicate

    " vim: set filetype=vim:

After running `:source ~/.config/tridactyl/tridacytlrc`, I can see that the `we` search URL doesn't work, it instead uses DuckDuckGo.

To see the currently used configuration, I ran `:mkt!`. That changed `~/.config/tridactyl/tridacytlrc` to this:

    " General Settings
    js tri.config.set("searchurls", {"ho": "https://hoogle.haskell.org/?hoogle="})
    set configversion 1.8
    js tri.config.set("update", {"lastchecktime": 1580650690239})

    " Binds
    bind yd tabduplicate

    " vim: set filetype=vim:

That's suprising, this removed all the search URLs but the last.

---

Running `:native`, I get

    Native messenger is correctly installed, version 0.1.11

I installed the native messenger from AUR.

Tridactyl version: 1.17.1pre3304-7dcf183
Firefox version: Mozilla Firefox 72.0.2
Operating system: linux

*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:

    /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/mb/.local/bin

*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:

    bash: /home/mb/.local/share/tridactyl/native_main.py: No such file or directory

**Comment by bovine3dom** [comment]
Closing as a duplicate / very closely related to #1409 - we had hoped it was fixed in #1764 but apparently not :(

**Comment by mb720** [comment]
No worries!

Thanks for checking it out! 👍
