### ISSUE TITLE
Weird composite behavior

### ISSUE THREAD

**Issue by user471** [tridactyl/tridactyl#2138]
Tridactyl version: 1.17.1pre3511-ae40375
Firefox version: Mozilla Firefox 72.0.2
Operating system: win

I created this bind a while ago.
```
bind s composite js document.execCommand("copy") ; js "tabnew " | fillcmdline
```
When I press `s` it should copy selected text and open command line with `tabnew`. It worked in 1.16
But in 1.17 when I press `s` it somehow open `open search [selected text]`

**Comment by bovine3dom** [comment]
You enter visual mode when you select text now. You can press `y` to copy text like you want by default.

If you want to turn off entering visual mode automatically you can run `:set visualenterauto false`.

A third option would be to run `:bind --mode=visual s composite js document.execCommand("copy") ; js "tabnew " | fillcmdline`
