### ISSUE TITLE
Not working on some site.

### ISSUE THREAD

**Issue by nuynait** [tridactyl/tridactyl#2139]
Tridactyl version: 1.17.1pre3304-7dcf183
Firefox version: Mozilla Firefox 72.0.2
Operating system: mac

Tridactyl completely not working on site such as: [Firefox Support](https://support.mozilla.org/en-US/products/firefox).

It also doesn't work on my bank site. After login to the account, it stops working. 

When I say stops working / not working above, I mean it behaves on that tab as I never installed Tridactyl. 

I wonder if I have a config issue or if that's a bug, or if that's expected behaviour? 

Thanks very much for your time. 😊

**Comment by bovine3dom** [comment]
Your bank site is probably using "Content Security Policy" to protect you from some kinds of attack - check the web console to see if you get any errors mentioning this. Firefox erroneously applies this policy to extensions too, which they say they will fix someday (see #760). We had a workaround for this but Mozilla asked us to remove it.

Firefox support probably stops all extensions from working on it for what they consider to be your security and the security of their entire add-on ecosystem. We had a workaround for this but Mozilla asked us to remove it.

It is still possible to replicate the workarounds in your RC file (which I personally do as I think the risks are tiny). Mozilla strongly suggests this is a bad idea.

**Comment by nuynait** [comment]
Thanks very much for the quick reply. Interesting to know. I do believe that the risks are tiny. Able to give some hint on how to replicate the workarounds in the RC file? 

So much appreciate your time and help. 

@bovine3dom

**Comment by bovine3dom** [comment]
My RC file is here and contains both workarounds: https://github.com/tridactyl/tridactyl/blob/master/.tridactylrc. I'd suggest you read up on CSP before you try to hack it apart - https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by nuynait** [comment]
@bovine3dom Thanks a lot for providing your RC file and additional resource for better understanding the topic.

I appreciate this so much. Going to try this at night after work.
