### ISSUE TITLE
open and tabopen does not search through bookmarks

### ISSUE THREAD

**Issue by vkamesh** [tridactyl/tridactyl#214]
Open and tabopen does not search through bookmarks. It only searches through history. If you clear you history regularly then you cannot have any filter or autocompletion. 

I am on firefox nightly (59.0a1 (2017-12-05) (64-bit)).

**Comment by bovine3dom** [comment]
This is on our to-do list, blocked by rewrite of completions. You can use `bmarks` in the meantime.

**Comment by vkamesh** [comment]
Great. Thank you. Looking forward for the rewrite. You guys are doing great job.

**Comment by P4Cu** [comment]
looks like bmarks has no documentation

**Comment by YorkZ** [comment]
When can this be fixed?

**Comment by bovine3dom** [comment]
@YorkZ we need to rewrite completions to allow for multiple completion sources. It might happen within the next few days. If it doesn't, it'll probably take much longer. `:bmarks` does exist already. You could bind it with, e.g. `bind \ fillcmdline bmarks`.

**Comment by glacambre** [comment]
I think it's unlikely to happen in the next few days.
