### ISSUE TITLE
how to set a key to write ":tabopen wikipedia" shortcut?

### ISSUE THREAD

**Issue by LucKy-4U** [tridactyl/tridactyl#2142]
Tridactyl version: 1.17.1pre3304-7dcf183
Firefox version: Mozilla Firefox 70.0
Operating system: linux

I want to set a shortcut key which automatically writes `:tabopen wikipedia` and waits for me to write the text that I want to search.
How do I do this?
I tried bind and alias but neither of them worked in doing this. :(

**Comment by bovine3dom** [comment]
E.g. `bind q fillcmdline tabopen wikipedia`. In general you can find what a key is currently bound to with `bind [key]`, so e.g. `bind t` would have told you how to do it :)

**Comment by LucKy-4U** [comment]
> E.g. `bind q fillcmdline tabopen wikipedia`. In general you can find what a key is currently bound to with `bind [key]`, so e.g. `bind t` would have told you how to do it :)

oops, I didn't see the obvious. ie, "fillcmdline" is supposed to Fill the Command line with stuff. :P
hahaha. I thought fillcmdline were supposed to send code to the linux command line or do something else. :P my bad.

yea, I know about bind [key], just didn't know what fillcmdline was supposed to do. I did finish your tutor lesson though. :))
Thanks for this add-on and really great work. :))
really appreciate the help. :))

**Comment by LucKy-4U** [comment]
@bovine3dom: why do you have G and Ctrl-G for searching? wouldn't N and Ctrl-N have made more sense given that N is used on vim editor for searching?

**Comment by bovine3dom** [comment]
The find mode is built-in to Firefox, it's not really anything to do with us :)

We have our own find mode which is left unbound by default - see `:help find`. You can bind that to the usual n/N.

Closing this issue as I believe it has been resolved :)

**Comment by LucKy-4U** [comment]
> The find mode is built-in to Firefox, it's not really anything to do with us :)
> 
> We have our own find mode which is left unbound by default - see `:help find`. You can bind that to the usual n/N.
> 
> Closing this issue as I believe it has been resolved :)

Yes, I was referring to the find mode that Tridactyl enables. by default it sets G and Ctrl+G as the default keys for going forward or backwards and is not left unbound.

I was calculating my pros and cons on whether to use Tridactyl or Vimium and till now, I have calculated 2 pros for tridactyl, which are:
1) Auto searches in find without having to press enter whereas in vimium you have to press enter to start the search.
2) It is made for firefox whereas vimium is a port of a chrome addon.

Cons:
1) Sub-par Tutorial, very hard to fiind out what exactly it can do and can't do and how. Features explaination is also sub-par. "You get the point" is not an explaination of the features.
2) Extra bloat because of useless firefox hacks which any user could do by modifying their userchrome.css if they wanted or by installing a million other addons.
3) Just about 20% of the features of Vimium.
4) Tridactyl breaks sometimes whereas Vimium is smooth and works perfectly everywhere.

You know, I installed this addon 2 days ago and when I installed there were 7,200 users of Tridactyl and 30,000 users of VimiumFF. I just checked it again and now there are 5100 users of Tridactyl and 33,000 users of VimiumFF.

I know and completely respect and love the fact that you guys are doing all this and are doing it for free so I have no right to ask for anything or request for anything or even say anything but I am just saying all this because I love what you guys are trying to do by bringing back vimperator and it's awesome. Kudos to you guys.
But If I were to have any say as a user who spent the past 2 days trying to figure out your addon.
I would say that you guys should stop trying to make this addon a swiss army knife of everything and anything. This addon shouldn't be able to modify firefox's appearances and have themes and such. You guys could write a separate add-on after you are done with this to do all that which could have been an extra addon on top of this. You guys could have used all that time and work to improve Tridactyl's core functionality which is subpar in comparison to vimium which is also a WIP for firefox.

Just my 2 cents, I know that I am being a little harsh and rude and my apologies for that.
Thank you for all the work that you guys have done on this addon, I appreciate and respect all your hardwork.

**Comment by glacambre** [comment]
>Yes, I was referring to the find mode that Tridactyl enables. by default it sets G and Ctrl+G as the default keys for going forward or backwards and is not left unbound.

That is Firefox's find mode, not Tridactyl's. If you uninstall Tridactyl, `/` and `<C-g>` will still work.

>Sub-par Tutorial, very hard to fiind out what exactly it can do and can't do and how.

It's not surprising that the tutorial is not helpful, it's been written by people who know the ins and outs of Tridactyl. They don't know what users might be interested in and some things that are obvious to them aren't actually obvious at all, but it's hard to tell what falls in that category. The only way this will improve is if people send pull requests or mention that they think something should be mentionned in the tutorial.

>Just about 20% of the features of Vimium.

It would be more helpful to mention what features Tridactyl is missing compared to Vimium than to simply say Tridactyl only has 20% of the features of Vimium.

>Tridactyl breaks sometimes whereas Vimium is smooth and works perfectly everywhere.

Could you open issues describing how Tridactyl breaks for you (unless there already are issues open for these breakages)?

>I love what you guys are trying to do by bringing back vimperator and it's awesome [...] This addon shouldn't be able to modify firefox's appearances and have themes and such

Seems a bit contradictory :^).

**Comment by LucKy-4U** [comment]
> That is Firefox's find mode, not Tridactyl's. If you uninstall Tridactyl, `/` and `<C-g>` will still work.
True, you are right, I just checked. I thought it was Tridactyl adding that feature.

> > Sub-par Tutorial, very hard to fiind out what exactly it can do and can't do and how.
well, look at the features explaination of Vimium, you can tell exactly what it can or can't do--even before installing it. They left out the advanced features of Vimium for the tutorial. Now compare that to Tridactyl. This is what you say on your features page: 
 >    You want to open a new tab? Hit t.
 >  You want to follow that link? Hit f and type the displayed label.
 >   You want to go to the bottom of the page? Hit G. Or the top? gg.
 >   You want to focus the text field on Wikipedia to search for another term? gi.
 >  Switch to the next tab? gt.
 >   Go back in time? H.
 >   Notice that this tab is rubbish and you want to close it? d.
 >   Regret that decision? u restores it.
 >   Want to write something in Vim? Ctrl-i in a text box opens it in Vim, if
 >   you have :native working.
 >   Temporarily disable all that magic because you can't stand it? Shift-Insert.
 >   But how do you use your browser now? Shift-Insert again and we're back on.
>The list could go on a bit here, but I guess you'll get the point. If you feel lost sometimes :help might help you a lot.

This sounds like Microsoft explaining to its users on how to user Windows.

Your users aren't newbies to computers. What they need is what key does what exactly. Going to help section after installing your addon and reading pages after pages of functionality for each tool isn't practical for someone who just wants to know what all it can do and how.
:tutor should have explain some of the more advanced features and help should be for everything else.
No one is going to read a book on how to use an add-on? They might, to become an expert in it after they love the addon but not immediately after installing it?

> It's not surprising that the tutorial is not helpful, it's been written by people who know the ins and outs of Tridactyl. They don't know what users might be interested in and some things that are obvious to them aren't actually obvious at all, but it's hard to tell what falls in that category. The only way this will improve is if people send pull requests or mention that they think something should be mentionned in the tutorial.

It is helpful.!  But all of the stuff that is inside the tutorial should be directly mentioned in the features section in shortcut. like Vimium has done.

> > Just about 20% of the features of Vimium.
Well, This might have been incorrect but I just can't spend days worth of time just to read what each and every command/feature can do. Tutor doesn't cover anything, barely even touches the basics.
What all key bindings are there and what all they do should be mentioned directly in the features section. Not everything but all the basic commands/bindings and some intermediate level commands/bindings, Tutor should add onto it and explain it better and Help should be for in-depth explaination.

> It would be more helpful to mention what features Tridactyl is missing compared to Vimium than to simply say Tridactyl only has 20% of the features of Vimium.
I agree on this and I am wrong here, I shouldn't have said it like that. It was a misake on my part. I will try to maybe make a list of what all features that I find in Vimium but not in Tridactyl.

> > Tridactyl breaks sometimes whereas Vimium is smooth and works perfectly everywhere.
Also, I felt sometimes that Tridactyl was atleast 3-4 times slower than vimium when loading pages. probably because of all the bloat from themes and such. I don't know.
but It only happened sometimes, not always.
With Vimium, you don't even feel it being there.

> Could you open issues describing how Tridactyl breaks for you (unless there already are issues open for these breakages)?
Yea, I can do that. Sure.

> > I love what you guys are trying to do by bringing back vimperator and it's awesome [...] This addon shouldn't be able to modify firefox's appearances and have themes and such
> 
> Seems a bit contradictory :^).

Well, I never actually used Vimperator but when I was looking for a few to get vim bindings in firefox, I found sooo many websites claiming it to be the best of the best and what not and almost all of them missing it. so I felt like it must have been something special.
Guessing from your contradictory comment. If it did have themes and ff's Visual appearance hacks then It might have been added once they were all done making Vimperator's core functionalities.
I mean, putting all those things inside an addon sounds more like an Emacs isn't it and also seems contradictory to VIM's ideology of being a Modal editor and doing one thing and doing it right. isn't it?

Just my 2 cents. :) Thanks for replying to my post and also for taking my criticism positively.
Really appreciate the fact that you are not trying to bash me over the head for my criticism. :))
Still, I seriously love, respect and appreciate what all you guys are trying to do. :))

**Comment by bovine3dom** [comment]
It's very simple to add to or edit the tutorial - it's just markdown: https://github.com/tridactyl/tridactyl/tree/master/src/static/clippy - I think it already covers most of the most common binds and commands. If you think there is something missing (e.g. fillcmdline? The find mode?) please make a PR or a separate issue. There are roughly 250 binds in Tridactyl, not including binds common to multiple modes, so we clearly can't mention them all in the tutorial - your help in choosing which should be included would be appreciated.

The description from the Firefox page you quoted was written by a one-off contributor (in docs/amo.md). If you have any concrete suggestions about it, please open a PR or at least an issue so that your suggestions don't get lost.

As for adding features versus fixing bugs: making new features is usually more fun than fixing bugs. Users who are frustrated by bugs are very welcome to fix them and we will happily help them to do so.

**Comment by LucKy-4U** [comment]
Well, I completely agree with you that making new features is much more fun but those features shouldn't be all clubbed together in a single addon because not all features are used by everyone.
I will give you an example of Pico, the developer of TreeStyleTab.
He has written 3-4 add-ons on top of treestyletab to add additional functionality to treestyletab but won't add anything of the like to treestyletab because he feels it is additional functionality and shouldn't be included in the core functionality.
Hell, I and many others tried sooo hard to get him to add a functionality to make treestyletab show tabs in the top-down order with the Newest tabs on top but he just wouldn't do it.
He says there should be a separate addon which should do that to add onto treestyletab's existing functionality because he claims it isn't core functionality of treestyletab.
I mean, really? an addon that sorts out tabs from bottom to top doesn't have sorting out tabs from top to bottom as its core functionality?
He won't even accept donation to add that functionality.
But I respect the fact that he doesn't want to bloat treestyletab even tiny bit and give him all probs for it. Great guy.

By telling you all this, I am just trying to say that the Core functionality is why people install a particular addon and it shouldn't be compromised by additional features.
That's all. But you guys are doing a terrific job and the addon is amazing.
all credit to you guys, everyone is able to get vimperator functionality. so it's awesome. :) Kudos to you all. :)) Cheers.

**Comment by LucKy-4U** [comment]
I am just trying to give you guys some positive criticism, to help you guys better the addon.
If any of my comments seem like negative criticism and is not helpful. I would much rather delete all my comments and not say anything rather than say anything negative or bashful.
I mean, I don't have any right to say anything negative in the first place considering the fact that you guys are doing sooo much hardwork for free.
so I sincerely apologize if any of my comments seem negative.
Please let me know whether I should leave them on or delete them.
Thank You for everything you guys are doing. It certainly means a lot that there are some good people doing good things in this world. :))

**Comment by bovine3dom** [comment]
As I said above, your feedback is appreciated but it would be more useful if it was in separate pull requests or issues so that it didn't get lost.

When I'm in the mood to fix something with Tridactyl I usually pick an issue at random, so it is helpful if that issue is self contained and succinct (e.g. "Improve text on Mozilla addons page" with some concrete examples and another separate issue for "Cover more features in tutorial" with a list of features to be covered). If your feedback remains solely in a closed issue about "tabopen" I can almost guarantee I will forget about it :)

**Comment by LucKy-4U** [comment]
haha

> As I said above, your feedback is appreciated but it would be more useful if it was in separate pull requests or issues so that it didn't get lost.
> 
> When I'm in the mood to fix something with Tridactyl I usually pick an issue at random, so it is helpful if that issue is self contained and succinct (e.g. "Improve text on Mozilla addons page" with some concrete examples and another separate issue for "Cover more features in tutorial" with a list of features to be covered).

ok, sure, I can do that. :))

>If your feedback remains solely in a closed issue about "tabopen" I can almost guarantee I will forget about it :)
hahaha, well, may I ask you something?
does your name bovine3dom actually mean bovinefreedom? I mean, does 3 stand for free? :))
I was just curious. :))

**Comment by bovine3dom** [comment]
Yes, it does stand for free. I needed a nickname and I had just seen a funny Flash animation - https://www.youtube.com/watch?v=FQMbXvn2RNI - I didn't think I would still be using it ~15 years later.

**Comment by LucKy-4U** [comment]
> Yes, it does stand for free. I needed a nickname and I had just seen a funny Flash animation - https://www.youtube.com/watch?v=FQMbXvn2RNI - I didn't think I would still be using it ~15 years later.

hahaha, awesome video. :))
its a nice name. :) dual meaning as well. 3 could stand for the shape of heart as well. so love. :)
bovine love or bovine freedom. :))
