### ISSUE TITLE
open/tabopen completion should show more candidates

### ISSUE THREAD

**Issue by mozbugbox** [tridactyl/tridactyl#2159]
The number of candidates shown in `open/tabopen` is hardwired to `10` in `completions/History.ts`. even if the `historyresults` was set to 20, 50, 200, 500...

This value should really be configurable by user. At least it should be set to something that is much larger than the 10 currently set. 

Since the current history priority filter was kinda very much simplistic, we need more options to choose from. Besides, just showing 50 to 200 pure html table rows from data that were already created should not be any  performance bottleneck.

**Comment by bovine3dom** [comment]
Dead simple - change the 10 here to config.get("historyresults") https://github.com/tridactyl/tridactyl/blob/ae403758f57b7a44258d7c52397a116a4353e686/src/completions/History.ts#L81 - or perhaps we need a new setting?

**Comment by user753** [comment]
@bovine3dom I think they should be the same. I opened a pull request
