### ISSUE TITLE
guiset auto show zone not working

### ISSUE THREAD

**Issue by zeorin** [tridactyl/tridactyl#2160]
*   Brief description of the problem:

After running `guiset gui none`, the GUI is hidden. In the past, when one hovered close to the top of the screen, the address bar would come back into view. This no longer works.

**Comment by bovine3dom** [comment]
Yeah, I noticed this a while ago. I've started using Ctrl-L to bring it up when I need it.

If you care a lot about it, I'd suggest looking around or asking on http://old.reddit.com/r/FirefoxCSS. If you find a fix please let us know and we can fix guiset :)

**Comment by zeorin** [comment]
I've switched to using `hide_tabs_toolbars` and `autohide_toolbox` userChrome adjustments from MrOtherGuy/firefox-csshacks.
