### ISSUE TITLE
Unable to move keyboard cursor in text fields/forms

### ISSUE THREAD

**Issue by Noexpert** [tridactyl/tridactyl#2163]
Hi,

I'm experiencing a strange issue when Tridactyl is activated. At random times, the typing cursor gets "stuck" on a line and cannot move.

The only way to resolve it is by using the mouse to click somewhere on the text form.
This happens when composing emails in Gmail and other websites.

I deactivated Tridactyl and the issue did not occur.
Can anyone else replicate this?

Thanks

**Comment by bovine3dom** [comment]
I personally haven't ever come across this. Do you have a link to a site where it happens regularly?

**Comment by Noexpert** [comment]
Gmail would be the one I see it most regularly.
I've seen it on a handful of other sites as well.

I should add that I'm on version 1.17.1.

**Comment by Noexpert** [comment]
Closing this for now.
I'll do more investigation at my end.
