### ISSUE TITLE
how should update to 1.18.0 [Help]

### ISSUE THREAD

**Issue by Monirzadeh** [tridactyl/tridactyl#2167]
for a long time version 1.18.0 not release.
i try beta version but its is version 1.17.1pre3532-f1725eb
how should i install 1.18.0?

**Comment by bovine3dom** [comment]
1.18.0 hasn't been released. Your version is quite recent.

Our versioning system is a bit mad. 1.17.1prexxxx will eventually become 1.18.0 when it is released.
