### ISSUE TITLE
Tridactyl's scripts are too large to be signed by Mozilla

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#2172]
Output from signing:

```
File is too large to parse.

Error: This file is not binary and is too large to parse. Files larger than 4MB will not be parsed. If your JavaScript file has a large list, consider removing the list and loading it as a separate JSON file instead.
content.js

File is too large to parse.

Error: This file is not binary and is too large to parse. Files larger than 4MB will not be parsed. If your JavaScript file has a large list, consider removing the list and loading it as a separate JSON file instead.
background.js
```

Looks like c776f722944714eef77a8dc3dd82d0e813befdab was the last commit to work.

@glacambre did you b64 some images a while ago? Could that be the source of the bulk of the bloat?

**Comment by glacambre** [comment]
I did in 1984a66fb98a0d5874b09be81b95ddddb2ede8df, which embeds base64 in CSS, so nothing to do with the issue at hand.

I think the easiest change we could make is to remove the custom typescript compiler pass. I won't be able to work on that before Saturday but I can make it my priority of the weekend.

**Comment by bovine3dom** [comment]
Thanks. There isn't much of a rush here - I listed it as P1 because it blocks all releases, but because we don't have anything we need to release urgently it doesn't matter all that much.

I'll look at minification and tree shaking today to see how far we can get. I'll also add a CI test for filesize so we don't get caught out again.

**Comment by bovine3dom** [comment]
@glacambre we now have 3.5MB more headroom so no need to mess with your compiler pass :)
