### ISSUE TITLE
urlmodify in new tab?

### ISSUE THREAD

**Issue by kroyagis** [tridactyl/tridactyl#2184]
Is there currently a way to do `urlmodify` but open in new tab?

**Comment by bovine3dom** [comment]
Best bet would be to refactor this https://github.com/tridactyl/tridactyl/blob/fe39c3e43adfe9cef9bc225c9db16aba3586af7c/src/excmds.ts#L1749 into a separate function so it can be piped into tabopen. Would be very easy to do :)

Alternatively you could do `:alias taburlmodify composite tabduplicate; urlmodify` then e.g. `:taburlmodify -t www. old.` which should work unless I've forgotten how aliases work.

**Comment by kroyagis** [comment]
thanks @bovine3dom for your quick response!
The alias you mentioned does not work; it opens the modified url in the original tab after duplicating it.
I'm interested in working on this issue, but I'm not very experienced with typescript. I'd appreciate it if you could provide me some guidance. 😄

**Comment by glacambre** [comment]
`composite tabduplicate ; urlmodify` should work once https://github.com/tridactyl/tridactyl/pull/2187 is merged :)

**Comment by bovine3dom** [comment]
It looks like your optimism was misplaced glacambre - after #2187 yours still changes the original tab.

`composite tabduplicate; buffer #; urlmodify -t www. old.` does work OK albeit looking a little janky :)

**Comment by bovine3dom** [comment]
In the latest betas:

```
composite urlmodify_js -t www. old. | tabopen
```
