### ISSUE TITLE
Refactor source/source_quiet

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#2185]
Tridactyl version: 1.17.1pre3532-f1725eb
Firefox version: Mozilla Firefox 73.0
Operating system: linux

I think we can remove the duplicate logic in source and source_quiet by using an approach similar to what we do with guiset and guiset_quiet:

https://github.com/tridactyl/tridactyl/blob/27572a59149ed7a3d423a531c1af664d82d20c1c/src/excmds.ts#L751-L769

**Comment by Dranaxel** [comment]
Will try to work on it, but to clarify : you want to create a a reusable function working for the arguments check in source/sourcequiet ?
Also, as I don't use this function, what does RC means ?

**Comment by glacambre** [comment]
Thanks for contributing to Tridactyl! :)

I think we could just have `source_quiet` call `source` and catch any error that it throws.

>Also, as I don't use this function, what does RC means ?

RC is a module that is imported here :

https://github.com/tridactyl/tridactyl/blob/9d7b1107cd67abf98a5659a6f36c2cb5c4e14588/src/excmds.ts#L161

It contains every symbol exported in [config_rc.ts](https://github.com/tridactyl/tridactyl/blob/master/src/background/config_rc.ts).

**Comment by bovine3dom** [comment]
I don't know the answer to your first question.

For the second question: "RC" stands for "run commands". It's a file of commands that a programme runs, usually at start up, usually used as a way to store configuration. We have an example in this repository: .tridactylrc in the root directory.

**Comment by bovine3dom** [comment]
Fixed in ##2484
