### ISSUE TITLE
Refactor tabclosealltoright/left

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#2186]
Tridactyl version: 1.17.1pre3532-f1725eb
Firefox version: Mozilla Firefox 73.0
Operating system: linux

These two functions are almost identical, it should be trivial to avoid duplication here: https://github.com/tridactyl/tridactyl/blob/27572a59149ed7a3d423a531c1af664d82d20c1c/src/excmds.ts#L2242-L2266

**Comment by Dranaxel** [comment]
Will try to work on this issue, made a first pull request but not compliant with CI.

**Comment by bovine3dom** [comment]
The end to end tests are broken so only worry about the other three :)

**Comment by bovine3dom** [comment]
Fixed in #2409. Thanks Dranaxel!
