### ISSUE TITLE
userChrome.css is not written or created

### ISSUE THREAD

**Issue by oknozor** [tridactyl/tridactyl#2210]
Tridactyl version: 1.17.1pre3304-7dcf183
Firefox version: Mozilla Firefox 74.0
Operating system: linux

- [tridactyl config dump](https://gist.github.com/oknozor/a2278dd1ef7414c2a493ceae29d5c016)

After installing tridactyl, I tried to use the `guiset` command. 

Ex : `:guiset tabs none`

I get a message telling me that changes were successfully written to `userChrome.css`.

After running the `guiset` command and restarting firefox, there is still no `chrome/userChrome.css` file in my `profile_dir` or anywhere on my machine. Running `sudo find / -name userChrome.css` returns nothing.

I tried to manually create the file `chrome/userChrome.css` under my `profile_dir` and use the `guiset` command again. Nothing was written to userChrome.css (even if the command respond with a success message). 

I this related to my firefox version ? Or did I miss something during tridactyl installation/configuration ?

**Comment by glacambre** [comment]
Hi, thanks for opening this issue. Could you tell us what `:native` prints? What about `js tri.native.getProfileDir().then(alert).catch(alert)`?

**Comment by oknozor** [comment]
- `:native` 
```
# Native messenger not found. Please run `:installnative` and follow the instructions. 
```
- `:js tri.native.getProfileDir().then(alert).catch(alert)`
```
$HOME/.config/tridactyl/
```

**Comment by glacambre** [comment]
Thanks. `:guiset` requires access to your filesystem in order to be able to write to `userChrome.css`, so you'll need to install the native messenger with `:installnative`. Once this is done, I would recommend also running `:unset profiledir`, to let tridactyl try to figure out what your profile directory is (`profiledir` is supposed to point to your Firefox profile, not your tridactyl configuration directory).

**Comment by oknozor** [comment]
It worked, thank you!

**Comment by glacambre** [comment]
Reopening because `:guiset` shouldn't tell you that it wrote to `userChrome.css` if it wasn't able to do so :).

**Comment by MyGitUsername** [comment]
I'll try to resolve this bug as a first issue.  I'm think I'll just set up a debian 10 VM so that I don't have to remove native messenger on local machine in order to reproduce and test it.

**Comment by glacambre** [comment]
Great, thanks for doing this! I think you'll mostly have to work with [excmds.ts](https://github.com/tridactyl/tridactyl/blob/9b13a0751ae0e43775b79451bc7e39a438a69b39/src/excmds.ts#L430) - what's missing in `:guiset` is that we don't check the return value of `guiset_quiet`.

**Comment by bovine3dom** [comment]
@MyGitUsername make sure you build with `scripts/build.sh --no-native` rather than `yarn run build` or we will helpfully install the native messenger for you : )

**Comment by MyGitUsername** [comment]
Great, thanks - this is good to know.
