### ISSUE TITLE
Reopen tab in FF 74 goes back in history

### ISSUE THREAD

**Issue by SammysHP** [tridactyl/tridactyl#2228]
Tridactyl version: 1.17.1pre3663-ba00bd4
Firefox version: Mozilla Firefox 74.0
Operating system: linux

### Brief description of the problem:

If a tab is closed directly after navigation and reopened afterwards, it will show the previous page.

### Steps to reproduce:

1. Open new tab, e.g. search for `ASDF`
1. Click on a link, e.g. the first search result
1. Wait until the page is loaded, then immediately close the tab (<kbd>Ctrl</kbd>+<kbd>W</kbd> or <kbd>d</kbd>)
1. Reopen the tab with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd>

The bug started to appear with Firefox 74. Might be related to this Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1612800

**Comment by bovine3dom** [comment]
Perhaps related to #2213

**Comment by bovine3dom** [comment]
I can't reproduce this, are you still seeing it?

**Comment by SammysHP** [comment]
No, doesn't happen anymore.
