### ISSUE TITLE
Commands not saved in commandline history

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#2236]
Tridactyl version: REPLACE_ME_WITH_THE_VERSION_USING_SED (1.17.1pre3666-2f02f3e)
Firefox version: Mozilla Firefox 74.0
Operating system: linux

I could have sworn we already had an issue for this but I couldn't find it. Tridactyl doesn't save my commands when I run `composite hint -qpipe a href | js -p JS_ARG.join(" ") | ! mpv`. My storageloc is default (`sync`). I'm not sure what else could be important for this.

**Comment by MoSal** [comment]
`git bisect` points fingers at 4497ec34429502b6e70fd69539f2d8c58e3f6ab8. Reverting that commit alone seem to fix this issue.

@bovine3dom

**Comment by bovine3dom** [comment]
Huh, it's nice that that fixed something. I haven't checked the duplicate tab issue. If reversion didn't fix it I'll unrevert it.

**Comment by bovine3dom** [comment]
I'm still seeing this in the wild (but not on fresh profiles).

**Comment by m2habert** [comment]
tridactyl: Version 1.19.0
ffx: 76.0.1
Mac 10.11.6

My command history stopped working some days ago.

Right now it is stuck in a single input, no matter which "tabopen"  (90% of my activity) I type.

It was working great till this week, with the only caveat that it would get cleared whenever a FFx restart happened. 

I've been trying to stay "late" with the ffx upgrades (in order to avoid major breakages), so the problem started while I was on FFx 15.0. (16 was released may 5th). 

I did upgrade to 16 in a vain possibility that tridactyl 1.19 would work better with it, but to no avail.

**Comment by glacambre** [comment]
On 2020-05-24 21:15, m2habert wrote:
> It was working great till this week, with the only caveat that it would 
> get cleared whenever a FFx restart happened.

Do you have a tridactylrc and are your using `:sanitize` in it? If yes, 
this might be the reason why your commandline history is wiped on every 
restart.

**Comment by m2habert** [comment]
Yep, I'm using 
`:sanitise tridactyllocal tridactylsync`

**Comment by bovine3dom** [comment]
On a real profile (not tested on temporary):

1. Open web console on a Tridactyl extension page (e.g. the new tab) and detach the console to a different window
2. run `tri.State.getAsync("cmdHistory").then(c => {tri.state.cmdHistory = c.concat(["test"])});` and then, a few seconds later run `tri.l(tri.State.getAsync("cmdHistory"))` and observe that "test" has indeed been added to the end
3. Change to a normal tab, press j/k a few times and wait a little bit
4. Run `tri.l(tri.State.getAsync("cmdHistory"))` in the detached console and observe that "test" has disappeared.

So, somehow it's being clobbered. Probably the same issue as #2407.

**Comment by bovine3dom** [comment]
I'm not sure if 9e750f6 fixed all these bugs but it definitely fixed some of them. I'll check on a real profile once it lands in the betas.

**Comment by m2habert** [comment]
Indeed, @bovine3dom  : 
![image](https://user-images.githubusercontent.com/7454005/83262633-b5c3e480-a193-11ea-8961-f5d0d470b674.png)



> On a real profile (not tested on temporary):
> 
>     1. Open web console on a Tridactyl extension page (e.g. the new tab) and detach the console to a different window
> 
>     2. run `tri.State.getAsync("cmdHistory").then(c => {tri.state.cmdHistory = c.concat(["test"])});` and then, a few seconds later run `tri.l(tri.State.getAsync("cmdHistory"))` and observe that "test" has indeed been added to the end
> 
>     3. Change to a normal tab, press j/k a few times and wait a little bit
> 
>     4. Run `tri.l(tri.State.getAsync("cmdHistory"))` in the detached console and observe that "test" has disappeared.
> 
> 
> So, somehow it's being clobbered. Probably the same issue as #2407.

**Comment by bovine3dom** [comment]
@m2habert are you using Tridactyl beta? I am 90% sure I fixed this. Otherwise you'll have to wait for 1.19.1 to be released on stable.

**Comment by m2habert** [comment]
I've just migrated to beta: 

Cmd hist appears to be working nicely and properly.

Thkx, @bovine3dom
