### ISSUE TITLE
Stable version number contains git commit and hash

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#2262]
Somehow TRI_VERSION isn't replaced in the built content.js.

If I run `scripts/git_version.sh` manually after the build has completed it is correctly written. I suppose we must have a race condition somewhere.

Edit: handy snippet for checking: ` grep -Eo ".{0,5}TRI_VERSION.{0,20}" build/*.js`

**Comment by bovine3dom** [comment]
Potentially related - stable versions always appear like `1.19.0pre3821-f4fa5b8` rather than `1.19.0-1.19.0` like they used to.

**Comment by glacambre** [comment]
This is fixed on both beta and stable now.

**Comment by bovine3dom** [comment]
I think stable versions still have git hash version strings.

I don't remember doing anything to fix this either, unless it was the webpack.config.js being set to production that was causing the issue?

**Comment by bovine3dom** [comment]
We could swap to using `browser.management.getSelf()` which has a `version` field: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/management/ExtensionInfo
