### ISSUE TITLE
List of default keybindings ?

### ISSUE THREAD

**Issue by qoxxxx** [tridactyl/tridactyl#228]
Is there one ?
There is a link from `:help` page that brings me to `.../static/docs/modules/_parsers_normalmode_.html#defaultnmaps`
Am I supposed to find them here ? Because I don't.

**Comment by bovine3dom** [comment]
The link's broken, it should direct you to config.ts.

**Comment by qoxxxx** [comment]
Indeed, thanks.
Feel free to close if already taken care of.

**Comment by gsbabil** [comment]
@bovine3dom 

Please ignore the cross-reference from #229 above. #228 and #229 are
unrelated. Thank you.

**Comment by schemar** [comment]
Link moved to https://github.com/tridactyl/tridactyl/blob/master/src/lib/config.ts

**Comment by bovine3dom** [comment]
I thought we linked to the right place. I'll look into it. Thanks.

**Comment by glacambre** [comment]
>I thought we linked to the right place.

I updated the in-addon links after saulrh's PR but forgot about the github ones. We should probably also `find . -type f -exec sed 's@github.com/cmcaine/tridactyl@github.com/tridactyl/tridactyl' -i '{}' ';'` while we're at it, I think we missed a few links in the markdown files.
Maybe also create a list of things to do when files are being moved around, although I doubt we'll remember it exists next time we need it.

**Comment by schemar** [comment]
Whoops sorry didn't mean for this to blow up 😅 
It is just that the first link I found was in this issue (above) and that one is outdated.

**Comment by jhinkoo331** [comment]
> 
> 
> The link's broken, it should direct you to config.ts:
> 
> https://github.com/cmcaine/tridactyl/blob/master/src/config.ts#L23

The link is broken now.. need help!!

**Comment by glacambre** [comment]
@jhinkoo331 The new link is here: https://github.com/tridactyl/tridactyl/blob/master/src/lib/config.ts#L184 . You should also be able to use `:viewconfig --default` to get a look at the default settings, although it seems to be broken for me at the moment.
