### ISSUE TITLE
Tridactlyl needs release and/or FF 75 support

### ISSUE THREAD

**Issue by alerque** [tridactyl/tridactyl#2297]
Tridactyl version: 1.17.1pre3304-7dcf183e
Firefox version: Mozilla Firefox 75.0

Surely something in the 459 commits since the last release merits a new tag! I just got bumped by Arch Linux to FF 75 and there are quite a few things that don't seem to be working right. For example the <kbd>Tab</kbd> key doesn't function while Tridactyl menus are open as it used to. I'm wondering if this is something that might have been long since been fixed but since none of the developers use the stable releases they didn't realize became such a blocker.

**Comment by bovine3dom** [comment]
I've been holding off a release for a while as there keep being bugs reported in the beta, e.g. #2291. I'll look at FF75 today - we haven't tried to fix Tab on purpose so it'll probably be broken in the beta too.

**Comment by alerque** [comment]
Okay thanks for the information. The Tab thing is weird. After a couple restarts it seemed to be working, but it starts failing after a little while. I can't make out what the trigger cause is.

**Comment by bovine3dom** [comment]
1.18.0 is released : ) https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/versions/

Please open an issue for `Tab` if it persists.
