### ISSUE TITLE
:help

### ISSUE THREAD

**Issue by cmcaine** [tridactyl/tridactyl#23]
We want documentation generated from the source code and runtime data (maps, current values of settings (once we have them), etc).

Basic use `:h :scrollline` --> an anchor in a helpfile like vim, content is from the function signature and doccomment in excmds.ts.

Better: 

 - `:h :scrollline` also shows all the maps that currently eventually map to it, and source code in an expando or something (like the Julia and Rust API documentation)
 - `:h scrollline` knows to show :scrollline if there isn't a map `scrollline`.
 - `:h` shows some useful index page (support for non-generated docs)
 - `:h <some complicated map` gives a generated help page which shows how the map expands.

First line of doccomment should be suitable for autocompletion help (e.g. :win shows :windo, :winclose, etc all with a one line description of what they do).

**Comment by P4Cu** [comment]
Is there something like python someFunction.__doc__ ? Or we have to parse it ourselves?
Maybe a decorator pattern would be nice here? (type script could do that)

**Comment by cmcaine** [comment]
Typescript will only do decorators on class methods and parameters, unfortunately.

There's a tool called `typedoc` that does a reasonable job. We could hack on that or it's output.

**Comment by bovine3dom** [comment]
I've started fiddling with this in the docs branch: https://github.com/cmcaine/tridactyl/tree/docs

**Comment by bovine3dom** [comment]
We can hide functions from typedoc with `/** @hidden */`.

**Comment by bovine3dom** [comment]
I've just merged this into master. It makes `sed` into a dependency.

Todo:

- [ ] make a TypeDoc theme that hides most of the things we don't want (return info, key at bottom of page, drop shadows, header page, etc)
- [ ] fix or remove the search box at the top of help
- [ ] write documentation for existing functions
- [ ] remove sed dependency by adding content script to theme

**Comment by cmcaine** [comment]
I wrote documentation for more of the functions, added links, injected our CSS and JS into every .html file in the docs folder.

**Comment by bovine3dom** [comment]
@glacambre has done most of this.

My dream is for the help page to look more like Vimperators'. Some day I'll spend some time doing that.

**Comment by bovine3dom** [comment]
I think it's probably good enough that we can close this issue.
