### ISSUE TITLE
Is there a way to disable searchurls functionality?

### ISSUE THREAD

**Issue by eeshugerman** [tridactyl/tridactyl#2306]
Is there a way to completely disable the `searchurls` functionality? When I do `:open google maps docs`, I want to do a Google search for "google maps docs". And when I do `:open github api rate limits`... same thing.

I am aware of `:search` / <kbd>s</kbd>, but I never remember to use it when I need it.

I've tried `:set searchurls {}`, but it seems this just appends to the default object rather than replacing it.

Thanks!

**Comment by glacambre** [comment]
You can use `:setnull searchurls.github` to kill the github searchurl.

Maybe we should remove all searchurls that are words/names.

**Comment by bovine3dom** [comment]
We need to improve the docs for `setnull`, I couldn't find it even though I half remembered writing it.

I assume that most people like searchurls as they rarely complain and they were in Vimperator. Perhaps we could remove some of them?

**Comment by eeshugerman** [comment]
Thanks for the tip!

I thought I'd try to programmatically set all `searchurls` null, so I went to the [exemplar rc files page](https://github.com/tridactyl/tridactyl/wiki/Exemplar-.tridactylrc-files) for some inspiration (I knew JS could be used for this kind of thing, but wasn't sure how exactly), and I came across this in @glacambre's:
```
jsb Object.keys(tri.config.get("searchurls")).forEach(u => tri.config.set("searchurls", u, null))
```
lmao. but... it doesn't seem to work for me? Has an update broken this?

As for documentation/removal, I'd say just adding a `setnull` example to the `searchurls` entry would be sufficient.

**Comment by glacambre** [comment]
Try this instead:
```
jsb Object.keys(tri.config.get("searchurls")).reduce((prev, u) => prev.then(_ => tri.config.set("searchurls", u, null)), Promise.resolve())
```
The snippet you quoted used to work a long time ago but now it doesn't, probably because of race conditions.

**Comment by eeshugerman** [comment]
That works, thanks!
