### ISSUE TITLE
Can't disable autocmd after setting in rc

### ISSUE THREAD

**Issue by hejops** [tridactyl/tridactyl#2314]
Tridactyl version: 1.17.1pre3766-ac33cbd
Firefox version: Mozilla Firefox 75.0
Operating system: linux

*   Brief description of the problem:
I tried writing an autocmd (see below) for YouTube pages in my rc file, but ran into an infinite loop, so I commented the autocmd out. When I re-source, however, the autocmd remains active.

*   Steps to reproduce:
1. Add the autocmd into rc file
2. Source, test out on a relevant url
3. Comment out the autocmd
4. Source and test again
5. autocmd should still be active

*   URL of the website the bug happens on:
Any YouTube channel with the url scheme below, [example](https://www.youtube.com/channel/UC3W-MdiGdX_kNhEVel8POxQ)

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
https://gist.githubusercontent.com/hejops/5e87d3381afc818b48b8c27d94790f8f/raw/fee0e5e9eeeba37ea6ba571e192ce029a9eb2c18/gistfile1.txt

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):
```
" autocmd DocStart ^https://www.youtube.com/channel/UC.{22}$ js tri.excmds.urlmodify("-g", "-1", "videos")
```
(I'll post the full rc file if necessary)

*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:
/home/[username]/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl 

*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:
Â{"cmd": "run", "content": "/home/[username]/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl\n", "code": 0}

**Comment by bovine3dom** [comment]
Commenting out stuff in the RC file won't undo it unless you have `sanitise` at the top, like the example suggests: https://github.com/tridactyl/tridactyl/blob/master/.tridactylrc

Can you confirm you have that line?

**Comment by hejops** [comment]
My bad, I didn't have that line. Everything works as it should now.
