### ISSUE TITLE
Feature request: Speed up bookmark selection

### ISSUE THREAD

**Issue by oredaze** [tridactyl/tridactyl#2315]
Tridactyl version: 1.17.1pre3304-7dcf183
Firefox version: Mozilla Firefox 75.0
Operating system: linux

Let's say I use "bmarks" (it can be "open" too or w/e). It calls the completion menu, I type the name of my bookmark. The name is unique. I press enter and the bookmark loads... Well... no. Currently that takes me to my default search engine. If I want the above functionality I have to press tab first each time. Currently typing a search engine keyword uses my desired functionality, but why not bookmarks?

It doesn't need to be done THIS way, I simply want to exclude pressing an extra key each time cuz efficiency.

Thank you.

**Comment by Sh4d1** [comment]
@bovine3dom any update regarding this request? I'd be happy to help, just not sure where to start!

**Comment by bovine3dom** [comment]
Hi, I think this issue was fixed in d4ebe1b. For me,

`:bmarks abou<CR>` takes me to the Mozilla About Us page as I would expect.

What behaviour do you get?

**Comment by Sh4d1** [comment]
Okay I was more thinking of the keyword of any bookmarks. If you have one, let's say `gh` for Github.com, then when you type `gh<Enter>` in the classic URL bar, sends me directly to the site, whereas it does not work that way in the tridactyl bar.

Maybe it's another feature though, happy to open another issue!

**Comment by oredaze** [comment]
It does work now (albeit only for :bmarks, but that is fine), I forgot to close the issue. Thanks.

**Comment by Sh4d1** [comment]
Created https://github.com/tridactyl/tridactyl/issues/4731 for my feature request then
