### ISSUE TITLE
bug(i18n): UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 311: character maps to <undefined>

### ISSUE THREAD

**Issue by Kristinita** [tridactyl/tridactyl#2323]
### 1. Summary

I can't use [**Cyrillic keyboard layout**](https://github.com/tridactyl/tridactyl/wiki/Internationalisation) for Trydactyl operations. I get traceback in Browser Console.

**#346**, **#790**, **#976** — possible related issues.

### 2. Purpose

I want click to links by hotkeys without switching keyboard layout. For example, I enable Tridactyl → I open [**the front page**](https://kristinita.netlify.app) of my site → I press <kbd>F</kbd> → I can click to links by press specific keys:

![Colemak](https://i.imgur.com/Vv3zNRK.png)

But I can't do it, use Russian keyboard layout. I need switching to my English keyboard layout.

It would be nice, if would be possible use Tridactyl without keyboard layout switching.

### 3. Steps to reproduce

As described [**here**](https://github.com/tridactyl/tridactyl/wiki/Exemplar-.tridactylrc-files), `:nativeinstall` → `:native` → I create `%USERPROFILE%/.config/tridactyl/tridactylrc` with [**this**](https://github.com/tridactyl/tridactyl/wiki/Internationalisation) content → `:restart` → also, I restart Windows.

As described [**here**](https://github.com/tridactyl/tridactyl/blob/master/doc/troubleshooting.md#getting-logging-information), `:set logging.$COMPONENT DEBUG` → I open Browser Console and Web Console → `:source`.

### 4. Current behavior

+ Web Console:

```typescript
controller in excmd:  Error: "Failed to send message to native messenger. If it is correctly installed (run `:native`), please report this bug on https://github.com/tridactyl/tridactyl/issues ." logging.ts:42:32
   log logging.ts:42
   acceptExCmd controller.ts:24
```

+ Browser Console:

```python
Traceback (most recent call last):
  File ".\native_main.py", line 510, in <module>
    reply = handleMessage(message)
  File ".\native_main.py", line 410, in handleMessage
    file_content = getUserConfig()
  File ".\native_main.py", line 123, in getUserConfig
    return open(cfg_file, "r").read()
  File "C:\Python38\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 303: character maps to <undefined>
```

If I remove all content from my `%USERPROFILE%/.config/tridactyl/tridactylrc` file and run `:source` in Tridactyl console, I don't get stack trace.

### 5. Environment

1. Windows 10.0.18363 Pro N for Workstations 64-bit EN
1. Firefox **Portable** ([**from PortableApps**](https://portableapps.com/apps/internet/firefox_portable)) 75.0 64-bit
1. Tridactyl 1.17.1pre3304-7dcf183
1. native 0.1.10
1. Python 3.8.2
1. Keyboard layouts:

    1. [**Colemak**](https://colemak.com/) — EN
    1. [**Standard Russian `ЙЦУКЕН`**](https://en.wikipedia.org/wiki/JCUKEN#PC) — RU

### 6. Configuration

1. [**`:viewconfig`**](https://www.pastery.net/uuzgde/)

    1. `:set profiledir` — `"D:\\PortableApps\\PortableApps\\FirefoxPortable\\Data\\profile"`

1. `%USERPROFILE%/.config/tridactyl/tridactylrc` — same as [**here**](https://github.com/tridactyl/tridactyl/wiki/Internationalisation)

Thanks.

**Comment by bovine3dom** [comment]
Thanks for the detailed report. 

Presumably this would be fixed by https://github.com/tridactyl/tridactyl/pull/896.

In the meantime you could paste the commands from https://github.com/tridactyl/tridactyl/wiki/Internationalisation into a GitHub gist and then run `:source --url [raw link to gist]`. That would avoid using the native messenger.

Please let me know if that works and we can update the wiki : )

**Comment by glacambre** [comment]
Another solution could be to `:set hintchars абвгдеёжзийклмнопрстуфхцчшщъыьэюя`.

**Comment by Kristinita** [comment]
@bovine3dom:

**Status: ❌  Not Fixed for me**

### 1. Steps to reproduce

I created GitLab Snippet — [**its raw**](https://gitlab.com/Kristinita/kiragitlabdebugging/snippets/1970066/raw). In Tridactyl console:

```text
:source --url https://gitlab.com/Kristinita/kiragitlabdebugging/snippets/1970066/raw
```

→ <kbd>Enter</kbd>.

### 2. Current behavior

+ Web Console:

```js
18:53:48.754 lock state was taken without confirmation locks.ts:30:24
18:53:48.766 lock state was taken without confirmation locks.ts:34:46
```

+ Browser Console:

```python
Traceback (most recent call last):
  File ".\native_main.py", line 510, in <module>
    reply = handleMessage(message)
  File ".\native_main.py", line 499, in handleMessage
    reply["files"] = os.listdir(path)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: './--url https://gitlab.com/Kristinita/kiragitlabdebugging/snippets/1970066'
```

### 3. Question

Have you considered making Tridactyl workable by default for any keyboard layout? I switched from Tridactyl to [**Surfingkeys**](https://github.com/brookhong/Surfingkeys): I installed Surfingkeys → this extension worked for my Colemak and Russian keyboard layouts out-of-the-box, without any configuration changes. I think, it more user-friendly behavior for quick start. New users can stop use Tridactyl due to similar keyboard layouts settings and/or problems.

Thanks.

**Comment by bovine3dom** [comment]
I'm glad you're happy with Surfingkeys :) The "built in" vim to edit text fields they have is very cool.

I can't remember why we didn't go for "keyboard agnostic" binds like Surfingkeys. I think we considered it but went for `keymaps` instead. @saulrh might remember better than me. I imagine it might confuse, e.g. our German users (who often use QWERTZ keyboards) when they have to press `zz` instead of `yy` to copy URLs, despite our documentation saying `yy`.

Thanks for this detailed report. It has helped me to uncover 4 unrelated issues, which I think is a record.

**Comment by bovine3dom** [comment]
In Tridactyl `1.23.0pre6655-504f1ecb` + just run `:set keyboardlayoutforce true` to pretend that your keyboard is US QWERTY, which is what I think Surfingkeys does
