### ISSUE TITLE
Tridactyl v1.18.0 broken in Firefox 75

### ISSUE THREAD

**Issue by StormPooper** [tridactyl/tridactyl#2324]
### Brief description of the problem:

Tridactyl is borked after upgrading to 1.18.0.

It shows a white page on the new tab page with the following console errors:

```
TypeError: can't convert null to object config.ts:1075:25
TypeError: can't convert null to object config.ts:1075:25
```
_**Update:** The CSP violations originally in the ticket happen with 1.17.1 so I've removed them, but those `TypeError` instances are only with 1.18.0. They don't show up on other pages, however, which makes me think it is something else._

I have no command bar with `:`, no mode indicator and most other shortcuts don't work (interestingly pressing `v` highlights most of the page though).

Downgrading back to 1.17.1 fixes it, but as soon as I upgrade again it breaks. I've tried it with and without my `tridactylrc` and uninstalling/reinstalling but it bombs out every time. With a fresh instance of the plugin it shows the welcome tutorial briefly, but that shuts as soon as I decide on whether to allow it to be work in Private mode. <kbd>Ctrl</kbd>+<kbd>i</kbd> still opens my local text editor.

### Steps to reproduce:

1. Update Tridactyl

### Tridactyl version (`:version`):

1.18.0 (can't run `:version` to get the exact version).

### Firefox version (Top right menu > Help > About Firefox):

**75.0 (64-bit)**
Mozilla Firefox for Arch Linux
archlinux - 1.0

### URL of the website the bug happens on:

All of them (including new tab).

### Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

Cannot run it to provide

### Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

Tried with and without this:

```
" General Settings
set configversion 1.8
set theme dark
set smoothscroll false
set csp untouched

" Search URLs
set searchurls.google ""
set searchurls.googlelucky ""
set searchurls.scholar ""
set searchurls.googleuk ""
set searchurls.bing ""
set searchurls.duckduckgo ""
set searchurls.yahoo ""
set searchurls.twitter ""
set searchurls.wikipedia ""
set searchurls.youtube ""
set searchurls.amazon ""
set searchurls.amazonuk ""
set searchurls.startpage ""
set searchurls.github ""
set searchurls.searx ""
set searchurls.cnrtl ""
set searchurls.osm ""
set searchurls.mdn ""
set searchurls.gentoo_wiki ""
set searchurls.qwant ""
set searchurls.am https://www.amazon.co.uk/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=%s
set searchurls.b https://www.bing.com/search?q=%s
set searchurls.d https://duckduckgo.com/?q=%s
set searchurls.g https://www.google.co.uk/search?q=%s
set searchurls.w https://en.wikipedia.org/wiki/Special:Search?search=%s
set searchurls.ww https://werewolv.es/Game/Index/%s
set searchurls.abt https://bugs.archlinux.org/index.php?show_task=%s
set searchurls.ab https://bugs.archlinux.org/index.php?project=3&type%5B%5D=&sev%5B%5D=&pri%5B%5D=&due%5B%5D=&reported%5B%5D=&cat%5B%5D=&status%5B%5D=open&percent%5B%5D=&opened=&dev=&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto=&do=index&string=%s
set searchurls.tw https://twitter.com/search?q=%s
set searchurls.af https://bbs.archlinux.org/search.php?action=search&author=&search_in=0&sort_by=0&sort_dir=DESC&show_as=topics&keywords=%s
set searchurls.ap https://www.archlinux.org/packages/?sort=&maintainer=&flagged=&q=%s
set searchurls.aw https://wiki.archlinux.org/index.php?title=Special%3ASearch&profile=default&fulltext=1&search=%s
set searchurls.au https://aur.archlinux.org/packages/?O=0&SeB=nd&outdated=&SB=n&SO=a&PP=50&K=%s
set searchurls.c https://chambers.co.uk/search/?query=test&title=21st&sourceid=Mozilla-search&title=21st&query=%s
set searchurls.yt https://www.youtube.com/results?search_query=%s
set searchurls.gi https://www.google.co.uk/search?tbm=isch&q=%s
set searchurls.f https://addons.mozilla.org/en-GB/firefox/search/?q=%s
set searchurls.gp https://play.google.com/store/search?q=%s
set searchurls.tr https://trakt.tv/search?query=%s
set searchurls.ka https://kitsu.io/anime?text=%s
set searchurls.km https://kitsu.io/manga?text=%s
set searchurls.bgg https://boardgamegeek.com/geeksearch.php?action=search&objecttype=boardgame&q=%s
set searchurls.eb https://www.ebay.co.uk/sch/i.html?_sacat=0&_nkw=%s
set searchurls.gm https://www.google.co.uk/maps?q=%s
set searchurls.s https://www.startpage.com/do/search?language=english&cat=web&query=%s
set searchurls.l https://www.google.co.uk/search?q=%s&btnI
set searchurls.jw https://www.justwatch.com/uk/search?q=%s
set searchurls.bgg https://boardgamegeek.com/geeksearch.php?action=search&objecttype=boardgame&q=%s
set searchurls.n https://www.npmjs.com/search?q=%s
set searchurls.tenor https://tenor.com/search/%s-gifs
set searchurls.wb https://web.archive.org/web/*/%s
set searchurls.gt https://translate.google.com/translate?sl=auto&tl=en&u=%s
set searchurls.tmdb https://www.themoviedb.org/search?query=%s
set searchurls.tvdb https://www.thetvdb.com/search?query=%s

" Binds
bind ;c hint -c [class*="expand"],[class="togg"]
bind yp composite js document.getElementById("clone-help-step-1").textContent.replace("git checkout -b", "git checkout -B").replace("git pull ", "git fetch ") + "git reset --hard " + document.getElementById("clone-help-step-1").textContent.split(" ")[3].replace("-","/") | yank
bind yg composite js "git clone " + document.location.href.replace(/https?:\/\//,"git@").replace("/",":").replace(/$/,".git") | clipboard yank
bind ,g js let uri = document.location.href.replace(/https?:\/\//,"git@").replace("/",":").replace(/$/,".git"); tri.native.run("cd ~/Code; git clone " + uri + "; cd \"$(basename \"" + uri + "\" .git)\"; st")
bind yy clipboard yank
bind ;C composite hint_focus; !s xdotool key Menu
bind gd tabdetach
bind gD composite tabduplicate | tabdetach
bind j scrollline 5
bind k scrollline -5
unbind --mode=ex <C-a>
unbind --mode=ex <C-c>
bind i fillcmdline bmarks
bind I fillcmdline bmarks -t

" Quickmarks
quickmark i https://www.inoreader.com/all_articles
quickmark t https://twitter.com/home
quickmark u https://www.tumblr.com/dashboard
quickmark y https://www.youtube.com/feed/subscriptions
quickmark c https://play.pocketcasts.com/web/podcasts
quickmark m https://mastodon.technology/web/timelines/home
quickmark b https://www.ebay.co.uk/mbf/Summary?MyEbay
quickmark p https://app.getpocket.com/
quickmark k https://kitsu.io/
quickmark d https://dev.azure.com/
quickmark g https://github.com/
quickmark e https://gmail.com/
quickmark a https://amazon.co.uk/
quickmark z https://dev.azure.com/afintechnologies/CoCoMo/_boards/board/t/DevelopmentTeam/Stories

" Subconfig Settings
js tri.config.set("subconfigs", {"twitter.com": {"nmaps":{"j":"","k":"","<Escape>":"","l":"",".":""}},"inoreader.com": {"nmaps":{"j":"","k":"","w":"","r":"","<Escape>":"","y":""}},"reddit.com": {"nmaps":{"gu":"urlparent 4"}},"google(\.[a-zA-Z0-9]+){1,2}/search": {"nmaps":{"f":"hint -Jc #top_nav a, #search a, .card-section a, a.fl, #pnnext, #pnprev","F":"hint -Jbc #top_nav a, #search a, .card-section a, a.fl, #pnnext, #pnprev","gF":"hint -Jqbc #top_nav a, #search a, .card-section a, a.fl, #pnnext, #pnprev"}, "followpagepatterns":{"next":"Next","prev":"Previous"}},"tumblr.com": {"nmaps":{"<Escape>":""}},"tumblr.com/dashboard": {"nmaps":{"j":"","k":"","l":"",".":"","f":"hint -J"}},"youtu((\.be\/.+)|(be\.com\/watch?.+v=.+))": {"nmaps":{"j":"","k":"","l":"","f":"","<Space>":"","N":"","P":"","i":""}},"dev.azure.com": {"nmaps":{"/":"","<ForwardSlash>":"","<C-f>":"","<C-i>":"","<Escape>":""}},"mail.google.com":{"nmaps":{"<Escape>":""}},"play.pocketcasts.com":{"nmaps":{"<Escape>":"","s":"","h":"","u":"","U":"undo"}},"discordapp.com":{"nmaps":{"<Escape>":""}}})

" Misc commands
command wayback composite get_current_url | tabopen wb
command translate composite get_current_url | tabopen gt

" Turn off tridactyl for these sites
blacklistadd discordapp.com/channels/
blacklistadd app.slack.com/client/

" Replace URLs
autocmd DocStart ^http(s?)://www.reddit.com js tri.excmds.urlmodify("-t", "www", "old")
autocmd DocStart ^http(s?)://registry.hub.docker.com/u/ js tri.excmds.urlmodify("-t", "/u/" "/r/")

" vim: set filetype=vim:
```
(Side note, if anyone knows a better way of adding the "subconfigs" to the rc file that'd be appreciated).

**Comment by bovine3dom** [comment]
The null thing could be fixed presumably with a guard here: https://github.com/tridactyl/tridactyl/blob/14501f71d5ab63f71c6697702efe9721f250c565/src/lib/config.ts#L1075

In your config the lines `set searchurls[...] ""` look dodgy (but shouldn't break anything). Could you swap them for `setnull searchurls.[...]`?

**Comment by StormPooper** [comment]
> In your config the lines set searchurls[...] "" look dodgy (but shouldn't break anything). Could you swap them for setnull searchurls.[...]?

Done, much cleaner, but didn't make a difference. I did manage to get it to update successfully once whilst testing, but after quitting Firefox it broke again and I haven't been able to reproduce that again (after many attempts).

**Comment by bovine3dom** [comment]
Could you try switching to the beta build (available here: https://tridactyl.cmcaine.co.uk/betas/tridactyl-latest.xpi)? Make sure you disable Tridactyl "stable" first.

I'll put out a potential fix in the betas tomorrow. Hopefully you can then tell me if that fixes it.

**Comment by StormPooper** [comment]
Just updated to the beta (`1.18.0pre3771-f0ec742`) and it's working for me now - I did have to update my unbinds to use `null` instead of `""` as per your suggestion for the search URLs, but otherwise it's working correctly at the moment.

**Comment by bovine3dom** [comment]
That's annoying - I didn't do anything to fix it. There must be something lurking in your config in the stable version that is tripping up our (buggy) code.

**Comment by StormPooper** [comment]
Let me know if you want me to try anything else, otherwise I'll wait for the next release and see if it makes a difference.

**Comment by bovine3dom** [comment]
I've just released beta 976377a. If you could update to that (about:addons, click the cog, click check for updates, wait a little bit, restart Firefox) and let me know if it's broken anything, that'd be grand.

With luck I won't have introduced any new issues and I'll put 1.18.1 out this evening.

**Comment by StormPooper** [comment]
Updated (`1.18.0pre3772-976377a`) and it seems fine, though I have just noticed that none of my unbinds are working for Tumblr, but are working for Inoreader and Twitter.

**Comment by bovine3dom** [comment]
I've just released 1.18.1 as a stable release. Could you try it out? https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/versions/

The binds not working on Tumblr is probably #2001 - we don't read RC files very reliably at the moment.

**Comment by StormPooper** [comment]
Yup, that's working now (`1.18.1pre3774-7fe4b6d`), thanks for your help.

The binds on Tumblr are in my config, they just don't work for some reason. I've also tried reseturl and then unbindurl again, but no difference.

**Comment by bovine3dom** [comment]
Hooray!

Could you open a new issue with more detail on the Tumblr stuff? Thanks.
