### ISSUE TITLE
Tridactyl has a high energy impact

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#2329]
Tridactyl version: REPLACE_ME_WITH_THE_VERSION_USING_SED (1.17.1pre3767-ec13746)
Firefox version: Mozilla Firefox 75.0
Operating system: linux

No idea how to reproduce. Might be caused by an update being available but not being applied
![screenshot_2020-04-26-08:07:30](https://user-images.githubusercontent.com/11534587/80299540-80dc0080-8795-11ea-9f88-f4aadc785279.png)
?

**Comment by glacambre** [comment]
The issue comes from locks.ts:lockhandler. Tridactyl cools done when placing a breakpoint on `await new Promise(resolve => setTimeout(resolve, 100)`.

**Comment by glacambre** [comment]
State on the breakpoint:
```
msg = { type: "lock", command: "acquire", args: ["state", 1587747691279.847, "d5e52b60-8646-11ea-8df3-f3878f2ee66f"] }
sender = "state"
ID = "4fcc9880-8450-11ea-80cb-8b7f8ef3ca52"
OWNED_LOCKS = { size: 0 }
DESIRED_LOCKS = { state = 1587529106840.473 }
```
Continue until next breakpoint:
```
msg = { type: "lock", command: "acquire", args: ["state", 1587832024717.4333, "5f55d020-870f-11ea-942d-3d4227efc621"] }
sender = "state"
ID = "4fcc9880-8450-11ea-80cb-8b7f8ef3ca52"
OWNED_LOCKS = { size: 0 }
DESIRED_LOCKS = { state = 1587529106840.473 }
```
Continue until next breakpoint:
```
msg = { type: "lock", command: "acquire", args: ["state", 1587798851076.1401, "91041510-86c3-11ea-a035-23c17530e046"] }
sender = "state"
ID = "4fcc9880-8450-11ea-80cb-8b7f8ef3ca52"
OWNED_LOCKS = { size: 0 }
DESIRED_LOCKS = { state = 1587529106840.473 }
```
Continue until next breakpoint:
```
msg = { type: "lock", command: "acquire", args: ["state", 1687787261062.8918, "49a708e0-86a9-11ea-ac65-8967a3cc7ac2"] }
sender = "state"
ID = "4fcc9880-8450-11ea-80cb-8b7f8ef3ca52"
OWNED_LOCKS = { size: 0 }
DESIRED_LOCKS = { state = 1587529106840.473 }
```

Removing the breakpoint and resuming execution results in Tridactyl fighting for state again.

**Comment by bovine3dom** [comment]
Perhaps we should give up on locks and implement #2208 instead?

**Comment by glacambre** [comment]
Giving up on locks sounds like a good idea to me. I don't know if moving 
state to the background is a good idea though (but I'm not opposed to 
it). Wasn't a centralized background script what Tridactyl had before? 
Why did we try to move parts of it to the content script?

**Comment by bovine3dom** [comment]
I think you're confusing two things. Saulrh moved lots of stuff that should be tab local out of the global state (e.g. mode, so one tab in ignore mode didn't infect the rest).

I'm suggesting we change the synchronisation strategy for global state from this current egalitarian thing where all the content and background scripts negotiate with each other, to one where the background script is in charge and all the content scripts tell it changes and ask it for the state of the state every time. I reckon we update the state much more often than we need to read the state so it should give us a decent performance boost.

**Comment by jamesnvc** [comment]
I've started seeing this issue as well; it seems to be associated with a message in the console: `lock state was released early`, from `locks.ts:55:46`

**Comment by glacambre** [comment]
In version 1.18.1pre3801-7d28e98, Tridactyl is back to consuming little to no energy. Thanks @bovine3dom!

**Comment by filterfish** [comment]
Wow! That has made a *dramatic* difference! Tridactyl was at the top of `about:performance` now it doesn't even get a mention.

**Comment by bovine3dom** [comment]
Sorry, it should have never made it into a release in the first place!

**Comment by HattDroid** [comment]
Hi,

Seems like the issue is back, not sure what's the reason though.
But Tridactyl periodically goes up to medium/high energy impact around 60 on Firefox 94.0.1. This keeps going up and down every 3-4 seconds, while not doing anything here.

Running Tridactyl version 1.21.1 here from Mozilla extension store.

**Comment by bovine3dom** [comment]
@HattDroid could you provide your Tridactyl config? There are quite a few settings that could cause that.

**Comment by HattDroid** [comment]
@bovine3dom Thanks for trying to help, please find it below, just a small config:

`{"configversion":"2.0","autocmds":{"DocStart":{"undefined":"mode ignore","feedly.com":"mode ignore"}},"nmaps":{"<C-b>":null}}`

**Comment by bovine3dom** [comment]
Hmm, there's nothing obvious there. I can't reproduce it on FF93. I'll update and see if anything happens.

**Comment by bovine3dom** [comment]
I can't reproduce it on FF94 either. Could you provide us with any more information? Do you see the same behaviour on a fresh profile with Tridactyl running? Is it worse / better on certain pages?
