### ISSUE TITLE
Escape is passed through to website when Tridactyl interface elements are open

### ISSUE THREAD

**Issue by lehasb** [tridactyl/tridactyl#234]
I expected to find this issue already listed, but I don't see it anywhere in the list, so:

When a piece of the tridactyl interface is open (hints or command bar), hitting escape not only exits the tridactyl interface, but also passes through to the main webpage. It's an issue on pages like http://ccca.biola.edu/advent/ where there's a separate popup that is closed when you hit escape. Expected behavior is that tridactyl will catch the escape when an interface element is open and not pass it on to the webpage.

**Comment by chrlsnchrg** [comment]
I'd like to add that this bug seems to extend to _all_ keys in hint mode, not just ESC. When keys used for hinting in "hint-mode" are pressed, both tridactyl and the website receive the key press. 
Try for example pressing "s" in hint mode on https://4chan.org/ck/catalog. The catalog page's search option will be activated _and_ the hint will be activated.

**Comment by Koushien** [comment]
Just naively, I noticed that `Escape` and `s` only activated the noted events in your respectively linked pages on keyup (the Biola U page seems to only listen for keyup), which Tridactyl never tampers with.

I've implemented a stupidly basic handler that suppresses keyup events outside of Ignore Mode in this branch: https://github.com/Koushien/tridactyl/commit/d29d2e19bc2ce9552b84c749e76cd84863c76707. I neither know if this is reasonably minimal or if the general method is better than the alternatives, but it's something you can use for now.

**Comment by lehasb** [comment]
Is there a recommended way to check how a website is using key events? I've noticed some other oddities in keypress behavior around dropdown menus, but I'm not sure if it's related to this or a separate issue.

**Comment by cmcaine** [comment]
You can try to reason it out from looking at the exclusion rules in src/keydown_content.ts and comparing that to what happens when you press keys or you can grep the source of the website for `addEventListener`

**Comment by bovine3dom** [comment]
Also happens on https://www.adamsmith.org/ - pressing `<Esc>` sends you to a squarespace login page (let's just set aside how strange a bind that is anyway).

**Comment by bovine3dom** [comment]
This has started annoying me more so I've made switched the labels to make myself feel better.
