### ISSUE TITLE
Find a tab in current open tabs

### ISSUE THREAD

**Issue by AlaaSaadAbdo** [tridactyl/tridactyl#2341]
Tridactyl version: 1.18.1pre3777-d4d1526
Firefox version: Mozilla Firefox 75.0
Operating system: mac

Hi! thank you very much for the amazing addon :)

I wanted to ask if there's a way to find a tab in the current open tabs analog to `t` but instead of looking into history and bookmarks it lists the current open tabs and takes you to the selected one :)

Thanks again, Cheers!

**Comment by bovine3dom** [comment]
Just press b. B does the same but for all windows :)

**Comment by AlaaMansourTW** [comment]
Thank you that worked. Sorry I'm not sure how I didn't find it in the key bindings

**Comment by AlaaSaadAbdo** [comment]
Thank you that worked. Sorry I'm not sure how I didn't find it in the key bindings
