### ISSUE TITLE
Can't seem to figure out how to set "autocmd DocStart example.net mode normal" to a keybind

### ISSUE THREAD

**Issue by nnadd** [tridactyl/tridactyl#2343]
Tridactyl Version 1.17.1
Firefox 75
Opensuse Linux 15.1 

I'm certainly doing something wrong here, looking at setting 

"autocmd DocStart example.net mode normal"
and
"autocmd DocStart example.net mode ignore"

to a keybind so I don't have to manually enter it each time for a specific site I frequently need to move through the modes, 

"bind <C-e> autocmd DocStart example.net mode normal" didn't seem to do the job and I'm out of ideas, what am I missing?

**Comment by bovine3dom** [comment]
You can't bind a toggle to a single key easily (although that is possible with `:js` and a little imagination).

I think you are just missing that you need to bind to a key sequence, e.g. `bind \\ autocmd DocStart example.net mode normal` and `bind \/ autocmd DocStart example.net mode ignore`.

I suspect you might prefer `bind \\ composite mode normal; autocmd DocStart example.net mode normal` and `bind \/ composite mode ignore; autocmd DocStart example.net mode ignore`, which enters/leaves ignore mode as immediately well as changing the rule.

**Comment by nnadd** [comment]
The second one worked. Though unfortunately while in ignore mode I can't use the keybind to go back to permanent normal mode until I press Shift+ESC. 

If you got some way to circumvent ignore mode doing its job and ignoring tridactyl commands I'm all ears, I'll close this since you solved my issue.

**Comment by bovine3dom** [comment]
Woops, that was my fault - try `bind --mode=ignore \\ composite mode normal; autocmd DocStart example.net mode normal` :)

**Comment by nnadd** [comment]
You're a lifesaver, thanks again for this fantastic addon.

**Comment by bovine3dom** [comment]
Happy to help! Now I think about it, the different modes mean that in your case you can use one bind as a toggle:

```
bind --mode=ignore \\ composite mode normal; autocmd DocStart example.net mode normal
bind \\ composite mode ignore; autocmd DocStart example.net mode ignore
```

**Comment by nnadd** [comment]
Interesting, that makes it simpler but also doesn't give me a clear indication what mode I'm currently in without looking at the bottom right.. with seperate keybinds I'm always sure where I'm standing.
