### ISSUE TITLE
`tri.config.update` sometimes fails to exit

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#2349]
From @xPMo:

I have a similar issue, same version. No tridactylrc, just manual `:unbindurl ` calls. All my unbound keys did nothing, not in the site nor in tridactyl.

Using `:viewconfig`, all my previous unbindurl calls are stored as

```json
"<site>":{
  "j": "",
  "k": "",
  ...
```

If I then call `:unbindurl <site> k`, then my config updates to

```json
"<site>": {
  "j": "",
  "k": null,
  ...
```

And the key is now passed down to the site as normal.

After taking a closer look at the original issue, the symptoms may be different enough for me to open a new issue.

_Originally posted by @xPMo in https://github.com/tridactyl/tridactyl/issues/2338#issuecomment-622108730_

---

Root cause is that we (i.e. I) forgot to update subconfigs when we switched to `null` for unbound keys: https://github.com/tridactyl/tridactyl/blob/d4d1526d3d021a9027740a86b42a420bff36bd50/src/lib/config.ts#L1457

Edit: Actually, this should have updated subconfigs - https://github.com/tridactyl/tridactyl/blob/d4d1526d3d021a9027740a86b42a420bff36bd50/src/lib/config.ts#L1307 - so further investigation is needed.

**Comment by bovine3dom** [comment]
I can't reproduce this:

```
set configversion 1.8
js tri.config.setURL("txti.es","nmaps","j","")
js tri.config.update()
viewconfig # subconfigs.txties\.es.nmaps.j is set to null
```

@xPMo is there any more information you can give us? If you run

```
set configversion 1.8
js tri.config.update()
```

does it fix it?

**Comment by xPMo** [comment]
> ```
> set configversion 1.8
> js tri.config.update()
> ```

That hangs for a while, eating memory until Firefox gets killed by earlyoom.

**Comment by bovine3dom** [comment]
https://github.com/tridactyl/tridactyl/blob/1c4722f4db13ce00754ae89c01cf35a70a52ba58/src/lib/config.ts#L1476 is probably the culprit - if `set("configversion","1.9")` doesn't work it will just keep hammering it.

We could simply change to a `switch` statement without breaks so that any config update automatically applies all later updates. @glacambre is there a reason we didn't do that initially?

**Comment by glacambre** [comment]
I don't think so, I just find having separate functions nicer wrt local 
variable declarations. A switch statement would indeed work nicely too.

**Comment by bovine3dom** [comment]
@xPMo are you using the Beta versions of Tridactyl? If you are, could you try 

```
set configversion 1.8
js tri.config.update()
```

again in the latest betas (available approx 5 mins after this comment :) )?

**Comment by xPMo** [comment]
Sorry, I'm not on the beta, but on `1.19.1pre3928-53d0d189` (according to the start page) there is no leak.
