### ISSUE TITLE
`tri.config.get` from the background page doesn't always use the right URL

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#2352]
https://github.com/tridactyl/tridactyl/blob/d4d1526d3d021a9027740a86b42a420bff36bd50/src/lib/config.ts#L1149

In practice it seems to often be `moz-extension://[UUID]/_generated_background_page.html`. This is probably causing us issues with `setURL`.

**Comment by glacambre** [comment]
On 2020-05-03 15:14, Oliver Blanthorn wrote:
> https://github.com/tridactyl/tridactyl/blob/d4d1526d3d021a9027740a86b42a420bff36bd50/src/lib/config.ts#L1149
> 
> In practice it seems to often be 
> |moz-extension://[UUID]/_generated_background_page.html|. This is 
> probably causing us issues with |setURL|.

This would be surprising to me because in the background page 
tri.contentLocation will be defined so it'll override window.location.

**Comment by bovine3dom** [comment]
Ah, I think I had my `console.logs` in the wrong place.

In that case I think the real issue is here:
https://github.com/tridactyl/tridactyl/blob/d1152b17acbac43ba1347348257e44f188b2bc1f/src/background.ts#L69

We update the `contentLocation` when the background script is loaded. We update it when tabs are changed.

We don't update it if people navigate to a different URL without changing tabs...
