### ISSUE TITLE
Undo close tab doesn't work on OSX FF 75.0

### ISSUE THREAD

**Issue by aleks-m** [tridactyl/tridactyl#2356]
Tridactyl version: 1.18.1pre3774-7fe4b6d
Firefox version: Mozilla Firefox 75.0
Operating system: mac

*   Brief description of the problem:

*   Steps to reproduce:

    1.  close a tab
    2.  press `u` or execute `:undo` cmd
    3.  get an error:
```
# controller in excmd: Error: An unexpected error occurred
```

*   URL of the website the bug happens on: any

*   Config : https://gist.github.com/aleks-m/66c1a225702cca8869da9b7754536b90

**Comment by bovine3dom** [comment]
Could you try on a fresh / temporary Firefox profile and see if it works there?

None of the developers use OSX so it will be tricky to debug.

**Comment by aleks-m** [comment]
Well... I can't reproduce it on an empty config/profile.
And after I switched back to my normal profile - undo started to work fine. Not sure what it was, will reopen if I see it again.
