### ISSUE TITLE
Can't search on earth.google.com/web

### ISSUE THREAD

**Issue by Noexpert** [tridactyl/tridactyl#2366]
Hi

I cannot type anything in the side panel search field at https://earth.google.com/web/.
The search field is selected and the cursor blinks but all keystrokes are intercepted by tridactyl instead.

This is on Firefox 76.0.1 and tridactyl 1.18.1.
Can someone replicate?

Thanks

**Comment by glacambre** [comment]
Works fine for me when entering ignore mode. Have you tried that?

**Comment by Noexpert** [comment]
Indeed it does, the comment was more in relation to why ignore mode needs to be entered at all when other Google services seem to work fine.

Thanks

**Comment by bovine3dom** [comment]
It seems to be a real `input` box so it's probably our fault that we aren't entering insert mode.

**Comment by glacambre** [comment]
There's a real input box but the events are actually triggered on the 
pane that contains it, so we can't know that an input box is focused.

**Comment by bovine3dom** [comment]
Seems to work fine now :confetti_ball:
