### ISSUE TITLE
tabnext mru

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#2378]
I'm using `set tabsort mru` and now my brain finds gt very confusing.

I think having an mru version of it should help.

**Comment by Dranaxel** [comment]
Hello @bovine3dom, I would be interested to work on this issue but I don't use this feature. I suppose you mean you are use the mru sort for the buffer mode (key B) and you want to add an option for going to the mrecent used with gt (instead of the right one). Am I right ?

**Comment by bovine3dom** [comment]
Hi, thanks for being interested. I hadn't thought about it very much to be honest. I want to be able to press `gt` or `gT` repeatedly to flick through tabs as if I had the buffer list open and I was pressing tab/shift tab.

I think you'd need to preserve the recency of tabs in the background script (or in state.ts) when gt was first pressed and the invalidate that after some time has passed without the function being called or on some other criteria (like interacting with the page?).

So it might be a bit trickier than I had thought.

As I'm moving, I'll be slow to reply for about a week now, so please be patient with me : )

**Comment by bovine3dom** [comment]
Resolved in #4595, I think - use `[n]gt` to go to the nth most recently used tab
