### ISSUE TITLE
Colours suggestions

### ISSUE THREAD

**Issue by AZanellato** [tridactyl/tridactyl#2380]
Tridactyl version: 1.19.0pre3821-f4fa5b8
Firefox version: Mozilla Firefox 78.0a1
Operating system: linux

# Making a feature request

Hello. I have been using trydactyl for quite a bit now and want to thank for all the effort you all are putting into it! :smile: 

I was curious about the colours command and why can't it have a hint about the pre-defined themes in trydactyl (I always forget how to spell shydactyl) and maybe we could cycle through them with tab? 

I'm up for helping implementing this as well :smile:

**Comment by glacambre** [comment]
This should be fairly simple to implement if you want to do it:
Just add a file in `src/completions/`, copy the contents of other files 
here (the Preferences.ts file is probably the simplest completion file 
we have and therefore a good candidate). You will find a list of bundled 
themes under the name `staticThemes` in `src/.metadata_generated.ts`, 
just import that in the completion file and offer it as completion options.

If you want to go a little farther and also offer themes written by the 
user, you will need to use the `getrcpath()` function available in 
`src/lib/native.ts` to get a path to the user's tridactyl config and 
then use `listDit` (still in `native.ts`) to read the contents of the 
"theme" directory users might have in their tridactyl config directory.

If you feel a bit lost, you can take a look at the `colourscheme` and 
`loadtheme` functions in `src/excmds.ts`. We have also lots of 
information in `contributing.md` and `/doc`. And of course, don't be 
afraid to ask questions here or in the Tridactyl room on irc/matrix :).

**Comment by AZanellato** [comment]
Thanks! Will start working on this as soon as I can :smile:
