### ISSUE TITLE
Bind esc to unfocus addess bar

### ISSUE THREAD

**Issue by Trosterud** [tridactyl/tridactyl#2381]
When pressing esc while in the address bar, it doesn't unfocus it. Having read and searches through both firefox and tridactyl documentation I haven't found a way to either use tridactyl bind or firefox settings to do this. I think this is common enough for people switching away from chrome that it could be featured better in the docs, maybe even set up by default :) 

*   Steps to reproduce:
Focus on address bar in Firefox (cmd/ctrl L) and press esc. Only works by pressing fn+6, which isn't very natural or vim-like at all

*   Tridactyl version (`:version`): any

*   Firefox version (Top right menu > Help > About Firefox): any

*   URL of the website the bug happens on: -

*   Config: default

**Comment by glacambre** [comment]
Unfortunately there's nothing Tridactyl can do to fix this. I believe 
Firefox's default <F6> shortcut should give focus back to the page though.

**Comment by bs** [comment]
One workaround on MacOS is to create a remap/shortcut for esc->F6 w/ BetterTouchTool.

**Comment by Tanath** [comment]
`<F6>` does work to toggle focus to the page.

**Comment by bovine3dom** [comment]
I don't see us being able to fix this any time soon :(
