### ISSUE TITLE
e2e tests seem more broken than usual

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#2387]
It used to be that about 1 in 3 tests would fail spuriously. It currently seems like about 95% of e2e tests fail.

**Comment by bovine3dom** [comment]
Looks like the selenium setup is just broken - on my machine I just get blank Firefox windows opening, with nothing happening until the timeout causes it to error out.

**Comment by bovine3dom** [comment]
It might be worthwhile looking at how Mozilla recommends we do testing - https://github.com/mdn/webextensions-examples/tree/master/mocha-client-tests - they seem to use `Karma`.

**Comment by glacambre** [comment]
Karma is just a test runner, so it's equivalent to jest. The important 
bit IMO is that they use sinon-chrome: 
https://github.com/mdn/webextensions-examples/blob/0d46482e7da8a53fefd684175ad35ca8dc0c3652/mocha-client-tests/karma.conf.js#L15

So they recommend mock testing, not the "real thing" (which makes sense 
given the pain testing webextensions with selenium is).

**Comment by bovine3dom** [comment]
https://github.com/mdn/webextensions-examples/blob/0d46482e7da8a53fefd684175ad35ca8dc0c3652/mocha-client-tests/karma.conf.js#L63 what does this mean then?

**Comment by glacambre** [comment]
If I understand correctly, that the test should be ran in the browser. 
But since they're using sinon, they're not actually loading the 
extension (with a content and a background script) in the browser - 
instead they load the background script in a page, and any call made to 
`browser` is handled by sinon.

**Comment by bovine3dom** [comment]
https://github.com/tridactyl/tridactyl/pull/2417 somehow the tests have all passed on this PR :S

**Comment by glacambre** [comment]
I'm not seeing anything in this PR that would prevent any test from succeeding, so there's probably nothing wrong, you just got lucky.

My dirty little secret for Firenvim is to run `npm run test || npm run test`. This allowed me to go from "failing on every commit" to "failing occasionally".

**Comment by bovine3dom** [comment]
We've passed four tests in a row, which I think is a record.

**Comment by bovine3dom** [comment]
https://support.circleci.com/hc/en-us/articles/360045268074-Build-Fails-with-Too-long-with-no-output-exceeded-10m0s-context-deadline-exceeded-

Seems most failing jobs now fail with this error, so it might be worth increasing the timeout.

**Comment by bovine3dom** [comment]
It would be nice to move from "pass (all tests) at least once out of n attempts" to "pass each test at least once after n trials". Is that easy to do with our test framework?

**Comment by glacambre** [comment]
Looks like it is: https://jestjs.io/docs/en/jest-object#jestretrytimes

**Comment by bovine3dom** [comment]
We need to use a different test runner to use that. I have no idea how easy that is
