### ISSUE TITLE
"tab" no longer accepts text arguments

### ISSUE THREAD

**Issue by hejops** [tridactyl/tridactyl#2401]
Tridactyl version: 1.19.0pre3855-37ea90f
Firefox version: Mozilla Firefox 76.0.1
Operating system: linux

As in the title, the `tab` command no longer accepts text arguments for me. It still accepts numbers though.

**Comment by bovine3dom** [comment]
Probably introduced in https://github.com/tridactyl/tridactyl/commit/caf38436b61666bbbd54662728f874146e857ca7

**Comment by hejops** [comment]
For example, I can invoke `:tab 1` to go to the first tab, but `:tab github` produces:

`# controller while accepting: Error: Can't convert "github" to any of: number,"#"`

AFAIK the only tab-related options in my tridactylrc are as follows:
bind B tab #
set tabsort mru

**Comment by bovine3dom** [comment]
It should be fixed in the latest betas. Thanks for pointing this out - I'm not sure how it slipped past me :)
