### ISSUE TITLE
Tridactyl broken on Firefox ESR

### ISSUE THREAD

**Issue by mddvul22** [tridactyl/tridactyl#2404]
Last night, Firefox disabled my Tridactyl plugin.  I'm running Firefox ESR version 68.8.  I'm can't find any way to force it to enable.  It was working fine on Firefox ESR, until last night.  I'm not sure what happened to make it suddenly get disabled, as I didn't make any changes.

I'm not sure how to reproduce this.  I have Firefox ESR 68.8 on three computers.  It is only disabled on one of them, so far.

*   Tridactyl version (`:version`): 1.17.1

*   Firefox version (Top right menu > Help > About Firefox): 68.8 (ESR)

*   Operating system: Mac

![image](https://user-images.githubusercontent.com/6833993/82625344-7ea96e00-9baa-11ea-8ef1-c7da3d58c18f.png)

I searched for Tridactyl in the addons, to see if there was a different version available.  Saw this:

![image](https://user-images.githubusercontent.com/6833993/82625559-19a24800-9bab-11ea-9528-904c4614af28.png)

I'm not sure why Tridactyl requires version 75.  It works fine, for me, in 68.8 -- at least until Firefox disabled it.  Is there anyway to force it to enable?

**Comment by glacambre** [comment]
I would recommend removing the current Tridactyl version you have and 
downloading it again. You should find an ESR-compatible version here: 
https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/versions/?src=search

**Comment by mddvul22** [comment]
That seems to have worked.  Thanks!
