### ISSUE TITLE
Command line not showing

### ISSUE THREAD

**Issue by b3n10** [tridactyl/tridactyl#2405]
Tridactyl version: 1.19.0pre3819-f269dcab
Firefox version: Mozilla Firefox 76.0.1
Operating system: Arch Linux

*   Brief description of the problem:
Command line (command prompt) is not showing when using `:` keybinding. Also error in console 
```
TypeError: "cmdline_iframe.contentWindow is null"
    show commandline_content.ts:62
    showcmdline .excmds_content.generated.ts:2413
    fillcmdline_notrail .excmds_content.generated.ts:2440
    acceptExCmd controller.ts:25
    ParserController controller_content.ts:198
    acceptKey controller_content.ts:211
    guardedAcceptKey content.ts:51
    commandline_content.ts:68:16
    show commandline_content.ts:68
    showcmdline .excmds_content.generated.ts:2413
    fillcmdline_notrail .excmds_content.generated.ts:2440
    acceptExCmd controller.ts:25
    ParserController controller_content.ts:198
    acceptKey controller_content.ts:211
    guardedAcceptKey content.ts:51
```

*   Steps to reproduce:
1. Press `:` on the keyboard (SHIFT + ' on my keyboard)
2. Command line not showing.
3. Open JS Console and error says `TypeError: "cmdline_iframe.contentWindow is null"`
4. Uninstall and reinstall (from Firefox Addons website) but same issue.
5. Uninstall and reinstall (from Arch Linux repo) but same issue.

*   URL of the website the bug happens on:
Any website

**Comment by bovine3dom** [comment]
I can't reproduce this on Windows with this exact version (i.e. 1.19.0 stable) and I didn't notice it on Linux, but I'll try this evening.

In the meantime could you try on a fresh Firefox profile so we can see if it is something to do with your configuration / other addons?

**Comment by b3n10** [comment]
It did work with new Firefox profile. Thanks for your help.

**Comment by bovine3dom** [comment]
Could you post your Tridactyl configuration here? If you go to make a new issue on this repository it will give you instructions on how to do that.

Ideally it would be hard to break Tridactyl like this so I would like to get to the bottom of it :)

**Comment by b3n10** [comment]
I don't even have and not using a tridactylrc. But I was wondering how come tridactyl still remember my keybindings even after re-installation?

Running this yields no result:
```
$ find ~ -name '*tridactylrc*'
```

**Comment by glacambre** [comment]
On 2020-05-23 02:38, b3n10 wrote:
> I don't even have and not using a tridactylrc. But I was wondering how 
> come tridactyl still remember my keybindings even after re-installation?

Your settings are stored in a "webextension storage" that Firefox keeps 
across installations.

One way you can retrieve your old settings is to type `tri js 
alert(JSON.stringify(config.get()))` in Firefox's urlbar.

@bovide3dom : @b3n10's `:version` information does not point to an 
existing commit, what could be going on there?

**Comment by b3n10** [comment]
I've totally messed up. I was tinkering with `seturl` and set it to disable command line in any websites, unfortunately I forgot the specific command and can't reproduce the issue. To enable command line without the `command line`, I typed this in JS console and it's back now:
```js
// also not sure what command worked, but I invoked all of these:
tri.config.setURL()
tri.config.setURL("", false)
tri.config.setURL([], false)
```

**Comment by bovine3dom** [comment]
> b3n10's `:version` information does not point to an
existing commit, what could be going on there?

I have no idea. Probably related to #2262
