### ISSUE TITLE
Tridactyl doesn't load native after nativeinstall

### ISSUE THREAD

**Issue by ChocolateOverflow** [tridactyl/tridactyl#2406]
Tridactyl version: firefox-tridactyl 1.18.1-1
Firefox version: Mozilla Firefox 76.0.1
Operating system: Manjaro linux

*   Brief description of the problem:
Firefox loads Tridactyl just  fine but `native` doesn't seem to work at all. I've tried both `yay -S firefox-tridactyl-native` and `:nativeinstall` but neither seems to work.

*   Steps to reproduce:

1. Install Tridactyl with `sudo pacman -S firefox-tridactyl`
2. Use `yay -S firefox-tridactyl-native` to install `native` from the AUR
3. Restart firefox several times. 
4. `:native` returns `Native messenger not found...`
5. Uninstall  `firefox-tridactyl-native`
6. Run (from `installnative`) `curl -fsSl https://raw.githubusercontent.com/tridactyl/tridactyl/master/native/install.sh -o /tmp/trinativeinstall.sh && bash /tmp/trinativeinstall.sh master`
7. Restart firefox several  times
8. `:native` returns `Native messenger not found...`

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
https://pastebin.com/n2UQbuGY

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):
```
" vim: filetype=vim

" Allow Ctrl-a to select all in the commandline
unbind --mode=ex <C-a>

" Allow Ctrl-c to copy in the commandline
unbind --mode=ex <C-c>

set searchengine duckduckgo
set smoothscroll true
set newtab about:blank

autocmd DocStart mail.google.com mode ignore
autocmd DocStart youtube.com mode ignore

bind H tabprev
bind L tabnext
bind K forward
bind J back
```

*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:
No output.

*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:
```
3{"cmd": "run", "content": "/home/user_name/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/opt/nessus/bin:/opt/nessus/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/user_name/.custom/scripts/bspwm:/home/user_name/.custom/scripts/ctf:/home/user_name/.custom/scripts\n", "code": 0}
```

**Comment by glacambre** [comment]
Are you running Firefox in any kind of sandbox (Firejail, Apparmor, 
Snap, Flatpak…)?

**Comment by ChocolateOverflow** [comment]
I'm running firefox with firejail. Which directories should I whitelist?

**Comment by glacambre** [comment]
On 2020-05-23 09:53, Chocolate Overflow wrote:
> I'm running firefox with firejail. Which directories should I whitelist?

~/.config/tridactyl/
~/.share/tridactyl/
~/.mozilla/
~/.mozilla/native-messaging-hosts/

You might also need to authorize Firefox to run Python and access 
python's libraries, as that's the language in which the native messenger 
is written.

**Comment by ChocolateOverflow** [comment]
I've whitelisted them in firejail's `firefox.profile`:
```
whitelist ${HOME}/config/tridactyl/
whitelist ${HOME}/share/tridactyl/
whitelist ${HOME}/.mozilla/
whitelist ${HOME}/.mozilla/native-messaging-hosts/
whitelist /usr/bin/python3*
whitelist ${HOME}/.local/lib/python3.8/site-packages/*
```

However, it's still not giving me `Native messenger not found`. Is there something wrong with my whitelist?

**Comment by bovine3dom** [comment]
@ChocolateOverflow if you enable Firejail logging with `--tracelog` it should tell you what the problem is. See https://github.com/netblue30/firejail/issues/152

Please report back if you work it out as we should add the solution to our FAQ.

**Comment by gerardbosch** [comment]
Should native work out-of-the-box when Firefox is installed with Snap?
I installed `native` but when I run `:native` it tells it's not found. I'm suspecting it is because of Snap installation.

**Comment by gerardbosch** [comment]
Hi there! I confirm that after installing Firefox with Nix package manager, `native` works, so it seems it does not work with Snap - I guess it cannot access the path where `native` is instalEd.

I've also noticed that recently Snap migrated Firefox profiles and stuff from `~/.mozilla` to `~/snap/firefox/common/.mozilla`. I found this as there was a replica of all my profiles in the later, and `stat` shows it was created last month.

**Comment by saulrh** [comment]
It looks to me like `native` is flat-out incompatible with firefox from snaps: There's no way to give a snap a permission to launch the necessary processes. https://forum.snapcraft.io/t/native-messaging-support-in-strictly-confined-browser-snaps/26849/6

This is a particularly substantial problem because newer versions of Ubuntu ship firefox *only* as a snap. It looks like it's time for me to switch to fedora for good.

**Comment by glacambre** [comment]
You could also install firefox from Mozilla's website, which as far as I understand is just a regular binary (with the ability to auto-update).

**Comment by bovine3dom** [comment]
Related FF bug tracking the issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1661935

**Comment by stagnation** [comment]
Thanks for the plugin!

Just to chime in if others search for nix and nixos.
I got the native running with a few steps, but couldn't find a good write up for how it is meant to work precisely in nixos. It could well be packaged just as it should in the nix world, I am new so that is a big disclaimer.

The regular installer does not work
```
$ file /home/nils/.local/share/tridactyl/native_main
/home/nils/.local/share/tridactyl/native_main: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynami
y linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=4946e69160d097c03e6782e55569523649e20987, for
/Linux 3.2.0, not stripped
$ /home/nils/.local/share/tridactyl/native_main
Could not start dynamically linked executable: /home/nils/.local/share/tridactyl/native_main
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
```

But there is a packaged messenger for firefox:

https://github.com/NixOS/nixpkgs/blob/release-24.05/nixos/modules/programs/firefox.nix
https://mynixos.com/nixpkgs/option/programs.firefox.nativeMessagingHosts.tridactyl

This can be configured and downloaded in `/etc/nixos/configuration.nix`:
```
  programs.firefox = {
          enable = true;
          nativeMessagingHosts.tridactyl = true;
  };
```

Then I expected it to work as-is, but had to perform one more manual step.
Please correct my misunderstanding here.

```
$ find /nix/store -name native_main
/nix/store/j32hhzj9ldiwq7xca10kmjzq1csnjyfn-tridactyl-native-0.4.1/bin/native_main
$ /nix/store/j32hhzj9ldiwq7xca10kmjzq1csnjyfn-tridactyl-native-0.4.1/bin/native_main
^CSIGINT: Interrupted by Ctrl-C.
# No warning about ld. It works!
$ rm /home/nils/.local/share/tridactyl/native_main
$ ln -s /nix/store/j32hhzj9ldiwq7xca10kmjzq1csnjyfn-tridactyl-native-0.4.1/bin/native_main
```

And that is it, `:native` and editing in vim now works!
