### ISSUE TITLE
`g;` seems to have stopped working

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#2407]
I get `# controller in excmd: Error: Invalid tab ID: 26` on Windows.

**Comment by bovine3dom** [comment]
It's a similar cause to #2236 - `concat` doesn't count as `get` so it's not triggering our errors, even though it's used in the content script: https://github.com/tridactyl/tridactyl/blob/891f7b7eafb7f2a51ff4f69f4d2b69fe161dbd0d/src/lib/dom.ts#L540

It should instead use `getAsync` before trying to concat with it.

I'm wondering whether it is worth abandoning the proxy altogether and just having simple `.set` and `.get` methods of our own.

**Comment by dit7ya** [comment]
Has this been solved? I am still getting this error.

**Comment by bovine3dom** [comment]
Works fine for me on 1.21.0pre5353-6c013b94 - what `:version` are you using?

**Comment by dit7ya** [comment]
I am sorry, just figured it was returning that error only after deleting the tab where the edits were being made. Otherwise it works fine. My bad.

**Comment by bovine3dom** [comment]
We could potentially make the error more human-friendly : )
