### ISSUE TITLE
`:bind d composite tabprev; tabclose #` doesn't work in the commandline

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#2408]
because `#` starts a comment. 🤦 

Workaround: use the address bar with `tri bind d composite tabprev; tabclose #`.

**Comment by glacambre** [comment]
This works fine for me. I thought Tridacytl used vim-style comments?

**Comment by bovine3dom** [comment]
It works for me too, now. I'm very confused. :(

>  I thought Tridacytl used vim-style comments?

Only in the RC file, and only at the beginning of lines. In the command line we use `#` but again only at the beginning of lines. I have no idea why we (I?) picked `#` for the command line...
