### ISSUE TITLE
Different rc files for different profiles.

### ISSUE THREAD

**Issue by caputchinefrobles** [tridactyl/tridactyl#2411]
Tridactyl version: 1.19.0pre3821-f4fa5b8
Firefox version: Mozilla Firefox 77.0
Operating system: linux (manjaro)

It is just a question. Is it possible running different tridactylrc files for different firefox profiles? I ask because it searches for ~/.tridactylrc, ~/.config/tridactyl/tridactylrc, etc. 
Is it possible having something like:

Home FF profile -> ~/.config/tridactylr/home_tridactylrc
Work FF Profile -> ~/.config/tridactylr/work_tridactylrc

Thanks

**Comment by glacambre** [comment]
That's not possible but you can easily simulate that in your tridactylrc 
with something like that:

js tri.native.getProfile().then(p => p.absolutePath == 
"/path/to/default/profile" ? 
tri.excmds.source("/path/to/tridactylrc/for/default/profile") : 
tri.excmds.source("/path/to/tridactylrc/for/other/profile"));
