### ISSUE TITLE
:mkt not working (controller in excmd)

### ISSUE THREAD

**Issue by Tanath** [tridactyl/tridactyl#2415]
Tridactyl version: 1.19.0pre3821-f4fa5b8
Firefox version: Mozilla Firefox 76.0.1
Operating system: linux

*   Brief description of the problem:  
Running `:mkt` or `:mkt!` results in: `# controller in excmd: Error: pconf[i][e] is null`

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):  
https://gist.github.com/Tanath/28eb3d9158e9616497f84b1a43513d8b

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
" General Settings
set update.lastchecktime 1587925524900
set configversion 1.9
set updatenaglastversion 1.17.1
set theme dark

" Binds
bind d scrollpage 0.5
bind x tabclose
bind e scrollpage -0.5
bind k scrollpage -0.25
bind j scrollpage 0.25

" Ignored sites
autocmd DocStart mail.google.com mode ignore

" For syntax highlighting see https://github.com/tridactyl/vim-tridactyl
" vim: set filetype=tridactyl
```

**Comment by glacambre** [comment]
This bug was introduced in 
https://github.com/tridactyl/tridactyl/pull/2157 . 
src/lib/config.ts:parseConfigHelper needs to check for nulls.
