### ISSUE TITLE
CI should be easier to replicate on your own machine

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#2419]
Tangentially raised in #2416. We should just have, e.g. ci/lint.sh, ci/e2e.sh to make it really easy for people to run.

**Comment by Dranaxel** [comment]
Hi, getting a little bit busy actually but still having a look on issues ;)
Do you think docker files to execute CI jobs would be great to ease the replication ?

**Comment by bovine3dom** [comment]
If we can manage it, I would like to avoid docker as it uses up a lot of disk space and can be slightly fiddly to set up.

What I'd like is for each CI job to just be a single script that can be executed by people on their own machines, so essentially:

```
ci/e2e.sh -> yarn jest
ci/unit.sh -> $(yarn bin)/jest src
... etc.
```

and called in the .github/workflows and .circleci/config.yml.


Do you understand what I mean?

I'm not so concerned about 1:1 replication of environment as much as the ease of running at all.

**Comment by bovine3dom** [comment]
I think we have pretty much done this with the `ci/` folder
