### ISSUE TITLE
Change default editor

### ISSUE THREAD

**Issue by strogiyotec** [tridactyl/tridactyl#2438]
Tridactyl version: 1.19.1pre3928-53d0d18
Firefox version: Mozilla Firefox 76.0.1
Operating system: linux
Good day , I really appreciate what you do.
I do want to change the default editor to fill input texts, my env variable for $EDITOR is nvim but tridactyl uses vim instead
According to help page
```
If it's a bit slow, or chooses the wrong editor, or gives up completely, set editorcmd to something you want
```
I am not really sure how exactly I am supposed to do it
I tried
```
:set editormode nvim
```
With this setting tridactyl doesn't open editor at all, also i tried this command
```
set editorcmd terminator -u -e "nvim %f '+normal!%lGzv%c|'"
```
It doesn't work as well. Please explain my what I missed and how I can change default editor to nvim Thank you

**Comment by glacambre** [comment]
Does running `:! which nvim` in tridactyl show a path to neovim? If it 
doesn't, your problem is that neovim isn't in Firefox's path. To fix 
this, give an absolute path to neovim in the editorcmd.

**Comment by strogiyotec** [comment]
@glacambre , the output is :
```
/usr/bin/nvim
```
So I assume that I have a correct path. Maybe I used editormode wrongly.
Is this command correct to change default editor ? 
```
:set editormode nvim
```

**Comment by glacambre** [comment]
On 2020-05-30 20:21, Abdrazak Almas wrote:
> Is this command correct to change default editor ?
> 
> |:set editormode nvim |

No, it should be `:set editorcmd /path/to/terminal -e /path/to/nvim`.
You might need to replace `-e` with another flag depending on what 
terminal emulator you want to use.

What's the path of your terminal emulator?

Also, where did you find `editormode`? Is it mentionned somewhere in the 
docs?

**Comment by strogiyotec** [comment]
@glacambre , thank you for response. This command
`:set editorcmd /path/to/terminal -e /path/to/nvim` works for me
