### ISSUE TITLE
Redirect Before Connecting

### ISSUE THREAD

**Issue by kayg04** [tridactyl/tridactyl#2454]
Tridactyl version: 1.19.1pre3938-a34bb31
Firefox version: Mozilla Firefox 76.0.1
Operating system: linux

Hello!

I'm trying to replace `Privacy Redirect` extension with `urlmodify` on Tridactyl. From the `tridactylrc` on the repo, I have the following in my tridactylrc:

`autocmd DocStart ^http(s?)://www.youtube.com js tri.excmds.urlmodify("-t", "www.youtube.com", "invidio.us")`

However it seems that, unlike `Privacy Redirect` which causes the redirect happen before connecting to the original URL, `Tridactyl` makes the rewrite after connecting to the original URL. Can the rewrite-before-connect functionality be achieved somehow?

Thank you.

**Comment by bovine3dom** [comment]
Not currently, at least not ergonomically. You can use the `webRequest` API with `:jsb` to add a redirect. See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest

You'll need to run that every time Tridactyl starts. The easiest way would be to add the line to your RC file.

Work on "official" support is tracked in https://github.com/tridactyl/tridactyl/issues/1885 - if you're interested in contributing I'd be happy to help you get started.

**Comment by kayg04** [comment]
Ah, I'm not sure how I'd go about using it. Could you give me an example? I haven't dabbled with any javascript yet so I don't think I'd be of any help on the development front. :/

**Comment by kayg04** [comment]
I found a solution here: https://www.w3schools.com/howto/howto_js_redirect_webpage.asp

Thanks!

**Comment by bovine3dom** [comment]
I'd be quite surprised if that works - the webrequest runs before any page JavaScript can execute. You've essentially replicated urlmodify there.

The correct way is to return a blocking response with a redirectUrl property. Everything you need is linked to from that page, but I am happy to show you exactly how when I'm next at my PC - I'm sending this from a phone : )

**Comment by kayg04** [comment]
You're actually right. I spoke too soon and I saw that it did exactly what `urlmodify` does. 

I was reading the `onBeforeRequest` page and it has some examples. I'd love some help from you as well.

**Comment by kayg04** [comment]
I got it working with:

```
// match pattern for the URLs to redirect
var pattern = "https://www.youtube.com/";

// redirect function
// returns an object with a property `redirectURL`
// set to the new URL
function redirect(requestDetails) {
console.log("Redirecting: " + requestDetails.url);
return {
redirectUrl: "https://invidio.us/"
};
}

// add the listener,
// passing the filter argument and "blocking"
browser.webRequest.onBeforeRequest.addListener(
redirect,
{urls:[pattern], types:["main_frame"]},
["blocking"]
);
```

and 

`autocmd DocStart ^http(s?)://www.youtube.com jsb -r redirect.js`

Now I need to work towards preserving the subpaths.

**Comment by bovine3dom** [comment]
You don't need it in an autocmd - addListener only needs to be run once per browser start. I'd stick it in an RC file, e.g.

```
jsb browser.webRequest.onBeforeRequest.addListener(
() => {redirectUrl: "https://invidio.us/"},
{urls:["https://www.youtube.com/"], types:["main_frame"]},
["blocking"]
);
```

You might want to look at https://github.com/tridactyl/tridactyl/blob/8e9eff4ebee9375c1b016dbfd633bee04306cb3e/src/excmds.ts#L1737 for inspiration on replacing domains.

**Comment by bovine3dom** [comment]
This should work in an RC file to preserve paths:

```javascript
jsb browser.webRequest.onBeforeRequest.addListener( \
    details => {
        let url = new URL(details.url) \
        url.hostname = "invidio.us" \
        return redirectUrl: url \
    }, \
    {urls:["https://www.youtube.com/"], types:["main_frame"]}, ["blocking"] \
);
```

**Comment by kayg04** [comment]
That didn't work. Not only does it not preserve subpaths but it breaks the redirect too. But I understand what you're doing though.

**Comment by bovine3dom** [comment]
There were at least two typos in there, woops ... I've fixed the ones I found, but it still doesn't work for me.

Let me know if you work it out, it's probably something daft :)

**Comment by bovine3dom** [comment]
I fixed it - my edited comment above works for me now in an RC file.

Summary of my mistakes:
- I missed off the semi-colons which are needed because of the way our parser merges lines in RC files
- I somehow missed `{}` off the object to be returned
- `redirectUrl` doesn't accept URL objects (obviously), so I coerced it to a string with `+ ""`
- The URL match pattern needed a wildcard at the end

**Comment by kayg04** [comment]
It seems to work now. :D

Not sure why it doesn't, for you. Thanks a lot, mate.

**Comment by kayg04** [comment]
Strange that my solution worked without the wildcard? Maybe I didn't restart Firefox.

Anyways, this is ultra helpful. To take what I'm trying to do further, I appended some parameters to `redirectUrl` as `redirectUrl: url + "?local=true&quality=hd720&dark_mode=true"` since you said `url` had to be a string. Worked out wonderfully. :)

This is all very interesting. Thank you for helping me reduce the number of extensions I use on Firefox / replacing `Privacy Redirect`.

Jun 4, 2020 21:08:02 Oliver Blanthorn <notifications@github.com>:
