### ISSUE TITLE
contributing.md

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#246]
Stuff to include:

- [x] overview of architecture: what file does what

- [x] ask people to come onto chat

- [x] explanation of build process

- [x] documentation explanation

- [x] macro explanation

- [x] suggestions of how people can help (include leaving honest reviews on AMO because barely anyone does this :( )

**Comment by cmcaine** [comment]
We should maybe have PRs listed as WIP or RFC as well.

**Comment by bovine3dom** [comment]
Started in be7abde.

**Comment by glacambre** [comment]
Is there anything else that would be useful to mention in contributing.md?
