### ISSUE TITLE
Help pages should respect dark mode

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#2470]
(there may already be an issue for this)

`:colours dark|quake` should have their help pages be dark like their new tab pages are.

As mentioned by JohnGalt2600 on Matrix.

**Comment by bovine3dom** [comment]
Probably as simple as adding this class to the help pages: https://github.com/tridactyl/tridactyl/commit/59e737f2544d8976ef57d4269097a4eb986fde32

**Comment by acicovic** [comment]
For those who might be interested and don't know how, here is how to enable dark mode in Tridactyl: https://github.com/tridactyl/tridactyl/issues/2774

**Comment by bovine3dom** [comment]
This specific issue was fixed recently 5a53665e2955eb6fecb89ea3d577c3494f33a651 : )
