### ISSUE TITLE
Feature request: navigating Google with j and k

### ISSUE THREAD

**Issue by wanghankun** [tridactyl/tridactyl#2476]
Is it possible to add search engine navigation with j and k like what's in qutebrowser?

**Comment by bovine3dom** [comment]
I don't understand what this means - could you explain it in more detail?

The answer is probably yes, but not as a default bind as J/K are used for switching tabs.

**Comment by wanghankun** [comment]
On qutebrowser, you can move up and down the search results with j and k and type enter to open the result. This makes navigating the search results a lot easier because I don't need to use f.

**Comment by wanghankun** [comment]
![image](https://user-images.githubusercontent.com/28958399/84394035-4d91eb80-abf4-11ea-8957-0ab992973f03.png)
For example, if I want to open the second result (wikipedia). I type j and press enter.

**Comment by bovine3dom** [comment]
You might find the two binds here https://github.com/tridactyl/tridactyl/blob/9d7b1107cd67abf98a5659a6f36c2cb5c4e14588/.tridactylrc#L57 do 90% of what you want. It's what I use personally.

You can then do `bind --mode=hint J hint.focusBottomHint` with similar for K but hint.focusTopHint. You may need to remove j and k from `set hintchars` but I'm not sure.

If you're feeling really adventurous you can do `autocmd DocLoad www.google.com/search hint -Jqb [the selector from before]` which will put you in rapid hint mode, I think, when the page loads. The hints won't refresh with scrolling, but I can't remember the last time I scrolled down the page on Google...

**Comment by wanghankun** [comment]
Thanks, this works very well!
