### ISSUE TITLE
Compatibility with Jupyter Lab Vim extension

### ISSUE THREAD

**Issue by wanghankun** [tridactyl/tridactyl#2478]
I added Jupyter lab into blacklist, which forces it into ignore mode, but with Jupyter Vim extension, Control + o switches tridactyl from ignore mode back to normal mode. Is it possible to make tridactyl unbind every keybinds on Jupyter lab?

Here is the link for the extension:
`https://github.com/jwkvam/jupyterlab-vim`

**Comment by bovine3dom** [comment]
`unbind --mode=ignore <C-o>` - if you use jupyter on a certain URL you can use `unbindurl [URL] --mode...` to preserve the ctrl-o bind on other pages.

We should probably add this information to `:blacklistadd` help

**Comment by wanghankun** [comment]
Thank you that solves it!

**Comment by bovine3dom** [comment]
Reopening to remind me to improve the help on blacklistadd.
