### ISSUE TITLE
Feature Request: Zoom by URL pattern.

### ISSUE THREAD

**Issue by simonhughcom** [tridactyl/tridactyl#2482]
You can already use 'zoom' to set zoom levels for the current page, but it would be nice If you could do it automatically per URL. (Or maybe you can already do that and I just missed it).

At first I thought you could do it with seturl such as 'seturl example.com zoom 150', but apparently not.

Maybe a new command such as 'zoomurl example.com 150'

Reason I think this would be useful is that you can then get rid off yet another extensions that deals with this, simplifying your setup and decreasing your attack surface. And I think this should be quite easy to implement.

**Comment by bovine3dom** [comment]
Does `autocmd DocStart [url] zoom [amount]` do what you want?

**Comment by simonhughcom** [comment]
It works, brilliant. I completely missed the autocmd, I kept searching the help page for everything related to url and zoom. Thank you.

**Comment by bovine3dom** [comment]
I'll leave this open to remind us to add a link to autocmd from seturl.

**Comment by simonhughcom** [comment]
Maybe it would not be such a bad idea to add a command such as 'zoomurl' anyway, even if you can use autocmd to do that?

**Comment by bovine3dom** [comment]
I'm not sure - I think I'd rather people learnt about autocmds. We could mention it on `:help zoom` : )

**Comment by simonhughcom** [comment]
Or that, and just a suggestion but maybe add a 'helpfull tips' section and/or an FAQ to the help page that show common tasks and answer common questions such as this and how to do them. Saves you having to answer a bunch of issue requests.
