### ISSUE TITLE
Tautological alias descriptions in command mode

### ISSUE THREAD

**Issue by makkonen** [tridactyl/tridactyl#2483]
Tridactyl version: 1.19.1pre3950-8628eb7
Firefox version: Mozilla Firefox 77.0.1
Operating system: linux

*   Brief description of the problem: One-line descriptions of aliases in the command mode console show up tautologically/unhelpfully in some cases.

*   Steps to reproduce:

    1.  Type ':help openwith' => useful description "Alias for `hint -W`" is displayed
    2.  Type ':openwith' => unhelpful description "Alias for `openwith`" is displayed

(same with any other default aliases, as well)

*   URL of the website the bug happens on: *

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com): https://gist.github.com/makkonen/1c43fbba23b06b8472d87b2e3faf20b0

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist): NA

**Comment by glacambre** [comment]
I think I broke it in https://github.com/tridactyl/tridactyl/pull/2369 . 
I don't understand why though - it worked fine when I tested it.

**Comment by MyGitUsername** [comment]
I can look into this bug.

**Comment by bovine3dom** [comment]
@MyGitUsername thanks! I should warn you that this is a fairly complicated part of Tridactyl. It's possible that it is an easy fix but it is also possible that it is not. If you need to look into the `Metadata`, it is generated from the `compiler/` folder.

If you get very stuck feel free to ask for help or pick an "easy" issue from https://github.com/tridactyl/tridactyl/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
