### ISSUE TITLE
How to mark the location of a Web page

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [tridactyl/tridactyl#2491]
Tridactyl version: 1.19.1pre3928-53d0d18
Firefox version: Mozilla Firefox 75.0
Operating system: win

It's like the Pentadactyl's 'm' hotkey，this is very useful when visiting a long page

**Comment by bovine3dom** [comment]
We don't have this feature, yet. We'd like it though :)

I'm closing this issue as a duplicate of #604.
