### ISSUE TITLE
`:tabopen` 📸 Flashbang keeps me awake

### ISSUE THREAD

**Issue by maricn** [tridactyl/tridactyl#2510]
Tridactyl version: 1.19.1pre3928-53d0d18
Firefox version: Mozilla Firefox 78.0
Operating system: linux

### Brief description of the problem:
Opening new tab will flash white background even though I'm using dark colorscheme. It takes a second to apply the colors. And when my eyes are tuned to the darkness, that can be pretty annoying. This is a short video of how it looks like when i open a new tab: https://www.maricn.me/images/tmp/tridactyl-flashbang.ogv (i use different theme here, but it's the same with `dark` as well).

### Steps to reproduce:
1. Install tridactyl on firefox.
2. Issue `colours dark` command.
3. Open new tab and observe white background before the dark colorscheme gets applied.

Note: I have userChrome.css tweak to change background color of about:blank and other browser tabs (https://fedidat.com/640-dark-newtab-firefox/). So, it's not that white background. And this issue is not present when tridactyl is out.

### Config

https://gist.github.com/maricn/a86720274072a9899d747524e8aacd84 (1st revision)

### Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc 

```
sanitise tridactyllocal tridactylsync

" General Settings
set configversion 1.9
set update.lastchecktime 1592561460698

set theme maricn-base16-gruvbox-dark-hard
set colours maricn-base16-gruvbox-dark-hard
set smoothscroll true
set modeindicatorshowkeys true
set modeindicator false

" Binds
unbind <F1>
unbind <C-f>
unbind <C-a>
unbind .
unbind p
unbind s
unbind S
unbind D
unbind U

bind d scrollpage 0.5
bind u scrollpage -0.5
bind <C-d> scrollpage 0.7
bind <C-u> scrollpage -0.7

bind <C-[> back
bind <C-]> forward

bind i mode ignore
bind --mode=ignore <escape> mode normal

bind t tabnew
bind J tabnext
bind K tabprev
bind x tabclose
bind --mode=ignore ^ tab #

bind / fillcmdline find
bind n findnext
bind N findnext -1
bind <Escape> composite mode normal ; hidecmdline ; nohlsearch

bind --mode=ex <ArrowRight> ex.insert_completion

" For syntax highlighting see https://github.com/tridactyl/vim-tridactyl
" vim: set filetype=tridactyl
```

UPDATE: Added link to video demo.

**Comment by bovine3dom** [comment]
I thought we had an issue open about this already but I can't find it. Thanks for reporting :)

**Comment by maricn** [comment]
I think it's definitely after the tridactyl page gets opened, because i can see its text (black on white, as in default theme). Only after a brief moment of seeing it like that, the colourscheme kicks in and paints it black.

I'd prefer using tridactyl with newtab.. I was using it without it for a while but, I want to reap benefits of having it.. Thanks for the workaround suggestion in any case! ;)

**Comment by MyGitUsername** [comment]
@maricn Adding the following lines to your userChrome.css should shorten the length of the 'white background flash', but I don't think it will remove it completely:

```
#tabbrowser-tabpanels {
  background: #3838d !important;
}
```

**Comment by maricn** [comment]
> Note: I have userChrome.css tweak to change background color of about:blank and other browser tabs ([fedidat.com/640-dark-newtab-firefox](https://fedidat.com/640-dark-newtab-firefox/)). So, it's not that white background. And this issue is not present when tridactyl is out.


> @maricn Adding the following lines to your userChrome.css should shorten the length of the 'white background flash', but I don't think it will remove it completely:
> 
> ```
> #tabbrowser-tabpanels {
>   background: #3838d !important;
> }
> ```

**Comment by tklebanoff** [comment]
hi all,
I'm getting the same issue.  I am using the latest firefox 80.0.1

running 
:colors dark
helps quite a bit, because the new tab page becomes dark instead of all white.

*however* there is a jarring white flash whenever i click the + new tab button manually on the tab bar.

It sounds like a small issue, but when I use the computer at night, I feel like I am repeatedly frying my eyeballs.
By nightfall, I try to have everything pulled into my terminal workspace so I dont need to use the white flashing internet :/
So here we are around about 7:42 PM for me and I feel like Will Smith in I Am Legend two hours after sunset.

disabling tridactyl fixes the white flashing problem, but then i dont get to use tridactyl!

any help would be much appreciated.

**Comment by bovine3dom** [comment]
@tklebanoff if you use the no-newtab build mentioned above you can use Tridactyl without the flashing page, although you will lose our new tab page.

The root of this issue is very similar to #2839 - we don't know what your theme is until your configuration has loaded. We could use a similar approach to `:tabopen` and `:set newtab` where we open the page with your theme pre-baked into it, but that wouldn't work for Ctrl-T tabs. I think making the new tab page be black until configuration has loaded would be jarring to users using the default theme (which, I assume, is almost all of them). I suppose as a compromise we could use grey, but that might look weird and not help very much.

What do you all think?

**Comment by maricn** [comment]
> We could use a similar approach to :tabopen and :set newtab where we open the page with your theme pre-baked into it, but that wouldn't work for Ctrl-T tabs.

I think that would be helpful in any case.

Just one comment - if you play that attached [video from my original post](https://www.maricn.me/images/tmp/tridactyl-flashbang.ogv), and pause it at:
* beginning of 4th second, you can notice the page turns all gray. That's my `userChrome.css` `browser` entry.
* end of 4th second, the page turns all white. That's tridactyl being loaded with all white background
* beginning of 5th second, tridactyl loads the newtab content in default theme, still in white
* end of 5th second, tridactyl is fully loaded with my custom theme

Would the solution handle all of these steps, ie. middle two are specifically important?

> I think making the new tab page be black until configuration has loaded would be jarring to users using the default theme (which, I assume, is almost all of them). I suppose as a compromise we could use grey, but that might look weird and not help very much.

I don't want to comment on whether others would find it jarring, but just considering that most users use default colorscheme would be a reason enough against changing it to default black. I agree that gray or any other color would be strange.

**Comment by bovine3dom** [comment]
It would definitely get rid of steps 3 and 4. It would probably get rid of step 2 too, depending on how Firefox works.

It would be a moderate amount of effort to implement though so no promises (a data: URI might be easiest?).

**Comment by muusik** [comment]
This issue also affects me. I tried putting this in my userChrome.css:
```
:root {
    --tridactyl-bg: black !important;
    --tridactyl-fg: white !important;
}
```
But it didn't do anything. It might be because my userChrome.css is not being loaded at all -- it doesn't show up in style editor, even though I enabled toolkit.legacyUserProfileCustomizations.stylesheets and a few checkboxes in Developer Tools settings ("Show Browser Styles", "Enable browser chrome and add-on debugging toolboxes", and "Enable remote debugging"). You can let me know if I'm missing anything. But if it worked, shouldn't this override the options defined in default.css? Or is userChrome.css loaded after Tridactyl's default.css?

**Comment by bovine3dom** [comment]
http://kb.mozillazine.org/index.php?title=UserContent.css&printable=yes - I think you need to use userContent.css rather than chrome.

**Comment by muusik** [comment]
Oh, ok, well, that solves it for me. Now I have a <profile>/chrome/userContent.css file with content from my previous comment, and I no longer get a flash of any colour. Well, it goes from dark grey (default background colour based on the installed browser style) to black, which is less noticeable. Thanks for the tip, and thank you ever so much for your work on Tridactyl!

**Comment by bovine3dom** [comment]
You're welcome : )

I probably should have told people in this thread to use userContent.css a while ago...

**Comment by maricn** [comment]
@bovine3dom Thanks for mentioning `userContent.css`.. I've tried using it as well, but I don't think that's the problem I'm facing. When using `userContent.css`, nothing is different compared to my first post nor the description in my last comment above.

You can notice on the attached video - Tridactyl's content is first rendered in default colorscheme and only then the dark colorscheme is applied. I doubt that's handled by any Firefox customization?

**Comment by bovine3dom** [comment]
userContent.css is a bit like Stylish (the CSS fiddler) but it works on extensions. So you should be able to change Tridactyl's colours there. Have you tried muusik's four line userContent.css exactly?

**Comment by maricn** [comment]
> userContent.css is a bit like Stylish (the CSS fiddler) but it works on extensions. So you should be able to change Tridactyl's colours there. Have you tried muusik's four line userContent.css exactly?

Ahh, that works! Thank you both for help!

**Comment by polyzen** [comment]
Perhaps this should be documented until there's a better solution.

**Comment by maricn** [comment]
Just for the record, in case you're using the version without newtab, you should set the following in the `userContent.css` (not `userChrome.css`):
```css
/* 
   dark background in new tabs without a white flash (with tridactyl newtab)
   @see: https://github.com/tridactyl/tridactyl/issues/2510
*/
:root {
  --tridactyl-bg: #1d1b19 !important;
  --tridactyl-fg: white !important;
}

/*
    set the background color of the new tab page (without tridactyl or with tridactyl without newtab)
*/
@-moz-document url-prefix(about:home), url-prefix(about:newtab) {
  body {
    background: #1d1b19;
  }
}

/* 
    if you set it straight to body element, it will be applied to the random web pages 
    that don't explicitly set the background color of their body element
    (there's many of those online)
*/
/* body { */
/* background-color: #1d1b19; */
/* } */

```

**Comment by bovine3dom** [comment]
thanks @maricn. Should probably add that to https://github.com/tridactyl/tridactyl/commit/f6b8ce04f7cc6876baa8e5279179fb37a5d2ec98

**Comment by rodrigoaguilera** [comment]
Starting with Firefox 69, you need to set the toolkit.legacyUserProfileCustomizations.stylesheets preference to true in about:config due to https://bugzilla.mozilla.org/show_bug.cgi?id=1541233

**Comment by maricn** [comment]
If anyone experienced regression on new tabs, this _hacky_ solution in **userChrome.css** (not userContent.css) worked for me:
```
/* darken the background on newtab in newer versions 
 * of firefox (at least 118+, maybe since before) */
html#main-window body vbox#appcontent 
hbox.browserSidebarContainer.newTabBrowserPanel.deck-selected {
  z-index: -1; /* sideeffect: this will disable right click context menu on new tabs */
}
```

That goes together with [my previous comment](https://github.com/tridactyl/tridactyl/issues/2510#issuecomment-763198138).

ref: https://forums.mozillazine.org/viewtopic.php?p=14967509#p14967509
