### ISSUE TITLE
Opening a new tab opens two tabs

### ISSUE THREAD

**Issue by zwma** [tridactyl/tridactyl#2511]
Tridactyl version: 1.19.1pre4000-91fc4f6
Firefox version: Mozilla Firefox 77.0.1
Operating system: linux

*   Brief description of the problem:

I set newtab to a local html file. When I press ctrl+t or issue the tabopen command, first a blank Tridactyl tab opens, then a second later the local html file opens in a separate tab.

*   Steps to reproduce:

1. set newtab to a local html file
2. open a new tab

I haven't changed any other Tridactyl setting besides enabling smooth scroll.

**Comment by bovine3dom** [comment]
From `:help newtab`:

> All usual rules about things you can open with open apply, with the caveat that you'll get interesting results if you try to use something that needs nativeopen: so don't try about:newtab.

file:/// URIs need `nativeopen`. This is the interesting result promised. Do you think we should explicitly add "file:" URIs to that description?

IIRC, `data:` URIs do work so you can put your local page in as a one-liner through that, or use a lightweight webserver like `caddy` to host your page locally and then set your newtab to the relevant URL.

**Comment by dwma** [comment]
OK, understood!
I'll see about those suggestions, thanks!

**Comment by jeffeb3** [comment]
I'm hitting this ATM. The workarounds are:

data: will let you put all the data of the website into the url. This would mean the content of the page goes into the url?

webserver: Run a local web server to host the html/js and then open it with something like `http://localhost:8081`?

#297 also had this [hint](https://github.com/tridactyl/tridactyl/issues/297#issuecomment-364562448) to set another key to open a specific url in a new tab, which seems to be working.

**Comment by bovine3dom** [comment]
> will let you put all the data of the website into the url. This would mean the content of the page goes into the url?

Yes: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

also yes to your web server question : )
