### ISSUE TITLE
My (and any) custom theme doesn't load

### ISSUE THREAD

**Issue by maricn** [tridactyl/tridactyl#2535]
Tridactyl version: 1.19.1pre3928-53d0d18
Firefox version: Mozilla Firefox 78.0
Operating system: linux

*   Brief description of the problem:

My custom theme doesn't load. They used to work just a few days ago...

*   Steps to reproduce:

Create tridactylrc which references your custom theme.

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
https://gist.github.com/maricn/a86720274072a9899d747524e8aacd84 (2nd revision)

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):
```
sanitise tridactyllocal tridactylsync

" General Settings
set configversion 1.9
set update.lastchecktime 1592561460698

set theme maricn-base16-gruvbox-dark-hard
set colours maricn-base16-gruvbox-dark-hard
set smoothscroll true
set modeindicatorshowkeys true
set modeindicator false

" Binds
unbind <F1>
unbind <C-f>
unbind <C-a>
unbind .
unbind p
unbind s
unbind S
unbind D
unbind U

bind d scrollpage 0.5
bind u scrollpage -0.5
bind <C-d> scrollpage 0.7
bind <C-u> scrollpage -0.7

bind <C-[> back
bind <C-]> forward

bind i mode ignore
bind --mode=ignore <escape> mode normal

bind t tabnew
bind J tabnext
bind K tabprev
bind x tabclose
bind --mode=ignore ^ tab #

bind / fillcmdline find
bind n findnext
bind N findnext -1
bind <Escape> composite mode normal ; hidecmdline ; nohlsearch

bind --mode=ex <ArrowRight> ex.insert_completion

" For syntax highlighting see https://github.com/tridactyl/vim-tridactyl
" vim: set filetype=tridactyl
```

* Contents of my custom theme:

https://github.com/maricn/base16-tridactyl/blob/master/maricn-base16-gruvbox-dark-hard.css

* What I have tried:
  * All suggestions from https://github.com/tridactyl/tridactyl/issues/1214 - i debugged the `loadtheme` function and it finds and loads the file correctly, however hte theme is not applied.
  * `:composite js tri.styling.THEMES | fillcmdline` only shows builtin themes even though I have many themes in my `~/.config/tridactyl/themes/`

**Comment by glacambre** [comment]
On 2020-06-25 12:07, Nikola Marić wrote:
> set theme maricn-base16-gruvbox-dark-hard > set colours maricn-base16-gruvbox-dark-hard

I think these are wrong, it should be `:colorscheme 
maricn-base16-gruvbox-dark-hard`. Colorscheme has special handling that 
enables loading themes from disk.

Did you find the `:set theme`/`:set colours` commands in the 
documentation? If yes, where?

**Comment by maricn** [comment]
@glacambre I'm not sure, but I think it came from `mktridactylrc`. This is the diff with new `mktridactylrc!`. So I think, I just removed that looong embedded inline css as I thought that `set theme` and `set colours` commands will handle file lookup.
 
![flameshot_2020-06-25T13-52-38](https://user-images.githubusercontent.com/3995223/85714889-299dd200-b6eb-11ea-86fe-42bac4e76d50.png)

**Comment by bovine3dom** [comment]
One issue you've uncovered there is that `:mktridactylrc` needs to escape newlines.

**Comment by maricn** [comment]
After changing theme settings in rc file it seems to have picked up on it.. Thanks for suggesting that.

![flameshot_2020-06-25T14-24-38](https://user-images.githubusercontent.com/3995223/85719877-26f1ab80-b6f0-11ea-8e1a-fc319a63278a.png)

On the issue of not escaping newlines I have no clue, I'd personally prefer not dumping whole css file into rcfile, but that's not my call.. Maybe we can open a new issue for verbatim newlines?

**Comment by maricn** [comment]
i'm closing the issue as your proposed solution to use `colorscheme` works.. thank you!
