### ISSUE TITLE
:taball stopped working

### ISSUE THREAD

**Issue by m2habert** [tridactyl/tridactyl#2539]
Tridactyl version: 1.19.1pre4125-2d6c5dd
Firefox version: Mozilla Firefox 76.0.1
Operating system: mac

It used to work flawlessly.

But right now (I haven't noticed since when) ` :taball` eiter jumps to the wrong page or reports the error:

`# controller in excmd: Error: (intermediate value)[0] is undefined `

I guess this seems similar to #990 ?... Tried to "reset" windows and tabs by deleting all and opening new windows and new tabs, but :taball keeps bugged.

**Comment by bovine3dom** [comment]
```
d5192f6daccf55cf23e5dd0e0821a3aae8ed0a54 is the first bad commit
commit d5192f6daccf55cf23e5dd0e0821a3aae8ed0a54
Author: Oliver Blanthorn <freedom4cows@gmail.com>
Date:   Fri Jun 19 15:19:46 2020 +0100

    Re-enable `prefer-regexp-exec`

 .eslintrc.js            |  2 +-
 src/background.ts       | 30 +++++++++++---------------
 src/completions/Tab.ts  | 57 ++++++++++++++++++++++++++-----------------------
 src/excmds.ts           | 16 +++++++-------
 src/lib/dom.ts          | 12 +++++------
 src/lib/editor_utils.ts | 36 +++++++++++++++----------------
 src/lib/native.ts       |  6 +++---
 src/perf.ts             |  9 +++++---
 8 files changed, 84 insertions(+), 84 deletions(-)
```

**Comment by bovine3dom** [comment]
Sorry, I introduced this bug when I did some refactoring last week. Thanks for reporting it - it will be fixed in the latest betas.
