### ISSUE TITLE
`vimperator-reflow` hints behave very oddly

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#2548]
1. ~~`:set hintnames numeric`~~ not needed: `set hintchars 123457890`
2. `:set hintfiltermode vimperator-reflow`
3. `:open news.bbc.co.uk`
4. `f` - BBC in the top right is number 1
5. `1` - Your account is now number 1

Related: #2544

**Comment by m2habert** [comment]
One tempoary fix I noticed/came up with is to press `<BS>` (defaults to `hint.popKey` ) after `f` : it "resets" everything and hinting behaves normally.

`hint.pushSpace` also works.
