### ISSUE TITLE
[doubt or (weak) feature request] Possible to combine :hint 's -b(ackground) and -k(ill) options?

### ISSUE THREAD

**Issue by m2habert** [tridactyl/tridactyl#2552]
Well, I'll be the first one to admit that this one is neatpickish at best... But, just in case:

The `hint -k` option seems pretty cool, but I haven't come with a way to actually use it in a practical way. What would be interesting, it got me thinking, would be to, whenever exploring a search result page, simultaneously open a link on the background and "kill" same link on said page (it would be akin to "crossing out" an item on a list on paper).

   That, clearly, can be done with first commanding `:hint -b` and following it with `:hint -k`, which it's too much trouble for a small layout gimmicky result. But I'd call "guilty" to any charges of "overmapping" in a minute if  `:hint -bk` did work.

  I wonder if that can be achieved through the `-pipe` option, but I don't get the javascript logic yet.

In the end, it would be for a mainly "cosmetic" output, so I'm not confident to push it for serious consideration, but, still, I do wonder... ¿Is it doable?

Thanks

**Comment by bovine3dom** [comment]
I tried to reply to this yesterday morning but GitHub wasn't working :(

---

I don't think it's possible with -pipe as that stringifies things which are piped. You need access to the original element.

If we had a callback hint mode, e.g. `hint -wearerunningoutofflags [selector] ...callback` it would be quite straightforward as you can kill elements with `element.remove()`: https://github.com/tridactyl/tridactyl/blob/9d7b1107cd67abf98a5659a6f36c2cb5c4e14588/src/excmds.ts#L4076

**Comment by bovine3dom** [comment]
In the latest betas,

```
hint -JF e => {tri.excmds.tabopen("-b",e.href); e.remove()}
```

I'm not sure why we didn't do this earlier, it was quite easy.

**Comment by m2habert** [comment]
Wow, it seems awesome, thank!...

But... it didn't work. The link does not open as a new tab (`-b`), but within the same tab (as in `hint -f`). 

I halfway understand the logic (the "-b" is there as var for `tri.excmds.tabopen`), but I tried other flags with no success.

**Comment by bovine3dom** [comment]
It works for me on, e.g. `google.com`. Are you sure you're using a very recent beta? `:help hint` should mention

> -F [callback] - run a custom callback on the selected hint, e.g. hint -JF e => {tri.excmds.tabopen("-b",e.href); e.remove()}.

as the last bullet point in the parameters: option section, about 3/4 of the way down its little help section.

**Comment by m2habert** [comment]
version says : `1.19.1pre4165-8378acd`

I'm on auto update (tridactyl, not FFx) : ¿Should it not download the latest beta?

**Comment by bovine3dom** [comment]
`1.19.1pre4175-54a0492` is the version you need (the number after the `pre` tells you whether it is older or newer - bigger is newer). Firefox only updates addons about once a day and Tridactyl only updates after you restart Firefox.

If you go to about:addons, click Extensions on the left, click the cog, then click "Check for updates", wait a few seconds and restart, you should get the latest version.

(There's a slight complication where if Firefox has already downloaded an older update for Tridactyl, and it is waiting for you to restart Firefox, it will install that update rather than the latest one. If that's the case just do all the "Check for updates" steps again and you should then get the latest version for real).

**Comment by m2habert** [comment]
Oh, now I see. It's working now.

Sorry for the lameness here... Should have checked restarting. (But, the way Mozilla is so aggressive in pushing its updates, I've thought that the same would extend to extensions/plugins).

Thanks again!
