### ISSUE TITLE
ex-mode text _word movement commands don't work anymore

### ISSUE THREAD

**Issue by m2habert** [tridactyl/tridactyl#2572]
Tridactyl version: 1.19.1pre4197-27c5a03
Firefox version: Mozilla Firefox 76.0.1
Operating system: mac

The following :

 ` bind --mode=ex <C-'> composite text.beginning_of_line ; text.forward_word ; text.forward_word ; text.backward_kill_word` 

is useful to one-shortcut-fast edit  <search_term> in   `:tabopen -b <search_term> foo bar qux`
 ... and it used to work perfectly (I even noted that in #1790 ).

Not anymore, the error :
 `  # Error processing editor_function(backward_kill_word) Error: getWordBoundaries: no characters matching wordpattern ([^\s]+) in text (# Error processing editor_function(forward_word) Error: getWordBoundaries: no characters matching wordpattern ([^\s]+) in text (# Error processing editor_function(forward_word) Error: getWordBoundaries: no characters matching wordpattern ([^\s]+) in text (tabopen -b tv patton oswalt))) `    

shows up instead.

**Comment by bovine3dom** [comment]
I probably broke this in d5192f6daccf55cf23e5dd0e0821a3aae8ed0a54
