### ISSUE TITLE
throw "string" doesn't work

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#2580]
Should be `throw new Error("string"))`. Crops up in a few places.

**Comment by glacambre** [comment]
What doesn't work? You won't get a stack trace but the control flow will be affected the same way as with `throw new Error(…)`.

**Comment by bovine3dom** [comment]
In the command line you get "Error: undefined" rather than 'Error: "string"'. ("string" is usually a helpful error message")

**Comment by glacambre** [comment]
I think this is a problem with what is thrown, not using strings, as `:js throw "hello"` shows "hello" (but I still agree that using `new Error(…)` is better as it generates stack traces).

**Comment by bovine3dom** [comment]
https://github.com/tridactyl/tridactyl/blob/19eefd100b68b2e5f21cbf779bfa771630e3eb68/src/excmds.ts#L3369 e.g. gives me undefined but if I do a new Error( I get the message through.

Unless you mean that `throw [any non-error object]` is a bad idea. I was just being lazy with the string thing : )

**Comment by MyGitUsername** [comment]
I can work on this issue: refactoring the code base to replace `throw "string"` with `throw new Error("string")`.

**Comment by bovine3dom** [comment]
You can if you like - I'd just use `sed -i 's|throw "(.*)"|throw new Error\("\1"\)' **.ts` if I've remembered the syntax correctly :)

**Comment by glacambre** [comment]
Ah, indeed, errors are lost when passing from background to foreground, so e.g. `:jsb throw "hello"` prints undefined. But one interesting thing is that `:jsb throw {message: "hello"}` does print `hello`. I'd say this is a bug in Mozilla's error handling, but one they probably won't want to fix.

**Comment by bovine3dom** [comment]
Should add a precommit check that tests for this

**Comment by fluem** [comment]
Enabling ```no-throw-literal``` should take care of this, or am I missing a reason why it should not? 
https://github.com/tridactyl/tridactyl/blob/66d40a4a6f2e6410be300a05986cfa653cfc0481/.eslintrc.js#L222
Currently there seems to be only one occurrence.

**Comment by bovine3dom** [comment]
I hadn't heard of it. It sounds like it would fix it. PRs appreciated :)
