### ISSUE TITLE
excmd scrollpage 0.5 pops up command dialog with an error

### ISSUE THREAD

**Issue by maricn** [tridactyl/tridactyl#2583]
Tridactyl version: 1.19.1pre3928-53d0d18
Firefox version: Mozilla Firefox 79.0
Operating system: linux

## Brief description of the problem:

When using tridactyl on atlassian.net websites (JIRA, Confluence), scrollpage commands beyond borders (scroll up when page is at top and scroll down when page is already at its bottom) produce error message:
```
# controller in excmd: TypeError: can't access property "startsWith", treeWalker.currentNode.src is undefined
```

## URL of the website the bug happens on:

It's my company's JIRA and Confluence webpages at https://example.atlassian.net (sorry, those are closed access pages) 

## Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

https://gist.github.com/maricn/a86720274072a9899d747524e8aacd84 (revision 3)

## Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
sanitise tridactyllocal tridactylsync

" General Settings
set configversion 1.9
set update.lastchecktime 1593077346454
set smoothscroll true
set modeindicatorshowkeys true
set modeindicator false

" Theme
" set theme maricn-base16-gruvbox-dark-hard
" set colours maricn-base16-gruvbox-dark-hard
colourscheme maricn-base16-gruvbox-dark-hard

" Binds
unbind <F1>
unbind <C-f>
unbind <C-a>
unbind <C-d>
unbind <C-u>
unbind .
unbind p
unbind s
unbind S
unbind D
unbind U

bind d scrollpage 0.5
bind u scrollpage -0.5

" conflicts with <C-d> as "Bookmark this page"
" bind <C-d> scrollpage 0.7
" bind <C-u> scrollpage -0.7

bind <C-[> back
bind <C-]> forward

bind i mode ignore
bind --mode=ignore <escape> mode normal

bind t tabnew
bind J tabnext
bind K tabprev
bind x tabclose
bind --mode=ignore ^ tab #

bind / fillcmdline find
bind n findnext
bind N findnext -1
bind <Escape> composite mode normal ; hidecmdline ; nohlsearch

bind --mode=ex <ArrowRight> ex.insert_completion

" For syntax highlighting see https://github.com/tridactyl/vim-tridactyl
" vim: set filetype=tridactyl
```

## I've tried
I've also tried toggling iframe settings for my url per https://github.com/tridactyl/tridactyl/issues/639 but it  disables a lot of tridactyl (i can't bring up command box with `:`, although `gi` works  to find input).

## Screenshot
![image](https://user-images.githubusercontent.com/3995223/86606669-985f1300-bfa8-11ea-9531-35a557b9e50a.png)

**Comment by bovine3dom** [comment]
I've had a go at fixing this but I'm working blind. Let me know if the issue persists in the latest betas or after the next stable Tridactyl version is released.

**Comment by maricn** [comment]
Totally understand.. I thought just raising visibility of this issue can be useful.. Or if anyone has tips for me where to look (debug) for solution..

**Comment by bovine3dom** [comment]
@maricn see if it works in a beta version of Tridactyl (e.g. 1.19.1pre4234-d59de4d) as my first guess at a fix is in there :)

**Comment by maricn** [comment]
Ah, I found another page where this happens - [any reddit thread](https://www.reddit.com/r/firefox/comments/hn50ce/smooth_scroll_on_the_new_firefox_preview/) (only inside a thread, and after it fully loads).

And I tried using beta version - it works fine with beta! So I guess that solves it. Thank you!
