### ISSUE TITLE
tridactylrc does not seem to be running on firefox startup

### ISSUE THREAD

**Issue by caputchinefrobles** [tridactyl/tridactyl#2593]
Tridactyl version: 1.19.1pre3928-53d0d18
Firefox version: Mozilla Firefox 78.0
Operating system: linux Manjaro

*   Brief description of the problem:

I use my tridactylrc file pointing to two rc files depending on which profile I start firefox. It happens that I created a new profile but it doesn't seem to be running the rcfile on startup, unless I explicitly call :source. 

It doesn't create containers, it doesn't open tabs with composite command but It creates predefined commands there like `command test tabopen https://testurl`. It is the work rcfile that is not running.

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

.tridactylrc:
```
js tri.native.getProfile().then(p => p.absolutePath == "~/.mozilla/firefox/dgasdsgal-dev-edition-default" ? tri.excmds.source("~/.config/tridactyl/home") : tri.excmds.source("~/.config/tridactyl/work"));
```
.config/tridactyl/work:
```
unbind --mode=normal x

bind J tabprev
bind K tabnext
bind x. tabclosealltoright
bind x, tabclosealltoleft

colours greenmat

containercreate work orange briefcase
containercreate courses purple fruit

composite tabopen -c Work https://www.evernote.com | pin

command aws https://console.aws.amazon.com
```

**Comment by bovine3dom** [comment]
Has this ever worked? `js tri.native.getProfile().then(...` should be `jsb tri.native...` I think.

**Comment by caputchinefrobles** [comment]
> Has this ever worked? `js tri.native.getProfile().then(...` should be `jsb tri.native...` I think.

yes.. It worked and still works but only for the `true` part of the conditional. It actually was a very good suggestion made by @glacambre in #2411 

So the point is every time I open the default profile, tridactyl reads the home rcfile correctly, but when I start a different profile it doesn't trigger work rcfile anymore. 

Any suggestion in how I could debug rcfile calls? Should I change `js` to `jsb`?

**Comment by bovine3dom** [comment]
> Any suggestion in how I could debug rcfile calls? Should I change js to jsb?

I'd run `jsb` preferentially as `js` needs a tab in which Tridactyl can run in, which often won't be true at startup.

The easiest way to debug is to run them (the individual lines) via the Tridactyl command line with the web and background consoles open (ctrl-shift-{j,k}) and see what errors appear. You can also use console.log (with a promise, .then(p=>console.log(p)))

**Comment by caputchinefrobles** [comment]
`jsb` did work. Thank you.
