### ISSUE TITLE
:js window.open(url) crash the current tab 

### ISSUE THREAD

**Issue by pmaziere** [tridactyl/tridactyl#2596]
Tridactyl version: 1.19.1pre4222-d65fd5c
Firefox version: Mozilla Firefox 78.0.1
Operating system: linux

*   Brief description of the problem:

When I use the command: `:js window.open('https://example.com')` it crashes the current tab and firefox output the following messages:

```
IPDL protocol error: Handler returned error code!
###!!! [Parent][DispatchAsyncMessage] Error: PContent::Msg_CreateWindow Processing error: message was deserialized, but the handler returned false (indicating failure)
###!!! [Parent][MessageChannel] Error: (msgtype=0x39012E,name=PContent::Msg_CommitBrowsingContextTransaction) Channel error: cannot send/recv
###!!! [Parent][MessageChannel] Error: (msgtype=0x390146,name=PContent::Msg_CreateWindowContext) Channel error: cannot send/recv
###!!! [Parent][MessageChannel] Error: (msgtype=0x39012E,name=PContent::Msg_CommitBrowsingContextTransaction) Channel error: cannot send/recv
###!!! [Parent][MessageChannel] Error: (msgtype=0x39012E,name=PContent::Msg_CommitBrowsingContextTransaction) Channel error: cannot send/recv
```

When I type `window.open('https://example.com')` in the firefox console, it opens the site as expected.

EDIT: disabling all addons but tridactyl gives the same result

With a fresh profile, everything is fine.

Things used to work correctly some times ago, but I'm not able to say with which firefox version or tridactyl version

**Comment by bovine3dom** [comment]
I suspect this is a Firefox bug. It would be nice to be able to minimally reproduce it and report it upstream.
