### ISSUE TITLE
Switch to clipboard API

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#2597]
https://blog.mozilla.org/addons/2018/08/31/extensions-in-firefox-63/#content-main

Less hacky so will hopefully fix #1239 and https://github.com/tridactyl/tridactyl/issues/1135.

We'd need to ask for the `clipboardRead` and `clipboardWrite` permissions, so we should do this the next time we ask for more permissions, e.g. https://github.com/tridactyl/tridactyl/pull/2359.

**Comment by Rummskartoffel** [comment]
I started looking at this and noticed we have those permissions already, added by no-one other than yourself in c76d3a6 😜. I'll see if I can't get this clipboard API working.
