### ISSUE TITLE
No focus on address bar when open new tab in FF nightly version

### ISSUE THREAD

**Issue by KevCui** [tridactyl/tridactyl#2618]
*   Brief description of the problem:

There is no focus on address bar when open new tab in FF nightly version. It causes the inconvenience to type things in address bar right after new tab is open. I have to manually click address bar or ctrl+l to trigger the focus.

*   Steps to reproduce:

1. Download latest FF nightly 80.0a1 from https://ftp.mozilla.org/pub/firefox/nightly/2020/07/ and extract it

2. Open FF nightly and install tridactyl from FF add-ons store, version 1.19.1

3. Open new tab (ctrl-t)

In FF nightly 80.0a1 (2020-07-13), when open new tab (ctrl-t), no focus on the address bar.

However, I checked the current FF release version 78.0.2, the focus on the address bar works without any problem.

**Comment by bovine3dom** [comment]
Does `:set newtabfocus urlbar` make a difference?

**Comment by KevCui** [comment]
@bovine3dom no difference for me, `newtabfocus` has already the value `urlbar` unfortunately.

**Comment by bovine3dom** [comment]
It's a Firefox bug / feature, then. Perhaps they started work on https://bugzilla.mozilla.org/show_bug.cgi?id=1589987 ? More likely it's just a bug. Might be worth reporting to them :)

Related: https://github.com/tridactyl/tridactyl/issues/1122

Closing as not-my-fault.

**Comment by KevCui** [comment]
@bovine3dom thanks for the info!

**Comment by KevCui** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1596738 It's a FF issue, it looks like it should be fixed soon :pray:
