### ISSUE TITLE
Allow -u flag in config helper command autocontain

### ISSUE THREAD

**Issue by aureooms** [tridactyl/tridactyl#2620]
Tridactyl version: 1.19.1pre3928-53d0d18
Firefox version: Mozilla Firefox 78.0.2
Operating system: linux

# Making a feature request

It seems it is currently not possible to run `autocontain -u ... ...` in the `tridactylrc` file. One has to resort to call `js tri.config.set("autocontain", ..., ...)` (for instance, see https://github.com/aureooms/dotfiles/commit/1484052e13f6e50a26529b97f8b22852637b599d). Either it should be possible to pass the `-u` flag in the config file or this limitation should be documented.

**Comment by bovine3dom** [comment]
It's a very simple function - https://github.com/tridactyl/tridactyl/blob/dc8919e7e65d5dfa2398a14a18a8563a742832c1/src/excmds.ts#L3522 - so this is probably related to #1409

**Comment by aureooms** [comment]
Do you know if `autocontain -u ...` currently works in `tridactylrc`? Maybe I am just incorrectly escaping stuff.

**Comment by bovine3dom** [comment]
`:viewconfig autocontain` in Tridactyl to see if your containers are there.

It should work but RC files are a very hit and miss at the moment as documented in the issue I linked to above :)

**Comment by aureooms** [comment]
OK. I have no time to test now. `tri.config.set` worked first try. I'll close for now.
