### ISSUE TITLE
`:undo` is broken

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#2625]
Tridactyl version: 1.19.1pre4277-b40c0ea
Firefox version: Mozilla Firefox 78.0.2
Operating system: linux

Both the command and completions. An error is thrown here:
https://github.com/tridactyl/tridactyl/blob/b40c0ea24250b9c1d47feb20b0e89534f6e5a5e1/src/completions/Sessions.ts#L96

The error message is `Error: An unexpected error occurred`.

Can't get the background script to break on exception. Might be a firefoox bug.

**Comment by bovine3dom** [comment]
It's working ok for me. I'll check which versions I'm on when I'm next at my PC.

**Comment by bovine3dom** [comment]
Works fine for me on 1.19.1pre4277-b40c0ea + FF 78.0.2 :/

**Comment by glacambre** [comment]
No idea why but it works again.
