### ISSUE TITLE
`:viewconfig` doesn't work from Tridactyl special pages

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#2628]
The JSON viewer doesn't load for some reason. Probably a Firefox bug.

**Comment by h-khoza** [comment]
Hello, I'm also having problem, the extension doesn't work on the default "page not error”
For example, when I use the shortcut to go to a link, found out that link doesn't exist anymore, I can't navigate back using keyboard

**Comment by bovine3dom** [comment]
@h-khoza that is a decision that Firefox has made - Tridactyl can't run on those error pages. If you are using Tridactyl Beta you can press `<C-,>` (ctrl-comma) or `<C-6>` (ctrl-6) to return to a tab where Tridactyl works, or you can press `<C-[>` (ctrl-[ ) which is a built-in Firefox bind to go back to the previous page.

**Comment by h-khoza** [comment]
@bovine3dom thank you. I also want to contribute but is I don't know anything about building browser extension. Any advice on where I can start?

**Comment by bovine3dom** [comment]
https://github.com/tridactyl/tridactyl#building-and-installing and https://github.com/tridactyl/tridactyl/blob/master/contributing.md :)

**Comment by Rummskartoffel** [comment]
I've looked at this a bit and it's almost definitely a Firefox bug. When you load the page, Firefox tries to load in a script that's supposed to, in turn, load the JSON viewer, but it gets blocked by CSP.

**Comment by bovine3dom** [comment]
We fixed this in some crazy way a while ago. Can't remember exactly how

**Comment by Rummskartoffel** [comment]
In #3495, using `browser.tabs.executeScript()`, which for some reason prevents the relevant CSP error from occurring.
