### ISSUE TITLE
Add visual mode to the tutorial

### ISSUE THREAD

**Issue by dllud** [tridactyl/tridactyl#2639]
Thanks a lot for implementing the visual mode. Quite handy!

I guess it works good enough now to be shown to the world at large. Could you add it to the tutorial (`:tutor`)?

**Comment by bovine3dom** [comment]
With an impressive lack of foresight I numbered the tutorial pages. I suppose we can add it as e.g. 2.5-visual-mode.md.

https://github.com/tridactyl/tridactyl/blob/24988248627cbb90c5b07ed6e5308134e02376d5/src/static/clippy/1-tutor.md#L1 is the place to start.
