### ISSUE TITLE
Hint on labels

### ISSUE THREAD

**Issue by zouglou** [tridactyl/tridactyl#2646]
Tridactyl version: 1.19.1pre3928-53d0d18
Firefox version: Mozilla Firefox 78.0.2
Operating system: linux

I just started using Tridactyl recently, and found out I couldn't "clic" on labels tags with hint mode. Which seems pretty normal as they're not links, but it's an element usually clickable to then focus on another element (which, with tridactyl, we would directly focus on), but labels can be used for some other tricks too, for instance:

Make "fake" buttons to toggle an invisible checkbox, which depending on its status displays or not a div, in a "pure html/css" way, being no-js-friendly.

I've an example hosted here:
https://noizette.net/vrac/tridactyl.html

So, I don't know if this has already been discussed in the project, what do you think? Should labels be "hintable"?

**Comment by bovine3dom** [comment]
Seems reasonable to me. Added :)
