### ISSUE TITLE
Tildes.net next keybinding broken

### ISSUE THREAD

**Issue by SoptikHa2** [tridactyl/tridactyl#2668]
Tridactyl version: 1.19.1pre3928-53d0d18
Firefox version: Mozilla Firefox 78.0.2
Operating system: linux

On tildes.net, pressing `]]` to navigate to next page doesn't navigate to next page (button with text `Next`, but to contribution page with link `more details`).

**Comment by bovine3dom** [comment]
I don't think we'll ever get automatic detection of this working 100%. If you have any ideas please let us know :)

In the meantime, `seturl tildes.net followpagepatterns.next ^next` is our recommended workaround. 

If the site is popular we can add this as a default like we did for Google: https://github.com/tridactyl/tridactyl/blob/134bc4d1ee6fdffda425788cccda6eebbb099670/src/lib/config.ts#L82
