### ISSUE TITLE
`:tabopen` broken in FF80

### ISSUE THREAD

**Issue by MoSal** [tridactyl/tridactyl#2695]
Tested with fresh profiles.

## FF79

Works as expected.

## FF80b2

```
:tabopen bla bla
```
works

```
:tabopen search bla bla
```
works

```
:tabopen google bla bla
```
broken (default new tab window)

```
:tabopen https://google.com
```
broken (default new tab window)

---

`:open` does not suffer from the same issue.

**Comment by bovine3dom** [comment]
Release date is 25 August so getting this fixed and out in the wild is quite high priority.

**Comment by bovine3dom** [comment]
I can't reproduce this on a temporary profile - `firefox-developer-edition --profile (mktemp -d)`, only on my fat profile. And even then only sometimes.

:(
