### ISSUE TITLE
change base16 themes error

### ISSUE THREAD

**Issue by zxf-thingsmatrix** [tridactyl/tridactyl#2699]
Tridactyl version: 1.19.1pre3928-53d0d18
Firefox version: Mozilla Firefox 80.0
Operating system: win

when i execute command `colors base16-xxx`, it reply error like this
`# controller in excmd: Error: QuotaExceededError: storage.sync API call exceeded its quota limitations.`

![image](https://user-images.githubusercontent.com/65008815/89143159-20e5ba80-d539-11ea-914f-0a441a7a0306.png)

![image](https://user-images.githubusercontent.com/65008815/89143391-f21c1400-d539-11ea-89e5-ad365e87fbe9.png)

**Comment by bovine3dom** [comment]
Will be fixed by #2665 once it is merged.

**Comment by zxf-thingsmatrix** [comment]
thanks!

**Comment by zxf-thingsmatrix** [comment]
> 
> 
> Will be fixed by #2665 once it is merged.

thanks!
