### ISSUE TITLE
Why did Tridactyl grow by 30% on May 27?

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#2710]
https://tridactyl.cmcaine.co.uk/betas/ Tridactyl went from 4.3MB to 6.1MB at 27/05/2020, 13:15:17, tridactyl_beta-1.19.0pre3921-an+fx.xpi.

It's a bit annoying as we keep running out of space on the buildbot.

**Comment by glacambre** [comment]
Tridactyl started including 1024*1024 versions of the logo on that date. No idea why. We should probably remove all these PNGs from the repo and use the SVG instead. If for some reasons we really need PNGs at build time we can use the CopyWebPack plugin and [sharp](https://www.npmjs.com/package/sharp) to generate them (I do this in [firenvim](https://github.com/glacambre/firenvim/blob/ef514c8fad2907ac862a1ba6684208e9e04e3be3/webpack.config.js#L110-L114)).

**Comment by glacambre** [comment]
7221b68646572b72eee6c1849aaa3541ca3760c8 update copy-webpack-plugin on that day. Perhaps the default behavior of this plugin changed and started including whole directories?

**Comment by bovine3dom** [comment]
We need the small pngs for the manifest, I don't think that supports SVGs. We could move the big one and the PSD out of src/ to doc/ it maybe a new folder, assets/

**Comment by glacambre** [comment]
Firefox accepts SVGs in webextension manifests (but Chrome doesn't).

**Comment by bovine3dom** [comment]
Oh, it looks like it's simple: copy-plugin updated the ignore configuration and I didn't notice.
