### ISSUE TITLE
Modify cursor position after fillcmdline

### ISSUE THREAD

**Issue by hejops** [tridactyl/tridactyl#2719]
I'd like to highlight text and search for it using various search engines. How can I modify the behavior of `s`/`S` to achieve the following commandline prompt? (`_` = the cursor)

Default: `[tab]open search <highlighted text> _`

Desired: `[tab]open _ <highlighted text>`

**Comment by bovine3dom** [comment]
I'm not sure.

https://github.com/tridactyl/tridactyl/blob/134bc4d1ee6fdffda425788cccda6eebbb099670/src/lib/config.ts#L346

You might be able to do what you want by appending `; sleep 100; text.beginning_of_line ; text.forward_word` to that. So `:bind --mode=visual s`, copy what it gives you, stick the thing I gave you at the end of it and then bind to that. No promises it will work though :)

**Comment by hejops** [comment]
Neat workaround, thanks. Can `fillcmdline` be made to output two "internal" spaces? With an extra space between `[tab]open` and `<text>`, I might be able to save one more keypress...

I understand that's probably a moot point, though, since there seems to be no `text.forward_character` command.

**Comment by bovine3dom** [comment]
Perhaps `composite js " " + document.getSelection().toString()`? Then text.forward_char

**Comment by hejops** [comment]
Ah, so it's `forward_char`. Works great!

**Comment by bovine3dom** [comment]
Closing as I don't think we could make this much more ergonomic than the solution posted - which, for the benefit of future searchers was:

`bind --mode=visual s composite js " " + document.getSelection().toString() | fillcmdline open search; sleep 100; text.beginning_of_line; text.forward_word; text.forward_char`
