### ISSUE TITLE
Quota exceeded when quickmarking

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [tridactyl/tridactyl#2732]
**First and foremost: my deep thanks for the extension and your work on it. Really, it's very pleasing to use and I'm glad to have found it and for you to pick up the ball when extensions were being axed left and right by FF (version 56 AFAIK). You guys are really great and I'm grateful for the time you spent on the tool.**
:heart: 

Tridactyl version: 1.19.1pre3928-53d0d18
Firefox version: Mozilla Firefox 79.0
Operating system: linux

# Reporting a bug / getting help

Fingerprint resisting (Mozilla FF setting) set as your troubleshooting page recommends it. Not a website issue AFAIK, appears on mutliple websites, but I tried also on a site without iframes. So far I think it's the issue with storage, rather straightforward. Not being very well acquainted with JS (and not at all with TS) I'm having a bit of trouble diagnosing it better. My very initial hypothesis is "local storage limit with large number of quickmarks, repeated due to go, gn, gw". So, if I quickmark this page, I'll need to have 3 entries with the URL. Not trying to mislead you here, that's something I picked up after reading a bit about localstorage etc. Couldn't find the local storage entries related to quickmarks in FF (using FF's console interface to it). Have deleted the pages cache - didn't help at all.

Issue appears both in priv or normal modes of my FF.

*   Brief description of the problem: adding a quickmark via `:quickmark (` doesn't set the quickmark, instead:

1. error message appears: `# controller in excmd: Error: QuotaExceededError: storage.sync API call exceeded its quota limitations`. 
2. in Ctrl+Shift+j console log, I see the messages as per image.

![image](https://user-images.githubusercontent.com/1167811/89909323-3ae56400-dbef-11ea-923b-fd086cd98071.png)

In case the image's gone, the most related message (and the topmost as well) is: `Error: CallResult for closed conduit tridactyl.vim@cmcaine.co.uk.1099511629789: ({childId:"tridactyl.vim@cmcaine.co.uk.1099511629789", callId:1099511629810, path:"storage.sync.get", result:{}}) ConduitsChild.jsm:167:13
    receiveMessage resource://gre/modules/ConduitsChild.jsm:167`

FF's console brings me to: view-source:resource://gre/modules/ExtensionStorageSync.jsm, namely error raising, so nothing interesting.

*   Steps to reproduce:

    1.  quickmark things
    2.  at some point quickmark stopped working - honestly don't know more specifics

It may be worthwhile that I'm reusing same set of quickmarks to mark my progress while reading. So, I'm frequently re-quickmarking the same quickmark. Even 5 times a week.

*   URL of the website the bug happens on: number of them, including this one, Google search etc.

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com): I didn't configure this much, if at all. Changed the theme. Set a number of quickmarks. I'm still learning Tridactyl. Reluctant to post config as there seems to be a lot to digest there and I dislike sharing things without understanding what I am sharing. :-)

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist): they do not.

Tridactyl native app was NOT installed.

Again, thank you VERY much for your work here. Let me know if I can help.

**Comment by bovine3dom** [comment]
Thanks for filling this issue. I'm glad you like Tridactyl.

We have stopped using the sync storage in Tridactyl 1.20 in part for this reason - #2655. Could you try updating? Go to about:addons, click the cog, click check for updates, wait e.g. 30 seconds (not forever as Firefox would imply), restart Firefox.

You'll then have to wait 5 seconds or so while your configuration is migrated. That apparently doesn't work for everyone - try `:firefoxsyncpull` if it looks like everything has been reset to default.

**Comment by LIttleAncientForestKami** [comment]
Thank you @bovine3dom - will update once I test as to do so I need to resolve my new problem: while there's a new version available on the update site my FF claims there's no new updates for addons.  :-)

**Comment by bovine3dom** [comment]
You probably just need to restart Firefox. If you aren't on the latest version, update again and then restart again :)

**Comment by LIttleAncientForestKami** [comment]
And you were absolutely right Oliver. Merci beacoup mon ami. 

Updating to Tridactyl 1.20 and restarting FF was all it took for the issue to be resolved.
