### ISSUE TITLE
Unbind seems to have no effect

### ISSUE THREAD

**Issue by wbthomason** [tridactyl/tridactyl#2735]
Tridactyl version: 1.20.0pre4432-f5670ace
Firefox version: Mozilla Firefox 79.0
Operating system: linux

*   Brief description of the problem:
Running `:unbind <C-f>` does not remove the default binding for `<C-f>`

*   Steps to reproduce:

    1. Run `:unbind <C-f>`
    2. Observe that `<C-f>` still scrolls the page rather than opening "find in page"

*   URL of the website the bug happens on:

Every website

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

https://gist.github.com/wbthomason/5cffa39bf6c8fb1a48ccd3a7296789bd

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

N/A

**Comment by bovine3dom** [comment]
`configversion: 0.0` is a bit strange. Could you try running `:jsb tri.config.update()`?

**Comment by wbthomason** [comment]
Sure! Unfortunately, that seems to do nothing - I get no output from the command (in browser or console), and it doesn't change the null effect of `unbind`.

**Comment by bovine3dom** [comment]
Hmm. Could you go to about:debugging, click this Firefox, click Inspect next to Tridactyl, click the console tab, run unbind again in another tab and see if any errors appear?

You could also play with browser.local.get / set in that console and see if anything looks dodgy.

**Comment by wbthomason** [comment]
Even before running `unbind`, I see a lot of this error:
```
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    u moz-extension://a81ec133-d1f2-4a49-b607-9ecf573fbd37/background/background.js:1
```
However, I don't get any new errors after running `unbind`.

On a hunch, I'm going to try restarting FF (though I think I've done that since this problem started?) and see if that fixes things; I'm wondering if the native client (which I have installed via a system package, on Arch Linux) was updated since I last restarted Firefox, which maybe would cause the connection errors I'm seeing?

**Comment by wbthomason** [comment]
Yup, that did it. I thought I had already restarted while seeing this issue, but maybe I missed a second update? Either way, the problem seems resolved. Thank you!

**Comment by bovine3dom** [comment]
Those errors aren't anything to worry about - it's just saying that we tried to run in a tab where we aren't allowed to run, IIRC.

Glad it got resolved.
