### ISSUE TITLE
Cannot bind a keystroke

### ISSUE THREAD

**Issue by vonpupp** [tridactyl/tridactyl#2744]
Hello Dr,

Herewith the completion of the requested data.

*   Brief description of the problem: I am trying to use tridactylrc to bind a keystroke but it doesn't work.

*   Steps to reproduce:

See the tridactylrc file for more details

*   Tridactyl version (`:version`): 1.20.1pre4473-2d34a79d (latest from beta channel)

*   Firefox version (Top right menu > Help > About Firefox): 79.0 (64-bit) [Archlinux]

*   URL of the website the bug happens on: github.com

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
bind ,c js javascript:location.href = 'org-protocol:/roam-ref?template=r&ref=' + encodeURIComponent(location.href) + '&title=' + encodeURIComponent(document.title)
```

I also tried this, and it didn't work either
```
bind ,i composite hint -pipe img src | exclaim_quiet feh
```

I thought it might be related to my firefox profile which is "hardened" for privacy purposes, so I tried on a separate fresh profile but I got the same results.

*   Operating system: Archlinux
*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:
Nothing happened from within firefox but on the terminal the value is:
```
/home/av/.asdf/shims /opt/asdf-vm/shims /opt/asdf-vm/bin /opt/android-sdk/platform-tools /opt/android-sdk/tools/bin /opt/android-sdk/tools /opt/android-sdk /opt/flutter /home/av/.gem/ruby/2.5.0/bin /home/av/node_modules/.bin /home/av/perl5/bin /usr/bin /home/av/.luarocks/bin /usr/local/bin /home/av/.local/bin /home/av/bin /home/av/.local/bin /home/av/bin /opt/asdf-vm/shims /opt/android-sdk /opt/flutter /home/av/.gem/ruby/2.5.0/bin /home/av/node_modules/.bin /home/av/perl5/bin /usr/bin /home/av/.luarocks/bin /usr/local/bin /home/av/.local/bin /home/av/bin /home/av/.local/bin /home/av/bin /usr/local/bin /usr/local/sbin /usr/bin /opt/android-sdk/tools /opt/android-sdk/tools/bin /opt/flutter/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl
```
*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:
/home/av/.local/share/tridactyl/native_main.py: No such file or directory

In fact the folder /home/av/.local/share/tridactyl is empty.

Thanks and congratulations on Tridactyl, awesome software!

**Comment by bovine3dom** [comment]
I suspect binding is working fine for you, but you're binding to things that don't work. It's always a good idea to make sure your command works before you bind to it. E.g. rather than `bind ,c js ...` run `js ...` and check that it works.

`bind ,c js window.location.href = 'org-protocol:/roam-ref?template=r&ref=' + encodeURIComponent(window.location.href) + '&title=' + encodeURIComponent(document.title)` has a better chance of working (untested).

For your second command, I think you don't have our native messenger installed. Follow the instructions from `:nativeinstall` to get that up and running.

**Comment by vonpupp** [comment]
Thank you very much Dr.

Your binding command worked. Awesome work with tridactyl, thank you very much!
