### ISSUE TITLE
Tridactyl breaks for the current tab when piping commands that use fillcmdline into yank or clipboard yank

### ISSUE THREAD

**Issue by Rummskartoffel** [tridactyl/tridactyl#2749]
Tridactyl version: 1.20.1
Firefox version: Mozilla Firefox 79.0
Operating system: win

*   Brief description of the problem: when using `composite` to pipe into `yank` or `clipboard yank`, Tridactyl breaks for the current tab until it is reloaded. It will still work on other tabs, but switching away from the broken tab and back again doesn't fix it.

*   Steps to reproduce:

    1. run a command such as `:composite get searchurls.google | yank`
    2. try to use any key binding (including `<C-,>`) or run any command

*   URL of the website the bug happens on: happens everywhere

*   Config: https://gist.github.com/Rummskartoffel/43a4ab6054be554ca29314727bab660b

**Comment by bovine3dom** [comment]
I keep forgetting to check if I can reproduce this. Apparently I don't look at the "needs review" label as often as I thought

**Comment by bovine3dom** [comment]
I can reproduce this but I think the blame should be shared equally between Tridactyl and you : )

Tridactyl shouldn't break when you do it, but you shouldn't be doing this - `get` is meant for interactive usage and opens the command line with the result. The return value of it is not meaningful.

The way to do what you want to do is via `js`:

```
composite js tri.config.get("searchurls","google") | yank
```

Note that where there was a `.`, we have split the arguments.


---

We could add a warning to `get`'s documentation. I think trying to stop Tridactyl from breaking might be too big an ask...

**Comment by Rummskartoffel** [comment]
I don't think just telling users not to do it is the right way of dealing with this. At the very least, the command should display an error message, but after taking a quick look at the code, I think making `get` pipeable shouldn't be too hard. I'll try and come up with something.

**Comment by bovine3dom** [comment]
Making get return a result wouldn't be hard. The thing that's hard (and I think the thing that's breaking stuff) is that `yank` uses the command line to copy things, so if you're trying to use the command line to display something at the same time, weird things will happen.

#2597 covers stopping `yank` from doing that.

**Comment by Rummskartoffel** [comment]
Oh, now I see. In that case, this issue isn't specific to `get`, but happens more generally with piping `fillcmdline` or any command that uses `fillcmdline` into `yank`. I've tried it, and `composite fillcmdline abcde | yank` has the same effect as using `get`.

**Comment by bovine3dom** [comment]
It might also be more general than the yank command - it could be any command that opens the command line piped into another command that opens the command line. So while fixing #2597 would fix yank, `composite fillcmdline this kills the | fillcmdline tridactyl` might still cause trouble.

**Comment by Rummskartoffel** [comment]
> 
> 
> It might also be more general than the yank command - it could be any command that opens the command line piped into another command that opens the command line. So while fixing #2597 would fix yank, `composite fillcmdline this kills the | fillcmdline tridactyl` might still cause trouble.

Interestingly, when I tried that command, it worked without issue. Looks like the second `fillcmdline` somehow resets it. And `composite fillcmdline abc | yank | fillcmdline def` works as well – useful if you want your clipboard to contain ",,,,,,,,,,,,,,,,".

**Comment by bovine3dom** [comment]
Ah, well that's easy then - this issue is mostly a dupe of #2597, with the addition that `get` should return something useful.

**Comment by Rummskartoffel** [comment]
Trying this out again, #3078 seems to actually have fixed this. Of course, `:fillcmdline` still returns garbage, but at least it doesn't seem to break anymore.
