### ISSUE TITLE
`:tabopen<CR>` doesn't focus on URL bar

### ISSUE THREAD

**Issue by lewurm** [tridactyl/tridactyl#2760]
Tridactyl version: Tridactyl 1.20.0pre4432-f5670ace
Firefox version: Mozilla Firefox 80.0
Operating system: mac

Tridactyl 1.19.1pre3928-53d0d18 _does_ focus on the URL bar as expected, and 1.20.0pre4432-f5670ace is the first version (that is available via firefox addons) that does _not_ focus on the URL bar.

Context: I often end up using `:t -c mycontainer<CR>` because the `-c mycontainer` part isn't ignored by the Tridactyl suggestion lookup, and thus kinda useless. Ideally that would be fixed, but now I'm used to that workflow 🙂

**Comment by bovine3dom** [comment]
We did this on purpose in #1974 / #1122 - I suppose if left long enough, any bug eventually becomes a feature.

![https://xkcd.com/1172/](https://imgs.xkcd.com/comics/workflow.png)

---

I don't understand 

>  I often end up using :t -c mycontainer<CR> because the -c mycontainer part isn't ignored by the Tridactyl suggestion lookup, and thus kinda useless.

`mycontainer` should be ignored there and is in my testing.

IIRC it's slightly tricky to return the focus to the URL bar. I'd prefer it if we could fix the things that make you want to use the normal address bar :)

**Comment by lewurm** [comment]
haha, I had that xkcd in mind when I was writing the issue 😄 

I guess using `:t` just ended up in my muscle memory for no good reason. I'll keep my eyes on https://github.com/tridactyl/tridactyl/issues/2761 and try to rewire my brain to just use `t` instead in the meantime.

Thank you for the fast response!
