### ISSUE TITLE
Are extension provided comands from Firefox omnibox accessible?

### ISSUE THREAD

**Issue by whnr** [tridactyl/tridactyl#2768]
Tridactyl version: 1.20.1pre4505-ce048e84
Firefox version: Mozilla Firefox 79.0
Operating system: linux

Is there a way to access short cuts like this one that is provided by lastpass:
![image](https://user-images.githubusercontent.com/8114817/91561319-65326380-e909-11ea-99e5-6732d1cf88bc.png)

When I type `lp ` I have immediate access to my saved passwords. I seem not to be able to do the same with tridactyl.

**Comment by bovine3dom** [comment]
I don't think so. If lastpass provided an API it would be possible, but we'd have to do it for every single extension.

We could ask Mozilla to allow us access to the omnibox but I suspect the answer would be no.

**Comment by whnr** [comment]
Thank you. Lastpass does have a cli, but that is separate from the Browser extension. Thank you.

**Comment by bovine3dom** [comment]
You can access the CLI via `:exclaim ` if you have `:native` installed
