### ISSUE TITLE
Dark mode newtab page

### ISSUE THREAD

**Issue by samuela** [tridactyl/tridactyl#2774]
Tridactyl version: 1.20.1
Firefox version: Mozilla Firefox 80.0
Operating system: linux

Feature request: dark mode for the new tab page. The new tab page is really harsh on the eyes at night. A dark mode would be great!

**Comment by glacambre** [comment]
On 2020-08-30 21:50, Samuel Ainsworth wrote:
> Feature request: dark mode for the new tab page. The new tab page is 
> really harsh on the eyes at night. A dark mode would be great!

Have you tried `:colorscheme dark`? It should make the newtab page dark. 
If you want to keep a white tridactyl UI but with a dark newtab page I'd 
recommend creating a custom theme, taking inspiration from the themes 
that can be found here:

https://github.com/tridactyl/tridactyl/tree/master/src/static/themes

**Comment by samuela** [comment]
Awesome, I wasn't aware of the `:colorscheme dark` option. Would it be possible to add that to the new tab page then? I feel like that'd be a useful tidbit of knowledge for newcomers.
