### ISSUE TITLE
escapehatch closes side-panel like TreeStyleTabs

### ISSUE THREAD

**Issue by oxysoft** [tridactyl/tridactyl#2775]
Love the new browser wide shortcuts and the built-in `<c-,>`, it was about time! Only problem is that the `escapehatch` command associated with `<c-,>` also forces any side panel to close instead of just ensuring the page has focus. Naturally, I'm not sure if this is simply a current limitation with what can be done.

Tridactyl version: 1.20.1pre4511-18fd6a36

**Comment by bovine3dom** [comment]
I imagine you're only allowed one sidebar open at once. We could add a preference that disables it but it would make it less useful - in particular you wouldn't be able to get focus back from the address bar to the page. Would it still be worthwhile?

**Comment by bovine3dom** [comment]
(For those who don't follow Tridactyl's development intimately: we open and close a dummy sidebar quickly to grab focus from the address bar back to the page. It's a dumb hack making use of what is probably a Firefox bug but it made my life better)

**Comment by chaoyi** [comment]
For me address bar is disabled via userChrome.css, having the option to keep the side bar open is even better.

**Comment by oxysoft** [comment]
Sorry for the late reply. I suppose this is better than nothing for now, but let's hope Mozilla offers a better way to do this in the future.

**Comment by bovine3dom** [comment]
I actually meant to add the preference today but forgot as soon as I opened my laptop ... if anyone fancies doing it you just need to move these two lines into a conditional on a config.get: https://github.com/tridactyl/tridactyl/blob/5e8f94ff06bd5f143732f2dabd32b08dabf1e65a/src/background/user_actions.ts#L13

Happy to help on Riot or here. Otherwise you'll have to wait for me to remember to do it : )

**Comment by oxysoft** [comment]
Perhaps it would be possible to re-open the last side panel, or at least a user-configurable default? Tree Style Tabs for example adds its own shortcut on F1 to open its side panel.

**Comment by bovine3dom** [comment]
No, we can only open our own sidebar. Extensions can't add an API that lets other extensions open their sidebars so there's no possible case-by-case workaround that I can see either.

**Comment by bovine3dom** [comment]
`:set escapehatchsiderbarhack false` in the latest betas (available when this post is approx 10 minutes old)

**Comment by chaoyi** [comment]
Thank you.  It's perfect.

**Comment by DivineMK** [comment]
A solution for this to me is bind F6 globally (to Ctrl+Shift+; personally). For escapehatch replacement I do this keybindings twice to unfocus iframes.

**Comment by bovine3dom** [comment]
That's a really good idea, if you want to avoid TST closing

`bind --mode=browser <C-.> composite !s xdotool key F6; !s xdotool key F6; escapehatch` 

works great if you have xdotool + :native installed and working :)

**Comment by DivineMK** [comment]
Thanks for reminding me of the browser wide mode so I can avoid global keybindings! Personally, I don't want to have to use another keybindings for escapehatch. 
Would you mind showing me how to bind Ctrl+Shift+; to composite !s xdotool key F6; escapehatch?
I tried <CS-;> and <C-S-;> but they have errors.

**Comment by bovine3dom** [comment]
> Is this because the colons and quotes symbols keys are not supported by firefox keybindings? I tried to setting these to extensions keybindings and they don't seem to work.

Apparently they are unsupported by the WebExtension command API which we use for browser-wide binds. Which binds are and are not allowed seems to be undocumented.

> I wonder how tridactyl still manage to support : and ;.

The other modes use the Web KeyEvent API which is a totally different API. It supports more keys (I think a superset but, again, undocumented so don't quote me on that) but not all of them.

Keybinds are an unloved part of Firefox :( I'd say about half of my friends were born after this bug was filed: https://bugzilla.mozilla.org/show_bug.cgi?id=57805

**Comment by DivineMK** [comment]
I see. I tried binding to <C-\> but the error still comes up even though it is documented here as a suggestion in bind help page.
![image](https://github.com/tridactyl/tridactyl/assets/42614396/95750e20-4ca1-4e96-8eb5-c1685c26b1f0)

**Comment by bovine3dom** [comment]
Hmm, I think that used to work, let me check in a few hours

**Comment by bovine3dom** [comment]
It works fine for me @DivineMK in everything except browser mode :eyes:

**Comment by DivineMK** [comment]
That's unfortunate. I'll settle with <C-,> 🙂

**Comment by bovine3dom** [comment]
in FF149+ browserAction.openPopup() is now available without a user action but opening it then closing it with `window.close()` doesn't return focus to the page so it is useless to us :(
