### ISSUE TITLE
bmarks command opens as search rather than matching bookmark

### ISSUE THREAD

**Issue by nwilleyltk** [tridactyl/tridactyl#2776]
*   Brief description of the problem:  bmarks command opens search page instead of matching bookmark

*   Steps to reproduce:

    1. Type :bmarks to invoke the bmarks command
    2. Search for a known bookmark  
    3. When it is the only bookmark shown, type the enter key
    4. On my computer the duckduckgo search page opens with my search term instead of the bookmark

*   URL of the website the bug happens on: N/A

**Comment by nwilleyltk** [comment]
[Config as Gist](https://gist.github.com/nwilleyltk/0e12418e6fe958a6aa6465150943d595)

**Comment by bovine3dom** [comment]
Thanks for telling us about this bug :)

We simply need to preselect a bookmark as we do with `:tabs`.

**Comment by bovine3dom** [comment]
This was fixed #2863 :)
