### ISSUE TITLE
Improve hinting

### ISSUE THREAD

**Issue by cmcaine** [tridactyl/tridactyl#28]
## Basic components

It's own mode. Most code in content script, driven by excmds.

 - Iterable of visible links on page
 - Algorithm for choosing hint characters for each link
 - Mode for controller and excmd to refine and select hints:
     - I imagine `:hint` to start 
     - `:hint j` to refine to only hints starting with j
     - `:hint jk` to refine to hints starting with jk
     - To make maps easier we can have `:hintaddchar j` and have the state of the current hintstr stored content-side.

## Improvements

Hinting submodes should be programmable on both:

 1. What is hinted (links, anchorpoints, frames, input elements, etc)
 2. What is done with the selected link (follow, yank, focus)

## Vimperator hint modes:

`:help` hinttags

```
string(default: //input[not(@type='hidden' or @disabled)] | //xhtml:input[not(@type='hidden')] | //a | //xhtml:a | //area | //xhtml:area | //iframe | //xhtml:iframe | //textarea | //xhtml:textarea | //button | //xhtml:button | //select | //xhtml:select | //\*[@onclick or @onmouseover or @onmousedown or @onmouseup or @oncommand or @role='link'or @role='button' or @role='checkbox' or @role='combobox' or @role='listbox' or @role='listitem' or @role='menuitem' or @role='menuitemcheckbox' or @role='menuitemradio' or @role='option' or @role='radio' or @role='scrollbar' or @role='slider' or @role='spinbutton' or @role='tab' or @role='textbox' or @role='treeitem' or @tabindex])
        
XPath string of hintable elements activated by f and F
```

Extended hint modes:

```
;  Focus hint 
?  Show information for hint 
s  Save link 
S  Save object 
a  Save link with prompt 
A  Save object with prompt 
f  Focus frame 
o  Follow hint 
t  Follow hint in a new tab 
b  Follow hint in a background tab 
w  Follow hint in a new window 
F  Open multiple hints in tabs 
O  Generate an ':open URL' using hint 
T  Generate a ':tabopen URL' using hint 
W  Generate a ':winopen URL' using hint 
v  View hint source 
V  View hint source in external editor 
y  Yank hint location 
Y  Yank hint description 
#  Yank hint anchor URL
c  Open context menu 
i  Show media object 
I  Show media object in a new tab 
x  Show hint's title or alt text
```

Blocks #24

**Comment by cmcaine** [comment]
Basic hinting is in as of 927e19c818ab299aaed6ea547611c8cd62dc5a76

Architecture is reasonably extensible for PRs and for when we support user JS.

excmds to filter the hint turns out to seem really weird, so I've left it out.

**Comment by robertgzr** [comment]
Currently hints can be either a single letter for the topmost links on a site or two letters if there are many...
If I want to follow a link behind a single letter hint I need to press the letter + enter.
All other vim addons for ff I have used showed you only two letter hints and thus did not require the extra enter.

**Comment by cmcaine** [comment]
I've written code to do uniform length hints, but it's not used by default. 

I was also thinking of setting space to be select completion, which would probably be my preferred solution.

Another possibility is to display a mix of lengths, but have no hint be a prefix of another one.

Thanks for your comments. We'll experiment and see what works best and all sensible options will be exposed as options.

**Comment by meh** [comment]
One thing I always use in Vimperator is the fact you can type parts of the link text being hinted to further filter the hints, and if there's only one hint then it would go to it directly.

**Comment by bovine3dom** [comment]
That's on the todo list too. We were discussing it on Matrix earlier today : )

**Comment by thejukra** [comment]
As a very happy Tridactyl user, I would appreciate a lot if 'F  Open multiple hints in tabs' would work like this:
- On a page 'A' user types F
- Every link in page is hinted
- User types in a hint that is valid in a page
- the hinted page user typed in will be opened in background tab
- the page 'A' is still in focus, and every link in page 'A' is hinted
- user types in another hint -> the hinted page will be opened in background tab, ..., ...

This would be very useful for different discussion forums and news pages where one can open desired links on one go to the background and the go on and read them one tab at a time. I think this was ;F in Vimperator. 

Thanks for you efforts so far! Tridactyl is really lifesaver for me both in work and free time now that vimperator has gone for good.

**Comment by bovine3dom** [comment]
It is on our todo list : )

**Comment by thejukra** [comment]
Ok, that's great news! I'll then sit tight and wait :)

**Comment by bovine3dom** [comment]
Additionally, I would like us to have rapid variants of all hint modes where it makes sense, especially "save link content" once we have it.

**Comment by bovine3dom** [comment]
From #111:
> It could be sensible to look at colouring elements that are partially contained within another element different colours.

It would be especially useful for `;p`.

**Comment by bovine3dom** [comment]
VimFx let you cycle which hints were on top. Probably useful.

**Comment by cmcaine** [comment]
Per @robertgzr suggestion, I changed tridactyl to uniform length hints a little while ago (1.5.0?)

**Comment by petr-tik** [comment]
I find SurfingKeys' hint [generation algorithm ](https://github.com/brookhong/Surfingkeys/blob/master/content_scripts/hints.js#L186-L210) better. If I understand it correctly, it uses chars from left or right handside of the keyboard to make it easier for different people

**Comment by cmcaine** [comment]
@petr-tik Does surfingkeys just only use characters from the left or right side?

If so, you can emulate that with something like `set hintchars asdfqwerzxcv`

**Comment by dkasak** [comment]
It would be useful if `<tab>` cycled the currently selected hint, if there are still multiple options left.

**Comment by bovine3dom** [comment]
Rapid hinting added in 4a5a25c. Bound to `gF`; excmd `hint -br`.

Barely tested. Sometimes crashes the "message manager", but it doesn't seem to break anything...

**Comment by bovine3dom** [comment]
`gF` is working exactly as one might expect when there is only a single link visible. It certainly lives up to its "rapid" name. I doubt this is what users will expect, though.

One potential fix is to store the last href and exit if the next one matches. You'd still get two tabs but that's probably better than ~50 before you work out what's happening.

**Comment by phmarek** [comment]
> Algorithm for choosing hint characters for each link
I'd really like if the character used for a link would be more stable; perhaps (if still available) the first character of the link text or so.

Eg. when browsing some web comics, the "next" link gets to have different characters associated - that means that to go to the next page, `F` then look at the link again `K` - oh no, that was the wrong one, move back `H` - which one was it - `F` `L` happens every now and then.

The hinting mode in konqueror was more stable, it used the first character IIRC.

Thanks!

**Comment by bovine3dom** [comment]
Have you tried `]]` instead? If it doesn't work on a specific page you can fix it with `seturl [URL] followpagepatterns.next [whatever text appears on the link]`.

**Comment by phmarek** [comment]
Ah no, didn't know that yet. Thanks, that looks like a good solution.

Just for reference, another way is to simply use `Ctrl-A` ....  ;)

Thanks a lot!

**Comment by chrlsnchrg** [comment]
Maybe everyone else is already aware of this, but uniform hinting is not possible in the newest version (1.14.9). I'd very much like uniform hinting to be a feature.

**Comment by bovine3dom** [comment]
Are you saying `set hintnames uniform` is broken?

**Comment by glacambre** [comment]
You can't `set hintnames uniform` because `uniform` isn't registered as a valid value in `lib/config.ts`. Should be pretty easy to fix.

**Comment by bovine3dom** [comment]
I don't think we need to keep this issue open any more, we seem to have done most of the things on it except letting the hint mode accept keys
