### ISSUE TITLE
Config page

### ISSUE THREAD

**Issue by IsaacKhor** [tridactyl/tridactyl#280]
I think it's finally time that the much vaunted config page actually gets started. There are two-and-a-half approaches that I can think of to implement a config page:

1. Load .tridactylrc, or at least some in-browser equivalent until we figure out the native messenger
2. Direct JSON editing of the the userconfig (similar to how VSCode handles configuration) in a `config.html` page
3. Some sort of hybrid where we either load from option 1 (from either the fs or web-ext storage) and display the resulting user config in something similar to option 2

I'm inclined to go with the second option, despite the 1st being more 'vim-like', given typical user expectations (raise your hand if your extension wipes your config on startup), and just the convenience factor. Having a central location displaying all active config options is going to useful anyways. Option 3 is just more code for no good reason (and I don't feel like writing it). 

Any suggestions before I start working on an implementation of option 2? Do you mind if I write it in InfernoJS? Pulling in both CodeMirror and Inferno as dependencies seems like a bit much, but if we're going to be migrating the command line over to Inferno anyways, might as well start using it now.

**Comment by Nefari0uss** [comment]
So long as there's an easy way to back it up via source control, I don't have a huge preference between 1 or 2.

**Comment by Koushien** [comment]
I'm not familiar with VSCode, can you share a sketch of what you imagine `config.html` looking like?
I think option 2 makes the most sense both at the moment and in the long term if it plays nice with typical vcs. Displaying everything the user can configure at once while possibly keeping it self-documenting so a prospective user doesn't need to dig too deep is a huge boon.

**Comment by johnbeard** [comment]
I don't have particularly strong feeling either way (I'd rather have something than nothing), but as well as upsides like discoverability, there are a few downsides to GUI-driven JSON config:

* No ability to add inline comments, or comment out configs temporarily/for reference
* Ditto for Vim folding and organisation - you have to use the order and format it is saved it in, and if you modify in a text editor and disagree with the JSON import-export round trip, you'll get an ugly diff.
* Harder to copy config block-wise if you have to fill in a web form, item by item.
* Have to write new web form code to add any config (and not all config is just key-value `set item = "foo"`)

The other thing I thought of is that presumably nearly all these configs will be accessible from the command line, which means that the ex-commands to access them are already required, and reading an RC file is "just" a "proper" ex-command parser (which is also badly needed) which can split new lines and drop comments (+ maybe multiline stuff like autocmds?). As long as the parser works robustly to detect separate commands, there's no extra work needed once an ex-command exists. 

Also, with RC files, there is only one unified route for config; with JSON there are two - ex-commands and direct insertion to the runtime config - these have to stay in sync if either changes.

**Comment by glacambre** [comment]
The help pages have input fields for "simple" settings (strings/bools/numbers), can be accessed with the "preferences" button in about:addons and help completions + `:viewsource` are pretty useful when it comes to discoverability. Do we still need the config page as it is discussed here?

**Comment by bovine3dom** [comment]
Probably not.
