### ISSUE TITLE
Feature Request: Zoom for current tab with autocmd.

### ISSUE THREAD

**Issue by simonhughcom** [tridactyl/tridactyl#2804]
When using autocmd to set zoom such as `autocmd DocStart .*github\.com.* zoom 150`, the zoom will be applied to all windows/tabs on github.com and not just on the tab where autocmd is being run on. 

It would be nice to have a "zoom for current autocmd tab" command that will only apply the zoom on the tab the autocmd is running on.

Or maybe even better, a autocmd option to apply any command only to the tab/window the autocmd is running on.

**Comment by bovine3dom** [comment]
I don't think we can do this easily: zoom is just using a built-in Mozilla jobbie. We'd have to unzoom when you left the tab. Handling multiple windows just wouldn't be possible.

**Comment by simonhughcom** [comment]
Well, autocmd seems to be able to apply zoom to particular URL's, so it is clearly selective. So maybe just have a autocmd option to only apply the excmd to the window.

**Comment by bovine3dom** [comment]
We already do that. We're just using this command - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/setZoom - with a simple wrapper - https://github.com/tridactyl/tridactyl/blob/5e8f94ff06bd5f143732f2dabd32b08dabf1e65a/src/excmds.ts#L1811

**Comment by simonhughcom** [comment]
`setZoom()` has an optional argument of `tabId` that defaults to the active tab of current window.
I think you should utilize that and set it to the ID associated with the event.

`return browser.tabs.setZoom(level)` Here you only seem to be setting the `level` and not `tabId`.

**Comment by simonhughcom** [comment]
So maybe something along the line of this:
```
export async function zoom(level = 0, rel = "false", tabId) {
...

**Comment by simonhughcom** [comment]
Sorry I accidentally Closed the issue, did not mean to do that. :D

**Comment by bovine3dom** [comment]
The active tab should be the same as the tab where the event is fired. You can try it with `:jsb tri.webext.activeTab().then(tab => browser.tabs.setZoom(3, tab.id)`. I think you'll get the same behaviour as you do currently.

**Comment by simonhughcom** [comment]
Sorry I got it wrong, this is my bad.

The problem is not that zoom is being applied to all windows, but to the current window.

Let me describe what I did:
When on a website such as github with the option `autocmd DocStart .*github\.com.* zoom 150`.
And then if I manually change the zoom level to lets say 100.
Then if I open a link to another github page but stay on the current window (i.e. the link is being opened in a background window), then the current window zoom would change.
This makes sense since the excmd is being applied to the current window and not the background window where the event originates.

I mistakenly interpreted this as the zoom changing on all windows/tabs, but it does not.

It is still an annoying behavior that I think could be fixed through the `tabId` option.

**Comment by bovine3dom** [comment]
Ah, I see. I agree with you completely. I'd really like to fix that.

We could potentially give `autocmd` a magic variable, e.g. `TRI_FIRED_TAB_ID` that you could then pass to `zoom` which we'd extend. I think that's probably the most general way of doing it.

**Comment by simonhughcom** [comment]
I'm not exactly sure of how the `autcmd` function works behind the scenes, but I assume that in has access to the `tabId` of the tab the event is being fired on.

In which case this should be an easy 10 min fix, simple passed the tabId from the autocmd function to the zoom function.

But I'll leave it in your expert hands :).

**Comment by bovine3dom** [comment]
https://github.com/tridactyl/tridactyl/blob/5e8f94ff06bd5f143732f2dabd32b08dabf1e65a/src/excmds.ts#L1876

probably as simple as string replace on the aucmds[aukey]. Not sure how to get the id of the tab a content script is running in, might have to write a small thing that asks the background.

Unfortunately I have a list of about a thousand things that will only take 10 minutes : )

**Comment by simonhughcom** [comment]
Is this what you are looking for?
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/getCurrent

**Comment by bovine3dom** [comment]
Not quite - that doesn't work in content scripts. There is an exhaustive list of the APIs they have access to here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts

**Comment by bovine3dom** [comment]
Ah, we'd already written the function we need: https://github.com/tridactyl/tridactyl/blob/5e8f94ff06bd5f143732f2dabd32b08dabf1e65a/src/lib/webext.ts#L73
