### ISSUE TITLE
support for opening links in containers

### ISSUE THREAD

**Issue by gurpreetatwal** [tridactyl/tridactyl#283]
Is there any plan to augment the hint command to add support for [firefox containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/)?

**Comment by johnbeard** [comment]
Should be possible as there is a `contextualIdentities` (i.e. containers) API: https://hacks.mozilla.org/2017/10/containers-for-add-on-developers/

This could probably do with a bit of thought on how the command would work. Presumably you'd want at least:

* Open link in new container
* Open link in existing container (but how to specify this from the hint context?)

**Comment by bovine3dom** [comment]
Perhaps we should extend the idea of counts to any arbitrary prefix that would give the function an extra argument? Then one could perhaps bind `x` to the work container, and xt would open a tab in that container, xf hint mode etc?

**Comment by johnbeard** [comment]
I like the idea, but it might need some kind of prefix to denote "this is a container prefix"? Otherwise having a container with (say) a `g` bind would kill the `gt` binding. Perhaps something like `_gt` where `_` denotes "next character is a container key" (and is a character I picked randomly, needs thought).

**Comment by cmcaine** [comment]
John's idea seems preferable to me: I don't think we should have prefixes and binds competing in the same namespace.

It also apes how e.g. registers or macros are accessed in vim.

**Comment by saulrh** [comment]
Tried to write this. Didn't get it done in one day. Thoughts so far:
- `openInNewTab` in `webext.ts` happily accepts a new `container?: string` option. This could be the exact name of a `contextualIdentity`, but as `browser.contextualIdentities.Query` is case-sensitive and identity names are arbitrary strings, I suspect we'll want to add a `containers` config var which maps container shortcuts (example: `{ p: "Personal", b: "Banking", h: "Hacker News"}`) to long-form container names and a convenience function to make that easier to work with. This feature works nicely and is sufficiently well self-contained that I'd feel comfortable making it a PR, even if there wouldn't be any code that'd use it. Note that this requires adding the `contextualIdentities` and `cookies` permissions to the addon, the first for obvious reasons and the second so we can issue the `cookieStoreId` option to `browser.tabs.create`.
- `open` and `tabopen` currently have the signature `...addresses: string[]`, which is then `join(" ")`ed and navigated to. Feeding any more information to those functions will be... obnoxious. I experimented with splitting out args that matched `/^<containerprefix><containerchar>$/`, but this just felt ugly.
- I agree that a prefix is the correct UI. However, the current architecture of the `normalmode` parser doesn't seem to like the idea. Next time I'll probably be looking at this parser to figure out everything that it's doing (completions?) and see if I can make it easier to extend.

**Comment by IsaacKhor** [comment]
We're currently in a major rewrite of the completions and parsing code, so hold off on that. The new engine that I'm writing supports gnu-style `-o --option=thing`, so here's what I'm thinking about for the new `tabopen` command: `tabo[pen] [-P --private] [-C --current-container] [-c --container=container_id] [-l --location=f[irst]|l[ast]|n[ext]|d[efault]] url`. The alternative would be the same command with the same arguments except that the container would not be in a gnu-style oution `-c=id` but instead `tabopen ci_id url`. Maybe we could write an alternative command `contabopen` that is the second format and leave `tabopen` on my first format.

I don't think we should map each container to an abbreviation in config; a sufficiently advanced completions engine (part of the rewrite mentioned) should be able to eliminate that part. 

I'm not sure what to think about accessing containers in normal-mode through prefixes; I'll come back to it once I've thought about it some more.

**Comment by saulrh** [comment]
> The new engine that I'm writing supports gnu-style `-o --option=thing`,

Ah, perfect! I think that position-independent options are better for this - prefixes would be shorthands for arguments, providing a nice pattern for generalized prefixes that should make implementation of that quite a bit nicer. In this particular case I'll want to add container-awareness to every operation that could open a tab, and I'd prefer to avoid an entire line of container-aware equivalent functions. Maybe as aliases, but not as primitive commands.

> I'm not sure what to think about accessing containers in normal-mode through prefixes; I'll come back to it once I've thought about it some more.

A completions engine handles `tabopen` nicely, but since hinting doesn't open the command bar, I think that some kind of prefix is necessary for "follow this hint in a container".
