### ISSUE TITLE
:bind <S-1> zoom 0.1 true not working? 

### ISSUE THREAD

**Issue by nnadd** [tridactyl/tridactyl#2850]
Tridactyl 1.20.1
Firefox 78.2.0esr

Good day.
Wanted to bind shift for a zoom operation for easy one hand usage, but it doesn't seem to work, checked the other <S- > binds and the only ones there are Escape and Insert, I tried the same zoom bind command but with Delete and it worked, so I'm guessing tridactyl doesn't want to bind Shift unless it's with special key? Can I somehow fix this so I can have

`<S-1> zoom 0.1 true` 
`<S-2> zoom 0.1 true` working? If I use `<C-1>` and `<C-2>` it works without problem

**Comment by bovine3dom** [comment]
Shift-1 is probably reported to us as a special character. Use that instead.

E.g. rather than bind <S-2> do bind "

**Comment by nnadd** [comment]
> Shift-1 is probably reported to us as a special character. Use that instead.
> 
> E.g. rather than `bind <S-2>` do `bind "`


I tried `bind "<S-1>"`
`bind <S-1>`
`bind <Shift-1>`
`bind "<Shift-1>"`


None of them worked.

**Comment by bovine3dom** [comment]
What character appears when you press shift and 1 in a text box? Bind to that : )

E.g. `bind ! zoom 0.1 true`

**Comment by nnadd** [comment]
> What character appears when you press shift and 1 in a text box? Bind to that : )
> 
> E.g. `bind ! zoom 0.1 true`

Man, I feel dumb now, thank you!
