### ISSUE TITLE
Allow space separated arguments to `JS_ARG`

### ISSUE THREAD

**Issue by dit7ya** [tridactyl/tridactyl#2859]
Tridactyl version: 1.20.2pre4626-14b65660
Firefox version: Mozilla Firefox 81.0
Operating system: linux

As far as I currently understand `JS_ARG` when run in combination with `tri.native.run` can take only one argument and throws an error if there are more. It would be nice to have bash-like functionality of `$1`, $2`, `$@`, `$#` etc..

Please let me know if there is any other way to pass more arguments to the shell via native messenger using `exclaim` or something else and I will close this PR.

**Comment by glacambre** [comment]
On 2020-09-30 08:46, Sayan wrote:
> As far as I currently understand |JS_ARG| when run in combination with 
> |tri.native.run| can take only one argument and throws an error if there 
> are more. It would be nice to have bash-like functionality of |$1|, $2|, 
> |$@|, |$#` etc..

I believe there is a fundamental limitation in the way commands are 
dispatched that prevents us from doing that.

> Please let me know if there is any other way to pass more arguments to 
> the shell via native messenger using |exclaim| or something else and I 
> will close this PR.
> 

Have you tried something like `composite echo hello world does this work 
| exclaim $YOURCOMMAND`? I think it should work.

**Comment by bovine3dom** [comment]
`js` is pretty hacky: https://github.com/tridactyl/tridactyl/blob/5e8f94ff06bd5f143732f2dabd32b08dabf1e65a/src/excmds.ts#L4609

We could have another option where you provide a termination character, e.g. `command withspaces js -e% console.log(JS_ARGS.join(" "))%`, then `withspaces a b c` would work.

**Comment by bovine3dom** [comment]
e.g. `command withspaces js -d% console.log(JS_ARGS.join(" "))%` in the latest betas : )
