### ISSUE TITLE
How to close other tabs

### ISSUE THREAD

**Issue by 4SM** [tridactyl/tridactyl#2864]
How should I set it up?
thanks.

**Comment by glacambre** [comment]
Have you tried `:tabclose ` and either typing the number of the tab you want to delete or selecting the tab you want to delete with completions?

**Comment by 4SM** [comment]
set in vimium. How to set to tridactyl?
`nmap cl closeTabsOnLeft
nmap cr closeTabsOnRight
nmap cc closeOtherTabs`

**Comment by glacambre** [comment]
`:bind cl tabclosealltoleft`, `:bind cr tabclosealltoright` and `:bind cc composite tabclosealltoleft ; tabclosealltoright` should work :)

**Comment by 4SM** [comment]
> 
> 
> `:bind cl tabclosealltoleft`, `:bind cr tabclosealltoright` and `:bind cc composite tabclosealltoleft ; tabclosealltoright` should work :)

Thank you：）
