### ISSUE TITLE
Disable quick find

### ISSUE THREAD

**Issue by NN---** [tridactyl/tridactyl#2872]
Tridactyl version: 1.20.2
Firefox version: Mozilla Firefox 81.0.1
Operating system: win

*   Brief description of the problem:
How I disable quick find ?
Tried everything and cannot find where it is bound.

**Comment by bovine3dom** [comment]
You can't find it because it isn't part of Tridactyl - that's a Firefox bind.

What do you mean by "disable"? `:bind / echo` will turn it into a no-op.

**Comment by NN---** [comment]
I mean that I don't have quick find if Tridactyl extension is disabled.

**Comment by NN---** [comment]
Found it.
After setting `accessibility.typeaheadfind.manual` to `false`, it doesn't show up again.
