### ISSUE TITLE
Key bindings for History and Bookmarks menu

### ISSUE THREAD

**Issue by kevintraver** [tridactyl/tridactyl#2876]
Is it possible to add custom keybindings for navigating the menus, for example History and Bookmarks (ie :tabopen)

Specifically, remapping `<C-n>` and `<C-p>` to move up/down the list instead of `tab?`

**Comment by bovine3dom** [comment]
We/you can't override ctrl-n because Mozilla thinks that would be too dangerous.

If you can find a binding that you like and that Mozilla allows, `bind --mode=ex ex.prev_completion`. See `:help ex.` for all the available commands.

**Comment by kevintraver** [comment]
Ok thanks!
