### ISSUE TITLE
[feature request] remove third party network request to matrix.to from the help page

### ISSUE THREAD

**Issue by m040601** [tridactyl/tridactyl#2906]
*   Brief description of the problem:

When I open tridactyl's help page, it "phones" the domain matrix.to (which belongs to matrix.org the chat app)

*   Steps to reproduce:

1. Open :help 
2. Tridactyl's help page, moz-extension://1b908df4-9cf1-40f4-98cf-8d8dc8686ba1/static/docs/modules/_src_excmds_.html will open
3. A network request is sent to matrix.to
4. You can hard reload the help page with "R"  to repeat this request. Check your dns logs and see this phone call to "matrix.to" again.

This happens because, down there on the page where it says:

> Getting Help
> For more information, and FAQs, check out our readme
> You can also get in touch using Matrix, Gitter, or IRC chat clients:
> 

There is an svg image being sourced from that third party domain, matrix.to:

`<img src="https://matrix.to/img/matrix-badge.svg" alt="Matrix Chat"></a>
`

There is absolutely no need for this. These images/badges can be sourced locally, has it is done for:

gitter.im

`<img src="/static/badges/gitter-badge.svg" alt="Gitter Chat"></a>`

ircs://chat.freenode.net 

`<img src="/static/badges/freenode-badge.svg" alt="Freenode Chat">`

**Comment by bovine3dom** [comment]
I'd happily accept a PR that served the SVG locally - just need to change this line: https://github.com/tridactyl/tridactyl/blob/fb3e4c49a11960cfac9bd185bd35a29d562d98a5/src/excmds.ts#L68
