### ISSUE TITLE
Tutor page "visual mode" missing or Hints page link broken

### ISSUE THREAD

**Issue by dewoller** [tridactyl/tridactyl#2936]
Tridactyl version: 1.20.2pre4706-e8101151
Firefox version: Mozilla Firefox 81.0.2
Operating system: linux

*   Tutor page "visual mode" link broken

*   Steps to reproduce:

Go to hint mode tutor page
moz-extension://d88a3427-457c-49aa-9a8d-7f6a6f25e1b5/static/clippy/3-hint_mode.html
Click on link at bottom of page
moz-extension://d88a3427-457c-49aa-9a8d-7f6a6f25e1b5/static/clippy/3.5-visual_mode.html

**Comment by fluem** [comment]
I guess, I broke this. The build script for the tutor pages uses ```.``` as delimiter. Changing the filename should fix this.
