### ISSUE TITLE
`colors` sometimes doesn't feel like recognizing my css

### ISSUE THREAD

**Issue by ExpandingMan** [tridactyl/tridactyl#2943]
Tridactyl version: 1.20.2pre4715-da5396f8
Firefox version: Mozilla Firefox 82.0
Operating system: linux (manjaro)

Sometimes on loading firefox the tridactyl colors load incorrectly.  Sometimes `:colors dracula` (that's my css) works, sometimes it can't seem to find it.  I recently did a new install on another machine with the same manjaro setup I always do, and for some reason I can't get it to recognize the css over there at all.

Anything I can do to diagnose why this doesn't work sometimes?  If it fails it just tells me it can't find the scheme.

**Comment by bovine3dom** [comment]
> I recently did a new install on another machine with the same manjaro setup I always do, and for some reason I can't get it to recognize the css over there at all.

Often it is because `:native` isn't installed.

Is there any pattern to when it works or not on your other machine? Specific sites perhaps?

**Comment by ExpandingMan** [comment]
Ugh, Picard facepalm.

Sorry, I just completely forgot about that this time.  That would definitely explain it while it's on the other machine.

Is there any way to diagnose why it still sporadically happens when I actually have it built properly?  I feel like it became a much less frequent problem after some update, but it still happens to me occasionally.

**Comment by bovine3dom** [comment]
I think this is where we load custom themes - https://github.com/tridactyl/tridactyl/blob/eca1e1614b8d0e51dcb7369a3b4026fed72ad209/src/content/styling.ts#L50

We don't do much logging but you could try `set logging.styling debug`. You might find messages appear in the Firefox web console when your theme doesn't appear. We probably need to add more logging first before we can find out what is happening.

At one point `mktridactylrc` mangled custom themes. Can you check to see that it hasn't done that if you have an RC file? It'd be something like "set customthemes.[name] [loads of lines]".

**Comment by bovine3dom** [comment]
I'm going to assume this has been fixed in f406031a : )
