### ISSUE TITLE
Script not running with `composite hint -y | exclaim /myscript`

### ISSUE THREAD

**Issue by mrhieu059** [tridactyl/tridactyl#2944]
Tridactyl version: 1.20.2
Firefox version: Mozilla Firefox 82.0
Operating system: FreeBSD

I had a script which which pass _url_ to youtube-dl. The script is work perfectly fine with this command:` composite get_current_url | exclaim /myscript` however, when I use this command `composite hint -y | exclaim /myscript` to pass a specific url onto myscript, it doesn't work and doesn't seem to activate the script.

**Comment by bovine3dom** [comment]
You need to use `hint -pipe a href` instead of `hint -y` : )

**Comment by bovine3dom** [comment]
Oh, if you're piping to exclaim it's a good idea to pipe through `:shellescape`. e.g. `composite hint ... | shellescape | exclaim ...`. Without it a site could execute whatever it liked on your machine if you clicked a malicious link which targeted users who weren't using shellescape.

**Comment by mrhieu059** [comment]
Thank you @bovine3dom, it worked when I pipe through `shellescape`.
