### ISSUE TITLE
Restore scrollline behaviour

### ISSUE THREAD

**Issue by Karowli** [tridactyl/tridactyl#2952]
Tridactyl version: 1.20.2
Firefox version: Mozilla Firefox 81.0.2
Operating system: linux

Apologies if this question has been asked before. I couldn't find the answer on Google.

In most cases pressing j or k will scroll a web page up or down similarly to pressing `<C-e>` or `<C-y>`. However, if you select/highlight some text then instead what happens is that the text itself will be modified a la visual mode in vim. Noticing that `<C-e>` is bound to scrollline, I've tried:

`bind j scrollline 10`

But this does nothing. How do you revert j and k to scroll the page even when text is selected?

**Comment by glacambre** [comment]
You have to toggle the `visualenterauto` setting, see `:help set` and 
`:help visualenterauto` for more information :).

**Comment by Karowli** [comment]
Thank you! That solved it!
