### ISSUE TITLE
Autocmd will not run when it should.

### ISSUE THREAD

**Issue by simonhughcom** [tridactyl/tridactyl#3001]
Tridactyl version: 1.20.2pre4635-cd3d1302
Firefox version: Mozilla Firefox 82.0.3
Operating system: linux

`Autocmd` don't always run when they should. When clicking on a link inside the website itself a autocmd won't run unless I refresh the page manually.

As an example:
I have this line in my config
`autocmd DocStart .*youtube\.com/(c|channel|user)/[^/]*/?$ urlmodify -g 2 videos`.
It is intended to skip the home page of a channel and go straight to the video page.
If I click on a link to the channel page on youtube it does not run, but it will run if I then refresh the page.

The expected behavior is for the autocmd to always run if the URL matches the pattern.

**Comment by bovine3dom** [comment]
YouTube is probably a single page application, so when you click on a link no DocStart event is triggered. We can probably add an event for UrlChange or something.

**Comment by glacambre** [comment]
I think the reason this doesn't work is that the autocommand you 
DocStart is triggered when a page is loaded and youtube doesn't reload 
pages - instead everything is loaded in the same page. That's regular 
web insanity and I'm not sure Tridactyl can do anything about it. We 
could try to hijack pushState ( 
https://developer.mozilla.org/en-US/docs/Web/API/History_API/Working_with_the_History_API 
) but I doubt it'd work reliably (I believe more and more pages have a 
CSP that disallow hijacking…).

**Comment by simonhughcom** [comment]
A UrlChange event would be cool.

If I inspect the link to a channel in youtube it look like this:
`<a class="yt-simple-endpoint style-scope yt-formatted-string" spellcheck="false" href="/user/NASAtelevision" dir="auto">NASA</a>`
Now correct me if I am wrong but that looks like a standard link to me and not some javascript magic?
Or am I misunderstanding you?

**Comment by glacambre** [comment]
It looks like a regular link but you can add event listeners to prevent 
a link from working as usual, e.g.

element.addEventListener(event => event.preventDefault())

I don't think you can see this can of thing by just looking at the HTML, 
you'd have to read all of the JS served to your browser too.

**Comment by simonhughcom** [comment]
I don't know if this helps but I just realized that if I open the link in a new tab then it does work. So it is only if the link is opened in the same tab that the problem occurs.

**Comment by simonhughcom** [comment]
> It looks like a regular link but you can add event listeners to prevent a link from working as usual, e.g. element.addEventListener("click", event => event.preventDefault()) I don't think you can see this can of thing by just looking at the HTML, you'd have to read all of the JS served to your browser too.

Is there anyway to override this with JS or is it a fools errand?
Maybe inject my own script that takes over the functionality and refreshes the page after?

**Comment by bovine3dom** [comment]
https://gomakethings.com/how-to-detect-when-the-browser-url-changes-with-vanilla-js/ a `PopState` event should be easy, right?

**Comment by simonhughcom** [comment]
> https://gomakethings.com/how-to-detect-when-the-browser-url-changes-with-vanilla-js/ a `PopState` event should be easy, right?
> 
> Edit: MDN link https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event

I tried it with `window.addEventListener("popstate", () => loadaucmds("DocStart"))` but it does not work.

**Comment by bovine3dom** [comment]
I'll try to look at this tomorrow.

**Comment by bovine3dom** [comment]
Ah, yeah, I was being blinded by optimism. There's a `popstate` event but no `pushstate` event - so your snippet does actually work, but only if you use the back button to navigate to the page.

I've added a `UriChange` event in #3003. It's not a pretty fix as it uses a tiny bit of CPU (not noticeable on complex pages), but it only does that if the URL matches a `UriChange` event, so we can add it without any negative impact on users who don't use it. I'll look at the code again tomorrow morning and see if I still feel the same way : )

**Comment by bovine3dom** [comment]
```
autocmd DocStart .*youtube\.com/(c|channel|user)/[^/]*/?$ urlmodify -g 2 videos
autocmd UriChange .*youtube\.com js window.location.href.match(".*youtube\.com/(c|channel|user)/[^/]*/?$") && tri.excmds.urlmodify("-g", "2", "videos")
```

in the latest betas. Note that the UriChange invocation is a bit more complicated since it has to be triggered on the page that takes you to the page you're interested in.
