### ISSUE TITLE
[FR] allow space to be used in hintfiltermode

### ISSUE THREAD

**Issue by laur89** [tridactyl/tridactyl#3021]
Tridactyl version: 1.20.2
Firefox version: Mozilla Firefox 82.0.3
Operating system: debian

* Description
When using the `f` & `F` shortcuts (following link) in the vimperator mode, we cannot use the space character.
Quite often I'm on a newspaper front page that has loads of headlines, and typing in the hint should allow spaces to be used.
As it stands now, once `space` is typed, the current closest match is followed.

*   Relevant bits fom ~/.tridactylrc:

```
" hintmode as it was in vimperator:
set hintfiltermode vimperator
set hintchars 1234567890
```

**Comment by bovine3dom** [comment]
Have you tried `unbind --mode=hint <Space>`?

**Comment by laur89** [comment]
Hey thanks, that does the trick.
One minor note - when space is used in the hints then it takes quite a few characters for the best match to be selected; for some reason it highlight not the literal match first, and once say 3 characters from the second word (after space) is typed in it hones on the correct link.
