### ISSUE TITLE
Is there a way to define aliases with arguments?

### ISSUE THREAD

**Issue by saulrh** [tridactyl/tridactyl#3026]
Tridactyl version: 1.20.2pre4788-35ebb97d
Firefox version: Mozilla Firefox 78.0.2
Operating system: linux

It appears that `alias`es are handled by string-replacing the alias in the excmd string, so there's no good way to give them arguments - anything you write after the alias is necessarily tacked on to the end of the excmd string. You can sort of handle it by using `js`, structuring the alias like `(function(args){ ... })(`, and then remembering that you have to use js arguments and close the paren, but this is quite icky. It'd be nice if there was a way to define aliases with arguments.

This may have to wait on having a real parser.

**Comment by bovine3dom** [comment]
https://github.com/tridactyl/tridactyl/blob/eca1e1614b8d0e51dcb7369a3b4026fed72ad209/src/excmds.ts#L4751

js -p and js -d serve this purpose currently. It could definitely be more ergonomic, though : )

**Comment by saulrh** [comment]
Ah, I missed those. Should probably mention them in the help for `alias`/`command`.
