### ISSUE TITLE
Behavior of relative zoom

### ISSUE THREAD

**Issue by MckinleyX** [tridactyl/tridactyl#3031]
Tridactyl version: 1.20.2
Firefox version: Mozilla Firefox 83.0
Operating system: linux

Running ":zoom +10 true" causes zoom level to increase by 10%, but running ":zoom -10 true" causes zoom level to decrease by (some very large number, presumably 1000%) before being reset to the minimum of 30%.

Is there a reason for the behavior between the two to be inconsistent?

(The solution is to just use +0.1 and -0.1 in the commands instead of +10 and -10, but since the help page states that :zoom 
> Expects percentages when changing the absolute zoom value **and percentage points when making relative adjustments**

this was rather confusing for me when I ran into this.)

(I'm not particularly sure how GitHub works, but a solution might be changing 
`level = level > 3 ? level / 100 : level`
to check if `Math.abs(level) > 3` instead of just checking `level > 3`)

**Comment by bovine3dom** [comment]
> Expects percentages when changing the absolute zoom value and percentage points when making relative adjustments

This just means that if you're at e.g. 200% zoom, :zoom +0.1 takes you to 210% rather than a 10% increase of 200% = 220%.

What you're describing sounds like a bug : )

**Comment by bovine3dom** [comment]
https://github.com/tridactyl/tridactyl/blob/eca1e1614b8d0e51dcb7369a3b4026fed72ad209/src/excmds.ts#L1828

Yes, I think your proposed solution is the right one.
