### ISSUE TITLE
Using @import rules in themes

### ISSUE THREAD

**Issue by noib3** [tridactyl/tridactyl#3037]
Tridactyl version: 1.20.2pre4844-1b9cfa6f
Firefox version: Mozilla Firefox 83.0
Operating system: mac

I have a custom theme in `~/.config/tridactyl/themes/my-theme.css`, but I wanted to keep fonts and colorschemes in other directories to have a more modular setup. However, if I try to import them (this are the first two lines of `my-theme.css`)
```css
@import "/Users/noibe/.config/tridactyl/fonts/JetBrainsMono.css";
@import "/Users/noibe/.config/tridactyl/colorschemes/gruvbox.css";
```
those import rules seem to be ignored. Is importing other files not supported for security reasons?

**Comment by bovine3dom** [comment]
Almost certainly, yes. You can get round it probably by running a small web server like "caddy" and then pointing the imports to that URL.
