### ISSUE TITLE
Hiding grey hints

### ISSUE THREAD

**Issue by noib3** [tridactyl/tridactyl#3038]
Tridactyl version: 1.20.2pre4844-1b9cfa6f
Firefox version: Mozilla Firefox 83.0
Operating system: mac

From the Hint mode page of the Tridactyl Tutorial:
> Some hints have their tags (the labels which show which characters to press to activate them) in grey in the default theme. These correspond to elements which have JavaScript mouse events attached to them.

Is it possible to hide those hints in a custom theme? Do they have a css selector (to `{display: none}`)?

**Comment by bovine3dom** [comment]
They do, they have the class `TridactylJSHint` https://github.com/tridactyl/tridactyl/blob/eca1e1614b8d0e51dcb7369a3b4026fed72ad209/src/content/hinting.ts#L1026

but it would be easier to just rebind f/F to hint modes without them, i.e.

```
bind f hint -J
bind F hint -Jb
```

I'd say that was better because if you ever need them you can just do `:hint f` or even `;b` to see them just once.

**Comment by noib3** [comment]
And what is the class for the hint spans (idk if that's what they're called, I mean the boxes in the top left corner of every clickable element)?. I'm trying to change their font.

**Comment by bovine3dom** [comment]
@noib3 it is probably easier for you to find out than me (I'm away from my PC) - if you enter hint mode, right click a hint and then click "inspect element" you will get taken the the HTML and you can see exactly what classes there are.

If you go to the console tab you can use `document.querySelectorAll("selector")` to see what your selector will effect.

Our theme documentation isn't great at the moment. The best thing to do is to just look at the themes we have in src/static/themes and also to use inspect element to see the structure of things.

The latter one: no, not at the moment. Please make a new issue if you want it and we'll try to add it someday
