### ISSUE TITLE
User-configurable binds outside of normal mode

### ISSUE THREAD

**Issue by azmeuk** [tridactyl/tridactyl#304]
Hi. First of all, thank you for the awesome extension.

Is there a way to bind multiple keys shortcuts to a command? For instance, I would like "Ctrl + c" to act like "escape" in edition mode. How can I achieve this?

Thank you

**Comment by bovine3dom** [comment]
Hi, you're most welcome!

As per the FAQ on readme.md, we don't currently support modifiers (e.g. Ctrl) in binds, and only allow binds in normal mode. Sorry!

**Comment by azmeuk** [comment]
Is this planned for some days?

**Comment by bovine3dom** [comment]
@azmeuk yes, we even have a branch, keyseq, where most of the plumbing for it is already completed.

**Comment by cmcaine** [comment]
You can have multiple non-modifier keys, though. e.g. `gg`, `;y`, etc.

**Comment by bovine3dom** [comment]
Added in 1.9.2, as @timokau pointed out.

**Comment by bovine3dom** [comment]
Actually, will leave this open for binds outside of normal mode.

**Comment by bovine3dom** [comment]
Wot needs to be done for this:

- Copy-paste ex-cmd parsing into other modes, replacing their switch statements.
- Move stuff to be as functionified as possible (probably pretty easy)
- Document these new functions. Potential syntax `help mode/command` -> module's help page + anchor.

Let's ignore hint mode for now as I reckon that's probably harder. Another non-goal is user-defined modes, for now.

**Comment by bovine3dom** [comment]
Normal mode, ignore mode, input mode (the one on `gi`) and insert mode all have been rewritten in the latest betas, 1.13.1-161+. (160 had a pretty hilarious bug).

You can now add binds to ex strings (e.g. `scrollline 10`) in these other modes by doing `set {ignoremaps,inputmaps,imaps}.[key-sequence] [ex string]`, where imaps are mappings for insert mode. We'll add `bind --mode=insert` etc. soon, probably once #789 is fixed.

You can view bindings in these modes with `viewconfig {ignoremaps,inputmaps,imaps}`.

@azmeuk `set imaps.<C-c> composite unfocus | mode normal`. It only took me six months to get around to it! :)

---

I'm leaving this issue open as hint mode and command mode don't use the normal parsers and have their own commands, so a rewrite for them will take quite a lot longer than the few minutes this actually ended up taking.

**Comment by bovine3dom** [comment]
Command mode already has binds; this is just open for hint mode now.

**Comment by bovine3dom** [comment]
Hint-mode binds added in latest betas, e.g. `bind --mode=hint <C-[> hint.reset`.
