### ISSUE TITLE
Request: skip duplicates when scrolling through history

### ISSUE THREAD

**Issue by noib3** [tridactyl/tridactyl#3042]
Tridactyl version: 1.20.3pre4852-ebc222e0
Firefox version: Mozilla Firefox 83.0
Operating system: mac

Vim automatically skips duplicates in the command history when scrolling with the up and down arrow keys. Can the same behaviour be reproduced in tridactyl?

**Comment by bovine3dom** [comment]
Yeah, that's a good idea.
