### ISSUE TITLE
firefoxsyncpush with large theme dir fails with error

### ISSUE THREAD

**Issue by shallowbit** [tridactyl/tridactyl#3050]
Tridactyl version: 1.20.3
Firefox version: Mozilla Firefox 83.0
Operating system: linux

*   Brief description of the problem:

    firefoxsyncpush with large theme dir fails with the following
      
    `"controller in excmd: Error: QuotaExceededError: storage.sync API call exceeded its quota limitations."`

*   Steps to reproduce:

    1. create a theme folder in the tridactylrc dir
    2. fill it with some files
    3. reload config?
    4. run firefoxsyncpush

*   Result of running ``, or `! echo %PATH%` on Windows, in Tridactyl:

/home/overlayed/.rbenv/shims:/home/overlayed/.nave/installed/default/bin:/home/overlayed/go/bin:/home/overlayed/.cargo/bin:/home/overlayed/.zsh/zplug/bin:/home/overlayed/.dotfiles/bin:/home/overlayed/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/overlayed/.dotfiles/vendor/rbenv/bin:/home/overlayed/.fzf/bin 

*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:

{"cmd": "run", "content": "/home/overlayed/.dotfiles/link/.zsh/zplug/repos/zplug/zplug/bin:/home/overlayed/.zsh/zplug/bin:/home/overlayed/.rbenv/shims:/home/overlayed/.nave/installed/default/bin:/home/overlayed/go/bin:/home/overlayed/.cargo/bin:/home/overlayed/.dotfiles/bin:/home/overlayed/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/overlayed/.fzf/bin:/home/overlayed/.dotfiles/vendor/rbenv/bin\n", "code": 0}

**Comment by bovine3dom** [comment]
Thanks for reporting this. I thought we already had an issue open for it but I can't find it.

The sync storage quota is very small, so we need to exclude custom themes from `firefoxsyncpush`.

Until we do that, running

```
unset customthemes
firefoxsyncpush
colours [your theme]
```

should let you push and keep your own theme locally.

If you want themes to be shared you'll have to do that yourself manually and also run `colours [theme]` on each machine.

**Comment by shallowbit** [comment]
A **bigger issue** is that there was **no indication of failure** when using firefoxsync cmds **from an RC**. You have to manually run it to find out nothing is syncing.

A **possible automated solution** to the size issue, since my themes are version controlled, might be to trim down the theme folder to an acceptable sync size and then **clone from the theme origin repo**? via an excmd/autocmd on startup from the RC? 

Someone with more autocmd familiarity will have to let me know if the above is possible. If it is, it may offer a more convenient solution to automate syncing an RC which uses a default theme from a repo. 

I quickly looked for how to get storage info and found an api call, `storage.sync.GetBytesInUse` but I'm not sure how to call this in the context of tridactyl. One could use that info to determine if cleaning is needed in an automated solution until this is fixed.

**Comment by bovine3dom** [comment]
Your first point is valid but a bigger issue - we don't really know how to get feedback to users about their RC files. It's not as simple as showing an error in the command line as we often can't show that while the RC is running (because, e.g., the page hasn't loaded yet).

If your theme and RC file are version controlled, why do you need to use the Firefox sync storage? I don't like the idea of automatic cloning as we'd essentially be turning Tridactyl into a dotfile manager, which there are already plenty of : )

My plan is just to exclude custom themes from firefoxsyncpush and warn people about it. I don't really think it's worth spending time on trying to manage the quota as it's a very niche feature (but if a PR appeared that did it well I'd still merge it).

**Comment by klas-genestack** [comment]
Could I hit the same issue today, in 2022?  I keep being unable to push my quickmarks for years, it seems like.  I have two themes, but `unset customthemes` workaround does nothing for me.
Can I somehow debug the issue?

**Comment by klas-genestack** [comment]
Thanks for quick reply!
The result doesn't make much sense to me:
<img width="1323" alt="Screen Shot 2022-06-06 at 18 30 49 " src="https://user-images.githubusercontent.com/5174481/172181873-6b6fe582-7b2b-46a4-973b-17479d8b4897.png">
I don't know what I expected, but that's not it.  Or should I look up something particular in that object?
My `tridactylrc` is pretty basic, it's mostly keybindings.  Maybe I did something stupid long ago and broke the storage?

**Comment by bovine3dom** [comment]
If you right click the object you should be able to copy it to your clipboard and paste it in a code editor or something. Just look for anything that takes up thousands of lines :)

**Comment by bovine3dom** [comment]
If Firefox is saying you've exceeded the quota then I believe it :) It is 100kB per extension.

Somehow the default config has gotten copied into your configuration. If you follow what I said in https://github.com/tridactyl/tridactyl/discussions/4246 you should be able to preserve your real settings, wipe everything, and reapply your real settings. Then do a firefoxsyncpush and it should be small enough.

**Comment by klas-genestack** [comment]
Right, thanks, that worked!
After wiping everything and running `:sanitise tridactyllocal`, I was able to push my changes (which in my case is essentially quickmarks).
