### ISSUE TITLE
bindurl persists through restarts after reseturl run and in tridactylrc

### ISSUE THREAD

**Issue by rdrr** [tridactyl/tridactyl#3063]
Tridactyl version: 1.20.3pre4881-c7a409a9
Firefox version: Mozilla Firefox 84.0
Operating system: win

*   Brief description of the problem:

Used a bindurl for google which I found in someone's awesome config many months ago:

`bindurl www.google.com f hint -Jc .rc > .r > a`
`bindurl www.google.com F hint -Jtc .rc > .r >a`

This doesn't work on google anymore unfortunately, but the setting haunts me!  I've run:

`reseturl www.google.com f hint -Jc .rc > .r > a`
`reseturl www.google.com F hint -Jtc .rc>.r>a`

from 'ex', command line, and also put it in my .tridactylrc file, where the original bindurls were sourced from.  Whenever I restart Firefox I have to run the command from excmd again.

I've also run 
`sanitise tridactyllocal tridactylsynn`
to no effect either.

:viewconfig shows:

`{"configversion":"2.0","subconfigs":{"reddit.com":{"nmaps":{"gu":"urlparent 4"}},"www.google.com":{"nmaps":{"f":"hint -Jc .rc > .r > a","F":"hint -Jtc .rc>.r>a"}`

right at the top of the file.  How do I delete this from the JSON file, which is stored in a sqlite database file I believe?

*   Steps to reproduce:

    1.  put 'bindurl www.google.com f hint -Jc .rc > .r > a' in your .tridactylrc and start Firefox.
    2.  run 'reseturl www.google.com f hint -Jc .rc > .r > a' and put it in your .tridactylrc, then close Firefox.
    3.  delete 'bindurl www.google.com f hint -Jc .rc > .r > a' from your .tridactylrc
    4.  restart Firefox and check on google, config, or reseturl in the ex.

*   URL of the website the bug happens on:

google.com

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

Have some sensitive data in my configs, so will post them if needed, but I think I included the relative parts already.

Thank you all so much...Love tridactyl!!

**Comment by bovine3dom** [comment]
I'll look into this but in the meantime you could just update the bind to one that works: https://github.com/tridactyl/tridactyl/blob/46f59ecdf8233b68e41473d2f6750fe2168d94d6/.tridactylrc#L63

`sanitise tridactyllocal ` really should have worked, so I'm wondering if you have another RC file on your system somewhere. I take it that reseturl works until there is a restart? What happens if you run `:source` after reseturl with no restart?

Possible places for RC files are `~/.tridactylrc` and `~/.config/tridactyl/tridactylrc`.

**Comment by rdrr** [comment]
Thanks! Unfortunately, I can't.  As with reseturl, I've the updated bindurl from excmd and my .tridactylrc. It works for the session if entered by excmd, but reverts on restart.

**Comment by bovine3dom** [comment]
I really can't think of any other explanation than you having two RC files. Did you try the other steps I mentioned above?

**Comment by rdrr** [comment]
Sorry if took a whole year for me to come back and update, but I wanted to report that `sanitise tridactyllocal tridactylsync` worked now on linux!  `reseturl` did not and the error message (for all url entries) is `# controller in excmd: Error: can't access property "startsWith", args[0] is undefined`.
