### ISSUE TITLE
keep d/gt/gT usable in hint mode

### ISSUE THREAD

**Issue by wideweide** [tridactyl/tridactyl#3075]
Tridactyl version: 1.20.2pre4830-e30385eb
Firefox version: Mozilla Firefox 83.0
Operating system: win

if I set hintchars with no d/g/t then keep d to close tab,gt/gT to navigator tab

I use pentadactyl with fx56 for a while,it seems tridactyl can replace it ...

**Comment by bovine3dom** [comment]
```
bind --mode=hint d tabclose
bind --mode=hint gt tabnext_gt
bind --mode=hint gT tabprev
```

I think : )

**Comment by wideweide** [comment]
cool,thanks!

d/j/k/J/K is my really used in hint mode
