### ISSUE TITLE
xdotool mouse then click default bind

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#3077]
:/

In 238ba801 I added a couple to make it easier to craft an `xdotool` command that just moves the mouse and clicks on the elements.

`hint -F e => { const pos = tri.dom.getAbsoluteCentre(e); tri.excmds.exclaim_quiet("xdotool mousemove --sync " + pos.x + " " + pos.y + "; xdotool click")}`

but I can't get it to actually click - the mouse moves just fine, but it doesn't seem to click. :(

If we can get it to work I'll probably add it as a default bind like we have for mpv on `;v`.

_Originally posted by @bovine3dom in https://github.com/tridactyl/tridactyl/issues/1567#issuecomment-740845149_

**Comment by snippins** [comment]
"xdotool click 1" instead of just "xdotool click"?

**Comment by bovine3dom** [comment]
Thanks @snippins, I clearly wasn't paying enough attention when I read the man page : )
