### ISSUE TITLE
set local html as newtab

### ISSUE THREAD

**Issue by vishi-1** [tridactyl/tridactyl#3083]
is it possible to set a local html file as new tab/homepage in tridactyl

**Comment by Rummskartoffel** [comment]
You can set your new tab page, but not to a `file:///` URI. See `:help newtab`.

**Comment by vishi-1** [comment]
oh thanks didn't know about this

**Comment by bovine3dom** [comment]
I think you can do this in Firefox nightly: https://blog.nightly.mozilla.org/2020/12/08/these-weeks-in-firefox-issue-84/

It should end up in Firefox stable in a few months time. Unlike the local web server method mentioned on `:help newtab`, I don't think Tridactyl will be able to run on that page.

**Comment by Rummskartoffel** [comment]
I'm not sure it'll be possible, to be honest. The blog has a screenshot of that feature, and it looks like it's just a drop-down of all the new tabs provided by extensions plus the default.

**Comment by bovine3dom** [comment]
Oh, you're right ... I thought Firefox usually let you set your new tab page to an arbitrary URL, but I was wrong : (

**Comment by Rummskartoffel** [comment]
Only the home page, unfortunately. No idea why changing the new tab page isn't a thing yet.
