### ISSUE TITLE
Broken session during .tridactylrc setup.

### ISSUE THREAD

**Issue by pecheny** [tridactyl/tridactyl#3094]
I had tried to set up tridactylrc following [this](https://github.com/tridactyl/tridactyl/wiki/Exemplar-.tridactylrc-files) instruction. On last step i called `:restart` then in appeared cmd window was logged some brief error (which i unfortunately didn't write down). After firefox start i found only 3 windows of 6, other 3 with dozen of tabs has disappeared which is very painful for me. I understand that is a tricky case and don't want to try to reproduce it (and i didn't find any log file which can be useful).
I only ask to add  warning and reminder about session backup on instruction page.

Tridactyl version: 1.20.3
Firefox version: Mozilla Firefox 82.0.3
Operating system: win

*   URL of the website the bug happens on:
https://github.com/tridactyl/tridactyl/wiki/Exemplar-.tridactylrc-files

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
bind <C-o> back
```

**Comment by bovine3dom** [comment]
https://github.com/tridactyl/tridactyl/blob/46f59ecdf8233b68e41473d2f6750fe2168d94d6/src/excmds.ts#L828 we do mention it on the `restart` help.

I am sorry that you lost your tabs. I asked Mozilla for a command that let us safely quit Firefox three years ago and they just said no : (

**Comment by bovine3dom** [comment]
I've added a warning to that page. Have you tried `:undo window`?

**Comment by pecheny** [comment]
Thanks! I had look at history > recently closed windows and tried to restore sessionstore backup. Unfortunately i had restarted firefox one time more so nothing changed. I guess `:undo` uses same mechanism?

**Comment by bovine3dom** [comment]
I think it does. Sorry.
