### ISSUE TITLE
Add option to disable auto hint acceptance when only a single match

### ISSUE THREAD

**Issue by bew** [tridactyl/tridactyl#3097]
Tridactyl version: 1.20.3
Firefox version: Mozilla Firefox 83.0
Operating system: linux

Add a way to not auto accept a match in hint mode even if it is the only match, and always require to validate.

The idea is to forgive mistakes by always having the possibility to go back and re-type the hint chars.

**Comment by YodaEmbedding** [comment]
I'm looking for something similar: if there is exactly one link on the page, do not automatically follow that link. Instead, produce a hint for that link so that the user still needs to choose it.

**Comment by bovine3dom** [comment]
Very simple to do: add a `config.get("hintautoselect") == "true"` condition to

https://github.com/tridactyl/tridactyl/blob/73ef32497d6b1fc7975d703753eca63de69e8af6/src/content/hinting.ts#L862

And 

https://github.com/tridactyl/tridactyl/blob/73ef32497d6b1fc7975d703753eca63de69e8af6/src/content/hinting.ts#L950

and a `hintautoselect` setting to src/lib/config.ts, default true.
