### ISSUE TITLE
Tridactyl breaks semi-permanently when using :seturl with a syntax error in the RegEx pattern

### ISSUE THREAD

**Issue by Rummskartoffel** [tridactyl/tridactyl#3131]
Tridactyl version: 1.20.4pre4968-2ead7df9
Firefox version: Mozilla Firefox 84.0.1
Operating system: win

Merry Christmas!

*   Brief description of the problem:

    When using `:seturl` with syntactically incorrect RegEx, Tridactyl immediately becomes completely unusable. Any kind of interaction has no effect save for writing swathes of `SyntaxError`s regarding the RegEx supplied to `:seturl` to the console. Additionally, the new tab page appears blank. Manually calling excmds through `window.tri` on one of Tridactyl's pages also doesn't work, same with the "tri" keyword in the address bar.
    The only way to remedy this problem I've found is to manually modify the config through `window.tri.browserBg.storage.local`. Restarting does not help, even when using an rc file that calls `:sanitise tridactyllocal`.

*   Steps to reproduce:

    Run any `:seturl` command with syntactically incorrect RegEx, e.g. `:seturl [ foo`. `:bindurl` has the same effect.

*   URL of the website the bug happens on:

    Mostly irrelevant. The only difference I've observed is that non-Tridactyl pages, i.e. any page on which `window.tri` is not defined, don't write the errors to the console, but they can still be seen in the extension toolbox.  

*   Config and rc file: N/A

This specific error originates from `config.getURL`, where the pattern set in the config is fed into `String.prototype.match` without prior validation or error handling. https://github.com/tridactyl/tridactyl/blob/2ead7df95a576d252ff50a8fe0e69c16e1d8e133/src/lib/config.ts#L1238
However, the larger issue in my opinion is that an error while loading the config can break the entire extension. A broken config should should just result in loading the default config and displaying an error message.

**Comment by bovine3dom** [comment]
Can probably catch them easily by just making a new RegEx here https://github.com/tridactyl/tridactyl/blob/73ef32497d6b1fc7975d703753eca63de69e8af6/src/excmds.ts#L3434 and here https://github.com/tridactyl/tridactyl/blob/73ef32497d6b1fc7975d703753eca63de69e8af6/src/excmds.ts#L3527

but yeah, we should make Tridactyl robust to broken configs.

And merry Christmas! 🦌🦌🦌🛷🎅🎁🎁🎁
