### ISSUE TITLE
Feature Request: Add count to `followpage`

### ISSUE THREAD

**Issue by ChocolateOverflow** [tridactyl/tridactyl#3145]
I'd like to have a `count` available for `followpage`.

If I'm on `example.com/page/1` and press `5]]`, I'd like to go to `example.com/page/6` rather than `example.com/page/2`.

**Comment by bovine3dom** [comment]
I'm not sure how we'd do that for followpage. `urlincrement` would be easy, though: 

https://github.com/tridactyl/tridactyl/blob/73ef32497d6b1fc7975d703753eca63de69e8af6/src/excmds.ts#L1612 we can add an optional multiplier argument to the end of it then e.g. `10<C-a>` would add 10 to the URL.

**Comment by ChocolateOverflow** [comment]
Using `5<C-a>`/`5<C-x>` current only increments/decrements the URL by 1 rather than 5. I don't do JavaScript but we should add the count the `urlincrement`.

**Comment by bovine3dom** [comment]
Sorry - that's exactly what I was trying to say. Repeated `followpage` would be much harder : )
