### ISSUE TITLE
Make native messenger less slow and easier to distribute

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#3159]
As I mentioned in #3150.

I've been playing with Nim. Here's what I have so far:

```nim
# compile with 
# nim c --verbosity:0 native_main.nim
# (add -d:release for real builds)

# test with
# time printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ./native_main

# compare with
# time printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | python ~/.local/share/tridactyl/native_main.py

import json
import options
import os
# https://nim-lang.org/docs/json.html

type 
    MessageResp* = object
        cmd*, version*, content*, error*, command*: Option[string]
        code: Option[int]

# let a = MessageResp(cmd: some(""))
# echo(a)

proc getMessage(): MessageResp =

    # length of the string - not required AFAICT
    var length: int32
    discard readBuffer(stdin, addr(length), 4)

    let command = to(parseJson(readAll(stdin)),MessageResp)
    
    # unclear how to get the output of this
    # execShellCmd(command.command.get())

    return command

echo(%* getMessage()) # %* converts the object to JSON
```

Currently runs in ~4ms compared to ~100ms for our Python native messenger. (`time python -c "1+1"` takes 50ms alone FWIW).

**Comment by bovine3dom** [comment]
Looks like `execShellCmd`  definitely doesn't let us capture stdout, so we need to use a lower level thing that directly starts a process.

https://nim-lang.org/docs/osproc.html#execProcess,string,string,openArray[string],StringTableRef,set[ProcessOption]

The problem with that is that we need to work out what shell the user wants. If we want API compatibility with the python messenger we need to do that in the messenger. Dunno if that's a show-stopper.

**Comment by bovine3dom** [comment]
@Rummskartoffel when you have a moment could you check that the Windows binary here works OK? https://github.com/tridactyl/native_messenger/actions/runs/466614342#artifacts

**Comment by bovine3dom** [comment]
Development of the binary has moved to this repository to make building it on various OSs a little easier: https://github.com/tridactyl/native_messenger

**Comment by Rummskartoffel** [comment]
Yeah, I noticed about the move already.

The binary works fine, but the file extension is ".py" and not ".exe", which *might* cause issues – I'm not sure, though.

**Comment by bovine3dom** [comment]
I made it `.py` for now to make it easier to use as a drop-in replacement without having to replace the native messenger JSON manifest thingy.

I reckon I'll drop it before we do a proper release, if only to stop people from getting suspicious.

Have you been tried it in Firefox? It's at the point where lots of stuff works OK on Linux, e.g. `:! echo 123`.

**Comment by Rummskartoffel** [comment]
I hadn't until now, but it works reasonably well. The only issue I noticed is an issue we already knew – the lack of a proper shell when using `native.run`.
