### ISSUE TITLE
Visual mode

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#32]
It should be possible to have a Vim-style visual mode using the selection API: https://developer.mozilla.org/en-US/docs/Web/API/Selection_API

I think it could be particularly helpful for browsing the web if we also support `^i`, `^o` and `gd`.

**Comment by sunnypp** [comment]
I also want this function, especially when I want to copy some text on the screen when navigating with Tridactyl.

Say when I use `/` to search for a string on the page, then press `^g` to the occurrence I want and then `<cr>` to start my selection:
If we can eval some JS string, we may well have some work around..
`h`: `s=window.getSelection();s.extend(s.focusNode, s.focusOffset-1)`
`l`: `s=window.getSelection();s.extend(s.focusNode, s.focusOffset+1)`
And then `y` would be something like `bind clipboard yank "window.getSelection().toString()"`..
Though I personally don't mind using `<Cmd+C>` as I don't have to move my hands too far (like to the arrow keys to do `<S-Left>` ...

If the [non-standard method](https://developer.mozilla.org/en-US/docs/Web/API/Selection/modify) `modify()` is used, we may also have something like: (`s=window.getSelection()`)
`j`: `s.modify("extend", "right", "line")`
`k`: `s.modify("extend", "left", "line")`
`b`: `s.modify("extend", "left", "word")`
`e`: `s.modify("extend", "right", "word")`
And `w` is a little trickier that we have to see if `s.toString.substr(-1)` is a space or not...

Hope we can have easier ways to copy text soon -- by the way I don't know why `open javascript:alert(1)` doesn't work -- thought about hacking through there to get an eval 😛

**Comment by sunnypp** [comment]
Here is a temporary hacked fork which we may use before an official release of Visual mode...
https://github.com/sunnypp/tridactyl
The hack is, by a very dangerous `exec` excmd that runs on JavaScript using `eval` we can do every evil... I hope this can be forgiven for the time being.
And then with reference to default maps in `normalmode.ts` and their implementations in `excmd.ts`, I did the following bindings:
```
bind h exec let s=window.getSelection(); s.type=="Range" ? s.extend(s.focusNode, s.focusOffset-1) : window.scrollBy(-50,0)
bind j exec let s=window.getSelection(); s.type=="Range" ? s.modify("extend", "right", "line") : window.scrollByLines(10)
bind k exec let s=window.getSelection(); s.type=="Range" ? s.modify("extend", "right", "line") : window.scrollByLines(-10)
bind l exec let s=window.getSelection(); s.type=="Range" ? s.extend(s.focusNode, s.focusOffset+1) : window.scrollByLines(50,0)
bind w exec let s=window.getSelection(); s.modify("extend", "right", "word")
bind W exec let s=window.getSelection(); s.modify("extend", "left", "word")
bind ` exec window.getSelection().removeAllRanges()
```
I used `W` instead of `b` because it is harder to hack into the buffers... And I seldom use `winopen` so I overridden the `w`.

So I still do "Next Occurrence" with `<Cmd-g>` and copy with `<Cmd-c>` -- I'm just avoiding using the arrow keys so my hands won't miss the homerow too much.

**Comment by bovine3dom** [comment]
Surfingkeys and Vvimpulation both support this: https://github.com/amedama41/vvimpulation/blob/master/content_scripts/visual_mode.js

**Comment by octavz** [comment]
Hi, any chance this will happen soon? I would like to move from Surfingkeys to tridactyl and I miss a lot select and search with keyboard.

**Comment by bovine3dom** [comment]
@octavz no-one is currently working on it so it's unlikely. If you're interested I'd be happy to help get you up to speed with our architecture here or on Riot.

Alternatively, Firefox has a caret mode built in if you press F7 which might do something similar to what you want.

**Comment by dfischer** [comment]
Oh wow, caret mode is actually pretty cool. Thanks!

**Comment by bovine3dom** [comment]
Rudimentary visual mode added in #2052. Enter it by selecting text with the mouse, caret mode (F7) or highlight hint mode bound to `;h`. Available now in the latest betas.

Known issues:
- Moving the cursor backwards over the selection (e.g. by holding h down) exits visual mode.
- Rapid hinting `hint -qh` doesn't work well as after the first hint you exit hint mode and enter visual mode

To my surprise, Firefox's built in `/` works pretty well; it automatically puts you in visual mode.

Feedback appreciated.

**Comment by Philipp0205** [comment]
Just a quick heads up for everyone wondering. 'v' instead of ';h' works as well and might be more familiar for vim users. Thanks again for this much needed feature.

**Comment by dfischer** [comment]
Is this live for all users now? @Philipp0205 wasn't working for me. Anyway to force update?

**Comment by Philipp0205** [comment]
@dfischer It's live in the newsest beta version (First link in the Readme).
