### ISSUE TITLE
How to set a file path as your newtab?

### ISSUE THREAD

**Issue by Disco-Dave** [tridactyl/tridactyl#3216]
Hello, how do I set `file:///srv/nfs/my-tab-page/dist/index.html` as my newtab.

I am able to run `:set newtab file:///srv/nfs/my-tab-page/dist/index.html` but when I run `:tabopen` I get `:# controller in excmd: Error: Illegal URL: file:///srv/nfs/my-tab-page/dist/index.html`

I'm sure I'm just not understanding the proper syntax, any help would be appreciated.

Thanks

**Comment by bovine3dom** [comment]
You can't do this directly due to restrictions from Mozilla. Sorry.

See `:help newtab`: https://github.com/tridactyl/tridactyl/blob/1522f0900cabfd8d95dfa223231772fee61938b7/src/lib/config.ts#L677
