### ISSUE TITLE
Visual indication of multiple-character shortcuts

### ISSUE THREAD

**Issue by magnus-ISU** [tridactyl/tridactyl#3217]
Tridactyl version: 1.20.4
Firefox version: Waterfox Ltd. Waterfox 78.6.0
Operating system: linux
<!--
:
# Feature request

First of all, sorry if this already exists as I am probably not searching with the correct keywords. Anyway,

one of the very nice features about tridactyl is the ability to bind a multiple-key shortcut, for example ;k or yy or whatever. However, there is no way to know if you are already in the process of typing a shortcut or not. It would be nice if you could see the characters tridactyl has seen you type, similar to how neovim (and vim too, I imagine) will display them in the bottom right.

Possibly related to adding a statusline which I saw on the to-do list issue, although it could be implemented elsewhere (for example the textbox showing your mode in the bottom right)

**Comment by bovine3dom** [comment]
Does `:set modeindicatorshowkeys true` do what you want?

**Comment by magnus-ISU** [comment]
Yes
