### ISSUE TITLE
Syntax for running excmd as an autocmd?

### ISSUE THREAD

**Issue by hejops** [tridactyl/tridactyl#3218]
I want to trigger a shell script of mine whenever I open a particular url regex. What is the correct way to do this? I tried the following two methods below, but neither worked (only an empty command line appeared).

```
" command run_script js -p tri.excmds.shellescape(JS_ARG).then(url => tri.excmds.exclaim_quiet('sh /path/to/script ' + url))
" autocmd DocStart <url> composite get_current_url | run_script

autocmd DocStart <url> js -p tri.excmds.shellescape(TRI_FIRED_URL).then(url => tri.excmds.exclaim_quiet('sh /path/to/script ' + url))
```

**Comment by bovine3dom** [comment]
I think you need to remove `-p` from the last one.

But

```
autocmd DocStart [URL] composite get_current_url | shellescape | exclaim_quiet sh /path/to/script 
```

should work fine.

If it doesn't I'd swap `DocStart` for `DocLoad` to give Tridactyl a bit longer to load everything.

**Comment by hejops** [comment]
Works great, thank you!
