### ISSUE TITLE
Does anyone use exotic architectures?

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#3234]
We're remaking the native messenger in Nim, so we'll be distributing binaries rather than python scripts - https://github.com/tridactyl/native_messenger/issues. At the moment we're only offering x64 binaries.

Does anyone use x86 ~~or arm64~~ (armhf added in #3410)?

**Comment by Rummskartoffel** [comment]
I was wrong with what I recently said on Matrix about the default being x86 for Windows, by the way. I must have manually installed an x86 version and then forgotten about it, somehow.

**Comment by Jab2870** [comment]
I use it on a Raspberry pi so arm64 would be useful.

**Comment by bovine3dom** [comment]
@Jab2870 have you tried it? We have an arm64 build. In theory it should just work from `:nativeinstall`

**Comment by Jab2870** [comment]
`:nativeinstall` has always worked for me up until now, yes. I assumed this
issue was about continuing support for arm64. Apologies if I got the wrong end
of the stick

**Comment by bovine3dom** [comment]
Yeah it is for that. Someone asked for `armhf` in a separate issue (for some reason I didn't link it to this one) and they got it: https://github.com/tridactyl/tridactyl/issues/3410

If you're on `:native` >= 0.2 you're already using a Nim arm build : )

**Comment by bovine3dom** [comment]
I think we have most architectures covered now except OSX arm, which is tracked over at https://github.com/tridactyl/native_messenger/issues/2
