### ISSUE TITLE
Look at mozillaAddons permission

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#3237]
https://github.com/mozilla-services/screenshots/blob/master/webextension/manifest.json.template#L83

Should allow us to run on reader and PDF pages. Definitely won't be accepted on AMO but maybe it'll work unsigned. If not we may need to patch Firefox.

**Comment by bovine3dom** [comment]
Yeah, unpatched Firefox removes the permission from addons that aren't supposed to have it. It checks `isPrivileged`: https://searchfox.org/mozilla-central/rev/361d3e3a61929bb3fc4f088adf97649e38900f00/toolkit/components/extensions/Extension.jsm#2141

That looks very much like it isn't C++, @glacambre, so perhaps we can patch it?

`SIGNEDSTATE_SYSTEM` also looks promising. Perhaps all system-level extensions get that, even if they aren't explicitly signed?

**Comment by glacambre** [comment]
>That looks very much like it isn't C++, @glacambre, so perhaps we can patch it?

Huh, I guess I was wrong about that!

>Extension.jsm doesn't appear in omni.ja

I did find an `Extension.jsm` in my `/usr/lib/firefox/omni.ja` in the extracted `modules/` directory.

**Comment by bovine3dom** [comment]
That's weird. I'll look again. Maybe the thing I used to unzip it didn't work properly.

**Comment by bovine3dom** [comment]
I definitely don't have an `Extension.jsm` in my modules/ directory.

What are you using to unzip it? `unzip --help` for me says p7zip 16.02.

**Comment by glacambre** [comment]
On 1/17/21 12:47 PM, Oliver Blanthorn wrote:
> I definitely don't have an |Extension.jsm| in my modules/ directory.
> 
> What are you using to unzip it? |unzip --help| for me says p7zip 16.02.

UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.

**Comment by bovine3dom** [comment]
Thanks. I just tried it with that and I still have no `Extension.jsm` :/

```
modules/ExtensionControlledPopup.jsm
modules/ExtensionPopups.jsm
modules/ExtensionsUI.jsm
modules/UrlbarProviderExtension.jsm
```

Maybe Arch is doing something weird to Firefox.

**Comment by glacambre** [comment]
On 1/17/21 1:07 PM, Oliver Blanthorn wrote:
> Thanks. I just tried it with that and I still have no |Extension.jsm| :/
> 
> |modules/ExtensionControlledPopup.jsm modules/ExtensionPopups.jsm 
> modules/ExtensionsUI.jsm modules/UrlbarProviderExtension.jsm |
> 
> Maybe Arch is doing something weird to Firefox.
> 

Are you sure you're looking at firefox/omni.ja and not 
firefox/browser/omni.ja ?

**Comment by bovine3dom** [comment]
That was it. I can't decide who is sillier - me, for not reading properly, or Firefox for having _two_ files called "omni.ja". Omni means all dammit.

**Comment by bovine3dom** [comment]
Cool. Managed to stop Firefox complaining about giving Tridactyl the `mozillaAddons` permission. Other than that, nothing seems to work. Further investigation needed. Closing in favour of https://github.com/tridactyl/godmode.
