### ISSUE TITLE
feature: text.backward_char / text.forward_char

### ISSUE THREAD

**Issue by n14s** [tridactyl/tridactyl#3251]
First of all, thanks for this great program!

I got a question regarding the text navigating in ex/input/insert mode. 
There are several commands for navigating the text, eg. move forward a word, move to end of input field, that I'm very happy with.
There seems to be missing a command to move just a character left or right. Is it possible to produce that functionality on a custom key like C-h/C-l?

I was already thinking about mapping C-h/C-l globally on my linux machine to the arrow keys, enabling me to use it in all programs. I'm hesitating though, since it could interfere with functionalities of programs that arent as customizable as tridactyl.

**Comment by bovine3dom** [comment]
`text.backward_char` exists: https://github.com/tridactyl/tridactyl/blob/aae421f4e52fa9c0455200c3e7cce32efa80606a/src/lib/editor.ts#L365

as does `text.forward_char`: https://github.com/tridactyl/tridactyl/blob/aae421f4e52fa9c0455200c3e7cce32efa80606a/src/lib/editor.ts#L356


Are they broken for you?

**Comment by n14s** [comment]
You are absolutely right. 
I searched the docs and then files for a "text.forward" and then a "text." regex not finding a hit regarding chars. Now I see why. 
Thanks for clearing that up! Feel free to close this thread.

**Comment by bovine3dom** [comment]
You're welcome.

I think the help pages for the text.* commands are broken. I'm sure there's another issue open for that somewhere so I'll close this one.
