### ISSUE TITLE
Can we have a yankorg?

### ISSUE THREAD

**Issue by ycpei** [tridactyl/tridactyl#3255]
Tridactyl version: 1.20.4
Firefox version: Mozilla Firefox 84.0.2
Operating system: gnu/linux

Can we have a `yankorg`, similar to [`yankmd`](https://github.com/tridactyl/tridactyl/blob/master/src/excmds.ts#L3179), but with [orgmode markup syntax](https://orgmode.org/guide/Hyperlinks.html) for a link?

So instead of `[description](link)` as in `yankmd`, `yankorg` would write `[[link][description]]` to the clipboard. Like the other yank commands, bind `yo` to `yankorg`.

Thank you.

**Comment by bovine3dom** [comment]
Yes, you may : )

**Comment by ycpei** [comment]
That was fast, thank you.
