### ISSUE TITLE
Ctrl+x and Ctrl+a changes port of url, if it has no path

### ISSUE THREAD

**Issue by FredeEB** [tridactyl/tridactyl#3258]
Tridactyl version: 1.20.4
Firefox version: Mozilla Firefox 84.0.2
Operating system: linux

*   Brief description of the problem:

I've been developing an app on localhost:3000, accidentally hitting ctrl+a or ctrl+x goes to localhost:3001 and localhost:2999 rescpectively. I'm not sure if this is intended, however, I would like to have the options to turn that off, as it disables tridactyl if nothing is running on that port.

*   Steps to reproduce:

1. Open a url with a port

2. Press ctrl+x or ctrl+a

*   URL of the website the bug happens on:

Anything ending in a port like localhost:3000

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

https://pastebin.pl/view/e22e702c

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

Empty

**Comment by bovine3dom** [comment]
Hmm, I'm not sure that this is a bug. I accept that most people would never want to increment or decrement by a single port, but `<C-{a,x}>` both accept counts so you can do e.g. `100<C-x>` to reduce the port by 100, which people might more plausibly want to do if they have multiple services running.

Might I suggest 

```
:unbindurl ^https?://localhost <C-a>
:unbindurl ^https?://localhost <C-x>
```

to fix your immediate problem?


I'm happy for people to come in and tell me that no-one ever would want to use C-a/x for changing port : )

**Comment by FredeEB** [comment]
That was my though too, which is why i was suggesting a way to disable it, which is doable with what you're suggesting. For me that's enough to close the issue :+1:
