### ISSUE TITLE
Tabpush/tabgrab improvements

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#3283]
Tabpush should not list the current window. If no arguments are provided and two windows exist the other window should be used. Perhaps it makes sense to extend this to "the last used window", so that something happens even with more than two windows.

Tabgrab should not list tabs from the current window.

**Comment by bovine3dom** [comment]
A PR that did this should use the minimum amount of code. completions/Tab{,All}.ts is already bad enough for duplication, I don't want another two : )

**Comment by klas-genestack** [comment]
I've noticed that (at least) in _1.21.1pre6005-83b1f7c7_ `tabpush` with no arguments (and two windows) started to behave as described 🎉

**Comment by bovine3dom** [comment]
It was added in #3744 : )
