### ISSUE TITLE
MacOS users: help wanted testing native

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#3290]
I'm looking for some help testing the new native messenger on MacOS. I strongly suspect it works but I haven't managed to get a real human to confirm it for me yet.

I'm therefore looking for a real human to:

1. Install or already use Tridactyl beta
2. Download and run this script https://github.com/tridactyl/native_messenger/blob/master/installers/install.sh
3. Check in Tridactyl that `:native` returns 0.2.0
4. Check that `:tabopen about:addons` opens about:addons
5. Reply in this thread telling me whether it all works

Thanks : )

**Comment by rprimus** [comment]
Wed Jan 27 10:43:43 GMT 2021

> Install or already use Tridactyl beta

- [X] Already use Tridactyl beta
- [x] Native messenger is correctly installed, version 0.1.11 

> Download and run this script https://github.com/tridactyl/native_messenger/blob/master/installers/install.sh

```shell
: ; sh ./inst.sh
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
(23) Failed writing body
Failed to install!
```
Failed option: -P
brew install grep
Modified script to use ggrep:

```shell
: ; sh ./inst.sh
Installing manifest here: /Users/m/Library/Application Support/Mozilla/NativeMessagingHosts/
Installing script here: XDG_DATA_HOME: /Users/m/.local/share/tridactyl

Successfully installed Tridactyl native messenger!
Run ':native' in Firefox to check.
```

> Check in Tridactyl that :native returns 0.2.0

- [x] # Native messenger is correctly installed, version 0.2.0 

> Check that :tabopen about:addons opens about:addons

- [X] Done

> Reply in this thread telling me whether it all works

- [X] Done

**Comment by rprimus** [comment]
Wed Jan 27 11:21:55 GMT 2021

Replace `grep` 
```shell
native_version="$(curl -sSL https://api.github.com/repos/tridactyl/native_messenger/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')"
```

with `awk`:
```shell
native_version="$(curl -sSL https://api.github.com/repos/tridactyl/native_messenger/releases/latest | awk -F'"' '/tag_name/ {print $4}')"
```

**Comment by bovine3dom** [comment]
Thanks!

Could you remove `/Users/m/.local/share/tridactyl/` and try the version I've just pushed?

I didn't see your post and went with 

```
native_version="$(curl -sSL https://api.github.com/repos/tridactyl/native_messenger/releases/latest | grep "tag_name" | cut -d':' -f2- | sed 's|[^0-9\.]||g')"
```

Also could you confirm that you haven't done anything unusual like disabled the Apple binary signature checking?

**Comment by rprimus** [comment]
Wed Jan 27 11:49:39 GMT 2021

> Could you remove /Users/m/.local/share/tridactyl/ and try the version I've just pushed?

The new script works.

> Also could you confirm that you haven't done anything unusual like disabled the Apple binary signature checking?

I've done nothing 'unusual'.

FYI:
```shell
➜  tridactyl
: ; codesign --verify --verbose ./native_main
./native_main: code object is not signed at all
In architecture: x86_64
```

**Comment by rprimus** [comment]
Wed Jan 27 12:02:25 GMT 2021

BTW - am currently running:
```
: ; sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H114
```

Might be good to get someone running  `Big Sur` (11.1) on 
1. Intel
2. M1

to test as well.

**Comment by gsbabil** [comment]
@bovine3dom 

I have the following:

- Native messenger: `0.2.1`
- Operating System: `Mac/Big-Sur 11.2`
- Firefox: `Nightly 87.0a1`

The following does not work for me yet:

- `:tabopen about:addons`
- `:saveas ~/Documents` (or any other valid target in place of `~/Documents`)

Thank you.

**Comment by rprimus** [comment]
Fri Feb  5 10:39:54 GMT 2021

As requested ...

`:saveas` also (partially) fails with version `0.2.0`.  The initial download is successful, however, if an argument is provided to `:saveas`, the `move` portion fails:

```
08:36:40 <rprimus> # controller in excmd: Error: '/Users/m/Downloads/native_main.nim' could not be moved to '/tmp/fred'. Make sure it doesn't already exist and that all directories of the path exist.

08:37:31 <rprimus> # controller in excmd: Error: '/Users/m/Downloads/native_main(1).nim' could not be moved to '/tmp/'. Make sure it doesn't already exist and that all directories of the path exist.

08:38:00 <rprimus> # controller in excmd: Error: '/Users/m/Downloads/native_main(2).nim' could not be moved to '/tmp'. Make sure it doesn't already exist and that all directories of the path exist.

08:38:52 <rprimus> # controller in excmd: Error: '/Users/m/Downloads/native_main(4).nim' could not be moved to '~'. Make sure it doesn't already exist and that all directories of the path exist.
```

Using @gsbabil 's example from `IRC` (but using the current native (nim) binary):

As a basline, trying other `cmd`'s:
```
: ; ~/zff/tridactyl/native/gen_native_message.py 'cmd..version' | ./native_main
z{"cmd":null,"version":"0.2.0","content":null,"error":null,"command":null,"sep":null,"files":null,"isDir":null,"code":null}%
```
```
: ; ~/zff/tridactyl/native/gen_native_message.py 'cmd..env' 'var..HOME' | ./native_main
}{"cmd":null,"version":null,"content":"/Users/m","error":null,"command":null,"sep":null,"files":null,"isDir":null,"code":null}%
```
```
: ; ~/zff/tridactyl/native/gen_native_message.py 'cmd..list_dir' 'path../tmp' | ./native_main
�{"cmd":null,"version":null,"content":null,"error":null,"command":null,"sep":"/","files":["powerlog","com.apple.launchd.DP7l6387mb","com.apple.launchd.68cQAomnok","tmux-501"],"isDir":true,"code":null}%
```
```
: ; ~/zff/tridactyl/native/gen_native_message.py 'cmd..read' 'file../tmp/zz' | ./native_main
�{"cmd":null,"version":null,"content":"Hi, Tridactyl\n","error":null,"command":null,"sep":null,"files":null,"isDir":null,"code":0}%
```
```
: ; ~/zff/tridactyl/native/gen_native_message.py 'cmd..read' 'file..~/zz' | ./native_main
�{"cmd":null,"version":null,"content":"Hi, Tridactyl\n","error":null,"command":null,"sep":null,"files":null,"isDir":null,"code":0}%
```

Attempting `move` again: Note:  `code:2`: `OSError`
```
: ; ~/zff/tridactyl/native/gen_native_message.py 'cmd..move' 'from..~/zz' 'to../tmp' | ./native_main
t{"cmd":null,"version":null,"content":null,"error":null,"command":null,"sep":null,"files":null,"isDir":null,"code":2}%
```
Trying with destination file that exists:
```
: ; ~/zff/tridactyl/native/gen_native_message.py 'cmd..move'  'to../tmp/zz' | ./native_main
t{"cmd":null,"version":null,"content":null,"error":null,"command":null,"sep":null,"files":null,"isDir":null,"code":1}%
```
Finally, with a fully qualified destination path (that doesn't exist): (OSError)
```
: ; ~/zff/tridactyl/native/gen_native_message.py 'cmd..move'  'to../tmp/zz-1' 'from..~/zz' | ./native_main
t{"cmd":null,"version":null,"content":null,"error":null,"command":null,"sep":null,"files":null,"isDir":null,"code":2}%
```

**Comment by gsbabil** [comment]
Hi @rprimus,

Thanks for adding the details above.

- I'd just like to add that the `move()` operation fails with `"operation not permitted"` which very likely means that the OS is blocking the `write()/move()` operation with the target source/destination combo (`from` and `to` values in your examples above). 

  - This can be verified by enabling `DEBUG` mode with `write_log()` in the older Python `native_messenger.py` and closely observing the `shutil.move(...)` operation.

- Also, `codesign`-ing and removing `com.apple.quarantine` attribute from the downloaded (source) file does not solve the problem (for both `Nim` and `Python` messengers).

- Strangely, the `move()` function if attempted directly on CLI with a previously downloaded file Firefox e.g. saved in the `~/Download` folder will work with `code == 0` (as shown below), but will fail with `code == 2` if invoked from Firefox with `:saveas ~/tmp/`

- To confirm, this is quite positively not related to incorrect path or path expansions as in case of `~`, `../` or `./`.

```
gen_native_message.py 'cmd..move' 'from..~/Downloads/blah' 'to../tmp' | ./native_main
```

Hope this helps. Thank you.

**Comment by rprimus** [comment]
Fri Feb  5 11:52:09 GMT 2021

Hi @gsbabil ,

I've updated my post above.

The error is because `moveFile` is being called with the arguments reversed.  As the `source` does not exist, `OSError` is being raised.

Similar to:
```sh
: ; mv does-not-exist /tmp
mv: rename does-not-exist to /tmp/does-not-exist: No such file or directory
```

**Comment by gsbabil** [comment]
@rprimus 

I have the following in `native_messenger.py`:

```
    elif cmd == "move":
        dest = os.path.expanduser(message["to"])
        if (os.path.isfile(dest)):
            reply["code"] = 1
        else:
            try:
                shutil.move(os.path.expanduser(message["from"]), dest)
                reply["code"] = 0
            except Exception:
                reply["code"] = 2
```

At least with the Python messenger, I think the `src` and `dst` inputs to `shutil.move(...)` are correct, and I still get the same error. Did you have better luck with reversing the `src` and `dst` on the Nim version? Thanks.

**Comment by gsbabil** [comment]
@rprimus 

I think you are right about the Nim version. Thanks!

```
        of "move":
            let dest = expandTilde(msg.to.get())
            if fileExists(dest):
                reply.code = some 1
            else:
                try:
                    moveFile(dest,msg.`from`.get())  ## SRC and DST are reversed/incorrect
                    reply.code = some 0
                except OSError:
                    reply.code = some 2
```

**Comment by gsbabil** [comment]
@rprimus 

I just recompiled the `Nim` version with the following and still get the same error as I got with the `Python` messenger (returns `code == 2`): 

`"could not be moved to '~/Documents'. Make sure it doesn't already exist and that all directories of the path exist."`


```Nim
        of "move":
            let dest = expandTilde(msg.to.get())
            if fileExists(dest):
                reply.code = some 1
            else:
                try:
                    moveFile(msg.`from`.get(), dest)
                    reply.code = some 0
                except OSError:
                    reply.code = some 2
```

**Comment by rprimus** [comment]
Fri Feb  5 13:51:39 GMT 2021

@gsbabil 

`msg.from.get()` needs to be wrapped in `expandTilde`,  else `OSError` as `~` is not expanded:

```sh
: ; ~/zff/tridactyl/native/gen_native_message.py 'cmd..move'  'to../tmp/zz' 'from..~/zz' | ./native_main
Got exception ref 0x1060d2050 --> [errorCode = 2,
parent = nil,
name = 0x106071972"OSError",
msg = 0x1060d3060"No such file or directory\10"
"Additional info: \"(\\\"~/zz\\\", \\\"/tmp/zz\\\", \\\"No such file or directory\\\")\"",
trace = 0x1060d4050@[[procname = 0x106071ef1"native_main",
line = 240,
filename = 0x106071e90"/usr/local/src/ff/native_messenger/src/native_main.nim"], [procname = 0x106071ed8"handleMessage",
line = 160,
filename = 0x106071e90"/usr/local/src/ff/native_messenger/src/native_main.nim"], [procname = 0x106071a0e"moveFile",
line = 1855,
filename = 0x1060718b0"/usr/local/Cellar/nim/1.4.2/nim/lib/pure/os.nim"], [procname = 0x1060719dc"tryMoveFSObject",
line = 1836,
filename = 0x1060718b0"/usr/local/Cellar/nim/1.4.2/nim/lib/pure/os.nim"], [procname = 0x10607197a"raiseOSError",
line = 94,
filename = 0x10607192b"/usr/local/Cellar/nim/1.4.2/nim/lib/pure/includes/oserr.nim"]],
up = nil]
with message No such file or directory
Additional info: "(\"~/zz\", \"/tmp/zz\", \"No such file or directory\")"
t{"cmd":null,"version":null,"content":null,"error":null,"command":null,"sep":null,"files":null,"isDir":null,"code":2}%
```

If you try with a fully qualified path, it should work.  The PR takes care of this.

**Comment by rprimus** [comment]
Fri Feb  5 14:10:25 GMT 2021

> and I still get the same error

Have you tried with any other directory/destination apart from `~/Documents`?   On later versions of `macOS`, 
`~/Documents`  and `~/Desktop`  are located on your  `iCloud Drive`.

https://osxdaily.com/2017/07/06/disable-icloud-desktop-documents-mac/

**Comment by gsbabil** [comment]
@rprimus 

> Have you tried with any other directory/destination apart from ~/Documents?

Yes. For example, both `/tmp` and `/private/tmp` equally fails.

> On later versions of macOS, ~/Documents and ~/Desktop are located on your iCloud Drive.

Can confirm that none of directories are on iCloud.

When a new Nim binary is compiled and it's invoked by FF, MacOS (`11.2` for me) asks for permissions for the `native_messenger` binary to access `~/Desktop, ~/Documents` etc. which I granted, but it still failed to perform the `moveFile(...)` correctly.

As mentioned above,  `Python` messenger has the `src/dst` correctly specified and it expands things like `~` correctly, but it still fails with `"operation not permitted"` on MacOS `11.2`.

Thanks.

P.S.

> msg.from.get() needs to be wrapped in expandTilde, else OSError as ~ is not expanded:

Specifying full valid path e.g. `/tmp` or `/Users/test/Documents` also fails. Thanks.

**Comment by gsbabil** [comment]
@rprimus 

```
: ; ~/zff/tridactyl/native/gen_native_message.py 'cmd..move'  'to../tmp/zz' 'from..~/zz' | ./native_main
... ... ...
with message No such file or directory
```

In your test above, are you sure that you had `~/zz` at `$HOME/zz`?

**Comment by rprimus** [comment]
Sat Feb  6 06:55:03 GMT 2021

@gsbabil 

> https://github.com/tridactyl/tridactyl/issues/3290#issuecomment-774374609

What I was showing was that just reversing the arguments - without wrapping - would still cause a failure.

> https://github.com/tridactyl/tridactyl/issues/3290#issuecomment-774374054

Let's take a step back.  In trying to solve your issue, there are two test paths:
1.  From command line
2.  From FF

Each of the above test paths need to be applied to the two artifacts: `native_messanger.py` and `native_main` - so a total of 4 tests.

The CLI tests:
```sh
rm -f /tmp/zz

./gen_native_message.py 'cmd..version' | ./native_main  >> /tmp/zz

./gen_native_message.py 'cmd..move' 'from../tmp/zz' 'to../tmp/zz-1' | ./native_main
cmp /tmp/zz /tmp/zz-1

# cleanup
rm -f /tmp/zz /tmp/zz-1
```

Starting with the `nim` binary:
1. Using the latest artifact (https://github.com/tridactyl/native_messenger/suites/1981902367/artifacts/39456678) or
    compile a local version of [PR-24:native_main.nim](https://github.com/tridactyl/native_messenger/blob/c4bcd6ef109fbc423a6be9d7ea1e161cf03970d7/src/native_main.nim).
    Run the above tests and post the results.

2. In the above tests, replace `./native_main` with `native_messenger.py` and post the results.

If any of the above CLI tests fail, testing via FF will not add any info.
If they both pass, then proceed testing using FF:

3.  Move the `nim` artifact to the directory on your system where `Tridactyl` expects to find it.
     Choose a tab in FF and run `:saveas /tmp/zz-ff`.
      Post what happens next (not just end results) or better yet a screen capture (via animated gif or video) of the test.

4.  Repeat step 3 for the python messenger.

**Comment by gsbabil** [comment]
@rprimus 

Added a new PR fixing the `saveas` issues on MacOS `11.2`. Thanks.

https://github.com/tridactyl/native_messenger/pull/25
