### ISSUE TITLE
`:tabopen .thing` should use searchengine instead of opening url

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#3298]
-   Brief description of the problem: When running `:tabopen .thing`, Tridactyl opens `https://.thing` instead of searching for `.thing` on my favourite search engine.

-   Steps to reproduce: `:tabopen .thing`

-   Tridactyl version (`:version`): 1.20.4pre5069-d5f1093c

-   Firefox version (Top right menu > Help > About Firefox): 84.0.2

**Comment by bovine3dom** [comment]
https://github.com/tridactyl/tridactyl/blob/3d2e5bd6035141f2915f491ca9bcdb74feb827a8/src/lib/webext.ts#L210

just need to change this line
