### ISSUE TITLE
Read-only mode for gui navbar

### ISSUE THREAD

**Issue by aureooms** [tridactyl/tridactyl#3338]
How would one prevent focus (and therefore editing) of the URL in the navbar? I want to access everything from the tridactyl command line but still see the native navbar. Sometimes the navbar is focused and that is annoying.

**Comment by bovine3dom** [comment]
I don't think this is possible without patching Firefox directly - `userChrome.css` can (obviously) only change CSS and you can't prevent focus with CSS - you need JS to set the `readOnly` property.

You can press `<C-,>` to escape from the navbar and return to Tridactyl. (If you use Treestyle Tabs, it will close that sidebar. You can stop Tridactyl from doing that but then you won't be able to escape the navbar)

**Comment by aureooms** [comment]
Sad. Thanks for the escape shortcut! I did not know about it.
