### ISSUE TITLE
New command to sort tabs by container

### ISSUE THREAD

**Issue by hejops** [tridactyl/tridactyl#3364]
As of 22 Jan '21, there is now the option to "sort tabs by container": https://github.com/mozilla/multi-account-containers/commit/68b1b2fe3756c8c60753734c9a9118584f11de46

Can this command be implemented into tridactyl?

**Comment by bovine3dom** [comment]
Do you mean in our `:tabs` command? Or do you mean without MAC installed? I think it should happen automatically if the option is set in MAC

**Comment by hejops** [comment]
Yeah, I suppose I meant without MAC. Would be nice issue such a command via a keybind (currently this involves 2 mouse clicks)

**Comment by bovine3dom** [comment]
```
:jsb browser.tabs.query({}).then(a => console.log(a.sort((l,r)=>l.cookieStoreId < r.cookieStoreId)))
```

is 90% of the way there. We could (also?) add a `:tabsort` command that sorts tabs based on some callback.

Does MAC auto-sort newly opened tabs or does it just sort them once when you ask it to?

**Comment by hejops** [comment]
Hmm, that command didn't seem to work for me. Maybe I'll give it a try on another (cleaner) profile.

MAC only sorts on demand, yes.

**Comment by bovine3dom** [comment]
Sorry, that won't do anything. It does everything except sort the tabs : )

It was a note to myself for implementation.

**Comment by bovine3dom** [comment]
`:tabsort --containers` in the latest betas (probably available once this post is ~5 minutes old)
