### ISSUE TITLE
Cannot install native messenger on Windows behind a proxy

### ISSUE THREAD

**Issue by bew** [tridactyl/tridactyl#3371]
Operating system: Windows 10, build 1909

**Brief description of the problem**:

I'm trying to install the native-messenger on windows, but I don't have direct access to the internet, I must pass though a proxy.

I downloaded the `win_install.ps1` separately (with a msys2 shell), then tried to run `powershell -NoProfile -File win_install.ps1 -Tag 1.20.4` but I get:

```
[+] Looking for Python 3 ...
    - Python 3 not found, will use EXE ...
[+] Preparing C:\Users\bdecheze100119\.tridactyl ...
    - Testing C:\Users\bdecheze100119\.tridactyl was successful!
    - Creating C:\Users\bdecheze100119\.tridactyl was successful!
[+] Downloading https://tridactyl.cmcaine.co.uk/betas/native_main.exe ...
Invoke-WebRequest Exception: System.Net.WebException The remote server returned an error: (407) Proxy Authentication Required.
Invoke-WebRequest StatusCode: 407
Invoke-WebRequest StatusDescription: authenticationrequired
[+] Downloading failed, quitting ...
```

I've exported the env vars `https_proxy` in msys2 shell hoping it would pass to powershell, but it doesn't seem to work.

**Comment by Rummskartoffel** [comment]
The variable should be set, but PowerShell doesn't know what to do with it. I know little about proxies, but try doing the following in Powershell:
```powershell
[System.Net.WebRequest]::DefaultWebProxy = New-Object System.Net.WebProxy('<your proxy>')
[System.NetWebRequest]::DefaultWebProxy.Credentials = Get-Credential
```
Then run the installer in the same shell. If it doesn't work, see [the site I got this from](http://woshub.com/using-powershell-behind-a-proxy/), maybe something else on there will.
If it does work, automatic updates should be possible by adding those two commands to your `nativeinstallcmd`.

**Comment by bew** [comment]
I changed my mind and don't actually need the native messenger anymore.

And I'm actually not allowed to use Firefox anyway on this computer, so I won't be able to test either.

I'll still leave the  issue open if someone needs this

**Comment by bovine3dom** [comment]
Closing this as we have switched to the Nim messenger, hoping this issue disappeared with that.
