### ISSUE TITLE
Missing Privacy Policy

### ISSUE THREAD

**Issue by una-engelkes** [tridactyl/tridactyl#3375]
I noticed that tridactyl has no privacy policy stated on AMO or in this repo. I believe that nowadays having a privacy policy is bon ton and even more so for tridactyl after its excellent job at explaining the needs for its permissions.

A thing worth noting in the policy is, I think, that for "beta" builds the update mechanism does not contact addons.mozilla.org but tridactyl.cmcaine.co.uk.

Regards and thanks for your amazing addon!

**Comment by bovine3dom** [comment]
Hi, thanks for raising this.

The only thing we do is log IPs and requests to that cmcaine.co.uk server.

If you think it's important, I'd be happy to add a privacy policy that says we don't collect any data outside of that.

**Comment by una-engelkes** [comment]
Hi, thanks for your reply

> The only thing we do is log IPs and requests to that cmcaine.co.uk server.

I did not expect anything else.

> If you think it's important, I'd be happy to add a privacy policy that says we don't collect any data outside of that.

I consider having a privacy policy medium to important (it was worth creating a GitHub account for it ;-r) ). Personally, for me it is a sign that the developer(s) care(s).  Similar to explaining to your users why some permissions are needed or declaring upfront what license the code is released under.  Having a policy makes (in my eyes) a much better impression.

To safe you some digging, here are some privacy polices I stumbled upon while browsing AMO and selecting my addons (here a good impression did play a role). These are meant to give you some inspiration about aspects which might or might not be applicable to tridactyl and you might or might not want to cover.

* [Vimium C](https://addons.mozilla.org/af/firefox/addon/vimium-c/), [Privacy Policy](https://addons.mozilla.org/af/firefox/addon/vimium-c/privacy/), your competitor

* [Decentraleyes](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/) [Privacy Policy](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/privacy/), a simple one

* [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/), [Privacy Policy](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/privacy/), mentions GitHub as host

* [Proxy Switchy Omega](https://addons.mozilla.org/af/firefox/addon/switchyomega/), [Privacy Policy](https://github.com/FelisCatus/SwitchyOmega/wiki/Privacy), mentions provider of the sync settings facility (Google in this case) but probably applicable to Firefox sync, too.

* [Dark Reader](https://addons.mozilla.org/en-US/firefox/addon/darkreader/), [Privacy Policy](https://addons.mozilla.org/en-US/firefox/addon/darkreader/privacy/), mentions PayPal/Sponsoring and has a "maybe in the future we will collect data" clause

* [True Sight](https://addons.mozilla.org/en-US/firefox/addon/detect-cloudflare-plus/), [Privacy Policy](https://addons.mozilla.org/en-US/firefox/addon/detect-cloudflare-plus/privacy/), pledges to ask for user's explicit consent if its collecting-behaviour ever changes.

* [ClearURLs](https://addons.mozilla.org/en-US/firefox/addon/clearurls/), [Privacy Policy](https://addons.mozilla.org/en-US/firefox/addon/clearurls/privacy/), mentions its update mechanism will connect to a third-party server.
