### ISSUE TITLE
blacklist and feedbin

### ISSUE THREAD

**Issue by cooperpellaton** [tridactyl/tridactyl#3380]
-   Brief description of the problem:
[Feedbin](https://feedbin.com/) offers native vim keybinds for navigating through feeds/articles. Tridactyl interferes rendering them useless. Disabling Tridactyl through `noiframe true` and `blaclistadd feedbin.com` has no effect on base keybinds `hjkl`.

-   Steps to reproduce:

    1. Sign into Feedbin
    2. Navigate using `hjkl`. 

-   Tridactyl version (`:version`): 1.20.4

-   Firefox version (Top right menu > Help > About Firefox): 85.0.2

-   URL of the website the bug happens on: [https://feedbin.com](https://feedbin.com/)

-   Config (in a new tab, run `:viewconfig --user`, copy the url and paste it somewhere like gist.github.com): [gist](https://gist.github.com/cooperpellaton/4facf9af651a598e38e1882c0111c575)

**Comment by bovine3dom** [comment]
It works fine for me:

```
:blacklistadd https://feedbin.com/
:open feedbin.com # then login
# I'm in ignore mode, pressing j/k switches between items
```

You don't need `noiframe true`.

Your `DocStart` entries look a bit dodgy. I'd suggest running:

```
:blacklistremove undefined
:blacklistremove feedbin.com
:blacklistremove feedbin.com/
:blacklistremove fastmail.com
:unseturl feedbin.com noiframe
```

**Comment by cooperpellaton** [comment]
Followed the above, but am still experiencing the same problem. Diff'd configs:
```diff
3c3
<         "lastchecktime": 1613537821008,
---
>         "lastchecktime": 1613624785179,
14,18c14,15
<             "undefined": "mode ignore",
<             "feedbin.com": "mode ignore",
<             "feedbin.com/": "mode ignore",
<             "https://feedbin.com": "mode ignore",
<             "fastmail.com": "mode!ignore"
---
>             "fastmail.com": "mode ignore",
>             "https://feedbin.com/": "mode ignore"
34,35c31,42
<         "feedbin.com": {
<             "noiframe": "true"
---
>         "feedbin.com": {},
>         "www.google.com": {
>             "followpagepatterns": {
>                 "next": "Next",
>                 "prev": "Previous"
>             }
>         },
>         "^https://web.whatsapp.com": {
>             "nmaps": {
>                 "f": "hint -c [tabindex]:not(.two)>div,a",
>                 "F": "hint -bc [tabindex]:not(.two)>div,a"
>             }
```

**Comment by cooperpellaton** [comment]
It turns out there was a bad regex in another `DocStart` command. After removing that it now works :facepalm:. Thank you for the debug assistance!

**Comment by bovine3dom** [comment]
If it's just a few binds you need to use you might prefer to use `unbindurl`.
