### ISSUE TITLE
How to load a JS file from tridactylrc?

### ISSUE THREAD

**Issue by abvbv** [tridactyl/tridactyl#3394]
Everything works if I do `:source`, but I'd like it to load on its own. So I have lines like these in my rc file:

```
js -r example.js
bindurl https://example.com/ gl composite js window.example_doSomething()
```

And `example.js` is like `window.example_doSomething() = function() { alert("Hello") }`. 

But if I press `gl` on `example.com` it says `# controller in excmd: TypeError: window.example_doSomething is not a function`.

I also tried `composite js -r example.js | bindurl https://example.com/ gl composite js window.example_doSomething()`, but it doesn't work either.

So what's the correct way to load a .js file from tridactylrc?

-   Tridactyl version: 1.20.4
-   Tridactyl native version: 0.1.11
-   Firefox version: 85
-   Operating system: NixOS (using [tridactyl-native](https://github.com/NixOS/nixpkgs/blob/04ee910d531e721022c15e317ee7305d68515675/pkgs/tools/networking/tridactyl-native/default.nix) package)

As I've been writing this issue, I discovered there's a separate repo for [native_messenger](https://github.com/tridactyl/native_messenger/). But my `:nativeinstall` doesn't mention it. So I suppose 0.1.11 version is still used today?

**Comment by bovine3dom** [comment]
```
//example.js
alert("hello")
```

```
" tridactylrc
bindurl https://example.com/ gl js -r example.js
```

The trouble with your way is twofold: `js` runs in a tab, but source runs in a special background script. `jsb` works but has no useful window object.

The second problem is that you need to run that js every time the page changes. With my suggestion you run it every time you hit the bind.

---

Yes, 0.1.11 is fine for native. We're releasing a new version soon - 0.2.x is used in Tridactyl beta.

**Comment by abvbv** [comment]
This works, thank you!

Does it mean you need to put each function in a separate file for it to work? I tried to pass `JS_ARG`, but it doesn't work with `js -r` apparently.

**Comment by bovine3dom** [comment]
> Does it mean you need to put each function in a separate file for it to work? 

The way I suggested, yeah. If your functions are short you can write them inline in the RC file e.g.

```
command loud_echo js -p alert( \
    JS_ARG \
)
```

Note that you can also source extra RC files within RC files, so

```
source commands_rc
```

would work.

> I tried to pass `JS_ARG`, but it doesn't work with `js -r` apparently.

`js -r -p` should work. Untested for now but I looked at the code and it looks fine.

> Maybe I just have a wrong concept in my mind. I'd like to have a .js file per website to define there various functions that are specific to the site, and bindurl these functions in tridactylrc.

I would personally just write the JS inline as I suggested above. The trouble with `js -r` is that it reads from disk each time it is run, so it is quite slow. `command xyz js ...` is stored in memory instead.

However, if you really want to do it your way, you can do 

```
autocmd DocStart [url] js -r [...]
bindurl example.com gl js window.example_doSomething()
```

> 
> > The trouble with your way is twofold
> 
> What would you recommend to read to understand these issues? Even after reading your comment I don't really understand what's the problem.

`:help js`, `:help jsb`, `:help source` all explain bits of this. We don't really have any great documenation for it yet - #3281. Essentially with js/jsb you are writing your own WebExtension, so MDN's docs are a good source of information.

Coincidentally the tips-and-tricks newsletter for donors this month will be on writing your own ex-commands (once I finish it...), so with a favourable wind it will become a wiki page or something within a few months.

**Comment by abvbv** [comment]
Thank you, Oliver, that's really helpful. It's much more clear for me now.
