### ISSUE TITLE
Pass visual selection to tabopen without opening command line?

### ISSUE THREAD

**Issue by hejops** [tridactyl/tridactyl#3428]
I currently use the following mapping to achieve this:

`bind --mode=visual S composite js document.getSelection().toString() | fillcmdline tabopen | ex.accept_line`

but I'm fairly certain there's a simpler/less ugly way to do this. Is there a built-in command I wasn't aware of?

**Comment by bovine3dom** [comment]
`bind --mode=visual S composite js document.getSelection().toString() | tabopen`

: )

**Comment by hejops** [comment]
Thanks! :smile:
