### ISSUE TITLE
[FR]Add mouse_mode to revert no_mouse_mode

### ISSUE THREAD

**Issue by DhruvaSambrani** [tridactyl/tridactyl#3431]
Tridactyl version: 1.21.0
Firefox version: Waterfox Ltd. Waterfox 78.8.0
Operating system: win

# Making a feature request

`no_mouse_mode` is an awesome trick to force me to use the keyboard as I'm learning, but I need to somehow unset this. The docs suggest reloading the page, but due to the DocLoad no_mouse_mode autocmd, it will get reset. If such a thing be made, then I can add a keybinding to unset it and use the mouse when I need to do something quickly

**Comment by bovine3dom** [comment]
Should be reasonably straightforward - just delete the elements made by this function (and probably cancel the setInterval) https://github.com/tridactyl/tridactyl/blob/191ac7c067754cd60a5787e05f891e424cc2099a/src/content/toys.ts#L25

As an aside it might be worth making it more sane while you're there. `:no_mouse_mode` was originally what `:neo_mouse_mode` is now, which I added as a joke. People asked me to make it less hilarious and I did so in a very lazy way.

**Comment by DhruvaSambrani** [comment]
More sane how? 
One thing I can see is that we are simply redrawing for no_mouse, so the setinterval should be activated only if the chars to print is non empty

**Comment by DhruvaSambrani** [comment]
How ok are you with using non-standard attributes for the div element? I need to store the Interval id to unset it, so I was planning to store it in the div itself.

**Comment by bovine3dom** [comment]
That's probably fine.

On sanity: yeah, the main issue is setInterval but in terms of tidiness most of that code from https://github.com/tridactyl/tridactyl/blob/191ac7c067754cd60a5787e05f891e424cc2099a/src/content/toys.ts#L46 onwards is irrelevant, so it should probably be split out into another function.
