### ISSUE TITLE
Windows 10 rc and theme locations not found

### ISSUE THREAD

**Issue by StarTroop** [tridactyl/tridactyl#3467]
Tridactyl version: 1.21.0
Firefox version: Mozilla Firefox 86.0.1
Operating system: win
Native messenger version: 0.3.4

-   Brief description of the problem:
Since I solved my last problem of not being able to load a local theme on my Linux machine (due to user error), I've now moved on to doing the same on my Windows machine, but I'm running into a new problem.

No matter where I put my rc and themes folder, I always get the same error when I try to run `:colourscheme`. The error message is:

```
controller in excmd: Error: getrcpath error: 1
```

I've tried to do my research on the issue, but nothing I've tried helps. I've used these two past issues as reference, but haven't come up with a working solution.  #1925 #1796

In my efforts I've tried placing my rc and themes folder in various locations in my user folder (e.g. under '.tridactyl' made by native installer, under '_config', '.config', and even directly in my user folder). I've set HOME as an env variable, I've installed latest version of Python and put in in my Path (result of echo: `C:\Program Files\Mozilla Firefox;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\altho\adb-fastboot\platform-tools;C:\Users\altho\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\altho\AppData\Local\Programs\Python\Python39\;C:\Users\altho\AppData\Local\Microsoft\WindowsApps `). If it's at all relevant, my rc was empty throughout most of my testing, although I added `js alert()` at one point to help identify if it started working.

None of the related issues I've found seemed to have been confirmed to be solved, so I'm not sure if this has ever been worked in Windows. Has anyone ever confirmed that it's working correctly?

**Comment by bovine3dom** [comment]
> If it's at all relevant, my rc was empty throughout most of my testing, although I added js alert() at one point to help identify if it started working.

So `:source` doesn't work either? You don't see the alert?

---

I'm a bit worried about your native messenger version. How did you install it? You shouldn't have got that version alongside Tridactyl stable - either we have a bug or you were intrepid and installed it outside of `:nativeinstall`. Not related to this issue but potentially a new one.

---

Could you run this script in powershell to install an older native messenger? 
https://github.com/tridactyl/tridactyl/blob/master/native/win_install.ps1

I'm assuming it's a bug we have introduced with the new messenger.

**Comment by bovine3dom** [comment]
Thanks, that's two separate issues you've uncovered there : )

**Comment by StarTroop** [comment]
Okay, so I removed the 0.3.4 version and tested both the deprecated installer you linked, and the latest version from native_messenger repo. I've confirmed that the first time I installed it was the official latest release (windows.ps1), which still did not work correctly. The copy+paste method with `:nativeinstall` did not work. The output in cmd reads:
```
File C:\Users\altho\AppData\Local\Temp\tridactyl_installnative.ps1 cannot be loaded because running scripts is
disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

I suppose this might be something that can be fixed on the user end, but I'm not so keen on overriding security measures just for this, unless the measure is basically ineffective anyway.

Subsequently, reinstalling with the deprecated version (win_install.ps1) **did** work, and is now reported as 0.1.10, even after `:nativeupdate`. I don't know if the reported version numbers are accurate, or if I'm missing any functionality from being out of date, but my rc is now being recognised and my theme is loaded correctly.

Let me know if there's anything I can do to help test or troubleshoot potential fixes for the official release.

**Comment by Rummskartoffel** [comment]
I don't think there's a separate problem with the update mechanism here. Since `:updatenative` does nothing more than running the install script for you, of course that doesn't work either when the execution policy isn't bypassed.

**Comment by bovine3dom** [comment]
> Let me know if there's anything I can do to help test or troubleshoot potential fixes for the official release

I wanted to know if you got the same rcpath error on 0.1.x : )

**Comment by StarTroop** [comment]
Nope, with version 0.1.10 installed with the deprecated win_install.ps1 script, everything appears to be working. No more rcpath error.

**Comment by bovine3dom** [comment]
Thanks, that's useful, it will help us to debug it : )

We might be back to ask more questions.

**Comment by Rummskartoffel** [comment]
I think [this](https://github.com/tridactyl/native_messenger/blob/8d635890d8344b52afe82ee0a4c6dd0590720375/src/native_main.nim#L85-L90) may be the culprit.
* L86: [`getConfigDir()`](https://github.com/nim-lang/Nim/blob/version-1-4/lib/pure/os.nim#L909) returns `C:\Users\<username>\AppData\Roaming` on Windows.
* L88: `%USERPROFILE%\_config` and what I can only assume must be interpreted as `C:\tridactyl\tridactylrc`.

**Comment by bovine3dom** [comment]
```
getHomeDir() / "_config", "tridactyl" / "tridactylrc",
```

Is a crafty typo, it should be 

```
getHomeDir() / "_config" / "tridactyl" / "tridactylrc"
```

obviously
