### ISSUE TITLE
nextpattern, previouspattern

### ISSUE THREAD

**Issue by h2ero** [tridactyl/tridactyl#3490]
The configuration item is not found in tridactyl help, Is it possible to support it?

like this:

```
  options.add(["nextpattern"],
            "Patterns to use when guessing the next page in a document sequence",
            "regexplist", UTF8(/'^\s*Next Page\s*$','^\s*Next [>»]','\bnext\b',^>$,^(>>|»)$,^(>|»),(>|»)$,'\bmore\b'/.source),
            { regexpFlags: "i" });

        options.add(["previouspattern"],
            "Patterns to use when guessing the previous page in a document sequence",
            "regexplist", UTF8(/'^\s*Prev(ious)? Page\s*$','[<«] Prev\s*$','\bprev(ious)?\b',^<$,^(<<|«)$,^(<|«),(<|«)$/.source),
            { regexpFlags: "i" });

```

https://github.com/pentadactyl/pentadactyl/blob/afb7054cdd8aae8ffaf842fff0db14c4551d32fc/common/modules/buffer.jsm#L2673

**Comment by h2ero** [comment]
I have solved it.

```
bind ]] composite js  -r next.js
```
next.js 

```
document.querySelectorAll("a").forEach(function(item) {
    if(item.textContent.match(/(\s*[下后][一]?[节页张个篇章頁首]\s*|← Older|Older|››)/)){
        item.click();
    }
})
```

**Comment by bovine3dom** [comment]
We do have these settings - `:set followpage.next` and `followpage.prev` - but it's one RegEx rather than an array.

https://github.com/tridactyl/tridactyl/blob/df8a745f62b3c89b42998f496a2fd3240f42f664/src/lib/config.ts#L627

**Comment by h2ero** [comment]
> We do have these settings - `:set followpage.next` and `followpage.prev` - but it's one RegEx rather than an array.
> 
> https://github.com/tridactyl/tridactyl/blob/df8a745f62b3c89b42998f496a2fd3240f42f664/src/lib/config.ts#L627

nice!!!  test it work fine

set followpagepatterns.next (\s*[下后][一]?[节页张个篇章頁首]\s*|← Older|Older|››|(next|newer|prochain|suivant)\b|→|»|>>)
set followpagepatterns.prev (\s*[上前][一]?[节页张个篇頁章首]\s*|Newer →|Newer|‹‹|(prev(ious)?|older|précédent)\b|←|«|<<)
