### ISSUE TITLE
Consider switching to esbuild

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#3498]
It claims to be x times faster than webpack. Tridactyl being slow to build is one of my pet hates so this could improve my life if we can get it working.

https://github.com/evanw/esbuild

**Comment by Rummskartoffel** [comment]
One related pet hate I have is that `yarn install` is slow – which indirectly also makes switching branches and pulling/merging slow –, which I believe is due in part or even mostly to webpack's dependencies. Maybe using esbuild would improve that as well.

**Comment by bovine3dom** [comment]
If you want to better appreciate how quick yarn is, symlink it to npm and see what we used to put up with : D

**Comment by bovine3dom** [comment]
Notes on moving to `esbuild` entirely:

```
yarn run esbuild src/content.ts --bundle --target=firefox68 --outfile=build/content.js
yarn run esbuild src/background.ts --bundle --target=firefox68 --outfile=build/background.js
```

is 90% of the way there but some packages we use need shims - https://github.com/tridactyl/tridactyl/blob/f5359f3370806fc503bdde70879be70a9ceb0c92/webpack.config.js#L33

Need to work out how to do those with `esbuild` or stop using the offending packages (`rss-parser` and `css`).

```
 > node_modules/css/lib/stringify/source-map-support.js:10:19: error: Could not resolve "path" (set platform to "node" when building for node)
    10 │ var path = require('path');
```

It looks like https://esbuild.github.io/api/#inject is the way to do it.

**Comment by bovine3dom** [comment]
^ most of this is now resolved in #3498 (package.json "browser" field takes care of it).

I'll leave this issue open as it would be nice to drop `webpack` for the full-fat builds too.

**Comment by bovine3dom** [comment]
> 
> 
> Struggling to work out how to replicate the old compilation / type checking - `tsc --project tsconfig.json --noEmit` gives me errors (on `master`) too.
> 
> Stuff like
> 
> ```
> src/completions/Sessions.ts:1:27 - error TS2691: An import path cannot end with a '.ts' extension. Consider importing '@src/lib/webext.js' instead.
> ```
> 
> which is clearly a lie as most of Tridactyl would be broken otherwise.

That error is correct, Webpack just doesn't follow "vanilla" TypeScript in that regard. Import paths ending in ".ts" are a long-standing WONTFIX for TS, as far as I know.

_Originally posted by @Rummskartoffel in https://github.com/tridactyl/tridactyl/pull/3554#issuecomment-826361192_

**Comment by bovine3dom** [comment]
With d9fe1bed..afda42e7 I've reduced the `tsc --project tsconfig.json --noEmit` errors to just

```
node_modules/rss-parser/index.d.ts:2:32 - error TS2307: Cannot find module 'https' or its corresponding type declarations.

2 import { RequestOptions } from 'https';
```

I haven't worked out why - in theory https://github.com/tridactyl/tridactyl/blob/afda42e7f99ae9b5d7fa5b98e658e6b754f8298e/package.json#L8

should prevent that error. I tried switching to `https-browserify` but that didn't work either.

**Comment by Rummskartoffel** [comment]
`https-browserify` can't help because it doesn't provide any type declarations. But does TypeScript even respect the `browser` field, anyway?

**Comment by bovine3dom** [comment]
https://github.com/tridactyl/tridactyl/pull/3645/commits/d54b9bcc24f82f21f94847c6c1a4328855563443 gets rid of the error but I'm pretty sure it's a terrible idea to pretend all of node is available when it isn't.

Upstream issue: https://github.com/rbren/rss-parser/issues/198

**Comment by Rummskartoffel** [comment]
Yeah, I tried that as well. We're probably not going to get around this without some kind of upstream fix, but Tridactyl is only using this package in one single place, anyway, so maybe we can just get rid of it entirely?

**Comment by bovine3dom** [comment]
Perhaps. It's a little bit gnarly but not too bad:

```js
let x = document
fetch("https://github.com/tridactyl/tridactyl/tags.atom").then(r => r.text().then(r => console.log((new DOMParser).parseFromString(r, "application/xml"))))
// wait a bit
x.querySelectorAll("entry")[0].querySelector("title").textContent
new Date(x.querySelectorAll("entry")[0].querySelector("pubDate").textContent) // error - it looks like `pubDate` has been replaced with `updated`?
```

**Comment by Rummskartoffel** [comment]
Huh, I didn't even consider that. I was thinking of using GitHub's API, but that doesn't seem to have an easy way of getting the newest tag, either.
