### ISSUE TITLE
Can I pipe the html source of the current page into an arbitrary file in my computer?

### ISSUE THREAD

**Issue by honestSalami** [tridactyl/tridactyl#3512]
Tridactyl version: 1.21.1
Firefox version: Mozilla Firefox 86.0.1
Operating system: linux

-   Brief description of the question:

Can I pipe the html source of the page I'm currently on to an arbitrary file in my computer?
My first guess is using the `native` shell support, but I have not idea how to research it.

I tried something like ```:viewsource >> ~/myfile```, but it did not work.

**Comment by bovine3dom** [comment]
I don't think anyone has asked this before. The best way is probably to use `:js`:

```
:js (async () => {let current = await tri.native.read("~/myfile"); let appended = [current, document.documentElement.innerHTML].join("\n"); tri.native.write("~/myfile", appended)})()
```

Untested but I think it should work.

If you need to make myfile into a variable you can do that too with `js -p` and `command`.

**Comment by Rummskartoffel** [comment]
Use `document.documentElement.outerHTML`, not `document.documentElement.innerHTML`, otherwise you'll be missing the `<html>` tag.

**Comment by honestSalami** [comment]
you guys are always so kind with my weird questions.

Anyways, I tried the javascript and could not find the file on my computer. I'm pressed for time, so I'll try something else. But thanks for the quick help!

**Comment by bovine3dom** [comment]
@honestSalami it works for me. I think you probably just don't have `:native` installed. Because `tri.native` is an internal API, we don't bother to check, so you probably won't see a helpful error message.
