### ISSUE TITLE
:containerdelete causes all tabs to be closed when an unexistent container name is passed

### ISSUE THREAD

**Issue by rdrg109** [tridactyl/tridactyl#3526]
# Brief description of the problem

Firefox prompts to close all tabs when an unexistent container name is passed as an argument to the command `:containerdelete`.

# Steps to reproduce

1. Find a container name that doesn't exist. You can list all existing containers by executing `:viewcontainers`. 
2. Execute `:containerdelete {name}`, where `{name}` is the name of the container obtained in the first step.

Firefox must show a prompt to close all tabs.

I was able to reproduce this issue in a newly created Firefox profile to make sure that any of my Tridactyl, `user.js`, `userContent.css`, `userChrome.css` configurations were not causing this behavior.

# System information

+ Tridactyl version: 1.21.1
+ Firefox version: Mozilla Firefox 87.0 (64-bit) for Arch Linux.
+ URL of the website the bug happens on: It happens regardless of the website or the number of tabs that are opened.
+ Config: I reproduced the issue after having deleted the configuration file `~/.config/tridactyl/tridactylrc` so this issue occurs regardless of the configurations.
+ Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc: As I wrote in the line above, I didn't have a `~/.config/tridactyl/tridactylrc` file.

# Additional information

I've the following in my `user.js` file. This configuration makes the warning that is shown when multiple tabs are being closed not to be shown, so the prompt is not shown which means that all tabs are closed without any prompt, so, in other words, Firefox is closed regardless of the number of tabs.

``` js
user_pref("browser.tabs.warnOnClose", false);
```

# Personal thoughts

I think that it must be better if a warning is shown when a unexistent container has been passed to the `:containerdelete` command just as happens when an unexistent container name is passed to `:tabopen` as shown below.

```
tabopen -c unexistent-container wikipedia.org
controller in excmd: Error: [Container.fuzzyMatch] no container matched that string
```

**Comment by Rummskartoffel** [comment]
`:containerdelete` calls `:containerclose`, which does this:
https://github.com/tridactyl/tridactyl/blob/62f8804eaf2db67363b3287a11182da24ca47c86/src/excmds.ts#L2927-L2928
If no container of `name` exists, `getId()` returns `Promise<undefined>` instead of throwing an error. The query on the next line therefore matches all tabs, all of which are then closed.
