### ISSUE TITLE
`guiset` throws unintelligble error on malformed userChrome.css

### ISSUE THREAD

**Issue by Sweenu** [tridactyl/tridactyl#3527]
Any time I try to run a `guiset` command, it fails with the following message:
```
# controller in excmd: Error: undefined:131:467: missing '}'
```
Couldn't find any logs to help me out.

Tridactyl version: 1.21.1
Firefox version: Mozilla Firefox 87.0
Operating system: linux
`$PATH` from tridactyl: `/home/sweenu/.poetry/bin:/home/sweenu/.local/bin:/home/sweenu/.go/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
`native_main` command output: `{"cmd":"run","content":"/home/sweenu/.poetry/bin:/home/sweenu/.local/bin:/home/sweenu/.go/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl\n","command":"echo $PATH","code":0}`

**Comment by bovine3dom** [comment]
Thanks for reporting this.

What's the output of `:native`?

**Comment by bovine3dom** [comment]
Could you also give us the content of `[firefox profile directory]/chrome/userChrome.css`, if it exists? You can find your profile directory on `about:support`.

**Comment by Sweenu** [comment]
Oh that's it, thank you, I totally forgot I was using a special theme (https://github.com/fellowish/firefox-review). Removing the theme solved the problem.
Thank you for your quick help and thank you for this awesome program :)

**Comment by bovine3dom** [comment]
I'm going to re-open this issue because that error message could be _much_ more informative : )
