### ISSUE TITLE
"source --url" does not handle data URLs properly

### ISSUE THREAD

**Issue by Plaunarome** [tridactyl/tridactyl#3535]
* Brief description of the problem:

When attempting to use a [data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) with `source --url`, the command fails.

Using a data URL like this is useful for sourcing a `tridactylrc` without having the native messenger installed.

* Steps to reproduce:

1. Execute `source --url data:text/plain,set%20newtab%20about:blank`
2. The command fails (notice the extra `http://` that appears in front of the data URL in the output):

```
:# controller in excmd: Error: Window.fetch: http://data:text/plain,set%20newtab%20about:blank is not a valid URL.
```

* Tridactyl version: 1.21.1
* Firefox version: 87.0 (running on Arch Linux)
* `viewconfig --user`:

```
{"configversion":"2.0"}
```

**Comment by bovine3dom** [comment]
Thanks for reporting this.

In the meantime have you considered using a local web server, e.g. caddy, to serve the file?

**Comment by Plaunarome** [comment]
Thanks for the prompt reply!

I already setup a simple server that serves my configuration file which worked.
