### ISSUE TITLE
:tabopen doesn't open the tab in the assigned container when multiple regexps matches the URL

### ISSUE THREAD

**Issue by rdrg109** [tridactyl/tridactyl#3545]
# Brief description of the issue

When there are two regular expressions in the variable `autocontain` that matches a given URL, `tabopen` doesn't open the URL in the given container.

You can find two GIFs below which exposes this issue with more specific details.

# The issue

In the GIF shown below, we can see that when we execute the following commands sequentially, the URL `pt.stackoverflow.com` is opened in the container.

```conf
sanitise commandline tridactyllocal tridactylsync

autocontain -s pt\.stackoverflow\.com Work

tabopen pt.stackoverflow.com
```

![2021_04_02__15_27_08](https://user-images.githubusercontent.com/74389646/113452763-4e397f80-93ca-11eb-8729-af41299dd368.gif)

While in the GIF shown below, we can see that when we execute the following commands sequentially, the URL `pt.stackoverflow.com` is ****not**** opened in the container.

```conf
sanitise commandline tridactyllocal tridactylsync

autocontain -s stackoverflow\.com Work
autocontain -s pt\.stackoverflow\.com Work

tabopen pt.stackoverflow.com
```

![2021_04_02__15_29_55](https://user-images.githubusercontent.com/74389646/113452780-5691ba80-93ca-11eb-882b-86ede3a68257.gif)

# System information

-   Tridactyl version: 1.21.1
-   Firefox version: Mozilla Firefox 87.0 (64-bit) for Arch Linux.
-   URL of the website the bug happens on: It happens regardless of the website or the number of tabs that are opened.
-   Config: I reproduced the issue before having deleted the configuration file `~/.config/tridactyl/tridactylrc` (as seen in the GIF) so this issue occurs regardless of the configurations.
-   Contents of `~/.tridactylrc` or `~/.config/tridactyl/tridactylrc`: As I wrote in the line above, I didn't have a \`~/.config/tridactyl/tridactylrc\` file.

**Comment by bovine3dom** [comment]
The "specificity" of a RegEx is (perhaps obviously) not trivial. I suppose we should just pick the longest one which matches.

**Comment by rdrg109** [comment]
Yes. Picking the regex from which the longest match can be obtained seems to be the most reasonable solution.

**Comment by aureooms** [comment]
@bovine3dom  Another option is to pick the first pattern that matches. Although I do not know if *first* is well defined.

**Comment by bovine3dom** [comment]
I think that could be confusing to users - it would probably just pick the oldest `autocontain` directive that matches, which could well be the opposite of what the user would want. I think longest is probably the safest proxy for specificity that we have : )
