### ISSUE TITLE
[FR] Mouse drawing mode

### ISSUE THREAD

**Issue by DhruvaSambrani** [tridactyl/tridactyl#3546]
Tridactyl version: 1.21.1
Firefox version: Waterfox Ltd. Waterfox 78.9.0
Operating system: win

# Making a feature request

**Add a annotation/drawing mode**
This mode should allow the user to draw on the page.
This can be implemented using a mechanism similar to the no_mouse_mode, where a canvas is added which reacts to drawing commands. Ideally the canvas should be as big as the `document`(not just as big as the `window`), and should scroll with the page.

While I guess that this feature is out of the scope of this project, I'm just shooting my shot I guess 😅

**Comment by bovine3dom** [comment]
Why in particular would you like this in Tridactyl? Aren't there other extensions that already do this well?

**Comment by DhruvaSambrani** [comment]
Tbf, no specific reason. I just thought it would be a nice addition, and I'd not need to install other extensions. Please go ahead and close the issue if you feel this doesn't come in the scope of this extension 😁

**Comment by bovine3dom** [comment]
If someone really wants to add it I'd merge it provided it wasn't too much code (<300 lines), so I'll leave the issue open : )

**Comment by glacambre** [comment]
This can be implemented with a (long) alias:
`:alias canvas js let c = document.createElement("canvas"); document.body.appendChild(c); c.style.position = "fixed"; c.style.top = c.style.left = "0px"; c.style.width = window.innerWidth + "px"; c.style.height = window.innerHeight + "px"; c.width = window.innerWidth; c.height = window.innerHeight; const state = { mousedown: false, context: c.getContext("2d"), x: 0, y:0 }; c.addEventListener("mousedown", () => state.mousedown = true); c.addEventListener("mouseup", () => state.mousedown = false); c.addEventListener("mousemove", e => { state.x = e.clientX; state.y = e.clientY }); function draw() { window.requestAnimationFrame(() => { state.context.fillStyle = "black"; if (state.mousedown) { state.context.fillRect(state.x, state.y, 3, 3) }; draw() })}; draw()`

**Comment by DhruvaSambrani** [comment]
Oh nice!

However, won't making height = window.innerheight make it only as large as the window and prevent scrolling with the page?

I'm not well versed with css placements and sizing, but can it be bound to the size and placement of the <body> instead?

Also, can mouseevents be "ignored" according to some condition? If so, can we add a "draw" mode to tridactyl, which allows us to add some keybindings to draw, erase and clear? While your suggestion works very well for a quick draw, can it be polished into a full blown feature(<300 lines, which I think we can achieve, ~~but even if we don't, we can minify it and store it in a single like 🤭~~)

**Comment by glacambre** [comment]
Sure, all of that is possible, just edit the snippet to make it do what you need :)
