### ISSUE TITLE
Infinite Refresh While Opening The Webpage

### ISSUE THREAD

**Issue by shahab-vahedi** [tridactyl/tridactyl#355]
There are a few addresses that when you try to open, if Tridactyl is enabled, you will see that the tab is stuck in a never-ending "transferring data / requesting connection". One example would be:

http://uploaded.net/file/7opca0dt/National.Geographic.Ninja.Shrimp.HDTV.XviD-OTV.avi

I tried this with plain Firefox and Tridactyl enabled only (no other addons). However, if you disable Tridactyl, it loads OK.

I am using Firefox 59.0.1 (64-bit) on Arch Linux. Tidactyl's version is 1.8.2-1.8.2 (derived from "new tab" page).

**Comment by cmcaine** [comment]
Thank you for the report. We understand why it's happening and we're working on fixing it.

**Comment by bovine3dom** [comment]
@cmcaine is this fixed now? Unfortunately, the link supplied is broken (404).

**Comment by cmcaine** [comment]
Fixed on similar sites.

**Comment by shahvah** [comment]
it's doing it again:
http://uploaded.net/file/jg7rre7u/12.Monkeys.S04E01.The.End.720p.AMZN.WEB-DL.DDP5.1.H.264-NTG.mkv

**Comment by bovine3dom** [comment]
Reproducible.

**Comment by shahvah** [comment]
I am seeing this happening for more websites. Is there any update or plan to fix this?

**Comment by shahvah** [comment]
indeed, 'set noiframeon ... ' contained the issue for me. thank you very much!

**Comment by bovine3dom** [comment]
Closing in favour of #639, which will fix it.
