### ISSUE TITLE
Add a :tabrename command

### ISSUE THREAD

**Issue by tobixx** [tridactyl/tridactyl#3577]
Tridactyl version: 1.21.1
Firefox version: Mozilla Firefox 87.0
Operating system: linux

Hi, I really would appreciate the ability to rename the tab title.
Reason: I always have a bunch of the same url open in different tabs, with slightly different content, for comparison reasons.
To distinguish them, this feature would be really helpful.   

Thanks in advance,
Tobix

**Comment by bovine3dom** [comment]
For the current tab this is easy:

```
:command tabrename js -d€ document.title = JS_ARGS.join(" ")€
:tabrename [new name here]
```

I'll leave this issue open for a version of the command that can be used from any tab with tab completions.

**Comment by tobixx** [comment]
Oh - cool! Thanks a lot for this hint!
