### ISSUE TITLE
Tridactyl logo no longer shows up on `:editor`

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#3625]
Tridactyl version: 1.21.1pre5624-ee7c2588
Firefox version: Mozilla Firefox 86.0
Operating system: linux

Title says it all. Glacambre suggests a CSP problem

**Comment by Rummskartoffel** [comment]
I think the file name's just misspelt. `--tridactyl-logo` is defined as `url("moz-extension://<id>/static/logo/tridactyl_64px.png")`, but the file is actually called `Tridactyl_64px.png`.
