### ISSUE TITLE
Unable to use hint shortcuts

### ISSUE THREAD

**Issue by fugkco** [tridactyl/tridactyl#3638]
### Brief description of the problem
I'm unable to use `:hint` via shortcuts `f` and `F` on duckduckgo. First I was only able to use them _only_ on the links of the search results, but seemingly overnight it's not working at all. Nothing is getting hinted. I can still use `:hint` normally though. `f` and `F` still work on all other websites as normal.

After running through the requirements for this issue, I noticed my config has a lot of user configurations that I have not set up, and it does look like the above two mappings are set to something that otherwise doesn't work. I'm not quite sure where these came from as I've not set up anything in my `.tridactylrc` files. 

Since I've not customised it at all, perhaps the best way is to just reset all the settings. What would be the best way to do so?

### Steps to reproduce
¯\\\_(ツ)\_/¯

### Tridactyl version (`:version`)
```1.21.1```

### Firefox version:
```Mozilla Firefox 87.0```

### URL of the website the bug happens on
https://duckduckgo.com/

-   Config (in a new tab, run `:viewconfig --user`, copy the url and paste it somewhere like gist.github.com): https://gist.github.com/fugkco/dcbbe15bdbd4066edd8bbdb5d7383d04

-   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist): They don't exist.

**Comment by bovine3dom** [comment]
It looks like you did at some point play with our exemplar RC file - until minutes ago they recommended

```
bindurl ^https://duckduckgo.com f hint -Jc [class=result__a]
bindurl ^https://duckduckgo.com F hint -Jbc [class=result__a]
```

which no longer work as DDG have changed their site a bit.

Anyway just run

```
sanitise tridactyllocal
[wait a bit]
colours dark
blacklistadd play.golang.org
```

and you should have all the settings you care about back.

If the binds mysteriously come back I'd check thoroughly for an RC file on your system : )

**Comment by fugkco** [comment]
Huh! Very interesting, I don't recall playing with the example RC file, but perhaps it had happened when I just installed tridactyl and forgot about it. Thank you very much.
