### ISSUE TITLE
How to remove autocontain's

### ISSUE THREAD

**Issue by devd79** [tridactyl/tridactyl#3675]
Tridactyl version: 1.21.1
Firefox version: Mozilla Firefox 88.0.1
Operating system: win

mkt! -f sample
manaully edit the file <<sample>>
source ~/sample

I noticed that with source, "General Settings sections gets restored but not " Autocontainers

-   Steps to reproduce:

1. Set the colorscheme to some dark
2. Set one autocontain
3. save it
4. change the colorcheme
5. restore it from saved local file

**Comment by devd79** [comment]
there is already a bug reported 3649

**Comment by bovine3dom** [comment]
Tridactyl has its own storage - the file is only for backup / version control / sharing configuration.

If you're sure that you haven't added any settings that you want to keep (outside the RC file) you can wipe the Tridactyl storage with `:sanitise tridactyllocal`
