### ISSUE TITLE
Manually scroll ":tab" list

### ISSUE THREAD

**Issue by Acelya-9028** [tridactyl/tridactyl#3738]
Tridactyl version: 1.21.1
Firefox version: Mozilla Firefox 89.0
Operating system: win

It's possible to manually scroll a list like ":tab" or ":open" ? I hide the default tabs bar because with a lot of tabs, it's completely useless. "Tab Center Reborn" is good for that but I try to ditch it because it's duplicate with ":tab" and it's not super useful otherwise. My only problem is that I didn't find how to scroll the list without autocomplete, it's difficult for me because with a lots of open tabs like 2 or 300, read can be the best solution to find what I'm looking for and autocomplete makes me miss a lot :s.

Thank you very much.

**Comment by bovine3dom** [comment]
Just press and hold tab or shift tab.

I think we mention this in :tutor :)

**Comment by Acelya-9028** [comment]
Oh yes, thank you very much :D
