### ISSUE TITLE
Urlmodify not working with composite

### ISSUE THREAD

**Issue by simonhughcom** [tridactyl/tridactyl#3743]
When using composite to run two `urlmodify` commands, the first one fails to run.
In my particular case I tried to run `composite urlmodify -g 2 search; urlmodify -s query searchterm`
The second `urlmodify -s query searchterm` correctly runs, but the first `urlmodify -g 2 search` fails to run.

**Comment by bovine3dom** [comment]
Hi, thanks for filing this issue.

The trouble is that the instance of Tridactyl that runs composite is lost as soon as a new page is loaded. I'm not sure how we would go about fixing that.

You could try using `:jsb tri.excmds.urlmodify(...).then(()=>tri.excmds.urlmodify (...))` instead.

Or maybe even `:jsb tri.excmds.composite (...)`

**Comment by simonhughcom** [comment]
No, neither of them work.
We could write a new argument for `urlmodify` that would make it accept an input as url and then pipe one into the other.
For example: `composite urlmodify_js -g 2 videos | urlmodify -i -s query searchterm URL_GOES_HERE`
Or even more simply `composite urlmodify_js -g 2 videos | urlmodify -s query searchterm -` where the dash means accept from stdin, to follow convention.

I can do it if you want me to, I just need to know how you would like it to be implemented.

**Comment by simonhughcom** [comment]
> Or even more simply `composite urlmodify_js -g 2 videos | urlmodify -s query searchterm -` where the dash means accept from stdin, to follow convention.

Never mind, after looking at the composite function, I don't think this this version would work, it would have to be the first one with the `-i` flag.

**Comment by bovine3dom** [comment]
`composite get_current_url | urlmodify_js ... | url_modify_js ... | open` seems very reasonable to me : )

**Comment by simonhughcom** [comment]
So you want `urlmodify_js` to always accept an input rather than use the current URL?
That would break backwards compatibility, are you ok with that?

**Comment by bovine3dom** [comment]
Ah, no, sorry. I didn't realise it did that - that was an odd choice to make.

I'd add a flag e.g. `u` that makes it accept a URL as the last argument, e.g. `urlmodify_js -tu www old www.reddit.com`. It shouldn't be too hard to implement, just remove the arg and the character once you've found them.
