### ISSUE TITLE
Debugging custom css styles

### ISSUE THREAD

**Issue by karizma** [tridactyl/tridactyl#3746]
Tridactyl version: 1.21.1pre5624-ee7c2588
Firefox version: Mozilla Firefox 89.0
Operating system: win

I'm creating a custom css with userContent.css. It's working currently but I have to reopen firefox each time to check the new styles.

I've also tried modifying the in-browser css but it's not working and it's pretty slow and unproductive.

Any suggestions for the setup to create this custom theme?

**Comment by bovine3dom** [comment]
Hi, modifying stuff in the browser is usually the way forward to test things out. What isn't working about it?

**Comment by karizma** [comment]
Should've specified sorry. The styling on the help pages changes, but the command line does not. Just tried out a few things and ig it's because the command line is an iframe and the css variables edited don't carry over. Adding the style tag inside the iframe works.
