### ISSUE TITLE
Add in FAQ or some other place about clipboard permissions

### ISSUE THREAD

**Issue by karizma** [tridactyl/tridactyl#3765]
To use `yy`, `:nativeinstall` or any other command that requires writing to the clipboard, I believe you need `dom.events.asyncClipboard` enabled in `about:config`, otherwise you will get the error: `window.navigator.clipboard is undefined`.

After enabling it you might also need to reinstall the extension. 

I can make a PR for it but I just wanted to confirm it's not stated anywhere, since I don't see any issues about it.

**Comment by karizma** [comment]
Also for users who don't want to enable `dom.events.asyncClipboard`, maybe have the copied contents of `:nativeinstall` somewhere else?

**Comment by bovine3dom** [comment]
Why do you have that disabled? You could add it to doc/troubleshooting.md

I'm not sure how to make :nativeinstall display nicely. Do you have any ideas?

**Comment by karizma** [comment]
I had it disabled for privacy, but looking at the docs firefox only allows extensions with user given permission to use the `read()` and `readText()` methods, so it's not too much of a privacy benefit. 

Other users might have it disabled for other reasons, regardless of their reason, it's a good idea to error handle it.

> I'm not sure how to make :nativeinstall display nicely. Do you have any ideas?

Tridactyl could add a modal or something but imo I think the best idea is just to give an error and link or open a tab to a github page with the code.

**Comment by bovine3dom** [comment]
The trouble is that the code is generated each time to make sure you get a compatible version of the native messenger. I guess we can try to catch permission errors and just dump it in the commandline instead

**Comment by karizma** [comment]
That works too,

You could also open a tab with a data url: `data:text/html,`, that way it's easier to add other details like the reason

Or open up a website and give the generated code as a query so it can render it: `tridactyl.xyz/nativeinstall?code=`. But I think that's a bit of work for something not that common

Last two might annoy some users though since it's not minimalist like the first option.

Up to you

**Comment by karizma** [comment]
Doesn't seem like anyone else is having this issue, either way they can just search through issues.
