### ISSUE TITLE
`:tutor`

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#380]
I've just made it so that the new tab page appears on first install, but this isn't a very good introduction to Tridactyl.

We really ought to make a series of pages for people to navigate so that they can get used to Tridactyl.

Also, somewhat tangential: we should document the command line binds somewhere (up/down, ctrl-c etc).

**Comment by glacambre** [comment]
I haven't actually tried it but Oni's tutorial seems pretty good. Maybe we could use it as inspiration? https://github.com/onivim/oni/wiki/Features#interactive-tutorial

**Comment by bovine3dom** [comment]
First version is now live on the betas and will appear in a new tab on first install.

It is much more wordy than I would like and I am not sure what to do about that.

Also, I think we should cover search engines and settings in more detail.

**Comment by rreuvekamp** [comment]
Great tutorial for getting started, especially the Useful normal mode bindings!

**Comment by bovine3dom** [comment]
Should add a bit about the native messenger.

**Comment by antonva** [comment]
The tutor should have a previous page to compliment the next page href.
Currently, `[[` sets off a pretty nasty error on the cmdline.

`Error processing followpage(prev) Exception { name: "NS_ERROR_NOT_AVAILABLE", message: "", result: 2147746065, filename: "moz-extension://629263ad-99e5-4e5d-…", lineNumber: 5139, columnNumber: 0, data: null, stack: "urlincrement@moz-extension://629263…" }`

**Comment by rajeshmanivan** [comment]
Hi, Is it possible to search for a word in a webpage using / and then cycle to the next occurence of the word using n .

**Comment by glacambre** [comment]
@rajeshmanivan : Hi, it is possible by using the following commands:
```
:bind / find
:bind ? find -1
:bind n findnext 1
:bind N findnext -1
```
But this is not recommended because our find mode is slow and there's no way to know what you've typed so far.

We're planning on implementing a better find mode with https://github.com/cmcaine/tridactyl/pull/623 but we need to fix other bugs before making it available.

You can subscribe to https://github.com/cmcaine/tridactyl/issues/64 in order to be notified when find mode becomes available. In the meantime, I'd recommend using the normal `/` binding to search for words and then using `<C-g>` in order to jump to the next occurence.

**Comment by bovine3dom** [comment]
Related: #824.

Also, should probably add a page about containers once the CPU issue is fixed.

**Comment by antonva** [comment]
I'll add a tutor page on containers to #754.

**Comment by bovine3dom** [comment]
The tutor and the rest of the documentation could do with some TLC in time for #903.

Particularly:

- explain difference between tabs and buffers
- rapid hinting
- abnormal mode binds

Help wanted. It's just a bunch of text files in `src/static/clippy/`. No specialist knowledge required, other than knowledge of Tridactyl : )

**Comment by x-ji** [comment]
When I try the keybinding `;k` for killing elements on the page about hints, Tridactyl seems to just stop to function on that page. Eventually I have to copy and paste the URL to continue viewing the tutorial normally. This behavior can be confusing.

**Comment by bovine3dom** [comment]
You're actually the second person to complain about it. We should reword the line that talks about it.

Are you sure it isn't actually just highlighting the mode indicator in the bottom right?

**Comment by glacambre** [comment]
>Are you sure it isn't actually just highlighting the mode indicator in the bottom right?

If that's the problem perhaps we could `seturl static\/clippy\/hint_mode.html modeindicator false`?

**Comment by bovine3dom** [comment]
Yeah, but then ;k would do nothing on the page it is introduced. Maybe we should put a nice fake banner advert at the top?

Or even a real one? $$$

**Comment by x-ji** [comment]
Don't think I saw any change on the page. Pressing `Esc` or any other key also seemed to have no effect, that's why I copied the page. Not sure though maybe somebody can double check it.

**Comment by bovine3dom** [comment]
It works fine for me with the mode indicator enabled or disabled.

**Comment by glacambre** [comment]
laertus on IRC suggests mentioning how to manipulate tabs (moving between then, closing them, restoring tem...).

**Comment by danra** [comment]
Feedback: the tutorial is great. Thank you.
I'm on a Mac, and it was unclear whether C-x stand for Ctrl-x or Cmd-x. Related, some of the comments such as C-f not working for find unless you unbind it are incorrect on Mac, since Firefox uses Cmd-f and Tridactyl seems to use Ctrl-f.

**Comment by bovine3dom** [comment]
I think `Cmd` is referred to by JavaScript and us as "Meta", so `<M-x>` would mean Cmd-x. We should mention this in the tutorial (along with the exception for find). Thanks :)

**Comment by paul-mcnamee** [comment]
> 
> 
> @rajeshmanivan : Hi, it is possible by using the following commands:
> 
> ```
> :bind / find
> :bind ? find -1
> :bind n findnext 1
> :bind N findnext -1
> ```
> 
> But this is not recommended because our find mode is slow and there's no way to know what you've typed so far.
> 
> We're planning on implementing a better find mode with #623 but we need to fix other bugs before making it available.
> 
> You can subscribe to #64 in order to be notified when find mode becomes available. In the meantime, I'd recommend using the normal `/` binding to search for words and then using `<C-g>` in order to jump to the next occurence.

I think it's worth adding a note for what actual keys `<C-g>` represents, that notation is likely not known for a beginner.

**Comment by Utopiah** [comment]
I just completed the tutorial again as I got a new keyboard. While completing it I realized I inexorably went back to "bad" habits using the mouse rather than shortcuts. Now that I completed the tutorial I feel confident I will be good for a bit... but might slip back.

Are there more resources, like Vim golf, to go beyond the basics or freshen up?

**Comment by bovine3dom** [comment]
@Utopiah i don't think so but i have heard that some people like to play wikipedia traversal games aiming to use the fewest keypresses rather than the fewest pageviews

edit: there's also `:no_mouse_mode` which disables the mouse on a page
