### ISSUE TITLE
:editor excmd not returning properly

### ISSUE THREAD

**Issue by guy-who-googles** [tridactyl/tridactyl#3800]
Tridactyl version: 1.21.1pre5876-dbd5bd42
Firefox version: Mozilla Firefox 89.0.1
Operating system: Ubuntu 20.04

* Brief description of the problem:
I receive the error `# controller in excmd: Error: JS_ARG is undefined` after closing the editor with either alias shown below.

```
alias editor_rm composite editor | jsb -p tri.native.run(`rm -f '${JS_ARG[0]}'`)
alias editor_test composite editor | jsb -p tri.native.run(`cat '${JS_ARG[1]}' | xclip `) | clipboard xselpaste)
```

* Steps to reproduce:

    1. Run `:editor_rm` or `:editor_test`
    2. Edit text in my editor
    3. Save changes and close
    4. Receive error above

* URL of the website the bug happens on: gitlab.com and app.standardnotes.org

* Context
When attempting to use my editor (amp) with the native messenger on certain text fields, the contents appear updated, but aren't actually written to the page. For example, when writing an issue in gitlab, I opened the issue field using `:editor`. After exiting, the contents appeared within the issue field, but after clicking the `Preview` to see how the markdown turned out, the content reverted back to the state before opening inside my editor. <br>
As a workaround, I can manually copy all text within my editor and then paste it into the issue field. To automate this process, I wanted to play off of the `:editor_rm` example given on the help page to do something like `:editor_test`

Any help is greatly appreciated. I've been using tridactyl for a few months now and absolutely love it.

**Comment by bovine3dom** [comment]
Thanks for reporting! This was a very silly bug. The fix should be out in the betas when I next remember to release one (which honestly doesn't happen all that often).

> For example, when writing an issue in gitlab, I opened the issue field using :editor. After exiting, the contents appeared within the issue field, but after clicking the Preview to see how the markdown turned out, the content reverted back to the state before opening inside my editor.

This is gitlab's fault, I think. I always just delete a few characters with the keyboard and type them out again before I do anything else (like submitting the form) - that seems to help a lot. : )

**Comment by guy-who-googles** [comment]
Oh gosh, didn't think to try deleting a few characters, thanks!
