### ISSUE TITLE
Attempting to run bash script on URL

### ISSUE THREAD

**Issue by SlidingHorn** [tridactyl/tridactyl#3828]
Tridactyl version: 1.21.1pre5897-a1b023b3
Firefox version: Mozilla Firefox 89.0.2
Operating system: linux

I'm new to Tridactyl and coming from qutebrowser, so I'm wondering how I can accomplish something. In qutebrowser, I had the following keybind I had set up:

`bind ,M hint links spawn /path/to/bash/script {hint-url}`

the bash script itself is just a call to `youtube-viewer` with nohup and disowning it:

```
#! /bin/bash


nohup youtube-viewer --no-video-info --no-interactive $1 &>/dev/null & disown -a
```

I tried reading the stuff about `hint -W` but I don't understand what anything in its description means...

**Comment by bovine3dom** [comment]
See `:bind ;v` and `:get exaliases.mpvsafe` - you essentially want to do that but replace `mpv` with `youtube-viewer [your flags]`.

If that doesn't help you, let me know and I'll write a more detailed reply in the morning : )

**Comment by SlidingHorn** [comment]
> See `:bind ;v` and `:get exaliases.mpvsafe` - you essentially want to do that but replace `mpv` with `youtube-viewer [your flags]`.
> 
> If that doesn't help you, let me know and I'll write a more detailed reply in the morning : )

That did it...

```
:command ytv = js -p tri.excmds.shellescape(JS_ARG).then(url => tri.excmds.exclaim_quiet('youtube-viewer --no-video-info --no-interactive ' + url))

:bind ,m hint -W ytv
```

**Comment by bovine3dom** [comment]
For future searchers: `command ytv = js` is a typo, it's just `command ytv js`.

I'm guessing it's just a transcription error since it's working :)

**Comment by SlidingHorn** [comment]
> I'm guessing it's just a transcription error since it's working :)

Correct - I found out when I tried to create another command, lol

**Comment by drselump14** [comment]
Set the same command in my tridactylrc but nothing happens. youtube-viewer is already installed in my computer

```
command ytv js -p tri.excmds.shellescape(JS_ARG).then(url => tri.excmds.exclaim_quiet('youtube-viewer --no-video-info --no-interactive  ' + url))

bind ;v hint -W ytv
```

**Comment by bovine3dom** [comment]
Are you sure `:native` is installed and working? Does `:! which youtube-viewer` return something sensible?

**Comment by drselump14** [comment]
Hi, thanks for the reply.
`:native` produces `Native messenger is correctly installed, version 0.3.7` message.
However, the `:! which youtube-viewer` doesn't  produces any message, just a blank prompt

**Comment by bovine3dom** [comment]
What about e.g. `! ls /`?

How did you install Firefox? If you're using something like Flatpak you might need to follow the instructions here: https://github.com/tridactyl/tridactyl/#user-content-containerizedsandboxed-firefox-installations

**Comment by drselump14** [comment]
Hi, thanks for the reply

Invoking `! ls /` give me `ApplicationsLibrarySystemUsersVolumesbincoresdevetchomenixoptprivatesbintmpusrvar `

I installed the Firefox by the installer if I can remember correctly

**Comment by bovine3dom** [comment]
Oh, sorry, I assumed you were on Linux ... $PATH on OSX is a mystery to me. The command will probably work if you provide the absolute path to `youtube-viewer`, e.g. `/usr/bin/youtube-viewer` or more likely `/wherever/the/homebrew/directory/is/youtube-viewer` :)

**Comment by drselump14** [comment]
Hi, thanks,

Finally, it worked. Something is wrong with my youtube-viewer installation, but using mpv works for me.

```
command ytv js -p tri.excmds.shellescape(JS_ARG).then(url => tri.excmds.exclaim_quiet("/opt/homebrew/bin/mpv --ontop --no-border --autofit=500x280 --geometry=-1000-50 " + url))

bind ;v hint -W ytv
```
