### ISSUE TITLE
Some keybinding shows no effect (e.g., n)

### ISSUE THREAD

**Issue by albert-ying** [tridactyl/tridactyl#3841]
Hi, I just switched to FF from Chrome. I noticed that there are some strange thing happens. `n` for find next doesn't work. But `N` works somehow. There might be many more things that I haven't notice. It feels like FF swallowed some of these keys.

I use FF 90 on macOS. Please give me some hints if anyone knows what is happening here.

**Comment by bovine3dom** [comment]
Could you show us your config? Copy paste `:viewconfig --user`  here.

It might help us get a better idea of what's going on : )

Also, what keyboard layout are you using?

**Comment by albert-ying** [comment]
@bovine3dom Thank you for your timely response!

Okay, after a restart `n` worked. But some shortcuts are still swallowed when in insert mode.

So here is my config.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/59846322/126085322-bdc4e35a-b539-4c92-a7d5-dceeb45d7257.png">

At first, I bind my `editor` command to `shift-alt e` through `bind --mode=insert <A-e> editor`.It doesn't work at all except typing a literal back-tick `´`.

I then remapped it to `<C-q>` and it works. But I still want to use `<A-e>` if possible.

It is not tridactyl specific as other shortcuts are overridden in insert mode as well. And I only saw this behavior in Firefox.

I'm wondering if it also happens to you and if there is any workaround for this.

Thank you!

**Comment by bovine3dom** [comment]
```
bind --mode=insert <A-e> editor
bind --mode=insert <A-E> editor
```

both work fine for me on Linux. (`<A-E>` is shift-alt-e, `<A-e>` is just alt-e).

It could be that alt-e is reserved on OSX by Mozilla, in which case we can't do much about that. Some keys we're just not allowed to bind to (and we can only find out by noticing that they don't work).

**Comment by albert-ying** [comment]
I think I figured out what is happening here. So this is a MacOS-specific issue. From firenvim's README file (@glacambre ):

> On MacOS, the default keyboard layouts emit special characters when the alt (i.e. option) key is held down. From the perspective of the browser, these special characters replace the underlying "main" character of a keystroke event while retaining the modifier. For example, in the standard US layout the key chord alt-o is received in the browser as alt-ø rather than alt-o. 

So here, alt-E is interpreted as alt-\`. When I bind the command to <A-\`> in the config file, it works when I press shift-alt-e.

The problem is that the Firefox treats the alt key differently with and without the textbox focus (i.e., `<A-E>` works when I'm not focusing on the textbox). This means that for firefox on MacOS I will need two sets of keybindings to get universal behavior with and without the textbox focus. This doesn't happen on Chrome.

@glacambre I'm wondering if you know any setting in Firefox to let it treat the `alt` in the same way with or without textbox focused?

**Comment by glacambre** [comment]
@albert-ying No, I don't. I'm not 100% sure but I think you can tell Tridactyl to treat <kbd><A-\`></kbd> as <kbd>\<A-e></kbd> by using the `:keymap` command.

**Comment by bovine3dom** [comment]
> This means that for firefox on MacOS I will need two sets of keybindings to get universal behavior with and without the textbox focus. 

But you'd need two sets of keybindings anyway because of the different modes, right?

I don't think there's much scope for us to fix this unless we add support for keycodes, but that would add a whole different layer of complexity.

**Comment by albert-ying** [comment]
> @albert-ying No, I don't. I'm not 100% sure but I think you can tell Tridactyl to treat <A-`> as <A-e> by using the `:keymap` command.

Yes, it works this way.

> I don't think there's much scope for us to fix this unless we add support for keycodes, but that would add a whole different layer of complexity.

Yes, I agree. It is a firefox problem of handling the `alt` key on macOS. It's not a big problem for Tridactyl as I can just change the binding in a different mode. But for other extensions without the flexibility of config file, it could be a problem (e.g., I cannot bind <A-E> or <A-`> to trigger firenvim). I'm closing this now, but if anyone knows how to let firefox treat `alt` as meta in insert mode (like other browsers do), please let me know!
