### ISSUE TITLE
How to highlight multiple selectors in a page using one key bind

### ISSUE THREAD

**Issue by n-w-o** [tridactyl/tridactyl#3884]
-   Brief description of the problem:

can one key bind highlight two different CSS selectors in the same page? 

would like to have something like `bind ,f -c input "plus -c to select css b>a"`

**Comment by bovine3dom** [comment]
I think this is pretty simple but I keep forgetting to look into it when I'm at my PC.

If I don't reply by the end of the day feel free to ping me : )

**Comment by bovine3dom** [comment]
Finally remembered to look at this at my PC :)

`hint -c myfirstselector, mysecondselector` works fine for me - `,` combines multiple CSS selectors into a single selector. Nothing to do with Tridactyl - that's just how CSS selectors work
