### ISSUE TITLE
`tab` flag to show tab completion sorted by last visit

### ISSUE THREAD

**Issue by mozbugbox** [tridactyl/tridactyl#3886]
Tridactyl version: 1.21.1pre5980-0b47bd70
Firefox version: Mozilla Firefox 78.12.0
Operating system: linux

It would be useful to have a option to the `tab` command to show tabs sorted in last visited. Make it easier to quickly jump to recently visited tabs.

Like firefox's builtin `ctrl-tab`  without pressing a meta key.

**Comment by bovine3dom** [comment]
`:set tabsort mru` : )

**Comment by bovine3dom** [comment]
Glad I could help : )
