### ISSUE TITLE
Tridactyl unresponsive with `browser.sessionstore.restore_on_demand;false`

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#389]
I was having an issue where, in the latest betas (1.8.2-104-g2d9d4d6), Tridactyl would be unresponsive when Firefox was launched until I changed tabs or reloaded.

The problem went away for 1 restart if I did `sanitise tridactylsync`, but then came back.

I seem to have fixed it by changing `browser.sessionstore.restore_on_demand;false` back to true in about:config. Disabling that setting breaks Tridactyl for me deterministically on my profile, but not on a fresh profile, even with lots of tabs open.

:S

**Comment by glacambre** [comment]
Does this setting still break your Tridactyl? It seems to work fine for me.

**Comment by bovine3dom** [comment]
Hmm, does seem to work fine. I guess we can just chalk it up to "mystery problems that probably aren't our fault".
