### ISSUE TITLE
[FR] Hide mouse pointer

### ISSUE THREAD

**Issue by Carl-Robert** [tridactyl/tridactyl#3891]
Not hiding mouse pointer during normal use results in awkward hover effects depending if said pointer happens to linger on top of something. For example following a link and mouse pointer ends up over some on-hover modal on the new page. Then the user has to reach for the mouse and move it somewhere else, where hopefully it doesn't land on anything on the next page.

A fancy feature for this would be a setting for auto-hiding mouse pointer completely after brief period of inactivity.

Alternative and possible easier way to do this would be a toggle similar to `no_mouse_mode` to disable mouse completely, or just combine them both.

I have no experience on WebExtension APIs, so not sure if extensions can manipulate pointers this way.

**Comment by bovine3dom** [comment]
What's the difference between this and `no_mouse_mode`?

**Comment by Carl-Robert** [comment]
'no_mouse_mode' doesn't hide the pointer, but it still shows over content. Obstructing text underneath it for example.

Also if need to use the mouse, have to reload the page instead of just wiggle the mouse so it appears. Probably should have worded this better from the start.

**Comment by bovine3dom** [comment]
We can add `cursor: none` to no mouse mode - https://developer.mozilla.org/en-US/docs/Web/CSS/cursor - easily

You shouldn't have to reload the page - run `:mouse_mode` to make the mouse work again.

I'm not sure how we would deal with wiggling + a timeout.

**Comment by Carl-Robert** [comment]
`cursor: none` is actually all that is needed. Users can create preferred keybindings for `no_mouse_mode` and `mouse_mode`[probably most useful as a toggling keybind between the two].

Auto-hide would be the fancy version, but toggling manually shouldn't be that hard.

**Comment by bovine3dom** [comment]
Hidden cursor will appear whenever I next release a beta version :)

**Comment by gnull** [comment]
Could it be also useful to add a `:toggle_mouse_mode` command? This way one switch between the modes with a single keybinding.

**Comment by bovine3dom** [comment]
Sure. I'd accept a PR :)
