### ISSUE TITLE
Github favicon broken in :tab view

### ISSUE THREAD

**Issue by Vermoot** [tridactyl/tridactyl#3892]
Hello !

I've been working on my own theme, based on shydactyl, and I've added back favicons to the :tab command. It works great, only problem is [the github icon seems to be broken for some reason](https://cdn.discordapp.com/attachments/648216442214416387/876807116126580736/unknown.png).

This is the only case I've found, there may be others but I haven't come across them.

Any ideas what could be causing this?

Thanks!

**Comment by bovine3dom** [comment]
Hmm, have you tried clearing your cache? Sometimes that can be a problem. I guess it's showing in the browser chrome ok...

It's very unlikely to be a problem with your theme, anyway.

Theme looks cool though!

**Comment by glacambre** [comment]
Can reproduce. The url of the favicon is "#zXssPreventedz". This is an issue I have already fixed in 3ddf350dc02ee46d5f75e7ab620e8155103fbf02 - fixing it again might just be a matter of adding an extra protocol in there.

**Comment by bovine3dom** [comment]
Thanks, was an easy fix :)

**Comment by Vermoot** [comment]
Sorry, I'm not sure how this works; I can expect to see this fixed in a future update of the extension, and I have nothing to do myself?

**Comment by bovine3dom** [comment]
Yeah, you just have to wait and/or nag me.

I'll release it on the beta channel ... soon (if you'd like it sooner just nag me). Once it's released it can take Firefox up to a week to notice unless you click the cog under about:addons, click update then restart the browser.

I'll release it on the stable channel eventually, usually I do them about every 2-6 months. We're probably slightly overdue one. (If you want one sooner just nag me). Then it'll take Firefox up to a week to notice.
