### ISSUE TITLE
I need to change the font for hints - What's the correct way (ie quickest performance) of doing that?

### ISSUE THREAD

**Issue by OwenAR** [tridactyl/tridactyl#3906]
I just tried searching the wiki for "font" and "css", but couldn't find anything there.

(
The default font has *major* problems for me, particularly N/M/H being practically indistinguishable
-- is that specific font set by tridactyl?
or is it just inheriting a font specific to my particular firefox/system, which just coincidentally happens to be really bad for this purpose?
)

**Comment by bovine3dom** [comment]
Tridactyl just uses whatever Firefox tells it to for monospace fonts. Change it here: https://support.mozilla.org/en-US/kb/change-fonts-and-colors-websites-use : )

**Comment by OwenAR** [comment]
Took me a while to get around to testing this
(just now finally got around to double-checking I had a woff version of the font I was testing in all of regular/italic/bold (thank you "[nerd-fonts](https://github.com/ryanoasis/nerd-fonts)" and `sfnt2woff`))...

but the tridactyl hints seem to actually use the font set in the "`sans-serif`"-field,
not the "`monospace`"-field
(and they seem to do so whether or not the "`proportional`"-field is set to "`serif`" or "`sans-serif`")

![{firefox fonts} 2021-09-14-221356_790x792_scrot](https://user-images.githubusercontent.com/3036957/133383413-9f168981-1f37-4da4-ad28-73fe67d03ec0.png)

However, there are two problems:

- that ends up with *tons* of other things in the browser using the same font

- for some reason the size of the font used in the hints ends up much smaller than the default.  
(The only way I found to change that was to set something in the "`minimum font size`"-field, but that sets the minimum for *all* fonts used by the browser)

So...
**Is there a way of targeting the tridactyl hint font more specifically?**
**(Even if it's not as fast, so long as there's a chance I won't notice a lag on my shitty old hardware...)**


---
(
Fun fact:
while I was messing with this, I briefly accidentally set a bunch of things in firefox (eg wikipedia, gmail chat) to use *klingon letters*.
(I guess a klingon font came in with all the other font stuff I was messing with, "KApIqaD").

I dunno, I just found that amusing.

Oddly, while this klingon font displayed just fine on eg wikipedia,
the tridactyl hints themselves just displayed blank, nothing inside the boxes.
![{klingon letters} 2021-09-14-223836_1230x449_scrot](https://user-images.githubusercontent.com/3036957/133383549-e1fa6314-76b5-45f9-b1b9-a9a5d6271a3a.png)

Clearly this is a very serious bug and needs to be fixed ASAP.
)

**Comment by bovine3dom** [comment]
> but the tridactyl hints seem to actually use the font set in the "sans-serif"-field

Yeah, it does, I misremembered :)

> this klingon font displayed just fine on eg wikipedia,
the tridactyl hints themselves just displayed blank

Thanks for reporting. I'll make sure we don't anger the Klingon when we get round to adding i18n support to Tridactyl.

**Comment by bovine3dom** [comment]
> Is there a way of targeting the tridactyl hint font more specifically?

Yes, you just need to make a theme. See `:help colours`. The `:colours shydactyl` theme might be good enough for you already
