### ISSUE TITLE
Editor indicator stamp left after editor closes

### ISSUE THREAD

**Issue by madduck** [tridactyl/tridactyl#3909]
Tridactyl version: 1.21.1pre6005-83b1f7c7
Firefox version: Mozilla Firefox 88.0.1
Operating system: linux

As of late, when I use external editing, and I close the editor, the stamp used to denote that an input field is being edited isn't removed:

![image](https://user-images.githubusercontent.com/195073/133528012-5ce8c963-09da-4c1b-8ef4-7f9466be036f.png)

**Comment by bovine3dom** [comment]
Potentially introduced with #3887
