### ISSUE TITLE
how do i bind keys for controlling speed of videos? 

### ISSUE THREAD

**Issue by tjallemaal** [tridactyl/tridactyl#3913]
Tridactyl version: 1.21.1
Firefox version: Mozilla Firefox 92.0
Operating system: mac
config:  https://gist.github.com/tjallemaal/4b080c398770735c50693ac08e3a46cd

how do i create key binds for controlling the speed of videos?
i used to do this in firefox with `shift+>` and `shift+<`. 
is there already respective keybinds for this but i'm not aware? if so, apologies

**Comment by bovine3dom** [comment]
There's no easy way of doing this with Tridactyl. You can write a bit of JavaScript yourself to do it though:

You would have to use `:js` with https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate

If you can think of a nice way of doing it I would accept a PR to Tridactyl that added playback speed controls : )

**Comment by tjallemaal** [comment]
hm.. i can't code yet, currently learning vim+latex so maybe in the future.
but why is that possible with the firefox shortcut then?

**Comment by bovine3dom** [comment]
> why not keep the binds by firefox? or is this just not the way it works

We use the keys for different things. If you do `:unbind <<` and `:unbind >>` you should get the Firefox binds back.
