### ISSUE TITLE
Prevent navigating from a page while editing

### ISSUE THREAD

**Issue by madduck** [tridactyl/tridactyl#3915]
Tridactyl version: 1.21.1pre6005-83b1f7c7
Firefox version: Mozilla Firefox 88.0.1
Operating system: linux

When editing using `editorcmd` and accidentally navigating away from the page, there is no way to restore the link between the file being edited and the input field.

It's quite common on the Web for webpages to ask the user to confirm whether to leave or stay on the page while things are being edited. Would it be possible to put such a safety guard in place while `editorcmd` is running?

**Comment by bovine3dom** [comment]
Yeah, this would be quite straightforward to do with https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload

**Comment by madduck** [comment]
Thank you. Will trial when I get back to my laptop in a few days.

**Comment by bovine3dom** [comment]
You'll only see it if you build Tridactyl from source - at the moment, beta builds are only updated when I remember to do it manually :)

**Comment by madduck** [comment]
> You'll only see it if you build Tridactyl from source - at the moment, beta builds are only updated when I remember to do it manually :)

About to move from one earth hemisphere to another, I don't have the nerves for this, so I'll wait for the next beta — but I am sure it works fine, so *thank you for the work!*

**Comment by bovine3dom** [comment]
Wow, good luck! I hope it goes well and isn't too stressful.

I released a beta recently so you may already have the code - `:version` should be 1.22.0pre6142 (+ some git hash)

**Comment by madduck** [comment]
Indeed. I can confirm it works nicely. There is no way to customise the message displayed by the warning dialog, or is there?

**Comment by bovine3dom** [comment]
> There is no way to customise the message displayed by the warning dialog, or is there?

No, apparently not since Firefox 4 (circa 2011): https://developers.google.com/web/updates/2016/04/chrome-51-deprecations?hl=en#remove_custom_messages_in_onbeforeunload_dialogs
