### ISSUE TITLE
text2qr

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#3916]
Would be nice to pipe stuff to qr / aztec codes. Should handle making stuff uppercase for QR etc. `yq` for yank to QR. Probably best to have it display in pop-up/application window with Tridactyl running in it.

Should copy-paste a library into Tridactyl so that we don't have to worry about people changing bitcoin addresses etc.

(Hat tip to Nyxt for making me think about this)

**Comment by bovine3dom** [comment]
https://symbology.dev/reference/two-dimensional.html

this is a very cool rabbit hole to fall down

**Comment by oguzhanogreden** [comment]
Do you mean `:text2qe https://github.com/tridactyl` should display a QR/Aztec code that encodes the URL, essentially?

Indeed looks like a cool rabbit hole.

**Comment by bovine3dom** [comment]
Yeah, exactly that :)

**Comment by stupidcomputer** [comment]
You could probably do that with a command and a shell script. There's a software project that can encode arbitrary text and data into QR codes; I'm not sure about Aztec codes. It runs on the command line.

**Comment by satyamkr1729** [comment]
Hi, Can i work on this one?

**Comment by bovine3dom** [comment]
Absolutely!

**Comment by satyamkr1729** [comment]
Regarding displaying of the QR, would it be better to display in the ex command console itself?

**Comment by bovine3dom** [comment]
I think that would be difficult. I would probably make a new page like I did in the reader PR here - https://github.com/tridactyl/tridactyl/pull/3938/files - and then open it with `:winopen -popup` or `:tabopen`.

Probably, by default, closing that page after 5 seconds? Whatever feels reasonable.

**Comment by satyamkr1729** [comment]
> Should copy-paste a library into Tridactyl so that we don't have to worry about people changing bitcoin addresses etc.

What did you mean by this one? Do you not want to handle the library using yarn?

> https://symbology.dev/reference/two-dimensional.html
Btw this package only supports till node 17.

**Comment by bovine3dom** [comment]
> What did you mean by this one? Do you not want to handle the library using yarn?

There have been a few cases where QR code generators (I think mostly websites) have been hijacked and used to re-write bitcoin addresses to steal money from people. I think if we use a simple enough library we can avoid that problem by just never updating it.

I don't know how trustworthy yarn/npm is - if we just pin it to a certain version, is that good enough? Could someone replace a version?

So maybe it is better to just include the whole package in Tridactyl using e.g. https://stricker.digital/posts/how-to-vendor-npm-dependencies/

> Btw this package only supports till node 16.*

Do you mean it can't run in the browser? I don't have any strong opinions on which package we should use.

**Comment by satyamkr1729** [comment]
> Do you mean it can't run in the browser? I don't have any strong opinions on which package we should use.

No i dont think it should cause any issue in browser. Will try it and see if any issue comes.  Otherwise will opt for some npm lib which focuses on just QR codes. Thanks for clarifying 🙂

**Comment by bovine3dom** [comment]
Added in #4728 thanks to satyamkr1729 :)
