### ISSUE TITLE
Can Tridactyl add and use the keyword field for bookmarks?

### ISSUE THREAD

**Issue by llinfeng** [tridactyl/tridactyl#3924]
Tridactyl version: 1.21.1
Firefox version: Mozilla Firefox 92.0.1
Operating system: win

"Keyword" is a field in Firefox's Bookmark menu. In Firefox's own terms, it is described as:
> Use a single keyword to open bookmarks directly from the address bar

These keywords can be arbitrarily long or short, and can be more flexible than the `M[char]` markers in Tridactyl. Currently, to add a keyword to a bookmark, I need to open the "Library" for the bookmarks and add it manually. For long, this effort is well justified, as I can then use the keyword in the address bar directly.

Here is a wishlist of potential interactions with FF's bookmark keywords via Tridactyl:
1. With `:open` and `:bmarks`, when it receives a short text that is a keyword for a bookmark, load that bookmark instead of querying Google for that keyword.
2. When adding bookmarks with `:bmark`, let there be a `-keyword=xxx` flag. Then, the new bookmark gets added along with "xxx" in its keyword field. 

----

Currently, the `titlearr` option for `:bmark` allows for assigning a name to the bookmark. And, both the Firefox's address field and `:open/:bmarks` are providing very nice completion for bookmarks. However, in either case, it takes an extra step to open the bookmark.
* With Firefox's own address bar, depending on the search-engine setting, the suggested bookmark can be many "down-arrows" away from the top. Upon disabling the search-engine setting that reads "Show search suggestions ahead of browsing history in address bar results", still, it takes one additional down-arrow press to select the bookmark entry vai name-match.
* With `:open/:bmarks/:tabopen`, upon typing a portion of the text in the name of the bookmark, I'll need to tab-select the entry if there are other bookmarks sharing the same text-snippet.

With the keyword, hitting enter just loads the page directly.

**Comment by bovine3dom** [comment]
We can't support bookmark keywords as Mozilla won't allow us - we've had lots of issues open about this already because lots of people want it. You can find more information in those issues, e.g. #73, #194 : )

**Comment by bovine3dom** [comment]
No worries, GitHub issue search is pretty bad. I file duplicates all the time...
