### ISSUE TITLE
encoding is wrong

### ISSUE THREAD

**Issue by kasal** [tridactyl/tridactyl#3953]
Tridactyl version: 1.21.1pre6005-83b1f7c7
Firefox version: Mozilla Firefox 92.0.1
Operating system: win

I noticed a bug with page https://portal.rozhlas.cz/
Its encoding is UTF-8, as declared in meta charset in the page header.
When I load it without tridactyl and hit Ctrl-I, I can see that the page encoding is correctly set as utf-8.

But with tridactyl, the page is displayed incorrectly and Ctrl-V Ctrl-I indeed shows encoding Windows-1250.

I got this behaviour consistently for a few months now and on all my systems (Fedora 33 / x86_64 and two installations of Windows 10)

Thanks in advance for any help.

**Comment by bovine3dom** [comment]
Hi, thanks for reporting this. Where can I see the text encoding in the inspector?

For what it's worth, the page looks fine to me ... but I'm not sure I would be able to tell if it wasn't : )

**Comment by kasal** [comment]
Hello, thanks for quick reaction.  About the bug: you would see the difference  :)
Czech uses letters with accents, e. g. "Nejpodrobnější". When the utf-8 encoded letters get interpretted as windows-1250, you get capital letters and accents without a letter, like this: "NejpodrobnÄ›jĹˇĂ­"

I do no know where can I see encoding in the inspector.

With more testing, I was able to partially reproduce the bug even with tridactyl switched off:
page portal.irozhlas.cz or plus.irozhlas.cz displays a box about the results of the elections that were hold this Friday and Synday in Czechia.
The box has title/subtitle "Parlamentní volby 2021 / Celostátní výsledky" incorrectly displayed as "ParlamentnĂ­ volby 2021 / CelostĂˇtnĂ­ vĂ˝sledky"
The box is inserted a few seconds later than the rest of the page, perhaps by a script.

Consequently, I believe the issue is not directly caused by tridactyl; it looks like a timing issue.
My guess is that with certain timing, the supplied charset gets replaced by a default.  The default might be utf-8 for most people anyway, but it might differ in my case as my system is configured to use English interface.

In any case, it doesn't seems to be a tridactyl bug after all.  Thanks for your time.
