### ISSUE TITLE
Add support for LibreWolf browser in native messenger

### ISSUE THREAD

**Issue by Carl-Robert** [tridactyl/tridactyl#3965]
Librewolf is a tweaked/patched Firefox, basically a bunch of configuration overrides instead of being a true hard fork of it https://gitlab.com/librewolf-community/browser. It however uses its own executable `librewolf` and profile directory. For that reason the native messenger doesn't play nice, because calling for `firefox` only.

**Comment by bovine3dom** [comment]
I thought Librewolf was a set of preferences? https://gitlab.com/librewolf-community/settings

I didn't think they patched Firefox at all. I'd be interested to see the patches if you know where they are :)

**Comment by Carl-Robert** [comment]
https://gitlab.com/librewolf-community/browser/common Patches are here.

**Comment by bovine3dom** [comment]
Thanks! I think I've found the source of the problem: the local user storage directory has been renamed - https://gitlab.com/librewolf-community/browser/common/-/blob/master/patches/mozilla_dirs.patch

If you symlink `~/.mozilla/native-messaging-hosts` to `~/.librewolf/native-messaging-hosts` it might just start working for you :)

**Comment by guy-who-googles** [comment]
I'm not OP, but it looks like symlinking works! I'm on Linux, not Windows though

**Comment by Carl-Robert** [comment]
On Windows there isn't the Unix specific .dot folders. I made a symlink between `C:\Program Files\Mozilla` and `C:\Program Files\LibreWolf` but issuing `restart` still says `#Browser executable not found `. Something I missed?

**Comment by bovine3dom** [comment]
Is librewolf called `firefox.exe`? If not, you might need to `:set browser [the real name]`

**Comment by bovine3dom** [comment]
Closing this as Librewolf has a nice section in their FAQ about it https://librewolf.net/docs/faq/#how-can-i-get-tridactyls-native-messaging-to-work-when-i-install-librewolf-with-flatpak

Copied for posterity

```
To get Tridactyl's native feature to work Tridactyl's install script needs to look into Librewolf's app data directory and be allowed to read the user's RC file.

Execute the following:

curl \
	https://gitlab.com/librewolf-community/browser/common/-/raw/master/helpers/tridactyl-install.sh \
	> /tmp/tridactyl-install.sh # patched install script with changed manifest destination
sed -i \
	's/\.librewolf/\.var\/app\/io\.gitlab\.librewolf-community\/\.librewolf/g' \
	/tmp/tridactyl-install.sh
chmod +x /tmp/tridactyl-install.sh
/tmp/tridactyl-install.sh

# If installed onto the system, rather than the user, then remove `--user`
flatpak --user override io.gitlab.librewolf-community --filesystem="${XDG_CONFIG_HOME:-~/.config}"/tridactyl
flatpak --user override io.gitlab.librewolf-community --filesystem="${XDG_DATA_HOME:-~/.local/share}"/tridactyl
```
