### ISSUE TITLE
Slack Webapp can't navigate channels

### ISSUE THREAD

**Issue by dianrob** [tridactyl/tridactyl#3982]
Tridactyl version: 1.21.1
Firefox version: Mozilla Firefox 93.0
Operating system: mac

# Reporting a bug / getting help

Can't navigate slack channels. Even though they are highlighted by the hinting feature the channels hints work in slack webapp.

I know this is a lot to ask for and a edge-case but for me personally it would make sense to be able to navigate slack via keyboard using tridactyl. Thanks for all the hard work! I just started using it two days ago and have to say it is amazing.

EDIT: Sorry for being such a noob. Hinting with :hint -c div works just fine

**Comment by dianrob** [comment]
`:hint -c div`

**Comment by isamert** [comment]
I ran into the same issue and found @dianrob's solution and then created these bindings for `slack.com` urls. They might override some default bindings but only on `*.slack.com`:

```vim
" ;c highlights all channels etc. on the sidebar
bindurl .*.slack.com --mode=normal ;c hint -c div[data-sidebar-link-id]:not([data-sidebar-link-id=""]),div[data-section-channel-index]:not([data-section-channel-index=""])
" ;u jumps to "All unreads" directly
bindurl .*.slack.com --mode=normal ;u hint -c div[data-sidebar-link-id="Punreads"]
" ;t jumps to "Threads" directly
bindurl .*.slack.com --mode=normal ;t hint -c div[data-sidebar-link-id="Vall_threads"]
" ;d jumps to ... you get the idea
bindurl .*.slack.com --mode=normal ;d hint -c div[data-sidebar-link-id="Pdms"]
bindurl .*.slack.com --mode=normal ;a hint -c div[data-sidebar-link-id="Pactivity"]
```

**Comment by bovine3dom** [comment]
@isamert that looks cool - maybe make a Slack page on the Wiki with it on so people can find it more easily: https://github.com/tridactyl/tridactyl/wiki :)

**Comment by isamert** [comment]
@bovine3dom nice idea, created one with even more useful bindings!

https://github.com/tridactyl/tridactyl/wiki/Slack
