### ISSUE TITLE
Document built-in key theft prevention

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#3997]
https://news.ycombinator.com/item?id=29263854

Apparently Firefox has a setting that can stop websites stealing /. We should make sure it works and document it.

**Comment by ash-m** [comment]
I thought I'd document my cursory experience for anyone that comes across this:
 - as explained in the (possibly updated) original post, the setting (`permissions.default.shortcuts = 2`) does not work (although there is some misleading documentation here: https://support.mozilla.org/en-US/questions/1241294 )
 - it _will_ mess up Tridactyl (at least it did to me but I do have other extensions installed: darkreader, dashlane, adblock). I was unable to exit "hint mode" after entering it normally (by pressing `f`) and `ctrl` + `,` no longer had an effect in "insert mode". Sometimes the mode indicator would disappear and Tridactyl had no function entirely (which could be solved by revisiting the URL explicitly).
Takeaway: This is not a good setting to mess with.

**Comment by nmeum** [comment]
I can also confirm that it will mess up Tridactyl.

I was also unable to exit hint mode as well and I don't have additional extensions installed.

**Comment by bovine3dom** [comment]
Thanks for confirming, I'll close this issue to make sure no-one is misled by it :)
