### ISSUE TITLE
[feature-request] Freeform clicking with screenspace subdivision

### ISSUE THREAD

**Issue by brettmitchelldev** [tridactyl/tridactyl#4035]
Tridactyl version: 1.22.0
Firefox version: Mozilla Firefox 95.0.2
Operating system: linux

This was something I thought of while navigating popout menus with Tridactyl; sometimes opening a submenu requires that you hover the parent button instead of clicking it, and clicking will actually take you to a new page. In addition, some overlay-style ads have close buttons with weird element types that Tridactyl has a hard time identifying as 'clickable' for the easymotion style link activation.

To solve these issues, it might be nice to include an alternate easymotion interaction, where the user selects an evenly subdivided section of the screen rather than an element. This could recurse into finer and finer subdivisions until the user is happy with the location of the interaction, at which point they may confirm a click or hover.

Assuming the UX of the feature is nice enough not to scare people away from using it, I think this would solve some of the edge cases in Tridactyl right now; edge cases in iframe DOM interactions could be worked around through direct screenspace interactions (and maybe this could be further sped up / improved with a root element preselect that uses the current easymotion interaction). Also, Tridactyl wouldn't need to support weird button elements designed to prevent auto-closing, because of the same reason.

The second thing sort of piggy-backs off of this one since it applies there. It would be great to be able to activate hover on an element rather than just activating click. This would be something that gets added to both screenspace easymotion and element discovery easymotion, and would allow navigating menus that must be hovered to open. I don't know if that would be a completely new interaction (`f hk`  vs.  `<C-f> hk`) or if it would be a mode change during the motion (`f <C-h>hk`  vs.  `f hk`), or something else entirely.

Thanks for considering my feature request, and thanks for the amazing extension!

EDIT: I'm such a dummy, I didn't realize the grey options in easymotion mode work to hover an element. So there already is a solution for that in place. Maybe I would amend my hover request to suggest that tridactyl allow the user to hover any element? If that gets implemented, it might make sense to add a mode switch feature where you can choose between hover or click for any element. I feel like that would eliminate a good number of edge cases by just letting the user handle choosing which elements to hover themselves. :shrug:

**Comment by bovine3dom** [comment]
Thanks for filing this issue! I'll try to reply to it after the holidays :)

**Comment by brettmitchelldev** [comment]
Closing this as I don't think this is a good idea anymore. It represents a ton of work for what I think is very little value.
