### ISSUE TITLE
Window merging

### ISSUE THREAD

**Issue by Ssamm45** [tridactyl/tridactyl#404]
Sometimes when certain websites insist on opening something in a new window which can sometimes be annoying.
Would it be possible to create a command to merge two firefox windows into one with multiple tabs? Or maybe something more sophisticated that would allow moving any tab from any window to any other window?

**Comment by bovine3dom** [comment]
Yes. It's a good idea but before it can be useful we would need completions to select target windows, and we have a tacit agreement to not write any more until we have rewritten it in a saner manner.

**Comment by saulrh** [comment]
I think that this might be better implemented as a mode for `:tabmove` that can target buffers in other windows, but I think it'd also imply new completions functionality?

(Being able to target buffers outside the current window would also be useful for `:buffer` and `:tabclose`.)
