### ISSUE TITLE
is there a way to select from the middle of a feild in visual mode ?

### ISSUE THREAD

**Issue by nobodyatandnothing** [tridactyl/tridactyl#4042]

**Comment by bovine3dom** [comment]
Hi :)

No, there currently isn't - hint mode only works on HTML elements and text usually is contained within a bigger element. What you can do is select the whole element with `v`, use `b` and `e` to get to the end of the segment you want, press `o` to change the cursor position to the start of the selection and then use `w` and maybe `h` to get to the beginning of the segment you want.

**Comment by nobodyatandnothing** [comment]
thank you
