### ISSUE TITLE
can tridactyl open restricted pages or not  ?

### ISSUE THREAD

**Issue by nobodyatandnothing** [tridactyl/tridactyl#4043]
in [:h caveats](moz-extension://28e534c4-154f-493d-8b79-92486d9fea42/static/docs/modules/_src_excmds_.html#caveats) it says that "Tridactyl can't run on about:*, some file:* URIs, view-source:*, or data:*, URIs." but in the tutorial in the page "Native Messenger" it says that with native, tridactyl can "Open privileged pages (e.g. about:preferences) from Tridactyl's commandline (:h nativeopen)." i have native 0.3.6 installed but when i try to nativeopen about:pages , tridactyl doesnt work.

**Comment by bovine3dom** [comment]
Tridactyl can't run on those pages (except `:bind --mode=browser` binds but with lots of caveats - the most useful being `Ctrl+,` to get you back to a page where Tridactyl does work), but we can open them.

Can you confirm that you can also open them? It isn't clear to me whether you can open them from your issue, or whether you can open them but then not use Tridactyl on those pages :)

**Comment by nobodyatandnothing** [comment]
i can open them but i cant use them

**Comment by bovine3dom** [comment]
This is expected behaviour, sorry :(
