### ISSUE TITLE
"Error: Not an excmd" for seach engine commands

### ISSUE THREAD

**Issue by hemanti0503** [tridactyl/tridactyl#4065]
-   Brief description of the problem:

I'm new to Tridactyl and am just going through the tutorial. So far loving it. :) However, I can't get `:google`, `:duckduckgo` or any other search engine to work like that. 

-   Steps to reproduce:

    1. Go to any arbitrary website. 
    2. Type `:google hi`
    3. Get the error `# controller while accepting: Error: Not an excmd: google`

-   Tridactyl version (`:version`): 1.22.0

-   Firefox version (Top right menu > Help > About Firefox): 95.0.1 on Linux Mint

-   URL of the website the bug happens on: any

-   Config (in a new tab, run `:viewconfig --user`, copy the url and paste it somewhere like gist.github.com): 
https://gist.github.com/hemanti0503/2198db763faa42a833e158b84e415d98

-   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist): Files don't exist.

- Additional notes: 
Strange thing is: it worked yesterday when I tried for the first time. Since then, I installed a few other add-ons. When I discoveres this issue, I thought, that maybe one extension broke it. However, I just tried in an empty profile and the problem remains.

**Comment by bovine3dom** [comment]
Hi, thanks for filing this issue. The search engines are magic keywords for use with open/tabopen/winopen commands, e.g.

`:open google what is the meaning of life`

:)

> Strange thing is: it worked yesterday when I tried for the first time

You probably pressed `o` or `t` rather than `:` to bring up the command line :)

**Comment by hemanti0503** [comment]
Indeed. I must have been more awake yesterday. :) Thank you!
