### ISSUE TITLE
Resetting "newtab" value

### ISSUE THREAD

**Issue by kronomax** [tridactyl/tridactyl#4071]
-   Brief description of the problem: 
I changed the newtab value into DDG with:
 ```
:set newtab https://duckduckgo.com
```
After a bit, I figured I actually want to keep the default Tridactyl page, as it has some keybinds which I might want to learn over time. The issue is I can't seem to find a way to reset the value of "newtab" to whatever it's originally at. Great extensions in any case!

-   Tridactyl version (`:version`): 1.22.0

-   Firefox version (Top right menu > Help > About Firefox): 96.0.1

-   URL of the website the bug happens on: -

**Comment by bovine3dom** [comment]
Hi, glad you like the extension!

`:unset newtab` should do the trick :)

Feel free to reopen the issue if it doesn't
