### ISSUE TITLE
Open in existing tab

### ISSUE THREAD

**Issue by TKone7** [tridactyl/tridactyl#4091]
I wonder if there is a way to solve the following problem I have:
Let's say I often work with a web application hosted under `web.app`. By it's nature this app initially loads quite a bit of bundled js which is slow. Afterwards, navigating is rather quick cause no new pages are loaded (only executing API commands). I often need to click on links to `web.app` from other pages. This results a new tab to open and download the entire app. I would like to be able to open a link in an already existing tab. So, let's say I am on `example.com` and click on a link to `web.app`, I want tridactyl to check if there is an existing browser tab and open the link in it.

I already tried things like this:
```
 composite tab 5; open web.app
```
This switches to the tab I wish, but opens the link on the original tab, the command was executed on.

Does anyone have an idea how to achieve this?

-   Tridactyl version `1.22.0`

-   Firefox version 96.0.3

**Comment by bovine3dom** [comment]
This is a bit daft but it works:

```
composite tab #; sleep 200; jsb tri.excmds.open("news.bbc.co.uk")
```

1. Switch to the tab you want
2. Wait a little bit for the tab to be switched to
3. Execute the `:open` command in the background context. Tridactyl can't run that command in the background context so it tries to run it in the currently open tab instead, which is the tab you just switched to

NB: you can also use `:composite tab [fragment of title]` to switch to the tab you want rather than hardcoding an ID

**Comment by TKone7** [comment]
Hey @bovine3dom thanks a lot for the idea and explanation. I will try this out for sure 👍🏽 

I also experimented a bit more myself and came up with this (feedback appreciated):
```
composite hint -Jyc a; tab_helper false true [fragment of title]; clipboard open
```
This: 
1. Highlights all the anchor links that I could possibly open and yanks `-y` the one selected
2. uses `tab_helper` to select to correct tab (and suppresses user interaction in case there are multiple matches)
3. `clipboard open` seems to wait for the tab to be loaded without any adjustments

**Comment by bovine3dom** [comment]
I kind of love it, you're using maybe three things at once in ways they weren't supposed to be :)

I can't see any immediate improvements :)

**Comment by TKone7** [comment]
I guess therein lies the beauty of Tridactyl; once you understand the basic building blocks there is no limit what you can achieve by combining them in novel ways. I really love what you've built! Many thanks.

It would be cool to have a space for inspiration, where users would publish their own little solutions that they use to make their daily lives easier. I mean, your examples in `.tridactylrc` is a good start but this could be much bigger and broader when nurtured by the community.

**Comment by bovine3dom** [comment]
I'm pretty sure anyone can edit the wiki: https://github.com/tridactyl/tridactyl/wiki

I'm not sure if anyone reads it though :)

**Comment by m2habert** [comment]
Hi there, @TKone7 : I've learned from this issue a bit much so I've thought my recent #4361 would be of related interest...

(Also regarding tab_helper)
