### ISSUE TITLE
tri.excmds.bind inserts a "," character

### ISSUE THREAD

**Issue by m2habert** [tridactyl/tridactyl#4118]
I wanted to use the `js -d` to create a command to assign the same hint to a given bind, a "memory hint", if you will.

So:

        command memoryHint js -d€ tri.excmds.bind(";m", "hint -Jf " +JS_ARGS)€

So,  if inputed:

    :memoryHint comment

expected: 
it should bind `;m` to `hint -Jf comment`

but what I get is `;m` binded to `hint -Jf ,comment` 

I just can't get why it is inserting that comma...

Any help?

Thanks.

**Comment by bovine3dom** [comment]
use `JS_ARGS.join(" ")` instead of `JS_ARGS`

it's an array so javascript stringifies it by default by inserting commas between elements

**Comment by m2habert** [comment]
thanks!
