### ISSUE TITLE
New tab setting with Tab Mix Plus

### ISSUE THREAD

**Issue by Massimo-B** [tridactyl/tridactyl#4145]
firefox-91.7.0
Tridactyl: Beta 1.22.0pre6186
Tab Mix Plus v1.0.0-pre.6

Hi, I'm using Tridactyl with Tab Mix Plus.
https://tabmixplus.org/
https://github.com/onemen/TabMixPlus

However the setting Addons->Extensions->TabMixPlus->Preferences->Events->NewTabs->Load on New Tab is overwriting the Firefox setting and does not allow Tridactyl to work on new tabs.
Possible settings in Tab Mix Plus are:

- New Tab Page, Address: "about:blank" or whatever
- Blank Page
- Home Page
- Current Page
- Duplicate Tab with history

When using the first item, I can set the address for a new page. Is there any address that would start Tridactyl just like Firefox does when opening a new tab?

**Comment by bovine3dom** [comment]
You could try `:tabopen` in Tridactyl to get a new tab page, copy the URL of that page with `yy`, and paste that URL, but I don't have much hope that it will work :)

Otherwise your best bet is to file and issue with tabmixplus asking for a setting that allows you to not change the new tab page.

**Comment by Massimo-B** [comment]
I did in the cross-referenced ticket.
However thanks for the hint, that workaround works. The New Tab setting for me is the cryptical address
`moz-extension://681afe6e-b94b-49bb-b44d-5d43c06498e5/static/newtab.html`.

**Comment by bovine3dom** [comment]
Great :)

You might want to switch to the stable builds of Tridactyl because I think that URL changes with every release (so if you stay on the betas you'll have to change it more often)

**Comment by onemen** [comment]
In Tab mix just leave the option for `New Tab Page, Address:` empy
