### ISSUE TITLE
.tridactylrc location profile based

### ISSUE THREAD

**Issue by Massimo-B** [tridactyl/tridactyl#4154]
As far as I know from 
https://github.com/tridactyl/tridactyl/wiki/Exemplar-.tridactylrc-files
the only locations are `~/.tridactylrc` or `~/.config/tridactyl/tridactylrc`
Why isn't this based on the Firefox Profile? This would allow to have separate tridactylrc per profile as all the addon configurations are actually profile-based.

I noticed that when migrating my Firefox profile to a new machine and forgot about my `~/.tridactylrc`. A better place would be in the profile path.
Would it be possible to have that file synced via Firefox sync somehow?
Is it possible to do all the lines of a .tridactylrc (most are `bind....`) alternatively in about:config and having that synced over machines?

**Comment by Massimo-B** [comment]
Any news here?

**Comment by bovine3dom** [comment]
Sorry I missed this issue, thanks for bumping it.

As I just replied in the other issue you can sync manually with `:firefoxsyncpu{sh,ll}`.

It's slightly tricky for us to detect FF profile directories - it's somewhat unreliable. What you could do instead is run `js tri.native.getProfileDir().then(dir => tri.excmds.source(dir + "/tridactylrc"))` in an RC file in the normal place to make it then read an RC file in your profile directory.

**Comment by Massimo-B** [comment]
Thanks.
