### ISSUE TITLE
Tridactyl causes tabs to crash instantly as of FF 99.0-1

### ISSUE THREAD

**Issue by gfarrell** [tridactyl/tridactyl#4187]
Every tab shows content for under a second then "Gah, your tab crashed!"

* I have tried reinstalling firefox-tridactyl
* Disabling tridactyl prevents this behaviour
* I have removed the native messenger in case this was causing issues

Firefox: 99.0-1
Tridactyl: 1.22.1-1
OS: Linux (archlinux)

I'm not entirely sure how to debug further, as nothing last longer than a split-second when tridactly is enabled.

**Comment by gfarrell** [comment]
It seems that, while having tridactyl enabled is making the browser _completely_ unusable, it still has some issues as tabs are randomly crashing.

**Comment by gfarrell** [comment]
And, furthermore, that these tab crashes happen in new profiles, too. I think this is something else in my system so I'm going to close the issue here.

**Comment by multun** [comment]
@gfarrell hey, I have the exact same issue with firefox 99 and leechblock, did you find out what's going on?

**Comment by gfarrell** [comment]
@multun see [this thread](https://bbs.archlinux.org/viewtopic.php?pid=2030775) on the ArchLinux forums.

**Comment by gfarrell** [comment]
For me it was an issue with font handling for monospace fonts.
