### ISSUE TITLE
Tridactyl breaks a website

### ISSUE THREAD

**Issue by aitchnyu** [tridactyl/tridactyl#4202]
Tridactyl version: 1.22.1
Firefox version: Mozilla Firefox 96.0
Operating system: linux

-   Brief description of the problem: Probably interacted with chatbox service and broke the whole page.

-   Steps to reproduce: visit the url 

-   Tridactyl version (`:version`): 1.22.1 

-   Firefox version (Top right menu > Help > About Firefox): Mozilla Firefox 96.0

-   URL of the website the bug happens on: https://www.42square.ai/

-   Config (in a new tab, run `:`, copy the url and paste it somewhere like gist.github.com): https://pastebin.com/VCFaFZdb

-   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
Insert tridactylrc contents between the backticks
```

-   Operating system:
-   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:
-   Unix-like only:
    -   `:native` less than 0.2.0: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:
    -   `:native` at least version 0.2.0: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main` in a terminal:

**Comment by bovine3dom** [comment]
Thanks for reporting, probably would be fixed by #639

**Comment by aitchnyu** [comment]
You are right. Thanks, will close this issue.
