### ISSUE TITLE
Tridactyl re-enabled on URLs added using blacklistadd on pressing Ctrl + comma (,)

### ISSUE THREAD

**Issue by anupamvamsi** [tridactyl/tridactyl#4234]
Tridactyl version: 1.22.1
Firefox version: Mozilla Firefox 100.0
Operating system: linux

-   Brief description of the problem: When `<C-,>` (escape hatch) has been pressed, Tridactyl reactivates on websites where it is disabled (using `blacklistadd`). However it works as intended on pages such as `about:config` or `about:preferences` where Tridactyl cannot work on. 

-   Steps to reproduce:

    1. Add the URL of the website (for e.g., `github.com`) using `blacklistadd` to disable Tridactyl.
    2. Open the website.
    3. Press `<C-,>`.
    4. The `ignore` mode changes to `normal` mode.
    5. On reload of the website, Tridactyl goes back to being disabled, but can be reenabled again with `<C-,>`.

P.S. on `mail.google.com`, (while logged in and when on the inbox page) the exact steps as above did not seem to work, but can be done:
    1. After blacklisting `mail.google.com`, the `<C-,>` does not work. 
    2. But if you activate the address bar (to edit) and then press `<C-,>`, `normal` mode is enabled like before.
    3. Steps 1 and 2 here are applicable to all other websites as well in addition to the original steps 1 to 5.

-   Tridactyl version (`:version`): 1.22.1

-   Firefox version (Top right menu > Help > About Firefox): 100.0

-   URL of the website the bug happens on: Any

-   Config (in a new tab, run `:viewconfig --user`, copy the url and paste it somewhere like gist.github.com): [viewconfig](https://gist.github.com/anupamvamsi/2927df4ea94694aa3768213e6863b259)

-   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist): NA

### Extra
This has been observed on Xubuntu (Ubuntu 20.04 LTS) running Firefox 100.0 inside a VM, but the issue was able to be reproduced on a machine with Windows 10 running the same version of Firefox.

**Comment by bovine3dom** [comment]
This is intended behaviour - the idea with ctrl-, is that you can always press : afterwards and have access to the Tridactyl command line. What would you prefer it did?

(The Google ctrl-, thing is a Firefox bug - Google shouldn't be able to steal ctrl-, from Firefox but it can)

**Comment by anupamvamsi** [comment]
I assumed that the extension would always be disabled / on `ignore` mode on the blacklisted sites. And on press of `<C-,>` it would go to the most recent tab where Tridactyl is enabled. Like how it works on the `about:config` page, for example?

This functionality is what I'd have preferred, since my intention / use case of blacklisting a site is for when I'm accessing my mails or some finance websites? (I get that blacklisting is also a feature for when websites don't play well with Tridactyl.) 

But maybe I'm better off doing those things in a private tab when the extension's not running?

Do let me know what you think.

**Comment by bovine3dom** [comment]
I think your usecase might be better served by `seturl [URL] superignore true` which almost totally disables Tridactyl on matching URLs, like happens on about:config.

blacklistadd/ignore mode just tells Tridactyl to ignore most keypresses by contrast. Perhaps we can improve the documentation somewhere :)

**Comment by anupamvamsi** [comment]
OK, that works great, it is indeed what I want, thanks!

Yes, I might agree, I was looking at the FAQ to see how I might disable Tridactyl:

> ![image](https://user-images.githubusercontent.com/39518444/168471699-7155627a-fca4-47cf-8dd0-02406cd30d6e.png)

Maybe, to this question's answer it would be more clear to add a note saying that Tridactyl is set in the `ignore` mode when URLs are added using `blacklistadd`. Then your answer to my use case, `seturl [URL] superignore true` can be mentioned that it can be used for disabling the extension (almost) entirely.

And I also had a look at #4215, the complete toggling on and off of Tridactyl through the FF toolbar would be really welcome, it was one of the things I was looking for.

Thanks for your quick and very helpful support, Tridactyl is awesome, I can see myself using and recommending it! :D
(Closing the issue.)
