### ISSUE TITLE
Allow `:tabopen` to _not_ focus page content

### ISSUE THREAD

**Issue by bew** [tridactyl/tridactyl#4259]
Hello!

I'm usually using Ctrl-t to open a tab and immediately type something as the address bar is focused.
My issue with Ctrl-t is that the tab is opened after all other tabs.

`:tabopen` opens right next to the current tab, which is more what I'm looking for.
However a tab opened with `:tabopen` auto-focus the page content, instead I would like to focus the address bar

I'm looking for an opt-in flag to tell tabopen to not focus page content and leave the focus on the address bar (like firefox's Ctrl-t).
Something like `:tabopen -focus-address-bar`

**Comment by bovine3dom** [comment]
I made the flag be `--focus-address-bar` to fit with the majority of our other multi-character flags ... although we're definitely not consistent about it

**Comment by bew** [comment]
Is it released yet?
I tried to add:
```
bind <A-t> tabopen --focus-address-bar
bind --mode=insert <A-t> tabopen --focus-address-bar
```
without much success (it opened a search for `--focus-address-bar` without my default search engine)

**Comment by bovine3dom** [comment]
Hey, nope, sorry, no releases yet. They're all blocked by #4261 which is stopping people from updating, so there's no point in making any releases until I merge that.

I'm on holiday at the moment - will try to get a release out with it in the first or second week of July : )

**Comment by bew** [comment]
Got it, have some nice holidays \o/
