### ISSUE TITLE
Open multiple URLs

### ISSUE THREAD

**Issue by tokuue** [tridactyl/tridactyl#4263]
Hi team,

I am trying to migrate from Pentadactyl to Tridactyl.

Pentadactyl has the ability to open multiple web pages at the same time by specifying multiple URLs in the open command.

Can you please add the same functionality to Tridactyl?

The following is an excerpt from the Pentadactyl manual.
The manual says "open" but "o", "t" and "p" also work with multiple URLs.

[Pentadactyl Browsing](http://bug.5digits.org/help/pentadactyl/browsing.xhtml#:open)
Open a single URL in the current tab, or multiple URLs in the current tab and background tabs. URLs may be separated with 'urlseparator', in which case the first URL is opened in the current tab and the rest are opened in new background tabs.

[Pentadactyl Options](http://bug.5digits.org/help/pentadactyl/options.xhtml#'urlseparator')
The regular expression used to split URL lists in commands like :open. When set to the empty string, URL lists are never split. With the default value, the following will open three URLs in the current tab and two new background tabs,

	:open google Linux | wikipedia Arch Linux | imdb Serenity

Thank you in advance.

**Comment by bovine3dom** [comment]
Hi, you could probably make your own command with `command multiopen js -d€ tri.excmds.open(JS_ARGS[0]); JS_ARGS[the rest but I can't remember the syntax].map(url->tri.excmds.tabopen("-b",url))€` but with more error checking and extra complexity if you want delimiters other than space

**Comment by tokuue** [comment]
Hi, Blanthorn.

Thanks for the reply.

I don't know much about Tridactyl or javascript, but I assumed that the method you presented would work the same way as the "o" command in Pentadactyl.

I mostly use the "p" or "P" command, i.e. copying multiple URLs to the clipboard and pressing the P key to open multiple web pages.

Is it possible to make it work the same way as the "p" command in Pentadactyl?

Thank you in advance for your help.

**Comment by bovine3dom** [comment]
Yeah, it's much the same but you would have to use `tri.excmds.getclip()` instead of JS_ARGS. It's an asynchronous function so it's easiest to use it like `js tri.excmds.getclip().then(urls -> {tri.excmds.open....`

I'll try to remember to look at this again this afternoon to just write the snippet for you exactly if you don't manage it yourself. Please remind me if I forget :)

**Comment by tokuue** [comment]
Hi, Blanthorn.

I would be very happy if you could present a complete program that works, as I am unable to complete it.

Thank you in advance for your help.

**Comment by bovine3dom** [comment]
```
:set searchengine google
:command pasteopen_tokuue jsb tri.excmds.getclip().then(urls => {const url_arr=urls.split("|"); tri.excmds.open(url_arr[0]); url_arr.slice(1).map(url=>tri.excmds.tabopen(...["-b", ...url.trim().split(" ")]))})
:command pastetabopen_tokuue jsb tri.excmds.getclip().then(urls => {const url_arr=urls.split("|"); tri.excmds.tabopen(url_arr[0]); url_arr.slice(1).map(url=>tri.excmds.tabopen(...["-b", ...url.trim().split(" ")]))})
:bind p pasteopen_tokuue
:bind P pastetabopen_tokuue
```

let me know if you have any problems with it :)

**Comment by tokuue** [comment]
Hi, Blanthorn.

I have tried to run the script you provided.

I was able to open multiple URLs, but the order of the tabs is not what I expected.

For example, when I open the following URLs, my expected order is locomotive, passenger car, freight car.
And the leftmost locomotive page is the active tab.
https://www.brawa.de/produkte/h0/lokomotiven/elektrolokomotiven/43806-traxx-ellok-br-1465db-ag/ | https://www.brawa.de/produkte/h0/wagen/personenwagen/twindexx-vario-ic2-mittelwagen-db-ag-1-kl/ | https://www.brawa.de/produkte/h0/wagen/gueterwagen/containerwagen-sffggmrrss-der-db/

When I opened with "P" the order was freight cars, passenger cars, and locomotives.
The active tab is the rightmost locomotive tab.

When I opened with "p", the order was locomotive, freight car, passenger car.
The active tab is the leftmost locomotive tab.

Is it possible to change it so that it opens in the order I expect and the leftmost is the active tab?

Also, I can no longer open the following URLs, although they are not multiple URLs.
https://www.audiaaa.com/usedcar/audi/tt-rs/tt-rs-coupe/url-1_15-list.htm#/i|t_warranty,1/s|10,AABY|1150,1/l|12,1,DATE_OFFER,U

I have only seen audi use pipes for URLs, but I would like to be able to use them if possible.

Thank you in advance for your help.

**Comment by bovine3dom** [comment]
Fixed the audi problem (now you always need a space before and after the pipe) and made `p` do what you want.

I've left `P` as it was because it would be harder to fix but also the reversed order makes more sense to me - if you copy `1 | 2 | 3 | 4` and try to open it with p or P, pressing `d` to close the tabs takes you through the tabs in the same order.

```
:set searchengine google
:command pasteopen_tokuue jsb tri.excmds.getclip().then(urls => {const url_arr=urls.split(" | "); tri.excmds.open(url_arr[0]); url_arr.slice(1).reverse().map(url=>tri.excmds.tabopen(...["-b", ...url.trim().split(" ")]))})
:command pastetabopen_tokuue jsb tri.excmds.getclip().then(urls => {const url_arr=urls.split(" | "); tri.excmds.tabopen(url_arr[0]); url_arr.slice(1).map(url=>tri.excmds.tabopen(...["-b", ...url.trim().split(" ")]))})
:bind p pasteopen_tokuue
:bind P pastetabopen_tokuue
```

**Comment by bovine3dom** [comment]
```
:set searchengine google
:command pasteopen_tokuue jsb tri.excmds.getclip().then(urls => {const url_arr=urls.split(" | "); tri.excmds.open(url_arr[0]); url_arr.slice(1).reverse().map(url=>tri.excmds.tabopen(...["-b", ...url.trim().split(" ")]))})
:command pastetabopen_tokuue jsb tri.excmds.getclip().then(async (urls) => {const url_arr=urls.split(" | "); await Promise.race([tri.excmds.tabopen("-w", url_arr[0]), tri.excmds.sleep(1000)]); url_arr.slice(1).reverse().map(url=>tri.excmds.tabopen(...["-b", ...url.trim().split(" ")]))})
:bind p pasteopen_tokuue
:bind P pastetabopen_tokuue
```

this version waits up to one second for the first tab to load before opening the other tabs. Unless you have a very slow machine I think these should always open in the order you want :)

**Comment by tokuue** [comment]
Hi. Blanthorn.

Thank you very much.

The program presented by Blanthorn worked as I expected.

But I could not understand why this program works as expected.
