### ISSUE TITLE
Allow Forward Slash Unbinding

### ISSUE THREAD

**Issue by thisisphan** [tridactyl/tridactyl#4286]
The / (forward slash) key conflicts with the "snap to search bar" shortcut of many search engines.

I'd love to be able to unbind it on specific URLs. 
I'm not aware of a fix to this currently.

Cheers!

**Comment by bovine3dom** [comment]
Apologies in advance for the silly setting name but

`:set leavegithubalone true`. You can use `seturl` to only affect certain websites if you prefer :)
