### ISSUE TITLE
Quirk with dark mode and transparent iframes

### ISSUE THREAD

**Issue by davidscotson** [tridactyl/tridactyl#4294]
I originally noticed this with a third party theme:

https://github.com/jrolfs/gruvbox-material-tridactyl

But, the same issue is visible in the midnight theme that ships with Tridactyl, and as far as I can tell it's a general issue with transparent iframes and dark mode and will affect any theme that uses a transparent iframe for shadows etc.

To reproduce:

log into github.com and go to the settings page where it lets you choose a user theme.

If you select any of their dark themes, the Iframe that tridactyl uses for it's commandline gets a solid white color. If you select any of the non-dark themes, it becomes transparent again.

I couldn't figure out what was happening from using the dev tools to inspect it, but this blog posts suggests it may be an interaction between dark mode and iframes:

https://fvsch.com/transparent-iframes

Which quotes a spec saying:

> In order to preserve expected color contrasts, in the case of embedded documents typically rendered over a transparent canvas (such as provided via an HTML <iframe> element), if the used color scheme of the element and the used color scheme of the embedded document’s root element do not match, then the UA must use an opaque canvas of the Canvas color appropriate to the embedded document’s used color scheme instead of a transparent canvas.

The fix seems to be setting color-scheme: light on the iframe, wwhich is the opposite of what seems logical, but does seem to fix the problem for me.

**Comment by davidscotson** [comment]
Adding version info to help track this down as not everyone sees this issue.

Mac OS 12.3.1 (21E258)
Firefox 102.0 (64-bit)
Tridactyl 1.22.1

**Comment by jrolfs** [comment]
I wasn't able to reproduce this issue until I upgraded to Firefox 102.
