### ISSUE TITLE
Native messenger won't install on M1 Mac (macOS 12.4)

### ISSUE THREAD

**Issue by mrafaeldie12** [tridactyl/tridactyl#4298]
-   Brief description of the problem:
Trying to install native messenger on Mac M1 doesn't work

-   Steps to reproduce:
1. Run :nativeinstall and get 
```
curl -fsSl https://raw.githubusercontent.com/tridactyl/native_messenger/master/installers/install.sh -o /tmp/trinativeinstall.sh && sh /tmp/trinativeinstall.sh 1.22.1
```
receive the following message
```
Installing manifest here: /Users/<my-user>/Library/Application Support/Mozilla/NativeMessagingHosts/
Installing script here: XDG_DATA_HOME: /Users/<my-user>/.local/share/tridactyl

Successfully installed Tridactyl native messenger!
Run ':native' in Firefox to check.
```
2. Run :native in tridactyl afterwards only to get an error that it doesn't detect the native messenger
3. Try to run the ./native_main and get this
```
zsh: bad CPU type in executable: ./native_main
```

-   Tridactyl version: 1.22.1

-   Firefox version (Top right menu > Help > About Firefox): 102

-   Config: https://pastebin.com/MQsdiyMt

-   Operating system: macOS Monterey 12.4

**Comment by dougmaitelli** [comment]
Related? https://github.com/tridactyl/native_messenger/pull/9

**Comment by mrafaeldie12** [comment]
Fixed by
- Cloning https://github.com/tridactyl/native_messenger
- Running nimble build --cpu:arm64 -o:native_main-arm64.py
- Running /.installers/install.sh/ local

**Comment by bovine3dom** [comment]
Do you have any idea what we were doing wrong in https://github.com/tridactyl/native_messenger/pull/9 ?

**Comment by mrafaeldie12** [comment]
Not entirely sure :( looks like the nativemessenger cli call is still fetching a non arm64 binary. The only thing I did really was clone the source and add the arm64 target.

Maybe this helps with debugging this is what I get out of the `nativemessenger` command in tridactyl cmd
```sh
curl -fsSl https://raw.githubusercontent.com/tridactyl/native_messenger/master/installers/install.sh -o /tmp/trinativeinstall.sh && sh /tmp/trinativeinstall.sh 1.22.1
```
