### ISSUE TITLE
Tridactyl hijacks `&lt;` (less than `<`)  input in any page input element

### ISSUE THREAD

**Issue by maricn** [tridactyl/tridactyl#4321]
Tridactyl version: 1.22.1pre6237-623b05ba
Firefox version: Mozilla Firefox 102.0.1
Operating system: linux

-   Brief description of the problem: Trying to type `<` doesn't produce any output (nor any other discernible outcome), as if tridactyl swallows it. I have to c/p it. If tridactyl is disabled, I can regain input on the pages. Otherwise, URL bar and other firefox inputs (settings, etc.) allow `<` to be typed. I can't find any binding with that character, nor I know how to properly escape it for binding in the first place.

-   Steps to reproduce:

    1.  2.  3.  4.  5.

-   URL of the website the bug happens on: everywhere

-   Config (in a new tab, run `:viewconfig --user`, copy the url and paste it somewhere like gist.github.com): https://gist.github.com/maricn/a86720274072a9899d747524e8aacd84/98cef79e3c7e816b7f544a21ad928aaae6e8ecac

-   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
" vim: filetype=tridactyl
" don't sanitize https://github.com/tridactyl/tridactyl/issues/1409
" sanitise tridactyllocal tridactylsync

" General Settings
set configversion 1.9
set update.lastchecktime 1593077346454
set smoothscroll true
set modeindicatorshowkeys true
set modeindicator false
set editorcmd foot nvim

" Theme
" set theme maricn-base16-gruvbox-dark-hard
" set colours maricn-base16-gruvbox-dark-hard
colourscheme maricn-base16-gruvbox-dark-hard

" Binds
unbind <F1>
" url increment/decrement
unbind <C-a>
unbind <C-x>
" scrolls
unbind <C-d>
unbind <C-u>
" unbind firefox shortcuts, but use default tridactyl
unbind <C-f> --mode=browser
unbind <C-b> --mode=browser
" clipboard tabopen
unbind p
unbind P
" repeat
unbind .
" unbind s
" unbind S
" unbind d
" unbind D
unbind u
unbind U
" unbind CTRL+I for external editor as that's often toggle for Italic font
unbind --mode=insert <C-i>
" unbind gf (view source) because I often do it by accident (ggggggf), and it's a really slow operation
unbind gf

bind d scrollpage 0.5
bind u scrollpage -0.5

" conflicts with <C-d> as "Bookmark this page"
" bind <C-d> scrollpage 0.7
" bind <C-u> scrollpage -0.7

bind <C-[> back
bind <C-]> forward

bind i mode ignore
bind --mode=ignore <escape> mode normal

bind t tabnew
bind J tabnext
bind K tabprev
bind x tabclose
bind --mode=ignore ^ tab #

bind / fillcmdline find
bind n findnext
bind N findnext -1
bind <Escape> composite mode normal ; hidecmdline ; nohlsearch

bind --mode=ex <ArrowRight> ex.insert_completion

bind --mode=insert <C-A-i> editor

" For syntax highlighting see https://github.com/tridactyl/vim-tridactyl
" vim: set filetype=tridactyl
```

-   Operating system:
-   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:
-   Unix-like only:
    -   `:native` less than 0.2.0: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:
    -   `:native` at least version 0.2.0: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main` in a terminal:

**Comment by bovine3dom** [comment]
I reckon your insert mode bind is the problem. Try:

```
:unbind --mode=insert <C-A-i>
:bind --mode=insert <CA-i> editor
```

Let me know if it persists :)
