### ISSUE TITLE
Improve docs for temporarily disabling or forwarding keys

### ISSUE THREAD

**Issue by xeruf** [tridactyl/tridactyl#4337]
# Making a feature request

## Problem

I want to activate https://revealjs.com/speaker-view/ with a simple press of `s` but neither deactivate Tridactyl nor unbind that key - just forward the key once.

## Potential Solutions
- Key binding that forwards the following key to the page
- Key binding to temporarily disable Tridactyl, or locally for the current tab

Maybe this is already available, but I could not find it :/

**Comment by bovine3dom** [comment]
Ctrl-v should send the next key to the page. It doesn't always work.

Otherwise you can toggle ignore mode with shift-insert.

**Comment by xeruf** [comment]
Thank you, works perfectly! Is that documented somewhere?

**Comment by bovine3dom** [comment]
I thought it was but I can't see it. We document the inverse - entering normal mode when you're already in ignore mode - here https://github.com/tridactyl/tridactyl/blob/fd1674a00005f313442ba2c0c96bd94dec9de977/src/static/clippy/1-tutor.md#L33 so we should probably add Ctrl-v in the section above.

Where did you look when you wanted to find out about it? They would be good places to add information :)

**Comment by xeruf** [comment]
The landing page, as that info should be available offline, too, without any extra effort ;)

https://github.com/tridactyl/tridactyl#default-normal-mode-bindings looks great, I guess that will be visible in the next release there?

**Comment by bovine3dom** [comment]
@xeruf no, that's a separate page to stop the new tab page becoming enormous. It is already mentioned on the new tab page here: https://github.com/tridactyl/tridactyl/blob/ed5633d2ac7d5483509c19b73fcf27cd0de84154/src/static/newtab.md#L38

**Comment by xeruf** [comment]
It's weird that this and `Shift-Insert` are not grouped together though
