### ISSUE TITLE
Copy element id

### ISSUE THREAD

**Issue by RyanGibb** [tridactyl/tridactyl#4345]
Is there a way to copy DOM element's id attribute with tridatyl?

**Comment by bovine3dom** [comment]
You should be able to do this with the callback hint mode

https://github.com/tridactyl/tridactyl/blob/fd1674a00005f313442ba2c0c96bd94dec9de977/src/excmds.ts#L4960

just call tri.excmds.yank()

**Comment by RyanGibb** [comment]
Thanks @bovine3dom !

The problem is hint only works for link elements.

Using `:bind i hint -JF e => {tri.excmds.yank(e.href)}` approximates this, but ideally something like `:bind i hint -JF e => {tri.excmds.yank(e.id)}` would work for non-link elements.

**Comment by RyanGibb** [comment]
It seems like:
```
:bind i hint -JF e => {tri.excmds.yank(e.href)}
```

Is equivalent to https://github.com/tridactyl/tridactyl/issues/1727

**Comment by bovine3dom** [comment]
Use `:hint -JFc [selector] [callback]` to specify a CSS selector to hint non-link elements :)

**Comment by RyanGibb** [comment]
That works!

```
bind i hint -JFc [id] e => { tri.excmds.yank(e.id) }
```

Thanks again for your help :-)

**Comment by RyanGibb** [comment]
For posterity, I ended up using
```
bind i hint -JFc [id] e => { tri.excmds.yank(document.URL + "#" + e.id) }
```
to get the full URL of an element
