### ISSUE TITLE
[ question : solved ]  any way to trigger a command from an error message?

### ISSUE THREAD

**Issue by m2habert** [tridactyl/tridactyl#4361]
If one inputs
   `:tab_helper false true https://web.whatsapp.com/` 
   and there's no whatsapp page open, tridactyl returns the following error:

  ` controller in excmd: Error: No tab found matching: https://web.whatsapp.com/ `

  Which prompts the question:

  ¿Is there a way to trigger an action / command in case of an error?

  (Of course, I would like to trigger `tabopen  https://web.whatsapp.com/` to streamline things up)

Thanks

**Comment by GHolk** [comment]
How about use the `promise.catch()` in js context?

E.g:
```
js tab_helper('false', 'true', 'https://web.whatsapp.com/').catch(e => tabopen('https://web.whatsapp.com'))
```

**Comment by m2habert** [comment]
Holly cow! THat's freaking perfect!  

I honestly thought it would not be that straight out doable as it did not popped up in the forum before.

Thanks a million, @GHolk !

**Comment by m2habert** [comment]
My take on "cleaning it up a bit":

`js let qurl =  'https://web.whatsapp.com/' ; tab_helper('false', 'true', qurl).catch(e => tabopen('-b', qurl))
`
(for the user who, like me, tiptoes clumsly around javascript)

**Comment by m2habert** [comment]
Even better :
                    `command myJumper js -p   tab_helper('false', 'true', JS_ARG).catch(e => tab (0).then(tabopen("-b", JS_ARG)))
`

so then 
`   :myJumper https://web.whatsapp.com/`

does the trick nicely.

**Comment by GHolk** [comment]
Nice command! Maybe you can close the issue and share it on wiki?
