### ISSUE TITLE
bind/unbind completions are unhelpful

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#4384]
The completion inserts the command as well which is pretty well useless. Interestingly, bind completions for :help don't have the same problem.

**Comment by GHolk** [comment]
Unbind's completions are useless to me, but I am used to modifying the existing binds from completions.
Are there other ways to show and edit the existing binds?

**Comment by bovine3dom** [comment]
It's not for editing the binds, it's just if you do `:help` there are completions for binds as well as settings and ex-commands. If you use help on a bind it takes you to the ex-command it is bound to.

**Comment by GHolk** [comment]
Without the completions, there is no convenient way to modify a long `composite` bind or a long `js` bind, though there is no convenient way for aliases, too.

For example, I have my own `ym`:
`bind ym js let t = document.title + '\n' + window.location.href; yank(t); fillcmdline_tmp(2000, t.replace('\n', ' '));` .
If I want to modify it, I have to `get nmaps.ym` and revise the result to a legal bind or set command.

There is another issue: I would like to remove the `=` in the output of `get` command, so I can edit it and prefix it with `set` to execute it directly.

**Comment by bovine3dom** [comment]
Huh, I hadn't thought of that use-case when I changed it. I think someone had complained on Matrix.

We could change https://github.com/tridactyl/tridactyl/blob/4ec0e5eb61d2c528c51a44cef5405fa5d0d83ddb/src/excmds.ts#L4209 to instead return a valid ex-command that you could edit, would that help?

**Comment by GHolk** [comment]
Thank, it will be helpful!
I did not see relevant messages on discord's general channel. Are there more channels on matrix?

**Comment by bovine3dom** [comment]
No, it's the same as Discord. It's possible I imagined it :)
