### ISSUE TITLE
tridactyl.cmcaine.co.uk is down

### ISSUE THREAD

**Issue by AlanWarren** [tridactyl/tridactyl#4396]
Hello, you may be well aware of this, but tridactyl.cmcaine.co.uk is offline.  If you're aware, then feel free to close this.  I realize sometimes these kind of things can go a while before you realize it, so just an FYI. 

Maybe it would be a good idea to store nightly builds on github?  

Thanks

**Comment by bovine3dom** [comment]
Thanks for the heads up! It's back up now.

> Maybe it would be a good idea to store nightly builds on github?

Unfortunately beta builds can't be automated as Mozilla requires a human to upload source code manually each release.

We could have completed automated "unsigned" nightly builds but actually getting those builds to run in Firefox is so complicated that I think it would create more problems than it solved :(

**Comment by AlanWarren** [comment]
> 

Thanks for the explanation. It does sound like you're making the best of the situation.  Really appreciate it!
