### ISSUE TITLE
Tridactyl no longer works together with Link Hints after latest beta (1.22.1pre6421-239ea592)

### ISSUE THREAD

**Issue by snippins** [tridactyl/tridactyl#4402]
-   Brief description of the problem:
I've been using Link Hints with tridactyl for a while, after the last tridactyl beta update, they're no longer work together, I need to disable Link Hints for tridactyl to works

-   Steps to reproduce:

Enable both Link Hints and tridactyl, then try using some tridactyl keybinds, it's not working.

-  Affected Tridactyl version: 1.22.1pre6421-239ea592
-  Last known working Tridactyl version: 1.22.1pre6200-21b7546b

**Comment by bovine3dom** [comment]
Thanks for reporting. Someone mentioned this a couple of weeks ago - #4387. Could you check some of the versions in between? https://tridactyl.cmcaine.co.uk/betas/?sort=time&order=desc

I suspect strongly that it's more to do with the order in which the add-ons are installed/updated rather than anything we have changed.

**Comment by snippins** [comment]
I just did a few tests on fresh profiles (I created a new profile for each test):

```
Install LinkHints 1.3.1
Install Tridactyl 1.22.1pre6421-239ea592 
-> Only LinkHints works
```

```
Install Tridactyl 1.22.1pre6421-239ea592 
Install LinkHints 1.3.1
-> Only LinkHints works
```

```
Install Tridactyl 1.22.1pre6200-an+fx
Install LinkHints 1.3.1
-> Both works
```

```
Install LinkHints 1.3.1
Install Tridactyl 1.22.1pre6200-an+fx
-> Both works
```

Which version of tridactyl that you would suggest me to try these tests with?

**Comment by bovine3dom** [comment]
https://tridactyl.cmcaine.co.uk/betas/tridactyl_beta-1.22.1pre6237-an+fx.xpi most importantly; and https://tridactyl.cmcaine.co.uk/betas/tridactyl2-1.22.1pre6337.xpi if you have time please :)

**Comment by snippins** [comment]
Here are the results:

```
Install tridactyl_beta-1.22.1pre6237-an+fx.xpi
Install LinkHints 1.3.1
-> Both works
```

```
Install LinkHints 1.3.1
Install tridactyl_beta-1.22.1pre6237-an+fx.xpi
-> Both works
```

```
Install tridactyl2-1.22.1pre6337.xpi
Install LinkHints 1.3.1
-> Only Link Hints works
```

```
Install LinkHints 1.3.1
Install tridactyl2-1.22.1pre6337.xpi
-> Only Link Hints works
```

**Comment by snippins** [comment]
I just tested with the latest beta and everything is fine now.
