### ISSUE TITLE
:hint -b doesn't open link in background

### ISSUE THREAD

**Issue by ericzwo** [tridactyl/tridactyl#4403]
-   Brief description of the problem: hint -b stoppen opening hints in the background

-   Steps to reproduce:

    1. fresh browser profile 
    2. install tridactyl beta 
    3. open website and use `:hint -b` or `F` 
    4. A new tab is opened in the foreground

-   Tridactyl version (`:version`): 1.22.1pre6421-239ea592

-   Firefox version : 105.0.1

This doesn't happen in 1.22.1pre6337.

I checked the commits since then and [fd1674a](https://github.com/tridactyl/tridactyl/commit/fd1674a00005f313442ba2c0c96bd94dec9de977) could be the offender.

I'm only on my work laptop for the next week and can't build tridactyl myself, but i can test any builds if necessary.

**Comment by bovine3dom** [comment]
yeah you're right:

```
Bisecting: 0 revisions left to test after this (roughly 0 steps)
Running post-checkout hook...
[fd1674a00005f313442ba2c0c96bd94dec9de977] Fix #4259: add --focus-address-bar flag to tabopen
```
