### ISSUE TITLE
Escape key not firing commands

### ISSUE THREAD

**Issue by ericliou** [tridactyl/tridactyl#4461]
-   Brief description of the problem:
`<Escape>` key doesn't exit hint/excmd mode, nor it unfocuses the input field.
`Ctrl-[` does work though.

I used some random web based keyboard tester and verified that the Escape key is indeed being read by the browser.

-   Steps to reproduce:
1. Go to any website
2. Enter hint mode
3. Press `Esc`

-   Tridactyl version (`:version`): 1.22.1

-   Firefox version: 106.0.5 (64-bit) 
(Arch wayland)

-   URL of the website the bug happens on: all I tried, e.g. duck.com

-   Config

Reinstalled with an empty config.
Also tried manually binding escape.

```
[" General Settings
set update.lastchecktime 1668187205517
set configversion 2.0

" Binds
bind --mode=hint <Escape> "hint.reset"](data:application/json,%7B"update"%3A%7B"lastchecktime"%3A1668187205517%7D%2C"configversion"%3A"2.0"%2C"hintmaps"%3A%7B"%3CEscape%3E"%3A"%5C"hint.reset%5C""%7D%7D)
```

From the logs, it seems that Escape key was not being detected and logged (like how `Ctrl-[` was). Please see below:

<details>
 <summary><b>controller debug log</b></summary>
<pre>

normal normal 
Array [ keydown ]
 
Object { value: "hint", exstr: "hint", isMatch: true, numericPrefix: undefined, keys: [] }
[controller_content.ts:171:23](moz-extension://e9e25754-711e-467e-9a64-d9e68cb10023/src/content/controller_content.ts)
Object { el: button.types__StyledButton-sc-ws60qy-0.jRRqKL
, name: "h" }
[hinting.ts:762:15](moz-extension://e9e25754-711e-467e-9a64-d9e68cb10023/src/content/hinting.ts)
Object { el: button#react-aria-20.types__StyledButton-sc-ws60qy-0.fYxgJI
, name: "j" }
[hinting.ts:762:15](moz-extension://e9e25754-711e-467e-9a64-d9e68cb10023/src/content/hinting.ts)
Object { el: a.Link-sc-hrxz1n-0.bOlDhZ
, name: "k" }
[hinting.ts:762:15](moz-extension://e9e25754-711e-467e-9a64-d9e68cb10023/src/content/hinting.ts)
Object { el: a.Link-sc-hrxz1n-0.hrDDEC
, name: "l" }
[hinting.ts:762:15](moz-extension://e9e25754-711e-467e-9a64-d9e68cb10023/src/content/hinting.ts)
Object { el: a.types__StyledButton-sc-ws60qy-0.eeYzta
, name: "a" }
[hinting.ts:762:15](moz-extension://e9e25754-711e-467e-9a64-d9e68cb10023/src/content/hinting.ts)
Object { el: a.types__StyledButton-sc-ws60qy-0.eeYzta
, name: "s" }
[hinting.ts:762:15](moz-extension://e9e25754-711e-467e-9a64-d9e68cb10023/src/content/hinting.ts)
Object { el: button.types__StyledButton-sc-ws60qy-0.hATlcl
, name: "d" }
[hinting.ts:762:15](moz-extension://e9e25754-711e-467e-9a64-d9e68cb10023/src/content/hinting.ts)
hint hint 
Array [ keydown ]
 
Object { exstr: "hint.pushKeyCodePoint 67", value: "hint.pushKeyCodePoint 67", isMatch: true }
[controller_content.ts:171:23](moz-extension://e9e25754-711e-467e-9a64-d9e68cb10023/src/content/controller_content.ts)
hint hint 
Array [ keydown Control ]
 
Object { value: "hint.reset", exstr: "hint.reset", isMatch: true, numericPrefix: undefined, keys: [] }
[controller_content.ts:171:23](moz-extension://e9e25754-711e-467e-9a64-d9e68cb10023/src/content/controller_content.ts)

</pre>
</details>

**Comment by bovine3dom** [comment]
For me `Escape` works and shows up fine in the logs. Could you tell us which keyboard layout you are using?

<details>
```
normal normal 
Array [ {…} ]
​
0: Object { key: "Escape", altKey: false, ctrlKey: false, … }
​​
altKey: false
​​
ctrlKey: false
​​
key: "Escape"
​​
metaKey: false
​​
shiftKey: false
​​
translated: true
​​
<prototype>: Object { … }
​
length: 1
​
<prototype>: Array []
 
Object { value: "composite mode normal ; hidecmdline", exstr: "composite mode normal ; hidecmdline", isMatch: true, numericPrefix: undefined, keys: [] }
controller_content.ts:179:23

```
</details>

**Comment by galenhuntington** [comment]
I am also having issues with Escape not exiting hint or exmd, but so far only on GitHub.  On other websites it works normally.  Furthermore, on GitHub `Ctrl-[` and `Ctrl-]` work like browser back and forward buttons, and the former does not escape.  I can't think what configuration I could have done that would cause these behaviors.  Turning on/off "Character keys" in my GitHub accessibility settings made no difference, nor did flipping `leavegithubalone`.

Probably not related, but Tridactyl isn't working at all for me on Twitter anymore.  I assume it's Musk's doing.

On Ubuntu Firefox 106.0.5.

**Comment by ericliou** [comment]
I'm using the `us` layout.
```
$ swaymsg -t get_inputs
[...]
Input device: Logitech K270
  Type: Keyboard
  Identifier: 1133:16387:Logitech_K270
  Product ID: 16387
  Vendor ID: 1133
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled
```

**Comment by ericliou** [comment]
After some debugging, I found out the issue. It's my Firefox `user.js`. 

For future reference, this is the line that was causing the problem. 
```
user_pref("permissions.default.shortcuts", 2);
```

Interestingly, with the above config, [some](https://www.keyboardtester.com/) keyboard tester websites does see my Escape presses, but [other](https://codepen.io/chriscoyier/pen/mPgoYJ) websites don't. I didn't dig deeper to understand why. Might be a Firefox bug? I'm not sure.

Anyway, thanks for the help @bovine3dom
