### ISSUE TITLE
Twitter disables/overrides shortcuts (cannot open new tab, go back, forward, follow links, open console)

### ISSUE THREAD

**Issue by boastful-inaba** [tridactyl/tridactyl#4469]
-   Brief description of the problem: Twitter appears to disable most/all Tridactyl functionality.  This has only happened in the past few weeks.

-   Steps to reproduce: Open https://twitter.com/, try to perform any basic Tridactyl keys (f, gt, d) etc

-   Tridactyl version (`:version`): 1.22.1pre6426-4ec0e5eb

-   Firefox version (Top right menu > Help > About Firefox): 107.0 (64-bit)

-   URL of the website the bug happens on: Any page or subpage of https://twitter.com/

-   Config (in a new tab, run `:viewconfig --user`, copy the url and paste it somewhere like gist.github.com):
 
```
{"update":{"lastchecktime":1668775053366},"configversion":"2.0","hintchars":"1234567890","hintfiltermode":"vimperator","theme":"dark"}
```

**Comment by bovine3dom** [comment]
Thanks @Rhys-T, that made it very easy to make a fix/workaround.

The history events won't work on Twitter until we find a real fix but I imagine almost no-one cares. But the rest of Tridactyl now works :)
