### ISSUE TITLE
Error processing pushKey([object Object]) InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable 

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#449]
1) Visit https://duckduckgo.com/?q=single+page+app&t=hf&ia=web
2) Press <kbd>f</kbd><kbd>k</kbd> (I wanted to select the third link but it selected the input field instead).
3) Press <kbd>Esc</kbd>, <kbd>f</kbd> and then <kbd>l</kbd>
4) An error message will appear, telling me `# Error: Error processing pushKey([object Object]) InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable `

This might be hard to reproduce since we probably won't get the same hints due to differences in screen sizes, fonts etc.

**Comment by wrycode** [comment]
I get this error on all web pages after installing the [Ghacks user.js](https://github.com/ghacksuserjs/ghacks-user.js). The bug appears, then goes away, and I haven't identified the culprit. It's possible that a security setting in about:config is preventing the extension from working properly.

**Comment by bryan-p** [comment]
I get this error whenever I press "f" and select a text field of type "email". To see if it was related to the field type I opened up developer tools and changed other field types (eg. password) to type email, in which case it started giving the error for that field also. I also changed fields from type "email" to type "password" or "text" and it no longer gives the error. I tested on different sites. So seems to be something specific to the field type being email or somehow related to that.

**Comment by bovine3dom** [comment]
@bryan-p could you update Tridactyl and see if you still get the error in version 1.13.1? 

Update by going to about:addons and clicking the cog in the top right, then "Check for Updates", then restart Firefox.

It should have been fixed by #649.

**Comment by bryan-p** [comment]
Looks like the issue is fixed in 1.13.1.  

Thanks

**Comment by glacambre** [comment]
Can't reproduce this bug anymore. @wrycode , have you experienced it lately?

**Comment by glacambre** [comment]
@wrycode Thanks, I'm going to close this issue then. If you ever hit this bug again feel free to report it here or in a new issue :)
