### ISSUE TITLE
`autocmd BeforeRequest` does not work on 1.23.0

### ISSUE THREAD

**Issue by medanisjbara** [tridactyl/tridactyl#4516]
-   `autocmd BeforeRequest` does not work on 1.23.0

-   Steps to reproduce:

    1. Update from 1.22.1 to 1.23.0. (Note that this is not a problem on 1.22.1)
    2. Enter a website that you have set `BeforeRequest` as an `autocmd` (example `autocmd BeforeRequest https://www.bbc.co.uk/* () => ({redirectUrl: "https://old.reddit.com"}).`)
    3. Enter the website and observe how it does not redirect ot the required link.
    

-   Tridactyl version (`:version`): 1.23.0

-   Firefox version (Top right menu > Help > About Firefox): 107.0.1 (64-bit)

-   Happens on all URLs that I tested them on.

**Comment by GHolk** [comment]
Yes, this does happen.
Firefox now will throw error if pass unsupported `extraInfoSpec` in `browser.webRequest.on*.addListener`.

Example:

```js
browser.webRequest.onBeforeRequest.addListener(
  ()=>undefined,
  {urls: ["https://motherfuckingwebsite.com/"]},
  ["blocking", "requestHeaders", "requestBody", "responseHeaders"]
)
// Uncaught Error: Type error for parameter extraInfoSpec (Error processing 1: Invalid enumeration value "requestHeaders") for webRequest.onBeforeRequest.
```

The 3ff4ff1 in #4309 is not merged, too.
I'm using tridactyl beta.

**Comment by GHolk** [comment]
Since we have tons of issues and PRs, maybe we can have a label like **next release**,
or just review all PRs labeled with **needs review** before release?

**Comment by bovine3dom** [comment]
Yeah, sorry, I don't know how I missed that PR. I thought I had merged it. I'll try to work on a better system...

**Comment by bovine3dom** [comment]
```
~/p/tridactyl ((5af29e72…)|BISECTING|✚1) $ git bisect bad
5af29e72466cc76fef0df89f6b73c52eaae0edbe is the first bad commit
commit 5af29e72466cc76fef0df89f6b73c52eaae0edbe
Author: gholk <gholk@disroot.org>
Date:   Sat Oct 29 15:13:34 2022 +0800

    Include header in webRequest BeforeSendHeaders and HeaderReceived events

    Since we already have blocking and requestBody, adding requestHeaders and
    responseHeaders should be okay too.

 src/background/webrequests.ts | 2 +-
```

introduced by #4438 but maybe that's what you were trying to tell us gholk

should I revert it for the time being or do you think there's an easy fix? I imagine we need to write ourselves a map of what is permitted to ask for and then ask for different things for each event

**Comment by GHolk** [comment]
Revert this will only make `onBeforeRequest` work, but other event (like `onHeadersReceived`) with different `extraSpecInfo` will still throw errors.
You can revert this and publish a hot-fix beta. Anyway we need to fix other event handlers.
I don't think it will be difficult.
