### ISSUE TITLE
[documentation/README] - update mention of themes and reference to bezmi

### ISSUE THREAD

**Issue by m040601** [tridactyl/tridactyl#4530]
This is just a hint for a simple update on the README.

Currently, the README at, https://github.com/tridactyl/tridactyl, mentions,

> Tridactyl can also load themes from disk or URL, which would let you use one of the themes authored by @bezmi `(bezmi/base16-tridactyl).` See :help colors for more information.

I went there, https://github.com/bezmi/base16-tridactyl
,  and I noticed that that repo hasnt been updated since April 2021.

There's a Github banner stating,

>  This repository has been archived by the owner before Nov 9, 2022. It is now read-only. 

And the author himself wrote,

> This repo is not actively maintained. If updates are needed to work with a new version of tridactyl, make changes, test them and submit a pull request!

Maybe it still works. Maybe not. I'm an end user. I dont have the skill to judge, neither the skill to update them or make a pull request. So I will ignore that repo.  There's so much stuff to study and configure with tridactyl. The less confusing and uncertain dead avenues I might entering the better.

My suggestion is therefore, to just remove that mention. Maybe leave it like this ?

> Tridactyl can also load themes from disk or URL, which would let you use one of the themes hosted online. See :help colors for more information. Or check the wiki for related pages.

So my point, as an end user,  is,  tridactyl's README  should  be short, concise, straight to the point, 100% idiot proof and geared towards the minimum to get started. The less loaded to links to third parties the better. The less need for checking references that might stale in a couple of month. That stuff belongs to the wiki, or in a "Advanced.md" file.

**Comment by bovine3dom** [comment]
The themes do still work. We should probably fork the repository and adopt it under the Tridactyl banner.

**Comment by bezmi** [comment]
I've had some reports that they still work, but I archived it as I am not an active user and can't really provide support. It would be great If someone would pick up the repo and tidy it up. At the time I knew no CSS and just copied bits from other themes.

**Comment by bovine3dom** [comment]
Thanks bezmi, I've forked the repo to the Tridactyl organisation - https://github.com/tridactyl/base16-tridactyl - and I'm happy for Tridactyl to take over maintenance. Thanks for sharing the themes!
