### ISSUE TITLE
In Orion, command palette only shows one line

### ISSUE THREAD

**Issue by robrecord** [tridactyl/tridactyl#4533]
Using latest beta, in [Orion browser](https://browser.kagi.com) (a WebKit browser that allows Firefox extensions):

Opening command mode using `:` I see only one line of text, even if more should be shown. Any text that would be shown above is clipped.

<img width="605" alt="Screenshot 2023-01-09 at 10 30 39" src="https://user-images.githubusercontent.com/38916/211288112-d5a61a94-0543-4a24-9664-5dad0a9256b1.png">

**Comment by bovine3dom** [comment]
Thanks for filing this issue :)

It looks like Orion doesn't support 100% of the APIs that Firefox does: https://browser.kagi.com/WebExtensions-API-Support.html

Notably missing from that is support for containers. We don't fall back gracefully when an API isn't available - everything just breaks. We would need to rewrite a fair chunk of Tridactyl to stop that from happening, which we're planning to do in #1619.

To keep things neat I'll close this issue in favour of that. It is unlikely to get fixed any time soon as it would be quite a lot of work.
