### ISSUE TITLE
`home` only opens one URL

### ISSUE THREAD

**Issue by rddunphy** [tridactyl/tridactyl#4575]
-   Brief description of the problem: `home` only opens one URL if `homepages` is set to multiple URLs. I'm assuming each is supposed to be opened in a separate tab?

-   Steps to reproduce:

    1. `:set homepages ["github.com", "xkcd.com"]`
    2. `:home`
    3. `xkcd.com` is opened in the current tab

-   Tridactyl version (`:version`): 1.23.0

-   Firefox version (Top right menu > Help > About Firefox): 109.0

**Comment by bovine3dom** [comment]
`:home true` - see `:help home` - should do what you want :)

**Comment by rddunphy** [comment]
Oops - don't know how I missed that! Thanks!
