### ISSUE TITLE
Disable/clear "browser stored" configurations

### ISSUE THREAD

**Issue by wizhi** [tridactyl/tridactyl#4579]
Tridactyl version: 1.23.0pre6655-504f1ecb
Firefox version: Mozilla Firefox 109.0.1
Operating system: mac

-   Brief description of the problem:

Settings/bindings/quickmarks are persisted between browser sessions.
This is really tripping me up, since I'm expecting Tridactyl to only load my RC file.

Specifically, from `mkt`:

> NB: an RC file is not required for your settings to persist: all settings are stored in a local Firefox storage database by default as soon as you set them.

I can't find any settings related to disabling this, nor any way of restoring defaults.

If this is desirable behavior to most users, that's fair, but would it be possible to add a reset command, which could be run at the start of the RC file or something then?

-   Steps to reproduce:

```
:quickmark a https://github.com
```

Restart Firefox and do `goa` to be navigated to https://github.com.

**Comment by bovine3dom** [comment]
You can wipe your settings with `:sanitise tridactyllocal` but don't put that at the top of your RC file or you will get very weird bugs (see #1409).

Instead you can wipe your settings on Firefox quit with e.g. `:bind ZZ composite sanitise tridactyllocal ; qall`

**Comment by wizhi** [comment]
Ah, amazing! I totally missed that.

Thanks a bunch for the help and tips - and for the plugin, it's awesome work. :)
