### ISSUE TITLE
Container related commands

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#459]
Related to #283.

It would be nice to somehow support autocommands to automatically put URLs into specified containers.

**Comment by antonva** [comment]
Very related: [https://github.com/mozilla/contain-facebook/blob/master/src/background.js#L386](https://github.com/mozilla/contain-facebook/blob/master/src/background.js#L386)

**Comment by glacambre** [comment]
This is what `autocontain` does, isn't it?

**Comment by bovine3dom** [comment]
Yeah, good spot.
