### ISSUE TITLE
;m and ;M not working

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#4591]
@bovine3dom ;m and ;M haven't been working for me for nearly 1-2 years now, for reverse (Google) image searching. 

Did they work before? Yes. 

(2/10/23, 11:40 PM)

_Originally posted by @yarub123 in https://github.com/tridactyl/tridactyl/issues/113#issuecomment-1426648894_

**Comment by yarub123** [comment]
Thank you. ♥️
