### ISSUE TITLE
How can I avoid autocomplete tab index when pressing space?

### ISSUE THREAD

**Issue by nuynait** [tridactyl/tridactyl#4638]
If I press `b`, it brings out the buffer list. Then if I enter text like: `tridactyl` it will filter the buffer list with the keyboard. However, if I want to search for `tridactyl issues`, it will not further filter the list. The moment the space is pressed, it autocomplete the text with the tab index. 

How can I avoid it doing so and make it able to filter buffer list with multiple keywords?

**Comment by bovine3dom** [comment]
Ctrl+space to insert a space even if something is selected.

You can view binds available in the command line with `:bind --mode=ex `, maybe there are other useful ones you aren't aware of :)


If the behaviour annoys you too much you can unbind space or you can disable autoselect with `:set completions.Tab.autoselect false`

**Comment by nuynait** [comment]
Hi @bovine3dom, thank you so much for all of your wonderful tips. They have worked perfectly for me.
