### ISSUE TITLE
Addon configuration & info screen website URL

### ISSUE THREAD

**Issue by pataquets** [tridactyl/tridactyl#4647]
Currently, in the home/website page URL it reads https://github.com/cmcaine/tridactyl, instead of https://github.com/tridactyl/tridactyl.
I guess it's an outdated/moved link, since opening correctly redirects to the current repo.

**Comment by bovine3dom** [comment]
Thanks for filing this issue.

Do you mean on https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/ ? I found two outdated links which I have updated. Please tell me if I missed any :)
