### ISSUE TITLE
Counts are broken

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#466]
`3b` used to do `fillcmdline buffer 3`; `2.` used to repeat the last action twice. Probably broken by keyseq.

**Comment by diefans** [comment]
the same for history back e.g. `5H`

**Comment by bovine3dom** [comment]
@cmcaine bump : )

**Comment by glacambre** [comment]
Related: https://github.com/cmcaine/tridactyl/issues/269 .

**Comment by mg979** [comment]
Is this going to be fixed? *[n]gt* doesn't work, there's no way to switch to a particular tab. Thanks

**Comment by bovine3dom** [comment]
I personally don't use it, and I'm spending all the time I have for Tridactyl on trying to rewrite the command line, so probably not any time soon.

I'd be delighted to help you get started if you wanted to give it a go.

**Comment by mg979** [comment]
What should I do if I wanted to give it a try? I mean, how to rebuild the extension from the source and test it in Firefox?

**Comment by bovine3dom** [comment]
Scroll down to contributing on the main GitHub page: https://github.com/tridactyl/tridactyl

**Comment by mg979** [comment]
Ok thanks, I'll try.

**Comment by bovine3dom** [comment]
There's not much point in my giving you the exact commit - it "broke" when we moved from a "dumb" key sequence parser to one that supported modifiers. I say "broke" in quotes because cmcaine simply forgot to re-implement it.

The offending function is here: https://github.com/tridactyl/tridactyl/blob/2046dc2d26db80b53c447442360df272e99f4738/src/lib/keyseq.ts#L114

You need to detect counts in this function and then return them here https://github.com/tridactyl/tridactyl/blob/2046dc2d26db80b53c447442360df272e99f4738/src/lib/keyseq.ts#L137 with `... exstr: perfect[1] + ` ${count}` ...`
