### ISSUE TITLE
Yank in neovim as native messenger seems to break stdin 

### ISSUE THREAD

**Issue by inyutin** [tridactyl/tridactyl#4678]
# Reporting a bug / getting help

-   Brief description of the problem:
When yank in neovim that is opened via native messenger, the text from neovim stop to appear in Firefox
Basically, if there is no yank it works fine.  But if there was a yank, it not sending text from neovim to Firefox anymore

-   Steps to reproduce:

1. Find any input on any website
2. Focus on the input, run  Ctrl + I
3. Write something into neovim
4. Input "yy" into neovim (yank command)
5. Close neovim window via ":wq"
6. You will see the text from neovim doesn't appear in Firefox. But it should

I saw similar issues: https://github.com/tridactyl/tridactyl/issues/4429
It seems the problem should have been fixed in 0.3.7 version of native messenger. But I use version 0.3.8 and the problem is still appears 

I also tried to fetch some logs, as mentioned in troubleshooting guide, but there is nothing.
I'm willing to help as much as I could on this.
    
    ---------------
    
    
-   Tridactyl version (`:version`): 1.23.0

-   Firefox version (Top right menu > Help > About Firefox): 112.0

-   URL of the website the bug happens on: Any

-   Config (in a new tab, run `:viewconfig --user`, copy the url and paste it somewhere like gist.github.com): https://gist.github.com/inyutin/da32729615c3405a354e0d2796b50788

-   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist): they do not exist

-  Operating system: Manjaro Linux x86_64, 5.15.106-1-MANJARO
-  Native version: 0.3.8

**Comment by bovine3dom** [comment]
Could you see if you can reproduce it in a clean nvim profile?

`:set editorcmd /usr/bin/alacritty -e /usr/bin/nvim --clean`

I can't reproduce it with true vim or nvim using these steps, with native 0.3.7 on Linux

1. `:set editorcmd konsole -e nvim`
2. Ctrl+I in a github issue reply
3. Write something
4. `yy:wq`
5. text appears as expected

**Comment by inyutin** [comment]
Thank you for a quick investigation. 
With "clean" it's working fine. So the problem on my side
Sorry for a waste of time and thank you once again

**Comment by bovine3dom** [comment]
It wasn't a waste of time, I learnt something about `nvim` :)

Thanks for reporting it!
