### ISSUE TITLE
Support editing about:config via prefs.js/user.js

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#468]
http://kb.mozillazine.org/User.js_file and http://kb.mozillazine.org/Prefs.js_file

We should probably write to user.js and read from prefs.js and user.js.

Unfortunately it will require a restart unless we can get #460 working.

(Edit: main suggested use case: browser.uidensity 1)

**Comment by glacambre** [comment]
This is essentially what https://github.com/tridactyl/tridactyl/issues/940 is about. Closing this one as the other has more information about how to proceed and is thus more likely to attract first-time contributors.
