### ISSUE TITLE
Support: how to open a new tab, but in "discarded" mode

### ISSUE THREAD

**Issue by pataquets** [tridactyl/tridactyl#4694]
I've installed this add-on:
https://addons.mozilla.org/ca/firefox/addon/simple-discard-tab/
It also provides a convenient menu item on the link's right-click menu "Open in discarded tab", which speeds up opening multiple tabs, specially with heavy (lots of JS) websites.

I was wondering if Tridactyl could do this, but neither `open` nor `tabopen` have any parameter to do it. Searching for issues brings up #4148, which I guess would just allow to just open a tab normally and later discard it. The above add-on does not seem to do it this way, just opening the tab discarded from the very beginning, so I guess there's a function/API/etc in Firefox which allows this.

Is this possible from Tridactyl?

**Comment by bovine3dom** [comment]
We could add this quite easily, we just need to pass `{discarded: true}` to tabs.create https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create

I'm assuming you would mostly want to use it with hint modes?

**Comment by pataquets** [comment]
You're absolutely right :smile:
Having that flag available would be useful, then.

El ds., 6 maig 2023, 6:42 p. m., Oliver Blanthorn ***@***.***>
va escriure:

**Comment by bovine3dom** [comment]
`:tabopen --discard` and `;gd` / `;d` hint modes added, should appear in the next betas and 1.24.0 stable whenever I get round to releasing them :)
