### ISSUE TITLE
`focusinput`'s weird behaviour on google search box

### ISSUE THREAD

**Issue by shisui98** [tridactyl/tridactyl#4706]
-   Brief description of the problem: ` :focusinput ` has weird behaviour on Google search input box.

-   Steps to reproduce:

    1.  Visit google.com.
    2. Use ``` gi ``` to focus input on the search bar if it's not focused already.
    3. Type in anything, in this case "Tridactyl" and hit enter.
    4. Now use ``` gi ``` again to focus input on the search bar.
    5. You'll see that the cursor is placed at the start/front of text and not at the end of text/line.

    I remember clearly the default behaviour to be latter (cursor at end of text) in google and it is still the default behaviour in other search engines (tested on duckduckgo and startpage). While this realy isn't a big problem, it kinda feels off when the behaviour is exclusive to Google search input.

- My current workaround
    
    Easy. ` :bind --mode=input <C-e> text.end_of_line `

-   Firefox version: 102.11.0esr (64-bit) with Tridactyl 1.23.0
-   Waterfox version: 5.1.4 (64-bit) with Tridactyl 1.23.0pre6760-a5196759 (Waterfox is a fork of Firefox)

-   URL of the website the bug happens on: [Google](https://www.google.com)

-   Config: [viewconfig_user.json]( https://pastecode.io/s/04q0uic7 )

-   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc: N/A

    ***EDIT: Disabling javascript seems to fix the issue.***

**Comment by bovine3dom** [comment]
Thanks for filing this issue. I noticed it a while ago and it really annoys me too.

We might be able to add a workaround just for Google but no promises :)

**Comment by rlch** [comment]
Hey guys, thanks for raising this and providing a workaround.

I've improved the workaround a little bit so that `gi` is the only command required to replicate the original behaviour:
`bind --mode=normal gi composite focusinput -l | text.end_of_line`

**Comment by bovine3dom** [comment]
Ah, thanks, that would be easy to add as a site specific default, I'll try to remember to do it
