### ISSUE TITLE
Tridactyl could not be verified for use in Firefox and has been disabled.

### ISSUE THREAD

**Issue by mddvul22** [tridactyl/tridactyl#4717]
Firefox ESR (102.11.0) just disabled my Tridactyl add on.  

![image](https://github.com/tridactyl/tridactyl/assets/6833993/0c0411dd-63af-44ca-9506-90c0655abc55)

When I click on the More Information button: I get a page with the following text:

Add-ons that can change your browser's settings without your consent or steal your information have become increasingly common. Some add-ons can add unwanted toolbars or buttons, change your search settings or inject ads into your computer. Firefox does now verify that the add-ons you install have been signed by Mozilla, digitally. This article explains the add-on signing feature and how it works.

-   Tridactyl version: 1.23.0.

-   Firefox version: 102.11.0

**Comment by bovine3dom** [comment]
That's weird, do you remember where you installed Tridactyl from? Tridactyl is signed if you get it from the Firefox add-on store or if you get the beta from our site.

If you're using Arch and you install Tridactyl from the package manager, you also need to install Firefox from the package manager. It's possible that the ESR version gets less attention and so is missing the required patches.

**Comment by mddvul22** [comment]
Thanks for the reply.  I don't recall where I installed it from.  However, based upon your reply, I removed it and then searched for it in the add-on store and Firefox allowed me to install it.  So, things are good now.  Much appreciated!
