### ISSUE TITLE
Feature request: add pagescroll support for hint mode, and auto refresh "gF"  hints on pageup/pagedown

### ISSUE THREAD

**Issue by QiangF** [tridactyl/tridactyl#4754]
On a web page with a lot of links, I use "gF" to open in other tabs, currently if I need to open links in the other page areas, I need to escape hint mode with "Esc", scroll the page, and go back to hint mode with "gF".

An better alternative is this feature request: just hit PageUp/PageDown (or use the firefox default shortcuts: Shift+Space or Space), and keep the hint mode active.

It will save 3 key presses.

**Comment by bovine3dom** [comment]
It's not exactly the most elegant or obvious of commands but you can do this already with e.g.

```
bind --mode=hint <C-d> composite js tri.hinting_content.getHintCommands().reset() ; scrollpage 0.5 ; hint -qb
```

swapping `<C-d>` and `scrollpage 0.5` for whatever navigation commands you like.

I agree that it should be a default feature

**Comment by QiangF** [comment]
> 

After issuing that command, and I confirmed that C-d is binded to that command. It doesn't work as expected. Step to repeat.
1. open google.com, search for anything
2. "gF" go to hint mode
3. "C-d"
I can not get the page scrolling. The screenshot is below:
![Uploading img_2023_09_04__09_39_43.png…]()

**Comment by bovine3dom** [comment]
> , and I confirmed that C-d is binded to that command in ":viewcfg nmaps". 

Are you sure? It should appear in `hintmaps` not `nmaps`; did you miss out the ``--mode=hint`?

**Comment by QiangF** [comment]
Oh, it's so easy, I just bind Shift-Space to scroll page up:

    bind --mode=hint <S-Space> composite js tri.hinting_content.getHintCommands().reset() ; scrollpage -1 ; hint -qb

**Comment by bovine3dom** [comment]
Interesting, the Ctrl-d bind works for me, I tried it before I replied to the issue. Glad you found a solution that works for you.
