### ISSUE TITLE
Jumplist accross tabs

### ISSUE THREAD

**Issue by RyanGibb** [tridactyl/tridactyl#4755]
`tab #` is really useful for toggling between two active tabs, but I often find myself wanting to travel further back in my focus history.

I thought the jumplist might be a way to do this, but `jumpnext` and `jumpprev` only work within a single tab.

Is it feasible to have a 'jumplist' of tabs visited?

**Comment by bovine3dom** [comment]
If you do `:set tabsort mru` `:tab ` turns into this. `[n]gt` then takes you to the nth most used tab

**Comment by RyanGibb** [comment]
Thanks, I'll give it a try!
