### ISSUE TITLE
Feature request:  bind C-p and C-n to previous and next in a completion list, eg. when selecting tabs with "b" in normal mode.

### ISSUE THREAD

**Issue by QiangF** [tridactyl/tridactyl#4757]
1. C-p and C-n works just like Shift-Tab and Tab.
2. don't block the input area by echoing the tab url in "b"

**Comment by bovine3dom** [comment]
We can't bind to Ctrl+N because Mozilla won't let us - see #996.

I don't understand what you mean with your second point - is that when you do `<C-o>yy`?

**Comment by QiangF** [comment]
The second point is about the overlap of the input area with the echo area.
I can't get that problem repeat reliably. You may try:
1. go to normal mode
2. type b to get the tab list
3. type any character to filter, sometimes the first cadidate's url is printed in the echo area, as I said before, the echo area shares the screen area with the input area, so the input is block, not visible.

**Comment by bovine3dom** [comment]
I'm still not really understanding, is it when you press space and the highlighted completion is inserted? You can run `:unbind --mode=ex <Space>` if you want to stop that

**Comment by QiangF** [comment]
I have seen any blockage by echoing message today. I love this add-on!
