### ISSUE TITLE
[ help ] trimming current url thru sed not working

### ISSUE THREAD

**Issue by m2habert** [tridactyl/tridactyl#4761]
Simply put, if 
`composite get_current_url | shellescape | !s echo > ~/test.txt `

works 
and, in bash, 
`A='https://example.com/'   ;   echo $A | sed 's/https://'  > ~/test.txt  `
also works...

¿why can't I make the following work in tridactyl?

: 
 `composite get_current_url | shellescape | !s echo | !s sed "s/http//" > ~/test.txt `

( test.txt gets blank ) 

thanks in advance (the simpler the stuck, the bigger the hang up!)

(ideally I'd like to trim an url and send it to the clipboard thru `| pbcopy`  )

**Comment by bovine3dom** [comment]
Tridactyl pipes paste the output of the previous command at the end of the next command

so

```
composite get_current_url | shellescape | !s echo | !s sed "s/http//" > ~/test.txt 
```

will actually result in 

```
 !s sed "s/http//" > ~/test.txt [escaped URL here]
```

You have another problem in that `sed` requires stuff to be piped to it. You're better using `tri.native.run` so that you can use native pipes, e.g.

```
js (async () => {await tri.native.run("echo " + (await tri.excmds.shellescape(document.location.href)) + " | sed 's/http//' > ~/test.txt")})()
```

---

> (ideally I'd like to trim an url and send it to the clipboard thru | pbcopy )

if that's all you're trying to do, why not just use `:js`? e.g. `js tri.excmds.clipboard("yank", document.location.host + document.location.pathname)`

**Comment by m2habert** [comment]
> if that's all you're trying to do, why not just use :js? e.g. js tri.excmds.clipboard("yank", document.location.host + document.location.pathname)

... err, ¿becaaaaaause I'm stoooooooopid?

Self-debasing joke aside, you're right:  that's a neat and simple solution... and one I would be able to reach on my own if I were not so set in seeking a "shell" solution.

But, as usual: ¿why not (be more maleable)?

(on the other hand, I was bugged out to understand the `!s` proper working, and your explanation takes care of that.)

Thanks again, @bovine3dom , for the prompt help.

**Comment by bovine3dom** [comment]
The third line of code I replied with does solve it using the shell and `sed` :)

If that works for you can we close the issue?

**Comment by m2habert** [comment]
o, yes, totally.

(Sorry, I guess it would be more streamlined if I did say "thanks" and also close the issue.)
