### ISSUE TITLE
wrong behavior when neovim (using native) changes the content of clipboard

### ISSUE THREAD

**Issue by alanoliveira** [tridactyl/tridactyl#4771]
# Reporting a bug / getting help

-   Brief description of the problem:
Seems the same issue from https://github.com/tridactyl/tridactyl/issues/4678, but OP missed the `unnamedplus` detail
When I yank some text inside neovim, tridactyl 'freezes' the input field

-   Steps to reproduce:
1. `:set editorcmd /usr/bin/alacritty -e nvim --clean -c 'set clipboard=unnamedplus'`
2. Ctrl+I in a github issue reply
3. Write something
4. yy:wq

-   Tridactyl version (`:version`):
tested with `1.23.0` (native `0.3.6`) and `1.23.0pre6803-89a7e613` (native `0.4.0`)

-   Firefox version (Top right menu > Help > About Firefox):
`117.0.1 (64-bit)`

-   Config (in a new tab, run `:viewconfig --user`, copy the url and paste it somewhere like gist.github.com):
```json
{"editorcmd":"/usr/bin/alacritty -e nvim --clean -c 'set clipboard=unnamedplus'"}
```

-   Operating system:
`6.1.53-1-MANJARO`

-   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:
`/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin`

-   Unix-like only:
`R{"cmd":"run","content":"/home/alan/.cargo/bin:/home/alan/.asdf/shims:/opt/asdf-vm/bin:/home/alan/.local/share/zinit/polaris/bin:/home/alan/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin\n","command":"echo $PATH","code":0}`

**Comment by bovine3dom** [comment]
Thanks for reporting this. For clarity, without the `set clipboard=unnamedplus`, it works?

**Comment by alanoliveira** [comment]
Thank you for your attention.
Without `set clipboard=unnamedplus` not freezes, but I can't preserve the clipboard after I close nvim

**Comment by alanoliveira** [comment]
I think I found the issue
neovim is using xclip to make the interface with GUI clipboard.
It seems when we copy something to xclip, it starts a process that lives until we replace the clipboard with something not related to xclip.
So tridactyl keeps waiting until the xclip process die to release the input


To reproduce
1. `set editorcmd xclip -sel clip` (it will copy the input content to clipboard)
2. ctrl+I in a github issue reply
3. the input will  freeze with Tridactyl logo
4. to unfreeze `ctrl+c` in any text or kill xclip process


It is interesting that if in nvim we run `!xclip -sel clip <<<'a'` Tridactyl will keep waiting xclip process, but if we start a terminal buffer `:terminal bash` and inside this terminal we run ` xclip -sel clip <<<'a'` Tridactyl will not wait (but the xclip process will be there)

**Comment by alanoliveira** [comment]
This seems prevent the issue
```
alias editor_xclip composite js document.activeElement.addEventListener('focusin', e => { if(e.target.classList.contains('TridactylEditing')) tri.native.run('xclip -sel clip -o').then(c => tri.excmds.yank(c.content.slice(0, -1))) }, {'once': true}) | editor
bind --mode=insert <C-i> editor_xclip
bind --mode=input <C-i> editor_xclip
```

I don't think there is nothing to be done in Tridactyl, right?
If so I apologize for the confusion you can close this issue

**Comment by bovine3dom** [comment]
Hmm, yeah, I'm not sure that we can do much about this. I think in general it's the right behaviour to wait for child processes to die. Maybe in the distant future we could name a list of processes that we wouldn't wait to exit, but I think I'll close the issue for now unless lots of other people run into it.

Sorry for the slow reply :)

**Comment by bovine3dom** [comment]
@alanoliveira looking around on the internet, people are suggesting setting an autocommand in neovim to kill all xclip processes on exit

**Comment by alanoliveira** [comment]
It actually solves the hanging issue, but when we kill xclip it lose the clipboard.

**Comment by bovine3dom** [comment]
Maybe it's a neovim bug? Shouldn't it disown the process before exiting?

**Comment by alanoliveira** [comment]
Make sense
I was trying to find a way to reproduce it, so I could report on nvim repository, then I tried

```nim
import osproc
let process = startProcess("tobuterm nvim", options = {poEvalCommand, poStdErrToStdOut})
discard waitForExit(process)
close(process)
```
and it worked fine (it not hanged and not killed xclip).  
Do you have any guess why?

**Comment by bovine3dom** [comment]
Are you sure it is running with the `unnamedplus` setting? Otherwise it could be that `waitForExit` is doing something different to us
