### ISSUE TITLE
`tabgrab`/`tabpush` move next to current tab

### ISSUE THREAD

**Issue by dcaixinha** [tridactyl/tridactyl#4773]
Tridactyl version: 1.23.0
Firefox version: Mozilla Firefox 117.0.1
Operating system: linux

# Making a feature request

First of all, thanks for this amazing package :raised_hands: I searched in the help section and on GitHub issues / PRs, but couldn't find what I was looking for!

Whenver I use `tabpush`/`tabgrab`, the tab is moved to the end of the tab list. Is there any option to move it next to the current tab? I already have the following set in the `about:config` page:
```
browser.tabs.insertAfterCurrent true
browser.tabs.insertRelatedAfterCurrent true
```

Thanks!

**Comment by bovine3dom** [comment]
We'd have to tweak the index on this line here: https://github.com/tridactyl/tridactyl/blob/80d00d4db7bcc8f07487b386ea79cebf76ff5b12/src/excmds.ts#L2684

I'm not sure whether it should follow the "tabopenpos" setting or if we should add a separate setting, or if it should be a flag to the command ... what do you think?

**Comment by dcaixinha** [comment]
I think we should use the same `tabopenpos` setting. IMHO users who want to have their tabs opened next to the current tab will also want it when moving tabs around. If a use-case is presented later on for a different setting we can always break it into a different setting later. Can I try to take a stab at this? I'm not a JS developer, but I think I can make this one.

**Comment by bovine3dom** [comment]
I think you're right. Yes, please do have a go at implementing it. Don't hesitate to ask for help if you need it :)
