### ISSUE TITLE
Shortcut for Page Info window doesn't work

### ISSUE THREAD

**Issue by zk395** [tridactyl/tridactyl#4793]
The keyboard shortcut for the Page Info window (Ctrl+I) does nothing in a tab where Tridactyl is active, is there a way to circumvent this? This is the window I'm talking about:

https://support.mozilla.org/en-US/kb/firefox-page-info-window

**Comment by bovine3dom** [comment]
To access it once, press ctrl-v then ctrl-i.

To access it forever run `:unbind <C-i>`
