### ISSUE TITLE
Iframe clobbered on certain websites

### ISSUE THREAD

**Issue by zeorin** [tridactyl/tridactyl#4807]
Any website that (re)creates the whole DOM tree may clobber the iframe. Example: https://remix.run/

I notice this a lot on websites built with Remix. As a result, when I try to invoke any command that requires the command line, nothing happens, and this error is logged to the console:

```
14:40:20.955 TypeError: cmdline_iframe.contentWindow is null
    show moz-extension://56b76a2f-6d64-475d-bc28-966b0af3996b/content.js:16434
    showcmdline moz-extension://56b76a2f-6d64-475d-bc28-966b0af3996b/content.js:21087
    fillcmdline moz-extension://56b76a2f-6d64-475d-bc28-966b0af3996b/content.js:21100
    acceptExCmd moz-extension://56b76a2f-6d64-475d-bc28-966b0af3996b/content.js:13727
    ParserController moz-extension://56b76a2f-6d64-475d-bc28-966b0af3996b/content.js:16212
    acceptKey moz-extension://56b76a2f-6d64-475d-bc28-966b0af3996b/content.js:16219
    guardedAcceptKey moz-extension://56b76a2f-6d64-475d-bc28-966b0af3996b/content.js:23435
content.js:16437:15
```

**Comment by GHolk** [comment]
I experienced this bug, too.
I would add a autocmd to save the iframe node, and define a command to re-append it to the web-page.

eg:

```
autocmd DocStart ^https://some.url js tri.cmdlineIframe = document.getElementById('cmdline_iframe')
command cmdline_append js document.documentElement.appendChild(tri.cmdlineIframe)
```

**Comment by zeorin** [comment]
Thanks @GHolk, I ended up going with the following, which should fix it for all sites:

```vim
autocmd DocStart .* js tri.cmdlineIframe = document.getElementById('cmdline_iframe')
autocmd DocLoad .* js requestAnimationFrame(function reattachCmdlineIframe() { !document.documentElement.contains(tri.cmdlineIframe) && document.documentElement.insertBefore(tri.cmdlineIframe, document.documentElement.firstElementChild); requestAnimationFrame(reattachCmdlineIframe) })
```

**Comment by zeorin** [comment]
> I don't think call `reattachCmdlineIframe` 60hz in every tabs is a good idea.
It's a no-op if the iframe is actually there. `requestAnimationFrame` gets throttled if computer is busy, and halted when the tab isn't active. I'd rather do this than have to special-case every website that clobbers the whole DOM tree as I encounter them.

>  By the way, if you don't need to access the iframe node in other commands, you can just store it in a local variable
Neat!

**Comment by zeorin** [comment]
> I don't think call `reattachCmdlineIframe` 60hz in every tabs is a good idea.

While I didn't actually have any noticable performance impact due to that approach, I've since switched to using `MutationObserver`:

`~/.config/tridactyl/restore-tridactyl-commandline.js`:

```javascript
const cmdlineIframe = document.getElementById("cmdline_iframe");

let { parentElement } = cmdlineIframe;

const mutationObserver = new MutationObserver((records, mutationObserver) => {
  if (!parentElement.isConnected) {
    mutationObserver.disconnect();
    parentElement = document.documentElement;
    mutationObserver.observe(parentElement, { childList: true });
  }

  if (
    records.some(({ removedNodes }) =>
      Array.from(removedNodes).includes(cmdlineIframe),
    )
  ) {
    parentElement.appendChild(cmdlineIframe);
  }
});

mutationObserver.observe(parentElement, { childList: true });
```

`~/.config/tridactyl/tridactylrc`:

```vim
autocmd DocStart .* js -r restore-tridactyl-commandline.js
```

@bovine3dom, perhaps this behaviour could be added to Tridactyl, configurable behind a per-site option (that defaults to enabled)?
