### ISSUE TITLE
cannot source tridactylrc in flatpak

### ISSUE THREAD

**Issue by hoshsadiq** [tridactyl/tridactyl#4815]
I'm running firefox in flatpak, and i'm trying to source my tridactylrc in `~/.config/tridactyl/tridactylrc`. Doing `:viewsource ~/.config/tridactyl/tridactylrc`, also tried the full path, but nothing. 

-   Tridactyl version (`:version`): 1.23.0pre6803-89a7e613

-   Firefox version (Top right menu > Help > About Firefox): `118.0.2 (64-bit)`

-   Config (in a new tab, run `:viewconfig --user`, copy the url and paste it somewhere like gist.github.com):
    ```
    {"update":{"lastchecktime":1698840490003},"configversion":"2.0"}
    ```

-   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
Insert tridactylrc contents between the backticks
```

Firefox is able to access the file when I navigate to `file:///home/<user>/.config/tridactyl/tridactylrc`

**Comment by hoshsadiq** [comment]
Worth noting, I've had to manually expose that directory via KDE's built-in FlatSeal alternative.

**Comment by bovine3dom** [comment]
Have you followed https://github.com/tridactyl/tridactyl#containerizedsandboxed-firefox-installations ?

**Comment by bovine3dom** [comment]
more basic potential issues:

- the command is :source, not :viewsource :)
- what's the output of `:native`? What about `:! ls ~`?

**Comment by hoshsadiq** [comment]
> Have you followed [tridactyl/tridactyl#containerizedsandboxed-firefox-installations](https://github.com/tridactyl/tridactyl#containerizedsandboxed-firefox-installations) ?

I did! But `:native` still complains that it's not installed, though the permissions have definitely been set up.

```
$ flatpak permission-show org.mozilla.firefox
Table             Object            App                 Permissions                  Data
notifications     notification      org.mozilla.firefox yes                          0x00
background        background        org.mozilla.firefox yes                          0x00
webextensions     tridactyl         org.mozilla.firefox yes                          0x00
desktop-used-apps application/x-rpm org.mozilla.firefox org.kde.discover,1,3         0x00
desktop-used-apps text/plain        org.mozilla.firefox nvim,1,3                     0x00
```

> the command is :source, not :viewsource :)
Ah sorry, that's a copy paste error. I was actually doing `:source`.

**Comment by hoshsadiq** [comment]
I do wonder, why is native needed to source from the filesystem considering Firefox has access to the rc?

**Comment by hoshsadiq** [comment]
Seems like native messaging might not be supported in Flatpak just yet as a PR is still pending: https://github.com/flatpak/xdg-desktop-portal/pull/705

**Comment by hoshsadiq** [comment]
I gave up. Went back to the rpm build. Had a few other issues with Firefox in Flatpak.

**Comment by gebner** [comment]
@hoshsadiq FWIW, you can install the native messenger inside the sandbox in the meanwhile: https://github.com/tridactyl/native_messenger/pull/70
