### ISSUE TITLE
Add functions to move cursor up and down

### ISSUE THREAD

**Issue by jumper047** [tridactyl/tridactyl#4831]
Hi, Emacs user here:)!
Can you add functions `next_line` and `previous_line` to move cursor up and down inside text fields? I'm totally unprofessional in browser-related stuff, so can't do it myself (though I tried)

**Comment by bovine3dom** [comment]
Hi :)

This would be possible but would require some maths. Would need to add a function like this one: https://github.com/tridactyl/tridactyl/blob/ff696b5cc7dde4f3e24ab55df4e0bbfc7d5aa1e9/src/lib/editor.ts#L209

As a workaround, you could `bind --mode=insert [key map] !s xdotool key Up` provided that you have `:native` installed and working and `xdotool` in your PATH

**Comment by GHolk** [comment]
I have these features in my tridactylrc, see its [line 96](https://git.ccns.io/gholk/dot-public/-/blob/d89c7a1aa01fd43453a2de50a4a736c785df00f8/tridactylrc#L96) and 306.
Feel free to copy my code to draft a pr.

**Comment by jumper047** [comment]
Thank you @GHolk ! Your functions were very helpful!
