### ISSUE TITLE
`hint -pipe` shows all default hints, not just those that matches given selector

### ISSUE THREAD

**Issue by natrys** [tridactyl/tridactyl#4833]
Possible regression of 1da778ba56371c7b3063b2f8ade8fb5b1b2cdfc8 which enables default hints for everyone except for "-c" flag.

It might be more sensible to keep adding default hint behaviour disabled by default, and only enable it if new flag "-C" is explicitly given.

**Comment by bovine3dom** [comment]
Fixed in #4842, thanks @petoncle!
