### ISSUE TITLE
Slack started hijacking <C-6>

### ISSUE THREAD

**Issue by maricn** [tridactyl/tridactyl#4870]
-   Brief description of the problem: Can't use the default `tab #` shortcut (`<C-6>`) because some web pages stop propagating events once they consume it.

-   Steps to reproduce:

    1. Open browser with at least two tabs.
    2. Navigate to Slack app.
    3. Press ctrl+6.
    4. Observe nothing happens.

-   Tridactyl version (`:version`): `1.23.0`

-   Firefox version (Top right menu > Help > About Firefox): `120.0.1 (64-bit)`

-   URL of the website the bug happens on: `https://app.slack.com/client/*`

-   Config (in a new tab, run `:viewconfig --user`, copy the url and paste it somewhere like gist.github.com): https://gist.github.com/maricn/a86720274072a9899d747524e8aacd84

-   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist): https://github.com/maricn/dotfiles/blob/main/.config/tridactyl/tridactylrc

```
# only relevant is the default:
bind --mode=browser <C-6> tab #
```

- What I have tried:
  - Looking into the wiki (https://github.com/tridactyl/tridactyl/wiki/Slack) and issues for similar problems
  - Setting `permissions.default.shortcuts` to `2`. However, this always puts highest priority on browser shortcuts, meaning all other keyboard shortcuts, suck as Cmd+K default to firefox behavior, ie. focus the address bar instead of webapp functionality.
  - Writing Violentmonkey userscript to filter when ctrl+6 is pressed and issue `e.stopPropagating()`, however this also stops the propagation to tridactyl if i understand that right. Or maybe I'm not attaching my listener to the right element? 🤷 

- **My question**: is there any recommended way to override the webpage keyboard event listeners, so they are always caught exclusively by tridactyl?

**Comment by bovine3dom** [comment]
`bind <C-6> tab #` should get around it. `bindurl [slack] ...` if you want to be a bit neater.

There's a Firefox bug/feature where websites can override browser binds.
