### ISSUE TITLE
Add partial autocomplete

### ISSUE THREAD

**Issue by JasonGrace2282** [tridactyl/tridactyl#4887]
It would be nice to have partial autocomplete work, like if I wanted to type `colourscheme --url xyz` I could type in `col` hit tab to navigate to the correct suggestion and hit some special key (enter maybe?) and have it autocomplete to `colourscheme`.

**Comment by bovine3dom** [comment]
I think this already exists and is bound to space by default

Please reopen this issue if I've misunderstood :)
