### ISSUE TITLE
Launch other sidebar (that isn't tridactyl) with browser.sidebarAction.open()

### ISSUE THREAD

**Issue by hejops** [tridactyl/tridactyl#4897]
I know that calling `browser.sidebarAction.open/close/toggle()` from within tridactyl performs the corresponding action on our sidebar, but can it be called to open/close/toggle some other sidebar that isn't ours? This was once mentioned in the context of treestyletab (https://github.com/tridactyl/tridactyl/issues/377#issuecomment-380778169 -- and yes, I'm thinking of doing this to `open` TST).

**Comment by bovine3dom** [comment]
As far as I know, it's impossible without changes in Firefox. You need a "user action" to open/close sidebars. Messages from other extensions can't count as user actions.

The whole concept of "user action" should be abolished but I suspect Mozilla would disagree with me :)

**Comment by bovine3dom** [comment]
Your best bet is to use `:bind [whatever] !s xdotool [TST keybind]`.

**Comment by hejops** [comment]
Yeah I didn't want to reach for `xdotool` unless there wasn't a more native way to do it. Good to know then, thanks for clearing it up!
