### ISSUE TITLE
[Feature Request] `[n]<C-6>` should execute `:tab n`

### ISSUE THREAD

**Issue by oredaze** [tridactyl/tridactyl#4898]
Switching to the last accessed tab with `tab #` is cool and all, but in vim it takes a count, which is the buffer number. As far as I can tell it's not possible here?

An example I was trying to create:
press `<Tab>`  to `tab #`
press `3<Tab>`  to `tab 3`

------------------------------------------
**ALTERNATIVE REQUEST:**

If that is not something you would like to support I have a different request:
bind single numbers to commands:
`bind 3 tab 3` or some such
Of course that would disable counts for everything (which I don't really use)

This is actually faster for typing, but it goes against vim muscle memory and you can only bind 10 tabs with it....

**Comment by bovine3dom** [comment]
In normal mode, `3b<Enter>` takes you to the third tab, as does `3gt`. `b3<Enter>` also works, provided you wait for the command line to open after pressing `b`.

I don't think I fully understand what you're trying to do :)

**Comment by oredaze** [comment]
That's what I am doing now, but my request saves you pressing Enter in the `b` case. In the `gt`case you can't press it to go back to `#` like in the case of `tab #`
Also it's vim compatible behavior.

**Comment by oredaze** [comment]
It is up to you to decide it if's worth it. It will be a minor improvement. I can live without it.

**Comment by bovine3dom** [comment]
It's worth it enough that I would merge a PR that added it :)

**Comment by oredaze** [comment]
If only I could code... Maybe I should learn :)

**Comment by bovine3dom** [comment]
You can do it in Tridactyl currently, by the way, without needing to change any code for anyone else: `:bind <C-6> js -d€ tri.excmds.tab(JS_ARGS.join("") != "" ? JS_ARGS.join("") : "#")€`

**Comment by oredaze** [comment]
Thanks so much.
