### ISSUE TITLE
inbox.gmail.com doesn't work as expected

### ISSUE THREAD

**Issue by lucaslcode** [tridactyl/tridactyl#490]
The emails don't expand when you choose them in hint mode.

**Comment by bovine3dom** [comment]
Works for me on both the old gmail and the new fangled ugly one, provided that I choose the hint that is above the subject.

**Comment by lucaslcode** [comment]
This is Inbox for gmail <https://inbox.gmail.com>, not the usual gmail.

**Comment by bovine3dom** [comment]
Oh, wasn't paying attention, sorry. I'll take another look.

**Comment by lucaslcode** [comment]
Extremely quick investigation tells me tridactyl doesn't work with google's [jsaction library ](https://github.com/google/jsaction) which is being used.

**Comment by bovine3dom** [comment]
They're going to close it down in March. https://www.fastcompany.com/90235559/inbox-googles-playground-for-email-innovation-is-going-bye-bye

Problem solved, I guess?

**Comment by bovine3dom** [comment]
Yup, that approach worked well - wait long enough, and Google will close the service. Perhaps we should adopt it for #904 too.

**Comment by lucaslcode** [comment]
Brutal 😆😆
