### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#491]
Similarly to #481 and relevant to #200, we should allow users to import their own themes and document the variables we choose in #481 and what they do.

The easiest way programmatically would be to just read files from disk and save them to the local storage.

It might be more user friendly to have a theme tab on #314 that allows people to paste things in / load from disk via a file picker like the RC tab.

**Comment by glacambre** [comment]
Will this still be needed once https://github.com/cmcaine/tridactyl/pull/609 is merged?

**Comment by bovine3dom** [comment]
I think so - ideally there'd be a .config/tridactyl/themes folder that would magically work with `colours`.
