### ISSUE TITLE
Holding arrow keys in google sheets

### ISSUE THREAD

**Issue by bk322** [tridactyl/tridactyl#4955]
-   Brief description of the problem:

-   Steps to reproduce:

    1.  open any google sheet
    2. hold arrow key

   The current cell should be moving, and it used to work. But starting about a week ago it stopped to move.

-   Tridactyl version (`:version`): 1.24.0

-   Firefox version (Top right menu > Help > About Firefox): 124.0.1

-   URL of the website the bug happens on: https://docs.google.com/spreadsheets

-   Config (in a new tab, run `:viewconfig --user`, copy the url and paste it somewhere like gist.github.com):

-   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
Insert tridactylrc contents between the backticks
```

-   Operating system:
-   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:
-   Unix-like only:
    -   `:native` less than 0.2.0: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:
    -   `:native` at least version 0.2.0: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main` in a terminal:

**Comment by bovine3dom** [comment]
I can't reproduce this, it works fine for me. Maybe it's the result of some code that they're A/B testing?

**Comment by bk322** [comment]
Thanks for checking it up.

I leave only tridactyl in private window, open empty google sheet with private window and moving current cell with holding arrow keys works very slowly, even with `blacklistadd docs.google.com` (I understand that this sounds strange).

If I disallow tridactyl to run in private window, I open the same empty google sheet in private window, and holding arrow keys are snappy as before.

**Comment by bovine3dom** [comment]
Have you looked at `:help superignore`? It totally disables Tridactyl so it should fix your issue just as your private window technique does.
