### ISSUE TITLE
open: option to show bookmarks before history items

### ISSUE THREAD

**Issue by sweenu** [tridactyl/tridactyl#4966]
I would like to be able to always have my bookmarks appear first, before any history items when I do `:open` or `:tabopen`.
I searched pretty thoroughly and didn't find any option or issues on that. Have I missed it?

**Comment by bovine3dom** [comment]
`:set bmarkweight 10000000` (any big number will do)

https://tridactyl.xyz/build/static/docs/classes/_src_lib_config_.default_config.html#bmarkweight

**Comment by sweenu** [comment]
So I did miss it! Thank you!
I think I missed it because I didn't quite get what was meant by "page views pretend they have", you need to understand the underlying mechanism for ordering. Now I get it. Thanks.
