### ISSUE TITLE
Breaks tanstack.com

### ISSUE THREAD

**Issue by ysulyma** [tridactyl/tridactyl#4980]
https://tanstack.com/ breaks (is completely blank) when I use Tridactyl

- Tridactyl version 1.24.1
- Firefox version 125.0b8 (64-bit)

**Comment by bovine3dom** [comment]
Hi, sorry, I just saw this. Have you tried `:seturl [url] noiframe true` and if that doesn't work, `:seturl [url] superignore true`?

The page you linked to loads fine for me :)

**Comment by ysulyma** [comment]
weird, it was broken before (on multiple machines), but works for me now
