### ISSUE TITLE
proposal: Use quickmarks with open command

### ISSUE THREAD

**Issue by Brixy** [tridactyl/tridactyl#4984]
`tridactyl version: 1.24.1`

Thanks a lot for Tridactyl. I have been using it for a long time and just love it.

Yet, I have not been following its development closely. So I don't know whether this suggestion makes sense or has already been discussed somewhere else.

I use quickmarks extensively, but they might be more effective in combination with `open`:

`o<quickmark><ENTER>`

These could be the advantages:

- You could have multi-letter quickmarks, like `gh` for GitHub.
- You could use the same quickmarks as Firefox’s bookmark keywords/`SHORTCUTURL`s. (Firefox allows multi-letter keywords.)
- You could use the same quickmarks as `searchurls`:

	`:open ddg` would open the DuckDuckGo quickmark,

	`:open ddg <My search term>` would open DDG and start a search for the search term provided.

- Same number of keystrokes for single letter quickmarks as before:

	`goX` vs `oX<ENTER>`.

- `tabopen` etc. just work as for regular urls.
- It could be possible to support opening multiple quickmarks in separate tabs.

Thanks a lot!

**Comment by bovine3dom** [comment]
Sorry, I thought I had answered this. Run e.g.

```
:bind N js tri.excmds.gobble("<CR>", "js -p tri.config.set('searchurls', JS_ARG, window.location.href)")
```

(where <CR> means Enter) then

1. go to site you want
2. `N[quickmark keys]<CR>`
3. `t[quickmark keys]<CR>` opens your site

**Comment by Brixy** [comment]
Thank you very much, @bovine3dom. It's very impressive to see how flexible tridactyl is.

My idea was a proposal for a general change, which might have some advantages. But it would probably change too much. So let me just close this issue.
