### ISSUE TITLE
autocmd markaddglobal causes markjumpglobal to open same url in new tab

### ISSUE THREAD

**Issue by UreshiiPanda** [tridactyl/tridactyl#5008]
I have been trying to find a way to deal with the fact that markaddglobal is bound to URLs instead of to tabs. I have set autocmd's with DocLoad (and DocStart) for certain URLs with the markaddglobal command but then when using markjumpglobal, Tridactyl will open a new tab with the exact same url instead of jumping to the URL which is already open in another tab.

Using DocLoad will at least show the "global mark X set" but DocStart will not set the mark at all. But DocLoad will still "jump" to the url by opening the same url in a new tab

Steps to reproduce
1. autocmd DocLoad https://claude.ai/chat* markaddglobal C
2. open https://claude.ai/chat in a new tab
3. see that Tridactyl sets the global C mark on that url
4. switch tabs then try to use 'C to jump to that marked url
5. see that Tridactyl opens a new tab with the exact same url as the already-marked url

Env: 
MacOS Ventura
FireFox 127.0b9 (64-bit)
Tridactyl 1.24.1

**Comment by bovine3dom** [comment]
Hi, thanks for filing this issue. This is a bit of a weird way to use global marks - they persist between browser restarts so you only need to run `:markadd C` once and it will stay forever.

Still, this behaviour you're seeing shouldn't happen. I'm away from my computer at the moment but I'll try to investigate it when I get back :)

**Comment by UreshiiPanda** [comment]
Agreed it is weird, the reason for trying to wrap it in an autocmd is because I rarely restart my browser, and this scenario keeps happening to me:  I global-mark (let's say with X) a page then I navigate within that page to some other url on that same domain, then I switch tabs to go do something else, then I try to use my global-mark X but I forgot that the url changed slightly since I navigated after setting the global mark, so then mark X just causes the older url to open in a new tab. This has been my biggest issue with Tridactyl but otherwise it's an amazing plugin, I want to find a way to get marks to hold onto the general domain or the tab itself so that I don't have to worry about page-navigation messing with my marks.

But in the instance of this issue I opened, Tridactyl is actually opening up the exact same url in a new tab.

**Comment by bovine3dom** [comment]
Have you tried e.g. `:bind 'C tab https://claude.ai/chat` ?

**Comment by bovine3dom** [comment]
> Still, this behaviour you're seeing shouldn't happen. I'm away from my computer at the moment but I'll try to investigate it when I get back :)

`:autocmd DocLoad https://www.bbc.com/news* markaddglobal C` works fine for me so I think there must be something specific to Claude, it's probably subtly redirecting somehow

**Comment by UreshiiPanda** [comment]
that `:bind 'C tab https://claude.ai/chat` works very close to what I was looking for so I'll roll with that for now. Appreciate the help!
