### ISSUE TITLE
Define exclude list or multiple proxy without container

### ISSUE THREAD

**Issue by Monirzadeh** [tridactyl/tridactyl#5015]
# Add more than one Proxy without need to containerize website

currently we can set a proxy in settings with this command
```
proxyadd proxya sock5://127.0.0.1:8080
set proxy proxya
```
but we can't exclude specific address to not use that proxy or use any other specific proxy
we need something like this
```
set proxy proxya
autocontain -s [url regex] none [some magic proxy name that means no proxy]
```
this feature is critical because you can't accesses local ip or any other url that need to direct connection or specific proxy

**Comment by bovine3dom** [comment]
`:autocontain -s [url] [container] none` added, will appear whenever I next release a beta :)

**Comment by bovine3dom** [comment]
yeah, `:autocontain -s [url] none none` works fine :)
