### ISSUE TITLE
Broken site 

### ISSUE THREAD

**Issue by lordgrenville** [tridactyl/tridactyl#5023]
Tridactyl version: 1.24.1pre7027-eb1141b8
Firefox version: Mozilla Firefox 128.0
Operating system: mac

[This website](https://guywaldman.com) breaks tridactyl in the most complete way I've ever encountered. `seturl guywaldman.com noiframe true` and `seturl guywaldman.com allowautofocus true` didn't help.

Can share my personal config but fairly sure that it is unrelated.

In general, I'm just curious as to how this happens and ways to mitigate it.

Thanks for all your work!

**Comment by bovine3dom** [comment]
Have you tried `seturl guywaldman\.com superignore true`?

**Comment by lordgrenville** [comment]
Thanks for your help! I checked with a new profile, and it works, as you say. I'm very confused.

Here is my [personal config](https://gist.github.com/lordgrenville/f6327e0a0adfe8b36a30ca3cc8b5e8ee) and `~/.config/tridactyl/tridactylrc`:

```
seturl localhost superignore true
set modeindicator false
bind <Space> scrollpage 0.75
unbind A
unbind d
unbind <C-f>
bind q tabclose
colourscheme shydactyl
bindurl wikipedia\.org F hint -W tabopen -b
bindurl wikipedia\.org f hint -W open
seturl wikipedia\.org mouse_mode
unbind --mode=visual q

" Comment toggler for Reddit, Hacker News and Lobste.rs
bind ;c hint -Jc [class*="expand"],[class*="togg"],[class="comment_folder"]

" Only hint search results on DDG
bindurl ^https://duckduckgo.com f hint -Jc [data-testid="result-title-a"]
bindurl ^https://duckduckgo.com F hint -Jbc [data-testid="result-title-a"]
unbind w
bind w fillcmdline tabopen wikipedia
autocmd DocStart ^http(s?)://www.reddit.com js tri.excmds.urlmodify("-t", "www", "old")
```

**Comment by bovine3dom** [comment]
Your subconfigs look kind of messed up https://gist.github.com/lordgrenville/f6327e0a0adfe8b36a30ca3cc8b5e8ee#file-config-json-L194-L228

Would you mind following gholk's instructions here https://github.com/tridactyl/tridactyl/issues/4336#issuecomment-1209578534 to get a short version of your config to paste into your RC file, delete/comment out the lines you don't understand then run `:santise tridactyllocal` to wipe your Tridactyl config?

**Comment by lordgrenville** [comment]
Worked perfectly. And now I know how to do a reset and clean start in future. Thanks!
