### ISSUE TITLE
Question or Feature Request: Switching tabs by Pressing: b #  -- without needing to press RET

### ISSUE THREAD

**Issue by daffydock** [tridactyl/tridactyl#5028]
The description says it all. I switch tabs very often and find having to press RET [ENTER] to be unnecessary.
When wanting to switch tabs, I press b # and then RET. That is the standard behaviour. However, I wanted to know if I could be able to streamline this, or if there a way I can change it myself through settings. I do not know how I would go around doing this. I checked through the issues but could not find if this had been brought up or addressed before. Apologies if I missed it. 

Is there a way to simply press b # as to switch to X tab?

Thank you for any feedback. 
Cheers.

**Comment by bovine3dom** [comment]
You can do this already with `[n]gt`, e.g. `5gt` takes you to tab 5.

If you want to bind it to b just do `:bind b tabnext_gt`. You will still have access to an interactive tab switcher with `B`

**Comment by daffydock** [comment]
Thanks @bovine3dom . I apologize, I should have been more clear, since by now, I take my setup for granted. 

Using CSS, I have removed the entire UI from FF, with only the address bar showing when  the mouse hovers near the top, or press `Alt +D` or `Ctrl + L`, otherwise, it is all hidden. 

As such I cannot see the actual tabs I have, the order or even the number of tabs. Pressing `b`  is essentially the only way to see the tabs and their number. So using `[n]gt` is not ideal as I may not know a tab's number. 

Doing what you suggest would imply me knowing or seeing those tabs. Hence I still appreciate seeing a tab switcher before switching, hence my question. Furthermore `[n]gt` does not work with `b `or `B` activated. In that work flow, I would have to activate the tab switcher, see the number, deactivate the tab switcher and then do `[n]gt` technically more complex than pressing a number and `RET`.  

`Shift J` and `Shift K` suffice for switching to adjacent tabs.

**Comment by bovine3dom** [comment]
I see your problem. Have you seen https://github.com/tridactyl/tridactyl/issues/4854 ? Would that suffice?

The trouble with your idea as you have described it is that if you have >9 tabs open, selecting tab 10 conflicts with tab 1, etc.

**Comment by daffydock** [comment]
Funny. After I wrote my last comment, and while doing errands, it came to me, the exact same criticism you mentioned. I usually do not have that many tabs open so it escaped my mind, but it is an obvious problem when the time does come when there are say, 11 open tabs. I fully agree, it is far from optimal a take to the problem. 

Re: #4854 
I had briefly tried Surfkeys before sticking with Trydactyl and that feature seemed like a killer feature to have. I will definitely give it a try. Thank you for pointing it out. 

Latest script is:
https://github.com/Chic-Tweetz/tridactyl-stuff/blob/main/hinttabs-obscured/hinttabs.js  

Only issue, if you would be so kind to help, is that I am not sure how to fun it. Was reading the bit of documentation on `JS` and looked up other issues regarding running `JS` and `source` and I am still not sure how to run it. I usually get an error or simply nothing happens. 

Downloaded the file too, and tried running it locally as per the `Help` but it did not work for me. Think the best path now is to simply ask you. Since clearly, I am missing something. Any help would be appreciated.

**Comment by Chic-Tweetz** [comment]
Hi, @daffydock, I'm the one responsible for that script, and the lack of instructions!

[That latest script](https://github.com/Chic-Tweetz/tridactyl-stuff/blob/main/hinttabs-obscured/hinttabs.js) can be copy & pasted straight into Tridactyl's command line to create an alias, `:hinttabs`, which will run the `js` command.

You can then use `:bind [key(s)] hinttabs` to show tabs from the current window, or `:bind [key(s)] hinttabs -a` to show tabs from all windows.

Hope that helps!

**Comment by daffydock** [comment]
LOL
Hi, @Chic-Tweetz I spend 10-20 minutes trying to source the JS file in a multitude of ways. When you said, you could enter the JS in the command line, it did not occur to me to Copy/Paste the entire code, at face value, literally, in the command line. With that knowledge, I installed and set it up to my preferred keys in 5 seconds.
I found it funny. I appreciate it. 

It is nice to have this usability in my workflow and minimal setup, and I thank you for creating it. As I had said before, I liked Surfkey's hint tab option, so it is great to have a comparable tool in tridactyl.

@bovine3dom I think this addresses my issue, thank you to both of your for your help on this.  
I will be closing the issue. 

Cheers!

**Comment by Chic-Tweetz** [comment]
@daffydock Glad you got it working! I haven't made it especially obvious how it's supposed to work. I should probably add a little readme actually.
