### ISSUE TITLE
tridactyl not working properly all of a sudden

### ISSUE THREAD

**Issue by geomydas** [tridactyl/tridactyl#5038]
Tridactyl not working propery. Librewolf, Linux Mint. It just happened out of nowhere. I was using my PC and then I power it on and for some reason tridactyl doesnt seem to work properly. I've removed the extension twice, I've tried updating the extension, I rebooted my pc to no avail. It just happened of all of a sudden. Side note, pressing Win and then searching for something got laggier aswell since this happened . i've tried the troubeshooting guide to no avail. i've disabled resistfingerprinting in about:config to no avail

**Comment by geomydas** [comment]
also, pressing k either makes your scroll down instead of up and tab through an element

**Comment by bovine3dom** [comment]
Do you close this because you resolved your issue? What steps did you take to fix it?

**Comment by geomydas** [comment]
I closed this because I resolved my issue. Turns out, I have my screen reader enabled lol
