### ISSUE TITLE
Can't fold comment on new.reddit.com

### ISSUE THREAD

**Issue by TheToxicToast** [tridactyl/tridactyl#5039]
-   Brief description of the problem:
Can't click the fold comment vertical line in new.reddit.com
-   Steps to reproduce:
go to a new.reddit.com comment section, when using f it can't find the vertical clickable line with folds a comment

-   Tridactyl version (`:version`):
1.24.1
-   Firefox version (Top right menu > Help > About Firefox):
Floorp 11.17.8
-   URL of the website the bug happens on:
new.reddit.com
-   Config (in a new tab, run `:viewconfig --user`, copy the url and paste it somewhere like gist.github.com):
https://gist.github.com/TheToxicToast/363602cafcea7597965a9a3fbd3788ae
-   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):
none

**Comment by bovine3dom** [comment]
the `div` has a `click` event but it doesn't seem to get caught by this line here https://github.com/tridactyl/tridactyl/blob/eb1141b8c89472225a45c8c2d39cc8bc2ab26ee5/src/lib/dom.ts#L465

But I can't find any site that has JS hints on at the moment, so I'm wondering if it's totally broken? I don't think I have seen them for months

**Comment by bovine3dom** [comment]
bumping this to P2 because it looks like it doesn't work on any websites. even though no-one seems to have noticed...

removing this guard "fixes" it

https://github.com/tridactyl/tridactyl/blob/eb1141b8c89472225a45c8c2d39cc8bc2ab26ee5/src/lib/dom.ts#L438-L440

but after activating the "country specific" toggle on duckduckgo, you can't reenter hint mode I get the error

`# controller in excmd: TypeError: thing.getBoundingClientRect is not a function`


Any ideas @glacambre ? I think you wrote the code initially :)

**Comment by glacambre** [comment]
Hinting on reddit seems to work fine for me:
![20240907_06h45m10s_grim](https://github.com/user-attachments/assets/4c4a8852-c923-4a11-9f14-85609da5877d)
I can press `fs` and `sx` as many times as I want to fold/unfold the same comments.
I don't have any issues with duckduckgo's country toggle either. I'm on tridactyl `1.24.1pre7027-eb1141b8` / firefox `128.0` (don't judge).
Do you have anything about CSP in the console?

**Comment by TheToxicToast** [comment]
> Hinting on reddit seems to work fine for me

I was on the old Reddit site (new.reddit.com)

**Comment by glacambre** [comment]
old.reddit.com works pretty well too:
![20240907_07h00m27s_grim](https://github.com/user-attachments/assets/2234d989-7a23-48a4-ae99-5f6f0736721d)
`fm` and `fp` let me fold/unfold messages to my heart's content.

**Comment by bovine3dom** [comment]
@glacambre I'm talking about the JS hints you added years ago and I later styled to make grey

I haven't seen them on any websites for months or maybe years

They reappear if I remove this check.


```patch
diff --git a/src/lib/dom.ts b/src/lib/dom.ts
index 97fcbcee..f839861f 100644
--- a/src/lib/dom.ts
+++ b/src/lib/dom.ts
@@ -435,9 +435,9 @@ export function registerEvListenerAction(
     // We're only interested in the subset of EventTargets that are Elements.
-    if (!(elem instanceof Element)) {
-        return
-    }
+    // if (!(elem instanceof Element)) {
+    //     return
+    // }
```

`JF` is a hint that can't be clicked without this patch for me. I don't see any grey hints on your screenshots

![image](https://github.com/user-attachments/assets/07186034-cc77-4411-9a5b-2afbb8868d4f)

**Comment by glacambre** [comment]
@bovine3dom oh, yeah, sorry 🤦.
Adding a console log point on the if like this:
```js
elem, elem.__proto__.__proto__.__proto__, Element.prototype, elem.__proto__.__proto__.__proto__ == Element.prototype
```
Shows something quite strange, for all element. Here's an example
```
<a class="zcm__link dropdown__button js-dropdown-button"> 
ElementPrototype { getAttributeNames: getAttributeNames(), getAttribute: getAttribute(), getAttributeNS: getAttributeNS(), toggleAttribute: toggleAttribute(), setAttribute: setAttribute(), setAttributeNS: setAttributeNS(), removeAttribute: removeAttribute(), removeAttributeNS: removeAttributeNS(), hasAttribute: hasAttribute(), hasAttributeNS: hasAttributeNS(), … }
ElementPrototype { getAttributeNames: getAttributeNames(), getAttribute: getAttribute(), getAttributeNS: getAttributeNS(), toggleAttribute: toggleAttribute(), setAttribute: setAttribute(), setAttributeNS: setAttributeNS(), removeAttribute: removeAttribute(), removeAttributeNS: removeAttributeNS(), hasAttribute: hasAttribute(), hasAttributeNS: hasAttributeNS(), … }
 false
```
So:
- It's an `<a>` element
- It's a child of `ElementPrototype`
- Which looks a lot like the prototype of `Element`
- ... But their prototypes aren't the same?

I guess `Element`'s identity used to be preserved across the extension/page boundary when exporting a function to the page's context, and now it's not. So the `Element` we're testing `elem` against is actually an `Element` from the extension's context, whereas `elem` is a child of the page's `Element`.

The identity of the prototype chain not being preserved makes the `if` worthless in terms of security checks, so we could probably indeed remove it. But `addEventListener` can also be called on things that aren't elements (for example, `window` objects), so perhaps we still need to check that `elem` is an element. My tests from the JS console show that `if (!(elem instanceof window.Element)) {` might do the trick. I don't have a tridactyl setup ready to test this though, can I let you handle it?

**Comment by bovine3dom** [comment]
Works a treat, thanks @glacambre :heart:

**Comment by glacambre** [comment]
And thank you for keeping on maintaining Tridactyl after all these years :)
