### ISSUE TITLE
Content of the file shows a big html one-liner on Exercism

### ISSUE THREAD

**Issue by cassepipe** [tridactyl/tridactyl#5067]
-   Brief description of the problem:

On any [Exercism exercise page such as this one](https://exercism.org/tracks/elixir/exercises/hello-world/edit) when you `<C-i>`
in the editor, the file appear like one big line of HTML

It seems it is because is the editor implement a `<div>` for each line.

If you inspect the editor main `<div>` (the one with class `cm-content`) then try to use it console and print its `innerText` it looks fine so maybe the issue comes from using something thatn innerText

I  should mention that it is not a problem with latest firenvim.

-   Steps to reproduce:

   Install Tridactyl and go to this [page](https://exercism.org/tracks/elixir/exercises/hello-world/edit) and try to `Ctrl+i` in the editor

-   Tridactyl version 1.24.1

-   Firefox version is 131.0.3 

-   URL of the website the bug happens on, for example : https://exercism.org/tracks/elixir/exercises/paint-by-number/edit

-   Default post-install config

-   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist): No such file

**Comment by cassepipe** [comment]
So it seems that Tridactyl is using `getEditor` from the `editor-adapter` repo : 
https://github.com/glacambre/editor-adapter/blob/0f4b85923d5dbc778dc4faf840181c8fdbdd32cb/index.js#L423

It seems to be trying to see if it's any of those complex editors `[AceEditor, CodeMirrorEditor, MonacoEditor]` else it returns a `TextAreaEditor` object.

The `TextAreaEditor` constructor cares about the prefer html option :
https://github.com/glacambre/editor-adapter/blob/0f4b85923d5dbc778dc4faf840181c8fdbdd32cb/index.js#L244

Or that is indeed an option that's passed by Tridactyl when it uses `getEditor` so it seems to be the issue. (first link above)

Is there any reason why that option was chosen ?

**Comment by bovine3dom** [comment]
Thanks for filing this and for looking into it. Because of your sleuthing I've found a duplicate issue #3900 so I'm closing in favour of that
