### ISSUE TITLE
Mode indicator to indicate more than mode

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#507]
E.g, it could go purple in private windows, or get an underline with the colour of the container you're in.

(Obviously we should do it with variables/class names as per #481).

Related to #53.

**Comment by bovine3dom** [comment]
https://github.com/caputchinefrobles/tridactyl/commit/00af1516fcf7d6534758d67134f6dd0b29f78e99 will save me some precious thinking if I ever get around to doing this.

(shout out to @atrnh for doing something pretty cool in general with that fork)

**Comment by bovine3dom** [comment]
Private window support added in 7429f8c.

**Comment by antonva** [comment]
Basic container colour added in #683 
Haven't looked at adding variables/classes yet.

**Comment by bovine3dom** [comment]
There's also `set modeindicatorshowkeys true`.
