### ISSUE TITLE
Using :set to add a non-default key breaks :apropos completions

### ISSUE THREAD

**Issue by Chic-Tweetz** [tridactyl/tridactyl#5076]
-   Brief description of the problem:

Adding a non-default config key using `:set` breaks `:apropos` settings completions.
`:apropos` will still work with `-a`, `-b`,  or `-e` flags.
It may be intended for `:set` to only work with default keys, but I use several custom ones and have figured out it was causing apropos to not work.

-   Steps to reproduce:

    1. create a new config key using set, eg `:set break stuff`
    2. try to use `:apropos` - there will be errors in the console

-  Potential source of issue and fix:

In line 123 of completions/Apropos.ts:

```
Object.keys(settings)
    .filter(x =>
        (x + default_config.getMember(x).doc)  // line 123: default_config.getMember(x) is undefined
            .toLowerCase()
            .includes(query),
    )
```

Returning a falsy value if `default_config.getMember(x)` is undefined will discard non-default keys instead of throwing an error. Switching to an optional chaining operator seems to have fixed this for me:

```
(x + default_config.getMember(x)?.doc)
```

-   Tridactyl version: 1.24.1pre7072-811bde55

-   Firefox version : 131.0.3 (aarch64)

-  Config/rc: this will happen with default settings + one non-default key, so just this is enough:

```
set break stuff
```

**Comment by bovine3dom** [comment]
Thanks for reporting this, `apropos` has not worked for people seemingly randomly for years and I guess this is probably why :)

**Comment by Chic-Tweetz** [comment]
No problem! I like an issue that can be fixed with a single question mark
