### ISSUE TITLE
Contributing.md has a bad link

### ISSUE THREAD

**Issue by Blourvim** [tridactyl/tridactyl#5078]
### Problem Summary
In the `CONTRIBUTING.md` file, the link to "Queensberry Rules" in the Code of Conduct section is outdated and redirects to a "Lexical Data for AI" sales page instead of the intended definition.

### Details
- **File**: [`contributing.md`](https://github.com/tridactyl/tridactyl/blob/811bde558ab3306aeb2522936d8d8a29eebee40b/contributing.md)
- **Current Link**: [https://en.oxforddictionaries.com/definition/queensberry_rules](https://en.oxforddictionaries.com/definition/queensberry_rules)
- **Issue**: Redirects to [https://languages.oup.com/](https://languages.oup.com/), which does not contain definition for  "Queensberry Rules"
  
### Suggested Fix
Can either link here [https://www.oxfordlearnersdictionaries.com/definition/english/queensberry-rules](https://www.oxfordlearnersdictionaries.com/definition/english/queensberry-rules), which is the new oxford dictionary link
Or link to the wiktionary [entry](https://en.wiktionary.org/wiki/Queensberry_rules) which loses some meaning, so instead can just do it inline, "Be nice, play fair, keep it friendly" or something along those lines

**Comment by bovine3dom** [comment]
thanks for pointing this out

this is really annoying, why would a dictionary break its URLs, it's supposed to be a reference work, obviously people are going to reference it :(

i'm just going to sulk for a while about the state of modern society and link to Wikipedia
