### ISSUE TITLE
Counter-intuitive behavior when open'ing an integer (integer gets converted to IP address)

### ISSUE THREAD

**Issue by Alexis-D** [tridactyl/tridactyl#5081]
-   Brief description of the problem / repro:

`open 538` opens `https://0.0.2.26/` while I would expect it to open my default search engine with `538` as the query.

When the integer is large enough, the behavior is correct, e.g. `open 2549536629329` does opens my default search engine with `2549536629329` as the query.

-   Tridactyl version (`:version`): `1.24.1`

-   Firefox version (Top right menu > Help > About Firefox): `129.0.1`

-   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist): https://github.com/Alexis-D/.dotfiles/blob/master/.tridactylrc

Hypothesis:

`open` delegates to `openInTab` (line 1630 which GH doesn't render in the snippet below):

https://github.com/tridactyl/tridactyl/blob/bd23136c142e118c399ff29cca2761ab01b0eb93/src/excmds.ts#L1618-L1632

`openInTab` calls `queryAndURLwrangler`:

https://github.com/tridactyl/tridactyl/blob/bd23136c142e118c399ff29cca2761ab01b0eb93/src/lib/webext.ts#L398-L399

Which in turn has this logic:

https://github.com/tridactyl/tridactyl/blob/bd23136c142e118c399ff29cca2761ab01b0eb93/src/lib/webext.ts#L359-L366

Which seems to be the culprit:

```
>> new URL("http://538")
URL { href: "http://0.0.2.26/", origin: "http://0.0.2.26/", protocol: "http:", username: "", password: "", host: "0.0.2.26", hostname: "0.0.2.26", port: "", pathname: "/", search: "" }

>> new URL("http://2549536629329")
Uncaught TypeError: URL constructor: http://2549536629329 is not a valid URL.
    <anonymous> debugger eval code:1
```

Proposed behavior/fix:

Naively (?) I would assume that folks are more likely to expect `open [0-9]+` to open their search engine rather than rely on a somewhat obscure integer -> IP conversion. Instead we could check `address.match(/^\d+$/)` and if that's the case skip the `Maybe it's a domain without protocol ` logic in `queryAndURLwrangler`.

Issues I can think of with changing the current behavior (there might be more!):

* It's a breaking change if my assumption that no-one relies on this is incorrect ([xkcd – workflow](https://xkcd.com/1172/))
* On the off-chance someone has a search engine that matches `^\d+$` then this should probably be honored first

**Comment by bovine3dom** [comment]
this is absolutely a bug

`URL()` is converting a 32-bit integer to an IP address, which is, hilarious and technically allowed, but obviously not useful to any actual human beings

```js
parseFloat("192.168.1.1")
192.168 
```

sigh


IMO we should check if a string is float-ish and search for it if it's float-ish

**Comment by Alexis-D** [comment]
The JS world is full of surprising behaviors 😂.

Instead of `parseFloat` (which also would have been my first guess) maybe either of those will do the trick:

```
> ['538', '3.14', '1.1.1.1'].map(x => +x)
[ 538, 3.14, NaN ]
> ['538', '3.14', '1.1.1.1'].map(isNaN)
[ false, false, true ]
> ['538', '3.14', '1.1.1.1'].map(Number)
[ 538, 3.14, NaN ]
```

But not this one:

```
> ['538', '3.14', '1.1.1.1'].map(Number.isNaN)
[ false, false, false ]
```

And then we can wrap https://github.com/tridactyl/tridactyl/blob/bd23136c142e118c399ff29cca2761ab01b0eb93/src/lib/webext.ts#L359-L366 in a:

```typescript
// if the address looks like a number (e.g. 538, 3.14), then consider it as a search term, not a host; see #5081
if (!isNaN(address)) {
  // ...
}
```

?
