### ISSUE TITLE
Cancel activation

### ISSUE THREAD

**Issue by arialdomartini** [tridactyl/tridactyl#5086]
How to cancel an operation, when it was inadvertently initiated?

- Press `b` to show the tabs
- Say you change your mind, or you did not want to jump to another tab at all
- How to get back to the page?

Neither `Ctrl-c` nor `Esc` help here. I found no hints in the documentation.

**Comment by bovine3dom** [comment]
It should be as simple as pressing Escape. Maybe a duplicate issue of #5079 - could you try on a fresh profile as described in that issue?

**Comment by arialdomartini** [comment]
Hi @bovine3dom. It's indeed solved creating a new profile. Thank you.
