### ISSUE TITLE
Input field focus conflict on grep.app

### ISSUE THREAD

**Issue by alerque** [tridactyl/tridactyl#5090]
I make pretty regular use of [grep.app](https://grep.app), but the UI has an oddity that trips up Tridactyl. I can't even find an issue tracker for Vercel's project, but I'm wondering if it isn't something Tridactyl can be configured to *not* do on this specific site without completely disabling keyboard navigation.

When you first open the hope page, there is a front-and-center search box. Focusing it works fine with `gi`, but as soon as you type a single character the site redraws its own UI moving the search box to the top and introducing results. After that queries are processed and results shown incrementally.

The input focus is supposed to be re-connected after the search box is redrawn, but in my experience Tridactyl is intercepting something and the *second* character I type expecting it to be a search ends up being interpreted as a command. The UX is sometimes comical, sometimes worse.

Is there anything I can configure on Tridactyl's side for this site to not trip up the input focus redirection?

**Comment by bovine3dom** [comment]
works fine for me unless I run `:set allowautofocus false`

so `:seturl grep.app allowautofocus true` :)

**Comment by alerque** [comment]
Dude! I wish I'd asked a few *years* ago.

And thanks.

**Comment by bovine3dom** [comment]
You're welcome. In general if you have focus issues on a site, `allowautofocus` is the first thing to check :)
