### ISSUE TITLE
`:guiset gui none` leave URL bar half visible in firefox 133

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#5098]
title says it all :(

**Comment by protrolium** [comment]
can someone remind me where to locate the userChrome.css … I've done this before but cannot find it.

**Comment by protrolium** [comment]
thank you so much @leaty

**Comment by bovine3dom** [comment]
Just released this in a beta build. If you're on the beta branch (`:version` will have `pre` in it):

1. about:addons
2. click the cog, check for updates
3. restart firefox
4. run `:guiset gui none` or whatever you were using before
5. restart firefox
6. wait a few seconds
7. restart firefox again

so you'll have restarted Firefox three times in total
