### ISSUE TITLE
Address bar refusal to disappear.

### ISSUE THREAD

**Issue by 1xch** [tridactyl/tridactyl#5101]
-   Brief description of the problem:

-   Steps to reproduce:

    1.  2.  3.  4.  5.

-   Tridactyl version (`:version`):

1.24.1pre7084-6936f4fc

-   Firefox version (Top right menu > Help > About Firefox):

133.0 for Ubuntu
![Screenshot 2024-12-04 at 14-22-53 Hacker News](https://github.com/user-attachments/assets/ec9a7e0b-6445-41ab-b95b-49fa2ad7f9df)

pic related, Is this a new Firefox issue or a Tridactyl issue, or perhaps a third issue that is tangentially related to the first two? The address bar hangs down and refuses to go away.

**Comment by 1xch** [comment]
ehh, its likely not this apologies

**Comment by bovine3dom** [comment]
Duplicate of #5098 - it is Tridactyl's fault :)
