### ISSUE TITLE
tridactyl breaks firefox custom search

### ISSUE THREAD

**Issue by leshow** [tridactyl/tridactyl#5105]
-   Brief description of the problem:
enabling tridactyl causes all custom search engines to redirect to google instead of using the custom search.

for example: `rs pin` is meant to search for `pin` on the rust-lang std docs, if tridactyl is installed then this simply does a google search for `"rs pin"`

-   Steps to reproduce:
1. install extension
2. install custom search extension like: https://addons.mozilla.org/en-US/firefox/addon/rust-search-extension/
3. try to search using custom search extension (`rs foo`)

disabling tridactyl makes the custom search work again. is there a way to tell tridactyl not to do whatever it's doing with the search?

-   Tridactyl version (`:version`):
1.24.1
-   Firefox version (Top right menu > Help > About Firefox):
133.0
-   URL of the website the bug happens on:
all
-   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):
default config, no modifications

**Comment by bovine3dom** [comment]
`rs foo` works fine from the address bar

The extension you've linked isn't a "search engine" that we can access via this API - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/search - you can tell because it doesn't show up in `about:preferences#search`

It's using this separate API https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/omnibox but it means that other extensions can't interact with it.

I don't think there's any particularly good solution here - Mozilla won't let extensions interact via the omnibox because it could be used for privilege escalation between extensions, and your extension is unlikely to want to switch to the search engine API because it's much less powerful than the Omnibox one.

:(

**Comment by leshow** [comment]
Thanks for the comment. I'm not sure what version of tridactyl this changed in (could have been some time ago) but these two extensions used to play nicely together.

Is it possible to just disable tridactyl taking the input from the omnibox? I don't use tridactyl from the omnibox so I'd prefer the other extension to stay functional.

**Comment by bovine3dom** [comment]
I can't reproduce this - I can use `rs foo` from the omnibar while Tridactyl is installed. Tridactyl shouldn't be able to stop the other extension from working. It sounds like you're running into a Firefox bug

**Comment by leshow** [comment]
If you install the search extension after tridactyl it works for a little while, but I found it I restarted Firefox with both enabled it stopped working. I could enable and disable the extension again to get it working for a bit.

**Comment by leshow** [comment]
The reason I thought it was tridactyl is that the extension works fine when its run on its own, but after installing tridactyl omnibar says "Extension (tridactyl)" and the rs prefix doesn't seem to work anymore.

**Comment by bovine3dom** [comment]
Thanks for the extra info but I think this must be a Firefox bug that we can't do anything about :(

I'd recommend asking on the Firefox IRC channel and getting some help to file an issue on bugzilla

**Comment by leshow** [comment]
Got it. So tridactyl doesn't do anything to the omnibox search? Is that what you're saying? Weird how it only happens when the extension is installed. 

I'll try to contact Firefox but I suspect they will try to tell me it's an extension bug 😂

**Comment by bovine3dom** [comment]
It's not quite true that we don't do anything, we register a keyword `tri` just like the Rust extension registers a keyword `rs`. But those two shouldn't be able to conflict.

**Comment by leshow** [comment]
looks like this might be specific to the rust search extension, so i'll close this issue if that's okay

https://github.com/huhu/rust-search-extension/issues/229
