### ISSUE TITLE
Support POST requests with search engines

### ISSUE THREAD

**Issue by maxigaz** [tridactyl/tridactyl#525]
Certain search engines such as DuckDuckGo offer using POST requests by default so that your search queries won't show up in the page URL or the browsing history. It would be awesome if Tridactyl supported this in addition to GET requests (which is already possible through URL parameters like `?q=`).

As a bonus, such requests could be done through commands that don't show up in Tridactyl's command history either.

**Comment by glacambre** [comment]
This will be implemented "for free" once we get https://github.com/tridactyl/tridactyl/issues/792 working since the search API lets you use searchengines Firefox knows about, which could be configured to use POST.
