### ISSUE TITLE
Keep bookmark tags in mind when searching.

### ISSUE THREAD

**Issue by huffstler** [tridactyl/tridactyl#535]
### This is a feature request for "tag-aware" bookmark searching.

I'm not up to date on the WebExtension API and what it offers in the way of bookmarks, but I think it would be useful for categorization and cleanliness to be able to search for tags that you've assigned to bookmarks.

Currently there's a workaround where you can use a 'tag' for the name field, and search for that in the command bar. I don't think it's a viable long term option though :|

For example: 
![image](https://user-images.githubusercontent.com/9092204/40003277-efeb2ec2-5760-11e8-8a48-c80d975ef839.png)

If this were added, I would expect that link to show up here:
![image](https://user-images.githubusercontent.com/9092204/40003333-12906726-5761-11e8-9e45-c0206ed32252.png)

**Comment by glacambre** [comment]
I don't think we can access tags (they don't seem to be mentioned here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/bookmarks/BookmarkTreeNode).
We can access folders though, so we could try matching against parent folder names.

**Comment by bovine3dom** [comment]
Related: #73.

Mozilla don't seem to be keen on extending web extensions to let us do much with bookmarks, as they want to rethink bookmarks. We probably can't do anything to do with this at all.

**Comment by huffstler** [comment]
@glacambre 
Anything so that I can organize the monumental mess that are my bookmarks 😆 

@bovine3dom 
Are they trying to come up with something different to replace bookmarks? Is that what all this Pocket integration is for?

**Comment by bovine3dom** [comment]
@huffstler I have no idea.

**Comment by bovine3dom** [comment]
Closing a bunch of issues that we can't fix.
