### ISSUE TITLE
Scrolling with H/J/K/L does not obey smooth scroll preference

### ISSUE THREAD

**Issue by Bzly** [tridactyl/tridactyl#54]
Preference set in Preferences > Advanced > General > Use smooth scrolling. Page scrolling with arrow keys obeys this preference, but not with hjkl.

**Comment by cmcaine** [comment]
We can't read the user preference for smooth scrolling, but we can set our own preference for it and turn it on and off with the css property "scroll-behaviour".

In the future we hope to be able to scroll respecting the user prefence due to an extension to the webext API: https://bugzilla.mozilla.org/show_bug.cgi?id=1411724

**Comment by bovine3dom** [comment]
Tangential: some sites such as http://just-blinds.co.uk/blinds-manchester/ force smooth scrolling with j/k but not up/down.

**Comment by IsaacKhor** [comment]
Is this option currently implemented? I don't see anything that looks like a `smooth-scroll` option in `config.ts`. If not, how would you go about implementing it? I have some free time on my hands.

**Comment by cmcaine** [comment]
If the option is set apply the appropriate scroll-behaviour property to the body element. This needs to be done when config.ts starts.

There's no generic system for injecting variants of the CSS, but perhaps you can make one?

**Comment by IsaacKhor** [comment]
Temporary workaround: use Stylus to inject CSS into every page forcing `scroll-behavior: smooth !important`.

**Comment by bovine3dom** [comment]
Potentially fixed in #618 (requires native messenger and probably Linux/OSX for magic preference reading, otherwise do `set smoothscroll true`). Feedback wanted :)

**Comment by willsALMANJ** [comment]
With #618, single taps of `j` and `k` look nice. If I hold them down though, the response is not ideal. Tridactyl takes an initial step, pauses, then starts taking individual steps, and then continues taking more steps, potentially long after I let go of the key if I had held it down for a while.

Sorry if this is a newb question, but have you looked at what Vimium does? When XUL was first deprecated and Tridactyl was less polished, I used Vimium-FF for a while. Its scrolling seemed smooth and responsive to me.

One other slightly related question -- is it possible to change the individual scroll step size? The step size might be what bothers me more than the smoothness. When I press the arrow keys, I get a much smaller step.

**Comment by bovine3dom** [comment]
> One other slightly related question -- is it possible to change the individual scroll step size? The step size might be what bothers me more than the smoothness. When I press the arrow keys, I get a much smaller step.

`bind j scrolline 1` etc. The default is 10 :)

In general `bind [key]` will tell you what that key is bound to.

**Comment by Anton-Latukha** [comment]
> `bind j scrolline 1` etc. The default is 10 :)
`scrollline`

**Comment by bovine3dom** [comment]
Fixed, thanks.

**Comment by bovine3dom** [comment]
I'm going to close this as I reckon smooth scrolling is good enough in the latest betas (after #2016): `set smoothscroll true`. I don't think we'll ever get access to the Firefox smoth scroll permission.

**Comment by bovine3dom** [comment]
yeah, it's perfectly possible, we "just" need key up/down binds, see #4727 and #1626

the first time i tried almost everything worked except it broke all our special keys. then when i tried again a few years letter i had even more bugs.
