### ISSUE TITLE
Stick `hints` in your pipe and smoke it

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#545]
Left over TODO from the pipes PR:

- [ ] give most ex commands sensible return values
- [ ] rewrite hinting to use pipes as far as possible

**Comment by glacambre** [comment]
This is blocked by https://github.com/cmcaine/tridactyl/issues/663 .

**Comment by bovine3dom** [comment]
Closing as fixed alongside #2552 with `hint -F`
