### ISSUE TITLE
Exciting gotchas if you develop on Windows under MSYS2

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#549]
MSYS2 infects the path, so if you launch Firefox via MSYS2, you end up with lots of nice GNU utils that you probably weren't expecting to have.

This means that `set editorcmd auto` works on Windows if you launch via MSYS2 ~~~but not if you launch normally.~~~ fixed in 2779eaa.

**Comment by bovine3dom** [comment]
Also, weirdly, `firefox` somehow adds itself to on the PATH the native messenger sees, meaning that `nativeopen` just works.

**Comment by huffstler** [comment]
I'm gonna try re-creating this with cygwin (I'm under the assumption that it uses MYSYS2 under the hood right?)

This would be a very nice surprise to have it work.

**Comment by bovine3dom** [comment]
@huffstler I fixed it in 2779eaa anyway, so you shouldn't need to. I was just confused because Ctrl^I worked when I was developing, but didn't when I wasn't.

**Comment by bovine3dom** [comment]
wait, that commit was totally a no-op

why does it work now

help

**Comment by bovine3dom** [comment]
Actually fixed in 883243e, probably :D

**Comment by huffstler** [comment]
:( awhh okay

**Comment by bovine3dom** [comment]
Closing this as I don't think we have any Windows developers any more. If anyone reads this - I'd suggest using Linux, or using Windows Subsystem for Linux and then loading the extension via about:debugging in Firefox manually.
