### ISSUE TITLE
Not possible to bind bmarks with predefined title

### ISSUE THREAD

**Issue by scriptmode** [tridactyl/tridactyl#562]
I wanna define predefined targets for bookmarks, so I can bookmark them with one key to specific folders.

Syntax for bmark is "bmark \<url\> \<title\>" with <title> being optional. 
When binding this to a key, it would look like this: "bind \<key\> bmark \<url\> \<title\>", but given I don't wanna enter the \<url\> myself it should look more like this: "bind \<key\> bmark \<title\>"

But given the current syntax there seems to be no way to position \<url\> before \<title\>.
There seems to be two ways to fill url to bmark. First: call bmark without a parameter, then it will set \<url\> itself. Second: use current_url to add \<url\> at the end of bmark, which would result in "bmark \<title\> \<url\>". 

There are several possible solutions for this, maybe some are already possible now and I just didn't found them.

1. use an empty \<url\> which bmark then understand as undefined and fills in with the correct \<url\>
2. Communicate to bmark that \<title\> is not \<url\>
3. Allow for bmark or current_url to handle placeholders which will evaluate to \<url\>

**Comment by bovine3dom** [comment]
The sane solution is to have a flag on bmark for "use current URL", and another flag for title, which is blocked by #523.
---

But that's no fun at all.
You're right in that `current_url` does most of what you want, so let's have a look at what that does:
```
get exaliases.current_url
# exaliases.current_url = composite get_current_url | fillcmdline_notrail
```

So all you need to do is make another command that instead does this:

```
composite get_current_url | fillcmdline bmark
```

and make an alias for that:

```
command hackybmarktitlebind composite get_current_url | fillcmdline bmark
```

and then you can make binds as you wish:
```
bind mbe hackybmarktitlebind Emacs
```

... however, there seems to be a bug in composite where ex aliases are somehow putting arguments in the wrong place, so it doesn't actually work right now. :(

**Comment by bovine3dom** [comment]
## Attempt 2.
The following is a beautiful hack. I'm quite proud of it.

```
command hackybmarktitlebind !jsb tri.excmds.get_current_url().then(x => tri.excmds.fillcmdline_notrail("bmark " + x + "
```

```
bind mbe hackybmarktitlebind Emacs"))
```

Just remember the end quote and the brackets for each bind and you'll be golden.
:D

**Comment by scriptmode** [comment]
Oh, thanks for the fast reply :)
Seems like a solution, though I get the error "# Error: Not an excmd: !jsb". Similar when I try !js. I also used the Beta-Build as !jsb seems to be merged just yesterday, but same result. Both are not appearing in "viewconfig exaliases" either.

Is there some configuration neccessary to activate !js/!jsb? Or is my config just broken?

**Comment by bovine3dom** [comment]
You probably need to just update Tridactyl and restart - go to `about:addons`, click the little cog in the top right, click "check for updates", and then restart the browser (you can use `restart` if you have `native` working).

**Comment by scriptmode** [comment]
I tried that already, but it's the newest version from AMO (1.12.0 from 2018-05-14). 
The parallel installed beta-build is 1.9.8pre932 from today. 

I even created a new profile and tried the latest beta-build, but same result. 
Neither !js nor !jsb are available. I think js as a command is generally unknown.

**Comment by bovine3dom** [comment]
> The parallel installed beta-build is 1.9.8pre932 from today.

That's an old build: https://tridactyl.cmcaine.co.uk/betas/tridactyl-1.12.0pre1138-an+fx.xpi is the most recent. (rsync breaks the date modified times unhelpfully, which is probably why you think that's newer than it is). Also, please make sure you only have one version of Tridactyl running at once via about:addons.

`js` isn't on the AMO version yet.

**Comment by bovine3dom** [comment]
Yeah. We recently made some moderately big changes to `composite` so I want to leave it a while before doing another stable release.

**Comment by bovine3dom** [comment]
@scriptmode We might have broken your bind in the latest betas. Instead, try

```
command hackybmarktitlebind !jsb -p tri.excmds.get_current_url().then(x => tri.excmds.fillcmdline_notrail("bmark " + x + " " + JS_ARG)

bind mbe composite echo "Emacs" | hackybmarktitlebind
```

(there's probably a saner way of doing it but I can't think of it right now)

**Comment by glacambre** [comment]
```
alias hackybmarktitlebind js -p tri.excmds.fillcmdline_notrail(`bmark ${window.location.href} ${JS_ARG}`)
```
Works pretty nicely.
