### ISSUE TITLE
[Feature Request]: Focus text option for 'hint' command.

### ISSUE THREAD

**Issue by snippins** [tridactyl/tridactyl#564]
**Context**: I want to select text with keyboard. 

For now I am doing this by: enabling caret mode (firefox built-in). I noticed that when I focus something with 'hint -;' the caret go there. Thus to select a specific text:
1) I first focus something above it, then a search with Ctrl+F, 
2) Type a part of the text and multiples F3 to go there. 

This is quite slow, usually in a text editor I am able to jump to the same line thus only one or two F3 is needed and is as fast as the mouse. 

However I notice that the "hint -p" command hinting the text really well, thus if we can have a command similar to "hint -p" but just to focus and move the caret/cursor, I think we would able to have a full keyboard browsing experiment.

And thank you for making this great project. :+1:

**Comment by glacambre** [comment]
Would this be different from [visual mode](https://github.com/cmcaine/tridactyl/issues/32)?

**Comment by bovine3dom** [comment]
@glacambre I believe snippins is talking about the Firefox caret mode which Mozilla hides on `<F7>`.

I've had a go at implementing this in 14919b7, and `hint -; *` does hints everything as I'd expect, but it doesn't seem to move the cursor. It's quite possible that we can't `focus` `<p>` tags etc.

**Comment by snippins** [comment]
I believe this would support it. Normal search my go to the top of the page which is inconvenient. Thats why you need to cursor to be in the beginning

**Comment by snippins** [comment]
@bovine3dom I just tried surfingkeys and and able to move the caret with hint by their visual mode. Their own cursor and Firefox caret mode are appeared to be at the same place. You might want to take a look how they able to achieve that. Thanks you.

**Comment by snippins** [comment]
@bovine3dom I just read Surfingkeys code a bit more, it appears that the strategy to move the cursor to the tags that can't be focused directly is to add an element right before these tags and then remove it.

You can check the hideCursor and showCursor functions of Surfingkeys [here](https://github.com/brookhong/Surfingkeys/blob/2692192c0c1eec16f7a09cace13145b5f8700d57/content_scripts/visual.js).

**Comment by snippins** [comment]
The new visual mode solved this.
