### ISSUE TITLE
Extending followpagepatterns with user defined functions

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#599]
On https://lkml.org/lkml/2006/9/23/44 , I want `followpage next` to take me to the first answer to the current mail, not the next mail that was sent to the lkml. There doesn't seem to be any easily-matchable pattern to do that, so I'd probably need to write my own function that calls document.querySelector("li.origin") to find the right element to be followed.

**Comment by bovine3dom** [comment]
See #569 - you could do something similar.

**Comment by glacambre** [comment]
Thanks for linking this issue, I was looking for it but couldn't come up with the right search keywords.

**Comment by glacambre** [comment]
As you said, just a matter of adding the right DocStart autocommand.

**Comment by glacambre** [comment]
For those looking for something similar: I decided to use `:bindurl` in order to override my `:followpage` bindings on lkml.org. The code can be found here: https://github.com/glacambre/.dotfiles/commit/5c49243c6a23ce7407581d4c9c6fa3b7b6d319c3.
