### ISSUE TITLE
Command `open <arg>` searches google.co.uk instead of user's chosen search engine

### ISSUE THREAD

**Issue by hppavilion1** [tridactyl/tridactyl#60]
When the command `open <some_string>` is typed (including when the user presses 'o'), tridactyl searches google.co.uk rather than the user's default search engine.

**Comment by bovine3dom** [comment]
Thanks for the issue. This has been somewhat resolved by 709471a9ba2aa30761abbebb0da490c099518a47 as you can now choose from a big list and use, e.g., `open amazon widgets`. I'd recommend rebinding s to `fillcmdline open [engine of choice]`.

It should be in the beta builds soon, if not already.

Automatically using a different search engine on open based on a user preference is blocked by a more general configuration system.

Ideally, we would use the Firefox preference, but I don't believe that is possible at this time.

Thanks again for reporting these issues.

**Comment by hppavilion1** [comment]
Perhaps a settings window to allow

**Comment by hppavilion1** [comment]
Oops, accidentally closed. Disregard.

**Comment by ahungry** [comment]
At the least, you should allow setting the search engine based on a tridactyl user-preference, or if not possible, change to a more privacy minded search engine for the default, such as duckduckgo.com instead of google.

**Comment by ahungry** [comment]
Especially considering Duck user's can easily search google by typing "!g term here", or amazon via "!a term here" etc. (it has many many shortcuts for searching, giving a lot more power than a plain Google search).

**Comment by hppavilion1** [comment]
@ahungry That is true, and while the majority of internet users (English-speaking, at least) probably prefer Google to DuckDuckGo, the technical crowd that uses tridactyl is probably more prone to using DDG than average.

**Comment by bovine3dom** [comment]
We'll make it a user preference once we make user preferences. I think Google is a reasonable default, given that it is the default search engine in Firefox.

**Comment by ahungry** [comment]
I can understand that viewpoint, although I would disagree with it, since the original Google+Firefox combination was a business deal, same with the subsequent Yahoo+Firefox combination.

Since we/this project have no ties to Google, and Google is inherently anti-user (userbase is the product, advertisers are the client), setting DuckDuckGo as the default would help spread a more privacy oriented search engine among users who haven't heard of it before, as well as keep Google only 3 keypresses away (`!g term`) for users who prefer that while waiting on Tridactyl user-prefs/browser-prefs integration.

**Comment by madduck** [comment]
@bovine3dom instead of defaulting to GOOG, can't you just read the preference the user has already chosen for Firefox?

Apart from that, I totally agree that the Tridactyl userbase is not the one that expects or wants GOOG as a default for anything.

**Comment by m0tive** [comment]
For me this is pretty big. Back when using pentadactyl I would be constantly using `:o` in combination with ddg's bang commands for opening mdn reference, checking caniuse, searching wikipedia. Without proper support for ddg, i.e. having to type out "duckduckgo" (the normal abbreviation "ddg" isn't even supported...), tridactyl seems pretty slow in comparison to vanilla firefox.

**Comment by bovine3dom** [comment]
> I totally agree that the Tridactyl userbase is not the one that expects or wants GOOG as a default for anything.

According to the referer headers, the traffic from search engines to this project is about 90% Google, and 10% Duckduckgo, so I'm not totally convinced by this.

@m0tive as I said above, you could try `bind s fillcmdline open duckduckgo`. I've no problem adding `ddg` to the list of search engines if there is enough demand for it.

User preferences are a priority, although we're currently focused on getting the command line completions to a usable state.

**Comment by m0tive** [comment]
@bovine3dom that helps!

**Comment by madduck** [comment]
Dear @bovine3dom I just retrieved the latest version and it's fantastic how much progress you guys have made. Thank you so much.

Regarding this issue, I wanted to voice one more time the idea of defaulting to the user-chosen preference in the Firefox preferences. There, GOOG is the default search engine, unless the user overrides it. Wouldn't it make the most sense for Tridactyl to reuse that setting, if that's webext-possible…?

**Comment by bovine3dom** [comment]
It isn't possible with web extensions, as far as I know (hence the label).

I would be delighted to be corrected.

**Comment by ahungry** [comment]
Was any of this draft ever implemented? (is it in any way possible to query user pref data?)

https://developer.mozilla.org/en-US/docs/draft_Search_Extension_Tutorial

Would it be possible to just call the default 'search' method and use the same interpolation for `{searchTerm}` that FF recommends for custom search providers that get added?

**Comment by bovine3dom** [comment]
@ahungry Thanks, but unfortunately that is not part of WebExtensions. There are only 6 settings we can read - https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserSettings.

Overriding search engines was such a common tactic of crapware that you now have to do it in `manifest.json` so the browser can give you a nice big warning and ask you if you're really you want to.

It is somewhat ironic that Mozilla's solution to everybody overriding search engines is forcing us to override people's search engines.

**Comment by madduck** [comment]
I completely understand how Mozilla wants to prevent extensions from messing with preferences, but all we really need is to *read* the preference. Is there something that fundamentally speaks against this? If not, then do you think the Mozilla team could be amendable to this?

**Comment by bovine3dom** [comment]
They might be. It's probably a pretty niche request though, because they think everyone will use the omnibar.

**Comment by Bazalia** [comment]
I like using the t binding for opening new tabs. Its great because it shows history, but if I bind t to fillcmdline tabopen duckduckgo it will then only show history that includes duckduckgo. Is there a way to keep the binding to duckduckgo without losing history unrelated to duckduckgo?

**Comment by bovine3dom** [comment]
No, not really. You could bind it to a different key, or just do ctrl-backspace when you want non DDG history.

The other option is to do `bind t tabopen` and just use the omnibar (if you have set the default search engine to ddg in Firefox).

**Comment by Bazalia** [comment]
Thanks "bind t tabopen" works fine for me. I don't know how I missed that.

**Comment by bovine3dom** [comment]
`set searchengine bing` will be possible in the betas soon and should solve most of the problems in this thread : )

Adding search engines to SEARCH_URLS is on the to-do list, but we need to think about how we will allow users to set more complicated objects first.

Thanks for your patience!

**Comment by madduck** [comment]
That sounds great, @bovine3dom! Thank you so much. Can't wait for the beta…

**Comment by bovine3dom** [comment]
@madduck anything >= 497 on https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/versions/beta includes it : )

**Comment by madduck** [comment]
@bovine3dom so I already had it installed, and it works as expected. Thank you so much!

**Comment by bovine3dom** [comment]
Reopening in light of #792.

**Comment by coaxial** [comment]
how can I undo `bind s fillcmd open startpage` and restore `s` to whatever it was doing before now that `set searchengine <anything but google>` works?

**Comment by coaxial** [comment]
That worked, thank you

**Comment by glacambre** [comment]
Tridactyl can now use Firefox's search engines in the betas. Take a look at `:help searchengine` :)

**Comment by ahungry** [comment]
Hooray
