### ISSUE TITLE
Add an option to reset the focus when moving to an existent tab

### ISSUE THREAD

**Issue by j-a-m-l** [tridactyl/tridactyl#607]
For those of use that are used to navigate through tabs with `gt` and `gT`, it's annoying that when you move to a previous tab that has an input that was remains focused, if you press `gt` or `gT`, instead of moving to the next or previous tab, that characters would be written on the input.

Having an option to reset the page focus when moving to a tab would solve it.

**Comment by bovine3dom** [comment]
This is probably possible with https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/onActivated, but we'd need to make sure that e.g. `g;` wasn't affected. The best approach might be to make `tabnext` / `tabprev` make a listener that removed itself as soon as it was called.

**Comment by j-a-m-l** [comment]
Anyway, this should be optional, so people that don't want this behaviour could ignore it.

**Comment by glacambre** [comment]
There's also `set allowautofocus false` that should help you with this. This will break js editors such as Ace, but I find it very useful for everything else.
Note that if you set `allowautofocus` to false, you'll also probably want to set `browser.autofocus` to false in `about:config`.
We should probably implement a way to automatically toggle this flag when `allowautofocus` is changed.

**Comment by j-a-m-l** [comment]
Thanks @glacambre. I've tried that and it's probably enough

**Comment by glacambre** [comment]
In the betas there's also `autocmd TabEnter .* unfocus`. I think this issue can be closed now :)

**Comment by bovine3dom** [comment]
Should probably add something to the FAQ.

**Comment by glacambre** [comment]
I think this can be closed now since #644 has been merged.
