### ISSUE TITLE
Hook into existing new-tab addons

### ISSUE THREAD

**Issue by dertuxmalwieder** [tridactyl/tridactyl#66]
I understand that `about:newtab` is taboo zone. I, however, use Tabliss for my new tabs which should be enough to get that background script going. :-) Isn't there a way to detect existing "new tab" overrides, so Tridactyl could just hook in there?

(By the way: Thank you for Tridactyl. Really makes things easier.)

**Comment by bovine3dom** [comment]
The trouble is that we need a content script to run on every page to capture keyboard input. We can't interfere with pages from other extensions at all.

@cmcaine is working with Mozilla on a solution, namely moving key capture to the background script, but it will be a while (earliest possible is FF59) before we can use it.

**Comment by jaimehrubiks** [comment]
I investigated around this 'idea' for some time. I used to use "surfing keys" chrome extension and now I am trying this on firefox. The thing is that chrome allows for "global keybindings" which apply everywhere, giving you the chance to switch tabs faster (even when pages have not loaded yet) or even in new-tab, other extensions pages and even on the exensions 'shop'.

In firefox (I'm new after a lot time) I can't find any similar functionallity, so I ended up using together an extension like tridactyl in parallel with some OS level hooks (windows: AHK, and OSX: BTT) to allow me to, at least, change tabs (binded by keys to ctrl+tab) so that I do not get stuck in pages with no extensions loaded or to switch even in search or text mode (and of course, to switch faster).

**Comment by robertgzr** [comment]
> earliest possible is FF59

@bovine3dom 
FF Nightly is on 59.0a1 do you have a bugzilla issue I can track for that?

cc @cmcaine

**Comment by cmcaine** [comment]
@jaimehrubiks what do you mean by "chrome allows for "global keybindings""? Could you provide a link?

@robertgzr the main bug is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1215061 and there are dependent bugs.

**Comment by jaimehrubiks** [comment]
@cmcaine https://i.imgur.com/yWOT7Z0.png It is shown below in the extensions page. I don't know which API implements this or if firefox has something like this too or is chrome-specific.

Also today I saw a new idea from brookhong, he is a great dev and published a new mechanism to allow keybindings everywhere at chrome code level using a patch

https://brookhong.github.io/2017/10/15/surfingkeys-across-all-pages.html

**Comment by Bzly** [comment]
If you read the top part of the page you linked, you'll see that Surfingkeys suffers from the same limitations that Tridactyl does in Firefox:

>You may get annoying when you come to below pages, as Surfingkeys(actually all normal extensions) does not work on those pages.
    * Chrome built-in pages like chrome://extensions/
    * Google Webstore https://chrome.google.com/webstore/category/extensions
    * Pages from other extensions like chrome-extension://youmaygetannoyingwhenyoucometobe/options.html
That’s because the browser Chrome does not allow that for security reason.

**Comment by cmcaine** [comment]
@jaimehrubiks Thanks. That's the [commands API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/commands). Unfortunately, as an add-on developer, you have to register any shortcuts at install time and you can only register commands which are single keypresses with modifiers (excepting function and media keys, which don't need modifiers)

Thanks for the surfingkeys link, though, that might be useful for the new FF API we're trying to build.

**Comment by bovine3dom** [comment]
We now provide builds without a new tab page - https://tridactyl.cmcaine.co.uk/betas/nonewtab - and some people have reported that installing new tab addons just works fine with normal Tridactyl. I don't see this ever being something we can fix on our own, so I'm closing this for now - and I'll mention #760 just in case someone wants to report it to Bugzilla.
