### ISSUE TITLE
Shell script gotchas 

### ISSUE THREAD

**Issue by gsbabil** [tridactyl/tridactyl#672]
@bovine3dom @cmcaine @johnbeard @peff 

- #### XDG Directories

https://github.com/cmcaine/tridactyl/blob/335e994349da29dc56e71565f981055f2112bb6f/native/install.sh#L19-L20

If user's `XDG_CONFIG_HOME` is set to `/home/user/.xdg`, do you mean
to drop the native-messenger files into:

  1. `/home/user/.xdg`, or
  2. `/home/user/.xdg/tridactyl`

I have a feeling that it is [2], which is not met with above.

- #### Mixture of BASH and POSIX shell scripts

We have a mixture of Bash and vanilla POSIX shell scripts spread
under `native` and `scripts` directories. Do we need both varieties?

It might be simpler and cleaner to maintain one of them only. Bash
is pretty ubiquitous. But if you prefer POSIX, let's stick to POSIX 
only, and _not_ mix both.

- #### Nuance with `sed -i`

`sed -i` I don't think is portable to Mac. Mac tends to ship with
`BSD` version, while Linux ships with `GNU` version of sed, leading
to syntax errors around `sed -i`.

Please confirm. I am happy to submit patches where I can.

Thanks.

**Comment by peff** [comment]
> It might be simpler and cleaner to maintain one of them only. Bash
is pretty ubiquitous. But if you prefer POSIX, let's stick to POSIX
only, and not mix both.

My patch in this area fixed some bash-isms, but I really don't have anything against bash, as long as the `#!` line says `bash`  and not `sh`. Lots of platforms have non-bash shells as `/bin/sh`. Most modern platforms have bash _somewhere_, though it may not always be at `/bin/bash`, which complicates things a little.

**Comment by gsbabil** [comment]
Hi @peff,

Thanks. Similar to you, I don't mind either, but I'd indeed prefer
to avoid using both in the same code-base.

The reason I think we are fixing bash-isms in POSIX shell scripts,
and potentially the other way around, is because we have a mixture
of a both.

My two-cents here would be that we pick one - either POSIX or Bash -
and stick to that. We _can_ of course do both, but IMHO we _should_
pick only one, out of these two tools.

Thank you.

**Comment by bovine3dom** [comment]
```
Mixture of BASH and POSIX shell scripts

We have a mixture of Bash and vanilla POSIX shell scripts spread
under native and scripts directories. Do we need both varieties?

It might be simpler and cleaner to maintain one of them only. Bash
is pretty ubiquitous. But if you prefer POSIX, let's stick to POSIX
only, and not mix both.
```

Our goal was to make it such that the crunchbangs were not incorrect.

But - as I understand it, bash is mostly a superset of sh, so we should probably just use whatever the most portable way of finding bash is everywhere, as hopefully that will catch fewer people out.

---

I haven't looked at `sed` on OSX, but last time I tried to build Tridactyl on OSX it worked fine - but that was quite a few months ago.

**Comment by alphapapa** [comment]
I don't know of any system that has `bash` anywhere other than `/bin/bash`, but you could use `#!/usr/bin/env bash` to be extra safe.

**Comment by peff** [comment]
It's been a while since I've used one, but *BSDs used to ship only `ash` with the base system, and `bash` would get installed from ports as `/usr/local/bin/bash`. I have no idea if that's still the case, but certainly using `env bash` wouldn't hurt.

Lots of other ancient Unix systems also don't ship `/bin/bash`, but I doubt that they'd even run modern firefox. IMHO there's a long tail of "probably not relevant" systems that you can mostly ignore until somebody shows up with a real-world case and offers to do the portability work.

But note that I'm mostly just a user of tridactyl, so that's just my philosophical two cents; people with more than one patch in the project may or may not agree. :wink:

**Comment by bovine3dom** [comment]
> I'm mostly just a user of tridactyl
>
> -- Jeff King, git co-author

Can I put that on a t shirt? /fangirl

---

> IMHO there's a long tail of "probably not relevant" systems that you can mostly ignore until somebody shows up with a real-world case and offers to do the portability work.

This is exactly what we did for Windows and it worked well (thanks @gsbabil :D).

More seriously, #46 and #142 probably contain all we "need" to do.

Nobody has complained for a while, though, so maybe they just got sick of us adding new steps that broke the build for them.

**Comment by peff** [comment]
> Can I put that on a t shirt?

Heh. I love tridactyl, and am happy to endorse it on t-shirts or otherwise. ;)

**Comment by bovine3dom** [comment]
I'm hoping `shellcheck` will help us to keep things mostly portable. Also, no-one has complained in a while, so we're probably doing OK - or we've scared everyone with non-standard configurations (that is, not a ThinkPad X series running Arch) away.
