### ISSUE TITLE
Merchandise

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#676]
I'd quite like a Tridactyl t-shirt, maybe some stickers and definitely some Christmas cards.

@antonva recommended redbubble.com.

Does anyone else have any recommendations?

Edit: recommendations of stores which sell printed goods...

**Comment by glittershark** [comment]
I'd buy stickers and a shirt for sure!

**Comment by caputchinefrobles** [comment]
o/

**Comment by bovine3dom** [comment]
I'm glad people are excited, but I really wanted recommendations of merchants who sell printed goods; I think my OP was a little unclear.

**Comment by huffstler** [comment]
I've only really heard of RedBubble. Maybe Etsy if someone is more artistically inclined on the project.

**Comment by bovine3dom** [comment]
Vimperator used Zazzle: https://www.zazzle.com/maxauthority

**Comment by bovine3dom** [comment]
https://www.stickermule.com/uk sticker shop (although we would have to do all the postage ourselves)

**Comment by bovine3dom** [comment]
![tridactylsticker](https://user-images.githubusercontent.com/6505246/42956474-f518e98e-8b77-11e8-85de-c8379559914a.png)

^ This is my first attempt at a sticker. Thoughts?

I think for a t-shirt I'd remove the black outline.

**Comment by antonva** [comment]
![tmp](https://user-images.githubusercontent.com/1540222/43073231-55369ba2-8e68-11e8-9de7-eec0c03982a1.png)

Just using the new font plus logo on a rectangle.

**Comment by bovine3dom** [comment]
I quite like the one without a dot at all. I am a sucker for serifs, though...

**Comment by antonva** [comment]
![tmp](https://user-images.githubusercontent.com/1540222/43073596-bcfc6d4c-8e69-11e8-93c2-08b0a44260b6.png)

Like that?

**Comment by bovine3dom** [comment]
![tridactylsticker](https://user-images.githubusercontent.com/6505246/43162055-ca565d22-8f81-11e8-83c4-fb7625083bf4.png)

?

**Comment by Bzly** [comment]
Are you using the SVG logo, by any chance @antonva ? The auto convert wasn't particularly fantastic, and made the ratios inside the image ever so slightly odd, imo (also I don't think the tip of the claw sticking out on the left looks very good, particularly not at smaller sizes). 

The trouble is as the logo gets smaller the outline needs to get thinner - and not at a directly proportional rate - plus the thinner outline on the claw leaves odd-looking spaces on the left hand side, where the gap to the circle outline is smallest. I'd recommend twiddling about with the .PSD, as I assume @bovine3dom has.

I prefer the rounded corners of @bovine3dom, with the computer modern font.

**Comment by antonva** [comment]
@Bzly  I was using the SVG logo. I should probably touch that up a bit. 

And yeah I like the computer modern plus rounded corners just fine

**Comment by bovine3dom** [comment]
Tat is now live: https://www.redbubble.com/people/bovine3dom/works/32865870-tridactyl-add-some-vim-to-your-life?asc=u&modal=%2Fboom%2Fb%2FavailableProducts%2F32865870&p=t-shirt

I'm getting a t-shirt myself. No representations made to the quality of the items.

I'm happy to add more designs if people particularly want, e.g, a squarer sticker.

**Comment by bovine3dom** [comment]
You can use the coupon `B2S-gentleman15` for 15% off at the moment.

**Comment by bovine3dom** [comment]
The t-shirt arrived and is good. I got lots of funny looks going across London in it.

The stickers could do with a slightly higher DPI print. I'll get @cmcaine to upload a picture of them.

I'll leave this issue open till I can figure out where to put it on the readme.

**Comment by bovine3dom** [comment]
Link to shop is here - https://www.redbubble.com/people/bovine3dom/shop?asc=u - as I mention on the README, we don't take a cut. If you'd like to make a donation please use PayPal or Patreon.

There are lots of things available to buy other than the T-shirt but they are slightly well hidden. Just play with the filters.

At the time of posting, the voucher code `ART20` will give you 20% off.
