### ISSUE TITLE
mktridactylrc

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#695]
We want to convert the user's current settings into a tridactylrc file; i.e, a series of ex-commands.

- should check to see whether a tridactylrc already exists and only allow overwriting it if a ! is appended to the command.
- `mktridactylrc /path/to/tridactylrc` should also be supported
- pipe support for e.g, the clipboard could be nice

If we restrict ourselves to just replicating the non-default settings, then this should not be too difficult.

I think it's fine to have `guiset` and `fixamo` be out of scope at least initially.

Bonus: in the grand tradition of Pentadactyl, we should ensure that `mkv` and `mkp` are bound to some unexpected commands; `mkv` for installing tridactylrc ftdetect etc is fine, and perhaps `mkp` could be "make print preview"?

**Comment by antonva** [comment]
I've started working on this. Currently using `config.get` and parsing it into sectioned ex-commands. I'm currently only leaving out unset config settings like an empty `homepages` array or a `newtab` consisting of the empty string.

**Comment by bovine3dom** [comment]
@antonva my intention was to do it via the user config browser storage, to avoid writing defaults to the rc.

What I really meant to say in the first post is that everything can just use `set` and I think that's fine. We can do `bind` later if we want to.

**Comment by antonva** [comment]
@bovine3dom changing to user config browser storage should be easy, I'll switch to that. I've already done some basic parsing into `bind` and `alias` etc. I can shoot you a PR of what I have so far if you want.


PS I think we need to add some documentation on the site or in `:help` for config options discoverability. `:viewconfig` is all well and good but some options might need some better explanation

**Comment by antonva** [comment]
Oh, nice. Must have glossed over that one.

**Comment by bovine3dom** [comment]
>  I can shoot you a PR of what I have so far if you want
Yes please :)

**Comment by antonva** [comment]
I'm pretty much out for a good chunk of today, I'll create the PR when I get back.

**Comment by mMontu** [comment]
I look forward to see this feature working 😃
