### ISSUE TITLE
`blacklistadd` doesn't play nicely with multiple windows

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#707]
If one window is on a blacklisted URL, the other window is put in ignore mode and stays there.

Adding a `TabLeft [url] mode normal` doesn't seem to fix it. Perhaps we need `DocFocus` and `DocBlur` events?

**Comment by bovine3dom** [comment]
#739 related.

**Comment by glacambre** [comment]
Does this still happen?

**Comment by bovine3dom** [comment]
It was fixed by moving modes to content.
