### ISSUE TITLE
RSS finding

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#709]
E.g. `composite getrss | clipboard`.

I've no idea how the "subscribe" button in Firefox works (hidden behind the UI customisation these days), but it would be nice to replicate it.

**Comment by glacambre** [comment]
I had a similar idea here: https://github.com/cmcaine/tridactyl/issues/575

I believe what Firefox does is just find urls that match a certain pattern (e.g. `feed.xml`, `atom.xml`, `*.atom`…).

**Comment by reversebreak** [comment]
Hmm, Vimperator/Penta must have had code to grab the web feeds, since if you go 
G
CTRL+G
You get the page info screen which includes a listing of all feeds embedded in the page.
Maybe you can cannibalise that code?

**Comment by twm** [comment]
I believe that the Firefox Feed button works by looking for `<link rel="alternate">` with `type="application/atom+xml"`, `type="application/rss+xml"` and similar. There can be multiple links per page (different formats, different meanings). E.g., this page has:

![image](https://user-images.githubusercontent.com/43662/43053701-f3751842-8de2-11e8-97af-1beb9dfb2d9c.png)

@bovine3dom Would you want all of these URLs to be copied? The first? The last? The "best"?

**Comment by bovine3dom** [comment]
Added in #1263 as `rssexec`.
