### ISSUE TITLE
Shift+A to add favourite to 'Other Bookmarks' without prompting uses URL instead of Title

### ISSUE THREAD

**Issue by reversebreak** [tridactyl/tridactyl#711]
Easy to reproduce - just Shift+A on a page.
In Vimperator and Pentadactyl, the bookmark name was created using the page title, whereas in Tridactyl it just uses the URL instead.

**Comment by glacambre** [comment]
This is a [planned feature](https://github.com/cmcaine/tridactyl/blob/83e1026d7f1e889631234b5ebf8e397504ec2b75/src/excmds.ts#L2739).

**Comment by reversebreak** [comment]
I fixed it!

Unfortunately, the fix is still stuck on my local computer, as I'm stuck in some sort of `npm run pretty` hell loop.  
(I'm working in Git Bash btw, with the shell in the src directory)
So what happens is that I `git add src/excmds.ts`.  I try and commit, but it triggers a hook of some kind that wants me to run `npm run pretty`.  So I run the prettifier.  It seems to just have added a bunch of semicolons, which is OK.  I `git add src/excmds.ts`, and try to commit again.  It wants me to pretty it again, even though there's nothing left to prettify!  I literally just prettified the thing it wants to touch again!

Seriously how do I turn the autoimmune robot off, or even fix it?

**Comment by bovine3dom** [comment]
`git commit -n` will skip it : )

Development on Windows is not very well tested so you're bound to come into issues like this. If pretty is adding semicolons then it probably isn't finding the configuration correctly.

Please just make a PR and we can sort out the formatting for you.

**Comment by bovine3dom** [comment]
Added in #862. Thanks, @reversebreak :)
