### ISSUE TITLE
autocmds can run in a different tab to the one they were triggered in

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#727]
Steps to reproduce:

1. `autocmd DocStart www.reddit.com urlmodify -t www old`
2. `open news.bbc.co.uk`
3. `tabopen www.reddit.com`
4. Hit Ctrl-Shift-Tab as quickly as possible
5. Watch as old.bbc.co.uk is loaded.

**Comment by bovine3dom** [comment]
Alternative, more annoying steps to reproduce:

1. `autocmd DocStart www.reddit.com urlmodify -t www old`
2. `open search reddit.com`
3. Open a reddit link in a background tab with `F`
4. Watch as old.google.co.uk is loaded

**Comment by sjug** [comment]
I'm seeing this quite a bit, how can I disable these autocmds?

**Comment by antonva** [comment]
@sjug Have you set any autocmds yourself? You can double check by entering `:viewconfig autocmds`. This should contain all autocommands you might have issued at some point or another.

If you're experiencing the exact issue @bovine3dom is describing it could be that you are using the example `tridactylrc` which does indeed have the `autocmd DocStart www.reddit.com urlmodify -t www old` directive.

That being said, to remove an issued aucmd, on the latest betas you can use `:autocmddelete` from #750. If you're using a version prior to that your best bet is to issue `:unset autocmds` from the command line.

**Comment by bovine3dom** [comment]
(and remove it from your Tridactyl RC)

**Comment by antonva** [comment]
Even after making sure that the DocStart event was being fired from the expected tab I noticed something. The aucmd doesn't use the content script provided `urlmodify` but rather the one provided via `background.js`.

`function urlmodify(mode, ...args) {
    return Object(__WEBPACK_IMPORTED_MODULE_0__messaging__["messageActiveTab"])("excmd_content", "urlmodify", [mode, ...args]);
}`

Which then proceeds and urlmodifies the active tab as expected.

**Comment by bovine3dom** [comment]
Why refactor when you hack around bad decisions?

`autocmd DocStart www.reddit.com js tri.excmds.urlmodify("-t www old")` works fine.
