### ISSUE TITLE
trim content after copying from ;p

### ISSUE THREAD

**Issue by RNabla** [tridactyl/tridactyl#776]
It's more like enhancement

Many times I am copying content of some paragraph and I am getting many blanks or tabs in the beginning of copied content when I paste it somewhere else. It's kinda frustrating cause I am only interested in 'text' 99% of the time.

# Issue
Can Tridactyl trim such copied content as default behaviour?

**Comment by glacambre** [comment]
I'm against changing the default behavior. In my opinion we should just implement https://github.com/cmcaine/tridactyl/issues/545, which would let users who want it bind `;p` to something like `:composite hint | trimcontent | clipboard`

**Comment by glacambre** [comment]
Hi. I know this issue is quite old so you might not need this anymore but in case you do, you can use `composite hint -pipe a textContent | js -p JS_ARG.trim() | clipboard yank` in order to do what you want.
