### ISSUE TITLE
Trying to scroll beyond the end of a page sometimes makes scrolling up slower

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#777]
Steps to reproduce:

1. Visit https://www.viva64.com/en/b/0574/
2. Scroll to end of page with `G`
3. Press `j` a few times rapidly
4. Press `k`, observe that it takes a while to scroll up
5. Press `k` once more and notice that it takes less time

**Comment by glacambre** [comment]
I think I've noticed this issue from time to time but I can't reproduce it with Firefox `60.0.2` and Tridactyl `1.13.1-55-g581fda0` on the website you linked.

**Comment by glacambre** [comment]
This has been accidentally fixed, maybe by https://github.com/tridactyl/tridactyl/pull/1050/files . I'd never have thought that such an annoying bug could disappear in just 8 characters.

**Comment by glacambre** [comment]
This bug isn't dead at all :(

**Comment by bovine3dom** [comment]
I can reproduce this reliably on https://news.ycombinator.com/item?id=18184830 and can confirm it was never fixed.
