### ISSUE TITLE
Persuade the third of users on ancient versions to update

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#788]
Related to #708. About a third of our users are on really quite old versions that probably have some annoying bugs in: https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/statistics/usage/versions/?last=30

Sketch of approach:

1. Fix #708 (e.g. by filing bug via #760)
2. Remove all permissions since 1.7.x and make release begging people to update (and apologise to people who we have broken Tridactyl for temporarily)
3. Depending on question below: make release that re-instates the permissions right afterwards or a few days afterwards once the number of people using the old versions drops down to lower numbers

Questions:

- Will Firefox upgrade to the most recent update that doesn't require new permissions silently, even if updates in between required more permissions?
- If the most recent version requires permissions, but there is still a newer version that doesn't, will Firefox update to that?

**Comment by glacambre** [comment]
Another way of doing this could be to ask Mozilla to implement an actually useful optional permission API and switch all of our permissions to this.

**Comment by bovine3dom** [comment]
We seem to only have about 150 users still on 1.{9,7}.x, so I think I'm going to close this issue. #708's fix ought to prevent this from happening again.
