### ISSUE TITLE
Ignore keyboard layout

### ISSUE THREAD

**Issue by Susexe** [tridactyl/tridactyl#790]
I'll quote an option in Vimium-FF: "This forces the use of en-US QWERTY layout and can be helpful for non-Latin keyboards."

So basically, an option for enabling normal mode command execution regardless of a selected keyboard layout. It's a big priority for non-Latin users. Constantly changing layouts for executing commands and text input is pretty tiresome.

Thanks.

**Comment by bovine3dom** [comment]
This would probably fix #346.

**Comment by Susexe** [comment]
Is there a reason keymaps are preferred over forcing

**Comment by Susexe** [comment]
Is there a reason keymaps are preferred over forcing en-US QWERTY layout? It seems less convenient, even though use cases are probably wider. I pretty much use Tridactyl's default settings with minimal tweaks that I can type in really quickly into the console, and having to create a translation table and store my config file somewhere for the use on a new system seems like a hassle.

Forcing en-US layout as a default option in normal mode could be better, in my opinion.

**Comment by glacambre** [comment]
>Is there a reason keymaps are preferred over forcing en-US QWERTY layout?

On top of the flexibility you mentioned, implementation simplicity I believe. Right now the code just handles letters, if we wanted to force using the QWERTY layout we'd have to translate letters to key codes in a lot of places (bind, get, completions, help pages, key event handlers...). I'd also argue that this is how vim handles input and that not departing from it on this specific point sounds like a good idea to me but I'll recognize that this is a much flimsier argument.

>store my config file somewhere for the use on a new system seems like a hassle

I think Firefox Sync can synchronize your webextension settings, although some users have reported issues with it.
Do you use vim's `langmap` feature? Perhaps we could also add a `langmap` setting that would take the exact same syntax, then you could just copy/paste from your vimrc.

**Comment by bovine3dom** [comment]
I'm happy to accept PRs that help set up keymaps for specific languages if you have one, or we can (make and) add it to the wiki.
