### ISSUE TITLE
PyInstaller under Wine breaks native sometimes.

### ISSUE THREAD

**Issue by Susexe** [tridactyl/tridactyl#797]
At first, the `Invoke-WebRequest`was causing issues when executing the code generated by `:installnative`. I resolved it by installing a newer version of PowerShell. Now, even though the installation completed, `:native` still couldn't find it. I'm using Windows 7 64-bit along with Firefox 61.0.1.

**Comment by antonva** [comment]
I'm not up to speed on the current state of the native messenger on Windows but here are some questions that will probably speed up the debugging process for everyone: 

* Do you have `native_main.bat` `native_main.py` & `tridactyl.json` in your `C:\Users\$USER\.tridactyl\` directory? If not, do you have the .exe file there instead?
* Is python 3 Installed on your system?
* What is the output of the `:installnative` command when you run it in PowerShell?
* Which version of PowerShell are you running? See #798 and related issues.

**Comment by Susexe** [comment]
> Do you have `native_main.bat native_main.py` & `tridactyl.json` in your `C:\Users\$USER\.tridactyl\` directory?

I have `native_main.bat`, `native_main.exe` and `tridactyl.json`.

> Is python 3 Installed on your system?

No.

> What is the output of the `:installnative` command when you run it in PowerShell?

> [+] Looking for Python 3 ...
>     - Python 3 not found, will use EXE ...
> [+] Preparing C:\Users\VVV\.tridactyl ...
>     - C:\Users\$$$\.tridactyl exists, moving on ...
>     - Testing C:\Users\VVV\.tridactyl was successful!
>     - Creating C:\Users\VVV\.tridactyl was successful!
> [+] Downloading https://tridactyl.cmcaine.co.uk/betas/native_main.exe ...
>     - Testing C:\Users\VVV\.tridactyl\native_main.exe was successful!
>     - Creating C:\Users\VVV\.tridactyl\native_main.exe was successful!
> [+] Preparing C:\Users\VVV\.tridactyl\native_main.bat ...
>     - Testing C:\Users\VVV\.tridactyl\native_main.bat was successful!
>     - Creating C:\Users\VVV\.tridactyl\native_main.bat was successful!
> [+] Downloading https://raw.githubusercontent.com/cmcaine/tridactyl/master/native/tridactyl.json?1531475678,68742 ...
>     - Testing C:\Users\VVV\.tridactyl\tridactyl.json was successful!
>     - Creating C:\Users\VVV\.tridactyl\tridactyl.json was successful!
>     - Patching C:\Users\VVV\.tridactyl\tridactyl.json was successful!
> [+] Adding registry key HKCU:\Software\Mozilla\NativeMessagingHosts\tridactyl ...
>     - Adding registry was successful!
> [+] Cross-checking everything ...
>     - Testing C:\Users\VVV\.tridactyl\tridactyl.json was successful!
>     - Testing C:\Users\VVV\.tridactyl\native_main.exe was successful!
>     - Testing C:\Users\VVV\.tridactyl\native_main.bat was successful!
> [+] Getting (Default) registry value HKCU:\Software\Mozilla\NativeMessagingHosts\tridactyl ...
> [+] Getting registry key HKCU:\Software\Mozilla\NativeMessagingHosts\tridactyl ...
> [+] Installation successful!
>     - Run ':native' in Firefox to cross-check. :-)

> Which version of PowerShell are you running?

Version 5.

**Comment by bovine3dom** [comment]
> VVV.tridactyl

Could you confirm that this is actually a single folder rather than the expected VVV\.tridactyl?

Is your username really VVV or does it have some special characters in?

**Comment by Susexe** [comment]
The folder is in Cyrillic. Damn, that's probably causing issues. When installing Windows, I wrote my username in Cyrillic, and even though I changed it to Latin in local account settings, it didn't change the folder name. I guess there's a way to rename it without formatting my PC, I'll have to google it.

**Comment by bovine3dom** [comment]
It is probably something we can fix at our end. @gsbabil is there anywhere that Cyrillic characters might make the PowerShell script fall over?

**Comment by Susexe** [comment]
I formatted my PC, set a standard username without any special characters, and tried again. Still the same thing.

```
[+] Looking for Python 3 ...
    - Python 3 not found, will use EXE ...
[+] Preparing C:\Users\VVV\.tridactyl ...
    - C:\Users\Maja\.tridactyl exists, moving on ...
    - Testing C:\Users\VVV\.tridactyl was successful!
    - Creating C:\Users\VVV\.tridactyl was successful!
[+] Downloading https://tridactyl.cmcaine.co.uk/betas/native_main.exe ...
    - Testing C:\Users\VVV\.tridactyl\native_main.exe was successful!
    - Creating C:\Users\VVV\.tridactyl\native_main.exe was successful!
[+] Preparing C:\Users\VVV\.tridactyl\native_main.bat ...
    - Testing C:\Users\VVV\.tridactyl\native_main.bat was successful!
    - Creating C:\Users\VVV\.tridactyl\native_main.bat was successful!
[+] Downloading https://raw.githubusercontent.com/cmcaine/tridactyl/master/nativ
e/tridactyl.json?1531495658,27452 ...
    - Testing C:\Users\VVV\.tridactyl\tridactyl.json was successful!
    - Creating C:\Users\VVV\.tridactyl\tridactyl.json was successful!
    - Patching C:\Users\VVV\.tridactyl\tridactyl.json was successful!
[+] Adding registry key HKCU:\Software\Mozilla\NativeMessagingHosts\tridactyl ..
.
    - Adding registry was successful!
[+] Cross-checking everything ...
    - Testing C:\Users\VVV\.tridactyl\tridactyl.json was successful!
    - Testing C:\Users\VVV\.tridactyl\native_main.exe was successful!
    - Testing C:\Users\VVV\.tridactyl\native_main.bat was successful!
[+] Getting (Default) registry value HKCU:\Software\Mozilla\NativeMessagingHosts
\tridactyl ...
[+] Getting registry key HKCU:\Software\Mozilla\NativeMessagingHosts\tridactyl .
..
[+] Installation successful!
    - Run ':native' in Firefox to cross-check. :-)
```
(I just realized the missing backslash in the previous post was due to GitHub screwing it up. I put this one in the code tag.)

**Comment by bovine3dom** [comment]
Do you have any kind of anti-virus?

My current suspicion is that something is stopping the executable from running.

**Comment by Susexe** [comment]
I don't. Even Windows Defender is turned off.

The first thing I did after formatting was install Firefox, a new version of PowerShell and execute the code. It's probably a bug. Can I provide you with a log or something?

**Comment by Susexe** [comment]
I tried running native_main.exe manually, and the following error appears:

> Error loading Python DLL 'C:\Users\VVV\AppData\Local\Temp\_MEI24082\python35.dll'.
> LoadLibrary:

**Comment by bovine3dom** [comment]
How are you running it? It should just hang and wait for messages, so that doesn't sound good.

If you have Cygwin or MSYS2 etc installed, you can check that it is working with
``` 
printf '3\0\0\0{"cmd": "run", "command": "printf hello"}' | ./native_main.exe
```

If you don't, you can still test it by working out what the equivalent of printf is in Windows : )

**Comment by bovine3dom** [comment]
Some other people suggest you might have luck with VC 2015: https://www.microsoft.com/en-US/download/details.aspx?id=48145

Source: https://github.com/mitmproxy/mitmproxy/issues/1763

**Comment by glacambre** [comment]
If it's a missing DLL problem, couldn't we statically compile the binary? It'd make sense since the executable is supposed to be a hassle-free solution.

**Comment by Susexe** [comment]
> How are you running it?

Via command prompt.

> printf '3\0\0\0{"cmd": "run", "command": "printf hello"}' | ./native_main.exe

It outputs the same error.

I tried VC 2013, 2015 and 2017 (both architectures), non of them fixed the problem.

**Comment by bovine3dom** [comment]
: (

I'm out of ideas. It could be because we cross-compile under Wine. #620 might fix it.

@gsbabil wrote most of the Windows native code, so he might have a better idea of what's going on.

**Comment by Susexe** [comment]
I can wait. I already went hardcore by formatting my PC, Let's just hope this gets fixed. :)

**Comment by Susexe** [comment]
> Could you please post the contents of the following files:

```
{
    "name": "tridactyl",
    "description": "Tridactyl native command handler",
    "path": "native_main.bat",
    "type": "stdio",
    "allowed_extensions": [ "tridactyl.vim@cmcaine.co.uk","tridactyl.vim.betas@cmcaine.co.uk" ]
}

```
```
@echo off
call .\native_main.exe
```

> Open a fresh PowerShell Instance, run the following commands, and
> share the output:

```
Error loading Python DLL 'C:\Users\VVV\AppData\Local\Temp\_MEI40042\python35.dll'.
LoadLibrary:
```
Hash: FB38341A64E4AFBE2F1AE0CC53538446932006CB4B7FCCA1D06A201E2C252110

> In order to isolate this, @Susexe, could you please try things
> under a ASCII-only user account?

I did.

**Comment by gsbabil** [comment]
Hi @Susexe

Thanks for the details above.

The issue quite positively does not seem to be related to non-ASCII
path in this case, and only seems to be related to the compiled
`native_main.exe` on your Windows system.

1. For completeness, could you please share your Windows version.
   You can use the following PowerShell command to retrieve the
   details:

```
[System.Environment]::OSVersion.Version
```

2. I'm adding a new `native_main.exe` compiled on Windows 10 (build
   17134). Please replace the current `native_main.exe` (with hash
   [0]) with the new `native_main.exe` attached below, and then run
   the following commands again:

```PowerShell
cd $env:USERPROFILE\.tridactyl
Get-ChildItem
Get-FileHash .\native_main.exe
PowerShell -NoProfile -InputFormat None -NonInteractive -Command "[System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('FgAAAA0KeyJjbWQiOiAidmVyc2lvbiJ9DQo=')).trim(`n)" | .\native_main.exe

```

If you see `{"version": "0.1.6"}` in the output, you should be able
to run `:native` and other native-messenger commands in Firefore >
Tridactyl command-bar.

#### ## New `native_main.exe`

- New `native_main.exe` (zipped): https://github.com/cmcaine/tridactyl/files/2195212/native_main.zip
- New `native_main.exe` SHA-256 hash: `AE9065D162A8BF264E603F8DECA7F3F68B465580EBBEC3409ADF73B8B27170EF`
- VirusTotal submission of the above `native_main.exe`: https://www.virustotal.com/#/file/ae9065d162a8bf264e603f8deca7f3f68b465580ebbec3409adf73b8b27170ef/detection

Hope this helps. Thanks.

P.S.

The new `native_main.exe` was compiled with the following
PyInstaller command under Python 3.6 on Windows 10:

```PowerShell
cd $env:USERPROFILE\.tridactyl
pyinstaller `
  --clean `
  --console `
  --onefile `
  --noupx `
  --noconfirm `
  --log-level=ERROR `
  --workpath . `
  --distpath . `
  native_main.py
```

[0] FB38341A64E4AFBE2F1AE0CC53538446932006CB4B7FCCA1D06A201E2C252110

**Comment by bovine3dom** [comment]
We can close this issue once we release the Nim messenger for Windows
