### ISSUE TITLE
Tridactyl is unreponsive until tab reload sometimes

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#804]
@antonva suggested it happens when you unfocus a Firefox window and then re-focus it again.

It would be good to get steps to reproduce this.

I've given this a P1 tag because I think this is probably the kind of jank that will put people off Tridactyl the most.

**Comment by antonva** [comment]
I've deleted my profile and set up a new to try and catch this. I'll try to see if I can get some log information if it happens again.

**Comment by glacambre** [comment]
This is 100% reproducible by opening `http://example.org` in a new tab and using `:tabdetach`.

I think the problem is that the firefox window is selected but the page isn't, which means that Tridactyl doesn't receive inputs.

**Comment by bovine3dom** [comment]
I think that sometimes clicking in the page doesn't fix it. I'll try it next time I notice it in the wild.

**Comment by antonva** [comment]
To further describe the symptoms I've encountered:

Cycling through tabs with `gt` or `gT` will sometimes land me on a page that simply won't respond to tridactyl keystrokes.
This suggests to me that this is different from what @glacambre describes. 
My current solution is to use `^r` to reload the page and tridactyl with it.
There's seemingly no pattern to it, sometimes the tabs are clustered together, sometimes not.

**Comment by glacambre** [comment]
Could they be tabs from an earlier session that were restored by firefox? Could be related to https://github.com/cmcaine/tridactyl/issues/389 .

**Comment by antonva** [comment]
It could have been. I usually have a truckload of tabs open and who knows if they weren't from an earlier session or not. The new profile has the option mentioned in #389 to `true` so we'll see if that fixes this or not.

**Comment by bodograumann** [comment]
When I encounter this, I usually press F6 a few times and tridactyl works fine again. So a reload is not necessary in my experience.
Also I remember this was already an issue with vimperator. In that case I didn't know of F6 and did do the reload. Of course for vimperator the cause might have been completely different from the current problem.

**Comment by bovine3dom** [comment]
I caught it in the wild within the same window where clicking in the window doesn't fix it.

**Comment by bovine3dom** [comment]
`set logging.messaging debug`

Logs from pressing `j`:

```
{
  "type": "commandline_background",
  "command": "allWindowTabs",
  "args": []
}
{
  "type": "commandline_background",
  "command": "currentWindowTabs",
  "args": []
}
{
  "type": "browser_proxy_background",
  "command": "shim",
  "args": [
    "contextualIdentities",
    "get",
    [
      "firefox-default"
    ]
  ]
}
{
  "type": "browser_proxy_background",
  "command": "shim",
  "args": [
    "windows",
    "getAll",
    []
  ]
}
{
  "type": "browser_proxy_background",
  "command": "shim",
  "args": [
    "contextualIdentities",
    "get",
    [
      "firefox-default"
    ]
  ]
}
{
  "type": "browser_proxy_background",
  "command": "shim",
  "args": [
    "contextualIdentities",
    "get",
    [
      "firefox-default"
    ]
  ]
}
{
  "type": "browser_proxy_background",
  "command": "shim",
  "args": [
    "contextualIdentities",
    "get",
    [
      "firefox-default"
    ]
  ]
}
{
  "type": "browser_proxy_background",
  "command": "shim",
  "args": [
    "contextualIdentities",
    "get",
    [
      "firefox-default"
    ]
  ]
}
```

(last object is repeated approx 100 times)

On page https://github.com/cmcaine/tridactyl/pull/637

(and I just fixed it by pressing Ctrl-L to copy that URL...)

Compared with healthy page:

```
{
  "type": "keydown_background",
  "command": "recvEvent",
  "args": [
    {
      "shiftKey": false,
      "metaKey": false,
      "altKey": false,
      "ctrlKey": false,
      "repeat": false,
      "key": "j",
      "bubbles": true,
      "composed": true,
      "defaultPrevented": true,
      "eventPhase": 1,
      "timeStamp": 7957125,
      "type": "keydown",
      "isTrusted": true,
      "target": {
        "nodeName": "BODY",
        "nodeValue": null,
        "nodeType": 1,
        "namespaceURI": "http://www.w3.org/1999/xhtml",
        "prefix": null,
        "localName": "body",
        "baseURI": "https://github.com/cmcaine/tridactyl/pull/637",
        "textContent": "<snip> this was actually the entire page </snip>"
        "tagName": "BODY",
        "contentEditable": "inherit",
        "isContentEditable": false
      }
    }
  ]
}
{
  "type": "browser_proxy_background",
  "command": "shim",
  "args": [
    "tabs",
    "query",
    [
      {
        "active": true,
        "currentWindow": true
      }
    ]
  ]
}
{
  "type": "browser_proxy_background",
  "command": "shim",
  "args": [
    "sessions",
    "getTabValue",
    [
      1,
      "jumps"
    ]
  ]
}
{
  "type": "browser_proxy_background",
  "command": "shim",
  "args": [
    "tabs",
    "query",
    [
      {
        "active": true,
        "currentWindow": true
      }
    ]
  ]
}
```
(last two objects repeated approx 6 times in total)

**Comment by glacambre** [comment]
The only piece of code that calls `allWindowTabs` in the `BufferAll.ts` completion source. For them to be triggered, the command line would have to be focused, which would explain why clicking in the window doesn't fix it. Why it isn't shown is a mistery. If you manage to reproduce this bug, could you test whether using `<Esc>` fixes Tridactyl?

I'm not sure how we could fix this. This might be a race condition where Tridactyl tries to open a website and the commandline at the same time (like https://github.com/cmcaine/tridactyl/issues/784#issuecomment-405613562 ?). What would happen is that the command line is opened, the website is loaded and then Tridactyl tries to focus the commandline.

**Comment by bovine3dom** [comment]
On the plus side, it happened to me about four times today, so I'll probably see it again soon... I'll try pressing escape. I avoided doing that today because I was trying not to fix it on purpose.

**Comment by bovine3dom** [comment]
`<Esc>` does fix it, @glacambre.

**Comment by glacambre** [comment]
It's most probably the issue I described then. This might be fixed by implementing https://github.com/cmcaine/tridactyl/issues/434 or https://github.com/cmcaine/tridactyl/issues/639.

**Comment by antonva** [comment]
I have a feeling that this might be 2 separate issues then. I've had the same symptoms where `<ESC>` does nothing.

**Comment by glacambre** [comment]
Yeah I think we actually have three different bugs in this issue:
1) https://github.com/cmcaine/tridactyl/issues/804#issuecomment-404836229
2) https://github.com/cmcaine/tridactyl/issues/804#issuecomment-404871801
3) https://github.com/cmcaine/tridactyl/issues/804#issuecomment-405729272

**Comment by bodograumann** [comment]
I agree with @antonva. When you detach a tab (by dragging or with the commandline), tridactyl becomes unresponsive and `<Esc>` does not help. Pressing three times `<F6>` or clicking with the mouse inside the window works. So this is probably what @glacambre described in https://github.com/cmcaine/tridactyl/issues/804#issuecomment-404836229

**Comment by bovine3dom** [comment]
Steps to reproduce the "unresponsive where `<Esc>` fixes it" one:

```
:tabopen about:addons<CR>
<C-S-Tab>
```

:D

**Comment by glacambre** [comment]
Note: This is only reproducible on slow computers. If you're on linux, you can run `cpufreq-set -c CPU_NUMBER -u MINIMAL_SPEED_SUPPORTED_BY_YOUR_CPU MHz` to slow your computer down.

**Comment by bovine3dom** [comment]
> only reproducible on slow computers

It's not my fault no-one makes laptops with nice keyboards any more : (

**Comment by glacambre** [comment]
Slow computers are good, they help us find race conditions :D

**Comment by osleg** [comment]
Not a slow computer here but it does happen.
It does seem like the content is not focused hence tridactyl failing to work.
Sometimes <Esc> helps, when <Esc> doesn't help hitting <Tab> and then <Esc> works in 99%... which adds up to the idea of lost focus.
This happens at most for me when I'm using custom userChrome, where my tabs and loc bar are at bottom of the screen. When vanila userChrome is used it almost never happens

**Comment by madduck** [comment]
I feel like half the time I interact with a tab, I have to press a combination of `F6` and click with the mouse, in order to be able to even start using Tridactyl keys, which is a huge nuisance. Is this the right issue for this (it somehow seems related, but I also think the issues discussed here are sundry and conflated), or should I file a new one about how we really need to improve this user experience?

**Comment by bovine3dom** [comment]
Closing as I think this is fixed in betas and this issue is cluttered. Please do file a new issue if the issue persists in betas.
