### ISSUE TITLE
Domain/tab-local settings and keybindings

### ISSUE THREAD

**Issue by noctuid** [tridactyl/tridactyl#808]
Tab-local settings are mentioned in #434, but I couldn't find a dedicated issue.

For me this has always been one of pentadactyl's most useful features (the documentation for groups is in [repeat.xml](https://github.com/5digits/dactyl/blob/master/common/locale/en-US/repeat.xml)). Basically you create a group like this:
```
group image -description "Image viewing mappings" -locations .*\.jpg,.*\.jpeg,.*\.png,.*\.gif
" can now bind keys for that group only
nmap -group image -builtin y ZI
nmap -group image -builtin u ZO
```

This isn't the best example since it works inconsistently depending on the url name, but there are a lot of use cases for site-local settings/keybindings:

- use website's builtin shortcut keys (e.g. gmail; related: #57) or added shortcut keys (e.g. some greasemonkey user scripts or addons like RES) without the need for a custom mechanism for site-specific passkeys
- custom keybindings for these builtin/added shortcut keys by using `:feedkeys` or `xdotool` (is there an open issue for something like pentadactyl's `:feedkeys` or qutebrowser's `:fake-key`?)
- custom per-site navigation keybindings (e.g. you can reuse some prefix across sites for "domain-local" quickmarks; e.g. `,i` for gmail might go to the inbox, and `,s` might go to starred)
- with #468 implemented, users who use a security/privacy-focused about:config that breaks some websites (e.g. banking websites) could enable some settings only for certain websites
- there are of course many other settings that are useful to be changed only for certain tabs

Qutebrowser has a custom system for domain-local settings, but combining tab-local settings/keybindings and autocommands would be more flexible since there are potentially other events the user might want to change settings or keybindings for (definitely if there was tabgroup support with a corresponding switch autocommand and maybe for `au Private` or `au ShellCmdPost`if they existed). Using autocommands to set things locally would probably require #650 fixed to be sane.

I think it's probably not necessary to replicate pentadactyl's group feature. Some differences from using autocommands and local keybindings:
- pentadactyl has several builtin/special groups (e.g. one for the commandline)
- multiple groups can be active on a website (assuming that autocommand definition order matches execution order after #650 is addressed, this shouldn't matter)

The main issue with pentadactyl's groups is that the site filtering regexp is really limited. You often need multiple groups for the same domain (e.g. keybindings are different for reddit threads and subreddit pages), and pentadactyl's url matching is often hard to work with or not good enough to distinguish between these contexts. It looks like tridactyl supports full regexes based on the link in the docs?

**Comment by glacambre** [comment]
`:seturl` is available in the betas and I think does exactly what you need. You can use it like this: `seturl \(.*\.jpg\)|\(.*\.jpeg\)|\(.*\.png\)|\(.*\.gif\) nmaps.zi zoom 0.1 true` in order to bind `zi` to `zoom 0.1 true` on urls ending with one of the specified extensions.
Please note that the pattern you give to seturl can't contain spaces.

**Comment by bovine3dom** [comment]
Closing as added in #999. (Thanks to glacambre and saulrh).

**Comment by noctuid** [comment]
Thanks a ton. I will try this out when I get a chance. 

I have a couple of questions: 

- What determines precedence when multiple patterns match (order defined  = order settings applied would be nice; this is useful on a lot of sites, for example on reddit to distinguish between a page listing threads and a page showing a single thread)?
- What is used for the pattern (is it a small subset of regexp syntax like pentadactyl had or "real" regexps)?

> Please note that the pattern you give to seturl can't contain spaces.

Do you mean that it can't have escaped spaces or just that a space ends separates the pattern arg from the remaining args?

**Comment by bovine3dom** [comment]
- I can't remember, @glacambre might know. I remember it being discussed.
- Javascript regex (String.match())
- The space separates the pattern arg from the remaining args. See #789 for progress on fixing that.

**Comment by glacambre** [comment]
>What determines precedence when multiple patterns match

There is a "priority" setting you can set, e.g. `seturl .*\.org priority 5` `seturl example.org priority 20`, the setting with highest priority is chosen. Wen you don't specify an url-specific config's priority it defaults to 10 and if two configs have the same priority that's undefined behavior (but I think lexicographical order of the patterns might be used).

**Comment by noctuid** [comment]
> The space separates the pattern arg from the remaining args

Does that include even escaped spaces
```
\ 
```
?

> There is a "priority" setting you can set

Is only the one with the highest priority used (e.g. what if I want to have some site wide defaults but change or just add to those settings depending on the specific page)?

**Comment by bovine3dom** [comment]
To the first point: yes, we don't have any concept of escaping stuff yet.

I'm not familiar with the priority.

**Comment by glacambre** [comment]
>Is only the one with the highest priority used

No, you can for example have `:seturl .*\.fr followpagepatterns.next suivant` and `:seturl france.fr allowautofocus false`, both settings will be applied. You can even `:seturl france.fr followpagepatterns.next après` but then you'll need to make sure than `france.fr` also has a higher priority setting.

**Comment by noctuid** [comment]
Thanks, that's perfect.
