### ISSUE TITLE
Editorcmd FAQ and documentation.

### ISSUE THREAD

**Issue by antonva** [tridactyl/tridactyl#814]
This is one of the selling points of the native messenger. We should document it  better and have examples and faqs available for different operating systems etc.

**Comment by antonva** [comment]
**Windows:**
* To spawn vim.exe with cmd.exe: `set editorcmd start cmd.exe /c \"vim\"` -via @Susexe on matrix.

**Comment by bovine3dom** [comment]
I think there's another issue for this. Someone was saying it was poorly documented. Could just have been on Riot.

**Comment by antonva** [comment]
There's #782 which kinda mentions the same thing.
