### ISSUE TITLE
support Ctrl-[ as alternative to Esc

### ISSUE THREAD

**Issue by m0tive** [tridactyl/tridactyl#82]
In Vim you can do <kbd>Ctrl</kbd>-<kbd>[</kbd> as an alternative to <kbd>Esc</kbd>. Tridactyl doesn't seem to support this.

**Comment by lhyaax** [comment]
I need the mappings too.

**Comment by bovine3dom** [comment]
@cmcaine: Would you mind briefly looking at 4b3ec57? I can't quite get my head around all of the places I need to suppress `Ctrl-[` which is bound to back by default.

**Comment by hppavilion1** [comment]
Last time I checked, the codebase doesn't currently support modifiers (other than shift) in bindings.

**Comment by bovine3dom** [comment]
@hppavilion1 That's only in `normal` mode. Every other mode is much more hard coded, so we can write whatever we want in.

The code I referred to above works, but also triggers the Firefox back action.

**Comment by bovine3dom** [comment]
This is partially possible now:

`bind --mode=insert <C-[> unfocus`
`bind --mode=input <C-[> unfocus`

Bindings for the command line are still not user configurable, I'm afraid.
