### ISSUE TITLE
GitHub "integration"

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#823]
a.k.a I have commit access so I can add all the bloat I want, or "hub doesn't work on my PC any more"

I just added 

```js
bind yp composite js document.getElementById("clone-help-step-1").textContent.replace("git checkout -b", "git checkout -B").replace("git pull ", "git fetch ") + "git reset --hard " + document.getElementById("clone-help-step-1").textContent.split(" ")[3].replace("-","/") | yank
```

to .tridactylrc, but a) that's ugly, b) it only works for collaborators, and c) I'd like to have it correctly set the upstream. Currently I have to do e.g:

`git push --set-upstream git@github.com:gsbabil/tridactyl.git gsbabil-gsbabil/add-appveyor-windows-build-support:gsbabil/add-appveyor-windows-build-support`

i.e. `git push --set-upstream [repo address] [my branch]:[his branch]`.

GitHub has a pretty sensible API IIRC, so we should probably use that to solve b).

**Comment by glacambre** [comment]
I have the following settings in my tridactylrc:
```
alias gitclone jsb -p tri.native.run("git clone '" + JS_ARG + "' /home/me/prog/" + JS_ARG.split("/").slice(-1))
bind gc composite js window.location.href | gitclone
bind ;gc hint -qW gitclone
```
Potentially dangerous if someone manages to put a quote in the repository url I'm trying to clone but mostly harmless otherwise.

**Comment by bovine3dom** [comment]
`hub` has been working pretty reliably, and we have `issue`, so I'm closing this.
