### ISSUE TITLE
Document how to fix broken sites better

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#824]
- `set csp untouched`
- `set modeindicator false`
- `set noiframeon [space separated urls]`

The first two should probably be per-site settings.

- Add a page for page alteration to tutor describing these settings, and include `set csp` and `fixamo`.
- Mention on newtab / readme / help page

**Comment by glacambre** [comment]
Related issue: https://github.com/cmcaine/tridactyl/issues/578.

**Comment by glacambre** [comment]
Per-site settings work and the troubleshooting guide which mentions `set csp` is mentioned in `clippy/8-help.md` so is there anything left to do before closing this issue?

**Comment by bovine3dom** [comment]
It might be worth linking to the troubleshooting guide from the start of the help page and/or new tab page, as we still get quite a few people coming to us with issues that are resolved by the guide.
