### ISSUE TITLE
relative tabmove doesn't like completions

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#825]
I was going to fix this but the completions are too messy.

`tabmove +1` gets turned by completions into `tabmove 1`. Workaround is to use ` tabmove +1`.

**Comment by glacambre** [comment]
Do you also get an error stating `# Error: Type error for parameter moveProperties (Error processing index: Expected integer instead of null) for tabs.move. ` or is this something specific to my configuration?

**Comment by bovine3dom** [comment]
I don't recall seeing that.
