### ISSUE TITLE
Fix fallback heredoc return code

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#835]
As per https://github.com/cmcaine/tridactyl/commit/1d69d86c4d15a970f94a8abb5b75a9fdd835225e

**Comment by glacambre** [comment]
I think we can just remove the fallback. Betas are made to be broken, if removing the fallback breaks something for someone we can just tell them to upgrade their native messenger.

**Comment by bovine3dom** [comment]
Eh, no-one has mentioned this for over a year so we probably don't need to bother adding the fallback.
