### ISSUE TITLE
`nativeopen` can make Tridactyl appear unresponsive

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#836]
Hived off from #804.

Steps to reproduce on Linux (apparently on a slow machine):

```
:tabopen about:addons<CR>
<C-S-Tab>
```

On Windows, I find that focus seems to leave the Firefox window entirely - Ctrl-Tab doesn't work.

Suggested solution could be to try extra hard to close and unfocus the commandline when `nativeopen` is run.

Probably also worth doing a `git bisect` to see if it was introduced by e.g, fillcmdline_tmp.

**Comment by glacambre** [comment]
Bisect not needed, I can reproduce this issue on adc91d6 (the commit right after nativeopen was implemented).

**Comment by bovine3dom** [comment]
Fixed in #1044 as far as I can tell.
