### ISSUE TITLE
Make a Tridactyl GitHub organisation?

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#853]
Would make #852 easier as we could have tridactyl.github.io. Generally many people say having a good website is very important for software.

Also make clear that this isn't a one-man-band.

Increase bus survivability as can give more permissions to people than currently possible.

Downsides:
Lose Google ranking?
?

**Comment by glacambre** [comment]
Why would having a website lower our Google ranking? Wouldn't having a real website instead of just a github repo improve our ranking?

**Comment by antonva** [comment]
Initially we'd have a lower google ranking on the new repo which would be under github.com/tridactyl/tridactyl is how I read it.

I don't really think that it outweighs the pros of this.

**Comment by glacambre** [comment]
If we had a website we could probably also embed a demo of Tridactyl with basic features such as keyboard navigation/opening tabs from the command line.

**Comment by bovine3dom** [comment]
So long as you can navigate to the Tridactyl demo in the Tridactyl demo. We need to support infinitely-nested Tridactyls.

**Comment by glacambre** [comment]
I don't really care about where the repo sits. Having an organization would be useful if there are features only available to organizations that we could use. I think I remember reading that organizations let you add rules such as "allow contributors to merge PRs but not their own", which I believe could be useful here to both enforce code review and to delegate responsibilities without giving too much power to others.

**Comment by bovine3dom** [comment]
I think it's probably a little bit fairer to have it as tridactyl/tridactyl given the breadth of collaboration. I find it hard to believe that anyone would think less of it compared to cmcaine/tridactyl given that most properly successful projects are owned by organisations.

It would also be nice to give people little badges that mean that they can conduct official reviews on PRs, as glacambre says.

I'd also like to get my hands on the repo settings so that I don't have to wait for you to get around to looking at e.g, #637.

These are pretty minor concerns though. @cmcaine, you should ask some people wot have hired you whether they would care.

**Comment by antonva** [comment]
I support a Sid Meier style rebranding effort.

**Comment by bovine3dom** [comment]
Tridactyl's C M Caine?

I'll chip in towards the deed poll.

**Comment by ELLIOTTCABLE** [comment]
Colindactyl.

**Comment by cmcaine** [comment]
Done.

Please report any actionable problems with the transfer as new issues referencing this one. Unactionable problems should be listed here.

1. Issue 'updated' time is wrong
