### ISSUE TITLE
Incompatible with the Multi-Account Containers extension

### ISSUE THREAD

**Issue by ghost** [tridactyl/tridactyl#883]
I can open an [alternative account container tab](https://github.com/mozilla/multi-account-containers/) fine, but when I enter a URL it switches back to the default container.

Maybe you could add an optional toolbar button to quickly toggle off Tridactyl when I want to use an alt account briefly?

**Comment by antonva** [comment]
It's related to #882.

**Comment by bovine3dom** [comment]
Not actually fixed - autocontain still incompatible with MAC but at least it won't break until you try to use autocmd.

**Comment by bovine3dom** [comment]
I reckon @antonva fixed this a while ago.
