### ISSUE TITLE
Firefox 52 ESR support ends soon - let's have a sprint

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#903]
It looks like 52 will be dropped on 5th September: https://wiki.mozilla.org/Release_Management/Calendar

I think we have a good chance of picking up some more refugees, so I'd like to try to make Tridactyl a little less bad by then.

I don't think we'll manage to get the mythical #434 in that time but I think we could probably make the command line and completions much less janky, and sort out native performance #637 (and have a coup with #853 so that I can actually do that).

I'm going to be quite busy with actual work but I'd be happy to work on stuff wherever I can squeeze it in.

@glacambre, @antonva, I think you are the prime suspects for actually getting stuff done - we should organise a bit better in the short term if that's OK.

NB: I don't know what a sprint actually is

**Comment by antonva** [comment]
I have some time to spare to help with this. Just point me at what needs doing.

I currently have that `:mktridactylrc` branch live as well as some futile attempts at e2e testing (read: I suck at Selenium and Karma doesn't work with FF v61 and up.)

The mktridactylrc stuff could be finished in a few hours.
