### ISSUE TITLE
Breaks flight leg selection on qantas.com

### ISSUE THREAD

**Issue by madduck** [tridactyl/tridactyl#906]
Note: I have tried all the "Settings that can fix websites", but the problem prevails.

This is using Tridactyl 1.13.1 on FF 60.0 on Linux (Debian unstable).

When I try to book a flight on qantas.com, clicking on the price (see screenshot) does not yield any result. This means I cannot actually select a flight, or move on.
![screenshot-2018-8-13 flightbookings - select flights](https://user-images.githubusercontent.com/195073/44007420-1e95a41c-9ee9-11e8-9b8f-bd93899df1ab.png)

I have to disable Tridactyl in the add-ons page, reload the page, and then I can successfully select the flight (i.e. it opens up the far conditions and adds the leg to the itinerary:
![screenshot-2018-8-13 flightbookings - select flights 1](https://user-images.githubusercontent.com/195073/44007430-5bb1623c-9ee9-11e8-88e9-9913e992f1c4.png)

I do not have a config file, and here are [the config data you requested](https://scratch.madduck.net/2018-08-13-111339-paste-MZYc7g.txt).

**Comment by bovine3dom** [comment]
Can't reproduce on `1.13.2-16-g263b4d3`. Could you check again on 1.13.2?

**Comment by madduck** [comment]
Thanks @bovine3dom for looking into this. Unfortunately, the issue is still there wit 1.13.2. I do use a slew of other add-ons, too, but I've selectively enabled/disabled them all to figure out where the problem lies, and it is definitely Tridactyl, i.e. 100% — when I enable Tridactyl, the problem exists, and if I disable it, then the problem goes away.

**Comment by bovine3dom** [comment]
Strange. Could you perhaps try a fresh profile or Firefox 61?

**Comment by bovine3dom** [comment]
> I cannot reproduce this with a fresh profile and only Tridactyl installed, of course.

That's good - the problem is in your profile somewhere. I'll have a look at your config when I'm at a desktop.

If you back up your Firefox profile, you could try `sanitise tridactylsync`, restart and see if that fixes it. If that doesn't, do `sanitise tridactyllocal`, restart and try again. Please tell us which if any fixed it - local and sync store different things so it will help to narrow it down.

**Comment by madduck** [comment]
Sanitising `tridactylsync` seems to have fixed it!!

So now that I have the backup and this profile, should we even bother trying to find out the problem?

**Comment by bovine3dom** [comment]
Yes!

You shouldn't be able to break websites in weird ways without realising it.

`sync` basically just stores the config so it's something in there, probably.

**Comment by bovine3dom** [comment]
One strange thing in your config: 

nmaps: `"undefined": "",` - this looks like literally the sequence of keys `u n d e f i n e d`, but it is bound to a no-op, so nothing bad should happen. Still, `reset undefined` might be a good idea. I'm curious as to how this appeared.

Other things that aren't weird but could potentially be causing the bug as they are not default:

```
"noiframeon": [
    "https://**redacted**"
],
```

` "modeindicator": "false",`

So, please restore your profile from backup (and keep the backup where Qantas is broken), then:

1. try to reproduce qantas bug
2. do one of `reset undefined`, `unset noiframeon`, `unset modeindicator`
3. restart firefox, repeat

Please let me know which if any fixes it : )

**Comment by madduck** [comment]
Unfortunately, none of these three seem to play any role.

Meanwhile, I have also confirmed that `sanitise tridactyllocal` is not enough.

**Comment by glacambre** [comment]
@madduck Can you still reproduce this issue?

**Comment by madduck** [comment]
No, I haven't been able to reproduce this, and I've just booked a flight too! Yay!
