### ISSUE TITLE
Sending tabs to other devices via Firefox Sync

### ISSUE THREAD

**Issue by mrjovanovic** [tridactyl/tridactyl#908]
It would be great if we could have a functions to send the current tab to a device connected via Firefox Accounts. The command (e.g. `tab-send`) would then take as an argument the available devices, listed above the command input bar so they can be tabbed through.

Not sure if [this](https://github.com/mozilla-services/firefox-send-tab-to-device/blob/master/lib/main.js) deprecated extension might be of help here.

**Comment by bovine3dom** [comment]
We could cheat using sync storage and a TriStart command with some kind of hostname check.

**Comment by mrjovanovic** [comment]
@bovine3dom 
That wouldn't work for mobile clients though, which for me at least is the primary use of sending tabs to devices..

I guess we can't do much if the API doesn't allow for interaction with FF Sync.

**Comment by bovine3dom** [comment]
Closing this as a web extension limitation.
