### ISSUE TITLE
`guiset gui none` on Firefox 62 has bar at top when maximised

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#923]
There's a 1 or 2 pixel bar showing your theme's background at the top. I imagine this is less annoying if you don't have a ridiculous theme.

**Comment by quinoa42** [comment]
I hadn't encounter this until I upgraded to mac 10.13.6. I don't know about Windows, but on Mac to fix this simply set the `padding-top` in `#main-window[sizemode="maximized"] #content-deck` to `0px`.

**Comment by glacambre** [comment]
Does this still happen on Firefox 65? It looks like Firefox's layout has changed a lot with this version.

**Comment by bovine3dom** [comment]
Still there on Windows for me.

**Comment by bovine3dom** [comment]
I've decided that I don't care about this. If anyone else does, just comment and I'll re-open it.
