### ISSUE TITLE
Reverse image search hint mode

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#924]
Google has a secret API here: `images.google.com/searchbyimage?image_url=`

This might not need any new code in Tridactyl, as we can currently do `hint -W open images.google.com/searchbyimage?image_url=` with the caveat that we really want to give it a selector so that it only uses images.

**Comment by glacambre** [comment]
`composite hint -pipe img src | js -p tri.excmds.open("images.google.com/searchbyimage?image_url=" + JS_ARG)` seems to work.

**Comment by glacambre** [comment]
Should we turn this into a default binding, add it to the documentation somewhere (perhaps the tridactylrc in the repo?) or just leave it here for people to find if they happen to look for it?

**Comment by bovine3dom** [comment]
Yeah, let's make it a default bind.
