### ISSUE TITLE
Suggested smaller tasks

### ISSUE THREAD

**Issue by cmcaine** [tridactyl/tridactyl#94]
As a compliment of #90, this is a list of smaller jobs

- [x] `a` bookmarks
- [x] `gi` focus last input
- [x] `;` extra hint modes
- [ ] ~~Bundle a monospace font for windows users (courier is awful)~~
- [ ] Make css for hints and cmdline configurable (on the soon-to-exist options page, I think)

**Comment by reversebreak** [comment]
May I suggest Anonymous Pro for the monospace font?  It's under the OFL.
https://www.marksimonson.com/fonts/view/anonymous-pro

**Comment by bovine3dom** [comment]
We'd left it out on purpose; we just use the default system monospace font.

I'm of the opinion that if you don't like your system monospace font then you should probably change it to something that you do like. Personally, I really like Iosevka for HiDPI displays and Dina for low resolution displays, and I don't want to have to fight with Tridactyl to override that.

I appreciate that Tridactyl isn't fantastic out-of-the-box, but "bad initial experience for long term benefit" is basically Vim's motto. Do you strongly disagree?

I'd be happy to add a point to the FAQ about how to change the font we use.

**Comment by reversebreak** [comment]
Ah, no, I just saw the unchecked box in the list and thought I'd make a suggestion for a nice looking and legally safe one to include.  
Since that decision's changed, the suggestion isn't needed anymore.
