### ISSUE TITLE
Give Native.writePref an ex command

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#940]
We could have something awful like `firefoxset`.

We would need to parse the strings so that booleans / numbers were set correctly, as in e.g,

`Native.writePref("privacy.resistFingerprinting.block_mozAddonManager", true)`

Related: #674

**Comment by glacambre** [comment]
This command was named `:set!` [in pentadactyl](https://github.com/5digits/dactyl/blob/31a6ba0bcbf92bb393a529bde78610ee2297b55c/common/locale/en-US/options.xml#L317-L330). Not a fan of overloading commands with an exclamation mark though, I thing I prefer `firefoxset` or even just `pref`. `pref` used to be `tabopen about:config` in Pentadactyl but I'm not sure it's necessary to maintain compatibility here, I doubt `:pref` was used very often.

**Comment by noctuid** [comment]
`setpref` maybe? I think it would be better to keeo "set" in the name for clarity.
