### ISSUE TITLE
tabopen and hinting navigations should consult autocontain directives

### ISSUE THREAD

**Issue by saulrh** [tridactyl/tridactyl#952]
We have to keep the "hook webRequest.onBeforeRequest, close and reopen in right tab" logic to handle mouse clicks and other navigations, but when tridactyl kicks off a navigation itself it should be able to avoid the open-close-and-reopen dance using the autocontain configuration to set -c automatically.

**Comment by antonva** [comment]
@saulrh  can we close this now #953 is merged?

**Comment by saulrh** [comment]
Oops, yes, this feature was added in #953, and it doesn't depend on the as-yet-unobtained management permission so it actually works.

Fixed by #953.
