### ISSUE TITLE
Did we break Tridactyl on BSD in May?

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#957]
Looking at https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/statistics/usage/os/?last=365

We had about 25 BSD users. Suddenly, around 23rd May 2018, we lost almost all of them. Now we only have about 2.

Anyone have any ideas?

Edit:
My best guess so far is that https://github.com/cmcaine/tridactyl/pull/499 broke tabopen on old Firefox versions. 🤷‍♂️

**Comment by depressed-pho** [comment]
There is currently a strange problem on NetBSD, where trying to use "tabopen" and "open" on any pages other than the Tridactyl home results in ``browserBg.tabs`` being ``undefined`` in ``activeTab()``. Yes, this is unlikely to be your fault and is probably a Firefox bug. I'm having a hard time identifying the real cause...

**Comment by bovine3dom** [comment]
Closing this as `strict_min_version` should prevent most people from updating.

@depressed-pho if you still see that issue please open a new issue or add it to #760.
