### ISSUE TITLE
Update docs for hotkey for a last active tab.

### ISSUE THREAD

**Issue by aleks-m** [tridactyl/tridactyl#975]
It would be nice to have a hotkey for a last **active** tab (not just previous/next/last/first). 
In Vimperator it was a `^` key.

*   Tridactyl version:
1.13.3-1.13.3

**Comment by glacambre** [comment]
Doesn't `<C-^>` do this?

**Comment by aleks-m** [comment]
@glacambre ah, yes, thanks a lot (it just not mentioned in https://github.com/tridactyl/tridactyl#handling-tabs).

**Comment by glacambre** [comment]
Ah, yes, you're right! The readme hasn't been updated in a while, you'll find all default bindings here though: https://github.com/tridactyl/tridactyl/blob/cb9386285c7fdd6a1e4f744d9dc6d21d11581f09/src/config.ts#L106

**Comment by maixiu** [comment]
Hi, i can take this one. Should I also add all other missing ones, or only <C-^> ?
