### ISSUE TITLE
select a text from page without mouse

### ISSUE THREAD

**Issue by irmpow** [tridactyl/tridactyl#977]
# Making a feature request
Hello, have a nice day!
It would be a great pleasure to have feature for selecting text from page. May be in one more mode like hint mode. Feature is to have have blinking cursor, which can be moved with keyboard arrows, PgUp, PgDown, End, Home and so on. When shift is pressed and cursor is moving text on page becomes selected to use c-c to copy it.

If this feature is already availble please write how to use it.

**Comment by glacambre** [comment]
Hi, thank you for opening this issue :)
Unfortunately this is not possible yet, the closest thing we have is `;p`, which will let you copy the content of an HTML element. This is definitively planned though, we even have another issue about it: https://github.com/tridactyl/tridactyl/issues/564

**Comment by cmcaine** [comment]
Have a look for carat mode (or similar name) in Firefox.

It's not vim-like but it does what you're asking for as far as I recall.

**Comment by glacambre** [comment]
>carat mode

Ah, yes, caret mode can be turned on with `<F7>`

**Comment by irmpow** [comment]
Using find spawns caret at needed place, than it can be used. It's awesome! Thanks for help!

**Comment by bovine3dom** [comment]
Also related - #32. Closing in favour of those other issues : )
