### ISSUE TITLE
Override colours from theme

### ISSUE THREAD

**Issue by mox-mox** [tridactyl/tridactyl#978]
*   Tridactyl version (`:version`): 1.13.3-1.13.3

*   Firefox version (Top right menu > Help > About Firefox): 61.0.2 (64-bit)

Is it possible to override the colours provided in the themes without changing the source code?
For example, I would like to change 
```
    --tridactyl-photon-colours-warning-color: #fce19f;
    --tridactyl-photon-colours-warning-background-color: #44391f;
...
    --tridactyl-of-fg: var(--tridactyl-photon-colours-warning-color);
    --tridactyl-of-bg: var(--tridactyl-photon-colours-warning-background-color);
```
to be `#ffffff` and `#000000` instead (or anything that is not yellowish brown...).
I can change the colours in the source code,  but then I would need to maintain my own fork of tridactyl just for a colour change. Also, this would chain me to using the developer version of Firefox or force me to submit my fork to Mozilla for signing, wouldn't it?

**Things I have tried:**
I have tried just copying the relevant segment into my userChrome.css (I have literally tried to understand CSS for the first time today, so this may well be a stupid thing to do) and I have searched the repo to see if there is a highlight command that is just undocumented.

**Comment by glacambre** [comment]
>I have tried just copying the relevant segment into my userChrome.css

I think this should probably work. You might need to add `!important` directives to your rules (e.g. `--tridactyl-header-third-bg: #111 !important;`) in order to make sure they're applied.

>I have searched the repo to see if there is a highlight command that is just undocumented

We have two open PRs for this, https://github.com/tridactyl/tridactyl/pull/865 and https://github.com/tridactyl/tridactyl/pull/609 so this feature is definitively planned but as far as I know there's no way to easily customize your themes with Tridactyl for now.

**Comment by Noexpert** [comment]
@glacambre is this as simple as adding code in userchrome.css?

`.TridactylHintElem {
    background-color: [insert color] !important;
    outline: [insert color] !important;
}

.TridactylHintActive {
	background-color: [insert color] !important;
}`

I've tried but it doesn't seem to work.
Or is this ability yet to be implemented?

Thanks

**Comment by glacambre** [comment]
Ah, that's because it's `userContent.css` rather than `userChrome.css`. I didn't read @mox-mox's message correctly, sorry.

**Comment by Noexpert** [comment]
Thanks.
That worked.

**Comment by glacambre** [comment]
The tricks mentioned in this issue work nicely and `:colors` is now able to read themes from disk if you have the native messenger installer (see `:h colors`) so I'm going to close this issue. Feel free to let us know if there's something left unaddressed in this issue :)
