### ISSUE TITLE
Hint mode style is still present after coming back to the previous page for some links

### ISSUE THREAD

**Issue by guigot** [tridactyl/tridactyl#981]
Hello,

*   Brief description of the problem: 
When I use hint mode to access some links in particular, the hint mode style is still present after coming back to the previous page. Here it is a screenshot to be clearer : https://screenshots.firefox.com/t3snJeZlH7gtSJP2/github.com
I saw this issue only on github.com, for the tab "Issues" and "Pull requests", issues topics...

*   Steps to reproduce:

    1. Use hint mode to access an URL (tab "Issues" on github.com/tridactyl/tridactyl for example)
    2. Come back to the previous page

*   Tridactyl version (`:version`): 1.14.0 (this issue happened in previous versions, saw it for the first time from 1.13.3 I think)

*   Firefox version (Top right menu > Help > About Firefox): 61.0.1

**Comment by bovine3dom** [comment]
I was hoping this would have been fixed in 1.14.0. Thanks for reporting.

**Comment by saulrh** [comment]
Setting back to `normal` mode doesn't do it, since the tri content script appears to restart completely and comes up in normal mode. I think that what's happening is that some single-page apps snapshot the entire DOM when they navigate, _including_ tridactyl's hint elements, and then manually manage and restore those snapshots on navigation, including our hints. I'm basing this on the following observations:
* Tri comes back up in normal mode
* Flipping back and forth between normal and insert/ignore modes doesn't fix the dangling hints
* Flipping into hint-mode and back *does* get rid of the dangling hints

`onBeforeUnload` should be easy enough to support, just need to know what to run on it. I'm trying to figure out what it is in the "enter and then exit hintmode" sequence that kills the dangling hint elements.

**Comment by saulrh** [comment]
Yep, it looks like github's SPA implements "navigation" by mutating the DOM without ever unloading or loading the document. I predict that we'll observe these kinds of issues on most SPAs implemented with a functional-reactive framework. It also looks like I'm completely failing to understand how adding elements to the DOM works; Tridactyl's code says it's adding and placing a bunch of elements for hints, but the inspector says it's actually adding and removing its classes on existing page elements. The delay after a hint selection also means that the SPA swaps out the hinted elements before tridactyl gets around to removing its classes, so when the SPA swaps those elements back in the hint classes are still set.

As evidence, the hints can also be removed by running excmds like this:
```
js document.querySelectorAll(".TridactylHintElem").forEach(elem => elem.classList.remove("TridactylHintElem"))
```

There are a couple of things that'd deal with this:
* Find some events that we can hook to detect navigation-like events like this, and on each of them query the entire document for elements with Tridactyl hint classes and remove them. The query above should be pretty fast, and if we want to specifically target problematic sites we could even implement these as autocmds.
* Make the hinting system use the `CSSStyleSheet` [interface](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet) to add and remove selectors from `static/hint.css` as an additional way to ensure that hints aren't shown when they shouldn't be.

**Comment by glacambre** [comment]
>Tridactyl's code says it's adding and placing a bunch of elements for hints, but the inspector says it's actually adding and removing its classes on existing page elements

Two separate things happen, one is adding the `TridactylHintElem` class in order to turn the hinted element yellow and the other is adding the hints themselves to a div the class of which is `TridactylHintHost` and which is appended at the bottom of the document.

**Comment by saulrh** [comment]
Right, I forgot about the elements for displaying the hint characters. Which explains why those go away but the colors don't.

**Comment by cmcaine** [comment]
We could solve this by finding the coordinates of the elements we want to
hunt and drawing boxes for each one in the div or iframe we control.

But are we making sure we remove hints before clicking them? That would be
an easy fix.

**Comment by saulrh** [comment]
But are we making sure we remove hints before clicking them? That would be an easy fix.

**Comment by saulrh** [comment]
> But are we making sure we remove hints before clicking them? That would be an easy fix.

I was under the impression that we were specifically leaving at least the active hint class around for a bit to give the user visual feedback about a successful navigation. If not, killing hinting ui more aggressively after a success shouldn't be too hard to do.

**Comment by cmcaine** [comment]
We deliberately add a delay between hint selection and hint click in the
vimperator modes, but there's no deliberate delay after hint click.

Could be that we want to leave styles on after a click, but that's not a
deliberate feature of the code as I recall.
