### ISSUE TITLE
Why `:tabopen` and not `:tabnew`?

### ISSUE THREAD

**Issue by elimohl** [tridactyl/tridactyl#982]
It is strange that name of command that opens new tab is different from the same for vim.
Tridactyl version (`:version`): 1.14.0-1.14.0

**Comment by cmcaine** [comment]
They're from vimperator/pentadactyl to fit with :open, :winopen. I don't think anyone thought about it much.

We could alias tabnew to tabopen.

**Comment by bovine3dom** [comment]
Yeah, you just need to add `tabnew: "tabopen",` etc to the exaliases in src/config.ts.

**Comment by glacambre** [comment]
The betas now have a `tabnew` alias. This can probably be closed.

**Comment by glacambre** [comment]
Oh, didn't realize that I had the permissions to do that. Closing :D.

Please let us know if you need anything else :)
