### ISSUE TITLE
Favicons don't seem to work in FF Beta

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#986]
*   Brief description of the problem:
Favicons don't work on the list of buffers

*   Steps to reproduce:

1.  Be on Firefox beta
2. Press `b`

*   Tridactyl version (`:version`): 1.14.0-2-g51fcf8a

*   Firefox version (Top right menu > Help > About Firefox): 63.03b

*   Operating system: Windows 10

(I'm currently stuck on FF beta - I can't downgrade because of the storage stuff)

**Comment by maturanomx** [comment]
Same here with Firefox Developer Edition 63.0b3 (64 bit)
![capture](https://user-images.githubusercontent.com/5768813/45189219-86ba5200-b1fd-11e8-898f-2481bedbf8c2.PNG)

**Comment by bovine3dom** [comment]
This is now in Firefox stable so we should probably investigate it.

**Comment by glacambre** [comment]
This is caused by [html-tagged-template](https://github.com/straker/html-tagged-template/blob/5ca8c682848c0204f994da2f4073596d32e42425/index.js#L31).
