### ISSUE TITLE
Add the Space key is a modifier

### ISSUE THREAD

**Issue by cBournhonesque** [tridactyl/tridactyl#992]
Hi,
In vim, I used the Space key as my leader key, so virtually all my shortcuts (next tab, etc.) use Space as the initial modifier.

Would it be possible to add the Space key as a possible modifier key?
I cannot think about using tridactyl without this feature.

Thank you for your help!

**Comment by glacambre** [comment]
Hi, you can use `<Space>` in order to bind commands to the space key, just like in vim :)

**Comment by saulrh** [comment]
Hmm. I thought that the `<Leader>` key actually worked like a time-limited normal key, not a "hold this to modify other keys" key? Just with a time limit on using it. I don't use the leader key in my own vi bindings, but testing it I think that I can observe a binding like `<Leader>j` being triggered by the following sequence:
```
keydown <Leader>
keyup <Leader>
wait 750 milliseconds
keydown j
```

**Comment by glacambre** [comment]
>I think that that we could support

We already support that, we can just use something like `bind <Space>j tabopen`.

**Comment by cmcaine** [comment]
AFAIK, Leader is not handled very specially by vim's key sequence parser:
any multicharacter map can timeout.

It's just an alias for another key.

**Comment by cmcaine** [comment]
Closing. We're not interested in providing arbitrary key chording. A key sequence `<space>d` is fine.
